### ISSUE TITLE
Recipe Problem: Strange recipe for destroying a block of malachite

### ISSUE THREAD

**Issue by EldrinnElantey** [GTNewHorizons/GT-New-Horizons-Modpack#6908] opened 2020-11-09 03:26 UTC
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Privat Server
#
#### What did you try to do, and what did you expect to happen?
I watched what are the applications of malachite from Biomes o Plenty
#
#### What happened instead? (Attach screenshots if needed)
I found such a strange recipe. In essence, this is the destruction of a small hit block in the Cutting Machine.
![image](https://user-images.githubusercontent.com/46845681/98497098-92ca5000-225c-11eb-90a5-bf9269f5485d.png)
#
#### What do you suggest instead/what changes do you propose?
Restore the recipe as it should be. And if the block cannot be sawed for anything, then delete this recipe

**Comment by Prometheus0000** [comment] 2020-11-09 03:43
Duplicate of #6102. Use search.

**Closed by Prometheus0000** 2020-11-09 03:43 UTC
Labels: Type: duplicate
