### ISSUE TITLE
typing "cre" in nei search bar makes every block go compleletly transparent like air

### ISSUE THREAD

**Issue by lahmacum** [GTNewHorizons/GT-New-Horizons-Modpack#14918] opened 2023-11-21 20:32 UTC
### Your GTNH Discord Username

lahmacun7786

### Your Pack Version

2.4.0

### Your Server

sp

### Java Version

Java 8

### Type of Server

None

### Your Expectation

was messing around in creative and typed in "creative" in nei search bar to find debug power generator 

i am using linux mints latest version and GDlauncher 

### The Reality

every block went clear like air. happens after typing "cre"
before:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/108762888/e0f2dd07-8686-406e-a61a-c084537307cd)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/108762888/adf6aee3-a4d0-4107-b0e5-f8983b51f087)
after:
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/108762888/9932800d-3f12-4c75-a138-0ff1eae467a9)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/108762888/c4679bed-2610-4b53-895c-8c23e2613326)

### Your Proposal

pls make blocks not go clear

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2023-12-01 02:49
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12876 and fixed in dev.

**Closed by chochem** 2023-12-01 02:49 UTC
Labels: Type: bugMinor, Status: Triage
