### ISSUE TITLE
NEI Recipe image for coke oven -- time cost text not clear.

### ISSUE THREAD

**Issue by Gateswong** [GTNewHorizons/GT-New-Horizons-Modpack#9235] opened 2021-12-22 09:38 UTC
### Your Pack Version

2.1.2.1

### Your Server

/

### Your Expectation

The coke oven recipe in NEI doesn't show the time cost properly. Probably change the color to make it more clear.

### The Reality

![image](https://user-images.githubusercontent.com/2586057/147071163-56c2a531-6ab9-46ab-962c-f4c8c144d922.png)

### Your Proposal

The coke oven recipe in NEI doesn't show the time cost properly. Probably change the color to make it more clear.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment] 2021-12-22 12:05
I thought this was fixed in NEI Integrations. Did the pack not pull the latest?

**Comment by bombcar** [comment] 2021-12-22 12:06
http://jenkins.usrv.eu:8080/job/NEI-Integration/lastSuccessfulBuild/artifact/build/libs/NEIIntegration-1.7.10-1.1.3.jar

**Comment by Dream-Master** [comment] 2021-12-22 16:33
![image](https://user-images.githubusercontent.com/2970688/147124960-5e08bf62-f0a3-4d07-bfc9-9eb44b2db73e.png)
![image](https://user-images.githubusercontent.com/2970688/147125014-f84bd07a-9999-489d-9d1a-7bbb0488b3b1.png)

**Comment by Dream-Master** [comment] 2021-12-22 16:34
@bombcar this is not a nei integration issue its a issue with the text color in Railcraft

**Comment by bombcar** [comment] 2021-12-22 16:36
That's the NEI gui there, and @mitchej123 bypassed custom GUI handlers in NEI Integrations I was pretty sure ...

**Comment by Dream-Master** [comment] 2021-12-22 16:36
yes but we using lastest version

**Comment by bombcar** [comment] 2021-12-22 16:39
Yeah which I *think* means whatever override is supposed to happen isn't. Checking config.

**Comment by bombcar** [comment] 2021-12-22 16:41
![image](https://user-images.githubusercontent.com/533931/147126088-694a8c26-7273-47d9-b500-a06697aff5cf.png)

this seems ... strange

**Comment by bombcar** [comment] 2021-12-22 17:10
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9054 but I guess it hasn't been resolved yet

**Closed by bombcar** 2021-12-22 17:10 UTC
Labels: Type: Duplicate, Type: bugMinor
