### ISSUE TITLE
Drawer + Hopper voiding items

### ISSUE THREAD

**Issue by hucking** [GTNewHorizons/GT-New-Horizons-Modpack#7778] opened 2021-04-07 11:14 UTC
#### Which modpack version are you using?
2.1.0.5
#
#### If in multiplayer; On which server does this happen? 
Jimmy's Server
#
#### What did you try to do, and what did you expect to happen?
I put a drawer on top of a hopper, I expect it to stop trying to put items in when the hopper is full.
#
#### What happened instead? (Attach screenshots if needed)
The items that tried to go into the hopper once it was full got voided.
#
#### What do you suggest instead/what changes do you propose?
I don't know what causes this but would be nice if this would be fixed or at least disable the functionality of hoppers with drawers because voiding items is never fun. For now we've decided to either use different mote of transportation or use barrels since they don't seem to void items when connected to hoppers.
#
#### What is your GTNH Discord username?
Hucking#0193

**Comment by Prometheus0000** [comment] 2021-04-07 12:27
Duplicate of #2073, #4076, #5086. @johnch18 You were doing something with SD, right? Do you feel like fixing this? We already have a warning in the QB about this, and that's sufficient, but if can fix it, that would be better.

**Comment by hucking** [comment] 2021-04-07 12:28
oh sorry those are all closed so i didn't find it in my search

**Comment by johnch18** [comment] 2021-04-07 13:40
I could take a look

**Comment by Glease** [comment] 2021-12-23 10:38
Copying info from Skiftcha in #8400

> looks like problem is in minecraft hopper code and this [GTNewHorizons/StorageDrawers@`4392b15`/src/com/jaquadro/minecraft/storagedrawers/inventory/StorageInventory.java#L161](https://github.com/GTNewHorizons/StorageDrawers/blob/4392b1538151bdbcfd43991e5b13fccd0c709ee2/src/com/jaquadro/minecraft/storagedrawers/inventory/StorageInventory.java#L161) it gets outstack of drawer (e.g. 64 items), remember it do decrStackSize(stack, 1) so outstack is now 63 and if it cannot put item in hopper makes setInventorySlotContents back to remembered stack with size 64 but between decreasing and setting stack back drawer does syncInventory() so outstack is already 64 and setting it back to 64 does nothing
> 
> btw this line is added to prevent some dupe

**Comment by Glease** [comment] 2022-04-05 07:03
Retagging this to bugMajor, as this bug is just so annoying, and more than enough people have been caught in it.

**Closed** 2022-04-08 04:46 UTC
Labels: Type: bugMajor, Mod: Storage Drawers
