### ISSUE TITLE
GregTech ore ending up with illegal in-chunk coordinates and crashing the world upon loading in

### ISSUE THREAD

**Issue by LoUyyR** [GTNewHorizons/GT-New-Horizons-Modpack#16557] opened 2024-06-19 20:49 UTC
### Your GTNH Discord Username

SanorusVentus

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

A usual power outage in Ukraine because of the war caused my PC to shut down while playing. Upon opening the game again when electricity came back I can't load my world anymore. 

Trying to load the world every time causes the crash to happen again in about a second after loading in the world. I see the chat for a brief moment and then - crash.

### Crash Report

[crash-2024-06-19_23.36.43-server.txt](https://github.com/user-attachments/files/15905768/crash-2024-06-19_23.36.43-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2024-06-19 22:19
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16531
what you describe sounds like textbook save corruption though. use a backup.

**Closed by chochem** 2024-06-19 22:19 UTC
Labels: Type: Crash, Status: Triage
