### ISSUE TITLE
Missing texture for "air" in railcraft tank.

### ISSUE THREAD

**Issue by tbullock** [GTNewHorizons/GT-New-Horizons-Modpack#13148] opened 2023-04-06 20:08 UTC
### Your Pack Version

2.3.0

### Your Proposal

Missing texture for air as it fills the tank see photo. Suggest adjusting this.
![2023-04-06_14 03 24](https://user-images.githubusercontent.com/1172997/230483506-631f4ef4-22ba-44b5-926e-56fe961ae457.png)

### Your Goal

Fix the missing texture

### Your Vision

Remove visual glitches from the pack.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by BritishCynic** [comment] 2023-04-06 20:15
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11807

**Closed by BritishCynic** 2023-04-06 20:15 UTC
Labels: Type: Suggestion, Status: Triage
