### ISSUE TITLE
Have GT++ Fish Catcher support shift-clicking items

### ISSUE THREAD

**Issue by TwoTailedFox** [GTNewHorizons/GT-New-Horizons-Modpack#10087] opened 2022-04-03 13:56 UTC
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.3QF

### Your Proposal

To have the Fish Catcher support shift-clicking items (like chests support) so they can go into your inventory quicker than just single-click deposit into inventory

### Your Goal

To be able to extra fish quickly before automation comes into play.

### Your Vision

To ensure fish catchers have same functionality as other inventory blocks.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment] 2022-04-03 14:03
Duplicate of #9865

**Closed** 2022-04-03 17:36 UTC
Labels: Type: Duplicate, Type: Not a Bug, Mod: GT++, Type: Won't Change
