### ISSUE TITLE
Electric Implosion Compressor can't share walls anymore (2.3.) and delete Neutronium Blocks! 

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#12937] opened 2023-03-18 11:19 UTC
### Your GTNH Discord Username

Ngar

### Your Pack Version

2.3.

### Your Server

myFTB

### Java Version

Java 8

### Type of Server

Thermos

### Your Expectation

At version 2.2 builded a EIC as 2x2 wallsharing Mulitblock. It works well. 
Special: Input Bus placed in middle of all four machines, that all machine can work with same receipt.

### The Reality

After update to 2.3 only diagonal settled EIC are well formed. (picture: right front and left back)
The other two were missformed and loose (!) Neutronium Blocks after several minutes.  (picture: left front and right back)
![EIC_1](https://user-images.githubusercontent.com/7759876/226102021-e0a067db-6557-425b-a381-92a821d3eedf.JPG)

### Your Proposal

make wall sharing work again

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment] 2023-03-18 11:28
Wall sharing never was really officially supported, especially with multis that remove and spawn back blocks. And by the time you reach EIC, neutronium doesn't cost much anymore, so just move the multi one block.

**Comment by BlueWeabo** [comment] 2023-03-18 11:30
or disable the animation

**Comment by chochem** [comment] 2023-03-18 12:18
wasnt this always the case? dont think this is a 2.3.0 problem like the title suggests

**Comment by boubou19** [comment] 2023-03-18 12:51
yeah so not a bug then, i'm closing this. Maybe disabling animations can enable wallshare again, but explosion bugs are more important than wall sharing.

**Closed by boubou19** 2023-03-18 12:51 UTC
Labels: Type: bugMinor, Status: Triage

**Comment by Ngar1** [comment] 2023-03-18 16:15
Where this animation has to be disabled? Server side or client? and what config?

**Comment by Ngar1** [comment] 2023-03-18 16:17
> wasnt this always the case? dont think this is a 2.3.0 problem like the title suggests

I build this in 2.2. and Multi setup works.

**Comment by Ngar1** [comment] 2023-03-18 18:02
> 

targed of wallsharing was that 4 machine work with one input with same receipte to get a parallelizing effect
