### ISSUE TITLE
Electric Blast Furnace sound not being muffled by muffler upgrade or EU2 Sound Muffler

### ISSUE THREAD

**Issue by NikolaiM88** [GTNewHorizons/GT-New-Horizons-Modpack#8478] opened 2021-08-31 12:06 UTC
### Your GTNH Discord Username

Nishea/NikolaiM88#6542

### Your Pack Version

2.1.1.0

### Your Server

Stonehut

### Type of Server

Don't know

### Your Expectation

Our EBF is making a very low freequent buzzing sound, we put booth muffler upgrade into it and EU2 sound muffler next to it. Expected the sound to stop.

### The Reality

Neither the upgrade or the EU2 Sound muffler had no effect on the sound.

### Your Proposal

Make either sound muffler work on the sound.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by leagris** [comment] 2021-08-31 12:20
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8180

**Closed by leagris** 2021-08-31 12:20 UTC
Labels: Type: duplicate, Type: bugMinor, Status: Triage
