### ISSUE TITLE
Server crashed by NagaCourtyardWall

### ISSUE THREAD

**Issue by wadsqe1234** [GTNewHorizons/GT-New-Horizons-Modpack#16430] opened 2024-05-31 18:03 UTC
### Your GTNH Discord Username

wadsqe1234#4285

### Your Pack Version

2.6.1

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Actions

When player enter the twilight forest and approach Naga Courtyard.

### Crash Report

[crash-2024-06-01_01.43.00-server.txt](https://github.com/user-attachments/files/15517217/crash-2024-06-01_01.43.00-server.txt)
[crash-2024-05-31_23.10.44-server.txt](https://github.com/user-attachments/files/15517218/crash-2024-05-31_23.10.44-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Lyfts** [comment] 2024-05-31 18:17
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16353

You can update twilight forest to https://github.com/GTNewHorizons/twilightforest/releases/tag/2.6.12

**Closed by Lyfts** 2024-05-31 18:17 UTC
Labels: Type: Crash, Status: Triage

**Comment by chochem** [comment] 2024-05-31 18:20
technically that log is a bit different. hmm
