### ISSUE TITLE
Avaritiaddons chests visual bug

### ISSUE THREAD

**Issue by saltycco** [GTNewHorizons/GT-New-Horizons-Modpack#8044] opened 2021-06-12 20:09 UTC
#### Which modpack version are you using?
GTNewHorizonsClient-1.7.10-2.1.0.0

#### If in multiplayer; On which server does this happen? 
SIngle\private server

#### What is your GTNH Discord username?
saltycco#2083

Visual bug happens with compressed chest and infinity chest (Avaritiaddons mod).
1)When you have chest in inventory most of item icons located on the right side and below of the chest turned to gray.
https://prntscr.com/156n1hq
https://prntscr.com/156n1vn

2)On toolbar if you choose anything except compressed chest or clear hand, healing axe turning to gray.
https://prntscr.com/156n26b
https://prntscr.com/156n2nq

Launcher: TLauncher last version
Minecraft Forge: 1.7.10 - 10.13.4.1614
OS: Win10

Actions which i already tried:
1)  Full reinstall java using RevoUninstall to totaly clear it (java version jre-8u291-windows-x64)
2) Reinstall TLauncher\Forge\GTNH client
3) Deleted .minecrtaft from AppData\Roaming
I can provide any additional information\logs if you will need, or make some specific tests.

**Comment by GTNH-Afx237v7** [comment] 2021-06-12 20:10
Duplicate of #7113

**Closed** 2021-06-12 20:11 UTC
Labels: Type: duplicate
