### ISSUE TITLE
Dual Crafting recipes for Warpwood Staff

### ISSUE THREAD

**Issue by fabiobuhr** [GTNewHorizons/GT-New-Horizons-Modpack#7168] opened 2020-12-27 00:22 UTC
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
Hey guys, does anyone one know why there are the exact same crating ingredients for 2 items? items 4396:400 and 4396:480, both are Shadowmetal Attuned Warpwood Staff, but one holds 500 and one 750 vis. Can't seem to be able to chose the 750 version.
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/72572846/103161417-57f68a00-47c0-11eb-9a70-e3c12efa6235.png)

#
#### What do you suggest instead/what changes do you propose?
Disable or differentiate recipes.

**Comment by KiloJoel** [comment] 2020-12-27 00:26
This is a known issue which exists for all staffs. The one with higher capacity is a staffter and can't use foci. The regular staff recipe is meant to be 2 caps and no primal charm.

**Comment by KiloJoel** [comment] 2020-12-27 00:28
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5830

**Closed** 2020-12-27 00:31 UTC
Labels: Type: duplicate
