### ISSUE TITLE
Infernals

### ISSUE THREAD

**Issue by Waisse** [GTNewHorizons/GT-New-Horizons-Modpack#3229] opened 2018-06-30 19:11 UTC
#### Which modpack version are you using?

#2.0.4.6
#### If in multiplayer; On which server does this happen? 
#Delta

Infernal are an absolute pain, they don't despawn, and cause grief by just being nearby. They can spam cobwebs on you, strike you with lightning, drown you etc. WITHOUT NEEDING TO SEE OR TARGET YOU.
I'm absolutely ok with the difficulty infernal add, but they shouldn't cause that amount of grief even when they are just walking around. And there's also a bug that cause infernals to be invisible, go figure.

**Comment by PoptartOverlord-Xabedo** [comment] 2018-06-30 20:01
speaking of infernals those the only thing those bosses  do is oneshot you, get better armor? good luck before  a good while spent in MV as even full iron isn't enough around them, not to mention they are too damn common way to common in fact that almost all mobs have boss tags, they also don't  simply place some cobwebs or strike fireballs or lightening, its SPAMMED on you in a way you cant survive from at all

**Comment by PoptartOverlord-Xabedo** [comment] 2018-06-30 20:08
also i should note that yes they indeed add the the difficulty of the game, which is im personally fine with, but the sheer amount of just how many spawn makes you sick, literally they're a lot more common than normal mobs ,i think they completely replace them.
let me state this, i am with infernals as mobs that do spawn in the game and raise the difficulty, but the sheer amount of how they spawn and how they spam attacks is unbearable, if atleast they become less insuperable by decreasing their attacks, as they can be over  2 chunks (32 blocks)  away and still spam cobweb and lightening  around you

**Comment by boubou19** [comment] 2018-06-30 20:14
if you want to avoid infernal mobs in your base just claim the area with "/town claim"
and after disable the mob spawning with "/town perm toggle mobs" and your life should be easier ;)

**Comment by PoptartOverlord-Xabedo** [comment] 2018-06-30 20:16
thats true and thats what we did
but they're still annoying in an insuperable way not to mention with a little too far reach

**Comment by Waisse** [comment] 2018-06-30 20:21
Towns don't prevent infernals grief like cobwebs, to get rid of them I have to hunt them down or lure them into the town to despawn them. This is neither funny or engaging gameplay, I want to be safe in my town.

**Comment by DoomSquirter** [comment] 2018-06-30 21:19
push back the area around your town, place chandeliers down, later place magnum torches down.  light things up with torches.  do some caving.  properly protect your base.  wear armor.  make a crossbow.  except for one errant blaze that would not die, I've been able to kill every infernal I've run across.

the infernals as they are in this pack fit the pack perfectly.  do I like them?  no.  but there's nothing absurdly off kilter here that's not fully addressable by the end user.

**Comment by 0lafe** [comment] 2018-06-30 23:34
The only one I personally think should be removed is Webber, because they web up mob spawners which collect drops and cause lag. The rest are all totally avoidable, and you can always despawn them pretty easily. Makes getting better armors more worth it

**Comment by Waisse** [comment] 2018-07-01 00:56
So the answer is to completely shut off spawns and prevent mobs from spawning entirely ? That's absurd and near impossible to do in a survival setting. Town claims cost way too much to buy all spawnable chunk around my base. Heck I can't even claim all chunk I'm actively using.

Infernals shouldn't be such a nuisance that they shouldn't exist. Do you guys understand that I'm talking about passive grief from them ? Just having an infernal nearby WITHOUT FIGHTING IT is a nuisance : they spawn cobwebs on you, lightnings, hunger, force jump, drown etc. These abilities would be fine if infernals had to target a player to use them, but that's not the case, and this is why I opened this thread in the first place : they shouldn't make my life miserable when I'm sitting in my base.

Infernals would be fine if they didn't cause passive grief. Let's not talk about how to avoid them anymore because they keep coming back and THEY NEVER DESPAWN naturally.

**Comment by DoomSquirter** [comment] 2018-07-01 01:46
I understand exactly what you're talking about.  not impossible whatsoever.  you can easily push them back to the point where they don't trouble you.  you can build a wall around your area.  lots of options that don't involve towns/claiming.

**Comment by MineAnPlay** [comment] 2018-07-01 01:48
Your lucky you even have towns :P. Many people play SSP or on servers without town. It's very easy to avoid mobs in general, just build a base with walls and torch the surrounding 16-24 blocks around the base. Also I agree with 0lafe, other then Webber clogging systems, infernals are actually useful and are a fun (at times rage inducing) part of the pack.

**Comment by 0lafe** [comment] 2018-07-01 02:06
>Your lucky you even have towns :P. Many people play SSP or on servers without town

As one of these people, I agree that they aren't an issue. We use torches to block spawns, and walls to stop others that spawned outside our torch area.

**Comment by Prewf** [comment] 2018-07-01 05:23
@Waisse What are you suggesting as a possible fix for this?

**Comment by PoptartOverlord-Xabedo** [comment] 2018-07-01 05:57
i believe the issue isn't how strong the infernals are at all  nor how rage inducing they are, and countermeasures have been taken in our base because simply thats the easiest and shortest answer, but the problem lies with how unengaging they are  when you're doing something else completely(alot of the times outside of town) and they're about 32 blocks away then they start using their area of effect abilities on you then you start looking around for them but you cant find them because they're also invisible and no particles can be seen sometimes (yes i do have particles on max) but you simply can't find them because their area of effect is simply huge, which makes it alot less engaging to do what you're doing and start losing your shit because you cant find them
as some of us has stated we have no problem with them in combat at all when its face to face _(or back to face because stabbing in the back is fun......if you're the one that is doing that ;-;)_ but as long as we're doing something  else entirely and stopping that thing just to kill the endless hoards of them coming at you is not an engaging and fun mechanic of the game its just simply unplayable to a degree  _(unless you're unkillable :3)_
also this is not a bug its more of a discussion/suggestion, and the fix we probably suggest is that the infernals either stop using their abilities way too fast as for example the webber doesnt simply put the web beneath you to stop you from moving and your not even running, it just starts putting webs everywhere around you, as you walk a little you'll find your base covered in web_(which we can all agree on that cleaning after a messy party isn't that fun ;3)_
so uhm, the fix is either we tone down their abilities somehow as to stop them from casting webs all around you or 10 lightening strikes  straight on your head (from one mob, mind you) Or to make the infernals less common 
or at the very least, make them despawn as we dont want the world filled with them just because someone was exploring at night then a new player comes and gets rekt by them, for example.

also seriously on a side note, the invisible ones  really dont emit any particles sometimes 
"sometimes" is the keyword here

**Comment by Waisse** [comment] 2018-07-01 10:19
@Prewf 

I have several suggestions : 

- Remove Webber
- Allow infernals to despawn naturally
- Reduce their abilities area of effect
- Reduce infernal spawns

**Comment by Karl-Markkus** [comment] 2018-07-01 11:15
I just noticed another thing about infernals, though this might be fixed IF they either reduce spawn chance, and they despawn naturally. but the problem is that some infernals almost always have over 300 hp, or scaling up to 1000 hp, which is insane. And with withering, or even vengeance attribute, it is almost impossible to kill it, which leads to people just either needing to trap it, or run away.

**Comment by WarlordWossman** [comment] 2018-07-01 11:17
>we remove a lot of stuff already. If we remove more we can remove the mod and put in a dirt to dimand Blocks recipe. GTNH is a hard modpack and monsters have to be dangerous and nasty bastards. If you protect your Base with torches and later on with turrets you will be fine.
(maybe need to redone turrets make it more easy)

I disagree with this, crafting recipes have nothing to do with mobs since grind =|= difficult.
"GTNH is hard modpack", I wish it was but in reality those mobs are still super easy to cheese once you get how they work. It's the randomness and lag you introduce to the game that makes infernal mobs so bad imo. Having a lot of mobs with tags that they do not despawn on servers with god knows how many chunkloaders? Good idea, I wonder how much tps we lose because we are a "hard modpack".

If you think about it infernal mobs drop extra loot and endermen take forever to die in a smeltery giving you tons of ender pearls (or unlimited with regen effect). Once you make a decent enough crossbow you can fight almost all of them anyways, and if they have vengance you just don't fight them.

Back then when we had Zombie Awareness, that made mobs harder in a way you would want it to, but randomly buffing single mobs a lot is a really poor way of doing it and with the lag issues I mentiones it's bad game design on top of that.

There would be a lot of ways to make the game harder but mobs have to stay a ressource as well, fighting was never the main aspect of this game or modpack.
I have been playing this pack for over 3 years and know how to deal with all those mobs, or to build a crossbow that shits on them. 
If you want to make the modpack feel better for everyone you should take the feedback for once and we can rethink what to do with mobs to deal with the situation better. (Better ways to make mobs scarry).
But instead we keep a partially broken mod that adds lots of lag because "GTNH is a hard pack", even if 99% of the players agree that they are retarded, gg.

**Comment by richardhendricks** [comment] 2018-07-02 00:40
I think if we can add dimension control to infernal spawn rates or to which infernal tags are available, that would help alot.

**Comment by Dream-Master** [comment] 2018-07-02 06:32
We have dim control so we disabled it in Dim 50 (Thaumcraft dim) but we cant change more than that.
When somone make code changes we have more options.

**Comment by Methes** [comment] 2018-07-02 09:01
Infernals are more of an annoyance than feature really.
Once you get a crossbow (steam compressor+) you snipe them all except vengeance, once you get nano suit you snipe vengeance ones too.
Until then there's no point in fighting them as you simply stand no chance/the profit is none. With xbow you can FINALLY get rid of them if they stand in your way.

Another problem is the randomness. You can encounter them absolutely anywhere so there's no skill reward. See an infernal? Meh. I'll go a different way, have to dig a new tunnel, great. For bosses you prepare, know when you're about to face them. Infernals? Just random obstacles when RNG wants to screw with you.

Having mobs scaling with dimensions would be nice but even then it's tough to balance. Usually it's "one hit and I'm dead" or "oh hey someone is tickling me". Knowing when players enter certain areas and what their equip usually is you could balance it but I think it varies so much there's no point.

The only two places I've seen have balanced mobs are Vanilla MC with new combat system and MAYBE Project Ozone 2.

Zombie Awareness was dope.

**Comment by WarlordWossman** [comment] 2018-07-02 09:51
That is what I am saying, the randomness just feels super weird:
Sometimes there is a lame zobie you can kill in 2 or 3 hits that does literally nothing, sometimes they have 3000 hp with regen & vengance which means you cannot kill him in normal ways.
The idea here would be to find more of a middle ground, maybe buff the base zombie (more hp, 20% more movement speed, etc) but don't let the totally ridicolous ones happen at all, in the end that would probably be harder anyways and feel more consistent.
Same with improving the AI, make them smarter rather than just applying ridicolous stats - that would actually lead to players having to think about tactics rather than going "3000hp? better make a quicksand pit" (which btw isn't exactly hard imo).

@Dream-Master we never asked for things to be "easier" but when you have mobs that fluctuate from 20 to 4000hp or get unlucky and get a blaze that on hit gives you poison, fire AND wither, you might wanna rethink the system.
As I said there is plenty of ideas how to make mobs (consistently) harder instead of having a gamble each time a mob spawns. (and one unlucky player feels like shit because he faced a bullshit combination of effects)

**Comment by MineAnPlay** [comment] 2018-07-02 10:31
I think Infernal Mobs is opensource so we can fork it how we like it. I'd also want a larger loot table for them to get a few random materials (Some silver or basic materials maybe some gems maybe some other modded stuff because right now it's just the default loot table). Also I agree that stuff like Zombie Awareness and stuff are cool but the problem with usual smart AIs is that they can be laggy at times, especially ones that do siege/cooperative attacks. Maybe we can also implement a system to Infernal Mobs that adds a "clock" to players so that the Infernals get stronger/better overtime and also increase others/probabilities in higher tier dimensions. Or we could check or add achievements to check the "age" to increase their difficulty. Also make it should be so it gets the average "difficulty" of players around so as to not make it too easy/hard if there's others around. Heck if we want to invest this much we could try to make a new mod xD. I just wrote what ever came to mind to "improve" the mod.

**Comment by Methes** [comment] 2018-07-02 12:36
A cool addition would be if there were hordes of zombies trying to get to the player, breaking blocks in the process.
Then you'd have to build walls, traps, use turrets, golems, electric wires, guns...

**Comment by Waisse** [comment] 2018-07-02 12:49
How do you defend against that early game ? Are you crazy ?

**Comment by Methes** [comment] 2018-07-02 13:31
Early game would be easier of course with fewer and less dangerous mobs.
It's easy to track progress through the many achievements of GT so one could scale the mobs that way.

**Comment by alphaNOVAircraft** [comment] 2018-07-02 13:39
@Methes that could work out fine in singel player with some code change, but we cant change the code of the mod and on server new player would be completly overrun by the mobs because there are already some players that are pretty far into the gt achivments

**Comment by WarlordWossman** [comment] 2018-07-02 13:43
Eh, we are not some tower defense like modpack, no block breaking I would say.
Just make mobs in general more challanging instead of sprinkling a few super ridicolous ones into the harmless ones, as easy as that.

**Comment by MineAnPlay** [comment] 2018-07-02 13:44
It's possible to check for only the players near spawned mobs, so only high tier players will have those effects/mobs.

**Comment by Prewf** [comment] 2018-07-02 16:37
>Or we could check or add achievements to check the "age" to increase their difficulty.

>It's possible to check for only the players near spawned mobs, so only high tier players will have those effects/mobs.

I like this idea. The more cool tech/weapons people have access to, the tougher the mobs should be. Scaling mobs with your scaling equipment seems like a logical thing to do.

**Comment by Dream-Master** [comment] 2018-07-02 18:55
We can dreaming about new features but we need somonefirst  who touche the code and implement all that stuff.

**Comment by noobyaran9** [comment] 2018-07-03 01:07
Honestly speaking, i think the mod have to be toned down a little bit. Especially for some effect combination is just dumb. 
>Vampire Zombie Pigman + Revenge
>Regen + Revenge + Beserk

Some examples of the shitty-ness of this mod.
I could easily grief someone's base by luring a mob with lightning effect and cause fire around someone's base. Fire besides machine = boom.

I just spawn cobwebs around someone's base and cause them a hassle to clean up.

**Comment by Waisse** [comment] 2018-07-04 17:42
This thread completely blew up out of proportions. My only real suggestion was to remove webber since that's the only effect that bypass claims and can grief terrain.

**Comment by Bryfer** [comment] 2018-07-04 18:10
I'd suggest writing more in OP next time you make an issue, It was not really clear that you was suggesting "webber" to be removed
"Webber" was just one of many things you mentioned in OP, there was no proper conclusion or suggestion in there, just statements (which mostly sounds like whining). 
Ofcourse it will lead to massive discussions since this issue isnt about anything specific.

**Comment by WarlordWossman** [comment] 2018-07-04 18:28
Webber does 2 things:
* make the game more annoying
* give you free strings early game (hard modpack btw)

Everybody runs around with a sword anyways and it takes a second at max to break cobwebs.
I could go on about it but it seems like we want mobs to feel annoying...

**Comment by 0lafe** [comment] 2018-07-04 18:31
>Webber does 2 things:

It also fills up mob farms, picking up items and lagging servers/ssp. There isn't really a way around that, except filling the whole thing with vacuum stuff, hoping it can get it before the cobweb does. 

It's not that hard to fight that I think it justifies keeping it.

**Comment by PoptartOverlord-Xabedo** [comment] 2018-07-04 18:33
webber does 2 things:
1.makes people complain about it
2.allows me to make this post

**Comment by WarlordWossman** [comment] 2018-07-04 19:08
This is a very good point! @Dream-Master if we consider ourself a technic pack we shouldn't introduce mechanics that make mob farms so annoying, they are one of the more interesting mechanics besides just crafting and machines.

**Comment by wlhlm** [comment] 2018-11-21 15:34
I have tried to fix some aspects of Infernal Mobs. While not fundamentally changing the mod, it should at least fix some annoying aspects like infernals effecting neutrals players. Please have a look: https://github.com/GTNewHorizons/atomicstrykers-minecraft-mods/pull/1

**Comment by Dream-Master** [comment] 2018-11-21 16:07
very cool @wlhlm you the first one change code and don't complain on the existing mod itself without doing anything. Sadly I am not a coder but I will poke my team to check code.

**Comment by richardhendricks** [comment] 2019-12-18 21:05
Will review code changes 2020Q1

**Comment by richardhendricks** [comment] 2020-01-26 16:29
- [ ] Check on invisible mob mentioned in #4946

**Comment by Dream-Master** [comment] 2020-05-28 06:11
must be fixed. If not just reopen later

**Closed** 2020-06-07 18:53 UTC
Labels: FixedInDev, Need Code changes, bugMajor
