### ISSUE TITLE
Fluid Terminal shift click behavior

### ISSUE THREAD

**Issue by KhonaB** [GTNewHorizons/GT-New-Horizons-Modpack#14254] opened 2023-08-18 01:56 UTC
### Your GTNH Discord Username

Khona Betwanhe#7122

### Your Pack Version

Nightly #92

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Shift click stack of full fluid cells (regular IC2 cells) into the fluid terminal, expected fluid to go into the connected TFFT multi-io hatch as it did before updating from 2.3.6

### The Reality

Fluid is not transferred. This does not work even one by one or by clicking in the terminal. Slightly different behavior is observed using large fluid cells (clicking in the terminal one-by-one works) and ExU drums of fluid work normally.

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by firenoo** [comment] 2023-08-18 05:44
I think this was fixed in ae2fc 1.1.38

**Comment by KhonaB** [comment] 2023-08-18 05:58
I'll update tomorrow morning and test it then, it's late rn. Assuming the
version of ae2fc is in the next/most recent nightly, which I'll check.

**Comment by KhonaB** [comment] 2023-08-18 23:38
Shift click filling cells from the fluid terminal now works, however, shift-click emptying (from inventory) does not. Neither does one-by-one emptying by clicking a full cell on the terminal or on the fluid icon itself.
Additionally, now shift-clicking on a large fluid cell full of liquid in the inventory dupes the fluid (the cell is not emptied but fluid goes into the terminal). I don't *think* that happened before, but I may have just missed it. Individually emptying large cells works as normal.
ExU drums still work fine.

**Comment by firenoo** [comment] 2023-08-19 00:35
shift click emptying from inventory was never supported in ae2fc; thats an ec2 feature. in dev, the operations you listed work fine for me, so i am puzzled, you need to verify directly what mod version you have.

**Comment by firenoo** [comment] 2023-08-19 00:36
However, I can confirm that gt++ cells are broken at least

**Comment by KhonaB** [comment] 2023-08-19 01:07
Shift click emptying works with drums from the inventory though? If that's
not supposed to be a feature then that's kinda weird. And I've never used
extra cells 2, and I know I've done shift click and drag across a bunch of
filled ic2 fluid cells in my inventory to dump them before--i can probably
figure out which version I was on if it helps. I am on nightly 94 now,
which i believe has ae2fc 1.1.39. Additionally, the fluid dupe with gt++
large cells only occurs when shift clicking from the inventory.

**Comment by KhonaB** [comment] 2023-08-19 01:09
I'll try and take a video of my issues, that might be better than describing.

**Comment by firenoo** [comment] 2023-08-19 01:10
Sorry, I misspoke. Shift clicking insert should work, i was thinking shift click extract. Anyways i fixed the GT++ cells not working

**Comment by KhonaB** [comment] 2023-08-19 01:36
Shift click extracting full stacks works fine for IC2 cells, gt++ cells, and drums. The problem I'm having is in this video, cannot insert the contents of IC2 cells into the fluid terminal by any means.

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/12417837/3d8627d2-9a5f-48f0-9b51-367def80881d

**Comment by firenoo** [comment] 2023-08-19 02:00
Ok, just realized the problem. So Sampsa has been telling me IC2 cells are broken, but when I tested with IC2 cells (the lava cell), it worked. It was the GT cells that were broken, because their implementation is weird. Anyways thanks for helping me find it.

**Closed** 2023-08-19 10:34 UTC
Labels: Type: bugMinor, Status: Triage
