### ISSUE TITLE
[Bug] Semifluid Generator does not work

### ISSUE THREAD

**Issue by gyw2002** [GTNewHorizons/GT-New-Horizons-Modpack#7284] opened 2021-01-09 15:27 UTC
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Craftersland GT:NH
#
#### What did you try to do, and what did you expect to happen?
Tried to use single-block semifluid generators and fed creosote cells and/or creosote oil via pipe
#
#### What happened instead? (Attach screenshots if needed)
Semifluid generators did not accept fluid in any form
![2021-01-09_16 23 16](https://user-images.githubusercontent.com/13161774/104095505-787e1400-5297-11eb-9672-eeca96af2bf4.png)
![2021-01-09_16 23 18](https://user-images.githubusercontent.com/13161774/104095507-7916aa80-5297-11eb-907b-14d918395695.png)
![2021-01-09_16 23 13](https://user-images.githubusercontent.com/13161774/104095508-7916aa80-5297-11eb-9e36-4b924992155f.png)

#
#### What do you suggest instead/what changes do you propose?
If they can't be fixed, then please remove or disable them

**Comment by Dream-Master** [comment] 2021-01-09 20:07
@gyw2002 is this a gt or a gt++ block?

**Comment by gyw2002** [comment] 2021-01-09 20:48
both single-block variants and multiblock version are GT blocks

**Comment by Prometheus0000** [comment] 2021-01-09 20:56
What? They're GT++

**Comment by braeven** [comment] 2021-01-10 00:42
Duplicate of #4306

also tested this on Epsilon, they don't take Creosote or Seed Oil like the Quests say

**Closed** 2021-01-10 00:44 UTC
Labels: Mod: GT++
