### ISSUE TITLE
Bismuth bronze formula error

### ISSUE THREAD

**Issue by Mobius0526** [GTNewHorizons/GT-New-Horizons-Modpack#12412] opened 2023-01-28 02:03 UTC
### Your GTNH Discord Username

Mobius

### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

1 Bi + 4 ZnCu3 → 5 BiZnCu3

### The Reality

1 Bi + 1 ZnCu3 → 2 BiZnCu3

![image](https://user-images.githubusercontent.com/62875887/215236388-4bcc1b87-1349-4f85-81df-35f5f98b59b8.png)

### Your Proposal

1 Bi + 4 ZnCu3 → 5 BiZnCu3

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2023-01-28 11:07
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12115

**Closed by chochem** 2023-01-28 11:07 UTC
Labels: Type: Duplicate, Type: bugMinor
