### ISSUE TITLE
Missing Texture

### ISSUE THREAD

**Issue by Patch276** [GTNewHorizons/GT-New-Horizons-Modpack#18499] opened 2024-12-24 21:42 UTC
### Your Pack Version

2.7.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Items would have same textures after updating pack

### The Reality

Missing Texture for all GregTech Screwdriver items as well as all bolts after updating to pack version 2.7.1
By missing texture I mean they are instead represented by a solid white plate
![2024-12-24_16 41 30](https://github.com/user-attachments/assets/2bf9409a-0ee7-4b96-996b-616f6ade3e6f)

### Your Proposal

Represent item with texture for the item

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FourIsTheNumber** [comment] 2024-12-24 21:49
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18454 and https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18457.

Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/3678

Your post says you are using java 21 but this issue should be exclusive to java 8. Correctly switching to modern java should fix it for now.

**Closed by FourIsTheNumber** 2024-12-24 21:49 UTC
Labels: Bug: Minor, Status: Triage
