### ISSUE TITLE
New Type Filter Ore Dict: Siftables

### ISSUE THREAD

**Issue by General-Ike** [GTNewHorizons/GT-New-Horizons-Modpack#7828] opened 2021-04-19 03:23 UTC
While setting up my ore processing line, I found myself wishing there were a way to use the type filter to filter out specifically ores that have a recipe in the sifting machine. As it stands right now, the only way I can filter those ores is by using the input bus filter, but that introduces difficulty when I want to blacklist certain items from the sifter, since if I put a blacklist filter block in the pipeline, it no longer filters the incoming items to be siftable only.

I was told in Discord that this could theoretically be fixed by creating a new ore dict for siftable type items, allowing for interaction with the type filter block.

**Comment by Glease** [comment] 2021-04-19 03:50
Duplicate of #7277

**Closed by Glease** 2021-04-19 03:50 UTC
Labels: Type: suggestion
