### ISSUE TITLE
Localize GT server side

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8778] opened 2021-11-05 16:06 UTC
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.1.0

### Your Proposal

My proposal is to localize GT server side as well.

### Your Goal

It's needed because in opencomputer we get unlocalized names, and it's a real pain to parse the items from the gregtech lang file. It also takes a non neglictible amount of memory just to keep the localization table loaded in the computer. With the localization server side, all the item handling involving GT items will become way easier.

### Your Vision

This will improve the pack as lately, opencomputers has gained more and more popularity, so removing this tedium could remove a lot of difficulty for players beginning with the mod.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by PoroCoco** [comment] 2021-12-11 11:34
To add more precision to it.

Right now with OC, for a block/item we can have : 

- the name : "the untranslated item name, which is an internal Minecraft value like oc:item.FloppyDisk" 
- the label : "the translated item name"

This works fine for most if not every blocks in the game but for GregTech we have a few problems. 

- The label isn't universal between singleplayer and multiplyer. For exemple the EV advanced seismic prospector label in sp is "Advanced Seismic Prospector EV" and on mp it's "gt.blockmachines.basicmachine.seismicprospector.04.name".
- You could make a function to translate the label from "gt.blockmachines.cable.annealedcopper.16.name=16x %material Cable" to "16x annealedcopper Cable" using the lang file but as you can see the traduction isn't perfect next to the real name "16x Annealed Copper Wire".
- For items most of them cannot be translated using the lang file, for exemple the "Dense Meteoric Steel Plate" have these 2 lines associated in the lang file "gt.metaitem.01.22341.name=Dense %material Plate" and "gt.metaitem.01.22341.tooltip=SpFe₅₀C" so even if you get replace the %material by the tooltip you end up the chemical formula instead of the name.
- I don't know if there is a russian translation of gregtech but that would means that this would make the label even less universal
- For the name every gt machines uses the name "gregtech:gt.blockmachines" so it's universal but not unique.

So the best case scenario would be to make all gregtech items/blocks have a unique name but I don't know if it's doable so if we could at least have the label universal between sp and mp for English it would be an improvement.

**Comment by repo-alt** [comment] 2022-02-10 11:31
Apparently the issue was occasionally fixed by Mitch in rev. c25c1bce2dd620c2d39b77f33c57c1fc08b1ecb8

**Comment by repo-alt** [comment] 2022-02-14 13:38
Ok, so as it turned out, the issue is still there and I investigated it.
The problem is that net.minecraft.util.StringTranslate.replaceWith is client side only. So, GT is registering localizations server side in LanguageRegistry, but it is not propagated to StringTranslate and StatCollector (on the client it is done by the LanguageManager). The only solution I see so far is accessing StringTranslate.languageList via reflection server side, and stuffing the entries from LanguageRegistry there (either directly in GT_LanguageManager.addStringLocalization or later, because it looks like they are collected in GT_LanguageManager.LANGMAP)

**Comment by repo-alt** [comment] 2022-02-14 14:16
The whole mess is caused by the metagenerated items, their localization is split in 2 parts, the items themselves and materials. It probably can be refactored but it's a major change, I'd rather not fix what is (mostly) not broken.

**Closed** 2022-02-14 21:04 UTC
Labels: Type: Suggestion
