### ISSUE TITLE
quests "power of the sun 1x1 hv-iv" does not recognize freshly crafted robot arm (hv)

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#6467] opened 2020-08-01 14:11 UTC
#### Which modpack version are you using?
2.0.9.0 QF4
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### 
in comparison of the other power of the sun 1x1 quests, the hv-iv ones (quests 1007, 1719 and 1721) do not have ignore nbt set to true, making it not recognizing the freshly crafted robot arms.

**Comment by chochem** [comment] 2020-08-02 07:46
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6283, can be closed.
well actually, it looks there is one quest more in your list? then add that in the existing ticket please.

**Closed** 2020-08-02 11:04 UTC
Labels: NBT, Quest change, duplicate
