### ISSUE TITLE
Saving the desired recipe page in NEI by button A

### ISSUE THREAD

**Issue by Varkaus** [GTNewHorizons/GT-New-Horizons-Modpack#7479] opened 2021-02-14 18:26 UTC
2.1.0.0

Saving the desired recipe page in NEI by button A

It happens that sometimes you have to look at the recipe many times, and sometimes it gets boring, and it would be nice if it would be possible to save exactly the page that you like so as not to switch it many times to the right, to the left.

**Comment by GTNH-Afx237v7** [comment] 2021-02-14 18:27
Duplicate of #6836

**Closed** 2021-02-14 20:19 UTC
Labels: Type: duplicate
