### ISSUE TITLE
White panels

### ISSUE THREAD

**Issue by nuka-cole** [GTNewHorizons/GT-New-Horizons-Modpack#18457] opened 2024-12-20 19:08 UTC
### Your GTNH Discord Username

Nuka_cole

### Your Pack Version

2.7.1

### Your Server

offical  Eta

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

All bolts and screwsrivers on vanilla texture are just white panels 

### The Reality

![image](https://github.com/user-attachments/assets/b7eb117c-d7f2-4bec-b27d-1c24318ed3ba)

### Your Proposal

Too look normal 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by serenibyss** [comment] 2024-12-20 19:10
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18454 and fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/3678. A workaround is using Java 17+, otherwise we will mitigate this with a resource pack or pack update soon

**Closed by serenibyss** 2024-12-20 19:10 UTC
Labels: Bug: Minor, Status: Triage

**Comment by KamenriderZO** [comment] 2024-12-21 19:46
But the latest version of GT5u can't launch. Java 8
It stucked at lauching UI 33%
5.09.50.111 can run but 5.09.51.14 not

**Comment by serenibyss** [comment] 2024-12-21 19:51
@KamenriderZO do you have any errors in log?

**Comment by KamenriderZO** [comment] 2024-12-21 22:25
> @KamenriderZO do you have any errors in log?

No Just can't load further.And i have to force shut it down.
