### ISSUE TITLE
Client disconnect when placing a block from LittleTiles

### ISSUE THREAD

**Issue by vbion** [GTNewHorizons/GT-New-Horizons-Modpack#11331] opened 2022-09-17 10:25 UTC
### Your GTNH Discord Username

agiwheeze#1668

### Your Pack Version

2.1.2.3qf

### Your Server

private server

### Type of Server

Don't know

### Your Actions

1. Get a quarter of a block by the LittleTiles hammer.
2. Place this quarter on any block.
3. Get disconnected from the server. The server logs an Exception too.

### Crash Report

[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9591440/fml-server-latest.log)

The other players are not disconnected until they come close to the place where the block should've been placed. The placed block is invisible, it seems.

The clients and the server were 2.1.2.3qf. Clients were from CurseForge.
The world file right before placing the said block can be uploaded if you need it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment] 2022-09-17 10:47
Duplicate of #10153

**Closed by Glease** 2022-09-17 10:47 UTC
Labels: Type: Crash, Status: Triage
