### ISSUE TITLE
Server crashes when generating naga structure

### ISSUE THREAD

**Issue by Skulmarr** [GTNewHorizons/GT-New-Horizons-Modpack#17590] opened 2024-10-08 15:58 UTC
### Your GTNH Discord Username

skulmarr

### Your Pack Version

1.7.10

### Your Server

SP

### Java Version

Java 17

### Type of Server

Open To LAN

### Your Actions

When rendering Naga structure, server crashes

### Crash Report

[crash report.txt](https://github.com/user-attachments/files/17295982/crash.report.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2024-10-08 16:13
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16353 and a so so many others...

**Closed by chochem** 2024-10-08 16:13 UTC
Labels: Type: Crash, Status: Triage

**Comment by fbfnysnshnsgnwg** [comment] 2024-10-09 01:52
has been fixed for months
