### ISSUE TITLE
"Fire 51" in recipes

### ISSUE THREAD

**Issue by YannickMG** [GTNewHorizons/GT-New-Horizons-Modpack#9614] opened 2022-01-29 00:20 UTC
### Your GTNH Discord Username

Yannick#5937

### Your Pack Version

2.1.2.2QF2

### Your Server

SP

### Type of Server

Vanilla Forge

### Your Expectation

No Fire in recipes

### The Reality

Fire in recipes :
<img width="181" alt="image" src="https://user-images.githubusercontent.com/5321549/151638214-0ca38f3a-127b-425c-a162-63dbebeffe3d.png">

Recipes with Fire in them:

- Petal Apothecary
  - Narslimmus
  - Hopperhock
  - Jiyuulia
- Mana Infusion
  - Manasteel Ingot
- NASA Workbench
  - Tier 1-8 Rocket (Meta 1,2,3)

### Your Proposal

Take the fire out of the recipes.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment] 2022-01-29 16:41
it seems to be broken ore dict stuff. Its a bop flower errored here. Not sure why

**Comment by glowredman** [comment] 2022-01-29 16:44
Is it a NEI bug or are the recipes itself broken aswell?

**Comment by Dream-Master** [comment] 2022-01-29 16:47
not tested the recipe. What are the fire in GC? what item it replace? The chest ?

**Comment by glowredman** [comment] 2022-01-29 16:49
Yes, I'm asking because in GC/GS the NEI handler is completely sepperate from the NASA workbench recipe code

**Comment by bombcar** [comment] 2022-01-29 16:56
Yeah the 🔥 is where a chest should be. Iirc there were other cases.

**Comment by miozune** [comment] 2022-01-29 17:04
https://github.com/GTNewHorizons/NotEnoughItems/blob/master/src/main/java/codechicken/nei/PositionedStack.java
```
        if(items.length == 0)
            items = new ItemStack[]{new ItemStack(Blocks.fire)};
```
```
        if(item.getItem() == null)
            item = new ItemStack(Blocks.fire);
```
https://github.com/GTNewHorizons/NotEnoughItems/blob/master/src/main/java/codechicken/nei/guihook/GuiContainerManager.java
```
try {
...
} catch {
...
            drawItems.renderItemIntoGUI(fontRenderer, renderEngine, new ItemStack(Blocks.fire), i, j);
}
```
so it means
1. permutation has no ingredients
2. permutation contains null stack
3. failed to render stack

**Comment by glowredman** [comment] 2022-01-29 17:07
For GC/GS null stack can be excluded *if* actually crafting a rocket with chest still works, since the variable used for both recipes and NEI handler is the same

**Comment by miozune** [comment] 2022-01-30 04:11
I can reproduce this issue in my env (2.1.2.2-dev2 + some updates).
I inserted printf debug, and turns out `1. permutation has no ingredients` is the case. I believe NEI has no fault.

**Comment by miozune** [comment] 2022-01-30 04:43
okay https://github.com/GTNewHorizons/Galaxy-Space-GTNH/pull/18 works fine. Botania issue remains though.

**Comment by miozune** [comment] 2022-01-30 05:43
Will closed by https://github.com/GTNewHorizons/Galaxy-Space-GTNH/pull/18 and https://github.com/GTNewHorizons/Botanic-horizons/pull/2

**Closed** 2022-01-30 08:52 UTC
Labels: Type: bugMinor, Status: Triage
