### ISSUE TITLE
The Spice Of Life , Apple Core

### ISSUE THREAD

**Issue by veryangryapple** [GTNewHorizons/GT-New-Horizons-Modpack#17456] opened 2024-09-25 07:14 UTC
### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Literary anything that uses my saturation 
Consistent crashing seems to be gone after I held healing axe to fill my saturation bar
a single chest opening it also crashes the game. It is also caused by The Spice Of Life, Apple Core
![resim_2024-09-25_101647068](https://github.com/user-attachments/assets/76f494f1-232b-480b-8b27-538d0f0e6f1c)
these are the contents of the said chest breaking the chest and trying to pick up the items also crashes the game. 

I just found out that whenever I hover over any item that has food statistics the game crashes.(the UI element which shows how much hunger the item is going to fill). Added the related crash to the list.

I'll add more crash reports upon getting them from the same issue I have no idea if this will help, so please do inform me about this.

### Crash Report

with the one when my saturation goes low https://mclo.gs/yeiSOT6

and this one is when I open the chest https://mclo.gs/qEXdMJJ

Another one seemingly random same mods probably same issue https://mclo.gs/t4JOH3M

this one whenever I hover over any food item https://mclo.gs/XZevqEN

still crashing on 10/2/2024 on anohter machine whenever I hover over and food item https://mclo.gs/SNyol4n

(does anyone even look at this ?)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2024-10-12 23:02
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14471
probably some corrupted mod files, try redownloading.

**Closed by chochem** 2024-10-12 23:02 UTC
Labels: Type: Crash, Status: Triage
