### ISSUE TITLE
Applied Energistics (and related mods) bugs/comments

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6080] opened 2020-05-08 17:51 UTC
#### Which modpack version are you using?
GTNH-1.7.10-2.0.9.0-pre2-dev
#
I found these bugs while making AE2 quests:

AE2:
- There's some lag when activating the spatial transfer. I don't expect this to be fixed.
- The ME Portable Cell runs out of power so fast, you can't even fill it with items before it runs out.
- MEPC should be buffed with more power storage (100x?) and less consumption.

AE2 Wireless Crafting Terminal:
- There's some lag when opening the terminal
- What should be check marks or Xs or something in the magnet card interface is some kind of weird characters instead. Visual bug only probably.

EC2:
- EC2 higher item cells don't consume AE (256k+)
- EC2 fluid cells don't consume AE
- The ME Portable Fluid Storage only contains 128 buckets, why would you ever use it?
- MEPFS should have a larger size, it's only equivalent to 1 titanium cell, but way harder to make. Buff it to iridium cell level? Maybe increase power storage as well, if it just doesn't run out because you can barely put anything in. It might be kinda useless no matter what since you have to put the fluids in manually, and if you have the cells for that, you'd probably keep them in them?
- Fluid storage monitor locking with network tool doesn't work, can't get it to display fluid amount
- Fluid conversion monitor locking with network tool doesn't work, can't get it to display fluid amount (did work once somehow, can't reproduce)
- When placing filled cells into a fluid terminal with a bucket in the output, it just voids the cells
- When changing modes of the ME Block Container when it hasn't been locked to an item, it gives you a free Advanced Storage Housing, probably because the command conflicts with the one for separating components and housings. You can see a component for a millisecond before it goes back to being the BC. You can repeat this.
- Wireless Universal Terminal with essentia terminal added doesn't add functionality properly
- Wireless Universal Terminal won't allow adding crafting terminal to add crafting mode (apparently you can get it by using the WCT as the base, but I believe this should be an option as well)
- The ME Energy Cell Fixture both requires a channel (unlike other energy cells) and doesn't store any energy.
- ME Fluid Pattern [WIP]s don't work (are they disabled because we have cells?)

Thaumic Energistics:
- Essentia storage monitor power drain not consistent with same type
- Essentia conversion monitor power drain not consistent with same type
- There isn't a way to have the system craft essentia on demand for a craft, it would be nice if the essentia provider (or infustion provider) would send a request to any me interfaces that have a pattern for that aspect (you can make those patterns with the Distillation Pattern Encoder). This would be incredibly useful. 
- Alternatively (or as well) allow essentia export busses to accept the crafting card (and work with it of course), so you can use the essentia level emitter to activate them and keep a certain stock level.

**Comment by GTNH-Colen** [comment] 2020-05-08 20:11
If you use the wireless crafting terminal and hold shift while dragging your mouse it seems to kick the infinite range card out of the it for some reason making it useless until you get home again.

Also the magnet card/infinite range cards have a tendency to just delete themselves sometimes. I've lost 4 magnet cards and 1 infinite range so far.

**Comment by boubou19** [comment] 2020-05-09 16:03
they don't get deleted they drop on the ground, at least for me.

**Comment by GTNH-Colen** [comment] 2020-05-09 16:07
> they don't get deleted they drop on the ground, at least for me.

Sometimes they do that or appear in my inventory, maybe it's just me not realising that i've dropped them somewhere and they have despawned. Still a bug regardless though and an annoying one at that.

**Comment by repo-alt** [comment] 2020-05-11 19:17
ME Portable Cell energy buffer is set in config: 
`battery { I:portableCell=20000 }`

**Comment by Dream-Master** [comment] 2020-05-12 13:01
@repo-alt need this a code change or just a config change?

**Comment by repo-alt** [comment] 2020-05-12 13:04
Just a config. (config/AppliedEnergistics2/AppliedEnergistics2.cfg)
Consumption rate cannot be configured and I would not like to change it in code

**Comment by Dream-Master** [comment] 2020-05-12 16:38
@repo-alt close this issue ? or what we can do ?

**Comment by repo-alt** [comment] 2020-05-12 16:41
Not sure I understand, there are crapton of issues listed, For AE2 the only problem is insufficient energy in portable cell, should be fixed by changing value in config. e,g. to 2000000

**Comment by Dream-Master** [comment] 2020-05-12 16:42
ok will change the value

**Comment by GTNH-Afx237v7** [comment] 2020-05-12 16:44
As discussed on Discord, would be a quality of life feature if the EC2 Ore Dictionary Export Bus can accept multiple expressions (e.g. dustImpure* & beeComb* to go in a centrifuge). Currently it only allows one expression.

**Comment by leagris** [comment] 2020-05-12 17:02
I think it already supports RegExes but the input length is way too short for meaningful complex RegExes.
Otherwise it would allow such RegExes as:

```regex
(dustImpure|beeComb).*
```
or

```regex
dust(Im)?[pP]ure.*
```

or

```regex
(?!dust)Alumini?um
```

**Comment by repo-alt** [comment] 2020-05-12 17:12
It does not support regex. Here is the checking function:
`	private boolean checkItem(IAEItemStack s) {
		if (s == null || this.filter.equals(""))
			return false;
		int[] ids = OreDictionary.getOreIDs(s.getItemStack());
		for (int id : ids) {
			String name = OreDictionary.getOreName(id);
			System.out.println("Ore name: " + name);
			if (this.filter.startsWith("*") && this.filter.endsWith("*")) {
				String filter2 = this.filter.replace("*", "");
				if (filter2.equals(""))
					return true;
				if (name.contains(filter2))
					return true;
			} else if (this.filter.startsWith("*")) {
				String filter2 = this.filter.replace("*", "");
				if (name.endsWith(filter2))
					return true;
			} else if (this.filter.endsWith("*")) {
				String filter2 = this.filter.replace("*", "");
				if (name.startsWith(filter2))
					return true;
			} else {
				if (name.equals(this.filter))
					return true;
			}
		}
		return false;
	}
`

**Comment by Prometheus0000** [comment] 2020-05-12 17:14
Maybe you could increase the input length? Do you really want me to make separate issues for all of these though?

**Comment by repo-alt** [comment] 2020-05-12 17:15
Separate issues are way easier to handle, this will become a mess really soon

**Comment by Prometheus0000** [comment] 2020-05-12 17:21
Uh, which do you want?

**Comment by repo-alt** [comment] 2020-05-12 17:23
Either way is ok I think.

**Comment by Prometheus0000** [comment] 2020-05-12 17:24
I'll split them by mod and do both then.

**Comment by leagris** [comment] 2020-05-12 19:05
> private boolean checkItem(IAEItemStack s) { if (s == null || this.filter.equals("")) return false; int[] ids = OreDictionary.getOreIDs(s.getItemStack()); for (int id : ids) { String name = OreDictionary.getOreName(id); if (this.filter.startsWith("*") && this.filter.endsWith("*")) { String filter2 = this.filter.replace("*", ""); if (filter2.equals("")) return true; if (name.contains(filter2)) return true; } else if (this.filter.startsWith("*")) { String filter2 = this.filter.replace("*", ""); if (name.endsWith(filter2)) return true; } else if (this.filter.endsWith("*")) { String filter2 = this.filter.replace("*", ""); if (name.startsWith(filter2)) return true; } else { if (name.equals(this.filter)) return true; } } return false; }

@repo-alt how about making it a true Java Regex with much more characters for the Regex String like >250?

Something this way:

```java
import java.util.regex.Matcher;
import java.util.regex.Pattern;

// Compile filter to a RegexPattern on submit filter
public Pattern pattern = null;
this.pattern = ((this.filter.equasl(""))) ? null : Pattern.compile(filter);

private boolean checkItem(IAEItemStack s) {
		if (s == null || this.pattern == null)
			return false;
		int[] ids = OreDictionary.getOreIDs(s.getItemStack());
		for (int id : ids) {
			String name = OreDictionary.getOreName(id);
      if (this.pattern.matcher(name).matches()) return true;
		}
		return false;
	}
```

**Comment by GTNH-Afx237v7** [comment] 2020-05-15 15:01
Pack version GTNH 2.0.8.8

What happened:
placing a hollow cover over a dense ME cable disables the WAILA Information on how many channels are used/available completely. Instead, only the Name „ME Dense Cable“ is indicated. Once the cover is removed, the dense cable needs to be broken and replaced to correctly show the used/available channel information.

What did you expect:
Indication on channels to remain visible in WAILA even with cover in place

What do you suggest:
Analyze the cause and see if it can be fixed

**Comment by leagris** [comment] 2020-05-15 15:19
It is a long known issue that technically explains this way:

Normal AE2 cables are AE2 Block with AE2 Tile-Entity, until you place micro-blocks:
- Then it becomes a Forge Multi-part Block and Tile-Entity. A totally different block with totally different set of Data and a Much more complex Tile-Entity handled by FMP and delegating some functions to AE2.

Using AE2 facades rather than micro-blocks parts is a better option because facades:
- Are directly handled by AE2's own block and Tile-Entity.
- Therefore stays compatible with Waila's AE2's plugin.
- Causes less load on both Server and Client with lighter NBT Data and the direct handling by AE2 rather than proxy hooks through Forge Multi-part API. (Especially when AE2 updates or resolves its network layout.)
- Are much-less likely to bug.

**Comment by repo-alt** [comment] 2020-05-15 16:13
AE2 even dropped FMP support in 1.12 mainly for the stated reasons

**Comment by mitchej123** [comment] 2020-05-15 16:19
> AE2 even dropped FMP support in 1.12 mainly for the stated reasons

lol, I didn't even know AE2 supported FMP.  I always used facades.  Maybe we should do the same?

**Comment by repo-alt** [comment] 2020-05-15 16:32
There is certainly not much reason for it to exist.

**Comment by GTNH-Afx237v7** [comment] 2020-05-15 20:09
Thank you for the explanation. From my side I consider this closed then.

**Comment by repo-alt** [comment] 2020-07-12 14:34
Closing this because the relevant issues are listed in the forked bugs, and some are fixed.

**Closed by repo-alt** 2020-07-12 14:34 UTC
Labels: AE2 issue, EC2
