### ISSUE TITLE
Picking up thaumometer in inventory crashes the game

### ISSUE THREAD

**Issue by jurrejelle** [GTNewHorizons/GT-New-Horizons-Modpack#15825] opened 2024-03-25 18:45 UTC
### Your GTNH Discord Username

jurrejelle

### Your Pack Version

2.6.0-beta-1 (2024-03-23)

### Your Server

Multiplayer & SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

I created a new world in singleplayer creative, spawned in a thaumometer, and tried to click it in my inventory

### Crash Report

https://mclo.gs/KNb3SPF

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Lyfts** [comment] 2024-03-25 18:50
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15794

**Closed by Lyfts** 2024-03-25 18:50 UTC
Labels: Type: Crash, Status: Triage
