### ISSUE TITLE
Dire autocrafting NEI integration is incompatible with pattern terminals. (Regression)

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#18183] opened 2024-12-01 13:27 UTC
### Your GTNH Discord Username

Combu

### Your Pack Version

2.6.1

### Your Server

Delta

### Java Version

Java 21

### Type of Server

Thermos

### Your Expectation

Trying to setup dire autocrafting patterns from NEI

### The Reality

The recipe is inserted into the terminal in 1-sized stacks:
![image](https://github.com/user-attachments/assets/e92d167e-6235-4145-948c-75bb84875963)

This breaks any sufficiently-sized craft, like these LuV solar panels. The problem exists for the ME processing pattern terminal, and the ME pattern terminal (this is the vanilla one).

The problem does not exist for the fluid pattern terminal, the fluid processing pattern terminal. This issue also did not exist older versions of the modpack.

### Your Proposal

The default settings should produce the following across all processing pattern terminal flavours, as well as smaller pattern terminals if the size allows it:
![image](https://github.com/user-attachments/assets/2c103d98-6dcb-4eac-a8de-79dba5f751e8)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by RAFAEL-SOSA-UH** [comment] 2024-12-01 16:14
this feels like a duplicate of #13341

**Comment by RAFAEL-SOSA-UH** [comment] 2024-12-01 16:21
also, test it in version 2.7 alpha 4 , and the problem seems fixed.

**Comment by chochem** [comment] 2024-12-03 10:08
![image](https://github.com/user-attachments/assets/22dced1b-80dd-48d9-96a4-a0c6b03e5481)
yea seems to work just fine

**Closed by chochem** 2024-12-03 10:08 UTC
Labels: Type: Recipe, Bug: Minor, Status: Can't Reproduce, Mod: AE2, Mod: AE2FC
