### ISSUE TITLE
IC2 Cactus does not drop cactus

### ISSUE THREAD

**Issue by LazyFleshWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#15758] opened 2024-03-18 05:08 UTC
### Your GTNH Discord Username

LazyFlesh

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

I expected a cactus crop, fully mature, to drop cactus.

### The Reality

It dropped mini cactus, which is comparatively useless.

I checked in 2.4.0, and it did drop cactus.

### Your Proposal

Fix?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2024-03-18 11:33
isnt the tiny cactus the premature drop?

**Comment by LazyFleshWasTaken** [comment] 2024-03-18 16:01
Yes. That is why I specified on full maturity.

**Comment by chochem** [comment] 2024-03-18 16:04
Was looking into it some more, only to find its fixed already: https://github.com/GTNewHorizons/Crops-plus-plus/pull/64

duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15480

**Closed by chochem** 2024-03-18 16:04 UTC
Labels: Type: bugMinor, Status: Triage

**Comment by LazyFleshWasTaken** [comment] 2024-03-18 16:06
Oh, wonder why I didn't see it. Thank you, then. Sorry for the dupe.
