### ISSUE TITLE
ME pattern terminal will use OreDict substitutes to auto insert from NEI, even if the recipe doesn't allow for it

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12768] opened 2023-03-02 21:26 UTC
### Your Pack Version

2.2.10

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

For example the recipe for the rubber polymer catalyst demands 2 very specific types of rubber to be made, it will not accept OreDict alternatives.
However, if you're inserting it into a pattern terminal using the questionmark next to the recipe in NEI it will grab a random type of rubber, clogging your machines upon crafting if you don't notice NEI or ME inserting the wrong items into the pattern.

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2023-03-04 00:13
cant reproduce this on 2.3.0 RC2. I would have guessed its probably fixed but then there is https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12782.

**Comment by chochem** [comment] 2023-03-04 00:31
closed in favour of that other ticket

**Closed by chochem** 2023-03-04 00:31 UTC
Labels: Type: bugMinor, Status: Can't Reproduce, Mod: AE2
