### ISSUE TITLE
[RFC] Lava change

### ISSUE THREAD

**Issue by bartimaeusnek** [GTNewHorizons/GT-New-Horizons-Modpack#4816] opened 2019-07-02 19:41 UTC
Right now, there is an insainly easy recipe to make copper, tin, etc. from lava. So i suggest to change the recipe to a more realistc and actually effort-rewarding recipe. 
https://github.com/GTNewHorizons/GT5-Unofficial/pull/194

Basically, the new Lava centrifuging recipe will give out small piles Magnesia (MgO), Silicon Dioxide (SiO2), Sodium (Na), Calcite (CaCO3) and Potassium (K) at ~30% chance aswell as tiny piles of Tunstate at 10%. The Recipe cost will be increased from 80EU/t to 120EU/t and the time from 80ticks (4s) to 200ticks (10s). The Lava consumtion rate will be increased to 1000 from 100. 

To still get Copper, etc. youll now need to build a LHE, which converts the Lava into Panhoehoe Lava, that then can be centrifuged (1000L at 200ticks, 120EU/t).

EDIT: times Adjusted to 80ticks (4s) and input amount to 100L due to community wishes

Everyone who wants to comment on this, please only write down ONE comment with your Statement on:
- Do you like the change?
- Why do you like/dislike it?
- Do you have any other ideas on this topic?
- How long have you played this pack?

**Comment by Anarack** [comment] 2019-07-02 19:47
- Not really
- There are easier methods to gain all materials listed here and for cheaper than the original recipe rendering this change pointless.
- look into materials that are not trivial from other sources to swap in, perhaps rare earth? would be nice to have a trickle source of that
- 3 years at this point

**Comment by Bluebine** [comment] 2019-07-02 19:50
Like the drops change, dislike the rest.
I think that the new drops are more realistic, although definitely less useful. I would suggest adding sulfur, and removing SiO2- silicon dioxide is incredibly easy to mass produce in HUGE quantities from glass, making that recipe 100% useless. Easily renewable sulfur would be more useful.
But if you're making the recipe less useful, why would you increase the consumption and time to process? That's dumb. Keep them the same. 
If pahoehoe lava is gonna be kept the same (fine by me) then you shouldn't change its consumption by THAT much. 10x the consumption and 1/5th the speed is a BIG nerf. I'd start by just halving the speed of the recipe, keeping consumption at 100L, and increasing the usage to 120 EU/t.
I've been playing for 2-3 years, idk exactly how much

**Comment by kekzdealer** [comment] 2019-07-02 19:50
I like the change as it adds another possible output set from lava. 
Also I built a full lava setup with LHE, GT++ Centrifuge, and LGT to process 600L/s lava constantly (1.2 urns worth of lava, <2 cvis required) and the output is just crazy right now. It outputs around 500 ingots copper per hour and 125 of the other products while also producing close to 3000EU/t. 

The nerf/change is absolutely fine with me, and I'm considering using the remaining capacity from my current urns and centrifuge it as normal lava to gain the new extra products.

Played this pack for about 7.5 months / 1300h

**Comment by sthegreat** [comment] 2019-07-02 20:05
don't really like this change because

-The new outputs for lava centrifuging are pretty useless. The only one that isn't already easily+quickly renewable is potassium, which doesn't have a ton of uses besides NaK.
-Increasing inputs by 10x for normal lava just encourages urn spam, increasing for pahoehoe is the same with the exception that it might eventually require multiple lhes
-Copper is cheap af from xp bucket anyway, gold is renewable fast from mob farm or glowstone, silver is also from xp so balance isn't really broken by people getting those from lava.
-as I understand it, the gt++ lava boiler thing will continue to produce the full original outputs, so anyone who wants to can just get around this change and continue to quickly process lava while generating power

Overall this just seems like a pointlessly excessive nerf for something that was a minor balance issue. My suggestion would be just increase the time (or decrease output, similar except for lava consumption) on the current lava and maybe pahoehoe recipe. Maybe removing tungstate from normal lava would also be a good change.

Played for 2 years or so

**Comment by 0lafe** [comment] 2019-07-02 20:16
Fuck dots I'm giving my opinions

If this is at all happening, you really have to address the ++ version, as it's significantly worse than what you're trying to fix here. Change the recipe of the lava filter to use something difficult to input, as well as making the multi itself at least IV. The power usage equivalent for the output's it does is 1A IV of centrifuges rn, so imo reducing that to a small power gain is something that should be relegated to IV+. It's also such a cost reduction at the moment, not needing 64 singles and probably a PA. 

The idea of pahoehoe being needed is good, can't hate it. 

-kekz-

>while also producing close to 3000EU/t

Could also look at changing steam out from lava to make it roughly power stable to centrifuge all the output for the input. If you can't make the ++ thing right away, it ends with a power neutral setup that will gen you materials, as opposed to mats+power. 

-blueboi-

>But if you're making the recipe less useful, why would you increase the consumption and time to process? That's dumb. Keep them the same.

I think the point is to make it less useful, and all of those come together to reach a good point for it. Lava input is fairly low, and outputs are too high. Why not fix both 

-greatman-

>The new outputs for lava centrifuging are pretty useless. The only one that isn't already easily+quickly renewable is potassium, which doesn't have a ton of uses besides NaK.

I think that's the point, encouraging you to process the more involved lava for the useful shits. I would say there's a decent option here, put fucking phosphor in it. There's not really a tech based phosphor gen outside of pooproc, and the fairly useless ashes. 

>-Increasing inputs by 10x for normal lava just encourages urn spam, increasing for pahoehoe is the same with the exception that it might eventually require multiple lhes

WA?...

>-Copper is cheap af from xp bucket anyway, gold is renewable fast from mob farm or glowstone, silver is also from xp so balance isn't really broken by people getting those from lava.

xp crafting is kind of broken itself though. It's like a uu that doesn't take power. Even extracting it is fairly cheap power wise. 

>-as I understand it, the gt++ lava boiler thing will continue to produce the full original outputs, so anyone who wants to can just get around this change and continue to quickly process lava while generating power

If it's really that bad we can just tier it post LuV or something/remove it. Even just making like the filters horrible could work.

**Comment by DoomSquirter** [comment] 2019-07-02 22:01
* nope

* don't like the change cause I have never gotten around to abusing it yet and worried I will have missed the boat on it.  

* you all suck, and I rule.   :p 

* a year or so.  that's 7 years in dog years tho.  

sorry but too many times ppl are just throwing out things cause other ppl are doing them.  keep this up, there will be zero fun ways to scoot around and get free stuff and the only way to do something will be the official way.  then we aren't playing a pack where you have choices.  you are playing a pack with a roadmap and zero other routes to take and sorry, but that's boring as fuck.

**Comment by Shattered2909** [comment] 2019-07-02 22:58
changing some outputs is fine, nerfing the time it takes = bad

more options of getting materials from lava, gating the infinite metals behind LHE (EV), fine. it is a buff to all but the most basic setups
 
bart should admit the gay

i played for over a year, on my second run rn, at IV

**Comment by basdxz** [comment] 2019-07-02 22:58
Free copper out of lava which is free once you get the everburn urn is still kinda OP imo. You're basically spending EU for ez pz resource forever. It makes other sources of copper and gold irrelevant if you can keep it running forever. Barts nerf is a decent compromize, forcing the use of the LHE makes a lot of sense to me.

**Comment by hebiohime** [comment] 2019-07-02 22:59
-  support bart
-  support bart
-  support bart
-  support bart

**Comment by noobyaran9** [comment] 2019-07-02 23:23
So no more tin from this recipe?

Well crap, there goes my zinc plasma setup

**Comment by sthegreat** [comment] 2019-07-03 00:06
Also, I just want to mention that there is a big big difference here between singleplayer and servers with 24/7 chunkloading (this applies to any passive resource gen such as redlon). Something generating a few hundred copper per hour is totally infinite on a server but much more reasonable on sp, which is the mode I think the game should be balanced around in general.

**Comment by Methes** [comment] 2019-07-03 06:28
- Different outputs from lava and pahuehoe lava is fine. I'd like the outputs from regular lava to be more useful though, at least having sulfur. To encourage split setups.

- I wouldn't mess around with the numbers. Ever since mods were created renewable resources were a big part of them. Lately people have been growing more scared of anything that produces something and takes away the grind you have to do. Don't force everyone to use bees or crops, let other things as alternatives (xp, lava etc.)

- Been playing the pack since the beginnings of time, hell I even started making the pack with Arch, who you probably don't remember, he was Dream's predecessor.

**Comment by observeroftime02** [comment] 2019-07-03 07:34
I don't like the idea of different outputs from essentially the same input at all. But perhaps the percentages of outputs could be tweaked for Lava vs. Pahoehoe Lava. You could essentially keep the same output table, but shift the weights so that the Pahoehoe lava has a weight in favor of the more useful and desirable output. 

Lava could still be processed to give the more desirable outputs, but you would need a lot more of it, due to the nature of the weight of the outputs. This would incentivize running the Lava through a LHE to get better outputs on the Pahoehoe lava. 

This would remove the need to make the process take longer or need more lava. It could be kept the same, but by tweaking the weights of the two forms of lava you would essentially make it more costly to centrifuge lava for the more desirable outputs (due to a smaller % chance), whatever they may be.

**Comment by mitchej123** [comment] 2019-07-03 17:40
I'm fine with the output change.  Was not ok with the huge changes in time, energy, and inputs.

I would be fine with some reasonable tweaks to the time/output based on expected returns in SSP, and with a comparison to other roughly equivalent methods for obtaining the resources.

Other comments: Overall, we should be balancing for SSP, not for low population servers that run 24/7 with chunkloaders [*cough olafe/hak cough*].  Nerfing things 10x (unless they're stupid OP) just causes people to spam more of the same thing and slaughter TPS on the larger population servers.  Make it challenging, more interesting sure... but not just "do spam 10x of this for the same result as before"

🤷‍♂ 2 years or so; give or take?

**Comment by DietmarKracht** [comment] 2019-07-03 18:58
I like the change. I have been playing for almost 4 years now and i never really used the lava centrifuge recipe. i only used it for the copper singularities but nothing else

**Comment by repo-alt** [comment] 2019-07-03 21:49
Unrelated to the change, but there were 2 mentions of chunkloaders: on official servers World Anchors are disabled, so they effectively are no different from SSP in that respect.

**Comment by mitchej123** [comment] 2019-07-03 22:13
> Unrelated to the change, but there were 2 mentions of chunkloaders: on official servers World Anchors are disabled, so they effectively are no different from SSP in that respect.

Several of the people responding play on self hosted, or smaller servers with chunkloaders enabled and are basing their balancing input from that lens.

**Comment by AlexBucket** [comment] 2019-07-04 09:23
Bart’s changes sound good. 
OP, infinite resources like this should be nerfed or gated better. 

UV+ player, 4K+ hours on a server with world anchors disabled.

**Comment by Cinobi** [comment] 2019-07-09 16:32
--    Do you like the change?
Nope
--    Why do you like/dislike it?
Outputs from lava are useless(all of them), the only reason everyone uses this setup is tantallum and copper - and u want to break it.
--    Do you have any other ideas on this topic?
u can add different lavas to different planets, with different outputs in centrifuges for example, if u want to add this outputs so badly, Or, move vanilla output(this copper, gold, tantallum thingy) to some lava from distant planet(venus for example)
--    How long have you played this pack?
ALOT

**Comment by richardhendricks** [comment] 2019-07-09 17:15
- Do you like the change?
No
- Why do you like/dislike it?

For players clawing their way upwards, this is a bad change. Tantalum is the rarest ore in the game, with only a weight of 20, half that of lapis or diamond. So removing or gating that source further is a major nerf to EnderIO items which require tantalum for capacitors.

Second, lava centrifuging is a source of some key materials. Most of us are pretty jaded and experienced, but we should keep in mind new players or players who don't want to feel forced to go a certain route. This change would practically force players to get a high production glowflower farm, because it would remove an easy source of gold.

The current recipe is also a decent source of copper (a very high demand element) and silver (another high demand element). Pushing those back behind a LHE would really disadvantage players making their way up the tiers.

The suggested replacements are all pretty useless at all tiers IMO. 
- Magnesia (MgO) - Do we need a high volume source of this? Even with Rutile processing I still have many stacks of Mg.

- Silicon Dioxide (SiO2) - No, we don't need another source of this. What does this serve?

Sodium (Na) - A byproduct we already get lots of by the time you hit HV. No need for another useless source of it.

Calcite (CaCO3) - Why? Marble dust gives you plenty, and is easy to get in volume.

Potassium (K) - Do we use this at all? NaK cells only need tiny amounts, we don't need a dedicated source of it IMO.

Tungstate at 10%. - Ah, here's the problem. See my suggestion below.

- Do you have any other ideas on this topic?

Here's my idea. Leave the chances for all the drops the same, except remove Tungstate from normal lava. Replace it instead with either Pyrolusite or Spessartine as a Manganese source.  Now players can use garnets or other small Manganese sources to get into HV, then use lava centrifuging to get Manganese in volume for their HV machines and other stainless needs if they are unlucky and cannot find a Spessartine vein. They can still start higher end EnderIO machines once they start centrifuging for Tantalum.

Leave the Pahoehoe centrifuging recipe the same, but up the tungstate output to 2x. Now players who want to get their tungstate through lava need to build the LHE and infrastructure to get it, instead of a boring direct lava centrifuging recipe, which is fair since tungsten is IV material.

- How long have you played this pack?

2 years, including 2 starts up to EV. Both times I setup lava centrifuges using pumped Nether lava, not Everburning Urns.

**Comment by richardhendricks** [comment] 2019-07-09 17:17
> Unrelated to the change, but there were 2 mentions of chunkloaders: on official servers World Anchors are disabled, so they effectively are no different from SSP in that respect.

I disagree, passive anchors are still a big boost on the servers vs SSP. You can quit after a restart and get ~12 hours of processing before the next restart.

**Comment by Methes** [comment] 2019-07-09 19:16
Very well written Richard! Reasoning, gameplay value and balance. Awesome.

**Comment by Scottishprog** [comment] 2019-07-12 01:51
I support Richard's proposal.

Push tungsantate up a tier, leave the  rest alone.

**Comment by bartimaeusnek** [comment] 2019-07-12 04:14
RE to moronwmachinegun
No. Since Tantal is one of the Rarest ressources, it makes litterally no sense to enable upgrades that allow to get it in hughe quantites (im talking about ~7Stacks an hour) at HV age. This change would push that back to a reasonable level of difficulty, including a Multiblock in the processing chain, instead of a direct production. In addition to that, removing tungstate from the Lava would result in either a force to go to the end, at Space Tier 1, to get tungsten from endstone, or to centrifuge it from moonstone. Both alternatives arent exactly viable, and even with the Lava centrifuging, it still takes about 30min to even collect the needed dust. I agree with, if you'd need to set up Lava pumping in the Nether, it would be balanced propperly, but with the Urn mechanic, a constant free supply of materials in such a rate, is simply ridiculous and should not exist (all in all ~40Stacks of material/h). The change i suggested will push this to EV, and adds a little bit of "danger" to its mechanic due to the need of constant distilled water supply for the LHE.

**Comment by noobyaran9** [comment] 2019-07-12 04:19
>The change i suggested will push this to EV, and adds a little bit of "danger" to its mechanic due to the need of constant distilled water supply for the LHE.

I agree on this. We should reward the player if they're doing this method. 
My suggestion is change the orignal lava centrifuge recipe to be slower and at higher tier, and change the pahohoe lava centrifuging recipe to the orignal lava centrifuging speed and tier.

**Comment by Methes** [comment] 2019-07-12 05:04
Doesn't Urn need titanium? That makes it EV technically.
Also if you push this change, switch tantalum in Ender IO capacitors to something else.

**Comment by bartimaeusnek** [comment] 2019-07-12 06:58
@Methes 2 Plates which are very easy to get at HV, from aluminium gravel, for example

**Comment by richardhendricks** [comment] 2019-07-12 14:53
"Aluminium gravel" and "easy to get" don't belong in the same sentence.  I disagree with balancing around a resource that decreases as a server ages. 

If the problem is the easy unlimited resources from the urn, fix the urn.  Make it use tungstensteel plates, or dense titanium plates - either is fine with me, but I think tungsten/tungstensteel makes more sense.  Or change the alu gravel output to rutile if you want to force more infrastructure before granting the urn. 

Is there a higher level of Thaumcraft processing/machinery beyond infusion? That's probably half the problem there. There is 0 need for infinite lava at HV. There is need for the resources, including tantalum, at MV/HV. That lava can come from normal pumps in the Nether or fluid drills.

**Comment by Scottishprog** [comment] 2019-07-13 04:05
I am leaning towards dealing with the source as well. (Moving it up a tier...)
I am tired of infinite sources getting nerfed into the ground... they are there so the game as a whole isn't an intolerable drag.

For the record, I will be pumping all the lava I centrifuge, until EV at least.

**Comment by 0lafe** [comment] 2019-07-14 09:36
To moron

>So removing or gating that source further is a major nerf to EnderIO items which require tantalum for capacitors

Not really though, you always can find a tantallum vein in the nether. Manually looking for it is always an option, and using a prospector makes it more than reasonable. A single vein will give you a bunch of eio stuff in terms of capacitors. 

>force glowstone gold HV

Again not really. Hollow hill gold gives a ton for HV amounts. Even magnetite veins will give you a decent bit if you process it all. My first playthrough I didn't do HV lava or glowstone and it was never really an issue. Not to mention if glowstone is really that good that it would be what everyone does instead, maybe glowstone centrifuging needs to be changed. Even without crops it's kind of OP. 

>Copper

I think part of the point is that while it's needed, it's obtainable without lava enough that giving an infinite simple source for it isn't really a good idea. Copper without lava is also not really an issue, it's just made too simple with lava. 

>No, we don't need another source of this. What does this serve?
>Most of us are pretty jaded and experienced, but we should keep in mind new players or players who don't want to feel forced to go a certain route

That^, options are always nice. Lava is also slightly more interesting than glass proc. 

>useless other products

Potassium/Mg being infinite is nice, but maybe not a draw to use it. However Si is useful enough, and Ca has some power related uses. Personally I'd setup normal lava proc after this change to get these products, especially if P was also added. Its mostly bee/crop options rn, ash proc sorta sucks for it, and poo too from what I've seen. 

Overall I don't really support how good lava proc is for HV, and this is a good change to make getting tons of HV stuff infinitly an EV process. However... I wouldn't mind changing MgO, to one of the manganese mixes. Altho, again, with ores, and especially nether 2x now, you get a bunch from mining it.

**Comment by richardhendricks** [comment] 2020-01-09 18:12
I say reduce the tantalum output 50%, replace the tungstate with pyrolusite 50%. That offers a route to get the two, but still encourages finding a real vein.

The problem really sounds like you think the Urn is too easy to obtain.  If that's the case, that's what should be pushed up.  Maybe instead of 2 plates of titanium it should be a block and use late HV alloys like Vibrant Alloy that is post-freezer.

**Comment by quedral** [comment] 2020-01-10 23:20
I say change nothing. works perfectly well.

**Comment by Ngar1** [comment] 2020-02-19 11:54
It seems to search a solution without to solve the reason.
Reason is the lava urn is a endless and renewable source for energy and resources.
two possibilites, I think:
1. change urn lava generation in dependition of a non renewable ressource
2. remove lava urn

**Comment by GTNH-Colen** [comment] 2020-03-03 11:53
Is this issue still up for debate or did we agree the community was generally against it?

**Comment by Ngar1** [comment] 2020-03-03 12:18
from my point of view: 
endless automated ressources are the problem and not the receipt of lava processing.
=> remove lava urn

**Comment by GeicowithaBango** [comment] 2020-03-03 12:35
i dont like the system how it is rn, you shouldn’t get a decent amount of power and essential resources like copper/ tungstate. everything else is so irrelevant thats ok for me

**Comment by repo-alt** [comment] 2020-03-03 17:13
Endless automated resources are totally ok (it is a bit weird to hear the opposite in the context of this modpack), the only problem is the price/efforts/profits balance. I think proposed change is ok, meaning, you should set up heat exchanger to get anything useful from lava. (tbh centrifuging raw lava may be just plain disabled, because, really who needs infinite Mg or SiO2, and you would get enough Na & K from salt water which you would need anyway)

**Comment by GeicowithaBango** [comment] 2020-03-03 18:05
@repo-alt look up the lava centrifuging recipe. if im not mistaken, you are talking about electrolyzing obsidian dust.

**Comment by repo-alt** [comment] 2020-03-03 19:16
@GeicowithaBango I'm talking about the initial post proposal, don't think it was actually implemented.

**Comment by GTNH-Colen** [comment] 2020-03-03 20:06
Even if you removed the lava urn, it's not like there aren't other ways of getting lava. Methods that are potentially far more laggy (Pumping nether oceans for example).

**Comment by richardhendricks** [comment] 2020-03-03 20:14
Lag isn't the primary concern with this ticket.  Pumps are not a serious lag source anyways. We still have plans to look at underground fluids as well, and may add lava types to the Nether.

Getting lava that way involves a player time investment that just isn't necessary with an urn. Setup a node (doesn't even have to be a very good one) and just walk away.  How about we make the urn require some mid-tier blood magic slates?  At least that requires a decent investment into some magical infrastructure.

**Comment by mitchej123** [comment] 2020-03-03 20:20
We've got so much anti magic around here... let's stop nerfing anything that's useful from magic... OR... just remove all the magic mods and stick to tech only.  Doesn't the everburn at least require titanium or something else gated HV/EV?

**Comment by richardhendricks** [comment] 2020-03-03 20:23
I'm not anti-magic at all. But infinite lava that doesn't require any ongoing effort from the player can be OP based on the level. Per my comments earlier in thread:

> The problem really sounds like you think the Urn is too easy to obtain. If that's the case, that's what should be pushed up. Maybe instead of 2 plates of titanium it should be a block and use late HV alloys like Vibrant Alloy that is post-freezer.

**Comment by Prometheus0000** [comment] 2020-03-03 20:25
Two Titanium plates, plus you need to be able to move and energize nodes, and do the appropriate research, and make a wand/staff with enough capacity. There's a research to make a node that I don't really get that you could probably use too. Personally, I'd like the second type of lava to give different stuff at least.

**Comment by kekzdealer** [comment] 2020-03-12 11:03
@0lafe suggested new drops for Lava and Pahoehoe respectively today. bot wanted to have some production rates so here is what I came up with:

Lava (4s)        | Drop Chance       | Per day production*
|:---|:---|:---|
Ag                | 2.5% (nugget)     | 60 ingots
SiO2              | 12.5% (small pile)| 675 dusts
Al2O3             | 12.5% (small pile)| 675 dusts
MnTa2O6           | 5% (small pile)   | 270 dusts
MgO               | 5% (small pile)   | 270 dusts
CaO               | 5% (small pile)   | 270 dusts

Pahoehoe (2s) | Drop Chance | Per day production*
|:---|:---|:---|
Ag                | 2.5% (nugget)     | 120 ingots
Sn                | 10% (nugget)      | 480 ingots
Cu                | 20% (nugget)      | 960 ingots
WCa2O4            | 2.5% (small pile) | 270 dusts
P                 | 0.5% (small pile) | 54 dusts
(TiO2)2Al16H10O11 | 5% (small pile)   | 540 dusts

*Running a single centrifuge at base recipe tier for 24h
1d = 86,400s -> 43,200 LC Pahoehoe cycles

**Comment by 0lafe** [comment] 2020-03-12 11:06
^ I think the Ag in pahoehoe is meant to be an Au

**Comment by kekzdealer** [comment] 2020-03-12 11:11
I took them from you github message earlier and it said Ag for both. Does make sense to vary it though. I'll edit it.

**Comment by Prometheus0000** [comment] 2020-09-30 11:02
This already happened, why is this not closed?

**Closed by Prometheus0000** 2020-09-30 11:02 UTC
Labels: Status: RFC (request for comment)
