### ISSUE TITLE
The textures are broken

### ISSUE THREAD

**Issue by iamnotsane** [GTNewHorizons/GT-New-Horizons-Modpack#11917] opened 2022-12-03 23:31 UTC
### Your GTNH Discord Username

goatthroat#9467

### Your Pack Version

2.2.3/2.1.3

### Your Server

SP

### Type of Server

None

### Your Expectation

So i recently bought the real Minecraft after playing cracked for some time and I've started playing gtnh. Whats weird is how 2.1.3 the version my cracked launcher has worked perfectly with no problems except for some rubberbanding that is manageable but when I try to play the newer versions the textures freak out I was playing on 2.2.0 so I updated to 2.2.3 to see if it will work 

### The Reality

2.2.3 did not work either  I've been told that it might be because of my intel graphics and to downgrade them to a version before October 30 of 2021 I think but the problem is my computer is 12th gen which isn't able to downgrade that far in the past and just trying to add gtnh files to my versions file for my launcher doesn't work either (versions means instances on my cracked launcher)

### Your Proposal

i hope you can fix it somehow as I really want to play on the newer version to keep up with other YouTubers playthrough if you want to see what happens shoot me a text on discord

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment] 2022-12-03 23:45
The cracked fluid texture are fixed in latest dev. Not sure if it was fixed in 2.2.3

**Comment by iamnotsane** [comment] 2022-12-04 01:06
> The cracked fluid texture are fixed in latest dev. Not sure if it was fixed in 2.2.3

not cracked fluid texture but all textures in general

**Comment by Glease** [comment] 2022-12-04 01:50
It'll help us identify the nature of your issue if you can post a screenshot, or if you can describe the error in greater detail than *did not work*. There are some texture error we can fix (like the cracked fluid texture dream was talking about) but some other texture errors are caused by intel driver/gpu and we are powerless to help, like [this](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10965) or [this](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10490)

**Comment by iamnotsane** [comment] 2022-12-04 01:56
> It'll help us identify the nature of your issue if you can post a screenshot, or if you can describe the error in greater detail than _did not work_. There are some texture error we can fix (like the cracked fluid texture dream was talking about) but some other texture errors are caused by intel driver/gpu and we are powerless to help, like [this](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10965) or [this](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10490)

yes I have a intel driver but I'm confuse why I can still run 2.1.3 fine on a cracked launcher called launcher so idk

**Comment by chochem** [comment] 2022-12-04 02:10
to quote boubou:

intel graphics are borked since monthes now. Either you have another graphic card and you make the game use it, or you keep rolling back your intel drivers. In both cases, it's not our fault so i'm closing this

**Closed by chochem** 2022-12-04 02:10 UTC
Labels: Type: bugMinor, Status: Triage, Type: graphic card issue
