### ISSUE TITLE
constant client crash after using a titanium cell to get fluid out of a quad input hatch

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#13285] opened 2023-04-23 07:19 UTC
### Your GTNH Discord Username

LEO_PREMIUM#3437

### Your Pack Version

2.3.2

### Your Server

zeta

### Java Version

Java 8

### Type of Server

Don't know

### Your Actions

constant client crash after using a titanium cell to get fluid out of a quad input hatch

### Crash Report

[crash-2023-04-23_00.12.52-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11303079/crash-2023-04-23_00.12.52-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2023-04-23 09:08
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12170

**Closed by chochem** 2023-04-23 09:08 UTC
Labels: Type: Crash, Status: Triage
