### ISSUE TITLE
Infinite clay bucket

### ISSUE THREAD

**Issue by JodieRuth** [GTNewHorizons/GT-New-Horizons-Modpack#14071] opened 2023-07-26 07:31 UTC
### Your GTNH Discord Username

JodieRuth

### Your Pack Version

2.3.5

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

/

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132600151/1f450c05-3bea-49bc-b91a-9a8e8d829419)
As shown in the picture, the bucket has not been consumed

### Your Proposal

Fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment] 2023-07-26 07:41
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13814

**Closed by miozune** 2023-07-26 07:41 UTC
Labels: Type: bugMinor, Status: Triage
