### ISSUE TITLE
MB thaumium scoop recipe conflict with GT

### ISSUE THREAD

**Issue by truenachtara** [GTNewHorizons/GT-New-Horizons-Modpack#7075] opened 2020-12-08 15:15 UTC
#### Which modpack version are you using?
2.0.9.0

#### What did you try to do, and what did you expect to happen?
Tried to craft a Magic Bees thaumium scoop but it outputs a Gregtech scoop made of thaumium instead
![image](https://user-images.githubusercontent.com/16340367/101501863-df757980-3935-11eb-8793-765ca2b4df41.png)

#
#### What do you suggest instead/what changes do you propose?
Switching the hammer and cutters should make the MB version

**Comment by Prometheus0000** [comment] 2020-12-08 17:12
Duplicate of  #6692

**Closed by Prometheus0000** 2020-12-08 17:12 UTC
Labels: Type: duplicate
