### ISSUE TITLE
Quest Cheaper Simple Circuit #1714 Incorrect Requirements

### ISSUE THREAD

**Issue by uTired2** [GTNewHorizons/GT-New-Horizons-Modpack#10373] opened 2022-05-22 12:59 UTC
### Your GTNH Discord Username

uTired2#5206

### Your Pack Version

2.1.2.0-RC1

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

The quest Cheaper Simple Circuit requires 32 Fine Tin Wire, but to craft the NAND chip (via the NAND chip array) requires 16 Fine Copper Wire

### The Reality

The wire required by the quest cannot be used to complete the quest, copper needs to be used instead.

### Your Proposal

Change the requirements from Fine Tin Wire to Fine Copper/Annealed Copper Wire

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2022-05-22 13:03
already fixed in dev.

**Comment by miozune** [comment] 2022-05-22 13:10
Duplicate of #9420

**Closed by miozune** 2022-05-22 13:10 UTC
Labels: Type: bugMinor, Status: Triage
