### ISSUE TITLE
CrIB not functioning well (will close after confirmed fix)

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#16579] opened 2024-06-22 14:06 UTC
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

2.7.0 build 5.2.0

### Your Server

zeta

### Java Version

Java 8

### Type of Server

Thermos

### Your Expectation

crib works like it used to

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/4a436666-6532-4d2a-a892-917f59d937ee)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/4295b305-ceff-41c7-8c58-f67e4e3b12e9)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/367b832c-b7be-4622-a1ab-6248a4d4b0a9)

what's shown is 2 recipes using cribs not running, 
1. gear solidify
2. stellar mixer

they used to be running in older versions.
(break and replace does not solve the problem)

me and another guy can confirm this. chat in beta-testing channel.

### Your Proposal

this should be some recent changes, that guy reverted back to 2.6.1, and it is running fine.
please fix. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by HoleFish** [comment] 2024-06-22 15:35
Caused by https://github.com/GTNewHorizons/GT5-Unofficial/pull/2654 and probably be fixed by the third commit

**Closed** 2024-09-02 02:33 UTC
Labels: Type: bugMinor, Status: Triage
