### ISSUE TITLE
Client crashe after right-clicking a hopper with a crowbar

### ISSUE THREAD

**Issue by lacleman** [GTNewHorizons/GT-New-Horizons-Modpack#8832] opened 2021-11-13 21:24 UTC
### Your Pack Version

2.1.1.0

### Your Server

private server

### Type of Server

Multiplayer LAN

### Your Actions

Client crash  after right-clicking a hopper with a crowbar

### Crash Report
<details>
  <summary>Creash report</summary>
  
```
[04:40:00] [Server thread/INFO] [FML]: Unloading dimension 1
[04:52:38] [Netty IO #1/INFO] [FML]: Client protocol version 2
[04:52:38] [Netty IO #1/INFO] [FML]: Client attempting to join with 261 mods : BuildCraft|Silicon@7.1.23,AromaBackup@0.1.0.0,ProjRed|Expansion@1.0,ExtraBees@2.0.29.5,HardcoreEnderExpansion@1.8.8-GTNH,blocklimiter@0.53,MouseTweaks@2.4.4,Botany@2.0.29.5,dreamcraft@1.8.00,endercore@1.7.10-0.2.0.39_beta,BWCore@0.0.1,reauth@3.5.0,BuildCraft|Robotics@7.1.23,irontank@1.7.10-1.2.1,forgelin@@VERSION@,galacticgreg@1.0.3,Ic2Nei@1.2.1,openglasses@1.1-GTNH.1,GalaxySpace@1.1.7c-GTNH,betterbuilderswands@0.8.1,BiomesOPlenty@2.1.2-GTNH,LunatriusCore@1.1.2.21,gtnhtcwands@1.2.2,neieasysearch@0.8.11,openmodularturrets@2.2.11-245,ForgeMultipart@1.2.1.6,hodgepodge@1.6.8,lootgames@1.0.20,malisisdoors@1.7.10-1.13.2,berriespp@1.3.5.4,BrandonsCore@1.0.0.12,CoFHCore@1.7.10R3.1.4,malisiscore@1.7.10-0.14.3,ResourceLoader@1.3,catwalks@2.0.4,ExtraTrees@2.0.29.5,StorageDrawers@1.7.10-1.11.7-gtnh,gendustry@1.6.5.0-GTNH,TGregworks@GTNH-1.0.19,enhancedlootbags@1.0.4,BuildCraft|Energy@7.1.23,modtweaker2@0.9.6,IC2@2.2.828-experimental,WitcheryExtras_ASM@0.1-Beta,IguanaTweaksTConstruct@1.7.10-2.1.7.5,FML@7.10.99.99,Natura@2.3.0,NEIAddons|Forestry@1.12.15.41,ThE-core@1.0.0.1,BiblioWoodsNatura@1.5,<CoFH ASM>@000,Automagy@0.28.2,ProjRed|Illumination@1.0,TMechworks@0.2.16.2,LogisticsPipes@0.9.4.5.2,Australia@0.1,NotEnoughItems@2.1.5-GTNH,Thaumcraft@4.2.3.5,opensecurity@1.0.117,Waila@1.5.10,eternalsingularity@1.7.10-.1.0.4b,PlayerAPI@1.4,appliedenergistics2-core@rv3-beta-48-GTNH,NEIAddons@1.12.15.41,StorageDrawersForestry@1.7.10-1.1.2b,BiblioCraft@1.11.7,WarpTheory@1.7.10R1.0g.Custom,BuildCraft|Core@7.1.23,OpenModsCore@0.10.1,betterloadingscreen@1.3.29-GTNH,bdlib@1.9.4.109,NEIAddons|Developer@1.12.15.41,tcinventoryscan@1.0.11,ProjRed|Transmission@1.0,naturescompass@1.3.1,WR-CBE|Logic@1.4.2-GTNH,DummyCore@1.13,WitcheryExtras@GRADLETOKEN_VERSION,RWG@Alpha 1.3.2,BetterAchievements@0.1.0,inventorytweaks@1.59-dev-156-af3bc68,defaultworldgenerator@0.1-b13,InGameInfoXML@2.8.2.6,EMT@1.2.8.2,findit@1.0.1,GT++_Preloader@0.5-Beta,OpenBlocks@1.6.3,harvestthenether@1.7.10,ForbiddenMagic@1.7.10-0.575-gtnh-2,EnderStorage@1.4.8.29,gregtech@MC1710,CropLoadCoreASM@0.0.1,CarpentersBlocks@3.3.8.2,EnderIO@1.7.10-2.3.1.16_beta.31,Translocator@1.1.2.16,InfernalMobs@@VERSION@,CustomMainMenu@1.9.2,neiintegration@1.1.2,miscutils@1.7.05,MrTJPCoreMod@1.1.0.33,Roguelike@1.5.0,SpecialMobs@3.3.8,NEIAddons|Botany@1.12.15.41,sleepingbag@0.1.1,thaumicenergistics@1.1.3.1,fw@1.3.0,Aroma1997Core@1.0.2.16,CodeChickenCore@1.0.7.47,YAMCore@0.5.78,MineTweaker3@3.1.0,openprinter@0.1.0.132,GTTweaker@1.0,ThaumicTinkerer-preloader@0.1,bartworks@0.5.18,NodalMechanics@1.7.10R1.0,TravellersGear@1.16.7,adventurebackpack@1.7.10-0.9-h15-GTNH,gtneioreplugin@1.7.10-1.0.8,gadomancy@1.0.7.4,Baubles@1.0.1.10,ProjRed|Core@1.0,FloodLights@1.2.8-137,TML@4.0.3,ArchitectureCraft@1.7.2,ProjRed|Exploration@1.0,utilityworlds@1.0.9d,holoinventory@2.1.5-beta-GTNH.6,Forestry@4.3.1.44,ae2wct@1.7.10-rv3-1.8.7.7-GTNH,OpenMods@0.10.1,ifu@1.5,RIO@2.4.2,tcneiadditions@1.1.0.1,GalacticraftCore@3.0.27-GTNH,BiblioWoodsBoP@1.9,torohealthmod@1.7.10-1.0.0,tc4tweak@1.3.4,p455w0rdslib@1.0.4,tcnodetracker@1.1.2,questbook@2.1.1-1.7.10,battlegear2@1.7.10,ForgeMicroblock@1.2.1.6,Ztones@1.7.10,catwalkmod@x.x.x,ThaumicExploration@1.1.76,EnderZoo@1.7.10-1.0.18.3,MagicBees@2.5.5-GTNH,ProjRed|Integration@1.0,betterquesting@3.0.345-GTNH,controlling@1.0.0,cookingforblockheads@1.2.3-GTNH,compactkineticgenerators@1.7.10-1.0,ModMixins@0.0.1,ae2stuff@0.5.1.11-GTNH,OpenComputers@1.7.5.11-GTNH.29,kekztech@0.5,McMultipart@1.2.1.6,ProjRed|Fabrication@1.0,SuperTic@1.2.1,ExtraUtilities@1.2.12,Micdoodlecore@,Railcraft@9.12.2.1,detravscannermod@1.6.0,bq_standard@3.0.184-GTNH,WR-CBE|Addons@1.4.2-GTNH,IC2NuclearControl@2.4.3a,StevesCarts@2.0.0.b17,MCFrames@1.0,ThaumicHorizons@1.2.0.4,BiblioWoodsForestry@1.7,ironchestminecarts@1.0.4,FastCraft@1.25,Forge@10.13.4.1614,avaritiaddons@1.4b,croploadcore@0.1.4,HardcoreDarkness@1.7,tinkersdefense@1.2,OpenComputers|Core@1.7.5.11-GTNH.29,ThaumicTinkerer@2.5,OilTweak@1.0.3,AdvancedSolarPanel@1.7.10-3.5.1,AFSU@1.2.3a-Freeza,JABBA@1.2.2,angermod@0.6.1,ProjRed|Transportation@1.0,AppleCore@1.3.9,cb4bq@1,bartworkscrossmod@0.5.18,TiCTooltips@1.2.5,universalsingularities@1.7.10-8.5a,supersolarpanel@1.7.10-1.1.1-GT-NH-Mod,HungerOverhaul@1.7.10-1.0.2.DEV.80bb6db,ThaumicMachina@0.2.1,NEIAddons|CraftingTables@1.12.15.41,NEIAddons|ExNihilo@1.12.15.41,WailaHarvestability@1.1.7-GTNH,bartworkscrossmodtgregworkscontainer@0.5.18,beebetteratbees@0.2,Avaritia@1.19,craftpresence@1.8.2,ProjRed|Compatibility@1.0,ForgeRelocation@0.0.1.4,TConstruct@1.7.10-1.9.0.1-GTNH.build10,extracells@2.5.0,asielib@0.4.9,StevesFactoryManager@A92,BinnieCore@2.0.29.5,inpure|core@1.7.10R1.0.0B9,wawla@1.3.1,RelocationFMP@0.0.1.2,Genetics@2.0.29.5,mcp@9.05,Mantle@1.7.10-0.3.2.jenkins191,journeymap@5.1.4p2,appliedenergistics2@rv3-beta-48-GTNH,SGCraft@1.13.3,thaumcraftneiplugin@@VERSION@,AromaBackupRecovery@1.0,DraconicEvolution@1.0.2h,WR-CBE|Core@1.4.2-GTNH,StorageDrawersMisc@1.7.10-1.1.2b,harvestcraft@1.0.6,TaintedMagic@r7.6,TwilightForest@2.3.8dev,BuildCraft|Factory@7.1.23,ProjectBlue@1.1.6,computronics@1.6.6,GraviSuite@2.0.68u,NEIAddons|AppEng@1.12.15.41,GalacticraftMars@3.0.27-GTNH,BuildCraft|Compat@7.1.7,wailaplugins@MC1.7.10-0.2.3.2-16,HelpFixer@1.0.7,itlt@0.0.8,AWWayofTime@v1.3.3,IronChest@6.0.62.742,RandomThings@2.2.4,bugtorch@1.0.3,thaumicbases@1.4.25,SpiceOfLife@2.0.0-carrot-beta-7,WitchingGadgetsCore@1.2.13-GTNH,StorageDrawersNatura@1.7.10-1.1.1b,spongemixins@1.3.0,BuildCraft|Transport@7.1.23,StorageDrawersBop@1.7.10-1.1.1b,wanionlib@1.7.10-1.8,Aroma1997CoreHelper@1.0.2.16,chisel@release-24-5f87340,StevesAddons@0.10.17,Backpack@2.2.0,ToxicEverglades@0.1,ThaumcraftMobAspects@1.7.x-2B,botdustries@GRADLETOKEN_VERSION,witchery@0.24.1,enhancedportals@3.0.12,overloadedarmorbar@1.7.10-1.0.0,WitchingGadgets@1.2.13-GTNH,BuildCraft|Builders@7.1.23,chiseltones@@VERSION@,tectech@4.10.6-f087ad8e,BloodArsenal@1.2.2-11
[04:52:38] [Netty IO #1/INFO] [FML]: Attempting connection with missing mods [JourneyMapServer, Morpheus, netherportalfix] at CLIENT
[04:52:39] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
[04:52:39] [Server thread/INFO]: wuhu[/192.168.1.3:5931] logged in with entity id 211 at (-881.510125936792, 72.0, -46.59633363266753)
[04:52:39] [Server thread/INFO]: wuhu joined the game
[04:52:39] [Server thread/INFO] [Adventure Backpack]: Joined EntityPlayer of name: wuhu
[04:52:39] [Server thread/INFO] [EnderCore]: Sending server configs to client for com.enderio.core.common.config.ConfigHandler
[04:52:39] [Thread-15/INFO] [betterquesting]: Start force party quest sync
[04:52:39] [Server thread/INFO] [EnderCore]: Sending server configs to client for tterrag.wailaplugins.config.WPConfigHandler
[04:52:39] [Server thread/INFO] [Waila]: Player EntityPlayerMP['wuhu'/211, l='World', x=-881.51, y=72.00, z=-46.60] connected. Sending ping
[04:52:40] [Server thread/INFO] [ThaumcraftMobAspects]: The update checker has been disabled because you're running a snapshot.
[04:52:40] [Server thread/INFO] [JourneyMapServer]: On Request: Sending WorldID packet to: wuhu
[04:52:40] [Server thread/INFO] [JourneyMapServer]: wuhu is an EntityPlayerMP attempting to send the worldId packet
[04:52:44] [Server thread/WARN] [holoinventory]: Some error while sending over inventory, no hologram for you :(
[04:52:44] [Server thread/WARN] [holoinventory]: Please make an issue on github if this happens.
[04:52:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException
[04:52:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.block.BlockHopper.func_149731_a(SourceFile:571)
[04:52:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.World.func_147447_a(World.java:1221)
[04:52:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.world.World.func_72933_a(World.java:1024)
[04:52:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.dries007.holoInventory.util.Helper.getPlayerLookingSpot(Helper.java:62)
[04:52:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.dries007.holoInventory.server.ServerEventHandler.event(ServerEventHandler.java:131)
[04:52:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.eventhandler.ASMEventHandler_1063_ServerEventHandler_event_PlayerTickEvent.invoke(.dynamic)
[04:52:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[04:52:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[04:52:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at cpw.mods.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:350)
[04:52:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.entity.player.EntityPlayer.func_70071_h_(Unknown Source)
[04:52:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.entity.player.EntityPlayerMP.localOnUpdateEntity(EntityPlayerMP.java:295)
[04:52:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at api.player.server.ServerPlayerAPI.onUpdateEntity(Unknown Source)
[04:52:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java)
[04:52:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
[04:52:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
[04:52:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.network.play.client.C03PacketPlayer$C06PacketPlayerPosLook.func_148833_a(SourceFile:20)
[04:52:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[04:52:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[04:52:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
[04:52:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[04:52:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[04:52:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[04:52:44] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]:  at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[04:53:44] [Netty IO #1/ERROR] [FML]: NetworkDispatcher exception
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
        at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:1.8.0_281]
        at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:1.8.0_281]
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:1.8.0_281]
        at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:1.8.0_281]
        at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:1.8.0_281]
        at io.netty.buffer.UnpooledUnsafeDirectByteBuf.setBytes(UnpooledUnsafeDirectByteBuf.java:436) ~[UnpooledUnsafeDirectByteBuf.class:?]
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:870) ~[AbstractByteBuf.class:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:208) ~[NioSocketChannel.class:?]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:87) [AbstractNioByteChannel$NioByteUnsafe.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:480) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:447) [NioEventLoop.class:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:341) [NioEventLoop.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:101) [SingleThreadEventExecutor$2.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
[04:53:44] [Server thread/INFO]: wuhu lost connection: TranslatableComponent{key='disconnect.genericReason', args=[Internal Exception: java.io.IOException: 远程主机强迫关闭了一个现有的连接。], siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null}}
[04:53:44] [Server thread/INFO]: wuhu left the game
```
  
</details>

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by lacleman** [comment] 2021-11-13 21:32
client log
[2021-11-14-6.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7532782/2021-11-14-6.log)

**Comment by mitchej123** [comment] 2021-11-13 21:33
Which crowbar is being used? GT, RC, other?

**Comment by Glease** [comment] 2021-11-13 21:33
Sounds like a duplicate of #7918.

**Comment by Glease** [comment] 2021-11-13 21:36
IIRC this happens when the hopper rotates to an invalid direction, or otherwise somehow get an invalid metadata, which wrecked havoc in one of these two lines

https://github.com/GTNewHorizons/Hodgepodge/blob/bbfb7fa92fa29d9e4d0f18442f19a0cf63e04e26/src/main/java/com/mitchej123/hodgepodge/mixins/fixHopperHitBox/MixinBlockHopper.java#L71-L72

**Comment by lacleman** [comment] 2021-11-13 21:38
> Which crowbar is being used? GT, RC, other?

GT

**Comment by Glease** [comment] 2021-11-13 21:40
Partially addressed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/529, where I fixed the source of invalid hopper state. Maybe we should add a fallback case for that EnumMap, or maybe we can just call this done.

**Comment by lacleman** [comment] 2021-11-13 21:42
client crashes every time when I try to rejoin the server, what should I do?

**Comment by Glease** [comment] 2021-11-13 21:45
Ask someone else on the server to break the hopper with TNTs, block breakers or worldedit BUT without looking at the hoppers. 

Also take note to not rotate hoppers with soft mallets until your server upgrades to e.g. 2.1.1.2.

**Comment by lacleman** [comment] 2021-11-13 21:47
> Ask someone else on the server to break the hopper with TNTs, block breakers or worldedit BUT without looking at the hoppers.
> 
> Also take note to not rotate hoppers with soft mallets until your server upgrades to e.g. 2.1.1.2.

thanks!

**Comment by bombcar** [comment] 2021-11-13 23:09
note that Multiplayer LAN may cause all sorts of fun crashes in other areas and isn't recommended. Better to run a server and a client on the same machine.

**Comment by Glease** [comment] 2021-11-13 23:10
There might be some confusion with what type of server means what, and there is also this language barrier. I guess he meant a forge server on LAN.

**Comment by lacleman** [comment] 2021-11-13 23:27
> note that Multiplayer LAN may cause all sorts of fun crashes in other areas and isn't recommended. Better to run a server and a client on the same machine.

I do run the server and my client on the same machine, and my client only crashed once. But my friend crashed 3 or 4 times during some 20 hours gameplay, and he needs to restrat his client in order to rejoin the server.

**Comment by lacleman** [comment] 2021-11-13 23:28
I used mcedit to delate that hopper and now i can join the server. problem solved. thanks @Glease

**Closed** 2021-11-14 14:42 UTC
Labels: Status: FixedInDev, Type: Crash, Status: Triage
