### ISSUE TITLE
ZPM modules spawn only partially charged

### ISSUE THREAD

**Issue by NeroOneTrueKing** [GTNewHorizons/GT-New-Horizons-Modpack#7691] opened 2021-03-22 22:35 UTC
#### Which modpack version are you using?
2.1.0.0
#
#### What did you try to do, and what did you expect to happen?
Got super excited at finding a ZPM module on Ross (no EV or IV machines yet, sadly)
#
#### What happened instead? (Attach screenshots if needed)
...but it appears to have been generated with what looks like maxint32 value of stored eu... about 1/1000th of its expected storage.
![image](https://user-images.githubusercontent.com/28197216/112066320-20d01480-8b34-11eb-82c0-f62fa9e95a65.png)

#
#### What do you suggest instead/what changes do you propose?
At only 2e9 eu, it's actually incredibly unimpressive. Baby's first power substation holds almost that much eu. Since Ross is a T3 planet, we can assume the player has at least 1A EV constant power generation, which generates that much eu in 14.5 hours. Nevermind that it can't even be used without a ZPM battery buffer and LuV and IV transformers. 

#
#### What is your GTNH Discord username?
NeroOneTrueKing

**Comment by johnch18** [comment] 2021-03-22 23:12
If you take a close look at that number, you can see that it's the maximum value for an unsigned int.

**Comment by alphaNOVAircraft** [comment] 2021-03-23 11:20
Duplicate of #7161

**Closed** 2021-03-23 11:23 UTC
Labels: Type: duplicate
