### ISSUE TITLE
CoAL not crafting some UIV components

### ISSUE THREAD

**Issue by Ismaster84** [GTNewHorizons/GT-New-Horizons-Modpack#14960] opened 2023-11-29 13:51 UTC
### Your GTNH Discord Username

Ismaster

### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

The CoAL cant craft UIV Robot arms and UIV Pistons it crafts all other UIV components. I tryed putting a circuit directly on the crafting inpu buffer change to other buffer but nothing works. I reinstalled the modpack maybe 2 or 3 times on the server. If i install the 2.4.1 update this is solved but there are other bugs and i went back to 2.4.0. My CoAL have UMV casings and a 1M UV Laser hatch

https://prnt.sc/lbT3qvBbhaP0

this is an example of trying to craft robot arms

### The Reality

It doesnt craft.

### Your Proposal

Some kind of solution

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ismaster84** [comment] 2023-11-29 13:53
I fogot to add i made new recipes when i updated from 2.3.7 and i remade the recipes with different options on the Me fluid processing terminal and nothing works. Regards and sorry for my crappy english

**Comment by miozune** [comment] 2023-12-14 14:32
Cannot reproduce with nightly 245. Also the amount of transcendent metal is 152064 mB here.

**Comment by Ismaster84** [comment] 2023-12-14 16:05
i will try to add that amount of transcendent metal and see if it solves

**Comment by boubou19** [comment] 2023-12-14 17:07
author said it is solved in 2.4.1, closing

**Closed by boubou19** 2023-12-14 17:07 UTC
Labels: Type: bugMinor, Status: Triage
