### ISSUE TITLE
World Breaker and Planet Eater have no recipes

### ISSUE THREAD

**Issue by Yoshy2002** [GTNewHorizons/GT-New-Horizons-Modpack#18385] opened 2024-12-14 12:35 UTC
### Your GTNH Discord Username

yoshy1952

### Your Pack Version

nightly 772 and rc3

### Your Server

private Server/SP

### Java Version

Java 17

### Type of Server

None

### Your Expectation

Theres a quest for all creative Tools, so every Item should be craftable

### The Reality

World breaker and Planet eater both have no recipes, while the other tools got one.

### Your Proposal

Either Questbook is not updated or the recipes went missing

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2024-12-14 12:38
the recipes are fine. just a duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13386

**Closed by chochem** 2024-12-14 12:38 UTC
Labels: Bug: Minor, Status: Triage
