### ISSUE TITLE
Can't breed the steel bee according to its specification

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#8304] opened 2021-07-28 20:32 UTC
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
I tried breeding steel bees from coal and iron bees in a hot biome
#
#### What happened instead? (Attach screenshots if needed)
Despite running with mutagenic frames (which would bump the mutation chance to 250% for guaranteed purebreds) the steel species never appeared. Since the oasis biome (200% temperature, 30% humidity) wasn't a vanilla biome I tried a desert (200% temperature, 0% humidity) to no avail.

I tried the first hot biome in singleplayer that I could find (Brushland; 119% temperature 10% humidity), and steel bees appeared as expected there.

In all cases, the IC2 steel "refined iron block" was used as the foundation.

#
#### What do you suggest instead/what changes do you propose?
- Please make sure the tooltip matches the breeding behaviour. 
- optional: localise the `ic2.blockMetalAdvIron` reference in the tooltip.
#
#### What is your GTNH Discord username?
Combuster

**Comment by MathieuDR** [comment] 2021-11-03 23:41
I have the same issue but with tin bee's. It doesn't need a specific biome but it does need a foundation block `ic2.blockMetalTin` ant I'm using the IC2 Tin block. I do agree that localizing this would be a big help.

**Comment by rv-jgentile** [comment] 2021-11-14 18:38
Chiming in to say ran into this in SP as well. Tried different amounts of heaters on an alveary while still keeping it as a Hot climate, didn't do anything to adjust humidity. Did the same biome thing as @combusterf (brushland, 119% temperature / 10% humidity) and had success there.

**Comment by MathieuDR** [comment] 2021-11-14 20:53
So do you think this is an issue with the biomes not being 100% correct, since it work in brushlands? Would be nice if someone would look into this.(

**Comment by rv-jgentile** [comment] 2021-11-14 21:32
imho, and I'm just some guy, it seems the issue *here* is just the tooltip not being super descriptive (`ic2.blockMetalAdvIron` vs something readable like `ic2 steel block`). The issue with breeding itself seems more likely from [issue 8387](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8387), which was a duplicate of [7297](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7297).

**Comment by Runakai1** [comment] 2022-05-14 13:24
I had the same problem with ruby bees. Turned out, I used the wrong bee. Some species like diamond have 2 types of bees

**Comment by Runakai1** [comment] 2022-08-11 19:05
user error

**Closed by Runakai1** 2022-08-11 19:05 UTC
Labels: Type: Suggestion, Type: Bees
