### ISSUE TITLE
GT machine with battery and programmed circuit cause significant lag

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#6399] opened 2020-07-16 09:00 UTC
#### Which modpack version are you using?
2.0.9.0

#
#### If in multiplayer; On which server does this happen? 
Delta

#
#### What did you try to do, and what did you expect to happen?
I got a ping from staff about a lagging machine - which happened to be an UV assembler. Breaking and replacing it resolved the lag initially so I took some closer look with the tricorder:

Items contained | Average time (ns/t) | Worst time (ns/t)
------------ | ------------- | -------------
empty | ~800 | ~800
circuit 1 | ~800 | 310000
circuit 9 | ~800 | 270000
battery | 3500 | 3800
circuit 1 + battery | 290000 | 300000
circuit 1 + circuit 9 + battery | 350000 | 380000

The battery was full before placed in the battery slot, no actual crafting was being done. The problem is not limited to UV assemblers - similar results were obtained from an IV assembler, and an IV mixer.

#
#### What do you suggest instead/what changes do you propose?
It appears that battery-powered machines try to do something redundant on every tick - possibly checking all recipes - which should be corrected. The above numbers account for 1/150th of available time per tick, which is a lot.

**Comment by GTNH-Afx237v7** [comment] 2020-07-17 16:42
Related to (duplicate of?) #6357

**Comment by Dream-Master** [comment] 2020-08-01 15:38
https://github.com/GTNewHorizons/GT5-Unofficial/pull/307

**Closed** 2020-09-21 21:06 UTC
Labels: FixedInDev, Lag, duplicate
