### ISSUE TITLE
Boots of the traveler NEI entry broken (runic matrix accepts only vanilla fish, in NEI all moded present)

### ISSUE THREAD

**Issue by tomasz-brak** [GTNewHorizons/GT-New-Horizons-Modpack#13384] opened 2023-04-30 18:43 UTC
### Your GTNH Discord Username

baron#9972

### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Fish from all mods would work to craft boots of the traveler.

### The Reality

Only fish from vanilla game work to craft them.

### Your Proposal

All of the fish present in the nei recipie (boots of the traveler) should work to craft the item or only vanilla fish should be present in NEI recipe.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2023-04-30 18:48
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12938

**Closed by chochem** 2023-04-30 18:48 UTC
Labels: Type: Duplicate, Type: bugMinor, Status: Triage
