### ISSUE TITLE
GT++ Fish Catcher: Cannot Shift-Right-Click items out

### ISSUE THREAD

**Issue by Isaac-Pollack** [GTNewHorizons/GT-New-Horizons-Modpack#9865] opened 2022-03-05 06:39 UTC
### Your GTNH Discord Username

Droxo#9073

### Your Pack Version

2.1.2.2QF2

### Your Server

SP

### Your Expectation

They can be piped out fine, contents can be manually left click dropped into inventory no problem, but shift-right clicking does not fast-move them.

### The Reality

Nothing happens when shift-right-clicking

### Your Proposal

Add/Fix ability to shift-right-click Fish Catcher contents into player inventory.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by draknyte1** [comment] 2022-03-05 08:12
Intended behaviour.

**Comment by Isaac-Pollack** [comment] 2022-03-05 08:16
> Intended behaviour.

I don't understand why this is intended? This serves no purpose but to hinder. Automation is a different matter all-together, which I assume is the reasoning?

**Comment by draknyte1** [comment] 2022-03-05 08:19
Because I’m lazy to implement shift clicking and that’s been the case for like 5 years. I don’t see this changing in the future either because people just automate them.

**Comment by TwoTailedFox** [comment] 2022-04-03 15:18
> Because I’m lazy to implement shift clicking and that’s been the case for like 5 years. I don’t see this changing in the future either because people just automate them.

Pwetty pwease?

**Comment by draknyte1** [comment] 2022-04-03 17:34
Why reopen? 
I don’t see anyone else implementing it at this point, they’ve had years. As far as I’m concerned, it’s intended so I’m not changing it either.

**Comment by Dream-Master** [comment] 2022-04-03 17:35
because i like this will be added too. If you not do it maybe another one can add it ?

**Comment by draknyte1** [comment] 2022-04-03 17:39
> because i like this will be added too. If you not do it maybe another one can add it ?

They haven’t done so in the last 4-5 years, so I doubt it’s ever going to change. People just use hoppers. If someone wants to do it, then they can link the PR to a closed ticket. Keeping it open serves no purpose?

**Comment by Dream-Master** [comment] 2022-04-03 17:45
ok close it if you want .

**Comment by Dream-Master** [comment] 2022-04-03 17:46
or i do :)

**Closed by Dream-Master** 2022-04-03 17:46 UTC
Labels: Type: Not a Bug, Mod: GT++, Type: Won't Change
