### ISSUE TITLE
Vein name is wrong

### ISSUE THREAD

**Issue by MaGeBZz** [GTNewHorizons/GT-New-Horizons-Modpack#17542] opened 2024-10-01 16:22 UTC
### Your GTNH Discord Username

marvinhhmagebzz

### Your Pack Version

2.7 Beta 1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

The name should be right
It says "Grossular vein" in the chat
![image](https://github.com/user-attachments/assets/b8f5eba8-b5b7-446d-93ef-d7f2940802d3)
But it is actually a manganese vein in NEI
![image](https://github.com/user-attachments/assets/4b24dd91-b707-4a2f-af6c-853c62eb94d2)

### The Reality

The vein name is wrong in text field or NEI, depends on what is considered to be wrong

### Your Proposal

Probably change the name "Manganese vein" in NEI to "Grossular vein" I guess

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lyfts** [comment] 2024-10-01 16:24
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17477
Already fixed in beta2

**Closed by Lyfts** 2024-10-01 16:24 UTC
Labels: Type: bugMinor, Status: Triage
