### ISSUE TITLE
I was chenge GTNH2.2 to 2.3 And now i no have Step Assist on Armor, Human version and Wolf Transform (Lycantrop too) 

### ISSUE THREAD

**Issue by GreedReaper117** [GTNewHorizons/GT-New-Horizons-Modpack#13535] opened 2023-05-20 21:09 UTC
### Your GTNH Discord Username

peter117#9393

### Your Pack Version

2.3.0

### Your Server

-

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

I wanna normal walk single block up but i can't totaly step Assist was off on my game. I was trying active on Armor (Ender IO End steeel full set). And still no have Step Assist. 

### The Reality

Step Assist not working i can't walk 1 block up and slab block too... (Only working in small pipe to full block)  
![2023-05-20_23 07 50](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/131276069/3c719d89-0bd6-4d43-b1cf-9c2eaa53811c)

### Your Proposal

Please help me or send tip how can have step assist. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2023-05-20 21:11
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12859

**Closed by chochem** 2023-05-20 21:11 UTC
Labels: Type: bugMinor, Status: Triage

**Comment by GreedReaper117** [comment] 2023-05-20 22:29
Hi you close this topic for duplicate but not help me. What can i made for repair my bug?

**Comment by chochem** [comment] 2023-05-20 22:31
nothing, unless you are willing to try to update the mod (might or might not be updateable in isolation) or update to a dev version of the pack (which introduces other bigger issues).

**Comment by chochem** [comment] 2023-05-20 22:32
I would just give it a try https://github.com/GTNewHorizons/AdventureBackpack2/releases/tag/1.0.12-GTNH

**Comment by Fiyorin** [comment] 2023-05-20 22:33
the other ticked claims it has been fixed
could grab a newer version from: https://github.com/GTNewHorizons/AdventureBackpack2/releases

**Comment by GreedReaper117** [comment] 2023-05-20 23:19
Thx for help :+1:
