### ISSUE TITLE
Crash on creating a world for the fisrt time after downloading the ModPack

### ISSUE THREAD

**Issue by KochyOkami** [GTNewHorizons/GT-New-Horizons-Modpack#17605] opened 2024-10-10 11:00 UTC
### Your GTNH Discord Username

Kochyokami

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

tring to redownload and change java 8 to java 23

### Crash Report

https://mclo.gs/xhdms1R

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2024-10-12 22:52
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17555

**Closed by chochem** 2024-10-12 22:52 UTC
Labels: Type: Crash, Status: Triage
