### ISSUE TITLE
Unable to breed Titanium Bees

### ISSUE THREAD

**Issue by Hyperic88** [GTNewHorizons/GT-New-Horizons-Modpack#5969] opened 2020-04-23 16:40 UTC
#### Which modpack version are you using?
.8.8
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
Trying to get Titanium bees. So ive placed block of titanium underneath the Alveary, put Aluminium princess and redstone drone and repeat process couple times bcs of the low chance. Then i tried to to that in apiary with block under and mutagenic frames. Spent 10 frames but no luck, which is weird bcs that shouldnt be that hard considering 30 boosted cycles with those frames

#
#### What do you suggest instead/what changes do you propose?
Check the recipe/chance to get those bees. They are vital to get uranium bees to progress

**Comment by Dream-Master** [comment] 2020-04-23 16:41
that was fixed in later version i guess. Need to retest with 2.0.9 when on zeta

**Comment by chochem** [comment] 2020-04-23 16:49
yeah, the issue is here: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5816

**Closed** 2020-06-07 18:51 UTC
Labels: Bees, FixedInDev, duplicate
