### ISSUE TITLE
Overworld Fluids get corrupted after 2.4.0 upgrade

### ISSUE THREAD

**Issue by Polybomber** [GTNewHorizons/GT-New-Horizons-Modpack#14658] opened 2023-10-05 05:59 UTC
### Your GTNH Discord Username

Polybomber

### Your Pack Version

2.4.0

### Your Server

Personal LAN Server

### Java Version

Java 17

### Type of Server

Other MCPC+ fork

### Your Expectation

First I should mention this save is quite old. The original world gen is GTNH version 2.1.2.3qf (I think). I was originally playing single player, but then as my world got bigger I found I started to have performance issues, so I moved the single player save to a LAN server around version 2.3.0. That was working ok, but after upgrading to version 2.4.0, my fluids seem to be corrupted. By this I mean that I have random chemicals in the OW like epichloridryin and blood instead of oil. This also isn't just cosmetic, my oil drilling rig 3 won't drill in the blood chunk anymore.

In order to upgrade the server I believe I followed the Wiki instructions properly, and I performed the following steps. 

1.) I copied and renamed 2.3.0 server folder to a 2.4.0 server folder.
2.) I deleted config, mods, scripts, libraries folders from the 2.4.0 server folder
3.) I then extracted those folders from the archive to the 2.4.0 folder
4.) I copied the server journey map folder from 2.3.0 server\config folder to 2.4.0 server\config folder
5.) I added extra mods GTNH FTBUtils, Aroma Backup, Worldedit.
6.) I copied the visual prospecting folder from 2.3.0 to 2.4.0 server folder
7.) I extracted and over wrote: lwjgl3ify-forgePatches.jar, java9args.txt, startserver-java9.bat and startserver-java9.sh to the 2.4.0 server folder.
9.) Start server and client and join server.
10.) Open journey map and click to view fluid chunks.

I performed a similar procedure to upgrade the MultiMC client. Things seem to be working well apart from this fluid corruption problem. I'm hoping there's a way to fix the problem, because I'm in IV and have put a lot of effort into this game. I haven't yet tried to prospect outside of already generated terrain to see if the same corruption exists in new chunks. I also haven't checked Mars or other dimensions to see if they have similar issues.

### The Reality

My save seems to have various weird fluids like blood and Epichloridryin 
![04-10-2023 2-32-20 AM](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/53232010/da3e7e5e-98e9-4158-9cfc-3857bc4b3c00)

### Your Proposal

Fluids don't change on existing generated chunks from previous versions.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment] 2023-10-05 06:23
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11310. Rescanning should fix the display.

**Closed by miozune** 2023-10-05 06:23 UTC
Labels: Type: bugMinor, Status: Triage

**Comment by Rika-TH** [comment] 2023-10-05 12:29
They said that their drilling rig will also not function, unless it also goes off of that and rescanning regens it all

The linked issues is also marked as fixed since 2.2

**Comment by Polybomber** [comment] 2023-10-06 01:11
Thanks for the suggestion to re-scan, I assume you mean with a prospector? I'll give that a try. I went back and started the 2.30 server but it now has the same misnamed fluids as the 2.4 not sure why. I recall they were at least mostly correct in 2.30.
