### ISSUE TITLE
wrong quest order

### ISSUE THREAD

**Issue by Pnc6lx** [GTNewHorizons/GT-New-Horizons-Modpack#6023] opened 2020-05-02 15:13 UTC
the convocation of the damned from bloodmagic need a tier5 orb and 25 rune of the orb to arrive the require of  15M lp.
but now in questline tier5 orb is under the conversation of the damned. if use tier 4 orb,it will need 700 rune of the orb. you cant put such rune in your alter, so this is wrong.
please fix the quest order.

**Comment by Prometheus0000** [comment] 2020-05-02 15:58
See #6003.

**Comment by chochem** [comment] 2020-05-02 23:26
Duplicate of #6001

**Closed** 2020-06-07 18:51 UTC
Labels: FixedInDev, duplicate
