### ISSUE TITLE
possible input hatch ME bug causing AALs to shut down.

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#15612] opened 2024-02-27 23:00 UTC
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

2.6.0 build 3.6.1

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

they run with no problem

### The Reality

here is an example of AALs running PICO circuits. 
old design with no issue running:
for this design i give excess recipe fluids in AE sub net to keep it running.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/4405d1cc-2681-406d-a089-8aa8b5596fad)

new design which only replace the p2p fluid distribution to input hatch ME:
for this design, i keep nothing in the subnet.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/1e9e258d-5724-4786-bade-c0113bad76de)

The new ones tend to shutdown within a day, with no crash text in AAL main block.

### Your Proposal

not sure what caused it, plz help test it out.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by NotAPenguin0** [comment] 2024-04-18 13:41
Duplicate of #15836

**Closed by NotAPenguin0** 2024-04-18 13:41 UTC
Labels: Type: bugMinor, Status: Triage
