### ISSUE TITLE
Crash when opening AE2 Crafting Terminal

### ISSUE THREAD

**Issue by Blade8895** [GTNewHorizons/GT-New-Horizons-Modpack#18265] opened 2024-12-08 14:52 UTC
### Your GTNH Discord Username

Blade8895

### Your Pack Version

2.7.0

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Actions

Opened AE2 Crafting Terminal and got a Crash to Menu. 
After that i just got disconnected after opening the Terminal.
Restart fixes the problem

Cant Reproduce now

### Crash Report

[crash-2024-12-08_15.44.09-client.txt](https://github.com/user-attachments/files/18052680/crash-2024-12-08_15.44.09-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Stratofish** [comment] 2024-12-08 18:38
This also just happened to me. 2.7.0 with my client on Java 20 (openJDK), connected to my own server

I had been playing for about 2 hours with no issues, then while searching for "emitter" I got to "em" and it kicked me out with the same error message as in the log above. Going back in I could play normally and use my own inventory fine. I cleared my NEI filter and tried an ME terminal again, instantly kicked out

I created a new single player world, gave myself enough bits in creative for a simple ME network and tried that. The terminal still had the "em" prompt but didn't crash. I removed it and logged out and back into my server. I could now access ME again until I typed "o" in the ME filter and then it broken again just like before. This time the single player world also crashed but I didn't try and create another one.

I searched and found this report. Restarted my client as suggested above and it works again as normal now. I doubt the "em" or "o" are the cause but thought I'd mention them while I remembered

**Comment by Wo0kiee** [comment] 2024-12-09 20:09
Happened to me too. 
So i noticed after the crash that NEI doesnt respond to search bar. And openning any terminal leads to Crash to main menu. 
Tried openning Universal, Crafting, Arcane Crafting Terminals.
Client reload fixes it

Also **Search Box Mode**: NEI Synchronized Standart with **Save Search String**: On

I managed to turn off **Save Search String**. After that terminal didn't crash unless i type anything in search bar
Also while terminal was accesible i tried to scroll it all the way (no broken items)

![image](https://github.com/user-attachments/assets/5211bc7c-fe7e-4d82-b3d3-7e1b048687d5)

Can't Reproduce

2.7.0
Java 21 Eclipse
my own server, forge
[crash-2024-12-09_22.37.03-client.txt](https://github.com/user-attachments/files/18067315/crash-2024-12-09_22.37.03-client.txt)

**Comment by boubou19** [comment] 2024-12-09 20:13
probably the same thing as mine https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18288

**Comment by slprime** [comment] 2024-12-09 20:16
hm.... I can't understand how this can happen, because the filter can never be empty.  I'll try to find the reason

**Comment by gchan510** [comment] 2024-12-10 18:59
Locking/unlocking the ReentrantLock in the ItemFilterCache constructor fixed this for me; I'm not too familiar with how threading works in Java though so please verify.

**Comment by aofekiko** [comment] 2024-12-12 22:56
The same issue happened to me with the string "bio ca"

**Comment by Eldrinn-Elantey** [comment] 2024-12-16 20:05
My friend who we play with on my server has this problem too. So far, he has disabled NEI search and AE2 terminal sync for now.
[crash-2024-12-16_01.26.50-client.txt](https://github.com/user-attachments/files/18156564/crash-2024-12-16_01.26.50-client.txt)

**Comment by serenibyss** [comment] 2024-12-17 19:16
Fixed by https://github.com/GTNewHorizons/NotEnoughItems/pull/569

**Closed by serenibyss** 2024-12-17 19:16 UTC
Labels: Crash, Status: Triage
