### ISSUE TITLE
Performance (TPS) hit on 2.2.9-4dev

### ISSUE THREAD

**Issue by Eranicus** [GTNewHorizons/GT-New-Horizons-Modpack#12336] opened 2023-01-22 02:59 UTC
### Your GTNH Discord Username

Eranicus#5476

### Your Pack Version

2.2.8 - 2.2.9-4dev

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

.

### The Reality

I updated to test 2.2.9-4 dev and received +1-1.2 ms from nothing compared to version I play which is 2.2.8 . 

Then I decided to check 2.2.9-3 dev build ,  tps was good and identical to 2.2.8

Conclusion: something is seriosly broken in  2.2.9-4 dev

(I tested all versions on absolutely identical world backup)

### Your Proposal

Unfortunately I don't know the reason... but problem is in some changes between 2.2.9-3dev and 2.2.9-4dev

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2023-01-22 11:02
+1-1.2 ms doesn't sound 'seriously broken' but you can always try to analyze where the difference is coming from, so it can be optimized!

**Comment by boubou19** [comment] 2023-01-22 11:13
saying overall tick time changed is good, but providing a comparison between your lag sources before and after upgrading is better. You cannot expect us to find what caused this in the giant haysack that is GT:NH. Especially for a single millisecond of additional load. At worse it could even be caused by external load on your cpu, or a change in your driver configurations. We will be happy to fix lag sources, but we need you to help us spot from where it comes. If you don't, then this ticket is useless.

**Comment by Eranicus** [comment] 2023-01-23 09:17
> 

I did more testing and this is what I got so far: 

This is 100% not extra load on my cpu or any new drivers. 

Currently I asked one more person with big base to update to 2.2.9-4dev and to confirm or deny tps increase. 

But right now i did the following, I reinstalled clean 2.2.9-4dev and switched gregtech-1.7.10-5.09.41.232 (the one in 2.2.9-4dev) for gregtech-1.7.10-5.09.41.218 (the one from 2.2.9-3dev)  loaded the pack and tps is now exactly the same how it was before on 2.2.8 without +1-1.2ms. of avarage tick time.

Will try to go to different versions one by one from 218 to 232 then I get some time to determine what caused it.

**Comment by Hikari1nVoid** [comment] 2023-01-23 21:55
Any extra data from Opis/timingsv2?

**Comment by Eranicus** [comment] 2023-01-24 02:37
I checked different gregtech versions and the last version which has no tps difference is gregtech-1.7.10-5.09.41.218 , starting with gregtech-1.7.10-5.09.41.219-pre tps gets worse. 

Anyway this is all i can do and since nobody else confirm or deny worse performance in latest versions , feel free to close ticket.

**Comment by Glease** [comment] 2023-01-25 03:49
The only difference between those two versions that affect MTE (not MuTE) is https://github.com/GTNewHorizons/GT5-Unofficial/pull/1654. @mitchej123 it appears the extra layer of calling will cause small but noticeable lag on larger bases. might need to do a partial revert.

**Comment by Glease** [comment] 2023-01-25 03:51
BTW please don't test with -pre builds. They are highly unstable and might damage your save file. They sometimes will crash on start outright.

**Comment by Eranicus** [comment] 2023-01-25 08:31
> BTW please don't test with -pre builds. They are highly unstable and might damage your save file. They sometimes will crash on start outright.

Im testing with separate instances , my main game is still 2.2.8. And without such tests it would be very hard to determine the problems later on....

Im very glad you found the reason for this extra lag.

**Comment by chochem** [comment] 2023-01-25 08:48
yea, please DO test with dev builds of the pack dream puts out. Just know that it is testing and keep your main version, exactly as you say. Thank you!

Without testers it is the next release/stable that might be 'highly unstable and damage your save file'.

**Comment by Eranicus** [comment] 2023-02-06 05:47
What connection does 2.1.2.4-25-pre ticket has to do with this one ? 

Here the problem is worse TPS and the problem is clearly in gregtech-1.7.10-5.09.41.219-pre

**Comment by Alastors** [comment] 2023-06-15 00:45
The other issues related to this are closed as complete so I presume this is as well

**Comment by Alastors** [comment] 2023-06-15 00:45
*fixed in 2.3.2

**Closed by Alastors** 2023-06-15 00:45 UTC
Labels: Type: bugMinor, Status: Triage
