### ISSUE TITLE
Hempcrete powder un-craftable due to wheat

### ISSUE THREAD

**Issue by VIgilanteofLight** [GTNewHorizons/GT-New-Horizons-Modpack#13904] opened 2023-07-09 17:37 UTC
### Your GTNH Discord Username

Vigilante_of_Light (vigilante_of_light)

### Your Pack Version

2.3.4

### Your Server

private server

### Java Version

Java 17

### Type of Server

None

### Your Expectation

Tried to craft hempcrete powder following the NEI recipe. Tried in crafting grid and AE crafting terminal.

### The Reality

Using the autofill feature fills the sand in the recipe but does not autofill wheat. This happens in both the crafting table and AE crafting terminal, when wheat is available. Manually filling out the recipe does not allow crafting of the item either.
![2023-07-09_18 32 34](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/121089248/b232ae22-2605-486a-a0e0-cf096fb0c7ce)

### Your Proposal

I am unsure what is needed to fix this, maybe it's an item ID clash? Others have said it could be there are two different wheat items that are clashing.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2023-07-09 17:39
I already fixed that :)

**Comment by chochem** [comment] 2023-07-09 17:39
also duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13702 I guess

**Closed by chochem** 2023-07-09 17:39 UTC
Labels: Type: bugMinor, Status: Triage
