### ISSUE TITLE
Crash when clicking the search button in the quest book

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#16194] opened 2024-05-07 01:25 UTC
### Your GTNH Discord Username

hallucinogender

### Your Pack Version

Nightly 463

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Actions

I updated from 2.6.0 to Nightly 463. I opened my save. I opened the quest book. I clicked the search button in the quest book. After a brief moment, the game crashed to main menu. This appears to happen every time I click the search button in the quest book on this version of the modpack.

### Crash Report

[crash-2024-05-07_02.21.38-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15228256/crash-2024-05-07_02.21.38-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Ngar1** [comment] 2024-05-07 04:52
see #16117

**Comment by Glease** [comment] 2024-05-09 06:50
Duplicate of #16117. Thanks Ngar1

**Closed by Glease** 2024-05-09 06:50 UTC
Labels: Type: Crash, Status: Triage
