### ISSUE TITLE
Crash Related to Spice of Life

### ISSUE THREAD

**Issue by Irgendwer01** [GTNewHorizons/GT-New-Horizons-Modpack#16186] opened 2024-05-06 02:51 UTC
### Your GTNH Discord Username

Irgendwer5308

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

I don't know the exact steps, but this one triggered it most of the time:
1. Load World
2. Open QB
3. Trying to open the quest "Clay: The Gathering"
4. See Crash

It also crashed one time when trying to open and then close the chest, but I wasn't able to reproduce that one.

### Crash Report

QB:
https://mclo.gs/aE2xoXf
Chest:
https://mclo.gs/q4LrZYQ

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment] 2024-05-11 02:33
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14471, try reinstalling the pack

**Closed by miozune** 2024-05-11 02:33 UTC
Labels: Type: Crash, Status: Triage
