### ISSUE TITLE
large fluid cells not showing liquid texture.

### ISSUE THREAD

**Issue by jesuseduardo90** [GTNewHorizons/GT-New-Horizons-Modpack#8392] opened 2021-08-11 18:44 UTC
#### Which modpack version are you using?
2.1.1.0

#### What did you try to do, and what did you expect to happen?
just the large steel fluid cells doesnt show the liquid that has inside like any other normal cell or universal cell does, i think any large cell doesnt show it (steel, tungten, aluminiuiuiuim, etc..)(not tested)

#### What do you suggest instead/what changes do you propose?
fix that:v idunno is not that bad just a visual bug.

#### What is your GTNH Discord username?
jes_eduardo90#6931

##screenshot
<img width="282" alt="cell" src="https://user-images.githubusercontent.com/78877858/129085431-ac28b4d0-2fcc-4df3-8d16-92686db37a8e.png">

**Comment by jesuseduardo90** [comment] 2021-08-11 20:04
oh extra info, insalled on other computer fresh dowload same issue, not optifine issue.

**Comment by Prometheus0000** [comment] 2021-08-11 20:31
It's not a bug, there's no code to do it right now.

**Comment by Prometheus0000** [comment] 2021-08-11 20:41
You don't need to close it, people want this, just no one's done it yet, so it's a feature request instead of a bug report.

**Comment by jesuseduardo90** [comment] 2021-08-12 18:14
yeah actually i came back because i tought this could be a "suggestion"(but you tought it first:v), for the pack now that the new directly click with cell system implemented in te last update the cellsusage increse by alot:v

**Comment by GTNH-Afx237v7** [comment] 2021-08-29 09:54
Works fine for me with the PR by TimeConqueror; consider it fixedindev.

**Closed** 2021-08-29 10:33 UTC
Labels: Type: suggestion, Status: FixedInDev, Mod: GT
