### ISSUE TITLE
Fluid detection cover causes crash when the threshold is used

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#9368] opened 2022-01-05 21:41 UTC
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.2.0

### Your Server

Delta

### Type of Server

Thermos

### Your Actions

1. place a giant output hatch
2. place a fluid detector cover
3. set the threshold to 99000000
4. remove the cover with a crowbar (block should be invisible now)
5. place again the cover
6. enjoy the crash

### Crash Report

<details>

<summary> crashlog </summary>

```
java.lang.ClassCastException: Cannot cast gregtech.common.covers.GT_Cover_LiquidMeter$LiquidMeterData to gregtech.api.util.ISerializableObject$LegacyCoverData
	at java.lang.Class.cast(Unknown Source)
	at gregtech.api.util.GT_CoverBehaviorBase.forceCast(GT_CoverBehaviorBase.java:53)
	at gregtech.api.util.GT_CoverBehaviorBase.isGUIClickable(GT_CoverBehaviorBase.java:198)
	at gregtech.api.metatileentity.BaseMetaTileEntity.onRightclick(BaseMetaTileEntity.java:1470)
	at gregtech.common.blocks.GT_Block_Machines.func_149727_a(GT_Block_Machines.java:361)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(Unknown Source)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.lang.Class.cast(Unknown Source)
	at gregtech.api.util.GT_CoverBehaviorBase.forceCast(GT_CoverBehaviorBase.java:53)
	at gregtech.api.util.GT_CoverBehaviorBase.isGUIClickable(GT_CoverBehaviorBase.java:198)
	at gregtech.api.metatileentity.BaseMetaTileEntity.onRightclick(BaseMetaTileEntity.java:1470)
	at gregtech.common.blocks.GT_Block_Machines.func_149727_a(GT_Block_Machines.java:361)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78760_a(Unknown Source)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1447)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953)
```

</details>

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment] 2022-01-05 21:44
Duplicate of #9244

**Closed by Glease** 2022-01-05 21:44 UTC
Labels: Type: Crash, Mod: GT
