### ISSUE TITLE
ME crafting cpu filled with an already finished craft until relog after thaum arcane assembler recipe

### ISSUE THREAD

**Issue by CatsLeftEar** [GTNewHorizons/GT-New-Horizons-Modpack#12279] opened 2023-01-15 11:48 UTC
### Your GTNH Discord Username

Keyla#3300

### Your Pack Version

2.2.8

### Your Server

Own server

### Type of Server

Ultramine

### Your Expectation

Tried to craft some arcane assembler recipes with me system

### The Reality

recipe was finished, cpu did not clear itself after the craft was completed
![image](https://user-images.githubusercontent.com/67397297/212538814-c9457428-42a4-4eb4-b468-9f3633bf25ba.png)
![image](https://user-images.githubusercontent.com/67397297/212538824-4bdb09cc-90fd-4235-aa98-0ef4cae9c89c.png)

### Your Proposal

fix the code or tell me how to fix it it the problem is me

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by greesyB** [comment] 2023-01-15 16:54
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12186

**Closed by greesyB** 2023-01-15 16:54 UTC
Labels: Type: bugMinor, Status: Triage
