### ISSUE TITLE
Tungsten Bee does not produce correct combs

### ISSUE THREAD

**Issue by MrWye** [GTNewHorizons/GT-New-Horizons-Modpack#10832] opened 2022-07-26 15:59 UTC
### Your GTNH Discord Username

MrWye

### Your Pack Version

2.1.2.0

### Your Server

Epsilon

### Your Expectation

Tungsten Bee is expected to produce Slag, Tungsten and Molybdenum combs, latter being specialty if conditions are met (hot, arid)

### The Reality

Instead Tungsten Bee produces Slag, Chromium and Iridium and no Tungsten or Molybdenum at all.
https://prnt.sc/6VNWvkaTDZBX
Beealizer - https://prnt.sc/mgvWsL8XkAvN

### Your Proposal

Assuming the beealizer data is correct, remove Chromium and Iridium, add  Tungsten and Molybdenum

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment] 2022-07-26 16:18
Duplicate of #9161

**Closed by miozune** 2022-07-26 16:18 UTC
Labels: Type: bugMinor, Status: Triage
