### ISSUE TITLE
Getting fluid from nothing

### ISSUE THREAD

**Issue by PredVesTNiK2142** [GTNewHorizons/GT-New-Horizons-Modpack#5915] opened 2020-04-14 10:03 UTC
#### Which modpack version are you using?
2.0.8.8
#
#### What did you try to do, and what did you expect to happen?
To get any liquid in the game, we need Water Reservoir, ME Fluid Export Bus, ME Fluid Storage Bus and a sample of the liquid you need to get. We connect Storage to Reservoir. We connect Export to any storage and indicate the liquid that you want to receive. That's all :) The endless source of fluid is ready.

P.S. Works anywhere in the AE system
P.S.S. Logically, only water should be generated in this way.
#

**Comment by draknyte1** [comment] 2020-04-14 10:26
ExtraCells is broken as fuck. 🤦🏻‍♀️

**Comment by quedral** [comment] 2020-04-14 10:49
not surprised. extracells has been buggy/laggy like this for years and there are no fixes unless you code the whole damn thing from ground.

**Comment by leagris** [comment] 2020-04-14 11:41
I'd add that Extracells is wholly useful when used **responsibly**. But, as it is a dupes nest, even the most adult and mature players have to keep an eye not to accidentally dupe fluids though. If you are a server admin, you'd better review your whitelist applications so you can trust your players not to abuse the gazillion flaws in all the mods.

**Comment by draknyte1** [comment] 2020-04-14 11:42
Is there any real reason we even still use EC2?

I’m sure the handful of useful bits could just be rewritten and put into a new mod.

**Comment by leagris** [comment] 2020-04-14 11:56
EC2 is very convenient when autocrafting on-demand recipes with fluids interfaces and crafting patterns. Example sending 36L of soldering alloy fluid with items to the assembler or circuit assembler.

EC2 is a convenient mod when used responsibly. If you feel the gut to provide feature parity with AE2 integration ore rewrite/fix this whole mod, then go for it. Although I am used to consider all mods for educated mature players only. (the kind of player who will take mods for their good, will not try to abuse flaws, avoid overloading servers… everything that need maturity and education).

**Comment by boubou19** [comment] 2020-04-14 11:59
maybe i'm doing it wrong but can't get this to work in 2803

**Comment by Prometheus0000** [comment] 2020-04-14 12:07
If someone wants to rewrite it or break out the most useful parts (though it doesn't seem to have a whole lot to it to begin with, being an addon, so I dunno if that would be all that different) they have my full support. The problem is getting someone willing to do that of course. I do wonder if maybe some of these problems are fixed in a later version? And I believe AE2 itself added some kind of fluid support too later on. Maybe it would be easier to backport changes instead of rewriting the whole thing.

PS: I confirmed this works in 2.0.8.8.

**Comment by quedral** [comment] 2020-04-14 12:31
Still removal of the mod itself will cause some issues. There are bigger cells than 64k cells exist within the mod and i am sure alot of players are using them.

**Comment by leagris** [comment] 2020-04-14 12:40
@quedral this and all the features. You cannot remove a mod like this without providing 100% of feature parity and ensuring existing blocks and items continue to work. Even if @draknyte1 manages to provides 100% feature parity with own mod, he would need to squat the `exctracells` namespace and implements all items and blocks from EC2.

For the short term and until someone has enough time and energy to rewrite EC2. I suggest we try to keep EC2 issues with dupes and lagg sources documented and spread awareness to server admins. SP players are free to ruin their own gaming experience.

**Comment by draknyte1** [comment] 2020-04-14 12:42
Stealing the modid? No problem. 
Reimplementing everything? Not worth it. Only the useful parts.

**Comment by leagris** [comment] 2020-04-14 12:44
I fear that *your* useful parts will not be *my useful parts* or anyone-else's useful parts.

**Comment by Prometheus0000** [comment] 2020-04-14 12:44
Can't we just tell people it's being removed a couple versions in advance? Like with the bees. And what specifically would people define as the useful parts? Do the higher tier cells count? Should we make a list?

**Comment by jackowski626** [comment] 2020-04-14 12:45
Maybe make a pr for the quest book that warns SP players. I haven't gotten to these cells yet but didn't know they were buggy either. If it doesn't get removed

**Comment by draknyte1** [comment] 2020-04-14 12:48
I don’t even use EC2/AE2.
But we can’t call super broken content useful if nobodies going to fix it. We can however define what works and migrate it out.

**Comment by leagris** [comment] 2020-04-14 12:49
If it is removed and not reimplemented 100% equal feature I will  just re-add EC2 or stop using/upgrading GTNH if I can't or it cause issue. As simple as that.

**Comment by Prometheus0000** [comment] 2020-04-14 12:59
I tried to sort them, but I've never used EC2 for fluids in a serious way, so I could be wrong.

Useful:
Being able to store fluids in AE.
Being able to use fluids in autocrafting with AE.
Being able to autorequest crafting of fluids via AE.
Fluid Cells
ME Fluid Terminal
ME Fluid Storage Bus
ME Fluid Import Bus
ME Fluid Export Bus
ME Fluid Level Emitter
ME Ore Dictionary Export Bus
ME Fluid Interface (block) (haven't used, but probably important?)
ME Fluid Interface (flat) (haven't used, but probably important?)
ME Fluid Assembler (haven't used, but probably important?)
ME Fluid Pattern (haven't used, but probably important?)

Not Useful:
Walrus
Certus Quartz Tank
ME Portable Fluid Storage
Fluid Vibration Chamber
Blast Resistant ME Drive
ME Drive Fixture
ME Energy Cell Fixture

Questionable:
ME Block Container (dunno what it does)
The higher tiers of normal cells
The higher tiers of crafting storage 
Wireless Fluid Terminal
Wireless Universal Terminal
ME Upgrade (these are apparently for OC?)
ME Fluid Storage Monitor
ME Fluid Conversion Monitor
ME Fluid Auto Filler (same as fluid canner, but can request fluids, but is it always buckets?)

**Comment by quedral** [comment] 2020-04-14 13:45
actually Certus Quartz tank is portable tank if you break it with ae2 wrench(works like drums but 32buckets) . many people strore their fluid in them so it is quite useful. 

Walrus is one of the two attractions EC has :D

**Comment by Prometheus0000** [comment] 2020-04-14 13:48
You should be using a large cell or dolly with an obsidian tank if you want that. It's not necessary. And you should be using super tanks by the time you get AE2 in the first place. Or drums. It loses out to the bloody gold tank, and is harder to make. 'Attractions' are not useful.

**Comment by Dream-Master** [comment] 2020-04-14 13:50
@DeForce maybe you can help with this issue ? As you know much more about this mod and fix alot of things.

**Comment by DeForce** [comment] 2020-04-14 14:08
@Dream-Master tag EC2 issues as some tag that I can filter by, when I get to look at the issues - I'll just filter by the tag.
I know that there are a couple outstanding issues.

As for the converstation - EC2 is broken as hell, but still, it does solve so many problem you can have with liquids. Just saying "remove it, rewrite it" is not a way to solve a problem. You don't have a replacement. EC2 was not written in a day, it's a complex thing built on a complex system. AE2 is not easy. 
EC2 is buggy? Yes, but it's a very powerful tool if you know how to use it. 
It's not easy to just go and write EC3, or backporting AE2 liquid system from 1.12 because no one have that amount of free time.

**Comment by quedral** [comment] 2020-04-14 14:12
> You should be using a large cell or dolly with an obsidian tank if you want that. It's not necessary. And you should be using super tanks by the time you get AE2 in the first place. Or drums. It loses out to the bloody gold tank, and is harder to make. 'Attractions' are not useful.

Respectfully you are not in position to determine what is and is not useful.

**Comment by Dream-Master** [comment] 2020-04-14 14:13
@DeForce i will make a tag for ec2 and send you the list with issues. Hope some issues can be fixed. And thanks for fixing things in the past allready.

**Comment by Prometheus0000** [comment] 2020-04-14 14:21
I'm just expressing my opinion, as we are all free to do. And cutting content that is reproduced (or exceeded) elsewhere is the first thing you should do if paring down features. Not that it matters if we're not removing stuff.

+1 to thanks as well.

**Comment by repo-alt** [comment] 2020-04-14 15:06
As for AE2 fluid system in 1.12, it is unfortunately also not dupe-free. In general fluid support in AE is very tricky.

**Comment by draknyte1** [comment] 2020-04-14 15:11
> fluid support in Forge is very tricky

Fixed. The API is shit, handling is oddly left to other mods half the time. Why they’re 100000% more prone to dupes, unlike items.

**Comment by Dream-Master** [comment] 2020-04-18 20:41
@DeForce i add the tag and will do it for the other issues as well.

**Closed** 2022-07-07 14:12 UTC
Labels: Status: Waiting for Fix, Type: bugMinor, Mod: EC2
