### ISSUE TITLE
Digester structure not showing in NEI

### ISSUE THREAD

**Issue by Csstform** [GTNewHorizons/GT-New-Horizons-Modpack#15208] opened 2023-12-23 16:57 UTC
### Your GTNH Discord Username

Csstform

### Your Pack Version

2.5.0

### Your Server

private

### Java Version

Java 17

### Type of Server

None

### Your Expectation

In 2.4.0 I was able to see the structure in NEI

### The Reality

Structure tab doesn't even exist

### Your Proposal

Add render

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2023-12-23 17:02
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15110 and fixed

**Closed by chochem** 2023-12-23 17:02 UTC
Labels: Type: bugMinor, Status: Triage
