### ISSUE TITLE
Full hopper voiding items from drawer

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#8400] opened 2021-08-13 13:35 UTC
#### Which modpack version are you using?
2111a
#
#### What did you try to do, and what did you expect to happen?
Got too much redstone from drilling and put the extra in a big drawer. Wanted to process it later but when the processing machine filled up the rest is got voided.

When i do the same with compressed chests or JABBA barrels it works as expected. Only the "Storage Drawers" - drawer is affected

demo: 

https://user-images.githubusercontent.com/7230430/129365280-30a1dce6-100a-40f2-ba91-a14febd760cf.mp4

#
#### What is your GTNH Discord username?

szajkop

**Comment by Glease** [comment] 2021-08-13 14:09
I thought we fixed it via https://github.com/GTNewHorizons/StorageDrawers/pull/9 ?

**Comment by Skiftcha** [comment] 2021-09-04 21:08
http://jenkins.usrv.eu:8080/job/StorageDrawers/14/ still voiding

**Comment by Skiftcha** [comment] 2021-09-04 22:13
looks like problem is in minecraft hopper code and this
https://github.com/GTNewHorizons/StorageDrawers/blob/4392b1538151bdbcfd43991e5b13fccd0c709ee2/src/com/jaquadro/minecraft/storagedrawers/inventory/StorageInventory.java#L161
it gets outstack of drawer (e.g. 64 items), remember it
do decrStackSize(stack, 1)
so outstack is not 63
and if it cannot put item in hopper makes setInventorySlotContents back to remembered stack with size 64
but between decreasing and setting stack back drawer does syncInventory() so outstack is already 64 and setting it back to 64 does nothing

btw this line is added to prevent some dupe

**Comment by Glease** [comment] 2021-12-23 10:37
Duplicate of #7778

**Closed** 2021-12-23 10:37 UTC
Labels: Type: bugMinor, Mod: Storage Drawers
