### ISSUE TITLE
PA Removal - Some equivalent multiblocks are still missing/tiered too far

### ISSUE THREAD

**Issue by Ultraxite** [GTNewHorizons/GT-New-Horizons-Modpack#17271] opened 2024-09-09 08:13 UTC
### Your GTNH Discord Username

deleno

### Your Pack Version

2.7

### Your Proposal

Some singleblocks like the brewery which sometimes need to be used very fast for things like lubricant have no multiblock equivalent and rely on PAs to bandaid this. others, like dehydrator, are locked much further than other similar multis in the EV-IV era because they have balance implications for more advanced processing lines (froth). 

Another major one is circuit crafting in EV-IV-Early LuV slows down significantly and PAs helped stopped singleblock inworld, in-cleanroom spam. The first assline craft can be painfully slow until you unlock prass or the CAL which itself is quite the process to craft and setup the first ones.

### Your Goal

Either make new multis for these purposes, or keep PAs for now until this problem is sorted. Maybe in the case of the dehydrator, tier it down but make it require an upgrade for froth processing similar to macstack or dangote chips.

### Your Vision

Not needlessly and hastily removing things which are not an active detriment to the pack <3

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Teykn** [comment] 2024-09-09 08:34
Regarding circuit crafting & cleanroom requirements:

If no "down-tiered simpler CAL" or equivalent multi is planned for IV tier, I feel like a suitable compromise would be to change the cleanroom's maintenance mechanics.
The cleanroom's maintenace mechanics differ from most other multiblocks since it doesn't increase power consumption/causes power failures. It instead has a maintenance item probability mechanic where the % efficiency of the cleanroom is the % chance of success for an item craft. This is incredibly cruel compared to the regular maintenance mechanic, since it doesn't shut down any machines inside, so if you have a big craft planned, you can lose a decent amount of items instead of just 1. This mechanic is made worse by the fact that there are no alert mechanics when you are:
- far away
- in a different dimension (if you're having trouble finding a moon dungeon while crafting some circuits, haha)
- chunkloading while offline (applicable to servers or SP if you go afk)

I want to advocate for the cleanroom's maintenance mechanic to be more in line with other multis. I feel that a maintenace issue should either shut down all the singleblocks inside (equivalent to a power fail, will void 1 recipe but _won't_ continue voiding other recipes) or slow down the processing speed of the machines inside.

**Comment by duckedddd** [comment] 2024-09-09 08:36
Agreed, with 90 zpm circuits for a full assembly line, and in particular, needing to do that in a cleanroom... many players will not enjoy that and will already make IV tier more of a pain point for players leaving then it already is. In addition it is also an excellent machine to bridge the gap right before obtaining access to all the multis and not having to spam sb machines for every circuit or lens. Not sure that complete sudden removal is the solution and I see no point in doing so.

**Comment by Ultraxite** [comment] 2024-09-09 08:37
> I want to advocate for the cleanroom's maintenance mechanic to be more in line with other multis. I feel that a maintenace issue should either shut down all the singleblocks inside (equivalent to a power fail, will void 1 recipe but won't continue voiding other recipes) or slow down the processing speed of the machines inside.

i think the cleanroom mechanics are ok, but maybe we need to have a slightly more accessible automatable maintenance around IV-LuV if its expected to be used for many many hours on end. holding the player hostage to basically watching their cleanroom for 4 hours while you craft the 90 zpm circuits is terrible gameplay

or we could just not delete PAs for now and avoid this problem entirely :caught:

**Comment by Reflex18** [comment] 2024-09-09 08:38
> > I want to advocate for the cleanroom's maintenance mechanic to be more in line with other multis. I feel that a maintenace issue should either shut down all the singleblocks inside (equivalent to a power fail, will void 1 recipe but won't continue voiding other recipes) or slow down the processing speed of the machines inside.
> 
> i think the cleanroom mechanics are ok, but maybe we need to have a slightly more accessible automatable maintenance around IV-LuV if its expected to be used for many many hours on end. holding the player hostage to basically watching their cleanroom for 4 hours while you craft the 90 zpm circuits is terrible gameplay
> 
> or we could just not delete PAs for now and avoid this problem entirely :caught:

There is an option for the drone center now that allows for full automation of maintenance.

**Comment by Jonodonozym** [comment] 2024-09-09 08:47
> > I want to advocate for the cleanroom's maintenance mechanic to be more in line with other multis. I feel that a maintenace issue should either shut down all the singleblocks inside (equivalent to a power fail, will void 1 recipe but won't continue voiding other recipes) or slow down the processing speed of the machines inside.
> 
> i think the cleanroom mechanics are ok, but maybe we need to have a slightly more accessible automatable maintenance around IV-LuV if its expected to be used for many many hours on end. holding the player hostage to basically watching their cleanroom for 4 hours while you craft the 90 zpm circuits is terrible gameplay
> 
> or we could just not delete PAs for now and avoid this problem entirely :caught:

How about adding a new tier of air filter casings in IV which let the cleanroom work without maintenance and possibly without power?

**Comment by Ultraxite** [comment] 2024-09-09 08:48
> There is an option for the drone center now that allows for full automation of maintenance.

i have heard about it, but the point is, is this now intended gameplay in what is already probably the hardest and most content dense tier in the entire pack? making like 16-32x  singleblock parallelization automation in a limited space in a multi that will void your shit if you have a single power or maintenance issue, unless you build this other intricate multi that can automate maintenance on top of everything else in IV?

**Comment by Reflex18** [comment] 2024-09-09 08:52
> > There is an option for the drone center now that allows for full automation of maintenance.
> 
> i have heard about it, but the point is, is this now intended gameplay in what is already probably the hardest and most content dense tier in the entire pack? making like 16-32x singleblock parallelization automation in a limited space in a multi that will void your shit if you have a single power or maintenance issue, unless you build this other intricate multi that can automate maintenance on top of everything else in IV?

Your very much right, it would not be intended gameplay as the drone center requires the player to invest into a hv tier solar panel in order to create the controller. This would require a heavy investment in an area of the pack that many regard to be a complete meme and only useable for recipes.

**Comment by dvdmandt** [comment] 2024-09-09 09:19
What if cleanroom would still have 100% crafting chance with up to one maintenance issue, then start to drop?

**Comment by chochem** [comment] 2024-09-09 09:45
CAL seems fine where it is.
Dehydrator multi I dont care one way or the other. I think its fine where it is but wouldn't complain about IV either.
lubricant could/should be added to vat I would say.

**Comment by Ultraxite** [comment] 2024-09-09 09:59
> lubricant could/should be added to vat I would say.

@chochem thats tiering large scale lubricant production till quite far away, like well into LuV tier. Not to mention Lubricant requirements start going up quite a lot around IV/LuV as you need it for every LuV component, cutting requirements for all the circuits go way up, need a lot of drilling fluid, etc. 

I guess you could argue it encourages passiving and stocking up on it early but thats still meh gameplay imo.

**Comment by Ultraxite** [comment] 2024-09-09 10:31
> > > lubricant could/should be added to vat I would say.
> > 
> > 
> > @chochem thats tiering large scale lubricant production till quite far away, like well into LuV tier. Not to mention Lubricant requirements start going up quite a lot around IV/LuV as you need it for every LuV component, cutting requirements for all the circuits go way up, need a lot of drilling fluid, etc.
> > I guess you could argue it encourages passiving and stocking up on it early but thats still meh gameplay imo.
> 
> vat is HV, not LuV.

Oh my bad, was thinking of all the bio stuff you do for wetware way later. i assumed it was locked to then cause ive never seen someone make a bac vat before then lol

**Comment by Teykn** [comment] 2024-09-09 21:55
> CAL seems fine where it is. Dehydrator multi I dont care one way or the other. I think its fine where it is but wouldn't complain about IV either. lubricant could/should be added to vat I would say.
Any thoughts regarding a cleanroom maintenance mechanic change?

**Comment by yukieiji** [comment] 2024-09-10 05:06
What about changing AL to be upgradeable like ComponentAL so that we can craft AL at an earlier tier(HV or EV?)?
This will allow some machines that can only be create using AL, such as CAL, to be craft at a lower tier
I think it would be possible to adjust the difficulty depending on the block that controls the AL tier, if recipes could be unlocked as the AL tier increases, etc.

**Comment by Reflex18** [comment] 2024-09-10 05:58
> What about changing AL to be upgradeable like ComponentAL so that we can craft AL at an earlier tier(HV or EV?)? This will allow some machines that can only be create using AL, such as CAL, to be craft at a lower tier I think it would be possible to adjust the difficulty depending on the block that controls the AL tier, if recipes could be unlocked as the AL tier increases, etc.

That sounds like a horrible idea since the assembly line is an iconic feature of LUV age next to the fusion reactor.

**Comment by Reflex18** [comment] 2024-09-10 06:40
> > That sounds like a horrible idea since the assembly line is an iconic feature of LUV age next to the fusion reactor.
> 
> Isn't it because we have kept that feature that the content has ballooned to IV and LuV and this is causing these problems?

This feature has gone beyond gtnh and is in gregtech progression in general. The issue is not the tiering of the assembly line it is the requirement to craft 90 zpm circuits at once to get to the next tier. The assembly craft should be a test of a robust platinum line as that is the major aspect of iv age.

Instead it is challenging how many iv circuit assemblers the players want to stomach building or if they want to just afk the craft over night.

**Comment by yukieiji** [comment] 2024-09-10 06:53
> This feature has gone beyond gtnh and is in gregtech progression in general. The issue is not the tiering of the assembly line it is the requirement to craft 90 zpm circuits at once to get to the next tier. The assembly craft should be a test of a robust platinum line as that is the major aspect of iv age.

It seems to me that the test could be given by requiring 90 ZPM circuits when creating the AL for LuV tier.
The purpose of my idea is that we should unlock up the AL recipe earlier and craft CAL(Unlike LuV's, it requires more IV materials.)s etc. in early tier.

**Comment by Ultraxite** [comment] 2024-09-10 06:56
> Instead it is challenging how many iv circuit assemblers the players want to stomach building or if they want to just afk the craft over night.

Its just preparing players for post-UV content :TooTroll:

(cough neutronium smelting cough)

**Comment by Ultraxite** [comment] 2024-09-10 06:59
> > This feature has gone beyond gtnh and is in gregtech progression in general. The issue is not the tiering of the assembly line it is the requirement to craft 90 zpm circuits at once to get to the next tier. The assembly craft should be a test of a robust platinum line as that is the major aspect of iv age.
> 
> It seems to me that the test could be given by requiring 90 ZPM circuits when creating the AL for LuV tier. The purpose of my idea is that we should unlock up the AL recipe earlier and craft CAL(Unlike LuV's, it requires more IV materials.)s etc. in early tier.

Theres no point going down this line of thinking, they will never retier the AL or CAL.

**Comment by Alexdoru** [comment] 2024-09-10 14:53
Could we not remove the PA from the game ? Their purpose is to emulate all the single block machines that I could have placed down anyways. Some new multiblocks with bonus got added and that's a good thing but I would like to still be able to use a PA here and there.

**Comment by Ultraxite** [comment] 2024-09-10 15:57
> Could we not remove the PA from the game ? Their purpose is to emulate all the single block machines that I could have placed down anyways. Some new multiblocks with bonus got added and that's a good thing but I would like to still be able to use a PA here and there.

yes, this is ideal, but a few people have an irrational hatred towards it and want it gone. it is literally less effort and causes 0 harm to leave it in and ignore it until MuTEs, by which time it will have to go.

for now, taking out the PA is forcing a whole bunch of extra work to be done, for very little benefit other than some people just hate the Blue Cube, but are fine with Grey Cube and Green Cube and so on.

**Comment by GirixK** [comment] 2024-11-24 21:56
Closing issue, every point in this thread has either been addressed or determined to not need a change

**Closed by GirixK** 2024-11-24 21:56 UTC
Labels: Suggestion, Status: Triage
