### ISSUE TITLE
Add TipTheScales mod to pack (higher GUI scale options)

### ISSUE THREAD

**Issue by dgealow** [GTNewHorizons/GT-New-Horizons-Modpack#14122] opened 2023-07-31 22:49 UTC
### Your GTNH Discord Username

@droideka30

(huh, guess that autoconverts to a github username link. Incidentally, that is an old alt account of mine lol)

### Your Pack Version

2.3.4

### Mod Name

TipTheScales

### The Mod to Add

Turns the GUI Scale setting into a slider, that allows for scales bigger than "large" but smaller than "auto" (on high-res screens)

### Your Reason

On a high-res monitor, the "large" scale is miniscule, but the "auto" scale is too big--the top and bottom of e.g. the gold chest UI are cut off. This mod allows scales of size 1-8, where 1-3 are "small" "medium" and "large" in vanilla settings.

### Preliminary Investigation

It seems to straightforwardly work fine. I'll update this ticket if I notice any issues.

License: https://github.com/jaredlll08/TipTheScales/blob/1.7.10/LICENSE.md (GNU LGPL v2.1)
CurseForge page: https://www.curseforge.com/minecraft/mc-mods/tipthescales

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by greesyB** [comment] 2023-08-01 00:09
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13650 which was closed due to incompatibility with Optifine

**Closed by greesyB** 2023-08-01 00:09 UTC
Labels: Type: Mod Addition, Status: Triage
