### ISSUE TITLE
AE2FC Fluid Pattern Terminal not dividing by 2 patterns

### ISSUE THREAD

**Issue by zTotto** [GTNewHorizons/GT-New-Horizons-Modpack#15906] opened 2024-04-03 13:19 UTC
### Your GTNH Discord Username

totto.

### Your Pack Version

Nightly 390

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Trying to set up a pattern (not necessarily with fluids) in a Fluid Pattern Terminal and clicking the button in the image allows you to multiply by 2 and by 8 and divide by 2 with right click inputs and outputs.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49115537/51e8b794-8731-40b0-a7e1-64a35d394c19)

### The Reality

Right clicking the button still multiplies by 2 instead of dividing

### Your Proposal

Right clicking the button divides properly

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FireWarrior2** [comment] 2024-06-21 13:07
2.6.1 still not working..

**Comment by LazyFleshWasTaken** [comment] 2024-10-28 02:01
2.7.0 still not working, and also does not work in interfaces.

**Comment by miaowwwwww** [comment] 2024-11-08 20:57
dupe of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15752

**Closed by miaowwwwww** 2024-11-08 20:57 UTC
Labels: Bug: Minor, Status: Triage
