### ISSUE TITLE
certain tiny dusts also consume schematic in packager

### ISSUE THREAD

**Issue by chadtheturtle** [GTNewHorizons/GT-New-Horizons-Modpack#8130] opened 2021-06-27 08:59 UTC
#### Which modpack version are you using?
technic 2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
Tried to use the dust schematic in a packager and have it not be consumed
#
#### What happened instead? (Attach screenshots if needed)
It was consumed with Gypsum(and NEI doesnt show the "does not get consumed in the process tab") have not searched NEI for others this is just the one I caught.
#
#### What do you suggest instead/what changes do you propose?
change the recipe to not consume the schematic 
#
#### What is your GTNH Discord username?
chadtheturtle_est_thicc

https://user-images.githubusercontent.com/66935665/123538713-33925080-d704-11eb-86ad-d1f7e5bf87dd.mp4

**Comment by GTNH-Afx237v7** [comment] 2021-06-27 09:36
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8100 ?

**Comment by Glease** [comment] 2021-06-27 10:11
Duplicate of #8100

**Closed by Glease** 2021-06-27 10:11 UTC
