### ISSUE TITLE
Thaumic Dyes

### ISSUE THREAD

**Issue by kamenskyi** [GTNewHorizons/GT-New-Horizons-Modpack#15453] opened 2024-01-31 15:51 UTC
### Your GTNH Discord Username

proventus569

### Your Pack Version

2.5.1

### Mod Name

Thaumic Dyes

### The Mod to Add

Это небольшой аддон к моду Thaumcraft который добавляет крафт брони из таумкрафта и свою броню которую можно покрасить.

### Your Reason

Разнообразит типы брони для таумкрафта

### Preliminary Investigation

Сбоев не имеется

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by kamenskyi** [comment] 2024-01-31 15:51
https://github.com/KryptonCaptain/Thaumic-Dyes
https://www.curseforge.com/minecraft/mc-mods/thaumic-dyes

**Comment by EnderProyects** [comment] 2024-01-31 19:30
Dupe of this one
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11517

**Closed** 2024-02-04 22:23 UTC
Labels: Type: Mod Addition, Status: Triage
