### ISSUE TITLE
NEI search causing crash

### ISSUE THREAD

**Issue by SkyyWasTaken** [GTNewHorizons/GT-New-Horizons-Modpack#13247] opened 2023-04-18 02:23 UTC
### Your GTNH Discord Username

Ian#0674

### Your Pack Version

2.3.2

### Your Server

Self-hosted dedicated server

### Java Version

Java 19

### Type of Server

Don't know

### Your Actions

**---I'M USING JAVA 20 BUT JAVA 20 IS NOT AN OPTION WHEN CREATING AN ISSUE---**
Steps:
Launch game using Java 20
Join world
Search "Creatix" in NEI
Upon the OpenComputers Creatix appearing, all blocks unload and GUI darkens
Unfullscreen game
Crash

If I remove the creatix from my search and swap to the page it was on, this error state goes away and I can unfullscreen the game successfully

Upon reaching this point, this is logged in my client:
[21:04:58] [Client thread/ERROR]: ########## GL ERROR ##########
[21:04:58] [Client thread/ERROR]: @ Post render
[21:04:58] [Client thread/ERROR]: 1282: Invalid operation

Notably, I can see held items (like a skeleton's bow) or fire on said skeleton. Otherwise, only my UI and the skybox are visible. Additionally, all UIs get grayed out.
![image](https://user-images.githubusercontent.com/58508101/232644961-b9abf060-a4bc-490b-9820-bf1d0e1f707e.png)

### Crash Report

[crash-2023-04-17_21.17.21-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11256997/crash-2023-04-17_21.17.21-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2023-04-18 10:19
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12876

**Closed by chochem** 2023-04-18 10:19 UTC
Labels: Type: Crash, Status: Triage
