### ISSUE TITLE
NPE when adding Sensor Kit to non-complete Lapotronic Super Capacitor

### ISSUE THREAD

**Issue by Loreili** [GTNewHorizons/GT-New-Horizons-Modpack#16383] opened 2024-05-26 20:06 UTC
### Your GTNH Discord Username

loreili

### Your Pack Version

2.6.0

### Your Server

Private Server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Actions

- Half-build a lapotronic super capacitor
- Add a Gregtech Sensor Kit to the controller
- Put the data card in to an Information Panel (I used non-advanced)

If the panel is in range, the server will crash - crash occurred for me after adding some range upgrades to the panel.

### Crash Report

java.lang.ArithmeticException: / by zero
	at java.base/java.math.BigDecimal.divideAndRound(Unknown Source) ~[?:?]
	at java.base/java.math.BigDecimal.divide(Unknown Source) ~[?:?]
	at java.base/java.math.BigDecimal.divide(Unknown Source) ~[?:?]
	at java.base/java.math.BigDecimal.divide(Unknown Source) ~[?:?]
	at RFB-Launch//util.Util.toPercentageFrom(Util.java:72) ~[Util.class:?]
	at RFB-Launch//common.tileentities.GTMTE_LapotronicSuperCapacitor.getInfoData(GTMTE_LapotronicSuperCapacitor.java:918) ~[GTMTE_LapotronicSuperCapacitor.class:?]
	at RFB-Launch//gregtech.api.metatileentity.BaseMetaTileEntity.getInfoData(BaseMetaTileEntity.java:2292) ~[BaseMetaTileEntity.class:?]
	at RFB-Launch//gregtech.common.items.GT_SensorCard_Item.update(GT_SensorCard_Item.java:71) ~[GT_SensorCard_Item.class:?]
	at RFB-Launch//gregtech.common.items.GT_SensorCard_Item.update(GT_SensorCard_Item.java:61) ~[GT_SensorCard_Item.class:?]
	at RFB-Launch//shedar.mods.ic2.nuclearcontrol.tileentities.TileEntityInfoPanel.processCard(TileEntityInfoPanel.java:729) ~[TileEntityInfoPanel.class:?]
	at RFB-Launch//shedar.mods.ic2.nuclearcontrol.tileentities.TileEntityInfoPanel.func_70296_d(TileEntityInfoPanel.java:752) ~[TileEntityInfoPanel.class:?]
	at RFB-Launch//net.minecraft.inventory.Slot.func_75218_e(Slot.java:83) ~[aay.class:?]
	at RFB-Launch//net.minecraft.inventory.Slot.func_75215_d(Slot.java:78) ~[aay.class:?]
	at RFB-Launch//net.minecraft.inventory.Container.func_75144_a(SourceFile:222) ~[zs.class:?]
	at RFB-Launch//net.minecraft.network.NetHandlerPlayServer.func_147351_a(NetHandlerPlayServer.java:883) ~[nh.class:?]
	at RFB-Launch//net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:32) ~[ix.class:?]
	at RFB-Launch//net.minecraft.network.play.client.C0EPacketClickWindow.func_148833_a(SourceFile:10) ~[ix.class:?]
	at RFB-Launch//net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
	at RFB-Launch//net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at RFB-Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at RFB-Launch//net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at RFB-Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at RFB-Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at RFB-Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

net.minecraft.util.ReportedException: Ticking block entity
	at RFB-Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
	at RFB-Launch//net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
	at RFB-Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
	at RFB-Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at RFB-Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.ArithmeticException: / by zero
	at java.base/java.math.BigDecimal.divideAndRound(Unknown Source) ~[?:?]
	at java.base/java.math.BigDecimal.divide(Unknown Source) ~[?:?]
	at java.base/java.math.BigDecimal.divide(Unknown Source) ~[?:?]
	at java.base/java.math.BigDecimal.divide(Unknown Source) ~[?:?]
	at RFB-Launch//util.Util.toPercentageFrom(Util.java:72) ~[Util.class:?]
	at RFB-Launch//common.tileentities.GTMTE_LapotronicSuperCapacitor.getInfoData(GTMTE_LapotronicSuperCapacitor.java:918) ~[GTMTE_LapotronicSuperCapacitor.class:?]
	at RFB-Launch//gregtech.api.metatileentity.BaseMetaTileEntity.getInfoData(BaseMetaTileEntity.java:2292) ~[BaseMetaTileEntity.class:?]
	at RFB-Launch//gregtech.common.items.GT_SensorCard_Item.update(GT_SensorCard_Item.java:71) ~[GT_SensorCard_Item.class:?]
	at RFB-Launch//gregtech.common.items.GT_SensorCard_Item.update(GT_SensorCard_Item.java:61) ~[GT_SensorCard_Item.class:?]
	at RFB-Launch//shedar.mods.ic2.nuclearcontrol.tileentities.TileEntityInfoPanel.processCard(TileEntityInfoPanel.java:729) ~[TileEntityInfoPanel.class:?]
	at RFB-Launch//shedar.mods.ic2.nuclearcontrol.tileentities.TileEntityInfoPanel.func_70296_d(TileEntityInfoPanel.java:752) ~[TileEntityInfoPanel.class:?]
	at RFB-Launch//shedar.mods.ic2.nuclearcontrol.tileentities.TileEntityInfoPanel.func_145845_h(TileEntityInfoPanel.java:402) ~[TileEntityInfoPanel.class:?]
	at RFB-Launch//net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
	at RFB-Launch//net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
	at RFB-Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
	... 4 more

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2024-05-26 20:08
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16167 and a few others

**Closed by chochem** 2024-05-26 20:08 UTC
Labels: Type: Crash, Status: Triage

**Comment by Loreili** [comment] 2024-05-26 23:08
Agh, failed on my search-fu before I opened. Thanks! :)
