### ISSUE TITLE
Low voltage fluid tank not keeping inventory when picked up

### ISSUE THREAD

**Issue by nigtwisj** [GTNewHorizons/GT-New-Horizons-Modpack#11332] opened 2022-09-17 10:56 UTC
### Your GTNH Discord Username

Emerald#2630

### Your Pack Version

2.2.0.0-RC-2

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

The low voltage fluid tank should be portable implied by it's description and keep its inventory when picking it up with a wrench.

### The Reality

It gets picked up into your inventory and doesn't keep its stored liquid thus voiding the liquid stored making it not portable.

https://user-images.githubusercontent.com/28225553/190853194-3303a8de-19f3-4878-be10-5d18e2b18024.mp4

### Your Proposal

The tanks should keep their liquid stored when picked up as the description implies.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment] 2022-09-17 10:59
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11289

**Closed by miozune** 2022-09-17 10:59 UTC
Labels: Type: bugMinor, Status: Triage
