### ISSUE TITLE
Can't set the item on the ProjectRed chipes

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#6276] opened 2020-06-14 10:12 UTC
#### Which modpack version are you using?
2.0.9.0QF4
#
#### If in multiplayer; On which server does this happen? 
Single
#
#### What did you try to do, and what did you expect to happen?
I tried to set up an item on the ProjectRed chipes.
#
#### What happened instead? (Attach screenshots if needed)
The item could not be set and the item that was going to be set was lost.
#
#### What do you suggest instead/what changes do you propose?
Fix it.
I've had this issue with chipes that Extractor, Responser, Stock Keeper and Broadcaster.

**Comment by yukieiji** [comment] 2020-06-15 23:16
After testing with the minimal mod environment, this issue was found to be caused by the NEI.
I have confirmed that this issue occurs with NEI from 2.0.0-beta-6 or later.

minimal mod environment:
- CodeChickenLib-1.7.10-1.1.3.140-universal
- ForgeMultipart-1.7.10-1.2.0.347-universal
- ForgeRelocation-0.0.1.4-universal
- ForgeRelocationFMP-0.0.1.2-universal
- MrTJPCore-1.1.0.33-universal
- CodeChickenCore-1.7.10-1.0.7.47-universal
- ProjectRed-1.7.10-4.7.0pre12.95(All)
- NEI

**Comment by mitchej123** [comment] 2020-06-16 01:51
Please provide screenshots.  It's probably the bookmark panel

**Comment by yukieiji** [comment] 2020-06-16 03:54
@mitchej123 
- NEI beta-5 and older
![Captcha_20200616_123909_980x505_fps3](https://user-images.githubusercontent.com/40425798/84730122-5279e500-afd0-11ea-9929-e0853d00d3c6.gif)
- NEI beta-6 and later
![Captcha_20200616_124204_980x505_fps3](https://user-images.githubusercontent.com/40425798/84730195-7b01df00-afd0-11ea-8152-0154cb9c3577.gif)

**Comment by mitchej123** [comment] 2020-06-16 04:00
Yah, that's definitely bookmark panel overlap.  What's the name of the item you use to bring up that GUI?

**Comment by yukieiji** [comment] 2020-06-16 04:07
In the screenshot, it's a screenshot of the filter that the Item Responser Chip in ProjectRed.
Other similar screens, such as Item Extractor Chip,Item Stock Keeper Chip, and Item Broadcaster Chip, also have issues.

**Comment by mitchej123** [comment] 2020-06-16 04:54
I'll need to have NEI look for those and adjust the width, similar to what it does for FTB utils

**Comment by Prometheus0000** [comment] 2020-11-06 00:20
Duplicate of #6019

**Closed by Prometheus0000** 2020-11-06 00:20 UTC
Labels: Mod: NEI, Type: bugMinor, Type: duplicate
