### ISSUE TITLE
Life capsule blood dupe

### ISSUE THREAD

**Issue by drongood12** [GTNewHorizons/GT-New-Horizons-Modpack#17886] opened 2024-11-07 13:00 UTC
### Your GTNH Discord Username

werstor

### Your Pack Version

2.7.0 nightly 709

### Your Server

private

### Java Version

Java 21

### Type of Server

Don't know

### Your Expectation

When adding a life capsule to a fluid terminal, an empty capsule is expected to return.
![image](https://github.com/user-attachments/assets/b1fcdc27-71c2-4f15-b1f3-e3ed57edb4d8)

### The Reality

![image](https://github.com/user-attachments/assets/8ebbebca-8617-406e-8fd3-577a1670956f)
blood will appear in the fluid terminal and a full blood capsule will return to the inventory (the bug only works with the wax capsule from forestry) and this can be repeated indefinitely

Reproduction of the bug:
Take a wax capsule from forestry (from beewax), pour blood from the blood altar into a tank from bc factory for example, through the right mouse button take the blood from there with the capsule and through the fluid terminal pour the blood into the ae through the capsule and see which capsule will return to you empty or with blood and whether the blood in the AE2 network  will be replenished

### Your Proposal

Make the capsule empty when added to AE2. This dupe works the same way in 2.6.1

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by drongood12** [comment] 2024-11-07 13:48
![image](https://github.com/user-attachments/assets/31a2083e-cc72-4435-bb18-fdf87167e16f)
I assume this happens with all liquid capsules from the BartWorks mod.

**Comment by serenibyss** [comment] 2024-11-07 18:26
Yes, this is a duplicate of the above issue

**Closed by serenibyss** 2024-11-07 18:26 UTC
Labels: Bug: Minor, Status: Triage
