### ISSUE TITLE
Steam Coal Boiler now outputs steam to the bottom side

### ISSUE THREAD

**Issue by Coolrune206** [GTNewHorizons/GT-New-Horizons-Modpack#13787] opened 2023-06-24 02:43 UTC
### Your GTNH Discord Username

Coolrune206

### Your Pack Version

2.3.4

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Attached wooden pipe to steam boilers bottom connection piping in water. Added bronze pipes for steam to flow out the side. Water should have kept flowing through the bottom side (as indicated by quest book) and steam should have gone through any other face.

### The Reality

Steam attempted to flow through the lower pipe as well as the side pipe, causing the wooden pipe to burn.

### Your Proposal

The quest book indicates steam should not outflow through the bottom of the boiler and it did not use to do this previously. Thus, steam should not flow out of the bottom face.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment] 2023-06-24 02:44
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13783

**Closed by miozune** 2023-06-24 02:44 UTC
Labels: Type: bugMinor, Status: Triage
