### ISSUE TITLE
Food/saturation HUD rendering glitches upon quest notifications

### ISSUE THREAD

**Issue by vovaksenov** [GTNewHorizons/GT-New-Horizons-Modpack#15039] opened 2023-12-07 23:11 UTC
### Your GTNH Discord Username

vovassgreat

### Your Pack Version

nightly 248

### Your Server

unrelated

### Java Version

Java 21

### Type of Server

None

### Your Expectation

Quest notifications do not cause render glitches.

### The Reality

White squares appear:
![image-39](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/86674724/8999b0a2-461a-468b-96ce-8a37b88023b4)

### Your Proposal

Fix the food (or maybe saturation?) rendering.
This issue was made on behalf of EvgenWarGold.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment] 2023-12-07 23:17
@Alexdoru ans idea ?

**Comment by bombcar** [comment] 2023-12-07 23:52
I don't remember seeing this on j17 but I may be mistaken, because that was also older pack.

I do get it on j21 on Mac on 252

**Comment by bombcar** [comment] 2023-12-19 16:33
note the mention above is NOT actually the fix, btw

**Comment by Alexdoru** [comment] 2023-12-19 16:58
if enabling & disabling the same GL cap in the same method is a problem, is means they shouldn't have been enabled in the first place because they were already enabled

**Comment by Caedis** [comment] 2023-12-19 17:04
so the issue is in BQ, right?

**Comment by Caedis** [comment] 2023-12-20 01:32
Fixed in https://github.com/GTNewHorizons/BetterQuesting/pull/124

**Closed by Caedis** 2023-12-20 01:32 UTC
Labels: Type: bugMinor, Type: Visual, Mod: Betterquesting
