### ISSUE TITLE
Railcraft tanks are missing a 'liquid pouring in' texture for Biodiesel

### ISSUE THREAD

**Issue by drageuth** [GTNewHorizons/GT-New-Horizons-Modpack#15086] opened 2023-12-15 01:35 UTC
### Your GTNH Discord Username

doctor_professor_robot

### Your Pack Version

2.3.2 (newest)

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

When liquid pours into Railcraft tanks, you can see liquid pouring in. 

### The Reality

The pouring-liquid texture is missing for biodiesel, making a cylinder of black and red squares
![texError](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/6870362/9fdc3ff9-436b-475f-bb0a-e20d4445dc8c)

### Your Proposal

Needs fixing

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BritishCynic** [comment] 2023-12-15 01:36
Please try this on 2.5.0-rc1 and see if the same issue occurs.

**Comment by miozune** [comment] 2023-12-15 01:40
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15017

**Closed by miozune** 2023-12-15 01:40 UTC
Labels: Type: bugMinor, Status: Triage
