### ISSUE TITLE
Natura hopper creates a crash chunk

### ISSUE THREAD

**Issue by CatsLeftEar** [GTNewHorizons/GT-New-Horizons-Modpack#8894] opened 2021-11-21 19:08 UTC
### Your GTNH Discord Username

CatsLeftEar#3300

### Your Pack Version

2.1.1.0

### Your Server

Epsilon

### Your Expectation

Natura hopper creates a crash chunk when clicked by wrench on its front side

### The Reality

crash

### Your Proposal

remove any instrument interactions with there non-mechanical hoppers

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by draknyte1** [comment] 2021-11-21 19:28
Basically a duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8832 and https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7918.

**Comment by boubou19** [comment] 2021-11-21 21:55
Dunno if Natura extends vanilla hopper or if we need to patch it there too.

**Comment by Glease** [comment] 2022-01-30 08:25
Should be fixed by https://github.com/GTNewHorizons/Hodgepodge/pull/49.

**Closed by Glease** 2022-01-30 08:25 UTC
Labels: Type: bugMinor, Status: Triage
