### ISSUE TITLE
Molten Reinforced Glass Panes and Reinforced Glass Panes recipe issue

### ISSUE THREAD

**Issue by Logos-Askrson** [GTNewHorizons/GT-New-Horizons-Modpack#8668] opened 2021-10-11 19:26 UTC
### Your GTNH Discord Username

Logos#2981

### Your Pack Version

2.1.1.0

### Your Server

Eta

### Type of Server

Thermos

### Your Expectation

I attempted to create Reinforced Glass Panes for use in infusion by placing Reinforced Glass in a cutting machine, as the NEI recipe indicated.

### The Reality

Molten Reinforced Glass Panes share a recipe with Reinforced Glass Panes, and were created instead. While the two items are equivalent for many things, infusion appears to specifically require Reinforced Glass Panes.

### Your Proposal

Either separate the recipes for these two items, or ensure that the items are equivalent for all cases.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by yukieiji** [comment] 2021-10-11 23:49
Those recipes have been fixed in #8070 and look good in my environment.
This issue is probably caused by the NEI display or MT recipes not matching between server and client
![2021-10-12_08 37 45](https://user-images.githubusercontent.com/40425798/136868179-836576e3-4afb-4dec-8bdb-e2909159d411.png)
![2021-10-12_08 42 09](https://user-images.githubusercontent.com/40425798/136868168-fcb612a6-1584-433d-a7ad-9fad0cb0fc3a.png)
.

**Closed as completed** 2021-10-13 22:18 UTC
Labels: Bug: Minor, Status: Triage
