### ISSUE TITLE
Angelica crashes client after approximately 5 minutes after login.

### ISSUE THREAD

**Issue by Sarodinianzu** [GTNewHorizons/GT-New-Horizons-Modpack#16125] opened 2024-05-01 20:41 UTC
### Your GTNH Discord Username

Sarodinian

### Your Pack Version

2.6.0.0

### Your Server

Eta

### Java Version

Java 8

### Type of Server

Don't know

### Your Actions

After fresh reinstall of the modpack to 2.6.0, and after fixing the LSC issue, client would crash approximately 5 minutes or so after login. Removing Angelica corrected this issue for the time being.

### Crash Report

[crash-2024-05-01_16.08.39-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15181189/crash-2024-05-01_16.08.39-client.txt)
[crash-2024-05-01_16.12.52-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15181190/crash-2024-05-01_16.12.52-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2024-05-03 01:16
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16075

**Closed by chochem** 2024-05-03 01:16 UTC
Labels: Type: Crash, Status: Triage
