### ISSUE TITLE
Void miners mining unnamed useless ores

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#13853] opened 2023-07-01 19:23 UTC
### Your Pack Version

2.3.4

### Your Server

Private Server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

Ever since we've updated to 2.3.4 void miners are mining a bunch of ores without a name or any use whatsoever and our ME system has a bunch of unnamed and useless dusts(?) in it.

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/39203645/3c7eac8d-1b28-4efd-8c8d-1de9a3774cb0)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/39203645/cab7eef1-a724-4f74-a554-59d6fe4cf975)

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2023-07-01 19:38
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13687

**Closed by chochem** 2023-07-01 19:38 UTC
Labels: Type: bugMinor, Status: Triage
