### ISSUE TITLE
Broken recipe: Witchwood Rod

### ISSUE THREAD

**Issue by the-bukkit** [GTNewHorizons/GT-New-Horizons-Modpack#14779] opened 2023-10-26 15:24 UTC
### Your GTNH Discord Username

the_bukkit

### Your Pack Version

2.4.0

### Your Server

SP; private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

I was looking up the Witchwood Rod recipe in NEI. I expected to see craftable items.

### The Reality

Two items don't have a crafting recipe and have the name: gt.metaitem.01.8529.name

![Screenshot_20231026_165338](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/23724545/5bfe672c-f588-441f-a92c-b660d967b01f)

### Your Proposal

Correct item in recipe.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by EnderProyects** [comment] 2023-10-26 15:29
I think this was already fixed

**Comment by the-bukkit** [comment] 2023-10-26 15:31
I haven't found any issue mentioning this but I'll try a nightly release

**Comment by chochem** [comment] 2023-10-26 15:39
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14721 and already fixed

**Closed by chochem** 2023-10-26 15:39 UTC
Labels: Type: bugMinor, Status: Triage
