### ISSUE TITLE
Drilling rig pulling up pipes bug

### ISSUE THREAD

**Issue by Extremity4** [GTNewHorizons/GT-New-Horizons-Modpack#5848] opened 2020-04-01 11:52 UTC
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
N/A
#
#### What did you try to do, and what did you expect to happen?
I'm trying to use a fluid drill T1 on natural gas, which had been placed down a long while ago. On ver 8.3, this works as expected and the pipes go down to bedrock and stay there.
#
#### What happened instead? (Attach screenshots if needed)
On 8.8, the drill seems stuck perpetually raising and lowering the mining pipes, lowering pipes until bedrock then immediately raising them back up, which vastly slows down its rate of operation.

**Comment by repo-alt** [comment] 2020-04-01 13:17
This is at least weird, I don't see any changes related to the oil drill since 8.3

**Comment by repo-alt** [comment] 2020-04-01 13:27
You may enable 'debugDriller' via command "gt toggle debugDriller" or in config (config/GregTech/GregTech.cfg, "machines" section ), and see what it says while working.

**Comment by botn365** [comment] 2020-04-01 13:32
i rebuild the drill a few blocks down and now its working normal again 
i also had the same problem in 7.5 with a T1 oil drill

**Comment by repo-alt** [comment] 2020-04-01 13:57
next time, look up the debug output before rebuilding please :)

**Comment by Larsien973** [comment] 2020-04-07 07:28
I have a drill with the same issue, endlessly raising/lowering the mining pipes. Running version 2.0.8.6.QF. Where's the output of the debug? I don't see anything in the console, tricorder, controller block or in /logs.

Additional notes:
This was built over an existing bore hole, with mining pipes in place.
There's a machine controller cover on the controller
Fluid drill tier 3, ev energy hatch

**Comment by repo-alt** [comment] 2020-04-07 14:27
> You may enable 'debugDriller' via command "gt toggle debugDriller" or in config (config/GregTech/GregTech.cfg, "machines" section ),

**Comment by Larsien973** [comment] 2020-04-08 07:04
I enabled the toggle and got the confirmation message in the chat box.  I'm not seeing any output aside from the ordinary though, where is it supposed to go? I am however able to reproduce part of my issue, not the endless looping. And that particular bit is applicable to both the multiblock fluid and ore drill, the single blocks have no issues.

1. Somehow get a mining pipe fullblock/endpiece in the drills mining path, usually left from previous mining as they're not normally placable
2. Activate drill
3. Watch as it retracts when it hits the endpiece

**Comment by repo-alt** [comment] 2020-04-08 13:26
Ah, was that mining pipe head placed before the update? Such symptoms may happen if the drill meets some block that is not a bedrock, but a drill fake player cannot remove. There was a change in fake player recently, so maybe it cannot remove blocks that it placed itself. Was the pipe column intact when you rebuilt the rig? (I will add more logs to detect such situations too)

**Comment by Larsien973** [comment] 2020-04-08 18:52
Quite possible, the original drill was placed a while ago then relocated to mars. The whole tract of pipes where left inctact and a new drill whas placed over. The testing I did was done in creative though, all in one go. That said, I am still on 2.0.8.6. which might have some bearing on the issue. 

Tested with the machine controller on and this causes the drill to automatically restart leading to the endless looping, fully reproducing my original issue. Also, it has no problem digging up the normal pipes, only the drill head.

Some further testing shows the same for "end portal frames" as expected. I'm a bit doubtful that there exist many other naturally occurring blocks that are unbreakable, leaving predrilled holes as the issue.

A possible thematic solution would be to stop the machine, force a maintenace error and print somthing along the lines of "Unstoppable force met immovable object" to the controller. Should be enough for those who encounter this to figure it out on their own.

**Comment by toadjaune** [comment] 2020-04-23 22:07
Having the same issue here, although with different trigger conditions : 

Modpack version : 2.0.8.3
Self-hosted server, admin access


So, I created the full drilling rig on this modpack version, placed it on a chunk with a big oil deposit, it extended then retracted the pipes, and stopped.

Changed chunk in the same group, same thing.

Double-checked the location by prospecting in that same chunk, there is indeed oil here in [5] in the book.

Moved the rig next to a friend's, in the same chunk as his, works fine.

Bring it back to my place, try another chunk in a different chunk group, doesn't work either.



At this point I'm pretty sure the machine itself is fine, and tend to think that the issue lies in the chunks.

Maybe something to do with my being in a place with both negative X and Z ? I honestly don't know.


Tried to activate the debug as mentioned above, but the command gt doesn't exist in my server version. Is there any way to do it ?

**Comment by repo-alt** [comment] 2020-04-23 22:27
First of all - this is _not_ the same issue.
Moreover it has nothing to do with the oil drill (that you are talking about), nor the ore drill (that is what the current issue is about)
Also, debug command just wasn't in 8.3

The bug you describe is about prospector data being off by one chunk in negative coordinates area. (https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5588)

**Comment by toadjaune** [comment] 2020-04-23 22:36
Pretty sure this issue is about the oil drilling rig, not the ore one : "I'm trying to use a fluid drill T1 on natural gas"

You're right for the rest though, thanks for pointing me to the correct issue, and sorry for posting in the wrong place !

**Comment by repo-alt** [comment] 2020-04-23 23:13
Right, this is indeed about oil drill. Unfortunately not much we can do about the original issue, since idk how to reproduce it.

**Comment by combusterf** [comment] 2020-06-04 16:57
I have a drill with a similar problem on the official server (it's pumping salt water on Europa) I've upgraded it from T1 to T3 since its original placement when its performance dropped to access some extra chunks

My hypothesis is that it encounters a chunk it considers drained within its range and therefore stops operating despite having plenty to go by.

**Comment by repo-alt** [comment] 2020-06-11 11:56
What version are you using? Where do you get information about oil?

**Comment by Pfustey** [comment] 2020-06-11 12:34
2.0.8.8
LV Seismic Prospector

**Comment by Pfustey** [comment] 2020-06-11 18:55
I have moved my rig as a test to a ~30l natural gas field, and it started outputting massive amounts of oil.

**Comment by Pfustey** [comment] 2020-06-11 18:55
The oil field starts one chunk to the right

**Comment by botn365** [comment] 2020-06-11 18:56
there is a big with the seismic prospector if 1 of the axes is negtif it has a off by 1 error this is fixed in 9.0

**Comment by repo-alt** [comment] 2020-06-11 18:56
That is weird, I was sure I fixed the seismic prospector in the 8.8

**Comment by botn365** [comment] 2020-06-11 18:59
nope 8.8 came out in march while the fix was in april

**Comment by repo-alt** [comment] 2020-06-11 19:00
ah, ok then
I looked up, the fix got in GT 5.09.33.43

**Closed** 2020-12-28 10:14 UTC
Labels: Status: can't reproduce, Type: bugMinor, Type: help wanted
