### ISSUE TITLE
Pyrolyse Oven Stalls when One Recipe will Overflow, But Second will Not

### ISSUE THREAD

**Issue by desagas** [GTNewHorizons/GT-New-Horizons-Modpack#13866] opened 2023-07-02 20:05 UTC
### Your Pack Version

2.3.4

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

My pyrolyse oven has two of each of the following: input bus (1 for circuits and 1 for mulch), output bus (not used for anything), input hatch (water and biomass), output hatch (1 locked to biomass and 1 to fermented biomass). And, the oven itself it is set to void nothing.

The expected behavior would be to check if other recipes will pass the no void check if the currently recipe fails the no void check (I assume this feature already has such a Boolean check in place, which is what forces the oven to stop running). Meaning, if one recipe will not process because it would need to void, it should check for other possible recipes that will no void, based on current inputs, rather than simply not working.

### The Reality

My setup works as intended, creating biomass with mulch with the #1, and then exporting that to the input hatch, creating fermented biomass with #2, until the fermented biomass output hatch becomes full, where the oven stops working entirely, even though one recipe is valid. I also know that this is not because there are mutliple unused inputs, like water when created fermented biomass, because it still works, until the hatch is full, as described, which means this check is also already in place.

I would understand if this happened and was locked to a certain recipe in the oven's gui, however, this is not the case. No recipe is locked, and both recipes work fine until one, at random (logically assigned by block check code) I assume, is full.

### Your Proposal

My proposal is very simple, in theory: make the code for void checks identical to the code for valid recipe checks, where it checks if the previously successful recipe has valid inputs, and if not, it checks for other valid recipes with current inputs, until valid recipes no longer exist, and then shut off. Except, in this case, it checks if there is adequate room for outputs before checking other possible recipes with current inputs.

I assume this is not unique to the pyrolyse oven, but is identical in all multiblocks that have the overflow feature.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2023-07-02 20:10
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12493

**Comment by desagas** [comment] 2023-07-02 20:16
That is not a good sign, that it is stale, but I know you are all working hard on making the pack better, regardless.

Sorry, I tried searching but could not find via my searches.

**Closed** 2023-07-02 20:33 UTC
Labels: Type: Duplicate, Type: bugMinor, Status: Triage
