### ISSUE TITLE
gt material parts and material tools tab in nei are broken

### ISSUE THREAD

**Issue by CatsLeftEar** [GTNewHorizons/GT-New-Horizons-Modpack#17739] opened 2024-10-23 19:27 UTC
### Your GTNH Discord Username

Keyla3300

### Your Pack Version

2.7 beta

### Your Server

random one

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

expect normal behaviour
![tabs](https://github.com/user-attachments/assets/dc498101-b37c-43fa-ac69-3301be234457)

### The Reality

Cursor is in one place, game thinks its in another place

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FourIsTheNumber** [comment] 2024-10-23 19:30
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17715, fixed with update to nei custom diagram

**Closed by FourIsTheNumber** 2024-10-23 19:30 UTC
Labels: Type: bugMinor, Status: Triage
