### ISSUE TITLE
opening questbook crashes client (ZETA)

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#16280] opened 2024-05-15 10:47 UTC
### Your GTNH Discord Username

MIAOW246

### Your Pack Version

2.6.0 build 3.6.1?

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Actions

opening quest-book crashes client
since the cr is not entirely the same with what dream posted, i post another one. if they are the same, close mine.

this happened in zeta

Newly created sp world has no problem.

### Crash Report

[crash-2024-05-15_03.14.00-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15320163/crash-2024-05-15_03.14.00-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Dream-Master** [comment] 2024-05-17 16:49
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16277#issuecomment-2117965268

**Comment by D-Cysteine** [comment] 2024-05-17 19:32
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16277

**Closed by D-Cysteine** 2024-05-17 19:32 UTC
Labels: Type: Crash, Status: Triage
