### ISSUE TITLE
Twilight Forest crashes game

### ISSUE THREAD

**Issue by Arthaus14** [GTNewHorizons/GT-New-Horizons-Modpack#16475] opened 2024-06-07 04:36 UTC
### Your GTNH Discord Username

Arthas14

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Load into the twilight forest and am able to walk around for a time then it randomly crashes. I have previously been able to restart the game the load back in, but this most recent crash caused me to have to load a backup. This world was created on 2.6.0 and this was also happening in that version. Deleting the Twilight Forest dimension and remaking it also did not work to solve the issue.

### Crash Report

https://mclo.gs/i5IOUXt

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Lyfts** [comment] 2024-06-07 05:59
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16353

You can update twilight forest to https://github.com/GTNewHorizons/twilightforest/releases/tag/2.6.12

**Closed by Lyfts** 2024-06-07 05:59 UTC
Labels: Type: Crash, Status: Triage
