### ISSUE TITLE
Calculation of Large Plasma Generator seems to be wrong

### ISSUE THREAD

**Issue by pulsemageadvocate** [GTNewHorizons/GT-New-Horizons-Modpack#12087] opened 2022-12-25 12:13 UTC
### Your GTNH Discord Username

pulsemageadvocate

### Your Pack Version

2.2.8.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Large Plasma Generator runs at optimal flow using Huge Infinity Catalyst Turbine and Tin Plasma.
Optimal flow is 34L/s.

### The Reality

Large Plasma Generator repeats start and stop.
Portable Scanner says optimal flow is 34L/s
but true optimal flow seems to be higher.

![20221225_1](https://user-images.githubusercontent.com/59131259/209466827-dc928523-28c9-483e-bfe7-a1073590d69c.jpg)
Running with Huge Infinity Catalyst Turbine and Tin Plasma 187L/s.
872,336,401EU/t is too much.

### Your Proposal

Fix calculation.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2022-12-25 12:30
Looks like somebody messed up the scanner values. 34 L/s is way too low. Can you do the calc youself? Probably missing a factor 20 would be my guess

**Comment by shekurika** [comment] 2022-12-25 12:42
34L/s is the accurate optimal flow. the issue is the power produced, which is too high by a factor of ~750

**Comment by ZuOverture** [comment] 2022-12-25 13:07
187L/s is 5.5 times the 34L/s optimal, which is the correct overflow factor for tier 10 infcat rotor, so flow is correctly capped at 187.

Problem is EU/t. Just tested it with 2.2.8 with large plasmagen from 2.2.0 world - at 187L/t tricorder shows stable 2097152 Eu/t while it should be 3523208. So sort of opposite situation: EU/t is lower than expected.

Also turbine periodically stops if flow is set to 34L/s.

**Comment by chochem** [comment] 2022-12-25 13:15
@ZuOverture You are dynamo capped with buffered UV I would guess? So working correctly for you.

**Comment by ZuOverture** [comment] 2022-12-25 13:23
Indeed, missed the dynamo part (was UHV 1A). After changing to UXV 1A though tricorder shows 536870912 EU/t stable at 187L/s (152x the expected). So something is wrong here as well.

**Comment by chochem** [comment] 2022-12-29 21:51
should be fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1607

**Closed by chochem** 2022-12-29 21:51 UTC
Labels: Type: bugMinor, Mod: GT
