### ISSUE TITLE
Crashing after joining game

### ISSUE THREAD

**Issue by longme179** [GTNewHorizons/GT-New-Horizons-Modpack#16079] opened 2024-04-29 01:34 UTC
### Your GTNH Discord Username

.kommandantkater

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Actions

Update to 2.6.0 from 2.6.0 beta 3, join game, the game do auto backup, crash

### Crash Report

[crash-2024-04-29_08.26.48-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15144494/crash-2024-04-29_08.26.48-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Caedis** [comment] 2024-04-29 01:39
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16075

**Closed by Caedis** 2024-04-29 01:39 UTC
Labels: Type: Crash, Status: Triage

**Comment by longme179** [comment] 2024-04-29 01:52
the second time I started it up, it turned out to be normal now.
