### ISSUE TITLE
Can't lock fluid type oxygen gas on air industrial centrifuge 

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#11897] opened 2022-11-30 11:48 UTC
### Your GTNH Discord Username

GregTechDriver

### Your Pack Version

2.2.3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Centrifuge air for O2 and N2

### The Reality

When i lock fluid type on output hatch with oxygen .The machine doesn't run
Unless i unlock oxygen

Nitrogen gas has no problem

### Your Proposal

What happened with the machine??

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment] 2022-12-02 02:48
Please confirm after locking you still have space left for oxygen AND nitrogen.

**Comment by chochem** [comment] 2022-12-04 17:35
They work just fine with or without locking. This is probably something unrelated. Probably a duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11448

**Comment by BritishCynic** [comment] 2023-01-28 20:55
As this has not been able to be reproduced, this issue is being closed. If you can reproduce this issue on current dev, please leave a comment to re-open with steps needed to reproduce.

**Closed** 2023-01-28 21:28 UTC
Labels: Type: bugMinor, Type: Need More Info, Status: Can't Reproduce
