### ISSUE TITLE
crashing to desktop

### ISSUE THREAD

**Issue by NaCl0526** [GTNewHorizons/GT-New-Horizons-Modpack#10359] opened 2022-05-19 09:28 UTC
### Your Pack Version

2.1.2.3qf

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Play Selected World

### Crash Report

[crash-2022-05-19_17.18.58-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8727787/crash-2022-05-19_17.18.58-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2022-08-19 02:26
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10377
this was earlier but I am leaving the one with a lot more comments.

**Closed by chochem** 2022-08-19 02:26 UTC
Labels: Type: Duplicate, Type: Crash
