### ISSUE TITLE
These mobs shouldn't explode after death

### ISSUE THREAD

**Issue by CatsLeftEar** [GTNewHorizons/GT-New-Horizons-Modpack#7620] opened 2021-03-13 01:12 UTC
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
Tried to grindfarm louse (HEE dungeon mob)
#
#### What happened instead? (Attach screenshots if needed)
nearly every 1/5 louse explodes, dealing massive damage and destroying valuable loot (runes), while not beinge a passive mob, its hostile.
#
#### What do you suggest instead/what changes do you propose?
Hostile mobs shouldn't explode. Exploding animals are a punishment for not using the right tool, knife or butcher knife. Maybe spirit from random things mod shouldnt explode as well? 

#
#### What is your GTNH Discord username?
CatsLeftEar

**Comment by Prometheus0000** [comment] 2021-03-13 01:46
They probably count as passive mobs code-wise.

**Comment by KiloJoel** [comment] 2021-03-13 02:34
The mod that handles it is anger mod (there's no label for it)

**Comment by Methes** [comment] 2021-03-13 15:45
Absolutely no mobs should explode randomly on death as it's one of the most dumb features this modpack has. I have been turning it off for years in my private playthroughs. I have no clue how someone could think it was a good idea.

**Comment by interestingusernam3** [comment] 2021-03-22 10:20
>Absolutely no mobs should explode randomly on death as it's one of the most dumb features this modpack has. I have been turning it off for years in my private playthroughs. I have no clue how someone could think it was a good idea.

It's funny

**Comment by Dream-Master** [comment] 2021-03-22 15:03
It was desinged for Special ai mod where sheeps and cows attak you after you attak them. So Animals are dangerous and the explosion was a part of it. Like the cfg said "Kamikaze"

**Comment by Dream-Master** [comment] 2021-03-22 15:04
And yes it is funny.

**Comment by Dream-Master** [comment] 2021-03-22 15:04
Use a knife to avoid explosion

**Comment by Dream-Master** [comment] 2021-03-22 15:06
I guess this mobs maybe use the main animal class from mc so it acting like a scheep or cow or chicken.

**Comment by CatsLeftEar** [comment] 2021-03-22 15:25
Louse spawn often in groups, and there are lots and lots of treir spawners in dungeons. They kill you in nano armor, going against them with a knife?

**Comment by CatsLeftEar** [comment] 2021-03-22 15:33
Also small slimes, small magma slimes. They also explode. So, you are fighting huge slime, kill it, want to get all the loot, but small slime destroys everything with explosion. And considering there are usually not less then 6 small slimes from big slime, explosion is guaranteed. Going with knife even on slimes?

**Comment by CatsLeftEar** [comment] 2021-03-22 15:42
I strongly advice making only cow, pig, sheep, bird, penguin, deer etc. suicidal, not semi-passive mobs like slimes or sludgelings (small green organisms on Mars) and definetely not aggressive louses

**Comment by Prometheus0000** [comment] 2021-03-22 15:52
Config is in .minecraft\config\GTNewHorizons\angermod.cfg You can't specify mobs to include or exclude.

It also appears to be specifically for GTNH, as the version at https://github.com/GTNewHorizons/AngerMod isn't forked from something. So code changes would need to be done (but can be) to select only certain types of enemies. You should be able to set B:KamikazeMobRevenge=true to false though? Assuming that's the right one.

**Comment by Prometheus0000** [comment] 2021-05-03 22:45
Duplicate of #5365

**Closed by Prometheus0000** 2021-05-03 22:45 UTC
Labels: Type: bugMinor
