### ISSUE TITLE
Buff Robes of the Stratoshpere

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#7483] opened 2021-02-15 15:19 UTC
Considering that it is locked at IV tier with osmiridium, it would be nice if it can provide hazmat protection.
Idk if I missed something but that's the first armor that gives creative-like flight, and right now it's kinda a tradeoff to use it, as pollution is an issue, and it needs to be swapped everytime radioactive materials need to be handled.
I guess the rest of the armor would need to have the same effect applied aswell

**Comment by alphaNOVAircraft** [comment] 2021-02-15 15:26
Seems to be fine to me. It has its tradeoff - early creative-like flight vs pollution. The hazmat creative like flight is locked behind zpm.

**Comment by Glease** [comment] 2021-02-15 15:42
Duplicate of #6366

**Closed by Glease** 2021-02-15 15:42 UTC
Labels: Type: duplicate

**Comment by yukieiji** [comment] 2021-02-15 15:44
Isn't Thaumostatic Harness the first armor that gives you creative-like flight?(need fuel)
