### ISSUE TITLE
Crash with forestry worktable

### ISSUE THREAD

**Issue by louisferdi** [GTNewHorizons/GT-New-Horizons-Modpack#6485] opened 2020-08-07 14:37 UTC
#### Which modpack version are you using?
2.0.9.0-beta3(Server)
2.0.9.0(Client)
#
#### If in multiplayer; On which server does this happen? 
Stonehuts (gtnh.stonehuts.net)
#
#### What did you try to do, and what did you expect to happen?
was trying to make LV machine hull in a forestry worktable and i expected it to work instead it crashed
#
#### What happened instead? (Attach screenshots if needed)
https://pastebin.com/MmEinSEx
 this is the crashlog
#
#### What do you suggest instead/what changes do you propose##

**Comment by louisferdi** [comment] 2020-08-08 08:48
things to denote from this bug : in my experience it will crash if crafting block-type items as in the LV machine hull,when crafting items such as components,pumps,etc it won't crash

**Comment by boubou19** [comment] 2020-08-08 10:31
the culprit is not forestry itself, a few versions ago, we had the same issue and it was caused by M&B iirc. This time, it's the mod Adventure backpacks. If you have a backpack from this mod equiped, try unequip it before crafting and see if it keeps crashing

**Comment by louisferdi** [comment] 2020-08-08 12:59
i didn't have a backpack when the crash occured

**Comment by Glease** [comment] 2021-04-11 07:31
Same as #7414. Fixed in dev.

**Closed** 2021-06-22 17:29 UTC
Labels: Mod: Forestry, Status: FixedInDev, Type: Crash
