### ISSUE TITLE
Black Screen when Quest Completion / refresh Popup

### ISSUE THREAD

**Issue by Executorder** [GTNewHorizons/GT-New-Horizons-Modpack#15427] opened 2024-01-27 05:52 UTC
### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

seeing what Quest got completed/reset

### The Reality

Screen goes black, Quest text not visible
goes back to normal after quest "info" faded fully

restart "resets" the bug until i get a TC notification it seems (at least thats what i could boil it down to)

also tried with / without hololens as stated in another issue but neither fixes the bug
#15193
EDIT: triggers after TC headache message consistently

### Your Proposal

make me not go blind ?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lyfts** [comment] 2024-01-27 09:18
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15193

You can update to latest version of BetterQuesting for now: https://github.com/GTNewHorizons/BetterQuesting/releases

**Closed** 2024-01-27 09:18 UTC
Labels: Type: bugMinor, Status: Triage
