### ISSUE TITLE
Crash with Charm of Keeping 1 and equipping a weapon in the M&B slots

### ISSUE THREAD

**Issue by dvdmandt** [GTNewHorizons/GT-New-Horizons-Modpack#5619] opened 2020-02-19 16:20 UTC
#### Which modpack version are you using?
2.0.7.5, also happened on 2.0.5.1
#
#### If in multiplayer; On which server does this happen? 
My own, can also reproduce in SSP.
#
#### What did you try to do, and what did you expect to happen?
I died holding a charm of keeping 1 from Twilight Forest, and expected the game to not crash. I did use a weapon placed in the first Mine and Blade (I think?) slot.
#
#### What happened instead? (Attach screenshots if needed)
The server crashed with ArrayIndexOutOfBoundsException in twilightforest.TFEventListener.livingDies(TFEventListener.java:575).

I suspect this code to be the culprit:

`                if (player.inventory.getCurrentItem() != null) {
                    keepInventory.mainInventory[player.inventory.currentItem] = ItemStack.copyItemStack(player.inventory.mainInventory[player.inventory.currentItem]);
                    player.inventory.mainInventory[player.inventory.currentItem] = null;
                }
`
My guess is that player.inventory.currentItem gets values between 150-152 or when a weapon in the Mine and Blade slots is equipped, causing the exception.

#
#### What do you suggest instead/what changes do you propose?
I suggest adding a try..catch and/or an index boundary check to the crashing code. If that fails, get rid of charm of keeping as we have tombstones and soulbound enchantments anyway.

**Comment by dvdmandt** [comment] 2020-02-19 16:22
![image](https://user-images.githubusercontent.com/11985732/74851995-4b054080-533c-11ea-9412-42229b102dfb.png)

I was using a weapon in the slot where I have my Sword of the Zephyr in that screenshot when the crash happened.

**Comment by boubou19** [comment] 2020-02-19 16:35
does it happen in 2.0.8.3?

**Comment by dvdmandt** [comment] 2020-02-19 17:24
I can now confirm that it does happen in 2.0.8.3 as well.

Repro:
Create a world with cheats, make a TF portal and spawn in some tinkers sword as well as charm of keeping 1. Place the sword in one of your M&B slots, and use your hotkey to equip it (Draw weapons hotkey, default R but with multiple conflicts). Go through the portal and get killed.

**Comment by Dream-Master** [comment] 2020-02-19 17:42
@jss2a98aj 
any idea ?

**Comment by jss2a98aj** [comment] 2020-02-19 18:49
I have fixed the crash, but held M&B Battlegear items will not be kept. I plan to add proper support for it and Baubles slots later.

**Comment by daddy77gaming** [comment] 2020-02-20 20:47
Adding to this, 2 weeks back on toasted server I too died while holding a charm of keeping, game did NOT crash, BUT no grave spawned and ALL soulbound gear was gone, however there was a death inventory registered on server ( without ALL soulbounded gear )

**Comment by richardhendricks** [comment] 2020-02-26 16:45
How were you killed, and which version is Toasted running?

**Comment by Prometheus0000** [comment] 2020-10-07 15:54
Duplicate of  #5018

**Closed by Prometheus0000** 2020-10-07 15:54 UTC
Labels: Status: work in progress, Type: Crash
