### ISSUE TITLE
Dynamism Tablet Crashing Server

### ISSUE THREAD

**Issue by jccoogle** [GTNewHorizons/GT-New-Horizons-Modpack#16234] opened 2024-05-11 06:24 UTC
### Your GTNH Discord Username

LetJPlay

### Your Pack Version

2.6.0

### Your Server

Private server

### Java Version

Java 8

### Type of Server

Don't know

### Your Actions

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/16529308/19979859-3e04-4a09-a1ae-dab1e89b6c16)
Placed a dynamism tablet to auto-right click onto an ethereal shard to begin building an instrumentum filled shard for a massive node. Chest would hold the instrumentum ethereal essence and it would item conduit into the dynamism tablet. When I actually put instrumentum ethereal essence into the chest, it began spitting this error out over and over again 
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/16529308/61922d8a-3d93-4dee-9489-7616ec2a8ea0). After 5-10 seconds, server shut down

### Crash Report

[crash-2024-05-11_02.00.32-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15281835/crash-2024-05-11_02.00.32-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Caedis** [comment] 2024-05-11 06:26
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16151

**Closed by Caedis** 2024-05-11 06:26 UTC
Labels: Type: Crash, Status: Triage

**Comment by GTNH-Afx237v7** [comment] 2025-03-28 08:21
This exact issue persists in 2.7.3

```
[09:07:30] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: java.lang.ClassCastException: class thaumic.tinkerer.common.block.tile.tablet.TabletFakePlayer cannot be cast to class net.minecraft.entity.player.EntityPlayerMP (thaumic.tinkerer.common.block.tile.tablet.TabletFakePlayer and net.minecraft.entity.player.EntityPlayerMP are in unnamed module of loader 'Launch' @302c971f)
[09:07:30] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//com.sk89q.worldedit.forge.ForgeWorldEdit.onPlayerInteract(ForgeWorldEdit.java:195)
[09:07:30] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1972_ForgeWorldEdit_onPlayerInteract_PlayerInteractEvent.invoke(.dynamic)
[09:07:30] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
[09:07:30] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[09:07:30] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100)
[09:07:30] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//thaumic.tinkerer.common.block.tile.tablet.TileAnimationTablet.swingHit(TileAnimationTablet.java:167)
[09:07:30] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//thaumic.tinkerer.common.block.tile.tablet.TileAnimationTablet.func_145845_h(TileAnimationTablet.java:98)
[09:07:30] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//net.minecraft.world.World.func_72939_s(World.java:1939)
[09:07:30] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[09:07:30] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[09:07:30] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[09:07:30] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
[09:07:30] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[09:07:30] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[09:07:32] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent@152a470c:
java.lang.ClassCastException: class thaumic.tinkerer.common.block.tile.tablet.TabletFakePlayer cannot be cast to class net.minecraft.entity.player.EntityPlayerMP (thaumic.tinkerer.common.block.tile.tablet.TabletFakePlayer and net.minecraft.entity.player.EntityPlayerMP are in unnamed module of loader 'Launch' @302c971f)
	at Launch//com.sk89q.worldedit.forge.ForgeWorldEdit.onPlayerInteract(ForgeWorldEdit.java:195) ~[ForgeWorldEdit.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1972_ForgeWorldEdit_onPlayerInteract_PlayerInteractEvent.invoke(.dynamic) ~[?:?]
	at Launch//cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at Launch//cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at Launch//net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100) [ForgeEventFactory.class:?]
	at Launch//thaumic.tinkerer.common.block.tile.tablet.TileAnimationTablet.swingHit(TileAnimationTablet.java:167) [TileAnimationTablet.class:?]
	at Launch//thaumic.tinkerer.common.block.tile.tablet.TileAnimationTablet.func_145845_h(TileAnimationTablet.java:98) [TileAnimationTablet.class:?]
	at Launch//net.minecraft.world.World.func_72939_s(World.java:1939) [ahb.class:?]
	at Launch//net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) [mt.class:?]
	at Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) [MinecraftServer.class:?]
	at Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at Launch//net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[09:07:32] [Server thread/ERROR] [FML/]: Index: 51 Listeners:
[09:07:32] [Server thread/ERROR] [FML/]: 0: HIGHEST
[09:07:32] [Server thread/ERROR] [FML/]: 1: ASM: serverutils.handlers.ServerUtilitiesPlayerEventHandler@6e8f6ed5 onPlayerInteraction(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 2: ASM: com.github.namikon.blocklimiter.events.ItemUseEvent@4dc21eb1 onInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 3: NORMAL
[09:07:32] [Server thread/ERROR] [FML/]: 4: ASM: binnie.botany.Botany@2c64a60f onShearFlower(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 5: ASM: binnie.botany.Botany@2c64a60f onFertiliseSoil(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 6: ASM: gregtech.common.GTClient@268537f5 onPlayerInteraction(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 7: ASM: org.embeddedt.archaicfix.LeftClickEventHandler@492e5e4f onLeftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 8: ASM: mods.battlegear2.BattlemodeHookContainerClass@4d89a17f playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 9: ASM: micdoodle8.mods.galacticraft.core.event.EventHandlerGC@6e216f3e onPlayerClicked(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 10: ASM: mods.railcraft.common.carts.MinecartHooks@988eb59 onItemUse(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 11: ASM: team.chisel.item.chisel.ChiselController@1fd08e33 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 12: ASM: chylex.hee.system.achievements.AchievementEvents@4ed0466a onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 13: ASM: chylex.hee.mechanics.misc.TempleEvents@72b6cbfd onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 14: ASM: vazkii.botania.common.block.string.BlockRedStringInterceptor@3858495c onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 15: ASM: vazkii.botania.common.item.material.ItemManaResource@3cf2d454 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 16: ASM: vazkii.botania.common.item.relic.ItemLokiRing@622dce onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 17: ASM: vazkii.botania.common.item.rod.ItemExchangeRod@4ca9790e onLeftClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 18: ASM: binnie.core.item.ModuleItems@264e1bc onUseFieldKit(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 19: ASM: binnie.extratrees.carpentry.BlockCarpentry@26e03a74 onClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 20: ASM: thaumic.tinkerer.common.item.kami.ItemProtoclay@3b54828c Interact(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 21: ASM: minetweaker.mc1710.ForgeEventHandler@468b4620 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 22: ASM: com.brandon3055.draconicevolution.common.handler.MinecraftForgeEventHandler@5b58e21a playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 23: ASM: ru.timeconqueror.timecore.api.common.CommonEventHandler@49997ed6 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 24: ASM: remoteio.common.core.handler.PlayerEventHandler@3b847d0a onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 25: ASM: serverutils.handlers.ServerUtilitiesPlayerEventHandler@6e8f6ed5 onRightClickItemLog(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 26: ASM: com.dyonovan.tcnodetracker.events.RightClickEvent@55316c83 playerRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 27: ASM: witchinggadgets.common.util.handler.EventHandler@19c0c407 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 28: ASM: appeng.parts.PartPlacement@3d2978 playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 29: ASM: com.rwtema.extrautils.EventHandlerServer@1db46ca1 angelBlockDestroy(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 30: ASM: twilightforest.TFEventListener@5f32edd4 rightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 31: ASM: com.enderio.core.common.handlers.RightClickCropHandler@17f1513 handleCropRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 32: ASM: com.github.namikon.angermod.events.PlayerSpawnProtection@1188dc38 onInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 33: ASM: tuhljin.automagy.lib.events.AutomagyEventHandler@8b9a767 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 34: ASM: vazkii.botania.common.core.handler.SpawnerChangingHandler@237d89f0 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 35: ASM: vazkii.botania.client.core.handler.MultiblockRenderHandler@17fb44b9 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 36: ASM: fox.spiteful.avaritia.LudicrousEvents@11dbbe6e onPlayerMine(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 37: ASM: thaumic.tinkerer.common.core.helper.BonemealEventHandler@7f3f9875 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 38: ASM: thaumic.tinkerer.common.core.handler.kami.KamiDimensionHandler@2d662e8e onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 39: ASM: com.carpentersblocks.util.handler.EventHandler@1c16c621 onPlayerInteractEvent(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 40: ASM: li.cil.oc.integration.fmp.EventHandler$@16b19c7c playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 41: ASM: pl.asie.computronics.integration.forestry.nanomachines.SwarmProvider@452560fe onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 42: ASM: emt.util.EMTEventHandler@142c7c01 createCloud(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 43: ASM: flaxbeard.thaumicexploration.event.TXEventHandler@70ad1ba7 handleItemUse(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 44: ASM: net.dries007.holoInventory.server.ServerEventHandler@31a84bf8 event(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 45: ASM: com.creativemd.littletiles.common.events.LittleEvent@6fd55f68 onInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 46: ASM: logisticspipes.LogisticsEventListener@4ff2b406 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 47: ASM: net.malisis.doors.event.DoorEventHandlerClient@3ef2dc2e onClientInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 48: ASM: stevesaddons.naming.EventHandler@6a30143a playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 49: ASM: com.jaquadro.minecraft.storagedrawers.core.ForgeEventHandler@42fb8535 playerInteracts(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 50: ASM: jcm2606.thaumicmachina.core.event.PlayerEventHandler@3f149d3a onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 51: ASM: com.sk89q.worldedit.forge.ForgeWorldEdit@684f2a42 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 52: ASM: appeng.fmp.FMPEvent@14c39e14 playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 53: ASM: fox.spiteful.avaritia.compat.ticon.TonkersEvents@3d6b0f6 onPlayerMine(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 54: ASM: com.emoniph.witchery.item.ItemPoppet$PoppetEventHooks@6af27fc8 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 55: ASM: com.emoniph.witchery.infusion.Infusion$EventHooks@360bc48b onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 56: ASM: com.emoniph.witchery.common.GenericEvents@6f578ad onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 57: ASM: com.emoniph.witchery.brewing.DispersalTriggered$EventHooks@2e0dc17e onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 58: ASM: iguanaman.hungeroverhaul.util.IguanaEventHook@238b83f6 onPlayerInteraction(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 59: ASM: iguanaman.iguanatweakstconstruct.claybuckets.ClayBucketHandler@f23d800 onRightClickBlock(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 60: LOW
[09:07:32] [Server thread/ERROR] [FML/]: 61: ASM: codechicken.multipart.minecraft.EventHandler@4920b7a5 playerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 62: LOWEST
[09:07:32] [Server thread/ERROR] [FML/]: 63: ASM: bq_standard.handlers.EventHandler@2983f2e1 onPlayerInteract(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 64: ASM: buildcraft.oiltweak.OilTweakEventHandler@7a203a68 onRightClick(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 65: ASM: makeo.gadomancy.common.events.EventHandlerGolem@633301f6 on(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
[09:07:32] [Server thread/ERROR] [FML/]: 66: ASM: makeo.gadomancy.common.events.EventHandlerWorld@306c7449 on(Lnet/minecraftforge/event/entity/player/PlayerInteractEvent;)V
```

**Comment by GTNH-Afx237v7** [comment] 2025-03-28 10:55
My mistake - I was still using worldedit-v0.0.5 which does not include the following fix: https://github.com/GTNewHorizons/worldedit-gtnh/pull/6

Using worldedit-v0.0.7, the error does not appear.
