### ISSUE TITLE
Thaumic Horisons drugs crash game while holding thaumometer

### ISSUE THREAD

**Issue by BurgerFan45** [GTNewHorizons/GT-New-Horizons-Modpack#13348] opened 2023-04-29 07:16 UTC
### Your GTNH Discord Username

BurgerFan45#0661

### Your Pack Version

2.3.2

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Don't know

### Your Actions

Trying to open a chest with a Thaumic Horizons drug filled syringe while holding a Thaumometer crashes the client.

### Crash Report

[crash-2023-04-29_16.56.20-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11358598/crash-2023-04-29_16.56.20-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2023-04-29 10:12
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13037

**Closed by chochem** 2023-04-29 10:12 UTC
Labels: Type: Crash, Status: Triage
