### ISSUE TITLE
Empty Cells are not consumed when trying to fill a stack of cells of any amount above via the Fluid terminal

### ISSUE THREAD

**Issue by IsOobt** [GTNewHorizons/GT-New-Horizons-Modpack#13449] opened 2023-05-07 20:45 UTC
### Your GTNH Discord Username

oobt#8431

### Your Pack Version

2.3.2

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Attempted to Fill up a stack of cells with liquid via the fluid terminal

### The Reality

A cell with the selected liquid appears in the inventory but none of the cells in the stack are consumed (this does not apply if you are just using one cell)
![image](https://user-images.githubusercontent.com/114492400/236701715-62c306d9-0812-471e-a649-d24e2c95fa20.png)
![image](https://user-images.githubusercontent.com/114492400/236701724-bcb58cb5-7636-41ce-bb1a-4c5904d8eeb7.png)

### Your Proposal

Consume a cell in the stack when selecting a liquid to fill up the cells with

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by firenoo** [comment] 2023-05-07 20:47
Likely duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13177

**Closed by firenoo** 2023-05-07 20:47 UTC
Labels: Type: Duplicate, Type: bugMinor, Status: Triage

**Comment by miaowwwwww** [comment] 2023-05-07 20:54
it's fixed in newer versions, zeta server has this fixed already.
