### ISSUE TITLE
GT Tools Wrench 

### ISSUE THREAD

**Issue by AdminXiaoMai** [GTNewHorizons/GT-New-Horizons-Modpack#15386] opened 2024-01-21 19:17 UTC
### Your GTNH Discord Username

Admin_XiaoMai

### Your Pack Version

nightly-24-01-20  318

### Your Server

private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Actions

GT Tool Wrench Left Button to Break Me Cable

### Crash Report

https://paste.ubuntu.com/p/m7htKRQGJq/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2024-01-22 14:48
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15342

**Closed by chochem** 2024-01-22 14:48 UTC
Labels: Type: Crash, Status: Triage
