### ISSUE TITLE
Gameplay bug with Battlegear 2

### ISSUE THREAD

**Issue by SteamDoge9000** [GTNewHorizons/GT-New-Horizons-Modpack#8369] opened 2021-08-07 21:17 UTC
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
SP
#
#### What did you try to do, and what did you expect to happen?
Tried to Plug-in Gregtech weapons (Axe and Sword) in the Battlegrear Slots and expected them to be accepted 
#
#### What happened instead? (Attach screenshots if needed)
They refuse to go into the slots
#
#### What do you suggest instead/what changes do you propose?
adding support for GT items that can be used as weapons
#
#### What is your GTNH Discord username?
Doggo_9000 (Masked Thaumaturge
#
##### Additional Recommendations

add quiver support for for TConstruct Arrows/bolts (or make them be able to be picked up if the bolts are put inside the battegear slot

Please reference this if there was a previous report about this and it has gone stale

**Comment by Prometheus0000** [comment] 2021-08-08 20:32
Duplicate of #6957

**Closed by Prometheus0000** 2021-08-08 20:32 UTC
Labels: Type: suggestion, Type: Need Code changes, Mod: M&B Battlegear 2
