### ISSUE TITLE
Gregtech Fluid Filter Cover reseting after reboots

### ISSUE THREAD

**Issue by pariator** [GTNewHorizons/GT-New-Horizons-Modpack#9415] opened 2022-01-08 20:09 UTC
### Your GTNH Discord Username

Randy#4245

### Your Pack Version

2.1.2.1

### Your Server

Private server with fresh install. Has FTB utils installed and HC darkness removed.

### Type of Server

Don't know

### Your Expectation

When setting the Gregtech Fluid Filter Cover(6954:32669) options, they should remain after a server reboot.

### The Reality

After the server reboots, fluid filters are defaulting to Filter Input, breaking all of my automation the filters are integrated with. The fluid remains set, but the flow options resets.

### Your Proposal

Fix that. A temporary workaround seems to be to flip the side that the filter is on so when it resets to Filter Input, it will still filter properly.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment] 2022-01-08 20:10
This is a known issue but I don't know if a 2.1.2.1 patched jar exists, let me see what I can find

**Comment by pariator** [comment] 2022-01-08 20:12
Great, thanks. I did search for the issue but couldn't find it. My apologies!

**Comment by bombcar** [comment] 2022-01-08 20:17
hmmm I don't see a particular jar for 2.1.2.1 but try this on server and client:
[gregtech-1.7.10-5.09.40.16-1-g9fb99c2.dirty.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7833953/gregtech-1.7.10-5.09.40.16-1-g9fb99c2.dirty.zip)

rename existing gregtech jar to .jars, rename this .zip to .jar, and put in mods. don't unzip it, had to call it .zip to upload

**Comment by bombcar** [comment] 2022-01-08 20:18
duplicate of #9096

**Closed by bombcar** 2022-01-08 20:17 UTC
Labels: Type: bugMinor, Status: FixedInDev, Status: Triage

**Comment by pariator** [comment] 2022-01-08 20:27
Thank you very much for the rapid response. Have a wonderful weekend.
