### ISSUE TITLE
Client and Server are downloading mismatched cores and they appear to redownload different versions every launch

### ISSUE THREAD

**Issue by Hachuurui** [GTNewHorizons/GT-New-Horizons-Modpack#11348] opened 2022-09-18 20:47 UTC
### Your GTNH Discord Username

Hachuurui#6428

### Your Pack Version

2.2.0.0.-RC3

### Your Server

TWPI - Testing build locally

### Type of Server

Thermos

### Your Expectation

Client and server packs download the same versions of mods.

### The Reality

They are downloading different versions of mods.

This appears to affect the mods in the 1.7.10 folder. Dreammaster told me this folder was supposed to be gone, but it appears to still download ChickenCoreLib and MrTJPCore mods the issue is the MrTJPCore mod appears to be swapping between version 1.1.0.31 and 1.1.0.33 at random. Initial pack/server launch had client download v33 and server download v31. Then after a couple client relaunches  with deleting the 1.7.10 folder client eventually downloaded v31 instead of v33. At one point, I could swear it actually downloaded 33 again on its own without wiping the 1.7.10 folder, but I am still trying to verify that. 
![2022-09-18 16_37_10-Window](https://user-images.githubusercontent.com/2464584/190927458-12f81706-48f0-41dd-9545-890a567b86dd.png)

New server/client installs seem to replicate this behavior. I've reinstalled the client and server setup a few times now.

### Your Proposal

Take a look at the configs for files to pull I guess? Not sure what is causing this behavior. Posting the ticket since Dreammaster asked me too.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment] 2022-09-18 20:50
was the mod present in the mod folder? or is it missing and it does redownload it?

**Comment by Hachuurui** [comment] 2022-09-18 20:51
They were not present and a download window similar to the galacticraft download window popped up on initial launch

**Comment by eigenraven** [comment] 2022-09-18 20:53
it looks like the codechickencore dependency downloader, probably some mods have an old version definition for it in their jars

**Comment by boubou19** [comment] 2022-09-18 20:54
what i don't get tho is that it should be in both zips

**Comment by Hachuurui** [comment] 2022-09-18 20:54
I can say I pulled the downloads from the zip in the dropbox links

**Comment by boubou19** [comment] 2022-09-18 21:20
We checked with Hachuurui, but we couldn't reproduce it, so likely a bad extraction of the archives or something. I'm closing this for now, unless someone else is able to reproduce it.

**Closed by boubou19** 2022-09-18 21:20 UTC
Labels: Type: bugMajor, type: DreamAssemblerXXL
