### ISSUE TITLE
Crash when entering Naga maze

### ISSUE THREAD

**Issue by alexk101** [GTNewHorizons/GT-New-Horizons-Modpack#16511] opened 2024-06-11 01:01 UTC
### Your GTNH Discord Username

alexk101

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Actions

Tried to enter the Naga boss area in the twilight forest

### Crash Report

https://mclo.gs/bji6ySH

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2024-06-16 16:21
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16353 and many others.

You can update twilight forest to https://github.com/GTNewHorizons/twilightforest/releases/tag/2.6.12

**Closed by chochem** 2024-06-16 16:21 UTC
Labels: Type: Crash, Status: Triage
