### ISSUE TITLE
Infinite essentia storage with the essentia condenser

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#8943] opened 2021-11-29 13:48 UTC
### Your GTNH Discord Username

Maniifestantes

### Your Pack Version

2.1.1.4QF2

### Your Server

Zeta

### Your Expectation

The essentia condenser is a multiblock from gadomancy that can stored 200~3000 of each essentia type, which is pretty neat

### The Reality

If you use golems to store the essentia, the cap is removed essentially turning it into an unlimited essentia storage.
![2021-11-29_10 48 26](https://user-images.githubusercontent.com/57275066/143879407-bf116cdb-0917-4d38-8f47-b1d438f7c99f.png)

### Your Proposal

as much as i like this, it's not intended, so it should be fixed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by yukieiji** [comment] 2021-11-29 14:10
Duplicate of #7889, #2990

**Closed** 2021-11-29 19:44 UTC
Labels: Type: bugMinor, Status: Triage
