### ISSUE TITLE
2.0.9 Dev Mega Bug List

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#6008] opened 2020-04-28 23:57 UTC
A generalized post for a list of bugs that occur in the latest 2.0.9 Dev instance.

- [x] Potential Mod increasing tick speed of the player entity: #6004 

- [x] Potentially Railcraft Boilers not consuming Fuel: Found by SampsaxD, Colen, and Darkstar1712 on Zeta

- [x] Potential duplication with Railcraft Boilers or with certain things in general, ~deletion of certain fluid cells after exiting a fluid tank of some kind, and much much more hidden bugs potentially by the increased tick speed or similar issue: Found by me with further investigation. Bug is extremely dangerous and unpredictable.~

- [x] Deletion or reverting of filled cells of fluid/gases/metal/etc. Bug *seems* to occur whenever you have empty fluid cells in your inventory after gathering something from a different inventory; ~super/quantum fluid tanks. Output buses with this bug seem uncertain.~ After further testing, I can confirm this happens to ANY GUI screen involving the interaction of cells. Opening you chest to pick out a cell of molten Epoxid with other empty cells in your GUI, for instance, will simply revert them into empty cells. Does not occur with Ic2 Universal Cells. **Only occurs with a plugin and Thermos involved, but Thermos alone without plugins works normally.**

- [x] Dimension checks for quests do not properly check due to new biome check: Found by me, already addressed by Funawayguy and can be fixed by editing the JSON file where the quest exists.

- [x] Kekztech Thaumcraft Research is impossible to obtain, as you cannot obtain them, quite literally speaking. Despite what the book states that you've obtained the research upon right-clicking, it never actually appears in your inventory. This makes getting Thaumium Reinforced Jars and Ichor Jars impossible to obtain.

- [x] Ticking memory crash involving going to Ross128ba (Moon of Ross128b), a decorator block triggering the crash for some reason. A serious issue that may also occur on other GC planets (the Moon) or specifically only happening on Ross128ba, Found by @chochem

- [x] For whatever reason, Ichorium is blackened out as "Missing Required Research!" in the dev version, despite already have been researched or unlocked. Image from @chochem on the Discord server. This also occurs in all versions of 9.0. Unclear as to what or why Ichorium research is marked off and unobtainable. If you have Ichorium already researched, you can still click on it and view the recipe. Originally found by me upon playing the Dev version way back, but brushing it off for some reason. Also found by @chochem and kscode911 on the GTNH Discord.
![Spooky!](https://user-images.githubusercontent.com/41557212/81629413-ee07ac80-93b7-11ea-918e-8a3a8f2e2c78.png)
It was recently discovered that there were additional researches added to the requirement of Ichorium itself, for some strange reason. Kekz's Ichor jars were surprisingly not the issue. **While investigating, it was discovered that more research was added to the Ichorium Bar. Unclear what causes this, but needs an announcement and clarification whenever asked in the future.**

- [x] Looking up Nitrogen or possibly other fluids in the NEI will instantly crash your game by attempting to render an item. Unclear as to why this is occurring. Happens on 2.0.9.0-beta1. 

- [x] Integrated circuits for the LCR are frequently changing on server restarts; see #6143 for pictures/screenshots. Found separately by @chochem, Sampasa & Darkstar, and followed by me on Zeta. Very major bug and can interfere with MANY chemical setups.

If you have similar bugs on the latest 2.0.9 release, please put them down below.

###########################
Added by the admins:
###########################

- [x] https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6032

**Comment by GTNH-Colen** [comment] 2020-04-29 09:40
Both coke ovens and water tanks seem to exhibit this duping behaviour, clicking on them with a stack of buckets causes the stack to stay the same but a filled bucket to appear elsewhere in your inventory.

**Comment by Bluebine** [comment] 2020-04-30 03:50
.9.0 sparked a similar bug for me, which is that the game won't let me hold single cells in my inventory. If I right-click a tank, a cell appears in my inventory, then instantly disappears, but the tank still loses a bucket of fluid. If the cells are stacked, I can hold them, but the instant I have a single cell in an inventory slot, it empties itself. 

As far as I can tell, this only happens for GT cells. IC2 cells and GT++ ones work normally, but all the GT cells I've tested instantly void their fluid when I put them in my inventory. Doesn't produce anything abnormal in the logs.

**Comment by GTNH-Colen** [comment] 2020-04-30 18:51
> .9.0 sparked a similar bug for me, which is that the game won't let me hold single cells in my inventory. If I right-click a tank, a cell appears in my inventory, then instantly disappears, but the tank still loses a bucket of fluid. If the cells are stacked, I can hold them, but the instant I have a single cell in an inventory slot, it empties itself.
> 
> As far as I can tell, this only happens for GT cells. IC2 cells and GT++ ones work normally, but all the GT cells I've tested instantly void their fluid when I put them in my inventory. Doesn't produce anything abnormal in the logs.

This appears to be a MP issue, I tested it on zeta and it occurs but on sp I couldn't reproduced it unless you were able?

**Comment by Bluebine** [comment] 2020-05-01 02:32
I exclusively play SP, and yes, this was happening on SP in my main world.

**Comment by GTNH-Colen** [comment] 2020-05-01 21:32
> I exclusively play SP, and yes, this was happening on SP in my main world.

Bizarre, I tried for a while but couldn't get it to reproduce outside of zeta. To make things even stranger if I put empty cells in a coke oven as soon as they fill the coke oven throws them out in random directions including the actual interior of the oven.

**Comment by Bluebine** [comment] 2020-05-02 00:48
The coke ovens spewing cells everywhere is normal- well, idk if it's intended, but it's been happening for a while now for me anyways. The cells emptying themselves is the same problem I'm experiencing.

**Comment by ScriptedPiky** [comment] 2020-05-11 01:03
Added new bug: Kekztech Thaumcraft Research is impossible to obtain, as you cannot obtain them, literally. Despite what the book states that you've obtained the research, it never actually appears in your inventory. This makes getting Thaumium Reinforced Jars and Ichor Jars impossible to obtain.

**Comment by chochem** [comment] 2020-05-11 06:01
if they all should be collected here, I guess this crash is pretty important: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6083

**Comment by ScriptedPiky** [comment] 2020-05-11 06:08
That's quite a nifty crash you got involving GC decorator blocks apparently. Added it to the list.

**Comment by bartimaeusnek** [comment] 2020-05-11 10:20
The Ross128ba bug is only using base GC classes, (therefore a GC issue)

**Comment by Dream-Master** [comment] 2020-05-11 11:02
@mitchej123 maybe you can make a fix when you on GC source allready ?

**Comment by ScriptedPiky** [comment] 2020-05-12 01:50
Added to the list: Another bug involving Thaumcraft research of Ichorium Bars. For whatever reason, Ichorium is blackened out as "Missing Required Research!" in the dev version, despite already have been researched or unlocked. Image from @chochem on the Discord server. This also occurs in all versions of 9.0. Unclear as to what or why Ichorium research is marked off and unobtainable.
![Spooky!](https://user-images.githubusercontent.com/41557212/81629413-ee07ac80-93b7-11ea-918e-8a3a8f2e2c78.png)

**Comment by Prometheus0000** [comment] 2020-05-12 02:07
I believe this happens when you have the research completed, but don't meet the requirements for it. IE: a new research was added that is now required for Ichorium. I encountered this when I was testing to add the impure star.

**Comment by ScriptedPiky** [comment] 2020-05-12 02:10
I wonder what kind of research would be gate-keeping the Ichorium bars from being unlocked. I know for sure I've done all the other required research, maybe the Kekz Ichor jars are having an issue with this potentially?

**Comment by Prometheus0000** [comment] 2020-05-12 02:12
I think that's the only thaumcraft thing that's changed recently, so probably.

**Comment by Dream-Master** [comment] 2020-05-12 12:59
@kekzdealer any idea if your mod cause it?

**Comment by kekzdealer** [comment] 2020-05-12 13:05
As was explained to me, TTKami automatically added both my Jar researches to it's list of required researches. 
I'll add Ichor as parent to the Ichor Jar research and try to blacklist the Reinforced Jar research from being added. 
That should hopefully remove the issue.

The bug about research notes being unobtainable should already be fixed in v0.4

**Comment by kekzdealer** [comment] 2020-05-13 13:38
Update on the Jar researches: 
Neither of my researches show up in /iskamiunlocked after the update.
Also the Ichor Jar research is correctly hidden until ICHOR is researched.

Apparently the Ichorium Bar research bug still persists.

**Comment by Prometheus0000** [comment] 2020-05-14 05:07
Use of items in Bacterial Vat recipes don't seem to show up properly unless you check the Vat recipe itself. If you check the uses of the item, it doesn't show Vat recipes. Though fluids seem to work. Using beta1.

**Comment by kekzdealer** [comment] 2020-05-15 11:16
Things I found after playing 9.0 beta2 for a bit:
- The Industrial Wand Charger consumes EU at full power as long as it has a wand in it's slot. The charge state of the wand does not matter.
- Shift-dragging your cursor over items in your inventory does not move them into another inventory like it always used to
- The tick time of our server doubled from 25-30ms to 45-60ms. Can't tell yet if this is our problem or caused by the update.  
- It's impossible to switch pages for more research categories in the Thaumonomicon. The tabs just overlap weirdly:
![image](https://user-images.githubusercontent.com/31353359/82044675-13453500-96ae-11ea-9a06-a3d3ce3229c3.png)
- The research for Ichor, Cloth, Shadow Cloth, and Shadow Metal wand caps reset completely as if it was never completed.

**Comment by chochem** [comment] 2020-05-20 13:10
@kekzdealer the ichorium bar has the thaumic reinforced jar as a requirement from what I can tell (9.0 beta2)
at least the color turn back to normal and the 'missing research' thing disappeared, the moment I researched the jar.

**Comment by chochem** [comment] 2020-05-22 12:41
major bug with LCRs (and possibly other machines) in the latest beta: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6143

**Comment by kekzdealer** [comment] 2020-05-23 15:04
@chochem This is from our server where I already have both jars researched 
![image](https://user-images.githubusercontent.com/31353359/82733894-6b67e100-9d17-11ea-9304-02b77e50a0af.png)

**Comment by chochem** [comment] 2020-05-23 15:38
hmm, it fixed it for me, but if it doesnt for you then I am not sure whats going on. My thaumonomicon was almost complete, so maybe its multiple new requirements and I already had the other ones. :/

![image](https://user-images.githubusercontent.com/40274384/82734541-791b6780-9d13-11ea-9cf3-0dc8ab435c74.png)

**Comment by ScriptedPiky** [comment] 2020-05-23 22:18
If I do remember correctly, there are some additional things that you have to complete. Such things include Wither Ring (for some reason), ALL of the Thaumic Tinker phial fires, primal magical seeds (do not place them, you will crash your game), and the rest of the TT research. Despite that these researches were not included previously, they are now required for some reason.

**Comment by Prometheus0000** [comment] 2020-05-23 22:31
Isn't all of vanilla and TT required for ichor in normal TT? Or at least, I thought it was. And the things like the wither ring that got added to vanilla pages get added too.

**Comment by ScriptedPiky** [comment] 2020-05-23 22:35
These things normally weren't ever required at all. Stuff like all the taboo elemental/primal phial fires, the primal seeds, the mob summoning, and the Wither Ring (GTNH) weren't required for the Ichorium Bar. Normally, you'd just unlock all the previous prerequisite researches and unlock the rest of the Kami/Ichor line without trouble. Not sure why all of these researches are required now, but when we get an official update, this will need to be stated to prevent confusion at the very least.

**Comment by chochem** [comment] 2020-05-28 16:32
@ScriptedPiky 
1) if you were the one pinging me on zeta, dont. I am not on zeta.
2) as pointed out by Bluebine above, but apparently it needs repeating: the cell bug has nothing to do with thermos or plugins but happens in Singleplayer as well.
3) I havent tested the bartmoon again as I dont like crashing too much and currently dont even have rocket fuel. but promotheus tested it on beta2 where it was still crashing.
I am willing to test it again (with some cheated fuel) IF somebody has actually been trying to fix it. But up until now, I have seen nothing of that sort, so I will not just go there to crash my game.

**Comment by Prometheus0000** [comment] 2020-06-03 04:47
The cell bug and I think ross should both be fixed, so we should get a RC2 soon.

**Comment by Prometheus0000** [comment] 2020-06-03 05:00
Also, @bartimaeusnek are you going to fix whatever's wrong with NEI and the BVat and BLab recipes?
IE: The bio lab's first recipe doesn't show up under uses of Growth medium. Biocells do not show up as usable in the bacterial vat's last recipe under it's uses.

**Closed** 2020-06-07 18:54 UTC
Labels: EU Live Server, Need Code changes, Need more Info, Quest change, Zeta, bugMajor, bugMinor, help wanted, need help, need to be tested, recipe change, reminder, urgent
