### ISSUE TITLE
Packager consumes Dusts Schematic

### ISSUE THREAD

**Issue by D1P0** [GTNewHorizons/GT-New-Horizons-Modpack#8441] opened 2021-08-22 18:03 UTC
### Your GTNH Discord Username

Dipo#3713

### Your Pack Version

2.1.1.0

### Your Server

LAN world

### Type of Server

Multiplayer LAN

### Your Expectation

Trying to craft Redstone Alloy Dust out of 9x Tiny Pile of Redstone Dust using MV Packager with Schematic (Dusts). Expected it to yield 1x Redstone Alloy Dust and to preserve the schematic like with other types of dusts.

### The Reality

It yielded 1x Redstone Alloy Dust, but it also consumed the schematic, which in my opinion it shouldn't.

### Your Proposal

I suggest to fix this and make it not to consume the schematics. Also while quickly running through packager recipes, i noticed there are more types of dusts, where it doesn't say 'Does not get consumed in the process', for example Small Pile of  Lithium Peroxide Dust.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment] 2021-08-22 18:04
Duplicate of #8100

**Closed by Glease** 2021-08-22 18:04 UTC
Labels: Type: bugMinor
