### ISSUE TITLE
Lepidopterist's Chest does not have crafting recipe.

### ISSUE THREAD

**Issue by FindMeSomeFun** [GTNewHorizons/GT-New-Horizons-Modpack#17762] opened 2024-10-26 06:03 UTC
### Your GTNH Discord Username

FindMeSomefun

### Your Pack Version

2.7.0 Beta 3

### Your Server

Private Server

### Java Version

Java 21

### Type of Server

Open To LAN

### Your Expectation

Lepidopterist's Chest required by quest should be possible to make.

### The Reality

Lepidopterist's Chest does not have crafting recipe.

### Your Proposal

Add recipe for Lepidopterist's Chest. :P

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by BlueHero233** [comment] 2024-10-26 06:17
Dupe of #17691

**Closed by BlueHero233** 2024-10-26 06:17 UTC
Labels: Type: bugMinor, Status: Triage
