### ISSUE TITLE
[Avaritiaddons] Compressed chest brakes item rendering

### ISSUE THREAD

**Issue by TheElan** [GTNewHorizons/GT-New-Horizons-Modpack#8854] opened 2021-11-16 16:24 UTC
### Your GTNH Discord Username

Elan

### Your Pack Version

2.1.1.0

### Your Server

private

### Type of Server

Vanilla Forge

### Your Expectation

Items (from what I noticed ones having a block form) to render properly like:

![image](https://user-images.githubusercontent.com/13066272/142024152-a95f13af-70bd-45f6-b0cc-6758ad1bd8c6.png)

### The Reality

It looks like compact chest render code contaminates GL and makes other blocks rendered after it have incorrect shadowing:

![image](https://user-images.githubusercontent.com/13066272/142024285-20ae874a-9ffe-4db6-8fdf-9c2b6d2c4dc4.png)

### Your Proposal

Look around in compact chest render code and find a source of contamination

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment] 2021-11-16 16:41
Duplicate of... some issue that I cannot find, but this is fixed already by https://github.com/GTNewHorizons/Avaritiaddons/pull/1

**Closed by Glease** 2021-11-16 16:41 UTC
Labels: Type: bugMinor, Status: Triage, Mod: Avaritia Addons

**Comment by Glease** [comment] 2021-11-16 16:43
Duplicate of #7113.
