### ISSUE TITLE
Repeated crash on load in Twilight Forest

### ISSUE THREAD

**Issue by okdewit** [GTNewHorizons/GT-New-Horizons-Modpack#17358] opened 2024-09-15 19:51 UTC
### Your GTNH Discord Username

okdw

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Actions

Game crashed in Twilight forest.
It re-crashes on loading the same save.

Might be related to #17296

Here's a [Discord CDN link to the zipped corrupt world save](https://cdn.discordapp.com/attachments/1058144004602069045/1284964481377632298/PineapplePancakes_Crashy.zip?ex=66e88bed&is=66e73a6d&hm=4b0e50c2c6d18c7af40ed2531adc7ee887fef049fb5b0fa877cd3cbc926fe190&) in case that helps.

### Crash Report

Crash log: https://mclo.gs/W0RpZiS

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Hebbu** [comment] 2024-09-15 20:16
2.6.1 has issue with Twilight Forest, try updating TF to version 2.6.12.

**Comment by riking** [comment] 2024-09-15 20:24
To fix nagastone-related crashes, update the Twilight Forest mod:
https://github.com/GTNewHorizons/twilightforest/releases/download/2.6.12/TwilightForest-2.6.12.jar
Download the .jar, and replace the old version of the mod in your ./minecraft/mods/ folder.

**Comment by Lyfts** [comment] 2024-09-15 20:31
![s](https://github.com/user-attachments/assets/d9286e8a-10d1-493c-b13b-6c59d3cc2440)
Searching "Twilight Forest" or something similar on the issue tracker results in about 50 issues identical to this one. 

Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16353 and many others.

**Closed by Lyfts** 2024-09-15 20:31 UTC
Labels: Type: Crash, Status: Triage

**Comment by okdewit** [comment] 2024-09-17 20:28
@Lyfts Could make sense to add the hotfixed mod version to the GTNH modpack release zips in that case?

**Comment by FourIsTheNumber** [comment] 2024-09-17 20:33
> @Lyfts Could make sense to add the hotfixed mod version to the GTNH modpack release zips in that case?

In the next release.

**Comment by chochem** [comment] 2024-09-17 20:38
> @Lyfts Could make sense to add the hotfixed mod version to the GTNH modpack release zips in that case?

lyft (or four or me) is not an admin. so no we cant.
