### ISSUE TITLE
Plasma arc furnace bug

### ISSUE THREAD

**Issue by evgengoldwar** [GTNewHorizons/GT-New-Horizons-Modpack#15929] opened 2024-04-06 18:14 UTC
### Your GTNH Discord Username

EvgenWarGold

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

I wanted to build a plasma arc furnace, but it does not accept hatches only from below

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/69961523/84b3a372-263e-4b0c-8573-286ec6d6d1e0)

### Your Proposal

When building a plasma arc furnace, all hatches must be installed from below, otherwise there will be incompleteness, but this is not said anywhere

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by HoleFish** [comment] 2024-04-06 18:18
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14368

**Closed by HoleFish** 2024-04-06 18:18 UTC
Labels: Type: bugMinor, Status: Triage
