### ISSUE TITLE
client crash when logging in a server

### ISSUE THREAD

**Issue by berta24** [GTNewHorizons/GT-New-Horizons-Modpack#14742] opened 2023-10-20 11:23 UTC
### Your GTNH Discord Username

Berta24

### Your Pack Version

nightly 185

### Your Server

private

### Java Version

Java 20

### Type of Server

None

### Your Actions

logged in a server and got an instant client crash 

### Crash Report
```
[13:19:04] [Client thread/ERROR] [FML]: Exception caught during firing event cpw.mods.fml.common.gameevent.TickEvent$ClientTickEvent@3aff5ac2:
java.lang.NullPointerException: Cannot invoke "net.minecraft.server.MinecraftServer.func_71259_af()" because the return value of "net.minecraft.server.MinecraftServer.func_71276_C()" is null
	at gregtech.api.objects.blockupdate.Cooldown.getServerTimeInTicks(Cooldown.java:38) ~[Cooldown.class:?]
	at gregtech.api.objects.blockupdate.Cooldown.hasPassed(Cooldown.java:23) ~[Cooldown.class:?]
	at gregtech.api.objects.blockupdate.BlockUpdateHandler.OnClientTickEvent(BlockUpdateHandler.java:80) ~[BlockUpdateHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_2200_BlockUpdateHandler_OnClientTickEvent_ClientTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325) [FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Unknown Source) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Unknown Source) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Unknown Source) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:165) [lwjgl3ify-1.5.2-forgePatches.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:29) [lwjgl3ify-1.5.2-forgePatches.jar:?]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[13:19:04] [Client thread/ERROR] [FML]: Index: 101 Listeners:
[13:19:04] [Client thread/ERROR] [FML]: 0: HIGHEST
[13:19:04] [Client thread/ERROR] [FML]: 1: ASM: gregtech.common.render.GT_PollutionRenderer@45171421 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 2: NORMAL
[13:19:04] [Client thread/ERROR] [FML]: 3: ASM: gregtech.common.GT_Client@75a9501b onClientTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 4: ASM: net.glease.tc4tweak.ClientProxy@27c465ac onTickEnd(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 5: ASM: fastcraft.d@652a24a6 a(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 6: ASM: ic2.core.TickHandler@4337d929 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 7: ASM: mods.battlegear2.client.BattlegearClientTickHandeler@53f0414f keyDown(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 8: ASM: thaumcraft.client.lib.ClientTickEventsFML@3ca2aeb9 clientWorldTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 9: ASM: thaumcraft.client.fx.ParticleEngine@48821ac5 updateParticles(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 10: ASM: mods.railcraft.client.sounds.SoundLimiterTicker@27ddebc3 tick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 11: ASM: chylex.hee.mechanics.compendium.events.CompendiumEventsClient@7e4ea322 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 12: ASM: chylex.hee.mechanics.charms.handler.CharmPouchHandlerClient@23d3c1e8 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 13: ASM: chylex.hee.entity.fx.FXEvents@58529680 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 14: ASM: crazypants.enderio.item.darksteel.DarkSteelController@3f96f00b onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 15: ASM: wanion.lib.client.ClientTickHandler@37a8ff3e tickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 16: ASM: com.gtnewhorizon.structurelib.ClientProxy$FMLEventHandler@4afdc668 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 17: ASM: com.emoniph.witchery.client.PlayerRender@2783e8a2 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 18: ASM: com.emoniph.witchery.client.KeyboardHandler@a54bf84 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 19: ASM: lumien.randomthings.Client.ClientTickHandler@3f056097 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 20: ASM: codechicken.enderstorage.storage.liquid.TankSynchroniser@59583c39 tickEnd(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 21: ASM: emt.util.EMTClientEventHandler@26fff08b clientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 22: ASM: minetweaker.mc1710.FMLEventHandler@926f790 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 23: ASM: com.gtnh.findit.service.itemfinder.ClientItemFindService$TickListener@9ae5de7 onClientPostTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 24: ASM: ftb.lib.mod.client.FTBLibRenderHandler@3f5083d3 clientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 25: ASM: galaxyspace.core.handler.GSSkyProviderHandler@28a65b3b onSkyRendererTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 26: ASM: galaxyspace.core.handler.GSClientTickHandler@60e4b8ad onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 27: ASM: lumien.hardcoredarkness.HardcoreDarkness@7da3b503 clientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 28: ASM: ca.wescook.nutrition.events.EventWorldTick@1d368f86 clientTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 29: ASM: INSTANCE tickEnd(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 30: ASM: ru.timeconqueror.tcneiadditions.client.TCNAClient@f1f7da2 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 31: ASM: codechicken.wirelessredstone.core.WRCoreEventHandler@61719fe9 clientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 32: ASM: aroma1997.core.client.events.ClientEventListener@5ce01764 tick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 33: ASM: codechicken.core.internal.CCCEventHandler@2546e66a clientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 34: ASM: codechicken.nei.ClientHandler@2206e2db tickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 35: ASM: appeng.parts.PartPlacement@4ec576e5 playerInteract(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 36: ASM: com.rwtema.extrautils.EventHandlerClient@7a3a17fa getTimer(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 37: ASM: com.rwtema.extrautils.item.RenderItemGlove@4f4f9b3d tickCol(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 38: ASM: mcp.mobius.waila.overlay.WailaTickHandler@112cdf80 tickClient(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 39: ASM: tconstruct.client.HealthBarRenderer@1ce19711 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 40: ASM: micdoodle8.mods.galacticraft.core.tick.TickHandlerClient@c568a95 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 41: ASM: micdoodle8.mods.galacticraft.core.tick.KeyHandlerClient@4177d8e0 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 42: ASM: micdoodle8.mods.galacticraft.planets.asteroids.event.AsteroidsEventHandlerClient@72f2818b onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 43: ASM: micdoodle8.mods.galacticraft.planets.mars.MarsModuleClient$TickHandlerClient@2393ecca onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 44: ASM: mods.railcraft.common.util.misc.BlinkTick@4208053f tick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 45: ASM: twilightforest.client.TFClientTicker@28e19ccc clientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 46: ASM: com.enderio.core.client.handlers.ClientHandler@65b455a9 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 47: ASM: com.enderio.core.common.util.Scheduler@6be84db9 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 48: ASM: crazypants.enderio.CommonProxy$TickTimer@2b7d7800 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 49: ASM: crazypants.enderio.teleport.TravelController@fc61560 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 50: ASM: crazypants.enderio.item.darksteel.SoundDetector@eefeaa5 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 51: ASM: de.katzenpapst.amunra.tick.TickHandlerClient@44b15e74 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 52: ASM: squeek.applecore.client.HUDOverlayHandler@a959b49 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 53: ASM: vazkii.botania.common.core.handler.CommonTickHandler@b85c604 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 54: ASM: vazkii.botania.client.core.handler.ClientTickHandler@72724eb2 clientTickEnd(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 55: ASM: vazkii.botania.client.core.handler.CorporeaAutoCompleteHandler@1355c322 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 56: ASM: li.cil.oc.common.EventHandler$@2b2fc693 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 57: ASM: li.cil.oc.common.item.Tablet$@554aa283 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 58: ASM: li.cil.oc.util.Audio$@96b721 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 59: ASM: li.cil.oc.client.renderer.tileentity.HologramRenderer$@45137c5c onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 60: ASM: li.cil.oc.client.renderer.PetRenderer$@61724d47 tickStart(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 61: ASM: li.cil.oc.client.Sound$@696f6c72 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 62: ASM: li.cil.oc.client.renderer.TextBufferRenderCache$@b537e08 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 63: ASM: openblocks.client.ClientTickHandler@3b9efb21 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 64: ASM: pl.asie.computronics.tape.PortableDriveManager@41857cbe onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 65: ASM: pl.asie.computronics.util.sound.Audio@3cd02d8f onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 66: ASM: com.brandon3055.draconicevolution.client.handler.ClientEventHandler@3bb3e0a8 tickEnd(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 67: ASM: de.keridos.floodlights.core.FMLEventListener@2d630b7c onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 68: ASM: gravisuite.TickHandler@2e89d58a onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 69: ASM: com.sinthoras.hydroenergy.hooks.HEHooksFML@2ef49a2b onEvent(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 70: ASM: com.github.lunatrius.ingameinfo.handler.Ticker@19149df onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 71: ASM: invtweaks.forge.ForgeClientTick@7757eb8 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 72: ASM: logisticspipes.ticks.LPTickHandler@70b05efc clientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 73: ASM: com.github.lunatrius.schematica.handler.QueueTickHandler@60ecd458 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 74: ASM: com.github.lunatrius.schematica.handler.client.TickHandler@4bebf24e onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 75: ASM: net.blay09.mods.tcinventoryscan.client.ClientProxy@5d95e673 clientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 76: ASM: net.glease.tc4tweak.modules.researchBrowser.ThaumonomiconIndexSearcher@716b584c renderTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 77: ASM: net.glease.tc4tweak.modules.researchBrowser.BrowserPaging$EventHandler@6793a1dc onClientTickEnd(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 78: ASM: travellersgear.client.KeyHandler@50846906 handleKeybindsOnTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 79: ASM: shukaro.warptheory.handlers.warpevents.WarpBlood@435a743d onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 80: ASM: shukaro.warptheory.handlers.warpevents.WarpFakeRain@1b669635 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 81: ASM: codechicken.wirelessredstone.addons.WRAddonEventHandler@52e016f6 clientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 82: ASM: cofh.core.render.ShaderHelper@4a78f530 clientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 83: ASM: codechicken.lib.world.WorldExtensionManager$WorldExtensionEventHandler@2924d089 clientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 84: ASM: codechicken.multipart.ControlKeyHandler$@502ace9f tick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 85: ASM: tconstruct.armor.ArmorTickHandler@115c3b2c tickEnd(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 86: ASM: mods.railcraft.client.core.LocomotiveKeyHandler@26f7669 tick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 87: ASM: mods.railcraft.client.core.DebugViewTicker@7aa6d049 tick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 88: ASM: forestry.core.TickHandlerCoreClient@7d5e5a99 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 89: ASM: forestry.core.multiblock.MultiblockClientTickHandler@6d5ed99 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 90: ASM: com.mitchej123.hodgepodge.client.ClientTicker@69d0de67 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 91: ASM: mrtjp.core.render.RenderTicker$@63a3cfcd clientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 92: ASM: mrtjp.projectred.core.libmc.fx.ParticleManagement@1d642452 tickEnd(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 93: ASM: mrtjp.core.fx.FXEngine$@a63670e tickEnd(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 94: ASM: openmods.movement.PlayerMovementManager$LegacyTickHandler@42bd4901 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 95: ASM: mrtjp.relocation.RelocationClientEventHandler$@6ed061e clientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 96: ASM: makeo.gadomancy.client.events.ClientHandler@7642975 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 97: ASM: journeymap.client.forge.event.StateTickHandler@381a2f53 onClientTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 98: ASM: mrtjp.projectred.expansion.SpacebarClientTracker$@5764c3a9 tick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 99: ASM: mrtjp.projectred.expansion.ForwardClientTracker$@7e581c26 tick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 100: ASM: mrtjp.projectred.expansion.ItemJetpack$@725915b onRenderTick(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 101: ASM: gregtech.api.objects.blockupdate.BlockUpdateHandler@47ea60d7 OnClientTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 102: ASM: vazkii.botania.common.block.BlockPistonRelay@1f397d34 tickEnd(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 103: ASM: lumien.randomthings.Handler.RTTickHandler@6dea77db tick(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 104: ASM: com.brandon3055.draconicevolution.common.handler.FMLEventHandler@616d91db serverTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 105: ASM: remoteio.common.tracker.BlockTracker@61773fe6 onWorldTick(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 106: ASM: appeng.hooks.TickHandler@26131156 onTick(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 107: ASM: thaumic.tinkerer.client.core.handler.ClientTickHandler@381529df tickEnd(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 108: ASM: com.creativemd.creativecore.common.event.TickHandler@67da3865 onEventTick(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 109: ASM: me.lucko.spark.forge.Forge1710TickHook@250218d0 onTick(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 110: ASM: me.lucko.spark.forge.Forge1710TickReporter@54d23318 onTick(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 111: ASM: com.sinthoras.visualprospecting.hooks.HooksFML@713f8b04 onEvent(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[13:19:04] [Client thread/ERROR] [FML]: 112: LOWEST
[13:19:04] [Client thread/ERROR] [FML]: 113: ASM: buildcraft.oiltweak.OilTweakEventHandler@621ce499 onPlayerClientUpdate(Lcpw/mods/fml/common/gameevent/TickEvent$ClientTickEvent;)V
[13:19:04] [Client thread/WARN] [vfyjxf.bettercrashes.utils.ModIdentifier]: Failed to identify cpw.mods.fml.common.eventhandler.ASMEventHandler_2200_BlockUpdateHandler_OnClientTickEvent_ClientTickEvent (untransformed name: cpw.mods.fml.common.eventhandler.ASMEventHandler_2200_BlockUpdateHandler_OnClientTickEvent_ClientTickEvent)
[13:19:04] [Client thread/INFO]: Stopping!
```

**Comment by Glease** [comment] 2023-10-20 12:02
caused by https://github.com/GTNewHorizons/GT5-Unofficial/pull/2342. should be fixed after that PR is fixed/temporarily removed from nightly builds/rejected.

**Comment by iamblackornot** [comment] 2023-10-21 09:40
Sorry for this issue caused by my bad implementation. Hope it's working fine

**Closed** 2023-10-21 09:48 UTC
Labels: Type: Crash
