### ISSUE TITLE
Fluid Stocking Input Hatch (ME)

### ISSUE THREAD

**Issue by MaGeBZz** [GTNewHorizons/GT-New-Horizons-Modpack#14060] opened 2023-07-25 09:39 UTC
### Your GTNH Discord Username

marvinhhmagebzz

### Your Pack Version

2.3.5

### Your Proposal

Making a Fluid Stocking Input Hatch (ME) with up to 16 different fluids stocked

### Your Goal

It's the equivalent of the stocking input bus (ME) and many people want it

### Your Vision

Talked with dream and he says we just need a recipe for that to make that happen so I got an idea
He said maybe UHV/UEV and I would recommend maybe to do it like the stocking input bus (ME)

You need (1-16) (quad) input hatch UHV/UEV, (1-16) dual interfaces flat form, (4-16) hyper-acceleration cards and maybe a higher tier super/quantum tank

Personally I would say maybe 4 quadruple input hatches (UHV) cause the new quad hatches released and it would make sense eventually cause 4xquad would be 16 fluids
Then one dual interface flat cause it's the same like the item stocking input
Then 4 hyper-acceleration cards cause it would make it harder but the same amount of cards just the hyper instead of the normal ones
And at the end quantum tank III 16 of them maybe to make it harder and 16 cause 16 different fluids

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by minecraft7771** [comment] 2023-07-25 09:41
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12269

**Closed by minecraft7771** 2023-07-25 09:41 UTC
Labels: Type: Suggestion, Status: Triage
