### ISSUE TITLE
wrong Recipe for diluted sulfuric acid enables fluid duplication

### ISSUE THREAD

**Issue by Darkmaxsas** [GTNewHorizons/GT-New-Horizons-Modpack#13734] opened 2023-06-17 16:42 UTC
### Your GTNH Discord Username

Darkmaxsas

### Your Pack Version

2.3.4

### Your Server

private server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

that i get the same amount of Sulfuric Acid back as i invested in diluted sulfuric acid

Recipe in Pack Version 2.3.0
![diluted to sulfuirc 2 3 0](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/98653930/572f3825-1845-4390-a693-14e5f399bfd5)
![Sulfuric Acid to diluted 2 3 0](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/98653930/62b0c7d1-6260-4bd1-a438-0d065d79cc7a)

### The Reality

The new Recipe for Diluted Sulfuric Acid to Sulfuric Acid seems broken.
The Ratios are complete off and enable for duplication of the sulfuric acid

Recipe in Pack Version 2.3.4
![diluted to sulfuirc 2 3 4](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/98653930/2982a9c7-fee9-4c06-b18c-c69ed2308f0a)
![Sulfuric Acid to diluted 2 3 4](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/98653930/2e8552ed-b617-4818-935b-9291a2547ca7)

### Your Proposal

revert the Ratio back to the point it was in 2.3.0

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment] 2023-06-18 00:49
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13667, see https://gtnh.miraheze.org/wiki/Dev_Release_Stability

**Closed by miozune** 2023-06-18 00:49 UTC
Labels: Type: bugMinor, Status: Triage
