### ISSUE TITLE
Graphics doesn't rendering in space station

### ISSUE THREAD

**Issue by yuliiesh** [GTNewHorizons/GT-New-Horizons-Modpack#15869] opened 2024-03-29 19:36 UTC
### Your Pack Version

beta-2.6.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Block will render 
![screen](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/132001095/75b6e835-780b-4d78-970b-e5c5e0547d2b)

### The Reality

Block doesn't render

### Your Proposal

This may be cause of sodium

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2024-03-29 19:41
duplicate of https://github.com/GTNewHorizons/Angelica/issues/379

**Closed by chochem** 2024-03-29 19:41 UTC
Labels: Type: bugMinor, Status: Triage
