### ISSUE TITLE
Twilight forest repeated crashing

### ISSUE THREAD

**Issue by bowlofcupramen** [GTNewHorizons/GT-New-Horizons-Modpack#16540] opened 2024-06-16 16:45 UTC
### Your GTNH Discord Username

bowlofcupramen

### Your Pack Version

2.6.1

### Your Server

private server

### Java Version

Java 17

### Type of Server

Open To LAN

### Your Actions

I walked close enough to a naga maze for its chunks to load in. 

### Crash Report

[crash-2024-06-16_11.34.12-server.txt](https://github.com/user-attachments/files/15859055/crash-2024-06-16_11.34.12-server.txt)
[crash-2024-06-16_11.29.19-server.txt](https://github.com/user-attachments/files/15859057/crash-2024-06-16_11.29.19-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Lyfts** [comment] 2024-06-16 16:47
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16353 and many others.

You can update twilight forest to https://github.com/GTNewHorizons/twilightforest/releases/tag/2.6.12

**Closed by Lyfts** 2024-06-16 16:47 UTC
Labels: Type: Crash, Status: Triage
