### ISSUE TITLE
Should crushed ore oredict be changed?

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6841] opened 2020-10-22 03:03 UTC
Apparently when you use the EC2 ore dictionary export bus, if you specify crushed*, it will pick up not only crushed ores, but crushed purified and crushed centrifuged. My suggestion is to change (for example) crushedIron -> crushedOreIron or something like that.

Any thoughts? Or is this not a real problem?

**Comment by ScriptedPiky** [comment] 2020-10-22 03:08
One way to avoid this is to additionally have a GT type buffer that strictly tells what `oreCrushed` you want. While this is not a fix, it is a very powerful & nice bandaid solution to the problem.

**Comment by draknyte1** [comment] 2020-10-22 07:42
No.. just no..
How about just fix broken EC2... 🤦🏻‍♀️

**Comment by Prometheus0000** [comment] 2020-10-22 07:44
Huh? Which part of it is broken related to the export bus? This is about how GT names the crushed ore, what would need to be changed in EC2 to fix it?

**Comment by draknyte1** [comment] 2020-10-22 07:46
Fucks me. 🤷🏻‍♀️
Changing the OD tags is *not* the right solution at all. If EC2 can’t handle shit properly, the issue lies therein.

**Comment by Prometheus0000** [comment] 2020-10-22 07:51
crushedIron, crushedCopper,
crushedPurifiedIron, crushedCentrifugedIron,
crushedCentrifugedIron, crushedCentrifugedCopper
would all be grabbed with a crushed* on the export bus, whereas crushedCentrifuged* would only grab all ores that are centrifuged. I'm suggesting adding another word onto the initial crushed to prevent this, so you can grab all initially crushed ores.

**Comment by draknyte1** [comment] 2020-10-22 07:54
That’s working as intended though. * is a wildcard and those are *all* suitable values for it. 

Changing the OD tags isn’t viable anyway thanks to IC2 and other mods that you can’t change, making it inconsistent and even less usable.

**Comment by DualBallers** [comment] 2020-10-22 10:42
@Prometheus0000 I have wished for this addition for a looong time. 
This would be especially useful when exporting to the ore washer, where I **only** want crushedORE to be input and not crushedPurifiedORE or crushedCentrifugedORE. 

A way around this is to put the ore-dict bus directly on the input bus which apparently constricts the ore-dict types, but even then, strangely, sometimes I end up with crushedPurifiedAluminium in the input bus, stopping the ore washer.

**Comment by Prometheus0000** [comment] 2020-10-22 11:19
You should go check out the discussion in github-discussion, looks like they're going to try to make the export bus do exclusions instead so a bunch of stuff doesn't break.

**Comment by GTNH-Afx237v7** [comment] 2020-10-22 11:26
Suggest instead to use a storage bus with high priority pointing at a GT type filter that is set to crushed. This way all crushed ores that enter the ME system will go there. If you want to exclude certain ores from the washer, use an inverter card on the storage bus and put the ones in the GUI that you don’t want washed. Same applies to crushedPurified or crushedCentrifuged and all the other use cases. 
With the coming change of EC2 ore dictionary export bus this should also be possible.

**Comment by repo-alt** [comment] 2020-10-24 11:40
In the new version (since 2.0.9.0) you can use regexp to filter stuff. so something like `crushed((?!Purified).)*` should work

**Comment by Dream-Master** [comment] 2020-10-24 12:31
@repo-alt fixed in dev ?

**Comment by repo-alt** [comment] 2020-10-24 12:31
more like: "Need to be tested"

**Comment by Prometheus0000** [comment] 2020-10-24 20:30
I can't get this to work with the filter you gave, but I also don't really get regex that well. Also ```Purified``` by itself gave the 3 crushed ores for some reason. ```*Purified``` same, ```*Purified*``` gives purified and centrifuged.

Using 2.0.9.1a dev. EC2 is ExtraCells-1.7.10-2.4.4b6.jar.

**Comment by Prometheus0000** [comment] 2020-10-30 03:26
@repo-alt Are you sure this works? It really seems like it doesn't.

**Comment by repo-alt** [comment] 2020-10-30 07:44
Ill take a look.  Actually regex matching crushed* but not crushedPurified* would look like `crushed(?!Purified).*`

**Comment by repo-alt** [comment] 2020-10-30 07:57
Ok, regex/wildcard separation is borked. Idk what's the status of Bart's EC2 rewrite, should I PR the fix now or wait for it to settle down. 
Also, not sure if wildcards may contain dots. Currently I think I'll consider the string to be a regex if it contains any of `"|+?()[]"^$\` also previous code did automatically replace `*` with `.*` if it thought the string is a regex, I think that is a bad idea.

**Comment by Dream-Master** [comment] 2020-10-30 12:08
@repo-alt i would say make the fix.

**Comment by leagris** [comment] 2020-10-30 12:10
Just 2¢ idea: Add a Gregtech aware Import Export Bus which works like a Type Filter.
Having a Gregtech API expose a `getItemType` method would certainly help as well.

**Comment by repo-alt** [comment] 2020-10-30 12:20
Well, it means doing a GUI, meh

**Comment by Glease** [comment] 2020-10-30 16:19
I was also into the Type Export Bus ieda until I realized I have to make a model for it.

**Comment by GTNH-Afx237v7** [comment] 2020-10-30 16:56
Copy the existing ones?

**Comment by repo-alt** [comment] 2020-10-30 18:17
model is not a problem, GUI though, is not fun

**Comment by repo-alt** [comment] 2020-10-30 19:02
Ok, I was overcomplicating stuff, even though regex may not exactly work as advertized in the current version, wildcard does work. So pattern like `crushed* & !crushedPurified* & !crushedCentrifuged*` will filter what is asked by the topic starter.
I'll fix regex just in case, but it should not be necessary in real world cases.

**Comment by Prometheus0000** [comment] 2020-11-01 09:59
I can confirm that this works in 2.0.9.1a dev. Now that I have the right text at least.

**Closed** 2020-12-26 06:45 UTC
Labels: Mod: AE2, Mod: EC2, Mod: GT, Status: RFC (request for comment), Status: need to be tested, Type: oredict
