### ISSUE TITLE
[RFC] Bufferd Dynamo Hatches 

### ISSUE THREAD

**Issue by alphaNOVAircraft** [GTNewHorizons/GT-New-Horizons-Modpack#6901] opened 2020-11-07 01:07 UTC
#### Which modpack version are you using?
2.0.8.3 (but topic should be the same as in current versions) 
#

#### What do you suggest instead/what changes do you propose?
Bufferd Dynamo Hatches are in a weird state. The hatches themselfe come with a decent pricetag, but upgrading them to be able to output 4x the energy, adding a decent sized internal buffer and allowing turbines to use higher tier rotors (due to higher eu/t limit) doesnt really cost anything. Thus making the normal dynamo hatches (1 Amp) obsolete. Why should you make the efford of building a second turbine instead of just upgrading the dynamo hatch etc. 

I would suggest changing the recipe for a bufferd dynamo hatch to use: 
2 x Dynamo Hatch (same tier)
1 x Battery (same tier)
2 x Circuits (tier + 1, a 4 x dynamo hatch is basically a 1 amp hatch of the next higer tier, so + 1 should be fine) 
4 x 4x Superconductor (same tier)

Recipe is of course only a suggestion, maybe someone else got another idea how to make them more balanced. 
It would still be possible to get in the same tier not hardcore nerfing turbines, but it would also add some cost to using them.

**Comment by Prometheus0000** [comment] 2020-11-07 01:09
Duplicate of #6501

**Closed by Prometheus0000** 2020-11-07 01:09 UTC
Labels: Type: duplicate

**Comment by 0lafe** [comment] 2020-11-07 01:35
These are ++ right? I assume that means no touchey
