### ISSUE TITLE
Cannot find Lavender Fields biome

### ISSUE THREAD

**Issue by Grufoony** [GTNewHorizons/GT-New-Horizons-Modpack#14501] opened 2023-09-12 14:33 UTC
### Your Pack Version

2.3.0

### Your Server

private server

### Java Version

Java 8

### Type of Server

None

### Your Expectation

`Lavender Field` biome is nearly impossible to find in a 50k range from spawn with the nature's compass.
We're actually unable to go on with the quests.

The world was autogen within the server starting phase months ago.

### The Reality

see above

### Your Proposal

see above

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2023-09-12 15:05
ah lol. sounds like you changed world gen away from default. that would explain things.

Like the very first quest in the qb warns you about it.

**Comment by Grufoony** [comment] 2023-09-12 15:27
Ok changing only world type to `BIOMESOP` did not work... what can we do now? Is there a folder to partially delete if we don0t wanna lose the world?

**Comment by mitchej123** [comment] 2023-09-12 15:43
At this point you'll need to edit the level.dat and change the worldgen, the config was read and stamped on the level at world creation.  

Note: this will result in jagged worldgen; but can be minimized. What I'd suggest is go touch (place a block in) every chunk in your base(s) and no other chunks.  This will set the the last modified time for those chunks.  From there you can shutdown the server, remove any not recently modified region files, modify level.dat, and then start the server.  

Chunks are chunked (haha) together into region files, so there will be some old chunks that weren't trimmed.  These can be deleted/regenerated via worldedit, or you can just leave it as is.


DISCLAIMER: Make a backup, it's easy to mess this up.

**Comment by RiccardoBarbieri** [comment] 2023-09-12 16:27
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/43068188/2e6a4c8c-a5c4-4902-b56a-6daeff29ea91)
@mitchej123 
Do I have to modify the generatorName entry?

**Comment by mitchej123** [comment] 2023-09-12 16:30
I believe so, been a while since I've done it.  Also a note - `BIOMESOP` isn't supported as part of the pack, RWG/RTG are the expected world types.

I'd start a new world in single player and check what the NBT for level.dat says to be sure.

**Comment by RiccardoBarbieri** [comment] 2023-09-12 16:59
The problem is solved, we generated a single player world like you said and copied the contents of generatorName, generatorOptions and generatorVersion entries, although I believe that the only one that were necessary were generatorName and Version, some chunks are a little broken but i believe that those can be fixed with worldedit.

**Closed** 2023-09-12 17:00 UTC
Labels: Type: Not a Bug
