### ISSUE TITLE
Incomplete structure in Large Bronze Boiler

### ISSUE THREAD

**Issue by ZorbaHerbalist** [GTNewHorizons/GT-New-Horizons-Modpack#8350] opened 2021-08-04 12:42 UTC
#### Which modpack version are you using?
2.1.1.1a

#
#### If in multiplayer; On which server does this happen? 
Private server

#
#### What did you try to do, and what did you expect to happen?
After upgrade to 2.1.1.1a perfectly working Large Bronze Boiler shows "Incomplete structure".

#
#### What is your GTNH Discord username?
ZH

**Comment by Prometheus0000** [comment] 2021-08-04 12:45
See #8316. @Glease is this in the 1a version?

**Comment by Glease** [comment] 2021-08-04 12:46
If it doesn't work then it's 99% sure not in 2.1.1.1a, i.e. a duplicate of #8316 

As for a fix, please see that issue.

**Closed by Glease** 2021-08-04 12:46 UTC

**Comment by ZorbaHerbalist** [comment] 2021-08-04 13:15
It is 2.1.1.1a. Downloaded few hours ago from http://downloads.gtnewhorizons.com/Dev-Pack/Pack

http://jenkins.usrv.eu:8080/job/Gregtech-5-Unofficial/1415/ is obsolete i think. I've got 404.
