### ISSUE TITLE
Apparently random crash because of Spice of Life

### ISSUE THREAD

**Issue by Sacsy5** [GTNewHorizons/GT-New-Horizons-Modpack#11645] opened 2022-10-14 08:55 UTC
### Your GTNH Discord Username

Sacsy#2713

### Your Pack Version

2.2.3

### Your Server

SP

### Type of Server

Single Player

### Your Actions

The crash is seemingly random but it's always because of Spice of Life, sometimes happened in the overworld when I opened a chest containing food items, and it happened today 3 times in a row while in the nether not doing anything specific. Usually happens during the first minute of playing but sometimes (once during my play session yesterday) it does'nt happen at all.

### Crash Report

[crash-2022-10-14_10.32.06-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9784209/crash-2022-10-14_10.32.06-client.txt)
[crash-2022-10-14_10.28.48-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9784220/crash-2022-10-14_10.28.48-client.txt)
[crash-2022-10-14_10.17.30-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9784222/crash-2022-10-14_10.17.30-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by SlipperyPotatoes** [comment] 2022-10-20 17:43
I am able to replicate the same crash in my single player world. I am running version 2.2.0.0 of the pack. My crash report is this "https://paste.ubuntu.com/p/WRbCqKCdFr/". The crash occurs whenever you either try to hold a food item (aka anything that has a hunger value, including the lunchbox) or try to mouse over a food item in your inventory. Holding shift and passing over an item to move it from inventories does not cause a crash. My username on discord is Waltah#3548 if anyone needs me.

**Comment by Phil1216** [comment] 2022-12-19 03:26
Can confirm. It happens when I mouse over a food item. It wasn't happening yesterday.

**Comment by Phil1216** [comment] 2022-12-19 03:42
It doesn't happen with IC2 canned food (possibly because Spice of Life doesn't apply to it).

**Comment by SquareOne376** [comment] 2022-12-25 07:25
Same happened here, I have a potato laptop so I'm not sure if that has to do with anything. Some already finished and claimed quests "re-completed" as in they made the jingle sound and appeared onscreen when I loaded in the world before the crash. Was quick offloading (shift+click hold and drag) items into a chest when it crashed.

**Comment by SquareOne376** [comment] 2022-12-25 09:08
Ported entire instance file from TechnicL to Prism and it fixed itself? It even runs better? Am I nuts?

**Comment by hacatu** [comment] 2022-12-26 03:06
I've gotten the same crash three times now as well.  Very strange because I've been playing for a long time but I've only gotten it today.  [Here](https://pastebin.com/raw/bYZJfeFm) is the latest one.  It also doesn't actually happen when mousing over food for me - I was mousing over a rod of the skies that time I believe

**Comment by hacatu** [comment] 2022-12-26 03:12
[This](https://imgur.com/a/jrgcZ0u) is my inventory from the last time I got the crash, and immediately after taking this screenshot I crashed again when simply opening my inventory.  So this makes the game pretty much unplayable

**Comment by SquareOne376** [comment] 2023-01-04 11:00
> 

I've now updated to 2.2.8 and havent had the same crash since... seems pretty random... I hope you got you world working again.

**Comment by hacatu** [comment] 2023-01-04 16:07
I have been able to mitigate it - I only get this crash if I exit to the main menu and the re-open my world a couple times without closing the game.  So as long as I don't do that it hasn't returned.

**Comment by BritishCynic** [comment] 2023-01-28 21:18
As this crash has not had new comments for a while, it is being closed. If you can reproduce this crash on current dev, please leave a comment to re-open with a full log report of the crash.

**Closed by BritishCynic** 2023-01-28 21:18 UTC
Labels: Type: Crash, Mod: Spice Of Life

**Comment by miozune** [comment] 2023-02-22 06:13
Probably fixed by https://github.com/GTNewHorizons/SpiceOfLife/pull/26
