### ISSUE TITLE
Server tick in SP

### ISSUE THREAD

**Issue by Oueio** [GTNewHorizons/GT-New-Horizons-Modpack#16250] opened 2024-05-12 11:15 UTC
### Your GTNH Discord Username

oueio

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

My server tick in almost empty world (only have steam machines and bricked) blast furnace would be normal (20 tps)

### The Reality

Trying to getting some lava in 300m raise my server tick to 300ms, even there are nothing to load system (I checked on opis).
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/75951914/ffbe01a5-5661-4074-81d2-d915c4035f28)
On my UMV old base in another world even if i going somewhere else of base server tick has normal value (playable).
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/75951914/fb618cd8-3b14-4dd5-8a04-78c07eae6b70)

### Your Proposal

Please help me with this problem (Already tried writing in discord)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by elak93** [comment] 2024-05-12 11:16
Try downgrading random things. Or upgrading if they've fixed thaumcraft leaf decay

**Comment by Oueio** [comment] 2024-05-12 11:19
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/75951914/b0f4ffcf-0a99-4098-9ed4-fc4e7eff3efd)
Need to downgrade? Pack has version 2.5.3 already in mods

**Comment by Oueio** [comment] 2024-05-12 11:19
missclick

**Comment by Oueio** [comment] 2024-05-12 12:01
Downgrading to version RS 2.5.2 fixed issue

**Comment by chochem** [comment] 2024-05-12 15:11
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16092

**Closed by chochem** 2024-05-12 15:11 UTC
Labels: Type: bugMinor, Status: Triage
