### ISSUE TITLE
Muti Smelter (gregtech-5.09.34.14)

### ISSUE THREAD

**Issue by starstack14** [GTNewHorizons/GT-New-Horizons-Modpack#7533] opened 2021-02-25 16:56 UTC
#### Which modpack version are you using?
GTNH-dev 2.1.0.3a gregtech update to gregtech-5.09.34.14
#
#### If in multiplayer; On which server does this happen? 
private server core ultramine
#
#### What did you try to do, and what did you expect to happen?
not going to multi-smelter. Which put before the GT update are working

#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
fix

**Comment by repo-alt** [comment] 2021-02-25 17:01
A bit of translation: Newly built multiblock is not composing, what was built before the update works fine.
@bartimaeusnek was the multismelter switched to TT?

**Comment by Prometheus0000** [comment] 2021-02-25 17:05
It could also be the coil change.

**Comment by bartimaeusnek** [comment] 2021-02-25 17:18
core ultramine isn't supported. Same issue as thermos, it needs apache lang3

**Comment by Ritoshisan** [comment] 2021-03-03 04:01
The problem is not only with the multismelter, but also with pyrolysis, the same nonsense is not collected in the structure.

**Comment by Ritoshisan** [comment] 2021-03-03 04:02
The top of the structure in the center is not recognized at all.

**Comment by Ritoshisan** [comment] 2021-03-03 04:26
Try to singplayer. Problem not the termos

**Comment by mitchej123** [comment] 2021-03-03 05:19
No logs ✓
No useful info ✓
Unsupported Env (Ultramine) ✓

**Comment by mitchej123** [comment] 2021-03-03 05:20
(Check your gregtech.log, it's probably missing apache commons-lang3.jar)

**Comment by Ritoshisan** [comment] 2021-03-03 05:51
how can a structure be assembled without a top? but as soon as you put more than 3 blocks that are needed for the work, the structure is not going to be assembled.
[https://media.discordapp.net/attachments/703339623220379730/816381507769073684/unknown.png?width=400&height=225](url)
[https://media.discordapp.net/attachments/703339623220379730/816382329147752479/unknown.png?width=400&height=225](url)

**Comment by mitchej123** [comment] 2021-03-03 05:53
Is there anything going on in your gregtech.log?

**Comment by Ritoshisan** [comment] 2021-03-03 05:55
there are logs only from the ultramine server, but I didn’t find that this is because of the libraries, if necessary, I can throw it off.

**Comment by repo-alt** [comment] 2021-03-03 06:19
Does the structure work correctly in singleplayer?

**Comment by repo-alt** [comment] 2021-03-03 06:19
(@mitchej123 after you close the bug it is kinda hard to provide more info)

**Comment by Ritoshisan** [comment] 2021-03-03 06:30
> Does the structure work correctly in singleplayer?

No, it does not work, since it requires a minimum output, an input muffler and a service cabinet, and this is already more than 3+ blocks for a structure, it is simply not assembled.

**Comment by repo-alt** [comment] 2021-03-03 06:35
You mean Pyro oven does not check structure in the top 3x3 square? this is clearly a different issue.
Also does it work if you actually put the the hatches and the muffler on top?

**Comment by Ritoshisan** [comment] 2021-03-03 06:42
> You mean Pyro oven does not check structure in the top 3x3 square? this is clearly a different issue.
> Also does it work if you actually put the the hatches and the muffler on top?

yes that's right

**Comment by repo-alt** [comment] 2021-03-03 06:45
tbh I'm tempted to close the issue right now. Do you realize that is has nothing in common with the originally reported?

**Comment by Ritoshisan** [comment] 2021-03-03 06:57
> tbh I'm tempted to close the issue right now. Do you realize that is has nothing in common with the originally reported?

Yes, you can just close these problems of one nature.

**Comment by boubou19** [comment] 2021-03-03 08:32
as said by bart, your ultramine version has an outdated apache lang3 library. We had the issue on zeta with thermos, bart made a custom version of it searching for the new apache lang3, problem disappeared.

**Comment by repo-alt** [comment] 2021-03-03 15:01
Since pyro oven issue is separated https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7557 this one may be closed I believe. @starstack14 please report back if updating apache lang 3 didn't help

**Closed by repo-alt** 2021-03-03 15:01 UTC
Labels: Mod: Thermos Strikes Again, Type: not our fault
