### ISSUE TITLE
Greg tech remove metal tint config

### ISSUE THREAD

**Issue by Jimbno** [GTNewHorizons/GT-New-Horizons-Modpack#10538] opened 2022-06-24 17:21 UTC
### Your GTNH Discord Username

Jimbno

### Your Pack Version

2.1.2.4-5-dev

### Your Server

Dedidated SP server

### Type of Server

Single Player

### Your Expectation

use_machine_metal_tint=false should stop GT from overlaying its hideous blue tint over machines and GUIs

### The Reality

it does not work in this version

### Your Proposal

I propose that the config should indeed remove this disgusting blemish on machinery and ui 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment] 2022-06-25 06:38
Duplicate of #9599

**Closed by Glease** 2022-06-25 06:38 UTC
Labels: Type: bugMinor, Type: Visual
