### ISSUE TITLE
Rendering issues with BC tanks

### ISSUE THREAD

**Issue by Nicouuuuu** [GTNewHorizons/GT-New-Horizons-Modpack#6048] opened 2020-05-05 10:17 UTC
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
Placed a tank with molten iron inside on top of a machine
#
#### What happened instead? (Attach screenshots if needed)
The rendering was bizarre, we can see through the machine,
I Tried a few other configurations and the rendering was also glitched
Obviously I havn't tried that for every fluid but I tried with molten glass from the smeltery and it seems that for all the smeltery fluids into BC tanks are making rendering issues on machines : 
![2020-05-02_18 00 14](https://user-images.githubusercontent.com/62377720/81055788-b38aa500-8ec9-11ea-9b4c-98f78ca01b49.png)
![2020-05-02_18 00 20](https://user-images.githubusercontent.com/62377720/81055792-b4bbd200-8ec9-11ea-95b5-60f6dc197ebc.png)

Also transparent GT fluids inside BC tanks (like oxygen) are also making bizarre rendering with the near environnement as you can see on the picture with the mercury and the chests for example : 
![2020-05-04_19 50 03](https://user-images.githubusercontent.com/62377720/81055921-f6e51380-8ec9-11ea-9f17-955c5f8aa77d.png)
![2020-05-04_19 50 07](https://user-images.githubusercontent.com/62377720/81055924-f8164080-8ec9-11ea-8ad5-dc0af9d327d0.png)
![2020-05-05_00 59 44](https://user-images.githubusercontent.com/62377720/81055931-f9e00400-8ec9-11ea-8060-0cc37974b988.png)

#
#### What do you suggest instead/what changes do you propose?
Just correcting the graphic bugs

**Comment by Dream-Master** [comment] 2020-05-09 20:17
Only the red one is a BC Tank. The other is a tank form the BC tank additional mod.

**Comment by Prometheus0000** [comment] 2020-10-12 23:39
Duplicate of #5831

**Closed by Prometheus0000** 2020-10-12 23:39 UTC
Labels: Type: duplicate, Type: visual
