### ISSUE TITLE
OutOfBounds while mining

### ISSUE THREAD

**Issue by xhek** [GTNewHorizons/GT-New-Horizons-Modpack#7308] opened 2021-01-13 18:54 UTC
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Singeplayer
#
#### What did you try to do, and what did you expect to happen?
I was mining chalcopyrite ore with tinkers hammer nothing expected
#
#### What happened instead? (Attach screenshots if needed)
Mineraft crashed
#
#### What do you suggest instead/what changes do you propose?
OutOfBounds, Array Issue maybe?

Crashlog:
https://pastebin.com/GuBw8HSa

**Comment by Prometheus0000** [comment] 2021-01-13 19:03
Duplicate of #7289

**Closed by Prometheus0000** 2021-01-13 19:03 UTC
Labels: Type: duplicate
