### ISSUE TITLE
Game crash right after loading in world

### ISSUE THREAD

**Issue by SageOfStones98** [GTNewHorizons/GT-New-Horizons-Modpack#16674] opened 2024-07-03 20:25 UTC
### Your GTNH Discord Username

deadtome#3650

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Actions

Hi 
I just started the game and joined the world. After the loading screen I got into the world and it showed the starting text in the chat but the world was completely black and nothing loaded. After 3-4 seconds the game crashed then. When joining my test world it works perfectly fine.

Thanks in advance for any help!

### Crash Report

[crash-2024-07-03_22.12.34-server.txt](https://github.com/user-attachments/files/16090502/crash-2024-07-03_22.12.34-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by SageOfStones98** [comment] 2024-07-03 21:06
PS: I also tried reinstalling the modpack and copy and paste the world into the new folder. I still get a crash but for my untrained eyes the fail report looks different so I attach it as well. 
[crash-2024-07-03_23.03.33-server.txt](https://github.com/user-attachments/files/16090796/crash-2024-07-03_23.03.33-server.txt)

**Comment by chochem** [comment] 2024-07-03 21:14
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16531

**Closed by chochem** 2024-07-03 21:14 UTC
Labels: Type: Crash, Status: Triage

**Comment by SageOfStones98** [comment] 2024-07-04 05:33
@chochem Why is this getting linked to another seemingly unsolved issue which is already 3 weeks old? This won't help me

**Comment by Caedis** [comment] 2024-07-04 05:35
@SageOfStones98 they are saying you didnt follow
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/18713839/c19fb92c-95ce-4cef-aa02-afdda646281b)

**Comment by SageOfStones98** [comment] 2024-07-04 05:40
@Caedis What is this logic? The allegedly duplicate is just another crash of the game. Are all crashes automatically the same here? The description of the issue is not even the same. In the "original" post the game crashes when entering a certain area of the world. In my case I cannot even enter the save at all, it instantly crashes. And on top of that it is not solved as mentioned before.

**Comment by Caedis** [comment] 2024-07-04 05:45
The error is the same and its something we have not been able to recreate ourselves so its going to take a little bit of time to figure it out.

**Comment by KubaObeast209** [comment] 2024-07-06 11:13
@SageOfStones98 I have the same problem, hope we both get to play our worlds soon again.

**Comment by chochem** [comment] 2024-07-06 11:16
ah didnt see I was pinged sorry. yea its the same error (and several other tickets too). please discuss further over there to not spread things out. We don't have a clear idea yet, though some hints it could be corruption I suppose.

**Comment by KubaObeast209** [comment] 2024-07-06 18:57
@chochem Should I try to create a new world, or can I do something about it?
