### ISSUE TITLE
Twilight Forest crashes game, cannot load into world

### ISSUE THREAD

**Issue by mxHuber** [GTNewHorizons/GT-New-Horizons-Modpack#18015] opened 2024-11-17 17:52 UTC
### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Actions

Digging down in the Twilight Forest with an excavator. Cannot load into the world anymore, as it just crashes again.

### Crash Report

https://mclo.gs/VcE9GaJ

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Lyfts** [comment] 2024-11-17 17:54
![s](https://github.com/user-attachments/assets/d9286e8a-10d1-493c-b13b-6c59d3cc2440)
Searching "Twilight Forest", "Nagastone" or something similar on the issue tracker results in about a million issues identical to this one. 

Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16353 and many others.

**Closed by Lyfts** 2024-11-17 17:54 UTC
Labels: Crash, Status: Triage
