### ISSUE TITLE
Can't trade nagastone in shop for respawn

### ISSUE THREAD

**Issue by jentakmp2** [GTNewHorizons/GT-New-Horizons-Modpack#16750] opened 2024-07-14 14:29 UTC
### Your GTNH Discord Username

.

### Your Pack Version

GT: New Horizons 2.6.1 (The Twilight Forest 2.6.12)

### Your Server

.

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

I tried to trade nagastone in the shop for naga spawn egg.
I was not able to trade the nagastone.
I tried multiple different nagastones.
I tried in Twilight dimension as well.
I was only successfull in trading the coins.

### The Reality

.

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2024-07-15 20:11
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16380

**Closed by chochem** 2024-07-15 20:11 UTC
Labels: Type: bugMinor, Status: Triage
