### ISSUE TITLE
Native Ore Clusters from Netherrack Ores

### ISSUE THREAD

**Issue by Rubix2048** [GTNewHorizons/GT-New-Horizons-Modpack#8175] opened 2021-07-03 22:15 UTC
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
Use non-vanilla-stone ore (netherrack, red granite, etc) in thaumatorium to produce Witching Gadgets' Native Ore Cluster
#
#### What happened instead? (Attach screenshots if needed)
Although the recipe appears in the thaumatorium and is selectable, unless the ore is based in vanilla stone, essentia is not drawn in via pipes as expected. It is possible that the crucible works appropriately (I do not have one set up anymore) and the NEI recipe is present with all forms of the ore. Separately, netherrack and endstone ores do not have their inherent double bonus applied in the NEI recipe (their recipe says it makes 2 native chunks just like the overworld ores)
#
#### What do you suggest instead/what changes do you propose?
The ore purification recipe should work on non-vanilla-stone ores in the thaumatorium, and netherrack/endstone ores should be doubled over overworld stone ores.
#
#### What is your GTNH Discord username?
Khona Betwanhe#7122

**Comment by Glease** [comment] 2021-07-03 22:47
Duplicate of #8095

**Closed by Glease** 2021-07-03 22:47 UTC

**Comment by cubic-chariot** [comment] 2022-07-31 13:38
This is not an exact duplicate. As of 2.1.2.3qf, the recipe still makes only two native clusters when processing netherrack ores, which is the same amount produced for stone ores. The issue addressed on #8095 (not being able to make native clusters in a thaumatorium) was fixed, however.
