### ISSUE TITLE
gt wrench on gc fuel loader

### ISSUE THREAD

**Issue by EuroZona** [GTNewHorizons/GT-New-Horizons-Modpack#15366] opened 2024-01-18 22:03 UTC
### Your GTNH Discord Username

eurozona

### Your Pack Version

2.5

### Your Server

private server

### Java Version

Java 17

### Type of Server

Don't know

### Your Actions

just broke a fuel loader with a gregtech electric wrench and the server crashed

### Crash Report

[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13982010/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2024-01-18 23:36
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15195

**Closed by chochem** 2024-01-18 23:36 UTC
Labels: Type: Crash, Status: Triage
