### ISSUE TITLE
LCR missing Kerogen recipe

### ISSUE THREAD

**Issue by hacatu** [GTNewHorizons/GT-New-Horizons-Modpack#13978] opened 2023-07-18 06:46 UTC
### Your GTNH Discord Username

hacatu

### Your Pack Version

2.3.4

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Expectation

Note that I have updated the mods as suggested by https://gtnh.miraheze.org/wiki/Dev_Release_Stability, and additionally I have updated GT++ to 1.9.57

However, I'm pretty sure this is just a missing recipe

The regular chemical reactor has a recipe: 250 mb heated fulvic acid -> 250 mb Kerogen, 18 ticks @ 128 EU/t on circuit 10; however, the LCR has no corresponding recipe

### The Reality

The LCR has no corresponding recipe

### Your Proposal

Add an LCR recipe for Kerogen, possibly skipping the fluid heater step before and/or coke oven step after

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2023-07-19 20:54
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13896

**Closed by chochem** 2023-07-19 20:54 UTC
Labels: Type: bugMinor, Status: Triage
