### ISSUE TITLE
Processing array casing count inconsistency

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#8358] opened 2021-08-04 21:13 UTC
#### Which modpack version are you using?
2111a - dev
#
#### What did you try to do, and what did you expect to happen?
Upgraded from 2110 and almost all of my processing arrays broke with the message: Invalid structure
As it turns out the robust casing count is changed but still 14 stated at the tooltip
![kép](https://user-images.githubusercontent.com/7230430/128255334-c8c026b9-cc78-40c1-94b7-4ac66088b6cd.png)

After i changed 1 input bus to a casing the structure got completed
#
#### What happened instead? (Attach screenshots if needed)
Either the tooltip is wrong or the multi detection
#
#### What do you suggest instead/what changes do you propose?
update the tooltip or change the requirement back to the original(14)
#
#### What is your GTNH Discord username?
szajkop # 0522

**Comment by Glease** [comment] 2021-08-04 22:22
Duplicate of #8319

**Closed by Glease** 2021-08-04 22:22 UTC
