### ISSUE TITLE
Item Detector Cover crash

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#9244] opened 2021-12-23 00:12 UTC
### Your GTNH Discord Username

Pandoro#4811

### Your Pack Version

2.1.2.0

### Your Server

delta

### Your Actions

Placed an item detector cover on an input bus
Game crashed
Tested with full and empty input bus, when removing it always crashes. When placing it, it looks like that an empty input bus doesn't cause the crash.

Not sure if this is fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/824
Could be a duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9181
I'm just not sure if item and fluid covers are considered the same and if the PR fixes both.
Crash when removing seems like is the same, looks different when placing it on full input bus

### Crash Report

Crash when removing it
[crash-2021-12-23_01.06.55-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7765851/crash-2021-12-23_01.06.55-client.txt)
Crash when adding it to a full input bus
[crash-2021-12-23_00.50.50-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7765853/crash-2021-12-23_00.50.50-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by bombcar** [comment] 2021-12-23 00:28
Can you try with 2.1.2.1 zip? Or latest gt5u : http://jenkins.usrv.eu:8080/job/Gregtech-5-Unofficial/lastSuccessfulBuild/artifact/build/libs/gregtech-1.7.10-5.09.40.16-1-g9fb99c2.jar

**Comment by Glease** [comment] 2021-12-23 10:23
Duplicate of #9181

**Closed by Glease** 2021-12-23 10:23 UTC
Labels: Type: Crash, Status: Triage

**Comment by Sphyix** [comment] 2021-12-23 13:26
Yea, latest gt5u fixes it. I guess glease was faster than me to close this
