### ISSUE TITLE
Crush when eating cake

### ISSUE THREAD

**Issue by Alekseiev** [GTNewHorizons/GT-New-Horizons-Modpack#14065] opened 2023-07-25 19:37 UTC
### Your GTNH Discord Username

utl1ght

### Your Pack Version

2.3.5

### Your Server

private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Actions

Eating minecraft vanilla cake few times. When loggin in back to server and trying to eat it again - crush

### Crash Report

[crash-2023-07-25_22.21.38-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12165031/crash-2023-07-25_22.21.38-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment] 2023-07-26 00:17
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14033

**Closed by miozune** 2023-07-26 00:17 UTC
Labels: Type: Crash, Status: Triage
