### ISSUE TITLE
Adding LogisticPipes (already considered) mod is open source

### ISSUE THREAD

**Issue by Frafx** [GTNewHorizons/GT-New-Horizons-Modpack#7005] opened 2020-11-27 18:52 UTC
2.0.9.0

I suggested a mod to add to DreamMaster and he liked my idea, and suggest to make a ticket

I already write a draft for the recipes and i think he agreed with me about:
-if u want to use it, use it if not dont use it makes not differences
-will be a BETTER powerfull storage system in MV age.
-will be a better and powerfull autocrafting system in HV age (autocrafting sytem willl requires stainless steel).
-everything you will do with this mod will be not lose when u hit applied since you can interface it without losing storage and autocrafting.
-fluids pipe will be removed i think and recipes for pipes tweaked from my draft
-every module that needed chipset in non tweaked recipes will need still chipset plus a circuit: 
if iron chipset will need lv circuit, if gold chipset will need mv circuit, if DIAMOND chipset will need HV circuit.
Every module will need plastic sheet.
If you want to know about more
[recipes.pdf](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5609263/recipes.pdf)
ZenScript (cant upload .zs files)
[LP.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5609265/LP.txt)

Dream also said to post the config, since there is a lot of possibilities to make the mod lighter:
[LogisticsPipes.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5609495/LogisticsPipes.txt)

**Comment by Prometheus0000** [comment] 2020-11-27 18:55
Duplicate of #3286, #3237. Did you read everything in those issues first?

**Comment by Frafx** [comment] 2020-11-27 18:58
> Duplicate of #3286, #3237. Did you read everything in those issues first?

Yeah i read it, they are old tickets so i think its not a problem to repropose

**Comment by Prometheus0000** [comment] 2020-11-27 19:02
Ok, well then I'm going to say I'm against it. We already have the project red pipes (as mentioned before), and it's laggy (as mentioned before), and we already have a superior system in AE (also mentioned before).

Maybe you should address all of the points brought up in the previous issues. And I assume Dream forgot he said it, but he previously said no anyway in the issue.

**Comment by Frafx** [comment] 2020-11-27 19:31
> Ok, well then I'm going to say I'm against it. We already have the project red pipes (as mentioned before), and it's laggy (as mentioned before), and we already have a superior system in AE (also mentioned before).
> 
> Maybe you should address all of the points brought up in the previous issues. And I assume Dream forgot he said it, but he previously said no anyway in the issue.

Personally i hated ProjectRed transportation like EnderIO storage system,if its laggy idk, i never had issues i make new ticket since the last one are 2 and half years, of course AE is superior i just like the idea to have also a really good storage/autocraft system capable to interface with the superior one in the future. I add this mod to my singleplayer world and im loving it, i still cant wait to get AE system.Honestly if i didnt add LP i wouldnt use project red or EnderIO since is also HV maybe not really worth it if you have already a setup project red.

**Comment by Dream-Master** [comment] 2020-11-27 20:04
@Prometheus0000 I am not against it at all. Long time ago  we try to add LP. But minetweaker scripts not working so we change to project red. For my taste not the best replacement mod. After a year or so the issue in Lp was fixed but we not try to re add it.

**Comment by Dream-Master** [comment] 2020-11-27 20:08
idk how laggy it is . The lastest 1.7.10 version I never test. I can do a test run in sp or we test it on zeta for be sure.

**Comment by 0lafe** [comment] 2020-11-27 20:16
If we add LP we should probably disable the PR item movement recipes right? LP is definitely better it seems, so I'm personally all for this, especially if we have scrips already.

**Comment by Ethryan** [comment] 2020-11-27 22:26
I think i created a script for LP that lies on Dreams mods-get-gregged github, it probably needs to be edited but it’s better than starting from scratch

**Comment by Dream-Master** [comment] 2020-11-27 22:44
i remove dupe tag because the other issues both closed

**Comment by Prometheus0000** [comment] 2020-11-27 23:03
Technically, we should close this and reopen an older one, but I didn't do that solely because they're very long.

**Comment by mitchej123** [comment] 2020-11-27 23:40
I'm curious @Frafx @Ethryan or anyone else who's tried; how much does this increase the loading time of the pack by?

**Comment by boubou19** [comment] 2020-11-27 23:44
What does offer logistic pipes that is not provided by project red?

**Comment by Frafx** [comment] 2020-11-28 01:06
> I'm curious @Frafx @Ethryan or anyone else who's tried; how much does this increase the loading time of the pack by?

Literally a couple of seconds i guess. If it takes 15 seconds more idk the first start will take like 30. Its a mod adding small items, without oredict stuff,ores and few recipes.

**Comment by Frafx** [comment] 2020-11-28 01:14
For me, more fun and it feels better, faster, smother and its more satisfies lol. In terms of game mechanics ProjecRed litteraly copied Logistics pipe, I refused to play project red transportation but as far I've see and since is a copy the mains features are not missing. But logistic maybe has a better autocrafting more modules more customization and pipes, as u can see PR transportation is just the bad copy and since i have the possibilities to play with LP (still balance to the modpack) i simply refused EnderIO and PR.

**Comment by yukieiji** [comment] 2020-11-28 05:43
LP are often buggy and items can drop out. In contrast, PR is less buggy and items don't drop out. but yet it is a bad copy?

**Comment by bookerthegeek** [comment] 2020-11-30 11:58
Why not have both Logistic Pipes and the Project Red Item Pipes? I feel that they can fill two different roles aesthetically. If you don't like one then use the other? Unless their is a compelling reason not to have options on how to do things?

**Comment by Dream-Master** [comment] 2020-11-30 16:33
no one said that we remove project red

**Comment by bookerthegeek** [comment] 2020-11-30 19:01
Sorry @Dream-Master I was responding to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7005#issuecomment-734973491, I should have quoted it.

**Comment by Frafx** [comment] 2020-12-01 15:30
> LP is often buggy and items can drop out. In contrast, PR is less buggy and items don't drop out. but yet it is a bad copy?

Im not aware of this problems, keep sending feedback if you know more

**Comment by Frafx** [comment] 2020-12-01 15:34
> Why not have both Logistic Pipes and the Project Red Item Pipes? I feel that they can fill two different roles aesthetically. If you don't like one then use the other? Unless their is a compelling reason not to have options on how to do things?

Yeah, that's what i would like, having a choice since i don't like the other ones. A reason that the mod isn't in the pack is that they obviously can't ignore lag/bug issues.

**Comment by yukieiji** [comment] 2020-12-01 17:51
> Im not aware of this problems, keep sending feedback if you know more (im not saying that you are wrong)

Some of the bugs I know about include the following I'm sure there were others, but I've forgotten them...
・Cutting the pipe by Facade or Pipe Plug, but not disconnected from the logistic network.
・Compatibility with AE2 does not work properly.

**Comment by Prometheus0000** [comment] 2020-12-01 17:59
> ・Compatibility with AE2 does not work properly.

When you have AE, use that instead

**Comment by yukieiji** [comment] 2020-12-01 19:49
> When you have AE, use that instead

AE2 is useful but not as versatile as LogisticPipes or ProjectRed...
By using the Provider module and ItemSink module in the logistics pipe the ME network can be managed in the LogisticPipes network, but it should not have worked properly.

**Comment by 0lafe** [comment] 2020-12-01 23:20
We should probably address how useless much of PR pipes are atm. Imo it would be nice to have LP, but also give it some compelling usage pre AE. Maybe it's time we finally discourage manual labor pre AE? 



> Sorry @Dream-Master I was responding to [#7005 (comment)](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7005#issuecomment-734973491), I should have quoted it.

Definitely don't have to remove it, but I'm not sure they really need to both be here. I don't mean removing all of PR, but it seems weird to have such similar stuff.

**Comment by Ethryan** [comment] 2020-12-03 10:22
I am tinkering around with a .zs script for LP on [Link](https://github.com/Ethryan/GTNH-Faithful-Textures/tree/Ethryan-Temp-1/Scripts), right now only a few assembler and circuit assembler recipes are added, the rest are in need of changing. (The unrouted LP pipe recipe added is not working right now.)

Now for my question, should i continue and add the rest of the items and blocks, or is it a lost cause?

**Comment by Dream-Master** [comment] 2020-12-03 10:27
@Ethryan no i would say add the missing ones and we can test it on zeta

**Comment by Dream-Master** [comment] 2020-12-03 10:27
if the lag went bad we not add it but its a nice additional mod.

**Comment by Frafx** [comment] 2020-12-03 18:18
> I am tinkering around with a .zs script for LP on [Link](https://github.com/Ethryan/GTNH-Faithful-Textures/tree/Ethryan-Temp-1/Scripts), right now only a few assembler and circuit assembler recipes are added, the rest are in need of changing. (The unrouted LP pipe recipe added is not working right now.)
> 
> Now for my question, should i continue and add the rest of the items and blocks, or is it a lost cause?

I added to my script folder and as you said its not working however,
Assembler.addRecipe(UnroutedLPipe, [<ore:stickLongSteel> * 2, <minecraft:glass_pane>, <ore:wireFineGold> * 2], null, 100, 30);
-I agree with long steel sticks but i would prefer a glass tube instad of glass pane. But i think it should give still 3 pipes (like ae2)
Assembler.addRecipe(BasicLPipe * 4, [UnroutedLPipe * 4, <ore:smallGearRoseGold> * 2, <ore:stickDiamond> * 2, <ore:circuitGood> * 2, <ore:wireFineSilver> * 16, <ore:boltSteel> * 4], <liquid:molten.solderingalloy> * 72, 800, 30);
-i dont get it why rose gold it better any gold, and instad of stick diamond maybe something else
CircuitAssembler.addRecipe(BlankModule, [<ore:plateStone>, <ore:circuitGood>, <ore:foilPolyethylene> * 2, <ore:wireFineRedstoneAlloy> * 4, <EnderIO:itemBasicCapacitor> * 2], <liquid:molten.lead> * 144, 900, 30);
-If modules will crafted with circuits from lv to hv, i think is too annoying to craft mv circuit also for blank module, it will be enough a lv circuit.

Also im not conviced with the pipes (mk1-2-3, provider,crafting etc) i dont like the fact that need gears and sticks but i would still use chipset but no idea how.

**Comment by Ethryan** [comment] 2020-12-04 07:54
I havn't had time to work on the script more but i think i will do so this weekend.
Mandatory overtime sucks.

And as stated the script is still a work in progress, i will probably balance it better when everything is added.

**Comment by Frafx** [comment] 2020-12-04 12:33
> I havn't had time to work on the script more but i think i will do so this weekend.
> Mandatory overtime sucks.
> 
> And as stated the script is still a work in progress, i will probably balance it better when everything is added.

Get the time you need don't worry :), what i've seen is good but i don't decide anything i think the recipes will be decied by DreamMaster IF the mod will be added.

**Comment by 0lafe** [comment] 2020-12-04 19:23
Just curious @Ethryan what tier are you aiming to put them in? Keep with PR ideas and do MV or something else? Also, do you have general ideas of the cost? Imo PR is pretty useless atm due to its cost within MV tier, which needs very little complex automation. I have some really fun ideas on how to make these more useful even with recipes similar to PR, but I think people might get mad. Imo moving AE up some tiers to force complex automation with something that has complexity to it seems fun. Or drastically increasing the requirements pre AE to all but require you to do some fancy automation tasks

**Comment by Ethryan** [comment] 2020-12-05 09:09
I think the pipes will start in LV, but some of the more advanced functions will be MV or HV, 
Right now i am considering disabling the LP autocrafting system entirely.

**Comment by Frafx** [comment] 2020-12-08 10:18
> I think the pipes will start in LV, but some of the more advanced functions will be MV or HV,
> ~Right now i am considering disabling the LP autocrafting system entirely.~ - Moved to HV
> 
> Only got crafting, pipes, 2 components and 4 modules left todo. And the Glasses.

Great! Send the .zs here where your done. About autocrafting i think HV is perfect

**Comment by bartimaeusnek** [comment] 2020-12-15 18:24
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/3237
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/3286

Cleary proves that this mod is redudant and laggy. It should not be added.

**Comment by bookerthegeek** [comment] 2020-12-29 06:48
@bartimaeusnek I read through both the prior issues you [commented](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7005#issuecomment-745476493). I see a lot of discussion both for and against adding LP to the pack. What I don't see is anything in either of those previous threads that facts that support the idea that LP should not be added other then users spouting off that it causes lag. Just an fyi; All mods cause lag. Vanilla causes lag.

For everyone else, if the idea that the mod causes lag is the deciding factor, the question becomes if the amount of CPU cycles that LP takes is worth adding it or not. And to be clear I've seen both amazing setups that automate better than and impact less than AE2, and I've seen setups that are tiny and make a server unplayable.

So my idea/question is as follows:
 - Build a setup for a super late game item that involves multiple of multiple processes
 - Save this world and upload it somewhere, I will download it.
 - Anyone who wants to can automate it with AE and then LP, profiling it both times.

Then, we can compare the profiles and see what the answer is. If something comes up maybe it can be fixed as the mod is modifiable. And if it comes out that the issues are to big to fix or live with, the that is also an answer. 

While I feel I'm pretty amazing at automation, I've still a lot to learn about GT which is why A GT-Master ( ;) )of it should design the actual test world.

Also for what it is worth, I think LP should be added in upper MV lower HV, moving PR down to Mid Range LV.

**Comment by Prometheus0000** [comment] 2021-01-14 04:06
BTW is there any reason that the applicable code can't simply be moved to the RP version if they're so similar?

**Closed** 2021-06-22 17:29 UTC
Labels: Status: FixedInDev, Status: RFC (request for comment), Type: additional Mod, Type: suggestion
