### ISSUE TITLE
Spice of Life crashes the game

### ISSUE THREAD

**Issue by koiNoCirculation** [GTNewHorizons/GT-New-Horizons-Modpack#16328] opened 2024-05-21 01:11 UTC
### Your Pack Version

2.6.0

### Your Server

private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Actions

Open ae terminal, search 'hot ingots'(may vary depends on your save), then something triggers the crash from Spice of Life.
It's claimed to be fixed before.
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12696
I have to disable food modifier(crash source) before it's fixed.

### Crash Report

![f0f1bc1d2db9730fd8617f2ca84c3547](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/57739338/faba0129-7603-4878-a473-ee29750f8cfd)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment] 2024-05-25 15:39
It could be caused by corrupted jar, try reinstalling the pack especially if you're using CF. Closing as duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14471.

**Closed by miozune** 2024-05-25 15:39 UTC
Labels: Type: Crash, Status: Triage
