### ISSUE TITLE
Industrial TNT Voiding in Super Chest I and II

### ISSUE THREAD

**Issue by DragonStorm25** [GTNewHorizons/GT-New-Horizons-Modpack#10528] opened 2022-06-23 03:28 UTC
### Your GTNH Discord Username

Ant#3686

### Your Pack Version

2.1.2.4dev5

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I tried to store Industrial TNT in a super chest to buffer a large amount.

### The Reality

After storing 65 ITNT, the super chest voids anything else put into it. This happens when the super chest is connected to my AE2 system, when it's unconnected, when it's directly touching the output bus, and when it's being piped using a GT pipe. It also occurs with a freshly crafter super chest. This has only been tested with super chest I and II. It does not void when placed manually, and this does not occur with other items I am storing, such as carbon dust and gelled toluene.

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment] 2022-06-23 03:51
Maybe duplicate of #10454. Can you update GT and see if it works? https://github.com/GTNewHorizons/GT5-Unofficial/releases/tag/5.09.40.57-pre

**Comment by BritishCynic** [comment] 2023-01-28 20:22
This behaviour does not occur on 2.2.8, this issue can be closed.

**Closed** 2023-01-28 20:26 UTC
Labels: Type: bugMinor, Status: Triage
