### ISSUE TITLE
[SUGGESTION] Larger AE2 crafting units

### ISSUE THREAD

**Issue by AlexBucket** [GTNewHorizons/GT-New-Horizons-Modpack#4382] opened 2019-04-24 10:55 UTC
Since some of the autocrafting in GTNH can be quite convoluted, can we get larger AE2 proccesors? The largest available now is 64k and it would be much nicer if they would be bigger; 256k, 1064k etc. Even just those 2 would be so much nicer

**Comment by DietmarKracht** [comment] 2019-04-24 11:06
What do you craft to need such large processors?

**Comment by AlexBucket** [comment] 2019-04-24 11:08
> What do you craft to need such large processors?

Because GTNH?

Heres a 4096k ME storage drive, with a lot of components that I already have sitting around in my AE
![image](https://user-images.githubusercontent.com/34566584/56655065-181afd80-66d5-11e9-87e4-212731e5b8ba.png)

**Comment by bHXDgiuMa5yLHyC8** [comment] 2019-04-24 18:54
You might want to check these mods out:

https://github.com/AzazeII/Applied-Integrations/

https://minecraft.curseforge.com/projects/extra-crafting-storage?gameCategorySlug=mc-mods&projectID=295054

**Comment by draknyte1** [comment] 2019-04-24 19:00
> You might want to check these mods out

It’s actually a suggestion for GT++ in the wrong place. Which conveniently, is also a better idea than adding more AE2 addon mods.

**Comment by Dream-Master** [comment] 2019-04-25 01:34
ok but when a mod exists that  add only bigger crafting units why we need to add it our self ?

**Comment by draknyte1** [comment] 2019-04-25 01:55
> It’s actually a suggestion for GT++ in the wrong place. Which conveniently, is also a better idea than adding more AE2 addon mods.

It has nothing to do with NH. This was just Alex’s reason why he’d like them. 
Again, wrong GitHub. 

Plus, adding more mods is always worse than reusing existing mods.

**Comment by bartimaeusnek** [comment] 2019-04-25 02:00
> Plus, adding more mods is always worse than reusing existing mods.

If the existing mods are maintainable for us with their license, i agree, otherwise, i'd prefer another MIT mod over an extended ARR mod.

**Comment by Dream-Master** [comment] 2019-04-25 02:10
The mod is from zoko long time gtnh player. Its a GNU license
https://github.com/Zoko061602/ExtraCraftingStorage

**Comment by draknyte1** [comment] 2019-04-25 02:15
Just seems pointless to add a dead mod that hasn't been updated in ages, when I'm going to add these regardless of what you do.

#Bloat

**Comment by Dream-Master** [comment] 2019-04-25 02:15
And btw the mod is 13 or 14 kb small

**Comment by Dream-Master** [comment] 2019-04-25 02:15
look at rv3 branch @draknyte1

**Comment by draknyte1** [comment] 2019-04-25 02:16
My point still stands, you'd just be adding redundant stuff.
Because again, this suggestion was for _ME_ and will be done regardless of whatever GTNH does.

**Comment by Dream-Master** [comment] 2019-04-25 02:16
7 days ago and btw i have zoko here in Discord can contact him

**Comment by repo-alt** [comment] 2020-04-16 23:24
What is the status of this issue?

**Comment by Dream-Master** [comment] 2020-04-16 23:31
@repo-alt I am not sure  but if we add this to ae2 we dont need an extra mod

**Comment by draknyte1** [comment] 2020-04-16 23:31
I don’t think a ticket was ever made in my side so I probably forgot. 🤦🏻‍♀️

**Comment by GTNH-Colen** [comment] 2020-04-16 23:31
I thought we already added these?
<img width="624" alt="Screenshot 2020-04-17 at 00 31 16" src="https://user-images.githubusercontent.com/54497873/79516260-cc2e3a80-8042-11ea-99fc-2ae4f1408d45.png">

**Comment by Dream-Master** [comment] 2020-04-16 23:33
but better put it into ae2 . It's ae2 stuff and we forked the mod allready

**Comment by Dream-Master** [comment] 2020-04-16 23:34
@GTNH-Colen oh if we add it all fine and we can close the issue.

**Comment by draknyte1** [comment] 2020-04-16 23:34
> My point still stands, you'd just be adding redundant stuff.
> Because again, this suggestion was for _ME_ and will be done regardless of whatever GTNH does.

Read previous post. 
My mods still called MiscUtils at heart and it was intended for my repo, not here. 🤷🏻‍♀️

**Comment by repo-alt** [comment] 2020-04-16 23:34
Sometimes I see some wisdom in AE2 maintainer practice to automatically close all tickets having no activity for a year.
And no, it is fine being in EC2 unless we move the storage cells themselves, which makes little sense

**Comment by repo-alt** [comment] 2020-04-16 23:36
(Unless we want to get rid of EC2, which is desirable but not very realistic)

**Comment by GTNH-Colen** [comment] 2020-04-16 23:36
> @GTNH-Colen oh if we add it all fine and we can close the issue.

I haven't tested them but they are in NEI and have recipes at least so assumed they were done?

**Comment by Prometheus0000** [comment] 2020-10-09 19:23
We already have them

**Closed by Prometheus0000** 2020-10-09 19:23 UTC
Labels: Mod: EC2

**Comment by repo-alt** [comment] 2020-10-09 19:39
I heard that they are not working though

**Comment by Dream-Master** [comment] 2020-10-09 19:42
Who said this and why isnt this reported?

**Comment by Prometheus0000** [comment] 2020-10-09 19:45
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5264#issuecomment-706362990

They could do with a more permanent fix if you want to go at it.

**Comment by repo-alt** [comment] 2020-10-09 19:58
EC2, nah, it's ok.
