### ISSUE TITLE
Duplication of any item or stack of items

### ISSUE THREAD

**Issue by DualBallers** [GTNewHorizons/GT-New-Horizons-Modpack#6365] opened 2020-07-07 21:15 UTC
2.0.9.0

I found a very easy duplication method of any item or stack of items, related to issue #6296.

Please let me know if I should expand on the issue here or another place.

**Comment by DualBallers** [comment] 2020-07-10 18:49
Haven't heard anything for a couple of days, so I guess there is no issue posting this here?

Steps to recreate:

- Open the Wireless Crafting Terminal
- Place any item, or stack of items in any of the crafting slots, and place the cursor over the item
- If the Terminal is placed in the first hotbar slot, press 1 (if second press 2, and so on...)
![image](https://user-images.githubusercontent.com/30087707/87186848-7b01b000-c2ec-11ea-82c7-aa778aaa286f.png)
- Close the Terminal with Escape
- Open the Terminal again, and observe that the item is now duplicated
![image](https://user-images.githubusercontent.com/30087707/87187006-c451ff80-c2ec-11ea-8396-31d992d75343.png)
- Repeat a couple of times
![image](https://user-images.githubusercontent.com/30087707/87187239-23177900-c2ed-11ea-808a-2efd1bf072cd.png)

Solution?
When the terminal is open it should not be possible to move items from the crafting grid with the 1-9 shortcut function, or at least it should not work when moving to the terminal position in the hotbar.

**Comment by bigbass1997** [comment] 2020-07-11 13:31
I've transferred the fork currently used in the pack to the GTNewHorizons organization (was a personal fork) to make fixing this easier. https://github.com/GTNewHorizons/WirelessCraftingTerminal

**Comment by repo-alt** [comment] 2020-07-11 13:34
As far as I understand the dupe is possible only with EC2 "Universal" crafting terminal, not WCT, WCT just crashes in that scenario.

**Comment by yukieiji** [comment] 2020-07-11 14:05
I've confirmed that this issue occurred with WirelessCraftingTerminal

**Closed** 2020-10-10 12:55 UTC
