### ISSUE TITLE
crash-2024-09-01_12.55.39-server.txt

### ISSUE THREAD

**Issue by ericcleveland841** [GTNewHorizons/GT-New-Horizons-Modpack#17174] opened 2024-09-01 17:07 UTC
### Your GTNH Discord Username

baseballswag841

### Your Pack Version

2.6.1

### Your Server

private server

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

The repair profile function in Curse Forge. 

### Crash Report

https://mclo.gs/UlaSg8M 

![cf](https://github.com/user-attachments/assets/f40fc6be-2693-4236-86a4-52784e76e64a)

![IMG_0560](https://github.com/user-attachments/assets/1c89b462-a686-489f-94a4-328c02e44b06)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Lyfts** [comment] 2024-09-01 17:13
![s](https://github.com/user-attachments/assets/d9286e8a-10d1-493c-b13b-6c59d3cc2440)
Searching "Twilight Forest" or something similar on the issue tracker results in about 50 issues identical to this one. Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16353 and about a gazillion others.

You can update twilight forest to https://github.com/GTNewHorizons/twilightforest/releases/tag/2.6.12

**Closed by Lyfts** 2024-09-01 17:13 UTC
Labels: Type: Crash, Status: Triage
