### ISSUE TITLE
can't use shift + mouse wheel in fluid processing pattern terminal

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#11388] opened 2022-09-21 22:34 UTC
### Your GTNH Discord Username

Alexdoru#9395

### Your Pack Version

RC3

### Your Server

solo

### Your Expectation

be able to use shift + mouse wheel in the fluid processing pattern terminal when hovering hover an item that has ore dic ( a circuit) to scroll through the different circuit options

### The Reality

it doesn't scroll

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment] 2022-09-22 03:57
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11118

**Closed by miozune** 2022-09-22 03:57 UTC
Labels: Type: bugMinor, Status: Triage
