### ISSUE TITLE
Hastealloy N dense plate bending recipe broken

### ISSUE THREAD

**Issue by NeroOneTrueKing** [GTNewHorizons/GT-New-Horizons-Modpack#13170] opened 2023-04-09 15:03 UTC
### Your GTNH Discord Username

NeroOneTrueKing#5311

### Your Pack Version

2.3.0

### Your Server

private server

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

Create a dense Hastelloy-N plate with the Circuit [9] bending machine recipe of plates --> dense plate.

### The Reality

It makes a double plate instead:
![image](https://user-images.githubusercontent.com/28197216/230780366-c28fe14e-cd86-4e9d-9a8c-7dd2c69cd68b.png)

### Your Proposal

Fix recipe to create a dense plate.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LewisSaber** [comment] 2023-04-09 15:08
closed as duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12873

**Closed by LewisSaber** 2023-04-09 15:08 UTC
Labels: Type: bugMinor, Status: Triage
