### ISSUE TITLE
CraftPresence - Discord Rich Presence stopped working with GTNH config

### ISSUE THREAD

**Issue by endervad** [GTNewHorizons/GT-New-Horizons-Modpack#13703] opened 2023-06-14 18:30 UTC
### Your GTNH Discord Username

endervad

### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Upon starting the game my Discord profile had status of me playing GTNH including info about the world, etc.

### The Reality

Since yesterday nothing shows up. If I reset CraftPresence config, Rich Presence starts working but with default config. Confirmed this issue with a friend.

### Your Proposal

I don't know what needs to be done to fix this..

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by CDAGaming** [comment] 2023-06-14 22:04
@endervad Under a closer look at v2.3.0, it is using CraftPresence v2.0.0 Beta 2

Since v2.0.0 has long-since been released as of earlier last month, v2 Alphas and Betas are unsupported.
I will however look into this, but I will advise updating your pack to v2.3.4 which contains the supported releases, as well as major fixes for some issues GT:NH itself experienced.

**Comment by chochem** [comment] 2023-06-14 22:06
well for gtnh itself 2.3.0 is stable and broadly recommended. while 2.3.4 is a dev release and rather untested. but it might be fine to just update craftpresence to 2.0.5

**Comment by CDAGaming** [comment] 2023-06-14 22:07
Indeed, updating to 2.0.5 or a later release of CraftPresence is also recommended.
That being said, I am testing 2.3.0 to see if their issue can be reproduced,
albeit it'll be difficult as they did not produce a log in this ticket.

**Comment by CDAGaming** [comment] 2023-06-14 22:16
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/16328918/c6257158-0b18-440d-ab1a-f9ee60307ae4)
It seems as though v2.3.0 is using an invalid Client ID:
Ref: https://discord.com/api/oauth2/applications/695762783626854451/assets

Still investigating

**Comment by CDAGaming** [comment] 2023-06-14 22:21
Under confirmation, the Client ID GTNH was using appears to no longer be present.
Appropriate parties now in contact.

**Comment by chochem** [comment] 2023-07-20 15:37
fixed by https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/13720

**Comment by chochem** [comment] 2023-07-21 00:33
there are still assets missing so I guess this should stay open after all

**Comment by boubou19** [comment] 2023-07-31 20:29
for those who want to fix craftpresence's integration, you need to use the latest version of the craftpresence config from the modpack repo: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/config/craftpresence.json and you might as well want to update craftpresence to latest 1.7.10 version.

**Closed by boubou19** 2023-07-31 20:29 UTC
Labels: Type: bugMinor, Status: Triage, Mod: Craft Presence
