### ISSUE TITLE
Ore Chunk Crash - Exception getting block type in world

### ISSUE THREAD

**Issue by TypicalUnknown** [GTNewHorizons/GT-New-Horizons-Modpack#16620] opened 2024-06-29 07:51 UTC
### Your Pack Version

2.6.1

### Your Server

private server

### Java Version

Other versions in between

### Type of Server

Vanilla Forge

### Your Actions

Initial crash was to Naga bug. Updated twilight to version 2.6.12, reconnected and the crashes persisted. The crashes only occur whenever specific ore chunks are loaded. Currently on 2.6.26-pre.

### Crash Report

[crash-2024-06-29_07.18.55-server.txt](https://github.com/user-attachments/files/16039234/crash-2024-06-29_07.18.55-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2024-06-30 10:43
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16531

**Closed by chochem** 2024-06-30 10:43 UTC
Labels: Type: Crash, Status: Triage
