### ISSUE TITLE
Crush: Chunk build failed

### ISSUE THREAD

**Issue by SharkoTaras** [GTNewHorizons/GT-New-Horizons-Modpack#16155] opened 2024-05-04 12:07 UTC
### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Actions

Crashing at random moment

### Crash Report

[crash-2024-05-04_15.03.16-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15209613/crash-2024-05-04_15.03.16-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment] 2024-05-04 12:58
Duplicate of #16075

**Closed by Glease** 2024-05-04 12:58 UTC
Labels: Type: Crash, Status: Triage
