### ISSUE TITLE
Pyrolyse Oven not forming 2.1.1.1a

### ISSUE THREAD

**Issue by Zodiack256b** [GTNewHorizons/GT-New-Horizons-Modpack#8373] opened 2021-08-08 05:01 UTC
#### Which modpack version are you using?
2.1.1.1a
#
#### If in multiplayer; On which server does this happen? 
private/single player
#
#### What did you try to do, and what did you expect to happen?
Noticed pyrolyse ovens in personal server were not formed after update to dev versions. Built Pyrolyse in single and found it also would not form in single player as well.
#
#### What happened instead? (Attach screenshots if needed)
Multiblock would not form
#
#### What do you suggest instead/what changes do you propose?

#
#### What is your GTNH Discord username?
ZodiacK256B
![2021-08-08_00 00 44](https://user-images.githubusercontent.com/16424443/128621380-1bb7a7a4-99e4-4568-8042-dd2343666663.png)
![2021-08-08_00 00 58](https://user-images.githubusercontent.com/16424443/128621381-7f97de6d-e3af-43dc-a22b-92e584aa7803.png)
![2021-08-08_00 00 29](https://user-images.githubusercontent.com/16424443/128621382-bcc68714-bfc4-482d-bf1c-f237c1f51a40.png)
![2021-08-08_00 00 33](https://user-images.githubusercontent.com/16424443/128621383-e94f58a0-7a58-45d2-b59e-10f87d53d62f.png)
![2021-08-08_00 00 36](https://user-images.githubusercontent.com/16424443/128621384-083f07a7-b4ae-44e5-a509-559d4d640d2b.png)
![2021-08-08_00 00 40](https://user-images.githubusercontent.com/16424443/128621385-01a1b1cd-eeed-44e2-8669-a0190973857b.png)

**Comment by Zodiack256b** [comment] 2021-08-08 05:02
Input hatch/bus and muffler on top.

output hatch/bus, energy hatch, maintenance hatch, and controller on bottom.

Nichrome coils bottom center.

**Comment by Glease** [comment] 2021-08-08 05:06
Duplicate of #8319. See linked issue for a fix or wait for next dev release (we might have one this weekend)

**Closed by Glease** 2021-08-08 05:06 UTC
