### ISSUE TITLE
Duplicate recipe for wheat macerating

### ISSUE THREAD

**Issue by Glease** [GTNewHorizons/GT-New-Horizons-Modpack#8665] opened 2021-10-11 11:11 UTC
### Your GTNH Discord Username

glee8e#7174

### Your Pack Version

2.1.1.2

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Expectation

Macerate wheat for flour

### The Reality

There are two macerating recipe for flour

![scrn](https://user-images.githubusercontent.com/4586901/136780466-4df1b93f-e064-4546-a296-ab8222e811e8.png)

Only the first 20 second recipe is ever run though.

### Your Proposal

Remove one of them.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment] 2021-10-11 13:59
Could one of those be related to the windmill perchance?

**Comment by Prometheus0000** [comment] 2021-10-11 15:11
Ironically, this issue is also a duplicate of #6922.

**Closed by Prometheus0000** 2021-10-11 15:11 UTC
Labels: Type: recipe change, Type: bugMinor
