### ISSUE TITLE
Flickering of Insulates Redstone Conduit and Edges of Naquadria-Reinforced Water Plant Casing

### ISSUE THREAD

**Issue by Yoshy2002** [GTNewHorizons/GT-New-Horizons-Modpack#17892] opened 2024-11-07 19:33 UTC
### Your GTNH Discord Username

yoshy1952

### Your Pack Version

Nightly 719

### Your Server

private Server

### Java Version

Java 17

### Type of Server

None

### Your Expectation

No Flickering between Blocks and no Flickering of Insulated Redstone Conduit.

### The Reality

- If 2 Naquadria-Reinforced Water Plant Casings are placed next to each other, the Edge between them has white Dots in it. If you start moving your camera, these White Dots start Flickering.
- White Part of Insulated Redstone Conduits is not Rendering Correct, if you start moving your camera, these start to Flicker aswell.

https://github.com/user-attachments/assets/e27ee040-b6e4-4077-9d6d-3433c300eb4e

### Your Proposal

Fix the white Dots inbetween the Blocks an the wrong Rendering of Insulated Redstone Conduits

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Yamnasm** [comment] 2024-11-08 12:56
### Naquadria-Reinforced Water Plant Casings edge dots:
Reproduced on Nightly build 728.

White dots around blocks are not unique to Naquadria-Reinforced Water Plant Casings. They appear on every block that is dark enough to physically see the white dots:
_Basalt Bricks:_
![javaw_W9eYNd7zDc](https://github.com/user-attachments/assets/c23f1d8a-885f-45d3-84a0-881dd45f3105)

I couldn't find a video setting that removed these dots, but they are extremely small (I had to use 30-FOV to get decent footage of the visual artifact).

### Insulated Redstone Conduits flickering:
Duplicate of #15851

**Closed by Yamnasm** 2024-11-08 12:56 UTC
Labels: Bug: Minor, Type: Visual, Mod: Ender IO
