### ISSUE TITLE
Twilight forest crash

### ISSUE THREAD

**Issue by leonidas1283** [GTNewHorizons/GT-New-Horizons-Modpack#16862] opened 2024-07-28 20:14 UTC
### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Minecraft curseforge
what i do is get to close to the naga maze and half is loaded but crashes if i get any closer
i did this 3-4 times dont know the reason
regular single player same thing and LAN

![Screenshot 2024-07-28 160846](https://github.com/user-attachments/assets/7aa08b03-b39a-419d-8f2e-c52798efa7ae)

### Crash Report

https://mclo.gs/z0D5eaX
https://mclo.gs/uRqtonB

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by leonidas1283** [comment] 2024-07-28 20:16
this to i think
https://mclo.gs/h6r5YpW

**Comment by FourIsTheNumber** [comment] 2024-07-28 20:23
Update twilight forest: https://github.com/GTNewHorizons/twilightforest/releases/tag/2.6.12

**Comment by Lyfts** [comment] 2024-07-28 20:25
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16353 and a gazillion others.

**Comment by leonidas1283** [comment] 2024-07-28 20:26
how do i do that on curseforge?

**Closed by Lyfts** 2024-07-28 20:25 UTC
Labels: Type: Crash, Status: Triage
