### ISSUE TITLE
Cannot use Goldfish in Arcane Infusion recipes

### ISSUE THREAD

**Issue by slyk26** [GTNewHorizons/GT-New-Horizons-Modpack#15257] opened 2024-01-01 09:50 UTC
### Your GTNH Discord Username

slyk26

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/102811034/dd7ecf9e-6585-483e-b6c7-59115e82ec2d)

I want to use the goldfish in this recipe. i want to rightclick with it on a pedestal so it is placed as a ingredient.

### The Reality

you can't use the goldish on pedestals, you cant even rightlick a door to open it, while having the goldfish in your hand, or interact with anything... lol

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/102811034/6a970886-3a99-461a-a37e-7a54820c9a20

### Your Proposal

either remove the goldfish from the recipe, or make the goldfish placeable on that pedestal

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2024-01-01 09:58
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12938
see explanation there.

**Comment by bombcar** [comment] 2024-01-02 18:19
how I accidentally open lol

**Closed** 2024-01-02 18:20 UTC
Labels: Type: Duplicate, Type: bugMinor, Status: Triage

**Comment by desagas** [comment] 2024-01-25 17:15
This is not at all related to what Chochem suggested. His answer was quick and with zero testing, again, but. what else is new ... ugh .... while it may not work in the recipe, you can in fact deposit the fish on the pedestal with a hopper. Goldfish in the main hand prevents ALL player interactions with everything else in the world, period. With goldfish in your main hand, you can not put them into barrels, into drawers, you can not open doors, trap doors, you can not click on machines, you can not click on pedestals, runic altars, you can not interact with villagers, with witchery mods, etc etc etc. This is a bug in the mod with Goldfish.

**Comment by chochem** [comment] 2024-01-25 19:55
> This is not at all related to what Chochem suggested. His answer was quick and with zero testing, again, but. what else is new ... ugh .... while it may not work in the recipe, you can in fact deposit the fish on the pedestal with a hopper. Goldfish in the main hand prevents ALL player interactions with everything else in the world, period. With goldfish in your main hand, you can not put them into barrels, into drawers, you can not open doors, trap doors, you can not click on machines, you can not click on pedestals, runic altars, you can not interact with villagers, with witchery mods, etc etc etc. This is a bug in the mod with Goldfish.

dont make up lies about me. I tested it and its also confirmed by many other people. its literally the exact same as the other ticket. its also not limited to the Goldfish.

I guess if you were nicer what you are really trying to say is that there are further additional bugs. I would suggest you make a separate ticket for any such separate bugs. And yes I see slyk26 also has a side note like that, I guess they assumed it was connected. it is not.

**Comment by chochem** [comment] 2024-01-25 20:03
though as I understand the scream is a feature and not a bug.

**Comment by bombcar** [comment] 2024-01-25 21:58
> though as I understand the scream is a feature and not a bug.

A disableable feature. Where it is disabled is a bit of a journey to find.

**Comment by desagas** [comment] 2024-01-26 07:05
I love the scream. It’s fits the “hellish planimal” tag. Hahah. Although, when you walk through a field of them, that leaves something left to the yearning.
