### ISSUE TITLE
Loading new Twilight Forest chunk causes game to break

### ISSUE THREAD

**Issue by RoManInv** [GTNewHorizons/GT-New-Horizons-Modpack#17676] opened 2024-10-19 00:02 UTC
### Your GTNH Discord Username

RoMan

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Action 1
1. Explore Twilight Forest (TF) and get to a specific point
2. Game crashes

### Action 2: Reproduction
1. Explore TF and take a detour
2. Approach the direction in which the crash happened
3. Game crashes
4. Repeat the above-mentioned three steps and approach that direction from different points, game crashes. The points every time the game crashes seem to draw a circle (arc-shape).

### Action 3: Reproduction by restoring save
1. Restore the earliest possible save
2. Get to the point in TF where game crashed
3. Game crashes

### Action 4: Reproduction by new world
1. Create a new world with the same seed
2. Create a portal to TF at the same coordinate
3. Get to the point in TF where the game crashed
4. Game crashes

I think loading a specific new, unexplored (TF) chunk causes the game to crash. 
1. This crash happens multiple times, but every time it happens, the character is at or near similar location in the World TF. 
6. After this crash happens, restoring the previous or the second previous save can still run the game, but every time the character approaches that location in the World TF, the game crashes
7. After this crash happens, and the save is restored, the game can crash at the location that is already loaded and didn't cause any problem before. E.g. after restoring the save, I went back to the main world (MW) by taking the portal from TF to MW. After few walking in the surrounding, explored area, the game crashes

Additionally, the crash report seems to be different every time.

### Crash Report

[Last crash report](https://mclo.gs/cah88oL)

[Latest game log](https://github.com/user-attachments/files/17441673/fml-client-latest.log)

[Previous crash report with different description in TF](https://github.com/user-attachments/files/17441679/crash-2024-10-18_18.06.53-server.txt)

[Crash report at MW after the crash happens](https://github.com/user-attachments/files/17441681/crash-2024-10-18_18.12.58-server.txt)

[Crash report with description that is never seen in the previous crash reports](https://github.com/user-attachments/files/17441682/crash-2024-10-19_00.23.14-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by FourIsTheNumber** [comment] 2024-10-19 00:31
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16353 and approximately five billion others.
Update twilight forest mod here https://github.com/GTNewHorizons/twilightforest/releases/download/2.6.12/TwilightForest-2.6.12.jar

**Closed** 2024-10-19 00:34 UTC
Labels: Type: Crash, Status: Triage
