### ISSUE TITLE
"illegal ore" CTD'ing server across versions

### ISSUE THREAD

**Issue by xTwi** [GTNewHorizons/GT-New-Horizons-Modpack#17128] opened 2024-08-27 13:25 UTC
### Your GTNH Discord Username

neotwilight.

### Your Pack Version

2.7.0 Nightly 2024-08-27

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

None

### Your Actions

Generating new chunks in overworld with flight methods, suddenly booted back to menu. Server has CTD'd.
Attempt to log into world, instantly booted out and server CTD's again.

This persists between 606 and 612 nightly versions.

### Crash Report

https://mclo.gs/P3XRFYY

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Pxx500** [comment] 2024-08-27 15:30
For now there is nothing that can be done to prevent the bug, it's new and as of now there is no known fix except deleting affected blocks.
For that you need a new hodgepodge, regenerate config (or just add needed lines which are in the link). The block deletion is turned off by default to show player that something is broken, to enable it do as instructed here: https://discord.com/channels/181078474394566657/1211702130092539965/1254843421651107903

**Comment by Pxx500** [comment] 2024-08-27 15:36
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16728

**Closed by Pxx500** 2024-08-27 15:36 UTC
Labels: Type: Crash, Status: Triage

**Comment by xTwi** [comment] 2024-08-27 19:24
Thank you for your response and listing how to fix it, much appreciated.
