### ISSUE TITLE
8196 EU/t battery displaying EV-tier in description.

### ISSUE THREAD

**Issue by Gateswong** [GTNewHorizons/GT-New-Horizons-Modpack#10330] opened 2022-05-13 10:11 UTC
### Your GTNH Discord Username

Gates_ice#4537

### Your Pack Version

2.1.2.3qf

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

N/a

### The Reality

![image](https://user-images.githubusercontent.com/2586057/168262620-fe770dce-2631-437e-8644-a353c836557c.png)

### Your Proposal

Should be IV-tier?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment] 2022-05-13 10:41
Duplicate of #10140

**Closed by miozune** 2022-05-13 10:41 UTC
Labels: Type: bugMinor, Status: Triage
