### ISSUE TITLE
Crash caused by mining with hammer

### ISSUE THREAD

**Issue by Mobius0526** [GTNewHorizons/GT-New-Horizons-Modpack#12600] opened 2023-02-15 03:03 UTC
### Your GTNH Discord Username

Mobius

### Your Pack Version

2.2.9 lwjgl3.3.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Mining with hammer

### The Reality

Mining with hammer may cause crash
You cannot enter the archive again after returning to the main menu
Must restart
[crash-2023-02-15_10.57.35-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10738882/crash-2023-02-15_10.57.35-server.txt)

### Your Proposal

Fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment] 2023-02-15 03:13
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12567

**Closed by Glease** 2023-02-15 03:13 UTC
Labels: Type: bugMinor, Status: Triage
