### ISSUE TITLE
No Recipe for Calcium Ingots from Dust

### ISSUE THREAD

**Issue by Aggadahr** [GTNewHorizons/GT-New-Horizons-Modpack#8034] opened 2021-06-10 13:58 UTC
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Epsilon
#
#### What did you try to do, and what did you expect to happen?
Tried crafting Calcium Ingots, but there is no working recipe in the EBF, Furnace or Alloy Smelter (with Ingot shape)
There is a shown possibility in NEI in the Infernal Furnace from Thaumcraft, but srsly, that cant be the only intended way
EDIT: I built the infernal furnace and tried smelting calcium that way, doesnt work either.
#
#### What is your GTNH Discord username?
Shadii

**Comment by Skiftcha** [comment] 2021-06-10 14:05
fusion -> calcium plasma -> plasma turbine -> liquid calcium for another fusion

**Comment by Aggadahr** [comment] 2021-06-10 14:14
oh yeah sure, because the smelting point for calcium is 842°C, we cant possible reach that heat by burning friggin wood (sarcasm)
Our only Chance is creating it from other elements via Fusion or relying on magic, that makes sense

**Comment by Glease** [comment] 2021-06-10 15:07
Duplicate of #6274

**Closed by Glease** 2021-06-10 15:07 UTC
