### ISSUE TITLE
High server CPU usage by removeAll() method on net.minecraft.world.World.func_72939_s ()

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12148] opened 2022-12-30 20:15 UTC
### Your Pack Version

2.2.3

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

Although i would like to provide more information it's unclear to me as to where this comes from, but it occasionally pops up, heavily disrupting performance continuously until a restart.
![image](https://user-images.githubusercontent.com/39203645/210108712-f0097259-8ced-40ea-b7ff-4a81a1b4a938.png)

[Snapshots.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10326155/Snapshots.zip)

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by mitchej123** [comment] 2022-12-30 20:17
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9147

Fixed by https://github.com/GTNewHorizons/Hodgepodge/pull/133 (or adding fastcraft)

**Closed by mitchej123** 2022-12-30 20:17 UTC
Labels: Type: bugMinor, Status: Triage
