### ISSUE TITLE
Search for item in Storage Drawer no longer finds item

### ISSUE THREAD

**Issue by nmachen** [GTNewHorizons/GT-New-Horizons-Modpack#11757] opened 2022-10-29 01:54 UTC
### Your GTNH Discord Username

namc#8627

### Your Pack Version

2.2.0.0

### Your Server

private server

### Your Expectation

- Put item in storage drawer
- Press T on same item in inventory or NEI

Expected puff of smoke on storage drawer. This worked in 2.1.2.3qf but no longer works in 2.2.0.0. 

### The Reality

No puff of smoke. Nothing happens

### Your Proposal

Bug fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment] 2022-10-29 10:56
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11504

**Closed by miozune** 2022-10-29 10:56 UTC
Labels: Type: bugMinor, Status: Triage
