### ISSUE TITLE
Electric Air Filter Wonkiness

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#7997] opened 2021-06-01 21:44 UTC
Occurred on official Zeta server, pack version 2.1.0.7a.
![2021-05-31_23 55 39](https://user-images.githubusercontent.com/41557212/120393878-86384280-c2e7-11eb-9dc5-fc5a34d3ca68.png)

~~For whatever godforsaken reason, going above a certain Y level will cause the machine to never properly form. Likely the ancient code within this multiblock that, for whatever reason, is requiring a Y level and thus was never properly addressed or reported. ~~

Edit: Just reformed the multiblock on Zeta and found out that if there exists approximately five air blocks above the multiblock. However, the Multiblock doesn't ever state in the tooltip that there needs to exist air blocks above it in order to form (this might also bug out if there exists Thaumcraft lighting).

In this case, the Electric Air Filter needs more info attached to the tooltip and needs to properly state what materials is acceptable within the multiblock input.

**Comment by ScriptedPiky** [comment] 2021-06-01 23:09
**Additional Notes**
- Air Filter doesn't properly consume pollution a second and instead consumes pollution every ten (10) seconds or however long the processing time of the multiblock takes.
- Air Filter consumes negative EU and thus does not require an energy source attached to run it
- Turbine size or material type does not matter for the extra pollution consumption bonus if inserted into the controller
- Air Filter should output liquid pollution proportionate to how much pollution was absorbed at a 100:1 ratio (every 100 pollution equals 1); `dreamcraft_pollution`

**Comment by Prometheus0000** [comment] 2021-06-01 23:16
Are these things that need fixing, or more things to add to/change on the tooltip? You should state the _exact_ changes that you want.

**Comment by ScriptedPiky** [comment] 2021-06-01 23:54
I probably should've specified prior.

**Code Changes or Investigation Required:**
- Air Filter doesn't properly consume pollution a second and instead consumes pollution every ten (10) seconds or however long the processing time of the multiblock takes.
- Air Filter consumes negative EU and thus does not require an energy source attached to run it
- Turbine size or material type does not matter for the extra pollution consumption bonus if inserted into the controller (Unsure if intended?)
- Air Filter should output liquid pollution proportionate to how much pollution was absorbed at a 100:1 ratio (every 100 pollution equals 1); `dreamcraft_pollution`

**Tooltip Changes Required:**
- Remove or update `Add Air Filter in input for efficiency` line, as it does not specify the exact item it refers to; only matching name is the GT++ (not Dreamcraft or regular GT) instead of the legacy/uncraftable 'Adsorption filter casing'; `dreamcraft:item.AdsorptionFilterCasing`. Presumably, this extra line or item inside the machine does nothing and is not required for the multiblock to function

**Comment by Glease** [comment] 2021-06-02 09:02
> Air Filter doesn't properly consume pollution a second and instead consumes pollution every ten (10) seconds or however long the processing time of the multiblock takes.

Working as intentioned. not a bug.

> Negative EU
> turbine problem
sounds like a bug will look into it
> pollution output
make sense
> air filter
There is this `dreamcraft:item.AdsorptionFilter`. It is not disabled.

**Comment by Elisis** [comment] 2021-06-03 08:08
> * Air Filter consumes negative EU

This is a bug with it reporting EU usage, not actually usage from what I can tell.

**Comment by Glease** [comment] 2021-06-03 14:37
> negative EU

Pure display issue. It consumes the power just fine. If you run it without any pollution it will only consume 1A LV, which, at high power tier, could effectively be considered not draining any power.

Will be fixed by GTNewHorizons/NewHorizonsCoreMod#190.

> turbine problem

can't reproduce. you need to wait 10 seconds to see the effect of your changes.

> pollution output
> air filter

do you mean you want the filter consumption rate to go up porpotional to how fast it clean pollution? The current air filter doesn't output pollution fluid directly. You acquire it via dirty absorption filter.

**Closed** 2021-06-22 17:31 UTC
Labels: Status: FixedInDev, Type: Info, Type: help wanted
