### ISSUE TITLE
Visual texture glitches in the menus

### ISSUE THREAD

**Issue by DryHump** [GTNewHorizons/GT-New-Horizons-Modpack#15488] opened 2024-02-06 14:31 UTC
### Your GTNH Discord Username

Bonce

### Your Pack Version

2.5.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Attempted to change resource packs expecting to see a regular resource pack menu screen

### The Reality

The RP menu screen was covered by a large smushed texture resembling the background I was using
![image_2024-02-06_152536095](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/159155378/7ab0f278-827f-4111-b2ff-64775d249474)

The same issue occurred in some other menu tabs as well including the SP world select screen
![image_2024-02-06_152616930](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/159155378/69fe18d4-920f-4851-80ab-04d6373793c9)
![image_2024-02-06_152643334](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/159155378/1b4e6972-b42a-410f-8548-48215ebd5f82)
![image_2024-02-06_152935745](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/159155378/d8646126-8e65-48bd-ae0d-7de106917465)

### Your Proposal

Removal of the smushed textures which I assume are a byproduct of Angelica 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by rlqd** [comment] 2024-04-30 08:36
I can confirm, this also reproduces for me in 2.6.0
![Screenshot 2024-04-30 093525](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/83128595/acb6942b-667a-44cb-97e2-722a8f29d1cd)

**Comment by chochem** [comment] 2024-04-30 08:37
duplicate of https://github.com/GTNewHorizons/Angelica/issues/185

**Closed by chochem** 2024-04-30 08:37 UTC
Labels: Type: bugMinor, Status: Triage
