### ISSUE TITLE
Ticking Screen Crash on load in to server

### ISSUE THREAD

**Issue by TenchiRyokoMuyo** [GTNewHorizons/GT-New-Horizons-Modpack#10270] opened 2022-05-04 20:28 UTC
### Your GTNH Discord Username

TenchiRyokoMuyo#1721

### Your Pack Version

2.1.2.3

### Your Server

51.161.57.5:25566

### Type of Server

Don't know

### Your Actions

I upgraded my server from 2.1.2.0 to 2.1.2.3. I used the serverpack's located on website. I used the packs from MultiMC on website. I am running the pack through curseforge however.

I am having issues with MultiMC that are separate potentially to this, but for means of giving full info, I'll detail those issues as well. When I try to load the pack by importing it into MultIMC, console looks fine. No crashes, but the window refuses to focus, and when I view the window in alt-tab, it shows just a blank white screen. When I let it run, eventually the music from the main menu starts playing, as if the pack has loaded successfully. As a work around I took the pack instance from MultiMC, and loaded in to GTNH on curseforge. This works fine, and singleplayer runs fine.

When I try to log in on server, Server kicks immediately out. Join message in game shows, then immediately shows log out. About 25% of the time, my client crashes to Desktop. Other times, it shows a generic java exception error. 

Any assistance would be appreciated, whether with the white screen on MultiMC, or fixing this ticking screen issue. It seems other users in the discord may have had a similar issue with this Ticking Screen on login issue. 

### Crash Report

Server log on kick : https://pastebin.com/WG7ujXHB
Client Log on Crash : https://pastebin.com/jLZ40iec
Java Client Crash : https://gyazo.com/1ebca8fdcdadd2cba92ff507ea6b9fc6

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by TenchiRyokoMuyo** [comment] 2022-05-04 20:34
@kubasz on Discord posted these images, believing it to be the root of the issue. 

https://cdn.discordapp.com/attachments/234936569360809996/971474381366775898/unknown.png

https://cdn.discordapp.com/attachments/234936569360809996/971475190808711259/unknown.png

**Comment by Glease** [comment] 2022-05-04 21:33
Looks similar to #10207.

**Comment by Glease** [comment] 2022-05-04 21:39
Judging from the exception message (both attempting to write 155516 bytes into the buffer) this should be a duplicate of #10207

**Closed by Glease** 2022-05-04 21:39 UTC
Labels: Type: Crash, Status: Triage
