### ISSUE TITLE
Adjust 'Pain/Agony' enchantment from SpecialMobs

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#4775] opened 2019-06-24 20:52 UTC
Currently, the Pain/Agony enchantment deals an incredible amount of void damage, nearly killing the player by void damage alone. When tested with 25 hearts, a single Agony Bow is capable of dealing around 75% of my health. The same thing can be said if you have 10 hearts and get sent down to 2.5 hearts (assuming the arrow itself doesn't deal damage and that the enchantment only deals damage).

What I suggest is adjusting the Pain/Agony to make it more balanced and less "Wow, I literally got 1-shot through full diamond/Thaumium Fortress armor by a Brutish Zombie", allowing for more counter-play and fair & balanced gameplay for the player.

Adjust Pain to deal 15%, 30%, 45% of the entities **current hp**.
Adjust Agony to deal 7.5%, 15%, 30% of the entities **current hp**.

Should an item ever receive an enchantment level beyond three or higher (I.E. Pain IV on a Wooden Sword), it will instead cap the %currentHP damage to the highest variable of the specific enchantment (45% for Pain, 30% for Agony).

This makes it so that fighting any Brutish enemy with a pain/agony will offer some counter-ability for the player instead of out-right dying in full protection armor while still making these kinds of enemies extremely dangerous in nearly all stages of the game in a fair & relatively balanced style.

**Comment by richardhendricks** [comment] 2019-06-24 21:06
Aren't these mods coming from TC?  Not sure how much we can do there.

**Comment by ScriptedPiky** [comment] 2019-06-24 21:07
They're from SpecialMobs. The Pain/Agony that is. The 'Champion' kind of thing is from TC and that I'm not sure if we can really touch.

**Comment by richardhendricks** [comment] 2019-06-24 21:08
OKay, we can take a look at it.

**Comment by Dream-Master** [comment] 2019-06-25 09:41
we forked the source allready. The config file not have any entry to change it. Need to do it codewise.

**Comment by Methes** [comment] 2019-12-08 15:56
It still doesn't work as intended.

I believe the relevant piece of code is this:
DamageSource g = (new DamageSource("pain")).setDamageBypassesArmor();
                event.entityLiving.attackEntityFrom(g, event.entityLiving.getHealth() - pain)

However, there are various scenarios showing how much it's broken. Tested with same Brutish Zombie that had certain Pain sword (enchantment level not relevant):
Brutish Zombie attacking player with 10 hearts and
- Fortress Armor - instantly removing from 0,5 to 3 hearts each hit up to 6,5 total player health and then doing 0 or 0,5 hearts damage each consecutive hit
- Quantum Armor - instantly removing 3,5 hearts setting player health to 6,5 and then doing 0 hearts damage each hit.

Important scenario - Player has 20 hearts:
- Fortress Armor - deals ~5 hearts of damage until the player has 6,5 hearts, then same as above.
- Quantum Armor - sets player health to 6,5 hearts instantly then same as above.

Conclusion: Pain tries to get the player to 6,5 total health. Fortress Armor weakens this effect slightly but then doesn't protect 100% against normal damage. Quantum Armor has zero protection against Pain but then protects 100% against normal damage. This makes it brutally OP as the player can have excellent protection yet single blow can deal up to 33,5 hearts of damage while taking him instantly from 40 hearts to 6,5.


When player attacks a mob with Pain enchanted weapon it's even more broken. A Wooden Sword with Pain I takes the Wither from 330 health to 1 in single blow. Does the same to almost every other mob I've tried - single blow gets them to 1-5 hearts and second blow kills them.
Interestingly a Zephyr sword with Sharpness V, Wrath V and Pain III does LESS damage than wooden sword Pain I. I can't conclude any math out of that.

Please either somehow fix this (and rebalance, it's just stupid there's no protection against this) or better yet disable the enchantment in configs.

**Comment by draknyte1** [comment] 2019-12-08 16:04
As the person who wrote that exact piece of code, that’s how it should work. Previously it did entity.setHealth().

The number passed in named ‘pain’ may not be correct, but that’s original SM code.

**Comment by Methes** [comment] 2019-12-08 16:07
Yes it should deal 0,5-1,5 of damage based on enchant level. But for some reason it doesn't.
'pain' is defined here:

ItemStack heldItem = ((EntityLivingBase)attacker).getHeldItem();
                // Pain
                if (heldItem != null && EnchantmentSpecial.painSword != null) {
                    pain = EnchantmentHelper.getEnchantmentLevel(EnchantmentSpecial.painSword.effectId, heldItem);
                }
                else {
                    pain = 0;

**Comment by richardhendricks** [comment] 2020-01-26 06:05
It really seems like the original implementation wasn't well thought out. 
The original SM code looks completely backwards, in that it applies *less* damage based on higher pain levels.  Also, since the damage is subtracted from the entity health, that's why it "stops" at 1.5, because 1.5 health - the pain level is probably 0 or negative.

  I think instead we will give the Pain enchant a suitably high direct damage, like 4 per enchantment level. Max level of 3 = 12 damage per hit, or 6 hearts. If the player has less than the base direct damage health left (2 hearts), then the enchantment will do zero damage.

This way it bypasses armor, but doesn't directly set your health really really low.

**Comment by Methes** [comment] 2020-01-26 08:44
Just to summarize, what can the player do to protect against this?
More health
Runic Shielding
Infinity armor
Anything else? Would be nice to be able to get some sort of protection.

**Comment by ScriptedPiky** [comment] 2020-01-26 08:57
One way that we could *technically* balance this is make the Pain/Agony deal **magic** damage, or otherwise known as "potion damage." This way, certain armors like the Thaumcraft/Void Fortress, the Nano(?), the Quantum, and much more armor's can protect against this kind of damage instead of the enchantment dealing void damage. In addition, instead of void/setting health or any kind of that buggy mess, we could make the enchantments deal just increased magic/potion damage based on enchantment level. That way, it theoretically bypasses regular armor, but not more advanced armor, giving players a fair resistance and advantage that doesn't use void damage levels of power.

**Comment by Methes** [comment] 2020-01-26 09:14
It would be a nice balance of the two main armor paths.
Nano/Quantum protecting 100% against regular damage and offering Hazmat Suite protection at the same time, no need to repair, just recharge.
Fortress armor providing ~85% protection against regular damage + magical damage, needs to be repaired.
I'm not yet familiar with the advanced magical armors like Void Fortress, Kami armor etc.

**Comment by richardhendricks** [comment] 2020-01-26 16:20
Ok, what I did is make Pain set your hurtResistantTime to 1/4, and the pain damage is base 1.5 hearts per enchantment level. The damage bypasses armor, but for some weird reason even in vanilla, setting that doesn't allow the damage to pass through, so I set it to absolute as well. We can tweak as needed.
I haven't tested with all the various mod armors yet.

**Comment by Dream-Master** [comment] 2020-05-28 06:10
i guess this must be fixed with the update.

**Closed** 2020-06-07 18:53 UTC
Labels: FixedInDev, bugMajor, need to be tested
