### ISSUE TITLE
Stocking Input Hatch

### ISSUE THREAD

**Issue by AltyMan** [GTNewHorizons/GT-New-Horizons-Modpack#13828] opened 2023-06-28 18:49 UTC
### Your GTNH Discord Username

alty2x

### Your Pack Version

2.3.0

### Your Proposal

Add a stocking input hatch, pretty self explanatory but just to explain it acts like the stocking input bus but for liquids, with the purpose of pulling liquids from an ME system directly without the need of an export bus with/without accelerators. Also I was told a ticket won’t hurt even though this feature is well requested

### Your Goal

Have a solution for liquids like there is items

### Your Vision

It will improve QOL when making processing lines

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by minecraft7771** [comment] 2023-06-28 18:50
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12269

**Closed by minecraft7771** 2023-06-28 18:50 UTC
Labels: Type: Suggestion, Status: Triage
