### ISSUE TITLE
Division by Zero in a newly formed supercapacitor

### ISSUE THREAD

**Issue by PhoenixtheII** [GTNewHorizons/GT-New-Horizons-Modpack#11905] opened 2022-12-01 16:37 UTC
### Your Pack Version

2.2.3

### Your Server

My own

### Your Actions

Form a new IV tier 3 Lapatronic supercapacitor.

Go 2 chunks further make a 2x3 information display panel

Gregtech Sensor Kit the supercapactor
Insert the card into display panel
Insert a range upgrade into display panel too

....

Crash!

:25:51] [Server thread/INFO]: Done (10.332s)! For help, type "help" or "?"
[17:26:04] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3973ms behind, skipping 79 tick(s)
[17:26:05] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.ArithmeticException: / by zero
	at common.tileentities.GTMTE_LapotronicSuperCapacitor.getAvgIn(GTMTE_LapotronicSuperCapacitor.java:674) ~[GTMTE_LapotronicSuperCapacitor.class:?]
	at common.tileentities.GTMTE_LapotronicSuperCapacitor.getInfoData(GTMTE_LapotronicSuperCapacitor.java:697) ~[GTMTE_LapotronicSuperCapacitor.class:?]
	at gregtech.api.metatileentity.BaseMetaTileEntity.getInfoData(BaseMetaTileEntity.java:2241) ~[BaseMetaTileEntity.class:?]
	at gregtech.common.items.GT_SensorCard_Item.update(GT_SensorCard_Item.java:59) ~[GT_SensorCard_Item.class:?]
	at gregtech.common.items.GT_SensorCard_Item.update(GT_SensorCard_Item.java:49) ~[GT_SensorCard_Item.class:?]
	at shedar.mods.ic2.nuclearcontrol.tileentities.TileEntityInfoPanel.processCard(TileEntityInfoPanel.java:754) ~[TileEntityInfoPanel.class:?]
	at shedar.mods.ic2.nuclearcontrol.tileentities.TileEntityInfoPanel.func_70296_d(TileEntityInfoPanel.java:779) ~[TileEntityInfoPanel.class:?]
	at shedar.mods.ic2.nuclearcontrol.tileentities.TileEntityInfoPanel.func_145845_h(TileEntityInfoPanel.java:410) ~[TileEntityInfoPanel.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1145) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
	... 4 more

### Crash Report

:25:51] [Server thread/INFO]: Done (10.332s)! For help, type "help" or "?"
[17:26:04] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 3973ms behind, skipping 79 tick(s)
[17:26:05] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.ArithmeticException: / by zero
	at common.tileentities.GTMTE_LapotronicSuperCapacitor.getAvgIn(GTMTE_LapotronicSuperCapacitor.java:674) ~[GTMTE_LapotronicSuperCapacitor.class:?]
	at common.tileentities.GTMTE_LapotronicSuperCapacitor.getInfoData(GTMTE_LapotronicSuperCapacitor.java:697) ~[GTMTE_LapotronicSuperCapacitor.class:?]
	at gregtech.api.metatileentity.BaseMetaTileEntity.getInfoData(BaseMetaTileEntity.java:2241) ~[BaseMetaTileEntity.class:?]
	at gregtech.common.items.GT_SensorCard_Item.update(GT_SensorCard_Item.java:59) ~[GT_SensorCard_Item.class:?]
	at gregtech.common.items.GT_SensorCard_Item.update(GT_SensorCard_Item.java:49) ~[GT_SensorCard_Item.class:?]
	at shedar.mods.ic2.nuclearcontrol.tileentities.TileEntityInfoPanel.processCard(TileEntityInfoPanel.java:754) ~[TileEntityInfoPanel.class:?]
	at shedar.mods.ic2.nuclearcontrol.tileentities.TileEntityInfoPanel.func_70296_d(TileEntityInfoPanel.java:779) ~[TileEntityInfoPanel.class:?]
	at shedar.mods.ic2.nuclearcontrol.tileentities.TileEntityInfoPanel.func_145845_h(TileEntityInfoPanel.java:410) ~[TileEntityInfoPanel.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1145) ~[mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
	... 4 more

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2022-12-01 16:38
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11558

**Closed by chochem** 2022-12-01 16:38 UTC
Labels: Type: Crash, Status: Triage
