### ISSUE TITLE
Pyrolyse oven causing server lag when wood any wood other than vanilla oak is left in the input bus

### ISSUE THREAD

**Issue by Nrin123** [GTNewHorizons/GT-New-Horizons-Modpack#8047] opened 2021-06-13 09:12 UTC
#### Which modpack version are you using?
2.1.0.7a
#
#### If in multiplayer; On which server does this happen? 
http://stonelegion.com
#

Tested using all LV busses, hatches, and muffler. When the machine is powered on and the pyro oven is not processing a recipe it will cause a noticeable drop in the TPS if any wood other than vanilla oak wood is left in the input bus. I admit that I did not test every wood but I tested wood from multiple mods and every single one caused a similar drop in TPS. The woods I tested are:

Minecraft:
Oak Wood 17
Spruce Wood 17:1
Birch Wood 17:2
Jungle Wood 17:3

Biomes O' Plenty:
Sacred Oak Wood 762
Cherry Wood 762:1
Redwood Wood 764

Natura:
Redwood 640:1

IndustrialCraft 2:
Rubber Wood 169

I tested this with other energy hatches such as LV, HV, and EV and they all work to reproduce this bug.
#
#### What is your GTNH Discord username?
Nrin#7237

**Comment by KaneHart** [comment] 2021-06-13 09:14
Here is an example of the server side spam that altered me to the issue to begin with once I noticed the server TPS was dropping like crazy 

`[04:46:51] [Server thread/WARN]: WARNING: Possible Lag Source at [-3493, 56, 4748] in Dimension 0 with 953696135ns caused by an instance of class com.github.bartimaeusnek.crossmod.tectech.tileentites.multi.GT_Replacement.TT_PyrolyseOven`

**Comment by Nrin123** [comment] 2021-06-13 09:38
A bit more info. The pyro oven has all LV busses and hatches, also just leaving the spruce wood in the input bus without any circuit was impacting the server's TPS. It seemed to dorp it by at least two for the entire server simply by having some spruce wood in it. I have not tested it with any other wood.

**Comment by GTNH-Afx237v7** [comment] 2021-06-13 10:19
You can Try screwdriver on input bus to turn input filter off, see what the impact is.

**Comment by Nrin123** [comment] 2021-06-13 11:44
Changing the input filter had no effect. It continued to drop the TPS.

**Comment by boubou19** [comment] 2021-06-13 17:51
when the lag is observed, what the content of gregtech.log?

**Comment by KaneHart** [comment] 2021-06-13 18:00
> when the lag is observed, what's the content of gregtech.log?

Could we get timestamps on that log?

Nrin if you like, you can tell me when you try it again maybe just before so I can prune the log itself.. It does not actually seem to do time stamps.

**Comment by KaneHart** [comment] 2021-06-13 18:01
Here is our full Log since this issue started and since the last reboot before the issue:
https://gist.github.com/KaneHart/114c58fbff9fa44e4f5e172fbb26b9d3

**Comment by Nrin123** [comment] 2021-06-14 05:47
Okay so I did some more tests in a single player world. I replicated the bug with many different types of wood. I tested each type of wood by putting a single stack inside the LV input bus and watching the tps for changes. Every type of wood I tested caused the TPS to drop except for vanilla oak wood. The different woods and their ID I tested are:

Minecraft: 
Oak Wood 17
Spruce Wood 17:1
Birch Wood 17:2
Jungle Wood 17:3

Biomes O' Plenty:
Sacred Oak Wood 762
Cherry Wood 762:1
Redwood Wood 764

Natura:
Redwood 640:1

IndustrialCraft 2:
Rubber Wood 169

**Comment by Nrin123** [comment] 2021-06-14 06:09
More testing:
I tested a recipe of 1 bucket of steam in the LV hatch, as well as 20 wood, and a circuit with the value of 20 in the input bus to see if the problem occurs whilst the machine is running. I tried with LV, HV, and EV voltages and found that the TPS is not affected in any way I can see while the machine is running but as soon as the recipe finishes, if there is any wood other than vanilla oak wood left in the input bus it will cause an immediate drop in the TPS.

I would like to reiterate that the bug only occurs when the machine is powered on but NOT processing a recipe.

**Comment by Sovereignty89** [comment] 2021-06-30 12:32
I can confirm this. Didn't know about this issue till I noticed it myself. Built a Pyrolyse oven, Spruce wood in the Input bus. Machine was Enabled but I forgot to give it a circuit so it wasn't processing anything. The TPS tanked. 

![Pyrolyse Oven1](https://user-images.githubusercontent.com/6663736/123960270-6613a600-d9af-11eb-8048-dc757cdac5de.PNG)
![Pyrolyse Oven2](https://user-images.githubusercontent.com/6663736/123960282-68760000-d9af-11eb-926a-3ac8ffd3fbf4.PNG)

Version 2.1.1.0, SP world

**Comment by boubou19** [comment] 2021-06-30 15:49
i reproduced this on delta, and here is the warmroast report:
![image](https://user-images.githubusercontent.com/12850933/123991992-7e91b980-d9cb-11eb-9bff-48888eda2264.png)

**Comment by Glease** [comment] 2021-06-30 16:23
Anything with such kind of reckless dynamic recipe generation is going to cause equivalent problem. This would require a two step solution. First, you need to reduce the amount of dynamic recipe generation. Then, you need to ensure configuration is not saved more than once per tick/second/minute.

**Comment by KaneHart** [comment] 2021-06-30 16:36
Yeah that sounds right. Maybe the fast fix here is a better sleeping system for now and more work on the recipe system later?

**Comment by KaneHart** [comment] 2021-07-06 19:21
Any updates on this? @Nrin123 did you also have this with another machine? I think someone might of had another machine do the same. This pretty big issues that hopefully can get hotfixed vs wait 6 months.

**Comment by D-Cysteine** [comment] 2021-07-27 02:33
(Sorry, this ended up kind of long. Anyway, **tl;dr** config is getting read during gameplay when it's not supposed to be; reading the config causes it to try to write a huge >9 MB config file, leading to lag; this whole issue is probably just a symptom of messy configs)

I took a look at this, and I think it's reading the configs that's causing the slowness. Step-by-step:

1. The BW replacement pyrolyse oven code tries to add recipes dynamically for the current wood whenever it can't find a valid recipe with the current input:
https://github.com/GTNewHorizons/bartworks/blob/master/src/main/java/com/github/bartimaeusnek/crossmod/tectech/tileentites/multi/GT_Replacement/TT_PyrolyseOven.java#L168-L170
When there is something missing that makes all recipes invalid (e.g. missing circuit), this is going to get run every time the machine checks for a recipe, which is at least once per second I think.

2. The recipe adding code reads the configs. I'm not exactly sure what the purpose of this line is, but my guess would be that it's checking to see if the recipe is disabled by config (by having a value <= 0 set).
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/common/GT_RecipeAdder.java#L1263-L1265

3. The code that reads the config checks to see if the entry that was looked up actually exists in the config file. If it doesn't exist, then the code will write the entry into the config file. When it does this write, it writes the entire file, not just the one section that was changed. This means that the write time should be proportional to the size of the config.
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/util/GT_Config.java#L67

5. The config file is enormous (>9 MB).
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/config/GregTech/Recipes.cfg

So I think what happens is, every time you try putting some new type of wood into the pyrolyse oven (one that isn't in the config file), the code will try to write the entire >9 MB config file. I'm guessing that the write takes longer than a second, so in that time, more reads have kicked off, and they will fail because the file hasn't finished being updated yet. So these will trigger more writes, which eat up even more CPU, causing a cascade of lag. Once that entry actually does get written, though, all future reads will see the existing entry and not try to write the file. This is why oak wood doesn't cause lag: it's already in the config. Here are the default entries in the config as of right now (oak is in there, spruce is not):
https://pastebin.com/yZZWJrPR

I tested this by commenting out the config writes, and the lag went away completely, so I think this is the root of the issue. It's also kind of weird that a player's config file contents depend on which woods they happen to have tried putting into a pyrolyse oven (the added entries are permanent, and persist between sessions).

---

So how do we fix this? Well, fixing the immediate issue is pretty easy:

1. Stop dynamically adding recipes. Just delete these two lines:
https://github.com/GTNewHorizons/bartworks/blob/master/src/main/java/com/github/bartimaeusnek/crossmod/tectech/tileentites/multi/GT_Replacement/TT_PyrolyseOven.java#L168-L170
I'm not sure how many woods are not registered by the default recipe loaders, but it's likely that doing this will cause some woods to no longer have pyrolyse recipes.

2. Maybe look for any woods that are now missing pyrolyse recipes, and add recipes for them. It looks like this is the code that usually does the registering of pyrolyse recipes:
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/loaders/oreprocessing/ProcessingLog.java#L17-L94
though it's tough to figure out exactly which items that method gets called with.

---

I feel like the GT5U configs are just kind of in a bad state in general, though, and this issue is just one symptom of that overarching issue. I think the config code was originally written with the assumption that it will only get called during initial loading, but over time references to the config have kind of crept in all over the place and so it gets read even during the game, leading to these problems. Some examples that I've noticed:

1. That giant config file is way too big; maybe we should break it up. We can probably just break it up by section. This might be a lot of work, depending on how many references there are to it; it is unfortunately public, so there may be references to it outside of GT5U even. The config file is defined here:
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/GregTech_API.java#L222
and initialized here:
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/GT_Mod.java#L185

2. The config file logic will write missing entries into the configs, if it tries to read an entry that doesn't exist. I'm guessing that the point of this code was originally to auto-regenerate config files (after one gets deleted or something), but with the configs getting read all over the place, I think this is leading to a lot of junk getting added to the config (particularly combined with the third issue below). I linked the code for this already above, but here it is again:
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/util/GT_Config.java#L55
(and a few other places in that file)

3. The config file logic appends the value of `aDefault` to the name of the config entry it's reading, for some reason:
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/api/util/GT_Config.java#L53
This leads to all sorts of weirdness, like needing to append `_false` to the end of boolean config entries, and also no longer finding the entry in the config if you change the default value parameter to `true` (because now it's appending `_true` instead of `_false` to the name of the config entry that it's trying to read). I think the config file contains a lot of duplicate entries due to this. For example:
```
    I:dustSmallEnergeticAlloy_1600=1600
    I:dustSmallEnergeticAlloy_3000=3000
    I:dustSmallEnergeticAlloy_3200=3200
    I:dustSmallEnergeticAlloy_4400=4400
    I:dustSmallEnergeticAlloy_44400=44400
    I:dustSmallEnergeticAlloy_6600=6600
```

**Comment by Glease** [comment] 2021-07-27 10:42
* There must be a dynamic recipe generation because some wood got the logWood oredict name extremely late in initialization process via minetweaker scripts. (e.g. those from natura or BOP, can't remember.) There is already attempts at generating recipe map from all wood, but it can't catch those aren't something not yet a logWood at that time. In my structurelib integration branch I also added some guard to hopefully reduce the frequency of dynamic recipe generation. None has tested if it works though.

* Config won't get written to disk until post init (a phase in minecraft loading) finished. It was never expected to be written again more than a few handful times after that. My plan to fix this is to throttle config save to once per 30 seconds (or maybe make it configurable), if my previous guard failed. 

* aDefault must be written into the config name unless recipe adder got redone. This behavior is crucial to the proper functioning of recipe adder, e.g. in the example you have given, it's concerning 6 different recipe for the same output item. Not writing aDefault is like treating them as the same one and it won't be pretty.
  I won't mind if anyone go fix it, as it does make it very hard to find out unused config entries. However, it's going to take a lot of menial labor to update all the related code.

**Comment by Prometheus0000** [comment] 2021-07-27 14:39
Is there a need to make the pyro work on anything other than vanilla woods (and maybe a select few more)? Surely the vast majority only use vanilla or one of a select few, like rainbow oak from GT++, redwood from natura or BOP, or sacred oak from the same. Why bother adding _everything_ if it causes lag? We even have bonsais only for vanilla trees, which most people probably use if they want tons of automated wood.

**Comment by bombcar** [comment] 2021-07-27 16:00
Or add a generic "wood" block (use oak wood?) and allow a machine to do a simple any logwood -> oak wood conversion, and then only have basic recipes on the pyro? If someone really wants to use a strange wood they can middle-step it.

**Comment by D-Cysteine** [comment] 2021-07-27 19:16
Thanks for the background on the config stuff! I guess it was expected, but it sounds like making any big changes there is going to be really involved, so maybe best to save that for a separate discussion thread. I'll just give some final thoughts:

> Config won't get written to disk until post init (a phase in minecraft loading) finished.

Hmm, I wonder if we could just disable writing dynamically-generated config properties (i.e. any property that has an item name, fluid name, or maybe dimension name). If I'm right that the purpose of writing the configs is to provide a default entry for the configs, so that we can generate something a bit better than just an empty config file on initial modpack run, then I'm not sure that it makes sense to include dynamically generated entries in it. If we make this change, we might be able to prevent the config from being written to disk during gameplay.

> aDefault must be written into the config name unless recipe adder got redone.

Yeah, I figured there had to be a good reason why that was added. It is really confusing though. Maybe if I have time I can look at what it would take to clean this up. The large amount of changes needed aside, it will also be very difficult to check that a fix for this doesn't also accidentally break some recipe generation or something. Not sure if there is a better way than just checking manually that everything still works in-game.

---

For the pyrolyse oven, I did some testing in-game. Here's everything in NEI that is ore-dicted to `logWood` and does *not* work in the pyrolyse oven without the dynamic recipe generation (for mods with a lot of woods, I only tested a few):

> Tainted Log (Forbidden Magic)
> Forestry fireproof wood (non-fireproof works)
> Barnarda C Wood (Galaxy Space)
> Rubber Wood (IC2)
> Natura wood
> Warpwood (Tainted Magic)
> Pam's HC wood
> GT++ wood

I'm not sure how many of those are important. Natura redwood and GT++ rainforest oak both don't work, but BOP sacred oak does. The really interesting thing is, none of these woods have these recipes:
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/loaders/oreprocessing/ProcessingLog.java#L97-L107
but all of them have a recipe taking 20 logs, 1000L steam, and a `20` circuit making 24 charcoal.

I tracked that recipe down to here:
https://github.com/GTNewHorizons/GTPP/blob/2fcf772f83309c2d49ab82e50342d812d11baf6e/src/Java/gtPlusPlus/core/recipe/RECIPES_GREGTECH.java#L1173-L1184
and was able to use the same technique to register pyrolyse recipes for all woods during game load (with some experimentation to find the right phase with all woods registered). So thanks GT++ for that solution! As a bonus, the recipes will even show up in NEI now.
 * Pull request soon

**Comment by Prometheus0000** [comment] 2021-07-28 14:28
You need Barnarda C wood to make the radox(?) polymer, by getting something out of the logs. I'm not sure that's in the pyro though and probably doesn't use it as a 'log' but as a specific item.

**Comment by D-Cysteine** [comment] 2021-07-28 16:50
The radox recipe is actually in the pyrolyse oven! It's added separately, as a special case:
https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/2cba7fef3bb78b6a02ef17ed09e518847c6e9fd5/src/main/java/com/dreammaster/bartworksHandler/BacteriaRegistry.java#L175-L183

The dynamic recipe gen code just adds the stuff here:
https://github.com/GTNewHorizons/GT5-Unofficial/blob/experimental/src/main/java/gregtech/loaders/oreprocessing/ProcessingLog.java#L97-L107
which inputs 16 logs, or 16 logs + nitrogen, and outputs charcoal or ash (+ various fluids).

**Closed** 2021-07-30 10:36 UTC
Labels: Mod: BartWorks, Mod: GT, Status: FixedInDev, Type: Lag
