### ISSUE TITLE
Multiblock Centrifuge recipe bug 

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#9716] opened 2022-02-10 09:31 UTC
### Your GTNH Discord Username

Eason1134HK#5098

### Your Pack Version

2.1.2.0

### Your Server

delta

### Your Expectation

![image](https://user-images.githubusercontent.com/59776356/153378864-7819c260-e51a-4247-9d83-e7ef6356777d.png)

### The Reality

I'm not sure if it's just Impure Pile  of lead Dust have this bug 
maybe all of them are buggy 

### Your Proposal

Please fix it 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Eason134HK** [comment] 2022-02-10 09:32
I don't know if this is just a recipe display bug or a recipe bug

**Comment by GTNH-Afx237v7** [comment] 2022-02-10 09:53
Display but for GT++ , duplicate of #9137, fixedindev.

**Comment by Glease** [comment] 2022-02-10 10:02
Duplicate of #9137

**Closed by Glease** 2022-02-10 10:02 UTC
Labels: Type: bugMinor, Status: Triage
