### ISSUE TITLE
Universal wireless terminal bug

### ISSUE THREAD

**Issue by CatsLeftEar** [GTNewHorizons/GT-New-Horizons-Modpack#12708] opened 2023-02-26 00:24 UTC
### Your GTNH Discord Username

Keyla#3300

### Your Pack Version

2.2.10

### Your Server

Private server

### Java Version

Java 8

### Type of Server

Ultramine

### Your Expectation

Tried to make a pattern in a processing terminal

### The Reality

it wasnt accepting more than 1 of each item in "processing terminal", because "pattern terminal" was on a crafting pattern. 
When its on crafting pattern, processing terminal bugs, when its on processing pattern, processing terminal works better

### Your Proposal

bugs

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LewisSaber** [comment] 2023-02-26 00:31
Duplicate of #12682

**Closed by LewisSaber** 2023-02-26 00:32 UTC
Labels: Type: bugMinor, Status: Triage
