### ISSUE TITLE
fluid terminal don't work

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#7679] opened 2021-03-21 07:22 UTC
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
delta 
#
#### What did you try to do, and what did you expect to happen?
Take fluid from the fluid terminal
#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/59776356/111897118-01b08480-8a59-11eb-8255-eab12635d82d.png)
the fluid terminal don't work
#
#### What do you suggest instead/what changes do you propose?
Fix it ?
#
#### What is your GTNH Discord username?
is that really matter? lol 
@Eason1134HK#5098

**Comment by GTNH-Afx237v7** [comment] 2021-03-21 07:50
Duplicate of #4065?
Has been around for a while now, usually it will still accept universal fluid cells or it will work again after restart.

**Closed** 2021-03-21 16:18 UTC
Labels: Type: duplicate
