### ISSUE TITLE
Wrench does not change modes with Shift + R Click on server

### ISSUE THREAD

**Issue by NikhilManikala** [GTNewHorizons/GT-New-Horizons-Modpack#17472] opened 2024-09-26 11:56 UTC
### Your GTNH Discord Username

randompotato10

### Your Pack Version

2.6.1

### Your Server

Private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Shift + R Click with a wrench in the air changes the wrench between Line and normal mode 

### The Reality

Shift + R Click with a wrench in the air does not change the wrench mode when I am playing on my server. The same thing does however work when I load a singleplayer world. 

### Your Proposal

Shift + R Click should let me toggle my wrench mode on the server as I can in single player.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by NikhilManikala** [comment] 2024-09-26 11:57
I have spoken to other people but they seem to be on Singleplayer and not a private server and therefore cannot confirm if the bug exists for them.

**Comment by Lyfts** [comment] 2024-09-26 12:40
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17003

**Closed by Lyfts** 2024-09-26 12:40 UTC
Labels: Type: bugMinor, Status: Triage
