### ISSUE TITLE
Quest Book completion notifications cause other UI elements to render incorrectly

### ISSUE THREAD

**Issue by norbby42** [GTNewHorizons/GT-New-Horizons-Modpack#15097] opened 2023-12-17 02:44 UTC
### Your GTNH Discord Username

Quackers#6418

### Your Pack Version

2.5.0-RC1

### Your Server

Private Dedicated

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

Quest book notifications would not interfere with other UI element rendering

### The Reality

When the quest book displays a quest notification (the big text in the top center of the screen), it causes certain other UI elements to exhibit odd rendering.  I have noticed it primarily with the tinker's crossbow reticle and the saturation meter (specifically only for "over saturation" where haunches are highlighted):

![2023-12-16_19 59 22](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/10271937/36ad3918-022b-41ff-bc6e-d061bdeb5a50)
![2023-12-16_21 35 56](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/10271937/6b9d753b-3776-4c2c-89fe-c75b49647745)

### Your Proposal

Address the incompatibility

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Mobius0526** [comment] 2023-12-17 03:47
Yes, this kind of thing happens here too. When I complete a task, the game interface is completely black

**Comment by bombcar** [comment] 2023-12-17 03:54
Related https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15039

**Comment by chochem** [comment] 2023-12-19 00:38
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15039

**Closed by chochem** 2023-12-19 00:38 UTC
Labels: Type: bugMinor, Type: Visual, Mod: Betterquesting, Status: Triage
