### ISSUE TITLE
Crash In Main Menu after Changing Anisotropic Filtering

### ISSUE THREAD

**Issue by ALongStringOfNumbers** [GTNewHorizons/GT-New-Horizons-Modpack#12980] opened 2023-03-21 03:00 UTC
### Your GTNH Discord Username

ALongStringOfNumbers#9024

### Your Pack Version

2.3.1

### Your Server

Personal Server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Actions

Change the Anisotropic Filtering Level in the main menu by either clicking in the sliding widget, or by dragging the scroll bar.

### Crash Report

https://gist.github.com/ALongStringOfNumbers/70e06be50c6d30e20f79ccb877ca1103

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2023-03-21 16:59
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12968

**Closed by chochem** 2023-03-21 16:59 UTC
Labels: Type: Crash, Status: Triage
