### ISSUE TITLE
AE2 crafting order 'start' button often doesn't work

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12255] opened 2023-01-12 19:12 UTC
### Your Pack Version

2.2.3

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Expectation

When i hit the start button on a crafting order i expect it to start crafting if it can.

### The Reality

However, 8 to 9 out of 10 times the start button won't work at all, no matter how long i wait after it is already no longer grayed out with all required items present and a large enough CPU selected.
This forces me to cancel it and try again and again for sometimes more than a dozen times which can become quite infuriating, especially with orders that take a minute to calculate.

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by greesyB** [comment] 2023-01-12 19:13
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10590

**Closed by greesyB** 2023-01-12 19:13 UTC
Labels: Type: bugMinor, Status: Triage
