### ISSUE TITLE
Sterile farm casing displays wrong number of planks in NEI

### ISSUE THREAD

**Issue by Dr-Nye** [GTNewHorizons/GT-New-Horizons-Modpack#12479] opened 2023-02-03 13:41 UTC
### Your GTNH Discord Username

DrNye#6969

### Your Pack Version

2.2.8

### Your Server

SP

### Type of Server

Vanilla Forge

### Your Expectation

Displays 1 Needed so should only need 1

### The Reality

Takes 8 planks per craft

### Your Proposal

Either Make it only consume 1 or update NEI

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment] 2023-02-03 14:31
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12090

**Closed by miozune** 2023-02-03 14:31 UTC
Labels: Type: bugMinor, Status: Triage
