### ISSUE TITLE
TF naga crash

### ISSUE THREAD

**Issue by EnderProyects** [GTNewHorizons/GT-New-Horizons-Modpack#16508] opened 2024-06-10 15:42 UTC
### Your GTNH Discord Username

Ender Proyects#6669

### Your Pack Version

2.6.1

### Your Server

private

### Java Version

Java 20

### Type of Server

Other MCPC+ fork

### Your Actions

walking in the TF

### Crash Report

---- Minecraft Crash Report ----
// You're mean.

Time: 6/10/24 3:35 PM
Description: Exception getting block type in world

java.lang.NullPointerException: Exception getting block type in world
        at twilightforest.structures.courtyard.ComponentTFNagaCourtyardWallCornerOuter.func_74875_a(ComponentTFNagaCourtyardWallCornerOuter.java:52)
        at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:44)
        at net.minecraft.world.gen.structure.MapGenStructure.func_75051_a(MapGenStructure.java:93)
        at twilightforest.world.ChunkProviderTwilightForest.func_73153_a(ChunkProviderTwilightForest.java:950)
        at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
        at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050)
        at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
        at net.minecraft.world.World.func_72964_e(World.java:419)
        at net.minecraft.world.World.func_147439_a(World.java:345)
        at net.minecraft.world.World.func_147437_c(World.java:365)
        at mods.natura.worldgen.BaseCropWorldgen.generateBarley(BaseCropWorldgen.java:145)
        at mods.natura.worldgen.BaseCropWorldgen.generate(BaseCropWorldgen.java:54)
        at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
        at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
        at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1040)
        at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
        at net.minecraft.world.World.func_72964_e(World.java:419)
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:313)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Lyfts** [comment] 2024-06-10 17:15
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16353 and many others.

You can update twilight forest to https://github.com/GTNewHorizons/twilightforest/releases/tag/2.6.12

**Closed by Lyfts** 2024-06-10 17:15 UTC
Labels: Type: Crash, Status: Triage
