### ISSUE TITLE
GT fluid pipe pushing to pressurized fluid conduit voids fluids

### ISSUE THREAD

**Issue by repo-alt** [GTNewHorizons/GT-New-Horizons-Modpack#8867] opened 2021-11-18 12:37 UTC
### Your GTNH Discord Username

repolainen#0483

### Your Pack Version

2.1.1.4qf2

### Your Server

Zeta

### Your Expectation

Test setup: any GT tank with diesel, LV pump on it, tiny PTFE pipe attached to the pump and to the pressurized fluid conduit, conduit points e.g. to the combustion generator.

### The Reality

Setup above will eventually void all diesel, despite the fact that the generator does not work. (Actually generator may be replaced with any small tank)

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by yukieiji** [comment] 2021-11-18 12:57
Duplicate of #7094, #4161

**Closed** 2021-11-18 13:04 UTC
Labels: Type: duplicate, Type: bugMinor, Mod: Ender IO, Mod: GT, Status: Triage
