### ISSUE TITLE
Machine in-progress operation Item Dupe on World Reload

### ISSUE THREAD

**Issue by TwoTailedFox** [GTNewHorizons/GT-New-Horizons-Modpack#9870] opened 2022-03-05 18:59 UTC
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.3

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

When exiting the world, I expect machines with finished operations to stay finished.

### The Reality

When I reload the world, a GT machine that has finished operation with its output contents being emptied prior to client exit and world save, when the world is then reloaded as normal, is still processing the same operation, and has both the former output contents still in place, as well as the current machine operation still in progress. This results in item duping. This seems to happen to machines that have finished and that are emptied very close to me closing the MC client, like maybe 5 seconds away from inventory update to command to save and exit.

### Your Proposal

This may be due to machine states not being correctly read on world save and exit. Bug has happened three times to myself thus far, so this is far from a fluke, bug may require investigation.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment] 2022-03-05 19:05
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9838

**Closed by Glease** 2022-03-05 19:05 UTC
Labels: Type: bugMinor
