### ISSUE TITLE
Integrated Ore Processor gets wrong output with ME input bus 

### ISSUE THREAD

**Issue by FirstBigFor** [GTNewHorizons/GT-New-Horizons-Modpack#12483] opened 2023-02-03 16:59 UTC
### Your GTNH Discord Username

FirstBigFor#2789

### Your Pack Version

2.2.2.0

### Your Server

eta

### Type of Server

None

### Your Expectation

Once I use ME input bus in Ore Processor.The input  is always 1024 per times,but the output is just few.
![图片](https://user-images.githubusercontent.com/111168675/216659664-58f9e6d7-f743-4fac-a032-544bb410b7c6.png)

the output with one time running
![图片](https://user-images.githubusercontent.com/111168675/216659780-f3c04aef-6cf4-45ee-9108-c8e108e6536b.png)

### The Reality

The input number is right,but the output is less than expectation.This problem ONLY exist when I use ME input bus .With other gt input bus,the result is correct.

### Your Proposal

The wrong output number just equal to process one stack ore‘s result.So I think,maybe the ore processor just regards the ME input bus as one stack.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2023-02-04 17:31
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11490
fixed already.

**Closed by chochem** 2023-02-04 17:31 UTC
Labels: Type: bugMinor, Status: Triage
