### ISSUE TITLE
add a new multi for electromagnetic separator recipes

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#14445] opened 2023-09-05 20:34 UTC
### Your GTNH Discord Username

boubou_19

### Your Pack Version

2.4.0

### Your Proposal

let's add a new multi for electromagnetic separator recipes (tengam, and some recipes in monaline)

### Your Goal

add a missing multi to be inline with other singleblock -> multi transition, and this is a blocking point for PA removal.

### Your Vision

make the pack more consistent about the singleblock -> multi transition.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by vovaksenov** [comment] 2023-09-28 12:33
Duplicate of #14192

**Comment by Hikari1nVoid** [comment] 2023-12-30 13:37
As PA is still in the deprecation plan this should not be closed as 'not planned'.

**Comment by FourIsTheNumber** [comment] 2024-07-18 14:06
Resolved: https://github.com/GTNewHorizons/GT5-Unofficial/pull/2726

**Closed** 2024-07-22 15:05 UTC
Labels: Type: Suggestion
