### ISSUE TITLE
Game crashes during loading of older savegame

### ISSUE THREAD

**Issue by PaulVisschers** [GTNewHorizons/GT-New-Horizons-Modpack#9202] opened 2021-12-20 13:37 UTC
### Your GTNH Discord Username

PaulV#6149

### Your Pack Version

2.1.2.0

### Your Server

SP

### Type of Server

Single Player

### Your Actions

I upgraded the modpack from 2.1.0.0 to 2.1.2.0 using Technic Launcher and tried to load a savegame from 7 months ago. After taking ages to cache ore data it crashed back to desktop. Trying a few more times it went back to the main menu instead. On the discord someone suggested it may be due to VisualProspecting not having enough memory. I tried removing it as well as giving it more memory (with VisualProspecting still in place) and in both cases this speeded things along a lot but it still crashed. (Attached is the crash log where VisualProspecting was removed. I tried starting a new game without VisualProspecting and that worked just fine.)

### Crash Report

[2021-12-20-4.log.gz](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7745451/2021-12-20-4.log.gz)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment] 2021-12-20 13:43
Duplicate of #9123

**Closed by Glease** 2021-12-20 13:43 UTC
Labels: Type: Crash, Status: Triage
