### ISSUE TITLE
Crash when shift clicking an item into gregtech machine

### ISSUE THREAD

**Issue by no-odles** [GTNewHorizons/GT-New-Horizons-Modpack#17429] opened 2024-09-23 10:50 UTC
### Your GTNH Discord Username

noodl_es

### Your Pack Version

2.7.0-beta-1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

Steps to reproduce:
1) Open a GT machine
2) Shift click something into it (only succeeded with a gregtech item).
3) Game crashes 30-50% of the time

Possibly a duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17401, but doesn't require a gregtech tool. Has worked for me with empty cells, and a gregtech battery. The crash happens after shift clicking, not just holding shift and mousing over. Reloading the world shows the item was successfully moved into the machine despite the crash.

Running on Kubuntu 22.04.4
-Dgt.recipebuilder.recipe_collision_check=true java flag is enabled.

### Crash Report

[crash-2024-09-23_19.59.11-client.txt](https://github.com/user-attachments/files/17096041/crash-2024-09-23_19.59.11-client.txt)
[crash-2024-09-23_20.31.35-client.txt](https://github.com/user-attachments/files/17096252/crash-2024-09-23_20.31.35-client.txt)
[crash-2024-09-23_20.39.07-client.txt](https://github.com/user-attachments/files/17096254/crash-2024-09-23_20.39.07-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Vsevolod090** [comment] 2024-09-23 11:23
Issue is reported aleady
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17427#issue-2541463846

**Comment by NotAPenguin0** [comment] 2024-09-23 11:27
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17401 according to https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17427#issue-2541463846

**Closed by NotAPenguin0** 2024-09-23 11:27 UTC
Labels: Type: Crash, Status: Triage
