### ISSUE TITLE
Tier 1 and 3 OC Microchips don't oredict circuits.

### ISSUE THREAD

**Issue by weschaos** [GTNewHorizons/GT-New-Horizons-Modpack#5216] opened 2019-12-24 03:46 UTC
#### Which modpack version are you using?
2.0.8.0pre

#### What did you try to do, and what did you expect to happen?
I tried to use Quantumprocessors in the Tier 3 Opencomputers microchip recipe, but it didn't work. I expected it to work normally, but going through NEI it appears that it only accepts Workstations, which makes crafting OC components somewhat more burdensome. The tier 1 microchips have a similar problem with requiring Good Electronic Circuits.
#
#### What do you suggest instead/what changes do you propose?
Oredict the recipes for OC to accept quantumprocessors and other high-tier circuits, unless this is intentional for some reason. I'd do it myself for my personal use but I don't know how.

I'll look through recipes and see if there are any others that need similar changes. I don't think there are any at the moment, but I haven't gone through every OC component to be sure.

**Comment by Dream-Master** [comment] 2019-12-24 09:03
known bug.
Need help with the circuit assembler to use oredict correct.
@bartimaeusnek @Technus @mitchej123 @richardhendricks @repo-alt

**Comment by repo-alt** [comment] 2019-12-24 19:59
Duplicate of https://github.com/GTNewHorizons/NewHorizons/issues/5154
Looks like Bart's hack in GT_Values.RA.addCircuitAssemblerRecipe does not work if called after GT postInit. (I could not figure out how to launch NH core mod under debugger to investigate - some dependencies are missing and the log messages are not too helpful.)

**Comment by bartimaeusnek** [comment] 2019-12-24 20:01
@repo-alt IIRC OC directly accessed the maps...

**Comment by repo-alt** [comment] 2019-12-24 20:02
Nah, we redid the recipes

**Comment by repo-alt** [comment] 2019-12-24 20:03
Although, they can be added OC way, via config, then all the oredictionary variants will be added.

**Comment by repo-alt** [comment] 2020-01-04 04:05
Ok, I found out what is causing GT_Values.RA.addCircuitAssemblerRecipe to not work as expected.  Apparently @bartimaeusnek tried to fix that in GT_Recipe.findRecipe but not succeeded.
GT_Recipe.addRecipe, when checking for collisions, unifies added recipes, and if the recipe is added after GT postInit, it even ignores unification blacklist: https://github.com/GTNewHorizons/GT5-Unofficial/blob/e10456295def2ea5bacede8ab954524aa03165a4/src/main/java/gregtech/api/util/GT_OreDictUnificator.java#L146 I've no idea how to fix that w/o breaking tons of other shit, probably Bart dug in that code longer than me, and it would be easier for him to finish what he started.

**Comment by Prometheus0000** [comment] 2020-10-10 12:57
Dupicate of #4714

**Closed by Prometheus0000** 2020-10-10 12:57 UTC
Labels: Type: duplicate, Type: help wanted
