### ISSUE TITLE
Typo in MegaEBF tooltip

### ISSUE THREAD

**Issue by NeroOneTrueKing** [GTNewHorizons/GT-New-Horizons-Modpack#7841] opened 2021-04-22 01:04 UTC
#### Which modpack version are you using?
2.1.0.5
#
![image](https://user-images.githubusercontent.com/28197216/115640449-961e3900-a2dc-11eb-9373-fb9de45810b1.png)
Says it requires "Boronsilicate Glass". The correct name is "Borosilicate Glass" (at least, to be consistent with every other instance of it in GTNH).
#
#### What is your GTNH Discord username?
NeroOneTrueKing

**Comment by Prometheus0000** [comment] 2021-04-22 01:07
Duplicate of #6912.

**Closed by Prometheus0000** 2021-04-22 01:07 UTC
