### ISSUE TITLE
Maple tree gives unusable type of wood

### ISSUE THREAD

**Issue by Cleptomania** [GTNewHorizons/GT-New-Horizons-Modpack#7777] opened 2021-04-07 03:34 UTC
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
Is multiplayer, self hosted server
#
#### What did you try to do, and what did you expect to happen?
Cutting down a Pam's Harvestcraft maple tree would give me maple logs, and those would run in an extractor to make Maple Syrup
#
#### What happened instead? (Attach screenshots if needed)
Cutting down the tree(tried with both lumber axe and regular axe) gives wood with the ID 1629:1, as opposed to 1629. Putting this wood in the extractor does nothing. If I spawn in a log from NEI with just ID 1629, it runs in the extractor no problems.

Tried growing the tree with and without bone meal as well and had the same result.
#
#### What do you suggest instead/what changes do you propose?
Either make the tree give the proper ID, or adjust the extractor recipe to not care about it
#
#### What is your GTNH Discord username?
Clepto#5351

**Comment by Prometheus0000** [comment] 2021-04-07 05:09
Duplicate of  #5385, also, already fixed. Try using search.

**Closed by Prometheus0000** 2021-04-07 05:09 UTC
Labels: Type: duplicate
