### ISSUE TITLE
All screwdriver and bolt textures are pure white squares

### ISSUE THREAD

**Issue by DYstebo** [GTNewHorizons/GT-New-Horizons-Modpack#18561] opened 2024-12-28 21:56 UTC
### Your GTNH Discord Username

pkmrpres

### Your Pack Version

2.7.1

### Your Server

private

### Java Version

Java 21

### Type of Server

Don't know

### Your Expectation

Item pictures should show screwdrivers/bolts.

### The Reality

Item pictures show plain white square covering whole item slot.

### Your Proposal

Fix the image for both of the item types.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by StaffiX** [comment] 2024-12-28 21:57
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18454

**Closed by StaffiX** 2024-12-28 21:57 UTC
Labels: Bug: Minor, Status: Triage
