### ISSUE TITLE
Replacing LSC controller causes crash

### ISSUE THREAD

**Issue by UnknownTimelord** [GTNewHorizons/GT-New-Horizons-Modpack#16224] opened 2024-05-09 22:32 UTC
### Your GTNH Discord Username

tenthant

### Your Pack Version

2.6.0

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Actions

Destroyed LSC controller, and replaced it. This has happened one other time but we didn't get the log output last time.

### Crash Report

`[16:19:28] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
        at RFB-Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
        at RFB-Launch//net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
        at RFB-Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
        at RFB-Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at RFB-Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.ArithmeticException: / by zero
        at java.base/java.math.BigDecimal.divideAndRound(BigDecimal.java:4675) ~[?:?]
        at java.base/java.math.BigDecimal.divide(BigDecimal.java:5763) ~[?:?]
        at java.base/java.math.BigDecimal.divide(BigDecimal.java:1650) ~[?:?]
        at java.base/java.math.BigDecimal.divide(BigDecimal.java:1731) ~[?:?]
        at RFB-Launch//util.Util.toPercentageFrom(Util.java:72) ~[Util.class:?]
        at RFB-Launch//common.tileentities.GTMTE_LapotronicSuperCapacitor.getInfoData(GTMTE_LapotronicSuperCapacitor.java:918) ~[GTMTE_LapotronicSuperCapacitor.class:?]
        at RFB-Launch//gregtech.api.metatileentity.BaseMetaTileEntity.getInfoData(BaseMetaTileEntity.java:2292) ~[BaseMetaTileEntity.class:?]
        at RFB-Launch//gregtech.common.items.GT_SensorCard_Item.update(GT_SensorCard_Item.java:71) ~[GT_SensorCard_Item.class:?]
        at RFB-Launch//gregtech.common.items.GT_SensorCard_Item.update(GT_SensorCard_Item.java:61) ~[GT_SensorCard_Item.class:?]
        at RFB-Launch//shedar.mods.ic2.nuclearcontrol.tileentities.TileEntityInfoPanel.processCard(TileEntityInfoPanel.java:729) ~[TileEntityInfoPanel.class:?]
        at RFB-Launch//shedar.mods.ic2.nuclearcontrol.tileentities.TileEntityInfoPanel.func_70296_d(TileEntityInfoPanel.java:752) ~[TileEntityInfoPanel.class:?]
        at RFB-Launch//shedar.mods.ic2.nuclearcontrol.tileentities.TileEntityInfoPanel.func_145845_h(TileEntityInfoPanel.java:402) ~[TileEntityInfoPanel.class:?]
        at RFB-Launch//net.minecraft.world.World.func_72939_s(World.java:1939) ~[ahb.class:?]
        at RFB-Launch//net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
        at RFB-Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
        ... 4 more`
I also attached the full log just in case
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15268330/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Lyfts** [comment] 2024-05-10 05:54
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16167

Update Kekztech to latest https://github.com/GTNewHorizons/KekzTech/releases/tag/0.11.3

**Closed by Lyfts** 2024-05-10 05:54 UTC
Labels: Type: Crash, Status: Triage
