### ISSUE TITLE
Allow Granite Ores For Early Quests

### ISSUE THREAD

**Issue by DarkYuan** [GTNewHorizons/GT-New-Horizons-Modpack#8546] opened 2021-09-17 20:43 UTC
### Your GTNH Discord Username

DarkYuan#5002

### Your Pack Version

2.1.1.0

### Your Proposal

When I got to the quest for finding diamonds in the steam age it was locked to "stone" ores only. But by then I could mine red/black granite, which my diamond vein happened to be in. I'd change the quest requirements for at least the "Ooo, Shiny! (Not Platinum!)" quest 495 to also allow granite versions of the ores.

### Your Goal

By the time a player is expected to mine diamond, granite ores should be counted by the quests as well. There may be other quests further in that could benefit from a change like this, I don't know.

### Your Vision

QOL improvements

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment] 2021-09-17 20:58
The ores have no ore tag for the different variants so it might be hard to define it in the quests

**Comment by DarkYuan** [comment] 2021-09-17 21:00
Yeah, I noticed while I was writing this up, they're not considered oreDiamond. I think you can use an array in quest tasks though right?

**Comment by Prometheus0000** [comment] 2021-09-18 00:01
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6042. AFAIK, this is impossible. I'm not sure what you mean about an array though, maybe try it out and see if it works?

**Comment by Houstonruss** [comment] 2021-09-18 00:19
Easily solvable by not requiring the ores, but rather their outputs in the quests.

**Comment by DarkYuan** [comment] 2021-09-18 00:43
> Duplicate of #6042. AFAIK, this is impossible. I'm not sure what you mean about an array though, maybe try it out and see if it works?

Ah I see. It only supports oredict groups, not just any group of possible items. To do that would require manually adding the desired ores to a custom oredict entry.

**Comment by Prometheus0000** [comment] 2021-09-18 00:56
> Easily solvable by not requiring the ores, but rather their outputs in the quests.

These quests are about getting ore, not ingots/gems/dust. Plus it'd be a huge pain to change them all.

> To do that would require manually adding the desired ores to a custom oredict entry.

If you mean changing GT code, yeah it'd probably be possible. I have no idea why it separates it out into different oredicts by block type, I can't think of a reason to filter them based on this, you would simply do so with the generated byproduct dust instead. If someone wants to change the oredict attached to ores (or add one that applies to all), that's cool, but I don't feel like doing it. If someone feels like doing that this can be reopened.

**Closed by Prometheus0000** 2021-09-18 00:56 UTC
Labels: Type: duplicate, Type: suggestion, Status: Triage

**Comment by DarkYuan** [comment] 2021-09-18 00:58
Oh you wouldn't have to edit the code, they can be added to an oredict entry by crafttweaker script. But nonetheless, yeah too much manual editing.
