### ISSUE TITLE
No quests in questbook after update to 2.7

### ISSUE THREAD

**Issue by kInikel** [GTNewHorizons/GT-New-Horizons-Modpack#18298] opened 2024-12-09 05:20 UTC
### Your Pack Version

2.7

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

To see the quests in the questbook

### The Reality

There are no quests

### Your Proposal

The quests are missing

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by StaffiX** [comment] 2024-12-09 05:51
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18264

**Closed by StaffiX** 2024-12-09 05:51 UTC
Labels: Bug: Minor, Status: Triage
