### ISSUE TITLE
Machine Crash due to Stocking Input Bus/Hatch

### ISSUE THREAD

**Issue by OlliedeLeeuw** [GTNewHorizons/GT-New-Horizons-Modpack#15180] opened 2023-12-21 09:42 UTC
### Your GTNH Discord Username

ollie_de_leeuw

### Your Pack Version

2.5.1, same issue in 2.5.0

### Your Server

private server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

The stocking input bus/hatch to continue working and the machine to not crash.

### The Reality

the machine shuts off with a crash
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/154506304/43800fef-f368-43b5-ac0c-6dbcd132328c)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/154506304/b3aec221-6990-4984-8d0a-3d7f68eb93c9)
-version: 2.5.1 , ignore the maintenance issue it does not affect the result. 3 stocking input busses (1 without auto-pull, 2 with auto-pull)

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/154506304/a73e4dcc-7295-48fb-b0a4-8a573f730434)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/154506304/ad3b7e93-5658-410c-a6f0-26042f54b433)
-version: 2.5.0 (image from NotAPenguin), 1 stocking input hatch (without auto-pull)

### Your Proposal

When failing to extract happens it should proceed to do the next recipe check instead of staying on the failed extraction and crashing.

Don't have steps to reproduce it, first time happening to me, NotAPenguin has had it happen a few times in his mega naqline.
(similar to #15172 but different error)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by NotAPenguin0** [comment] 2023-12-21 11:46
To elaborate on this, I found this to happen the most when there are multiple very fast machines (MCR, MDT, MBF) contesting the same fluid. The issue is not exclusive to this case though (see large naquadah reactor)

**Comment by miozune** [comment] 2023-12-21 13:39
- Issue with having multiple stocking buses/hatches with the same configured ingredient included in the same machine (maceration stack one), can be mitigated by restoring https://github.com/GTNewHorizons/GT5-Unofficial/pull/2104. However, it has one downside; Stocking buses from different network with the same configuration will lose the ability to have parallel of two hatches combined, but limited to either of them instead.
- Issue with attaching stocking buses to different machines from the same ME source (what @NotAPenguin0 brought up) cannot be fixed without extra work on feature to get it running because of the way stocking bus/hatch currently work.
  - The "proper" fix is pulling actual ingredients from the network. It will permanently remove the chance of having accidental attempt to dupe ingredients. However, I got massive nay from players when I implemented it, since it means they need to re-configure all the stocking buses to fix load balance issue. (https://github.com/GTNewHorizons/GT5-Unofficial/pull/2324)
  - Another way comes to my mind is telling other buses in the same network that it consumed ingredients and others should also decrease stored ingredients. However, this might lead to massive lag caused by traversing ME network each time ingredients are consumed.
  - ~~Or we can simply allow duping ingredients since they're infinite at this point~~
  - Anyways, these two have major caveats and need good amount of time for implementation. Or if you have another idea please share that.

**Comment by bombcar** [comment] 2023-12-21 13:46
> The "proper" fix is pulling actual ingredients from the network.

could this fix be implemented as a “high speed parallel stocking bus” (maybe even similar price) that utilizes this code but leaves the existing as is?

**Comment by miozune** [comment] 2023-12-21 13:52
> Just dont turn off machine when this error, update stocking and go next recipe check. its will work?

Doesn't it mean you might lose all the ingredients that are consumed along with problematic ingredient failed extraction in the network?

> could this fix be implemented as a “high speed parallel stocking bus” (maybe even similar price) that utilizes this code but leaves the existing as is?

I'm not sure if people would use it honestly. Current way might be easier to use since it doesn't need extra configuration for load balancing.

**Comment by lordIcocain** [comment] 2023-12-21 13:57
> Doesn't it mean you might lose all the ingredients that are consumed along with problematic ingredient failed extraction in the network?
Return consumed ingredients back to network would be perfect solution.

**Comment by miozune** [comment] 2023-12-21 14:17
> Return consumed ingredients back to network would be perfect solution.

Maybe, but it still voids certain ingredients and refuses to process them without warning, which is not great imo.

**Comment by NotAPenguin0** [comment] 2023-12-21 14:23
That wouldn't be ideal, but machines with stocking buses/hatches randomly turning off every few hours is also not a great experience.

**Comment by lordIcocain** [comment] 2023-12-21 14:24
oh, so its impossible prevent void? sad

**Comment by miozune** [comment] 2023-12-21 14:33
I might work on this feature tomorrow to see how it could affect performance; `telling other buses in the same network that it consumed ingredients and others should also decrease stored ingredients`

What do you think about this one? `it has one downside; Stocking buses from different network with the same configuration will lose the ability to have parallel of two hatches combined, but limited to either of them instead.`

**Comment by lordIcocain** [comment] 2023-12-21 14:34
@miozune What about add quick and dirty fix for now? add min stack size to non auto pull mode and in error write "increase min stack size for prevent error"

**Comment by boubou19** [comment] 2023-12-21 14:37
it's useless as it won't be pushed in a potential 2.5.2. Dirt hacks like this should be avoided.

**Comment by lordIcocain** [comment] 2023-12-21 14:51
> I might work on this feature tomorrow to see how it could affect performance; `telling other buses in the same network that it consumed ingredients and others should also decrease stored ingredients`
> 
> What do you think about this one? `it has one downside; Stocking buses from different network with the same configuration will lose the ability to have parallel of two hatches combined, but limited to either of them instead.`

This will not working for situation when one stocking shared between several machines.

What if you take your rework and add stocking input bus/hatch slave (similar as with crafting input buffer). ofc still need re-configure setup. but it's much easier and perfect load balance. what do you think?

**Comment by miozune** [comment] 2023-12-21 14:52
Now I'm confused... Reading code makes me think the second issue is impossible to happen, unless items/fluids visible from buses/hatches are actually duplicated... Or maybe my brain is sleeping... Another pair of eyes for investigating this issue would be appreciated.

**Comment by NotAPenguin0** [comment] 2023-12-21 14:52
> it has one downside; Stocking buses from different network with the same configuration will lose the ability to have parallel of two hatches combined, but limited to either of them instead.

This sounds fine tbh, I've never ran into a case where this would be useful.

**Comment by NotAPenguin0** [comment] 2023-12-21 14:59
> Now I'm confused... Reading code makes me think the second issue is impossible to happen, unless items/fluids visible from buses/hatches are actually duplicated... Or maybe my brain is sleeping... Another pair of eyes for investigating this issue would be appreciated.

I never got this issue on 2.4.0, so I'd imagine this is indeed a bug that has snuck in somehow.

**Comment by miozune** [comment] 2023-12-21 15:06
> I never got this issue on 2.4.0, so I'd imagine this is indeed a bug that has snuck in somehow.

This anti-dupe feature was introduced after 2.4.1

**Comment by lordIcocain** [comment] 2023-12-21 21:27
[2.5.1] Getting this error twice today with only 1 stocking hatch in subnet shared between 4 LPF, so solution "let stocking speaking between each other" not working at all.

So allow dupe or rework. My opinion that rework should be, but with 2 changes:
1. Add stocking input slave (should work as with crafting input buffer)
2. Add ghost mode that let stocking work like it work now. This need for automation where you have non consumed items which should be in network constantly. Or just ability set list of items that should be stocked in as ghost.

**Comment by lordIcocain** [comment] 2023-12-21 22:59
what if 
machine found recipe -> stocking pull items from ME inside and if all ok -> start recipe. if no go next check. this prevent voiding other ingredients? or its just impossible?

**Comment by lordIcocain** [comment] 2023-12-25 01:24
> [2.5.1] Getting this error twice today with only 1 stocking hatch in subnet shared between 4 LPF, so solution "let stocking speaking between each other" not working at all.

I cant reproduce this error anymore, probably was my mistake. I apologize for misleading you.

**Comment by lordIcocain** [comment] 2023-12-26 15:49
I think its happen because sometimes slot updating happen before end recipe check, storedFluids[i] already null and cant be checked, that explain why happen only in auto pull mode, also explain why you can get wrong positive check for "failed extract from storage" error. Also idk why, but sometimes its just cant happen on current game load, i need restart game and then it start happen.
I have world save where can easy reproduce error, so i can run gt5 with extra console outputs for get more information.

**Comment by Riverness** [comment] 2024-01-30 18:10
Just happened with an input I'm 100% sure it isn't being requested by anywhere else. Not autopull, using the basic stocking input bus. When I have time later I will try replicating in a fresh world.

**Comment by RitumsC** [comment] 2024-01-31 00:05
Additional observations on the issue reported by Penguin in the comments:

This only seems to happen with the advanced stocking hatches.

I had a setup of 4 compact mk III fusion reactors and 1 mk IV; all mk III had regular stocking hatches with whitelisted fluids, and mk IV the advanced stocking hatch. When running recipes they properly pulled from the subnet without any problems.

Then I switched all compacts to use advanced stocking hatch, and now I constantly get this error and voided materials.

**Comment by Riverness** [comment] 2024-02-05 22:16
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45148827/681fd810-c509-496e-ab20-42343dbe3db1)

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/45148827/24ca35ef-a55f-4dc1-8290-65e16017e9db)

_Something_ is making the stocking input bus think the system has double the amount of the stuff.

I checked a few other buses, all of them exhibit this behaviour. The dusts are stored in a subnet drive, and these stocking input buses are all through p2p networks.

**Comment by Riverness** [comment] 2024-02-05 22:30
Okay. I determined the cause of the doubling in my case. I have multiple storage buses from the main net going to interfaces in the subnet, and all of them are bi-directional. The stocking input bus is reading the contents of the subnet from both storage buses separately, and this results in the stocking bus thinking it has double the items. In my case, this should be the root cause of the machines crashing.

**Closed** 2024-03-11 18:45 UTC
Labels: Type: bugMinor, Status: Triage
