### ISSUE TITLE
Railcraft multiblocks unforming on relog

### ISSUE THREAD

**Issue by WarlordWossman** [GTNewHorizons/GT-New-Horizons-Modpack#3276] opened 2018-07-08 14:30 UTC
#### Which modpack version are you using?
2.0.4.6

#### If in multiplayer; On which server does this happen? 
SMP; HUG server (host: Rohrschneider), does run forge essentials

Since yesterday all my railcraft multiblocks that DON'T cross a chunk border unform every time I relog.
Dimension change or player unloading the chunks in other ways didn't make them unform (tested a bit earlier).

![2018-07-08_15 55 05](https://user-images.githubusercontent.com/16925725/42420792-bd62a0ca-82cb-11e8-974b-2698458c1591.png)
![2018-07-08_15 55 09](https://user-images.githubusercontent.com/16925725/42420793-c0b11f04-82cb-11e8-8ddf-02877587335a.png)
![2018-07-08_15 54 27](https://user-images.githubusercontent.com/16925725/42420795-c4837104-82cb-11e8-9a4a-5212280fef0c.png)
![2018-07-08_15 54 18](https://user-images.githubusercontent.com/16925725/42420798-c7781f54-82cb-11e8-9c3d-1bfaa86d91c1.png)

This never happened to me before; the multiblocks are not obstructed by any chance since breaking and placing a single block makes them form again.
Also the ones on the chunk border don't seem to break for some reason, maybe the game does a check because they are stored in 2 chunks (?)

Anyways this makes it really annoying to play, having to fix 12 coke ovens, 1 adv coke oven, 10 water tanks and 1 iron tank every time I relog is pretty painfull.

**Comment by WarlordWossman** [comment] 2018-07-08 14:46
Oh yeah, the nuclear controll information pannel does also break on relog:
![2018-07-08_16 44 34](https://user-images.githubusercontent.com/16925725/42420986-58bb47c8-82ce-11e8-8dad-243a2e205464.png)

I have no clue what is going on but maybe all non GT multiblocks would break on relog, weird stuff...

**Comment by mitchej123** [comment] 2018-07-09 06:04
Can you reproduce this locally?  Any logs from the server that are helpful?

**Comment by boubou19** [comment] 2018-07-09 09:07
i will try to reproduce this on delta later today

**Comment by boubou19** [comment] 2018-07-09 12:42
So here is the setup i used for the test:
![2018-07-09_14 36 28](https://user-images.githubusercontent.com/12850933/42450902-ec24e73c-8385-11e8-9126-058349414434.png)
i quit Delta for like 30 sec then i joined Delta again:
![2018-07-09_14 38 45](https://user-images.githubusercontent.com/12850933/42450955-1daff760-8386-11e8-9a5e-d401b9a0bc76.png)
as you can see, the water siding tanks are still formed. I teleported myself at random coords so the chunks weren't chunkloaded. My guess is that it's only related to your server

**Comment by WarlordWossman** [comment] 2018-07-09 13:50
> Can you reproduce this locally? Any logs from the server that are helpful?

I will have to test more but I have played tons of singleplayer and it did never happen to me there.
Going to ask for the server logs but I obv cannot tell you if they will be given to me.

>i quit Delta for like 30 sec then i joined Delta again: as you can see, the water siding tanks are still formed. I teleported myself at random coords so the chunks weren't chunkloaded. My guess is that it's only related to your server
edit: i precise that all the tanks are formed not only the one crossing borders

Have played this pack pretty much since day 1 and never had the problem either, I did play on Delta and Epsilon multiple times as well and it did not happen.
I would support your guess that it has something to do with the server, even if I don't know every technical detail.

**Comment by daddy77gaming** [comment] 2020-10-15 20:07
I'd like to add to this. 

played thru GTNH 2x on SSP and 2x on a server.

Now on the second time playing on a server.

![image](https://user-images.githubusercontent.com/31905330/96180292-80e1df80-0f32-11eb-997f-763c2bf60669.png)

2 out of 2 times after having gone to space now the railcraft multiblocks all deform.

So i feel I can reproduce by going to space. If anyone guides me as to what server logs or whatever I need to look for to find out what is causing this to happen hit me up 👍

**Comment by Prometheus0000** [comment] 2020-10-15 20:09
Maybe it's thermos again?

**Comment by daddy77gaming** [comment] 2020-10-15 20:09
sidenote: when break and replace 1 of the blocks it reforms filled to the level it had prior to deforming.

![image](https://user-images.githubusercontent.com/31905330/96180597-f3eb5600-0f32-11eb-9f33-9c82a5b32024.png)

**Comment by daddy77gaming** [comment] 2020-10-15 20:20
the server is on standard forge FYI

![image](https://user-images.githubusercontent.com/31905330/96181607-98ba6300-0f34-11eb-83d3-402a99941336.png)

**Comment by dvdmandt** [comment] 2020-10-16 13:19
Not sure if related, but I had some problems with TC warp spawning bats inside a max size iron tank with steam. After a while, the bats would go to rest on the ceiling of it or whatever, and if server was restarted while they were inside, the tank didn't reform. Breaking a block, killing any bats and replacing block would reform the tank with contents intact. That was probably on 2.0.5.1 though, regular GTNH server download. I'm thinking there might be other mods spawning entities, like lamps and similar spawning some form of light sources objects inside the multiblocks. I vaguely recall the Thaumcraft Arcane Lamp causing problems like that at some point for example..?

**Comment by daddy77gaming** [comment] 2020-10-17 22:51
I went today to space for the third time to test this out.. and indeed on return all RC multi's deformed.

**Comment by Impos913** [comment] 2020-10-18 08:20
> I went today to space for the third time to test this out.. and indeed on return all RC multi's deformed.
This happened to me too. It was a singleplayer world, I came back from moon and all my railcraft multiblocks were not formed. One of the iron tanks were for water and it was feeding my large boiler. Caused the explosion of my large boiler.

**Comment by boubou19** [comment] 2021-12-12 02:11
can't reproduce either in SP or in MP on 2.1.1.0

**Comment by Gateswong** [comment] 2022-05-08 00:11
![2022-05-07_17 08 46](https://user-images.githubusercontent.com/2586057/167276175-3e63f322-1b11-4c55-a475-4d78635da5d5.png)

As of the date of posting, this problem still exists on 2.1.2.3qf.

**Comment by YannickMG** [comment] 2022-07-07 18:38
If this is to be fixed, we'll need reliable reproduction steps. Even a save where the bug occurs after doing X action would be better than nothing.

**Comment by Connor-Colenso** [comment] 2022-08-14 01:35
I don't classify this as severe enough to justify a major bug label. This is a niche issue for those insisting on using RC multis into late game.

**Comment by BritishCynic** [comment] 2023-01-29 01:45
I've not seen this bug for quite some time, so I'm inclined to close this issue for now.

**Closed by BritishCynic** 2023-01-29 01:45 UTC
Labels: Type: bugMinor
