### ISSUE TITLE
Another two minor bugs

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#6273] opened 2020-06-14 00:44 UTC
~Rather simple and minor bug. The Heavy Duty Alloy Ingot T4 outputs four tiny piles of Ruridite dust when in reality, the cost to make the same Heavy Duty ingot requires four Osmiridium bolts.~ I realized this specific bug was in a different issue, whoopies.

Fine Ruridite wire created from BartWorks does not have a proper fluid extraction recipe, and thus, you cannot properly obtain a full ingot in the case you wished to fluid smelt back eight fine wires.

Certain fluids from BartWorks, most notably Rhodium Sulfate and a couple of others, do not properly condom to specific fluid output hatch mechanics; i.e. You output Chlorine and tell it to lock that specific fluid to Hatch 1#, obviously, it states that it will and does what you expect. However, if you tell Rhodium Sulfate or Acidic Osmium Solution to output in Hatch 2#, it will instead and most likely take Hatch 1# and cannot be forced to output in a different hatch. Another example would be screw driving a hatch filled with that specific fluid, however, it won't do anything or even give you a notification that the fluid locking was successful. This can simply be avoided by producing more EBF's to separate fluids or having pristine fluid management to avoid accidental auto-voiding of fluids.

**Comment by chochem** [comment] 2020-06-14 03:00
which version are you on? the first one sounds like a duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6107. It is supposed to be Ruridit. If it still isn't fixed on QF4, please comment there.

**Comment by SBAngel810** [comment] 2020-06-14 05:02
it's not fixed on QF4

**Comment by chochem** [comment] 2020-06-14 05:05
yeah Piky already wrote that in the other issue.

@Piky maybe you can change the title and make this issue about the other two bugs. or some dev might come by and close it as a duplicate :)

**Comment by Prometheus0000** [comment] 2021-03-21 19:57
@bartimaeusnek It's still not fixed.

**Closed** 2022-08-08 15:29 UTC
Labels: Type: bugMinor, Mod: BartWorks
