### ISSUE TITLE
Remove the Traheremagy tab and merge it with another, it's two researches and a waste of a tab.

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#9579] opened 2022-01-25 04:03 UTC
### Your GTNH Discord Username

Alastor's Game

### Your Pack Version

2.1.2.2

### Your Proposal

Why the fuck would y'all make a tab that's literally two crowbars?
<img width="454" alt="Screen Shot 2022-01-24 at 10 01 27 PM" src="https://user-images.githubusercontent.com/78517796/150908609-de5b394a-064a-4468-9b10-8bad9aacd7a1.png">
I went into creative to make sure it was literally two crowbars and sure enough. This is a fucking waste and should be merged.

<img width="368" alt="Screen Shot 2022-01-24 at 10 01 57 PM" src="https://user-images.githubusercontent.com/78517796/150908687-a02f6c27-5e1f-4e59-8710-e4a7d1704af7.png">

### Your Goal

Am I a joke to you?

### Your Vision

My vision is to not waste spaces in the thaumonomicon, even if it's an infinite book, on stupid shit like a 2 research tab full of crowbars, that's dumb as shit. Guys, just put it in artifice or some shit.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment] 2022-01-25 04:41
Got it, add fifty seven thousand crowbars in different colors each with different reseo

**Comment by Glease** [comment] 2022-01-25 07:49
It's a failure in MT scripts. Duplicate of #9538.

**Closed by Glease** 2022-01-25 07:49 UTC
Labels: Type: Suggestion, Status: Triage
