### ISSUE TITLE
Crash Caused by NEI

### ISSUE THREAD

**Issue by IncandescenceSy** [GTNewHorizons/GT-New-Horizons-Modpack#11730] opened 2022-10-25 17:01 UTC
### Your GTNH Discord Username

Incandescence~ ♡#8301

### Your Pack Version

2.2.3

### Your Server

SP

### Your Actions

I was simply looking at recipes with NEI when the game suddenly crashed, saying that the crash had been caused by NEI.
![image](https://user-images.githubusercontent.com/76633436/197836628-e0995668-f48f-429f-9ced-89f5948628b2.png)

### Crash Report

[crash_report.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9862409/crash_report.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment] 2022-10-25 17:28
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11531

**Closed by miozune** 2022-10-25 17:28 UTC
Labels: Type: Crash, Status: Triage
