### ISSUE TITLE
Steam Squasher & Grinder previews in NEI have too many input buses

### ISSUE THREAD

**Issue by FireWarrior2** [GTNewHorizons/GT-New-Horizons-Modpack#14353] opened 2023-08-28 16:12 UTC
### Your GTNH Discord Username

fire.warrior

### Your Pack Version

2.3.7

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Steam Squasher & Grinder previews in NEI will have proper amount of buses and structure casings.

### The Reality

Steam Squasher & Grinder previews in NEI have too many input buses.
![2023-08-28_19 08 22](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/18097458/b032ae7e-526e-418d-b11d-7099d3a313ad)
![2023-08-28_19 08 35](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/18097458/8f2e9cb3-fdc3-454e-bcc4-5d084a50c996)

### Your Proposal

Fix Steam Squasher & Grinder previews in NEI.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2023-08-28 16:17
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12504

**Closed by chochem** 2023-08-28 16:17 UTC
Labels: Type: bugMinor, Status: Triage
