### ISSUE TITLE
Solar Grade Silicon Ingot recipe missing

### ISSUE THREAD

**Issue by fiftycthulhu** [GTNewHorizons/GT-New-Horizons-Modpack#10686] opened 2022-07-11 23:12 UTC
### Your GTNH Discord Username

Mycroft Holmes#1618

### Your Pack Version

2.1.2.4-18-pre

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I was trying to cool a hot Solar Grade Ingot to make a plate for transistors. However, this is in HV before the Vacuum Freezer unlocks, so I need to use a chemical bath and coolant. However, this recipe is not valid for these ingots, so I have no way to cool them and thus no way to make transistors and therefore HV circuits.

### The Reality

However, this recipe is not valid for these ingots, so I have no way to cool them and thus no way to make transistors and therefore HV circuits.

### Your Proposal

Please either unlock the Vacuum Freezer earlier or add a chemical bath recipe for Hot Solar Grade Silicon Ingots.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2022-07-11 23:15
The transistor needed (raw) silicon plate in previous dev versions and should probably be reverted to that.

**Comment by Dream-Master** [comment] 2022-07-12 03:31
we not revert it back but if the siSG need a vacuum freezer we can add a bath recipe maybe or remove the hot ingot

**Comment by GlodBlock** [comment] 2022-07-12 03:33
just decrease its smelting temperature so it won't need vac freezer.

**Comment by Dream-Master** [comment] 2022-07-12 03:41
nope i increase it that the direct smelting recipe need hv and you get forced to use siO2 and all Quartz gives you now si

**Comment by chochem** [comment] 2022-07-12 22:52
caused by https://github.com/GTNewHorizons/NewHorizonsCoreMod/commit/73e2dae3f3732e6012bf9565de3df122319635b2

**Comment by Dream-Master** [comment] 2022-07-13 00:10
Please read the issue before do a wrong fix. Thanks

**Comment by chochem** [comment] 2022-07-13 00:46
> Please read the issue before do a wrong fix. Thanks

sorry about that. (but its better than nothing for now so that progression works) 
This should not stand in the way of a more thought out different fix.

> nope i increase it that the direct smelting recipe need hv 

I do not know what you mean by that. The smelting for raw silicon was removed completely while the Silicon Solar Grade Dust smelts at MV (120Eu/t). I guess you mean that it needs kanthal and should continue to do so?

So if it needs to be solar grade and solar grade needs to require kanthal (which apparently means it makes the hotingot), then a chem bath recipe would be best.

I dont know if I am happy with that though. This is quite a significant nerf and will make crafting of advanced circuits and then integrated processors (and up) a good bit more expensive and time consuming due to the smelting time of 227s in mv as well as the coolant. Even if OCed to HV its still 113s, around double that of kanthal.

So I would propose to not just add a chem bath recipe but also reduce smelting time&energy for solar grade silicon by 50%.

**Comment by boubou19** [comment] 2022-07-18 03:54
tagging this as bug major, since it simply breaks the progression

**Comment by boubou19** [comment] 2022-07-18 08:38
but you cannot make transistors

**Comment by chochem** [comment] 2022-07-18 08:41
not in dev18, but  you can with the merged fix ;)
this is just still open since dream prefers to change it for a different fix.

**Comment by boubou19** [comment] 2022-07-18 08:45
i'm not really a fan of that patch as it makes no sense it's just a ductape. So i'll just convert the hot ingots into ingots magically until it is fixed.

**Comment by boubou19** [comment] 2022-07-18 10:16
this still isn't the change Dream wanted so it stays open until it's fixed

**Comment by chochem** [comment] 2022-07-18 10:39
uh. I did *not* mean to do that, sorry.

**Closed** 2022-07-18 12:54 UTC
Labels: Type: bugMajor
