### ISSUE TITLE
2 server issues on eta

### ISSUE THREAD

**Issue by BHTAelitepwn** [GTNewHorizons/GT-New-Horizons-Modpack#6307] opened 2020-06-21 10:58 UTC
#### Which modpack version are you using?
the newly updated version: 2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
eta

#### What did you try to do, and what did you expect to happen?
Issue1: mytown invites do not show up. I have been using ./mytown invite <playername> and it confirms succesful invitation. However, the player does not actually receive the invitation. I do not think this is a player specific issue, as we tested this both ways (we invited each other to both our towns)

Issue2: stargate at spawn is not working

#### What happened instead? (Attach screenshots if needed)
<img width="612" alt="Screenshot 2020-06-21 at 12 18 24" src="https://user-images.githubusercontent.com/67225329/85222859-9d27a280-b3be-11ea-87df-7c390ea7dc70.png">

#### What do you suggest instead/what changes do you propose?

issue1: fix the plugin so we can invite players to towns again, might need some extra testing what exactly causes it. Might be the new version

issue2: As some other uses pointed out, simply taking the components out of the stargate computer at spawn and putting them back in should suffice in making it operational again.

**Comment by boubou19** [comment] 2020-06-21 11:00
are you or viljar290 close to a gt machine that is able to chunkload itself? those are known to bug the commands that interracts with other players. try it again when you'll be both at spawn

**Comment by BHTAelitepwn** [comment] 2020-06-21 11:03
@boubou19 We were in a chunk that contained a passive anchor, a personal anchor, 2 apiaries and some tin item pipes. Neither of us had one of those machines (I assume you mean ore drilling rigs for example) running at the time. We will try doing it in spawn later today, thanks for a possible fix

**Comment by repo-alt** [comment] 2020-06-21 11:18
Stargate computer was restarted last night. There is an explicit sign next to it saying what to do if it stops.

**Comment by Prometheus0000** [comment] 2020-10-13 00:11
Is issue 1 still a problem?

**Comment by boubou19** [comment] 2021-03-17 13:49
was not able to reproduce issue 1, so i'm closing this.

**Closed by boubou19** 2021-03-17 13:49 UTC
Labels: Server: Eta, Type: MP Game
