### ISSUE TITLE
The GTNH tab in the thaumonomicon is gone, and all the recipes aren't working.

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#9578] opened 2022-01-25 03:57 UTC
### Your GTNH Discord Username

Alastor's Game

### Your Pack Version

2.1.2.2

### Your Server

Mine

### Your Expectation

be able to make those brewing station things

### The Reality

I couldn't, the GTNH tab was fuckin gone
<img width="920" alt="Screen Shot 2022-01-24 at 9 56 35 PM" src="https://user-images.githubusercontent.com/78517796/150908146-b55e6163-2c3d-4fa3-9d06-b8a8072f70f1.png">
<img width="875" alt="Screen Shot 2022-01-24 at 9 56 44 PM" src="https://user-images.githubusercontent.com/78517796/150908154-91483df9-d536-4873-8d48-57eb9576cd67.png">

### Your Proposal

Please add it back?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment] 2022-01-25 04:40
This may be related to all the modweaker weirdness.

**Comment by Glease** [comment] 2022-01-25 07:48
Duplicate of #9538

**Closed by Glease** 2022-01-25 07:48 UTC
Labels: Type: bugMinor, Status: Triage
