### ISSUE TITLE
Outdated quest IV mixer HSSG

### ISSUE THREAD

**Issue by firendlyGhost** [GTNewHorizons/GT-New-Horizons-Modpack#10440] opened 2022-06-04 13:24 UTC
### Your GTNH Discord Username

Ghost#4022

### Your Pack Version

2.1.2.3qf

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Quest #1410 says i need an IV mixer for HHSG dust, that is not true its an EV recipe 

someone forgot to update this quest 

### The Reality

Quest    1410  is outdated
its in the IV tab right next to the IV hull

### Your Proposal

Quest is outdated, remove and replace with ev mixer in an EV quest or replace with another quest i guess

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment] 2022-06-04 13:48
Duplicate of #8790

**Closed by miozune** 2022-06-04 13:48 UTC
Labels: Type: bugMinor, Status: Triage
