### ISSUE TITLE
Chest / Super Buffers not compressing stacks

### ISSUE THREAD

**Issue by johnch18** [GTNewHorizons/GT-New-Horizons-Modpack#7741] opened 2021-04-02 06:27 UTC
If you are using the transfer X option with chest or super buffers, it only looks at each of it's internal slots individually. So it is possible to have a super buffer set to only out but X items with (X-1)*273 items in its inventory. I would suggest recycling the code [from here](https://github.com/GTNewHorizons/GT5-Unofficial/blob/6981d6370945d1e53c96508ddf541c6234383028/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_Hatch_InputBus.java#L117). This might also be a good thing to do for item pipes.

**Comment by yukieiji** [comment] 2021-08-10 23:39
SuperBuffer is still not sorted on my server(GTNH v2.1.1.0), does anyone else have the same issue?

**Comment by combusterf** [comment] 2021-08-18 11:07
It's not fixed on Delta either. While it does like to sort when interacted with, it doesn't do so when automated and both the chest and super versions will indeed still break under realistic ore processing conditions.
![image](https://user-images.githubusercontent.com/8459776/129887737-c34179ff-7fe4-4d50-9734-eb9fc15e9ffc.png)

**Comment by D-Cysteine** [comment] 2021-08-18 22:33
This should have been fixed by:
 * https://github.com/GTNewHorizons/GT5-Unofficial/pull/629

Can you check if your version of GT is older than that one (i.e. older than `5.09.37.07`)? Also, what do you mean by "will indeed still break under realistic ore processing conditions"? Is there a bug where an overloaded buffer won't work properly?

Also, just to confirm, did you try turning sort mode on (shift-right-click with soldering iron)? Note that the chat message output has a bug where it says "disabled" when sort mode is actually enabled, and vice-versa, if your version of GT5 is older than this one:
 * https://github.com/GTNewHorizons/GT5-Unofficial/pull/633

(you can check whether your version is older by looking for number formatting in tooltips; no formatting means older)

**Comment by combusterf** [comment] 2021-08-22 13:59
Stock 2.1.1.0 Shipped with gregtech 5.09.35.00, so we can reasonably conclude this was insufficiently fixed for the version listed.

**Comment by D-Cysteine** [comment] 2021-08-24 08:36
That version is quite old, so this issue might already be fixed then. I guess comment again on this if you see that the issue is still happening even with a recent version of GT?

**Comment by combusterf** [comment] 2021-11-22 09:09
This is now fixed on delta, which presumably means it will be fixed for future releases as well.

**Closed** 2021-11-22 09:15 UTC
Labels: Type: suggestion, Status: FixedInDev, Mod: GT
