### ISSUE TITLE
Gregtech Pulsating Iron Ingot wont turn into plate but EIO Ingot does

### ISSUE THREAD

**Issue by NyrZ** [GTNewHorizons/GT-New-Horizons-Modpack#17501] opened 2024-09-28 14:40 UTC
### Your GTNH Discord Username

nyrz

### Your Pack Version

nightly 675

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Trying to craft 1 pulsating iron plate bending machine using 1 pulsating iron ingot (Gregtech)

### The Reality

Wont craft 1 pulsating iron plate bending machine using 1 pulsating iron ingot (Gregtech) but works with 1 pulsating iron ingot (Ender IO)

### Your Proposal

fix recipe kek

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment] 2024-09-28 15:22
@NyrZ we work on ore dict/unification stuff before. is there any recipe you cant make with the change or is this just cosmetic?

**Comment by NyrZ** [comment] 2024-09-28 15:27
@Dream-Master well I literally can't make any pulsating iron plate unless I give myself the EIO version of the ingot so it can be annoying. It's working for Gregtech Electrical Steel tho so it's not an EIO related issue maybe it's just for Pulsating Iron I haven't tested much more otherwise

**Comment by chochem** [comment] 2024-09-28 20:01
unable to reproduce this, even when its the enderio ingot registering the recipes (based on the log entry)

**Comment by NyrZ** [comment] 2024-09-28 20:06
@chochem not home anymore can't really try some more I'll try again tomorrow or the day after tomorrow after restarting server. 

Maybe try to smelt a pulsating dust in an EBF instead of giving yourself the ingot and use the output ingot in bending machine? The issue might be from that ? I was using an LV bending machine btw but I don't think the voltage matters anyway

**Comment by NyrZ** [comment] 2024-09-29 16:59
@chochem I updated to nightly 678 and I still can't process my pulsating iron into plates. EIO version of the ingot does still work tho
![image](https://github.com/user-attachments/assets/4967fdb8-9007-4018-872e-ee16f37ff199)

**Comment by chochem** [comment] 2024-10-02 23:19
should be fixed by https://github.com/GTNewHorizons/EnderIO/pull/175

**Closed by chochem** 2024-10-02 23:19 UTC
Labels: Type: bugMinor, Status: Triage
