### ISSUE TITLE
Game crash after ajusting MC Funnel with EIO Wrench

### ISSUE THREAD

**Issue by QianhyNyaU** [GTNewHorizons/GT-New-Horizons-Modpack#10137] opened 2022-04-12 06:51 UTC
### Your Pack Version

2.1.2.1 personal Server

### Your Server

2.1.2.1 personal Server

### Your Actions

In a UW Garden world in a server,
Look at a downward-set **Minecraft Funnel**. (I was looking to the east)
With a **EIO wrench** adjust its direction and it pointed to the north.
... And then no further reaction by the game, I cannot move or look around.
Game crashed, the server had no problem.
Log in again. Before I could load the map where I got disconnected, the game crashed again.
The logs showed that I logged in successfully into the server before I load the map on my screen, which meant that I can do nothing.
The crash info of my PCL Minecraft Launcher showed that it was caused by **Waila**.

### Crash Report

[14:25:12] [Client thread/INFO]: Connecting to server ***************************
[14:25:31] [Client thread/INFO]: [CHAT] 反作弊MOD列表未配置, 请在后台使用/cac指令进行配置!
[14:25:31] [Client thread/INFO]: [CHAT] NyaaaaaU joined the game.
[14:25:31] [Client thread/INFO]: [CHAT] §2A magic bubble of protection appears...
[14:25:33] [Client thread/INFO]: [CHAT] §6=====================================================
[14:25:33] [Client thread/INFO]: [CHAT] §lWelcome to Gregtech: New Horizons §a2.1.2.1
[14:25:33] [Client thread/INFO]: [CHAT] §9The Quest Book has a shortcut key, check your keybindings
[14:25:33] [Client thread/INFO]: [CHAT] §9to remove conflicts.
[14:25:33] [Client thread/INFO]: [CHAT] §2New features include: Using cells on machine GUI tanks for
[14:25:33] [Client thread/INFO]: [CHAT] §2I/O, NEI having tabs at the top and multiple recipes on a 
[14:25:33] [Client thread/INFO]: [CHAT] §2page, Cooking for Blockheads addition, Logistics Pipes
[14:25:33] [Client thread/INFO]: [CHAT] §2addition, Tungsten change, glowy textures (your resourcepack
[14:25:33] [Client thread/INFO]: [CHAT] §2will need to be updated to do this), other texture work you
[14:25:33] [Client thread/INFO]: [CHAT] §2probably won't notice but still looks nice, quest changes, and a
[14:25:33] [Client thread/INFO]: [CHAT] §2whole bunch of other stuff, so check out the changelog.
[14:25:33] [Client thread/INFO]: [CHAT] §aPlease report bugs here:
[14:25:33] [Client thread/INFO]: [CHAT] §6https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/
[14:25:33] [Client thread/INFO]: [CHAT] §9Visit our discord at https://discord.gg/EXshrPV
[14:25:33] [Client thread/INFO]: [CHAT] §6=====================================================
[14:25:52] [Client thread/INFO]: [CHAT] 
[14:25:55] [Client thread/INFO]: [CHAT] [§1保持库存§r] 你的背包将在死亡后保存
[14:25:55] [Client thread/INFO]: [CHAT] [§1保持库存§r] 苦力怕不会炸毁方块
[14:26:36] [Client thread/INFO]: [CHAT] 欢迎, NyaaaaaU！
[14:26:36] [Client thread/INFO]: [CHAT] 现金余额: ￥1355
[14:26:36] [Client thread/INFO]: [CHAT] 现在时间: 14:25:192022-4-12
[14:26:36] [Client thread/INFO]: [CHAT] 在线人数: 13
[14:26:36] [Client thread/INFO]: [CHAT] 你没有新的邮件
[14:26:53] [Client thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException
	at net.minecraft.block.BlockHopper.func_149731_a(SourceFile:572) ~[aln.class:?]
	at net.minecraft.world.World.func_147447_a(World.java:1221) ~[ahb.class:?]
	at net.minecraft.world.World.func_72901_a(World.java:1029) ~[ahb.class:?]
	at mcp.mobius.waila.overlay.RayTracing.rayTrace(RayTracing.java:90) ~[RayTracing.class:?]
	at mcp.mobius.waila.overlay.RayTracing.fire(RayTracing.java:55) ~[RayTracing.class:?]
	at mcp.mobius.waila.overlay.WailaTickHandler.tickClient(WailaTickHandler.java:72) ~[WailaTickHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1047_WailaTickHandler_tickClient_ClientTickEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at cpw.mods.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:330) ~[FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2064) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) ~[bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment] 2022-04-12 06:53
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7918.

**Closed by Glease** 2022-04-12 06:53 UTC
Labels: Type: Duplicate, Type: Crash
