### ISSUE TITLE
Picking up water in a bucket crashed the game

### ISSUE THREAD

**Issue by spobb** [GTNewHorizons/GT-New-Horizons-Modpack#17514] opened 2024-09-29 23:36 UTC
### Your GTNH Discord Username

spobb

### Your Pack Version

2.7.0 beta1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

![2024-09-30_01 34 54](https://github.com/user-attachments/assets/ba53f09b-990f-4f4a-904d-1576f338c30b)
Tried to pick up this source block, I was also able to open up the world without any issues afterwards

### Crash Report

[crash-2024-09-30_01.22.12-server.txt](https://github.com/user-attachments/files/17181758/crash-2024-09-30_01.22.12-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2024-09-30 13:13
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15928

**Closed by chochem** 2024-09-30 13:13 UTC
Labels: Type: Crash, Status: Triage
