### ISSUE TITLE
EnderIO teleportation methods very often fails

### ISSUE THREAD

**Issue by FloatDoubling** [GTNewHorizons/GT-New-Horizons-Modpack#14515] opened 2023-09-14 23:06 UTC
### Your GTNH Discord Username

quitebased

### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

When I use EnderIO items with travel upgrade (The Ender, Dark Pick) or Staff of Traveling for tp to anchor I expect them to work flawlessly on every use.

### The Reality

Now teleport to EIO anchor very often fails, there is animation of sword swing (in case of The Ender) and nothing happens. Also when this happens, next message always appear in log:

[Server thread/WARN] [EnderIO]: Player com.mojang.authlib.GameProfile@69a3d9d5[id=0dcb83d8-355e-42c9-b321-3ac77eb5df42,name=Rearz,properties={},legacy=false] tried to tp without valid prereq.

### Your Proposal

Teleport to anchor should always work.

Also I guess it was either 1 or maybe both of these EIO pr's when it was broken, before update it worked flawlessly:

https://github.com/GTNewHorizons/EnderIO/pull/128

https://github.com/GTNewHorizons/EnderIO/pull/131

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by vovaksenov** [comment] 2023-09-15 06:51
Can confirm. Happens to me frequently as well (on 2.3.7).

**Comment by chochem** [comment] 2023-09-16 15:17
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14456

**Closed by chochem** 2023-09-16 15:17 UTC
Labels: Type: bugMinor, Mod: Ender IO
