### ISSUE TITLE
You can't make Witching Gadget's native ore clusters in 2.1.2.1 (you could in 2.1.2.0)

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#9351] opened 2022-01-03 22:12 UTC
### Your GTNH Discord Username

Alastor's Game

### Your Pack Version

2.1.2.1

### Your Server

SP

### Your Expectation

Be able to make native coal

### The Reality

couldn't make native coal, it just didn't work
<img width="733" alt="Screen Shot 2022-01-03 at 5 11 28 PM" src="https://user-images.githubusercontent.com/78517796/147985996-c0c5ffe3-afcf-4291-8db8-1aab45a89e10.png">
I checked this, and it didn't work with any other witching gadgets native ores. However, as noted, it did work in 2.1.2.0 so it must be a new glitch

### Your Proposal

Please fix? It's really nice for coal

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alastors** [comment] 2022-01-03 22:13
The recipe doesn't show up in nei either anymore when it did in 2.1.2.0. It doesn't work in the thaumatorium, which is very sad. I haven't tried a normal crucible yet tho

**Comment by bombcar** [comment] 2022-01-03 22:14
This is likely a zscripts to coremod shift change. Maybe the thaumbanababan whatever auto adds crucible recipes too Early?

**Comment by Dream-Master** [comment] 2022-01-03 22:16
it's fixed so far I remember. Will check again.

**Comment by Alastors** [comment] 2022-01-03 22:18
> it's fixed so far I remember. Will check again.

in a newer version than 2.1.2.1?

**Comment by Alastors** [comment] 2022-01-03 22:19
2.1.2.1-dev-test2 maybe?

**Comment by bombcar** [comment] 2022-01-03 22:20
That’s older. It would be in a jar from jenkins but not sure which one (probably coremod)

**Comment by bombcar** [comment] 2022-01-03 22:21
You could try copying the appropriate zscript from 2.1.2.0 but that’s highly unsupported

**Comment by Alastors** [comment] 2022-01-03 22:21
The normal Thaumcraft ones work, but it's just not the witching gadgets ones

**Comment by Runakai1** [comment] 2022-01-03 22:48
On another note, if you research the nano boots of travelling you can access the recipe via the Thaumonomicon but not via NEI

**Comment by PolkageistHS** [comment] 2022-01-03 23:11
> On another note, if you research the nano boots of travelling you can access the recipe via the Thaumonomicon but not via NEI

You can see the recipe if you check the empty nano boots.  The full boots don't show up in NEI.  Unfortunately the Thaumcraft NEI plugin is ARR so fixing it is a pita.

**Comment by PolkageistHS** [comment] 2022-01-03 23:28
Confirmed the witching gadgets native clusters stuff works in 2.1.2.0 and not 2.1.2.1.  Now to find out what changed...

**Comment by PolkageistHS** [comment] 2022-01-03 23:42
It works in the crucible but not the thaumatorium.  Very similar to #8095.  Nothing has changed in Witching Gadgets except for a fix to oilsands, so I'm not sure why it worked in 2.1.2.0 but not 2.1.2.1.

**Comment by PolkageistHS** [comment] 2022-01-03 23:46
Further testing:  it works in the thaumatorium with oreBasaltCoal but not any of the other variants.  Something's happening during the recipe mapping that's not supposed to happen; probably also why there's 7 different ore clusters to pick from, but only one ever works.

**Comment by Glease** [comment] 2022-01-04 07:57
Confirmed to be a regression from TC4Tweaks 1.4.8 crucible recipe lookup optimization. In that revision a hash map is introduced to cut O(n) lookup time to O(1). All these native ore cluster are colliding with each other when computing recipe hash, so only one of these ever would work. They were colliding before, but due to TC4 searches the whole recipe list sequentially, only the first registered one works (i.e. the base ore variant). This change made the resolution to consider the last instead due to later enties overriding previous ones.

Updating TC4Tweaks server side to [TC4Tweaks 1.4.12](https://www.curseforge.com/minecraft/mc-mods/tc4tweaks/files/3593362) should make it revert to the old behavior. 

In the long run we need to find a permanet fix for this collision problem though. Either I go patch TC4 to make the collision less likely or we change WG recipes to make it not collide.

**Comment by repo-alt** [comment] 2022-01-04 09:43
You should perhaps log collisions in that case. Also what kind of hash map it is, does it use hash code as a key? I mean usual hash map contract allows collisions (if values are comparable and distinct), it just degrades performance.

**Closed** 2022-01-04 10:16 UTC
Labels: Type: bugMinor, Type: Duct-Taped

**Comment by Glease** [comment] 2022-01-04 10:33
That hash code is essentially the same thing as assline's recipe hash.

**Comment by repo-alt** [comment] 2022-01-04 10:47
Ok, I looked at TC4Tweaks and you indeed use hash as a key. That is of course very efficient, but w/o any collision detection that kind of bugs is kind of inevitable.
