### ISSUE TITLE
Unknow crash

### ISSUE THREAD

**Issue by Petrik002** [GTNewHorizons/GT-New-Horizons-Modpack#16882] opened 2024-07-31 14:42 UTC
### Your GTNH Discord Username

Petřík#7373

### Your Pack Version

2.6.1.

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Actions

Randomly crashed after 1 hour of playing.. Happened to me before, so I tried to install modpack, which doesnt help.

### Crash Report

https://mclo.gs/qcl6LJW

[crash-2024-07-31_16.29.54-client.txt](https://github.com/user-attachments/files/16443384/crash-2024-07-31_16.29.54-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Petrik002** [comment] 2024-07-31 17:52
Meaby I found the reason why it's happened, I have low space on my SSD. If it wont crash in  a couple of hours I will remove this issue..

**Comment by Pxx500** [comment] 2024-07-31 18:09
I'm not sure if you did a backup already but this error is not yet solved, the only bandaid solution we have is [here ](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16728#issuecomment-2227331646)

duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16728

**Closed by Pxx500** 2024-07-31 18:09 UTC
Labels: Type: Crash, Status: Triage
