### ISSUE TITLE
Client sent ModularUI packet while server doesn't think player is opening ModularUI GUI

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#13428] opened 2023-05-05 15:39 UTC
### Your Pack Version

2.3.2

### Your Server

Private Server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

Which GUI was opened to spam this issue a few dozen times at once is unknown:
```java
[Server thread/ERROR]: Expected ModularUIContainer on server, but got appeng.container.implementations.ContainerInterface@26f5fdde
```
More debug here could be welcome, as there are various mods running into this issue, such as adventure backpacks under some specific conditions.

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment] 2023-05-06 12:26
This log indicates that server thinks player is opening non-ModularUI GUI, but client somehow sent widget update packet from ModularUI. I can't reproduce the issue by myself, so concrete steps to reproduce would be appreciated.

**Comment by Tommeh1** [comment] 2023-05-06 14:51
> This log indicates that server thinks player is opening non-ModularUI GUI, but client somehow sent widget update packet from ModularUI. I can't reproduce the issue by myself, so concrete steps to reproduce would be appreciated.

I require better debug in order to go so.

**Comment by miozune** [comment] 2023-05-06 15:17
I don't even see how it can happen, as well as where to put debug logging.

**Comment by firenoo** [comment] 2023-05-06 15:25
Can it happen if a player lags? i.e. client opens modularui, sends a widget, closes ui, then opens ae2 gui? or can it happen with multiple players sending packets?

**Comment by miozune** [comment] 2023-05-06 15:57
As long as packets arrives in correct order it shouldn't be an issue;
1. server receives packet of updating widget on MUI
2. server receives packet of closing MUI GUI
3. server receives packet of opening AE2 GUI

Also widget update packet won't be sent after player hits `E` or `esc` to close GUI, at least as far as I can tell from code and some test.

**Comment by firenoo** [comment] 2023-05-06 16:48
packets aren't guaranteed to arrive in order. if its a harmless error, do you think it should be suppressed?

**Comment by miozune** [comment] 2023-05-07 03:08
sure

**Closed** 2023-05-07 03:08 UTC
Labels: Type: bugMinor, Status: Can't Reproduce, Status: Triage, Mod: ModularUI
