### ISSUE TITLE
StructureLib NEI Display bug

### ISSUE THREAD

**Issue by xiPakuL** [GTNewHorizons/GT-New-Horizons-Modpack#12691] opened 2023-02-23 19:17 UTC
### Your Pack Version

2.3.11

### Your Server

Dedicated Self hosted

### Java Version

GraalVM 22 Java 19

### Type of Server

Vanilla Forge

### Your Expectation

![grafik](https://user-images.githubusercontent.com/91191200/221007596-32a7d822-9b5f-44ac-86b1-aafcd59f3f7c.png)
The multiblock should look something like this.

### The Reality

![grafik](https://user-images.githubusercontent.com/91191200/221007420-4d4af817-378f-44b2-89de-ac20e7792553.png)
The multiblock is bugged in NEI and looks like this.

### Your Proposal

Fix the structureLib, i had some other multiblocks from BartWorks where this happened too, but i can't seem to find them anymore.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2023-02-23 19:24
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12211

**Closed by chochem** 2023-02-23 19:24 UTC
Labels: Type: bugMinor, Status: Triage
