### ISSUE TITLE
Arcane terminal replace with stone terminated item in storage while crafting with Shift

### ISSUE THREAD

**Issue by berta24** [GTNewHorizons/GT-New-Horizons-Modpack#8730] opened 2021-10-24 19:08 UTC
### Your GTNH Discord Username

Berta24

### Your Pack Version

2.1.1.4

### Your Server

private server

### Type of Server

Multiplayer LAN

### Your Expectation

Crafting an item in the arcane terminal with Shift key pressed (to craft the entire batch) will result in crafting the item correctly but in the crafting terminal the terminated items will be repalced with stone 

### The Reality

https://cdn.discordapp.com/attachments/181078474394566657/901910203023388712/unknown_2021.10.24-21.06.mp4

### Your Proposal

leaving the space empty instead of placing stone 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment] 2021-11-14 15:17
So is this intended or not?

**Comment by repo-alt** [comment] 2021-11-14 15:26
It is intended but the author dropped the mod long ago, so we may do whatever we want. I actually kinda like the feature

**Comment by boubou19** [comment] 2021-11-14 15:28
Well then if it's not a bug i'm closing this. A new ticket should be made to discuss this behavior change if it's really needed.

**Closed by boubou19** 2021-11-14 15:28 UTC
Labels: Type: bugMinor, Status: Waiting for Feedback, Mod: Thaumic Energistics
