### ISSUE TITLE
Railcraft Fluid Boilers producing WAY more pollution than described when more than 1x1x2 multi. 

### ISSUE THREAD

**Issue by Hachuurui** [GTNewHorizons/GT-New-Horizons-Modpack#7255] opened 2021-01-06 18:04 UTC
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
gtnh.twpi.pw (dm me on discord if you want to be whitelisted. Dream knows how to reach me)
#
#### What did you try to do, and what did you expect to happen?
I updated the server to 2.1.0.0 and Pollution doesn't exponentially increase but instead matches description
#
#### What happened instead? (Attach screenshots if needed)
the Railcraft Fluid Boilers destroyed the world with pollution in minutes/hours.
#
#### What do you suggest instead/what changes do you propose?
Take a look at the code for RC Fluid boiler pollution. I discussed this with Dream in discord and he helped me get the pollution under control but I have to keep a UHV scrubber running next to it using creative constantly to keep it from hitting poison/acid rain levels of pollution in minutes. Even with those running the chunk with the 2 fluid boilers have a constant 3k pollution. My concern is that its calculating pollution per block in the multiblock instead of a flat rate.. If so, these boilers are producing 1k+/sec instead of the described 80/sec.. These boilers already do not produce much steam when compared to GT boilers, but these were supposed to be the step between coal and GT boiler... If anyone had these boilers running and updated their server, it would be destroyed in minutes/hours like mine was.

As for my particular case, I'm in the process of converting the power system to GT boiler. I'm more concerned about newer players who get caught in this trap, plus the fact that this does not seem like something that would be intended.

**Comment by alphaNOVAircraft** [comment] 2021-01-06 18:27
Duplicate of #7227

**Closed** 2021-01-06 19:07 UTC
