### ISSUE TITLE
Found that there is no kraft brown AE smart cable. 

### ISSUE THREAD

**Issue by bamik69** [GTNewHorizons/GT-New-Horizons-Modpack#6998] opened 2020-11-27 01:25 UTC
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Your own version of the server. Without making modifications to your build.
#
#### What did you try to do, and what did you expect to happen?
![2020-11-27_04 07 21](https://user-images.githubusercontent.com/22926983/100400654-57a38b80-3068-11eb-9109-c99397896a2d.png)

#
#### What happened instead? (Attach screenshots if needed)
Similar to this
![2020-11-27_04 07 42](https://user-images.githubusercontent.com/22926983/100400678-65591100-3068-11eb-9b09-3522c6c2d312.png)

#

**Comment by Prometheus0000** [comment] 2020-11-27 01:56
Duplicate of  #2439

**Closed by Prometheus0000** 2020-11-27 01:56 UTC
Labels: Type: duplicate

**Comment by repo-alt** [comment] 2020-11-27 07:37
As a workaround you may paint it in world

**Comment by bamik69** [comment] 2020-11-27 11:00
> Дубликат [№ 2439](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/2439)

I'm glad it's been known for a long time.



> As a workaround you may paint it in world

I can do without it for now. I'll wait for a stable update.

**Comment by GTNH-Afx237v7** [comment] 2021-05-26 06:47
fixed with https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/7953
