### ISSUE TITLE
StructureLib Config to place no Hatches at all

### ISSUE THREAD

**Issue by minecraft7771** [GTNewHorizons/GT-New-Horizons-Modpack#12439] opened 2023-01-30 11:10 UTC
### Your GTNH Discord Username

minecraft7771#0427

### Your Pack Version

2.2.0.0

### Your Proposal

Imo there should be a config in StructureLib to place no hatches at all when survival auto-place is used.

### Your Goal

This will prevent random hatch tiers to be placed.

### Your Vision

Easier multiblock building.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment] 2023-01-31 09:12
@cainiaojun This has actually been on the todo list since first revision of survival autoplace, just that I never found a reason to actually go implement it.

**Comment by miozune** [comment] 2023-02-07 11:39
Closing as duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11799

**Closed by miozune** 2023-02-07 11:39 UTC
Labels: Type: Suggestion
