### ISSUE TITLE
Routed Request Pipe (ProjectRed) see only 1 stack on drawers

### ISSUE THREAD

**Issue by DV666** [GTNewHorizons/GT-New-Horizons-Modpack#3393] opened 2018-08-03 05:16 UTC
#### Which modpack version are you using?
2.0.4.6
#
#### If in multiplayer; On which server does this happen? 
Test on SP map
#
#### What did you try to do, and what did you expect to happen?
Playing with ProjectRed Transportation for system storage and i see ProjectRed have some compabilities issue with Drawer Storage.
Work perfectly with Jabba but Drawer Storage is more cheap with Drawer Controller.

![Image1](https://image.ibb.co/dK45fe/2018_08_03_07_08_49.png)
![Image2](https://image.ibb.co/ksjGmK/2018_08_03_07_09_08.png)

#
#### What happend instead? (Attach screenshots if needed)
See only 1 glowstone stack instead 448 glowstone.
#
#### What do you suggest instead/what changes do you propose?
Checks ProjectRed versions => Last versions used.

I find this github post => [Routed Request Pipe #1072](https://github.com/MrTJP/ProjectRed/issues/1072)

MrTJP said "Closing due to this now being handled by capabilities." but i didn't know what he means by that.... any idea ? 

Maybe need just an API update... idk.

**Comment by alphaNOVAircraft** [comment] 2018-08-03 09:26
Duplicate of #3385

**Closed** 2020-07-21 13:19 UTC
Labels: bugMinor, duplicate
