### ISSUE TITLE
Mega EBF doesn't output to multiple buses, nor does it accept an ME output bus

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#10034] opened 2022-03-25 15:41 UTC
### Your GTNH Discord Username

Piky#6375 (181103507711983616)

### Your Pack Version

2.1.2.3qf

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

Have multiple output buses

### The Reality

It doesn't output to multiple buses, effectively voiding. It also doesn't output in an ME output bus

### Your Proposal

What broke it?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GTNHAfx237v7** [comment] 2022-03-25 15:42
Did you update GT5u manually? I’m on 2.1.2.3qf as well and my MBF works fine with ME output bus.

**Comment by ScriptedPiky** [comment] 2022-03-25 15:43
I haven't yet, but is it fixed on the latest GT5u? If so, probably should mark this as FixedInDev, heh

**Comment by Glease** [comment] 2022-03-27 15:55
Cannot reproduce on latest dev bartworks. Probably fixed by one of those MBF related PR.

**Closed by Glease** 2022-03-27 15:55 UTC
Labels: Type: bugMinor, Mod: BartWorks
