### ISSUE TITLE
Server Crash when trying to break GC Oxygen Collector with a GT Wrench

### ISSUE THREAD

**Issue by Ced1999** [GTNewHorizons/GT-New-Horizons-Modpack#15597] opened 2024-02-26 09:43 UTC
### Your GTNH Discord Username

ced0115

### Your Pack Version

2.5.1

### Your Server

Self Hosted Server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Actions

Trying to break the Galacticcraft Oxygen Collector with a Gregtech Wrench.
This seems to consistently cause the Server to crash

### Crash Report

[crash-2024-02-26_09.25.50-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14402631/crash-2024-02-26_09.25.50-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2024-02-26 10:02
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15195

**Closed by chochem** 2024-02-26 10:02 UTC
Labels: Type: Crash, Status: Triage
