### ISSUE TITLE
JABBA Hopper and Redstone Upgrades craftable, but unusable due to missing recipes.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#12796] opened 2023-03-05 05:54 UTC
### Your GTNH Discord Username

Abdiel Kavash#2431

### Your Pack Version

2.3.0-RC-2_(MMC)

### Your Server

Singleplayer

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

JABBA Hopper Upgrade applied to a barrel allows the barrel to automatically output items to any of the barrel's sides. To designate the side of the barrel to output from, a Hopper Facade should be applied to that side.

The Redstone Upgrade allows the barrel to emit a redstone signal when it is full. To designate a side to output redstone signal from, a Redstone Facade is applied.

### The Reality

The Hopper and Redstone Upgrades are craftable in GTNH, but the corresponding facades are not. If the facades are spawned via creative mode, the upgrades work correctly.

The upgrades are useless without the facades, as they will not output items or redstone signal from any side, and therefore do nothing.

### Your Proposal

Either both of the upgrades and facades should be craftable in survival, or neither of them.

Adding a crafting recipe for the Hopper Facade and Redstone Facade would allow more options in early game automation.

If there is some issue with these facades (maybe a dupe bug or something?), then crafting of the corresponding Upgrades should also be disabled, to avoid misleading the player into thinking that they can be used.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by xiPakuL** [comment] 2023-08-26 18:36
Bump, still a major issue

**Comment by bertcardinaels** [comment] 2023-12-17 13:44
Here is me with a hopper upgrade and then realizing I can't craft hopper facades: 😭

**Comment by hallucinogender** [comment] 2024-05-17 00:22
This is still a problem in 2.6.0, and still needs to be fixed by either adding the missing recipes as initially suggested here, or by making the unusable upgrades uncraftable in order to alleviate confusion caused by crafting the upgrades and being unable to use them.

**Comment by DaviCompai** [comment] 2024-06-02 19:06
still an issue

**Closed** 2024-10-21 19:18 UTC
Labels: Type: bugMinor, Type: New Recipe, Mod: JABBA
