### ISSUE TITLE
infinity chest crashes the server when items are pushed in it via ender io

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#8853] opened 2021-11-16 11:42 UTC
### Your GTNH Discord Username

boubou_19#2706

### Your Pack Version

2.1.1.4-qf2

### Your Server

Zeta

### Type of Server

Thermos

### Your Actions

![2021-11-16_12 38 40](https://user-images.githubusercontent.com/12850933/141979084-70ee0ab8-cb45-40f3-b027-b26c7ff580d5.png)
Just put an item in the compressed chest after having set the setup above

### Crash Report

```
Description: Exception in server tick loop

java.lang.ArrayIndexOutOfBoundsException: 243
	at wanion.avaritiaddons.block.chest.infinity.TileEntityInfinityChest.checkSlot(TileEntityInfinityChest.java:141)
	at wanion.avaritiaddons.block.chest.infinity.TileEntityInfinityChest.func_94041_b(TileEntityInfinityChest.java:136)
	at com.enderio.core.common.util.InventoryWrapper.func_94041_b(InventoryWrapper.java:92)
	at com.enderio.core.common.util.InventoryWrapper.func_102007_a(InventoryWrapper.java:106)
	at com.enderio.core.common.util.ItemUtil.doInsertItemInv(ItemUtil.java:387)
	at com.enderio.core.common.util.ItemUtil.doInsertItemInv(ItemUtil.java:375)
	at com.enderio.core.common.util.ItemUtil.doInsertItem(ItemUtil.java:325)
	at crazypants.enderio.conduit.item.NetworkedInventory.insertItem(NetworkedInventory.java:284)
	at crazypants.enderio.conduit.item.NetworkedInventory.insertIntoTargets(NetworkedInventory.java:245)
	at crazypants.enderio.conduit.item.NetworkedInventory.doTransfer(NetworkedInventory.java:193)
	at crazypants.enderio.conduit.item.NetworkedInventory.transferItems(NetworkedInventory.java:166)
	at crazypants.enderio.conduit.item.NetworkedInventory.onTick(NetworkedInventory.java:113)
	at crazypants.enderio.conduit.item.ItemConduitNetwork.doNetworkTick(ItemConduitNetwork.java:214)
	at crazypants.enderio.conduit.ConduitNetworkTickHandler.tickEnd(ConduitNetworkTickHandler.java:63)
	at crazypants.enderio.conduit.ConduitNetworkTickHandler.onServerTick(ConduitNetworkTickHandler.java:47)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_393_ConduitNetworkTickHandler_onServerTick_ServerTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:252)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:894)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693)
	at java.lang.Thread.run(Thread.java:748)
```

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by repo-alt** [comment] 2021-11-16 11:44
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8741

**Closed** 2021-11-16 11:44 UTC
Labels: Type: Crash, Status: Triage
