### ISSUE TITLE
OPTIMIZATION: Autocraft-Hatch

### ISSUE THREAD

**Issue by FoKuCNiK** [GTNewHorizons/GT-New-Horizons-Modpack#11673] opened 2022-10-18 11:21 UTC
### Your GTNH Discord Username

FoKuCNiK

### Your Pack Version

LAST

### Your Proposal

I propose to introduce the ME Autocraft-hatch. How it should work, I will try to describe below:

1) There is an entrance hatch for patterns in the multiblock.
2) How does the template work while in the hatch?

Take for example crafting in a multi-block furnace: [1x Iron Ore] = [1x Iron Ingot].

What does the template do when we order crafting [1x Iron Ingot]?
1. He places [1x Iron Ore] into the virtual hatch buffer (which is set in the multiblock) and then the multiblock starts processing this ore.
2. After smelting this ore into [1x Iron Ingot], it immediately enters the ME network.
3. This hatch should work great if crafting contains not only objects but also liquid.

I think this innovation can reduce the number of lags on servers by tens or hundreds of times.
This is just a sketch, if this idea is interesting, I can paint a similar concept down to the smallest detail and integrate with my own multi-block for these hatches.

### Your Goal

null

### Your Vision

null

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by FoKuCNiK** [comment] 2022-10-18 11:23
if something was slightly incomprehensible in what was written (please forgive Google translator)

**Comment by Glease** [comment] 2022-10-19 03:51
Duplicate of #10968

**Closed by Glease** 2022-10-19 03:51 UTC
Labels: Type: Suggestion, Status: Triage
