### ISSUE TITLE
Compact Fusion Energy Hatches Super Bugged

### ISSUE THREAD

**Issue by Jackol03** [GTNewHorizons/GT-New-Horizons-Modpack#15069] opened 2023-12-11 14:57 UTC
### Your GTNH Discord Username

Propainchan

### Your Pack Version

2.5.0 Beta 1 

### Your Server

Private Server

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Before updating to 2.5.0 Beta 1 I would only have one multi amp wireless energy hatch to power my compact fusions. Now they power fail with one multi amp wireless energy hatch. Spamming multiple wireless energy hatches (doesn't matter if it's multi amp or not) seems to make them not power fail anymore. It power failed a compact mk5 with a few 16384k uxv wireless energy hatches (only ones I had available at the time lol) which doesn't seem right at all.

### The Reality

Compact MK5 failed with one 64a uxv wireless energy hatch

### Your Proposal

Fix plz

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment] 2023-12-11 15:00
do they fail on world load / restart? or randomly?

**Comment by Jackol03** [comment] 2023-12-11 15:30
Seems to powerfail whenever I try to turn it on.

**Comment by chochem** [comment] 2023-12-11 18:03
probably caused by this last minute change where the author specifically states its not really tested but that got merged anyway. https://github.com/GTNewHorizons/GoodGenerator/pull/222

Should we just revert it and reconsider after stable?

**Comment by bombcar** [comment] 2023-12-11 18:17
Unless a simple fix can be seen in the code I’m for reverting

**Comment by boubou19** [comment] 2023-12-11 18:37
there  is still time before stable, so what i suggest is to list it as blocking for stable, and if no one has figured out in time why it bugs , we will just revert.

**Comment by HoleFish** [comment] 2023-12-12 07:28
every energy hatch accept 20A uev, so MK5 should fail with only ONE energy hatch i think

**Comment by Dream-Master** [comment] 2023-12-14 16:10
So is this a bug @HoleFish or a user error @Jackol03 ?

**Comment by GDCloudstrike** [comment] 2023-12-14 17:05
Each energy hatch being limited to 20A UEV is intentional behaviour, no matter if its a laser/multiamp hatch or not
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/93287602/164846f1-5936-4a66-8260-5c308a27fdae)

**Closed by GDCloudstrike** 2023-12-14 17:05 UTC
Labels: Type: bugMinor, Status: Triage
