### ISSUE TITLE
Chips not work

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#6434] opened 2020-07-24 05:41 UTC
#### Which modpack version are you using?
latest
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### What did you try to do, and what did you expect to happen?
https://drive.google.com/file/d/1Rty6q31c236UMyA1B0xrfs8VlduHBpKR/view?usp=sharing
also those chips work in the previous version
#
#### What happened instead? (Attach screenshots if needed)
Sorry for my poor expression
#
#### What do you suggest instead/what changes do you propose?
Fix it

**Comment by boubou19** [comment] 2020-07-24 06:47
can you double click on your nei search bar and search for a random item? because it will darken the slots where the searched item is missing, and by doing that you can see all the slots detected by the game. That way you can check if it's the slots that are missing, or if it's the slots that are not correctly placed on the gui's texture

**Comment by GTNH-Afx237v7** [comment] 2020-07-24 06:53
Duplicate of #6019 and #6276 
The slots for the chips cannot be accessed due to the NEI bookmark overlay. Mitch wanted to look at it, not sure if that ever happened. Slots will be accessible when you disable NEI via hotkey (usually O).

**Comment by Godelboard** [comment] 2020-07-24 22:51
Workaround:
- Pick up item in mouse cursor
- Left click and hold on a working slot
- Move mouse cursor to slot you want it, then release left click

**Comment by Dream-Master** [comment] 2020-07-24 23:11
Workaround 3: we need to find somone who can fix it.

**Closed** 2020-09-27 09:29 UTC
Labels: Mod: NEI, Type: duplicate, Type: visual
