### ISSUE TITLE
Jumping while wearing Boots of the Seasons kicks player from server or crashes client

### ISSUE THREAD

**Issue by norbby42** [GTNewHorizons/GT-New-Horizons-Modpack#15213] opened 2023-12-24 20:39 UTC
### Your GTNH Discord Username

Quackers#6418

### Your Pack Version

2.5.0

### Your Server

Private Dedicated

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Actions

1. Craft up the Boots of the Seasons (from Thaumic Boots) through Infusion
2. Equip the Boots of the Seasons
3. Jump
4. Alternate: Use either of the Module Jump/Module Speed keybinds

### Crash Report

Server crash stacktrace:

```
[24.12 15:29:09] [Server] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingEvent$LivingJumpEvent@6a67d0cc:
[24.12 15:29:09] [Server] java.lang.NullPointerException
[24.12 15:29:09] [Server] 	at thaumicboots.api.ItemBoots.isJumpEnabled(ItemBoots.java:86) ~[ItemBoots.class:?]
[24.12 15:29:09] [Server] 	at thaumicboots.events.BootsEventHandler.playerJumps(BootsEventHandler.java:89) ~[BootsEventHandler.class:?]
[24.12 15:29:09] [Server] 	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1272_BootsEventHandler_playerJumps_LivingJumpEvent.invoke(.dynamic) ~[?:?]
[24.12 15:29:09] [Server] 	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
[24.12 15:29:09] [Server] 	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
[24.12 15:29:09] [Server] 	at net.minecraftforge.common.ForgeHooks.onLivingJump(ForgeHooks.java:349) [ForgeHooks.class:?]
[24.12 15:29:09] [Server] 	at net.minecraft.entity.EntityLivingBase.func_70664_aZ(EntityLivingBase.java:1385) [sv.class:?]
[24.12 15:29:09] [Server] 	at net.minecraft.entity.player.EntityPlayer.func_70664_aZ(EntityPlayer.java:1626) [yz.class:?]
[24.12 15:29:09] [Server] 	at net.minecraft.entity.player.EntityPlayerMP.localJump(EntityPlayerMP.java) [mw.class:?]
[24.12 15:29:09] [Server] 	at api.player.server.ServerPlayerAPI.jump(ServerPlayerAPI.java:5411) [ServerPlayerAPI.class:?]
[24.12 15:29:09] [Server] 	at net.minecraft.entity.player.EntityPlayerMP.func_70664_aZ(EntityPlayerMP.java) [mw.class:?]
[24.12 15:29:09] [Server] 	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:333) [nh.class:?]
[24.12 15:29:09] [Server] 	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137) [jd.class:?]
[24.12 15:29:09] [Server] 	at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(SourceFile:63) [je.class:?]
[24.12 15:29:09] [Server] 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
[24.12 15:29:09] [Server] 	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
[24.12 15:29:09] [Server] 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
[24.12 15:29:09] [Server] 	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
[24.12 15:29:09] [Server] 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
[24.12 15:29:09] [Server] 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
[24.12 15:29:09] [Server] 	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
``` 

Client crash report:

[crash-2023-12-24_15.29.50-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13762786/crash-2023-12-24_15.29.50-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by norbby42** [comment] 2023-12-24 21:51
I was able to workaround this by adding the `tag` compound to my copy of the item using `/nbtedit item` from Server Utilities.  Once the tag is added, `/iteminhand` reports `ItemNBT: [{}]` and jumping no longer causes a crash/disconnect.

I'm guessing that TC isn't adding the tag compound to the item when it's crafted.

**Comment by Alastors** [comment] 2023-12-25 04:40
Already know the cause of this, already know how to fix it, already been reported multiple times, wrong repo to report this.

duplicate of: https://github.com/Alastors/ThaumicBoots/issues/29

I’m on vacation, I come back the 6th, I’ll have it fixed sometime after that. Craft your seasonal boots into the Christmas boots in the meantime

**Closed by Alastors** 2023-12-25 04:40 UTC
Labels: Type: Crash, Status: Triage
