### ISSUE TITLE
Missing over 20 Storage drawers tipe recipes

### ISSUE THREAD

**Issue by Vernam** [GTNewHorizons/GT-New-Horizons-Modpack#6500] opened 2020-08-12 17:01 UTC
#### Which modpack version are you using?
2.0.9.0
#
#### What did you try to do, and what did you expect to happen?
i wanted to craft some Acacia drawers
#
#### What happened instead? (Attach screenshots if needed)
 I found that some of the recipes are not available. There are recipes in NEI, but there are not enough slots in the chisel to fit all types of drawers
#
#### What do you suggest instead/what changes do you propose?
the idea to chisel one drawer tipe to another is interesting, but i don't understand how to fix this... Maybe somehow add slots to all chisels or add there new pages? Now u cant scroll list of drawers. Maybe, for some drawers - return the recipes back ( for example, vanilla, thaumcraft and Natura, if this will be  enough). Of course, this is a small thing , but sometimes you need a drawer of a specific color and type, at the moment more than 20 types are not available.

**Comment by leagris** [comment] 2020-08-12 17:05
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6380

**Closed by leagris** 2020-08-12 17:05 UTC
Labels: duplicate
