### ISSUE TITLE
Flotation Cell Regulator takes incorrect amount of materials

### ISSUE THREAD

**Issue by FireWarrior2** [GTNewHorizons/GT-New-Horizons-Modpack#16323] opened 2024-05-20 17:45 UTC
### Your GTNH Discord Username

fire.warrior

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Flotation Cell Regulator will take 4 stacks of materials, as written in NEI.

### The Reality

Flotation Cell Regulator takes incorrect amount of materials.
I used ZPM energy hatch and 2 input buses: one for sod. eth. xant. and another for milled sphalerite. 
Only 1.5 stacks (96 items) instead of 4 (256 items) were taken by machine.
![2024-05-20_20 11 52](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/18097458/b708d65a-a23c-46b2-a7d4-dd64726789c2)

### Your Proposal

Honestly, better make this as feature than fix (decrease amount from 4 to 1.5 stacks).
Moreover (because line consumes too much energy and takes a lot of time, even for ZPM tier), it will be better to lower recipes tier, decrease recipes time or even increase amounts of materials processed.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by HoleFish** [comment] 2024-05-20 17:50
Probably a duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15606

**Comment by chochem** [comment] 2024-05-20 19:24
pretty sure it is, yes. but let us know in case if its still a problem in 2.6.0.

**Closed by chochem** 2024-05-20 19:24 UTC
Labels: Type: bugMinor, Status: Triage
