### ISSUE TITLE
Game crash when trying to remove item filter cover from an item pipe

### ISSUE THREAD

**Issue by ivanpu** [GTNewHorizons/GT-New-Horizons-Modpack#10052] opened 2022-03-27 18:18 UTC
### Your Pack Version

2.1.2.0

### Your Server

SP

### Type of Server

Single Player

### Your Actions

After understanding that my setup from #10038 will not work, but also realizing that Project Red chips are gates by lasers... I've tried to pull the stone dust from the output chest into the barrel by item pipes.
Conveyor did not work, so I've tried the item filter (aka "filtered conveyor cover") - both did not want to extract the dust.
So I've decided to dismantle it (right click with GT crowbar) and the client crashed.
After starting the client again the cover is in my inventory due to the magnet (it dings right before the crash).

Steps to reproduce:
0. Start with chest (diamond one in my case) and barrel above it, similar to how I had it in #10038 
1. Put item pipes behind the chest to the barrel above (2 total, small tin item pipes), and make them all connect (C shape)
2. Move the chest to a side by using a dolly
3. Put "item cover (import)" on the bottom pipe (facing the block where chest should be)
4. Use screwdriver (I've used electrical (LV), made from steel) to change it to whitelist
5. Right click it with stone dust to set the filter
6. Place back the chest (bu using a dolly) into its "hole"
7. Wait half minute or more to realize that the dust is still not migrating to the barrel
8. Right click with a crowbar on side of the pipe with the X area facing the chest
9. Hear a ding when "Item Dislocator" fetches the cover into your inventory
10. Observe how the launcher (PolyMC in my case, FOSS fork of MultiMC) presents you the crash log

### Crash Report

https://0x0.st/oqTx.txt

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment] 2022-03-27 18:26
Duplicate of .... a lot of issues. Fixed already in later versions. Again, I strongly suggest you to upgrade to at least 2.1.2.1.

**Closed by Glease** 2022-03-27 18:26 UTC
Labels: Type: Crash, Status: Triage

**Comment by ivanpu** [comment] 2022-03-27 19:07
1. I couldn't find similar issues... oh, wait... missed that there are more than one page of results, sorry...
2. I got an impression that x.x.x.0 are the stable versions, and the rest are development. Am I wrong?

**Comment by Glease** [comment] 2022-03-27 19:09
2.1.2.0 is the sole exception. It was the worst stable release I had ever seen. We haven't decided how things should be going forward, but we have already determined that one stable is defintiely not enough, and keep adding qf to version string is less than ideal...

**Comment by ivanpu** [comment] 2022-03-27 19:15
Ok, thanks for explanation.
Is it mentioned in the discord what are the recommended versions for playing? (and also the changelogs, when I think about it...)
I think it may be worth it to dig out what were my credentials for that app in this case.

**Comment by TwoTailedFox** [comment] 2022-03-27 19:16
If testing releases are necessary, perhaps they should be marked as "RC" (Release Candidate" so their integrity can be verified prior to a full release of that version number.

**Comment by Glease** [comment] 2022-03-27 19:28
Well no one actually use it if we mark it as rc. Major servers (officials included) only use stable releases only (for good reasons). Some of them will even postpone update until the new release has proven itself on stable. Every dev version is supposed to be tested, except we still have bugs in stable.
