### ISSUE TITLE
Crash while exploring 

### ISSUE THREAD

**Issue by IonKarl** [GTNewHorizons/GT-New-Horizons-Modpack#11993] opened 2022-12-16 02:36 UTC
### Your GTNH Discord Username

Lin Jie#0503

### Your Pack Version

2.2.3

### Your Server

SP

### Type of Server

None

### Your Actions

just exploring world 

### Crash Report

[crash-2022-12-15_21.21.01-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10242168/crash-2022-12-15_21.21.01-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2022-12-16 02:41
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11640

**Closed by chochem** 2022-12-16 02:41 UTC
Labels: Type: Crash, Status: Triage
