### ISSUE TITLE
Issue on Java 20 where items move from inventory after using the mouse wheel

### ISSUE THREAD

**Issue by BritishCynic** [GTNewHorizons/GT-New-Horizons-Modpack#14964] opened 2023-11-29 17:17 UTC
### Your GTNH Discord Username

britishcynic

### Your Pack Version

GTNH-2023-11-29+239

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

The backpack should be openable but without any interference in the player's inventory

### The Reality

I use the mousewheel to scroll between hotbar cells; if I mousewheel up, and then right-click to open a Forestry backpack with 15 slots, it removes one of a stack from Row 1, Cell 5, and deposits it in an available slot, starting from Row 2, Cell 7 in the inventory, and will use empty cells goes right if cells from then are occupied (and then down to Row 3, Cell 1 if Cells 7, 8 and 9 in row 2 are occupied; if all cells are occupied from Row 2, Cell 7 onwards, including all of Row 3 and Row 4, it'll deposit in the next free cell from Row 1, Cell 1 onwards). If I mousewheel down, and then right-click to open a Forestry backpack with 15 slots, it'll remove such an item from that new other stack and add it to the middle cell in the top row (but does nothing if that cell is empty).

This does not occur with Backpacks from Backpack Edited for Moddednetwork, or 45-bag Forestry bags. It does happen with Gold Chests and Iron Chests as well; after using Mousewheen Down, it will either remove an item from your chest's inventory from Row 7, Cell 5 in Gold Chests (Row 6, Cell 5 in Double Vanilla Chests or Iron Chests), or put one back if Mousewheel Up is used prior to opening the chest.

When Mousewheel Down is used, and then the inventory UI is opened, it places one of the item in the top middle cell in the crafting grid. This means that when the inventory is closed, that item is then dropped in the world.

### Your Proposal

This does not occur in Java 8, so I'm inclined to think that this is behaviour specific to the Java 11+ version. Something is happening when the mousewheel is moved that is then causing a further interaction in the inventory screen when it's next opened on whatever cell the mouse cursor is positioned on when the UI opens.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment] 2023-12-14 17:14
User can't reproduce it anymore.

**Comment by eigenraven** [comment] 2023-12-14 17:28
@boubou19 it doesn't happen on java 8 but does happen on modern java with lwjgl3ify

**Comment by boubou19** [comment] 2023-12-14 17:29
he asked me to close it because he couldn't reproduce it, but if you have a way to spot the bugs we can let this open

**Comment by eigenraven** [comment] 2023-12-14 17:29
Ah you should've mentioned this was based on a discord message

**Closed by eigenraven** 2023-12-14 17:29 UTC
Labels: Type: bugMinor, Status: Triage
