### ISSUE TITLE
GUI disappears when looking with holo visor on at a chest (or other inventory) with a magic map in it

### ISSUE THREAD

**Issue by dgealow** [GTNewHorizons/GT-New-Horizons-Modpack#16291] opened 2024-05-16 02:38 UTC
### Your GTNH Discord Username

@droideka30

### Your Pack Version

2.6.0

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Looked at a chest, that had a magic map in it, with the holo visor on. Expected to see the popup of everything in the chest, and be able to open it and interact with the contents as normal.`

### The Reality

All GUI/HUD elements disappeared. Could still open the chest, and move things around (or moreso, drop them on the floor), but without being able to see what I was doing since there was no visible chest GUI

### Your Proposal

Fix this bug I guess? it's really funny for about 30 seconds but then it gets pretty annoying, so yeah I think you should probably fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by ReaganAR** [comment] 2024-05-16 04:40
Duplicate of #16123 

Should be fixed if you update [to the most recent version of holoinventory](https://github.com/GTNewHorizons/HoloInventory/releases/download/2.4.9-GTNH/holoinventory-2.4.9-GTNH.jar)

**Closed** 2024-05-21 01:40 UTC
Labels: Type: bugMinor, Status: Triage
