### ISSUE TITLE
Drawer controller quest description is wrong

### ISSUE THREAD

**Issue by 110101001** [GTNewHorizons/GT-New-Horizons-Modpack#10366] opened 2022-05-20 23:17 UTC
### Your GTNH Discord Username

wpc#8101

### Your Pack Version

2.1.2.3

### Your Server

SP

### Type of Server

Open To LAN

### Your Expectation

The drawer controller has a range of 4 blocks, so the quest book should also tell players that its range is 4 blocks.

### The Reality

According to the quest book, the drawer controller has a range of 12 blocks.

### Your Proposal

Change the radius in the quest "Controlling your drawers"description to 4.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment] 2022-05-21 03:14
Duplicate of #9603

**Closed by miozune** 2022-05-21 03:14 UTC
Labels: Type: bugMinor, Status: Triage
