### ISSUE TITLE
LSC explodes when there is only 1 uhv(or uhv+) capacitor inside(no other capacitor at all) and turn wireless on

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#13524] opened 2023-05-18 06:00 UTC
### Your GTNH Discord Username

LEO_PREMIUM#3437

### Your Pack Version

2.3.4 nightly

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

it does not explode.

### The Reality

i did a test, the only difference between this two is that the top one has one ev capacitor. After they both did a wireless transfer to the wireless network, both ones successfully did the transfer but the lower one exploded.
![QQ截图20230517224518](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/61d8df82-d41d-414d-abd4-a3403e380aea)
![QQ截图20230517224440](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/1a49fdc0-da80-4346-a7c4-3cbfc8219d48)
![QQ截图20230517224743](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/4d8ba977-77de-45db-9e3d-efb8677b746d)

### Your Proposal

dear dev help, thx. 

if it's hard to fix, i recommend add a line to the tooltip or quest book saying don't do this, so that they will not loss their first uhv capacitor.

i do know that there is an issue about lsc explosion in #12620, but i do not know if they are actually the same bug.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment] 2023-05-18 06:57
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12620
there you can also see the current work around

**Closed by minecraft7771** 2023-05-18 06:57 UTC
Labels: Type: bugMinor, Status: Triage
