### ISSUE TITLE
2.0.9.1a and above Bug List

### ISSUE THREAD

**Issue by ScriptedPiky** [GTNewHorizons/GT-New-Horizons-Modpack#6714] opened 2020-09-28 02:38 UTC
If you have any listed bugs found and **not resolved** both 2.0.9.0 & 2.0.9.1 and above, please put them or edit them inside of this post. Mark the ones as listed off if they're fixed (and linked to the fix preferably). The ones I listed were found on Zeta.

- [x] Items inputted into the **Multi-Smelter** with an output over one (e.g. Borosilicate Glass Block that outputs nine ingots) will only output one ingot total.
- [x] **Raw "SDHC-120" Alloy** (5345#) has no recipe and cannot be crafted. (9.1a exclusive?)
- [x] Latest Kekztech version has considerable problems with voiding fluids in the **TFFT** among many other things; occurred in Sampsa's base and was found by Darkstar1712. 
- [ ] From @Rakdarian "Kekztech reinforced warded jars randomly void their aspects, and lose their labels"
- [x] Loading the **Io dungeon boss** (and presumably other GalaxySpace bosses) instantly crashes the game/server if the entity is loaded in any form.

**Comment by Rakdarian** [comment] 2020-09-28 02:39
Kekztech reinforced warded jars randomly void their aspects, and lose their labels

**Comment by Dream-Master** [comment] 2020-09-28 05:56
ok we can backdate to kekztech 0.46

**Comment by Dream-Master** [comment] 2020-09-28 05:57
@bot356 dind' t you fix the multi smelter ?

**Comment by Dream-Master** [comment] 2020-09-28 05:58
Glowredman forgot maybe this recipe since galaxy space script was removed.

**Comment by glowredman** [comment] 2020-09-28 06:59
That is a possibility, especially because Raw SDHC-120 is not a GalaxySpace item

**Comment by Dream-Master** [comment] 2020-09-28 11:51
it's a core mod item

**Comment by ScriptedPiky** [comment] 2020-09-30 05:57
Added Rak's issue and a serious issue involving a crash and soft-lock by spawning in GalaxySpace's Io ghast boss on Zeta (will need to wait until Dream gets a log of the crash), and presumably more of GalaxySpace's bosses that can crash upon loading them.

**Comment by Dream-Master** [comment] 2020-09-30 09:01
[crash-2020-09-30_07.52.48-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5304272/crash-2020-09-30_07.52.48-server.txt)
[crash-2020-09-30_07.42.03-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5304274/crash-2020-09-30_07.42.03-server.txt)

**Comment by botn365** [comment] 2020-09-30 09:44
yep the multie smelter can be marked as fixed

**Comment by ScriptedPiky** [comment] 2020-09-30 10:31
I couldn't get the multi smelter fix to load on my end at all; always crashing with `java.lang.NoSuchFieldError: dirt` being shown (the crash file is in #zeta-dev). Was this crash fixed?

**Comment by botn365** [comment] 2020-09-30 10:39
no idea what coused that i just rebuilded the jar and testet on my own gtnh instense nothing i did on the multie smelter code could cous that problem

**Comment by bartimaeusnek** [comment] 2020-09-30 10:47
@ScriptedPiky Obfuscation problem, youre most likly using a deObfs version in an Obfs enviroment

**Comment by Prometheus0000** [comment] 2020-11-02 23:56
Items 1,2 and 5 (spawn egg worked) are fixed in 2.0.9.2b dev. Was the TFFT fixed, I see a commit from bot about it? I don't know how to reproduce, so I can't check it.

**Comment by Prometheus0000** [comment] 2020-11-03 18:37
- https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/pull/6893
- Uranium tube assembler recipe not ingame, did you forget to add the updated version?
- The notification about the farm change is also not ingame. Again, did you forget to add the updated version?

**Comment by Prometheus0000** [comment] 2020-11-05 21:29
For 2.0.9.2d dev

The above 3 issues are solved, but the U-tube CA recipe doesn't use ender eye. https://github.com/GTNewHorizons/GT5-Unofficial/pull/339
TT ATs aren't exploding any more either.

**Comment by botn365** [comment] 2020-11-05 21:32
add to the list that tesla towers are curently roken as well bass knows of it and is working on fixing it

**Comment by Prometheus0000** [comment] 2020-11-05 21:34
The one that doesn't have a recipe or proper texture?

**Comment by botn365** [comment] 2020-11-05 21:35
there is no ticket for it but it wont feed energy in machines with rich tesla cover

**Comment by Prometheus0000** [comment] 2020-11-05 21:40
Do you mean the weapon one or the wireless power one?

**Comment by Alexdoru** [comment] 2020-11-28 23:49
On 2.0.9.3.a.dev #7014

**Closed** 2020-12-27 01:18 UTC
Labels: Mod: Kekztech, Status: TODO, Type: Crash, Type: reminder
