### ISSUE TITLE
world crashing into main menu due to world generation

### ISSUE THREAD

**Issue by henrimps** [GTNewHorizons/GT-New-Horizons-Modpack#17741] opened 2024-10-23 19:55 UTC
### Your GTNH Discord Username

henrimps

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

walking on the twilight forest, if i get close to a naga courtyard?(saw it on the crash report) the world disconnects and i get sent to the main menu.
i can only get back to the world after restarting the game + decreasing my render distance(my thought was that if i didn't load the chunk i could get in the world). Although this allows me to get back in the world it's hard to avoid a chunk i don't know exactly where it is.

### Crash Report

https://mclo.gs/UK9glZ5

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by FourIsTheNumber** [comment] 2024-10-23 19:56
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16353 and approximately five billion others. Update twilight forest mod here https://github.com/GTNewHorizons/twilightforest/releases/download/2.6.12/TwilightForest-2.6.12.jar

**Comment by Lyfts** [comment] 2024-10-23 19:57
![s](https://github.com/user-attachments/assets/d9286e8a-10d1-493c-b13b-6c59d3cc2440)
Searching "Twilight Forest" or something similar on the issue tracker results in about 50 issues identical to this one. 

Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16353 and many others.

**Closed by FourIsTheNumber** 2024-10-23 19:56 UTC
Labels: Type: Crash, Status: Triage
