### ISSUE TITLE
Quests do not update in book on clients

### ISSUE THREAD

**Issue by Joakim432710** [GTNewHorizons/GT-New-Horizons-Modpack#13024] opened 2023-03-25 04:03 UTC
### Your Pack Version

2.3.1

### Your Server

private server

### Java Version

Java 19

### Type of Server

Open To LAN

### Your Expectation

Since updating to 2.3.x quests update weirdly. Players will receive the notification that the quest has been completed, but when opening the book the quest has not updated and can not be claimed. Running bq_admin default load will update the player's questbook progress once, but if he then completes the quest the book is not updated to reflect the completed quest or any other further quests he completes unless the command is re-run again. Behaviour persisted even after completely erasing quest progress both with bq_admin reset all and by deleting the relevant quest files in /World.

### The Reality

The quests do not update on the client-side book.

### Your Proposal

The quests should update correctly as they did in 2.2 and prior

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2023-03-25 11:13
you are wrong. its not 2.3.x. stable is fine, just the dev is broken.

duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12994

**Closed by chochem** 2023-03-25 11:13 UTC
Labels: Type: bugMinor, Status: Triage
