### ISSUE TITLE
GTNH crashes on startup.

### ISSUE THREAD

**Issue by Prismie** [GTNewHorizons/GT-New-Horizons-Modpack#10111] opened 2022-04-07 21:01 UTC
### Your GTNH Discord Username

Prismie#4096

### Your Pack Version

2.1.2.3

### Your Server

SP

### Type of Server

Single Player

### Your Actions

I set my modpack to open using Azul Zulu JRE 8.60.0.21 (x86 64bits). Then I put 4GB RAM on it and added these JVM arguments: -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:+AlwaysPreTouch

Then it crashes when I'm almost finishing my startup. I don't have time to fix the problems, my computer is bad and it takes a lot to open a modpack.

### Crash Report

[crash-2022-04-07_17.45.12-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8446452/crash-2022-04-07_17.45.12-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment] 2022-04-08 00:35
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10085.

To fix, replace logistics pipes jar in your mods folder with this one: https://github.com/GTNewHorizons/LogisticsPipes/releases/download/0.9.4.5.5/logisticspipes-1.7.10-0.9.4.5.5.jar

**Comment by Glease** [comment] 2022-04-08 00:36
If you just cannot find the old jar. Don't worry, just adding that download will do.

**Closed by Glease** 2022-04-08 00:35 UTC
Labels: Type: Crash, Status: Triage

**Comment by Prismie** [comment] 2022-04-09 00:24
> If you just cannot find the old jar. Don't worry, just adding that download will do.

Alright. I did that (didn't find the old mod), now it doesn't even launch.
[crash-08.04.22-21.20.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8455892/crash-08.04.22-21.20.txt)
