### ISSUE TITLE
fresh install issues ??

### ISSUE THREAD

**Issue by mightydanp** [GTNewHorizons/GT-New-Horizons-Modpack#7302] opened 2021-01-12 23:46 UTC
#### Which modpack version are you using?
2.1.0.0qf1
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?
installed fresh version from curse forge and it to work
#
#### What happened instead? (Attach screenshots if needed)
install fresh, advanced solar panels jar was corrupt and after re-downloading the jar from the mod site. pressed play and got this error in error log crashing game. https://pastebin.com/L6hdc8ei
#

**Comment by GTNH-Afx237v7** [comment] 2021-01-28 09:59
Does it work now? Reproducible crash?

**Comment by mightydanp** [comment] 2021-01-30 00:24
i havent  been able to check

**Comment by boubou19** [comment] 2021-02-24 20:45
I'm gonna close this as it seems to be random corruption while downloading the pack. Feel free to reopen it if it is still happening, but then please add the way you downloaded the pack.

**Closed by boubou19** 2021-02-24 20:45 UTC
