### ISSUE TITLE
Mushroom stew bug

### ISSUE THREAD

**Issue by nick1wasd** [GTNewHorizons/GT-New-Horizons-Modpack#11883] opened 2022-11-26 19:08 UTC
### Your GTNH Discord Username

Nick1wasd#9175

### Your Pack Version

2.2.3

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

Eat a stack of more than one Mushroom Stew, I expected the stack to decrement by one and return one wooden bowl.

### The Reality

The unite stack went away, I received one meat shank of food, and one wooden bowl

### Your Proposal

Fix the error so the stack decrements by one instead of being entirely consumed

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment] 2022-11-27 07:15
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9908

**Closed by miozune** 2022-11-27 07:15 UTC
Labels: Type: bugMinor, Status: Triage
