### ISSUE TITLE
Thermal Cloth quest requires Enchanted Fabric but there's no recipe that uses it.

### ISSUE THREAD

**Issue by Darkstar1712** [GTNewHorizons/GT-New-Horizons-Modpack#6158] opened 2020-05-25 17:38 UTC
#### Which modpack version are you using?
2.0.9.0-beta3
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
The Thermal Cloth quest(1462) requires Enchanted Fabric but the recipe for Thermal Cloth instead uses Woven Cotton.
![Thermal Cloth Quest](https://user-images.githubusercontent.com/34458535/82833362-aef85180-9eb5-11ea-8a7a-cd7629202d7d.png)
![Thermal Cloth](https://user-images.githubusercontent.com/34458535/82833370-b1f34200-9eb5-11ea-938d-f901aed26736.png)

**Comment by Dream-Master** [comment] 2020-05-25 17:42
yea questbook need a change.

**Comment by Prometheus0000** [comment] 2020-06-03 03:49
Isn't this bug the other way around? #5159 Somehow the thermal cloth stopped using the enchanted cloth for some reason (checked ingame with RC1).

**Comment by botn365** [comment] 2020-06-03 03:57
no dream changed the recipe so it doesent use thaumcraft

**Comment by chochem** [comment] 2020-06-03 03:57
dream confirmed on discord its an intended change.

**Comment by Prometheus0000** [comment] 2020-06-03 04:00
'I change thermal armor recipe because I thought put thaumcraft in us a bad idea'
I don't know what that's supposed to mean though? Dream, when you wake up maybe you could explain better?

**Comment by botn365** [comment] 2020-06-03 04:05
it means 
i changed the thermal armor recipe becous i tought that puting thaumcraft in it is a bad idea

**Comment by Prometheus0000** [comment] 2020-06-03 04:12
Yeah, but why would it be a bad idea is what I want to know. Especially when there's an issue about adding it to the other thermal padding, which is the opposite of removing it. Which dream said ok to.

**Comment by botn365** [comment] 2020-06-03 04:13
1 of them is becous thaumcraft is arr

**Comment by Dream-Master** [comment] 2020-06-03 06:17
cotton is a replacement to find another material. Maybe I need to add some nylon or some other synthetic item

**Comment by Prometheus0000** [comment] 2020-06-03 06:23
I listed a bunch of fabrics in #5494 if you want ones to use.

**Comment by shawnbyday** [comment] 2020-06-05 20:02
Also the portions are off. It has you gather 96 Aluminium Foil and 96 Meteoric Iron Strings but that is only enough to make 12 Thermal Cloth. Maybe double the amount needed to collect for the quest to reflect the correct amount?

Also each piece of padding also takes a certain amount of Meteoric Iron String (total of 24 additional). Maybe add that to the total too?

Total needed for 24 Thermal Cloth is:

- 192 Aluminium Foil
- 192 Woven Cotton
- 216 Meteoric Iron String

Maybe worth adding a recipe that uses Thaumcraft Enchanted Fabric too if people want to make it more efficiently? Maybe not on that.

**Comment by Prometheus0000** [comment] 2020-06-13 13:42
? In QF4 they add up to 24 TC (no additional MI string, I don't remember them having it before either), and each uses only 8 of each material, so it's 192 for all of them.

**Comment by Prometheus0000** [comment] 2020-06-13 13:47
NM, looked the uncrafting recipe instead.

**Closed** 2020-09-21 21:07 UTC
Labels: FixedInDev, Quest change
