### ISSUE TITLE
No recipe for Iron Cap.

### ISSUE THREAD

**Issue by Idiocy42** [GTNewHorizons/GT-New-Horizons-Modpack#13603] opened 2023-06-03 00:25 UTC
### Your GTNH Discord Username

Diolas

### Your Pack Version

2.3.3

### Your Server

private server

### Java Version

Java 20

### Type of Server

Don't know

### Your Expectation

Trying to craft Iron capped wooden wand.  No recipe for Iron Cap.

### The Reality

No recipe for Iron Cap.

### Your Proposal

Add a recipe for Iron Cap.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2023-06-03 00:30
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13549

**Closed by chochem** 2023-06-03 00:30 UTC
Labels: Type: bugMinor, Status: Triage
