### ISSUE TITLE
Magic Apiary has no improvements with centi-vis

### ISSUE THREAD

**Issue by richardhendricks** [GTNewHorizons/GT-New-Horizons-Modpack#4681] opened 2019-06-13 15:03 UTC
When testing various bee housing, discovered Magic Apiary doesn't improve at all with centi-vis. It draws it, shows the indicator on the GUI it is using it, but shows no improvements or differences. Need to debug.  We already have our own fork.

https://github.com/GTNewHorizons/MagicBees

**Comment by richardhendricks** [comment] 2019-06-13 15:03
Also appeared that Frames didn't have much effect either in terms of boosting output.

**Comment by Glease** [comment] 2020-04-24 18:04
Cannot reproduce this in 2086fix2. Did someone fix this and forget to close?

**Comment by Dream-Master** [comment] 2020-04-24 18:47
@Glease i update magic bees from krypton fork. Maybe he fixed it ?

**Comment by Glease** [comment] 2020-04-24 18:53
I can see a 2016 commit  GTNewHorizons/MagicBees@275f03ccbaeef02fd44bea19e360394e407c428b that fixed a similar (or perhaps identical) problem. Maybe that's the fix.

**Comment by Dream-Master** [comment] 2020-04-24 18:59
@Glease 
https://github.com/GTNewHorizons/MagicBees/commits?author=KryptonCaptain

**Comment by Glease** [comment] 2020-04-24 19:14
Then it is not fixed by krypton. I think it might be the test's fault, not magic apiary's. The math of bee keeping logic is just as well known as ic2 crop keeping logic, i.e. urban myth and outdated info makes up for bulk of the search result.

Just to be sure, we could ask some other community member to conduct the same test on latest dev pack.

FYI this is how I did the test:

1. Prepare a pure Doctoral queen.
2. Put it in a magic apiary without vis apiary booster.
3. Wait and see how many combs are produced. Use a ZPM WA to speed up the process. 
4. Do step 3 again but with a valid apiary booster and a aer node.

Without booster it's 30 comb for the entier lifespan. With booster it's 76 comb. So I think the booster definitely does have an impact.

There are multiple points that could easily make the test invalid, or interpret the test result in a wrong way:
1. Supply peridito centi vis. This will cut the lifespan of queen by half, so the total comb production will be halved. Combined with the production boost, the total comb production will be identical to that w/o a booster.
2. Observe and see the drop occur at a seemingly constant interval. This is true for all bee housing, frames, speed modifier. The speed/production boost merely changes the drop rate, not interval.
3. Use a bee speicies whose base drop rate is already high, e.g. 60-ish or so. The drop rate will already be capped at 100% with fastest, so any frame/bee housing can't affect it positively anyway.

**Comment by Glease** [comment] 2021-02-25 11:11
Anyone else who has been experiencing this? If not I think we can safely close it.

**Comment by Glease** [comment] 2021-04-06 14:05
Closing for now since I can't reproduce this in my tests.

**Closed by Glease** 2021-04-06 14:05 UTC
Labels: Mod: Thaumcraft, Type: Bees, Type: bugMinor
