### ISSUE TITLE
Remove Lubricant quest requirement on MV Energy hatch

### ISSUE THREAD

**Issue by Phillip-May** [GTNewHorizons/GT-New-Horizons-Modpack#11803] opened 2022-11-09 05:59 UTC
### Your GTNH Discord Username

hibber22#4257

### Your Pack Version

2.2.3

### Your Proposal

Remove LV lube quest as a forced prerequisite on the MV energy hatch

### Your Goal

The requirement is mute given that it's impossible to get that into MV without lubricant and it only serves to punish players who chose to use a distillery and creosote to obtain lubricant

### Your Vision

Polish/Quality of life improvement

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment] 2022-11-12 17:47
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8308

**Closed by chochem** 2022-11-12 17:47 UTC
Labels: Type: Duplicate, Type: Suggestion, Type: Quest Change
