### ISSUE TITLE
Dimethylbenzene conversion does not work

### ISSUE THREAD

**Issue by TwoTailedFox** [GTNewHorizons/GT-New-Horizons-Modpack#10659] opened 2022-07-07 21:31 UTC
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.4-17-dev-test

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I have been informed by Chochom that on previous dev pack versions, Dimethylbenzene was supposed to convert to 1,2 Dimethylbenzene when the world was loaded

### The Reality

I loaded a world directly from 2.1.2.3qf into .4-17 and no such conversion took place.

### Your Proposal

This should probably be corrected. I lost 12,000,000 mB in the conversion process when my world loaded.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment] 2022-07-08 10:35
will be fixed in https://github.com/GTNewHorizons/GT5-Unofficial/pull/1062

**Comment by chochem** [comment] 2022-07-08 11:16
I dont understand what you mean @GlodBlock. dev17 already includes the chem standardization changes. (that is more likely to be the cause than the fix but I dont know). unless you mean some commit after dev17? but I dont see anything in that direction.

**Comment by GlodBlock** [comment] 2022-07-08 11:20
it includes some chemical material name fix. the commit has not been pushed to the branch yet.

**Comment by chochem** [comment] 2022-07-08 11:21
ok 👍

**Comment by GlodBlock** [comment] 2022-07-09 14:47
fixed in https://github.com/GTNewHorizons/GT5-Unofficial/pull/1062

**Closed by GlodBlock** 2022-07-09 14:47 UTC
Labels: Type: bugMinor, Status: Triage
