### ISSUE TITLE
Opencomputer Microchips making

### ISSUE THREAD

**Issue by Hyperic88** [GTNewHorizons/GT-New-Horizons-Modpack#4714] opened 2019-06-18 11:14 UTC
#### Which modpack version are you using?
2.0.7.5
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
Trying to make OC microchips T1, even the quest says you can use all three tiers of MV circs aka goodcircuits it seems that only the basic one works according to NEI

![image](https://user-images.githubusercontent.com/14223368/59677833-22381480-91cb-11e9-9426-95d3e37330ab.png)

#
#### What happened instead? (Attach screenshots if needed)
Nothing, ive put materials into the machine and nothing, even tried to swap transistors for SMD version
![image](https://user-images.githubusercontent.com/14223368/59677774-ef8e1c00-91ca-11e9-8dbd-c3f6c897a50e.png)

#
#### What do you suggest instead/what changes do you propose?
Check the recipe / add all three circuits to be usable

**Comment by Smeany** [comment] 2019-08-19 23:23
Same Problem with Tier 3 microchips. It somehow only works for the Tier 2 microchip.

**Comment by repo-alt** [comment] 2019-12-25 20:49
Duplicate of https://github.com/GTNewHorizons/NewHorizons/issues/5154 (well, actually backwards, but some discussion/investigation is there)

**Comment by Prometheus0000** [comment] 2020-10-29 02:01
Recipes appear to be here: https://github.com/GTNewHorizons/NewHorizonsCoreMod/blob/27aef7321ee870bb84a4cce03a6c32f259213c2e/src/main/java/com/dreammaster/gthandler/GT_MachineRecipeLoader.java#L2605

**Comment by boubou19** [comment] 2021-09-26 17:03
looks like it's addressed with: https://github.com/GTNewHorizons/GT5-Unofficial/commit/f172d60252ac1b95eda343ebc84b1b9b25ef73bf ?

**Comment by Glease** [comment] 2021-09-26 17:52
Yes.

**Closed by Glease** 2021-09-26 17:52 UTC
Labels: Type: oredict, Mod: OC

**Comment by GTNH-Colen** [comment] 2021-09-26 22:44
After a very, very, VERY long time we can finally mark this fixed.
