### ISSUE TITLE
A Hopper BUG

### ISSUE THREAD

**Issue by Alipay1** [GTNewHorizons/GT-New-Horizons-Modpack#9253] opened 2021-12-23 10:35 UTC
### Your GTNH Discord Username

Alipay#3745

### Your Pack Version

2121

### Your Server

SP

### Your Expectation

Trying to use hopper.

### The Reality

![VA9Q1E4Z5G1I~65X@8T$2WI](https://user-images.githubusercontent.com/82697713/147227442-15c77b10-778c-4569-b121-8588d4c0b1c6.png)
Coal in drawer(I'm using Chinese Simplified)
![RRI$WIT4)L$R781A1WN22TG](https://user-images.githubusercontent.com/82697713/147227551-be81db5f-56af-4175-9ad4-40a4b823294e.png)
Redwood and redwood bark in hopper
![ZV2U~2(_N WM 0IKG 2EJUN](https://user-images.githubusercontent.com/82697713/147227615-1a0f95a0-2044-4756-b7db-b014eac2eb9e.png)
I took half a stack of Redwood, coal started disappear

### Your Proposal

When there is a drawer contains something, a hopper placed under the drawer filled 5 slots by 5 stacks of items.
If I take like half a stack of items in hopper now, the items in drawer will go disappear.(Also when the hopper is not full, take half a stack is just a sample)
The items in drawer disappear quicker if the item I took can not be added by another hopper, if some hopper add the item I took the rate of disappear will slower.
*Have not test if other item pipes or AE output bus effect the item disappear rate.
*The hopper connected to a 'small tin item pipe'
*People in QQ group told me to submit a issue

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment] 2021-12-23 10:36
Duplicate of #7778

**Closed by Glease** 2021-12-23 10:36 UTC
Labels: Type: bugMinor, Status: Triage
