### ISSUE TITLE
Golem recipes doesn't show on nei

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#7892] opened 2021-05-01 20:58 UTC
#### Which modpack version are you using?
2.1.0.6b
#
#### If in multiplayer; On which server does this happen? 
zeta
#
#### What did you try to do, and what did you expect to happen?
When i click R on a golem recipe, it doesn't show up, even though i've already unlocked its research
#
#### What happened instead? (Attach screenshots if needed)
![2021-05-01_17 56 17](https://user-images.githubusercontent.com/57275066/116794867-d2088980-aaa6-11eb-888b-92ec73a0bdd0.png)
![2021-05-01_17 56 23](https://user-images.githubusercontent.com/57275066/116794869-d339b680-aaa6-11eb-8d9a-84d983bbf2f8.png)

**Comment by Prometheus0000** [comment] 2021-05-01 21:25
It's not just golem recipes, it's most of the crucible recipes being wonky in nei. You can see it from U of the block though. I think there was similar problems for the infusion recipes?

**Comment by maniifestantes** [comment] 2021-05-01 21:54
yeah, i can only see the recipe of the aer infused seed, even though it shows all of them when i see the seeds uses on the infusion

**Comment by jesuseduardo90** [comment] 2021-11-29 03:45
yeah i actually was going to make a new issue report but this is pretty much the same thing.

"thauminite nugget" i cant see them with "r" even if i use "u" with thaumium_ingots.
 I can make it appear by using "u" in iron_ingot and then "u" in thaumiun_ingot

**Comment by bombcar** [comment] 2021-11-29 12:59
@D-Cysteine any chance you could what might be causing this? Perhaps one of the NEI “hide” layers we have? Or the thaum unhiding not working?

**Comment by D-Cysteine** [comment] 2021-11-30 12:27
I don't know much about it, but it's probably a bug in the Thamcraft NEI handler. Unfortunately, it looks like that is closed source:
 * https://github.com/EmanueleGiannuzzi/Thaumcraft-NEI-Plugin

This issue looks related:
 * https://github.com/EmanueleGiannuzzi/Thaumcraft-NEI-Plugin/issues/26

Not sure how easy it would be to fix. We'd probably have to look at the decompiled code to figure out what the issue is. It does look like TimeConqueror did some extension of that plug-in; we may be able to do something similar to fix this:
 * https://github.com/GTNewHorizons/TCNEIAdditions/blob/master/src/main/java/ru/timeconqueror/tcneiadditions/nei/arcaneworkbench/ArcaneCraftingShapedHandler.java

Also it looks like this also happens for *some* wand (also sceptre, staff) crafting: you can view craft recipes with 'U' on an ingredient, but you can't view craft recipes with 'R' on some wands. E.g. warpwood, blood.

**Comment by miozune** [comment] 2022-06-02 17:13
Fixed by https://github.com/GTNewHorizons/TCNEIAdditions/pull/5

**Closed by miozune** 2022-06-02 17:13 UTC
Labels: Mod: NEI, Mod: Thaumcraft
