### ISSUE TITLE
Mega Oil Cracker not check second slot in quad hatch if in first slot has not enough liquid for recipe.

### ISSUE THREAD

**Issue by lordIcocain** [GTNewHorizons/GT-New-Horizons-Modpack#14095] opened 2023-07-28 23:53 UTC
### Your GTNH Discord Username

lord_cocain

### Your Pack Version

2.3.5

### Your Server

private server

### Java Version

Java 19

### Type of Server

Vanilla Forge

### Your Expectation

When slot has liquid, but not enough liquid for recipe it work with next slot etc.

### The Reality

It just stop checking other slots. 
Also if first slot empty it check other slot.
Also regular oil cracking unit working fine with quad input.

### Your Proposal

After it find that in slot not enough liquid for recipe it should check next one.

also, same, but not same
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13809

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2023-07-28 23:54
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13809

**Closed by chochem** 2023-07-28 23:54 UTC
Labels: Type: bugMinor, Status: Triage
