### ISSUE TITLE
Crash When Trying to Write in a Recipe in the Universal Wireless Terminal

### ISSUE THREAD

**Issue by cainiaojun** [GTNewHorizons/GT-New-Horizons-Modpack#13972] opened 2023-07-17 00:24 UTC
### Your GTNH Discord Username

Cainiaojun

### Your Pack Version

2.3.4

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Actions

1.Open your universal wireless terminal, turn to Pattern mode.
2.Use your NEI and find a Electrical Implosion Compressor.
3.Click the "?" to add your recipe automatically to your wireless pattern terminal.
4.Enjoy your crash!

### Crash Report

[crash-2023-07-17_08.11.08-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12065426/crash-2023-07-17_08.11.08-client.txt)
[crash-2023-07-17_08.12.32-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12065427/crash-2023-07-17_08.12.32-client.txt)
[crash-2023-07-17_08.13.13-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12065428/crash-2023-07-17_08.13.13-client.txt)
[crash-2023-07-17_08.15.46-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12065429/crash-2023-07-17_08.15.46-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by TheEpicGamer274** [comment] 2023-07-17 00:27
duplicate of #12949

**Closed by TheEpicGamer274** 2023-07-17 00:27 UTC
Labels: Type: Crash, Status: Triage
