### ISSUE TITLE
Rendering crash with every Gregtech / GT Addon mod

### ISSUE THREAD

**Issue by seventh-june** [GTNewHorizons/GT-New-Horizons-Modpack#17451] opened 2024-09-24 17:59 UTC
### Your GTNH Discord Username

neura#2020

### Your Pack Version

Beta 2.7.0 release 1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

Crash has happened trying to access low pressure steam furnace and PBF

### Crash Report

https://mclo.gs/TftV5TV

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by grimly** [comment] 2024-09-25 20:25
Hello,

I got this issue as well.

I think I had my `shift` key pressed.
Looking at some code, you trust all modded items to give you back a modifiable `aList` line list when granted an opportunity to print their description : https://github.com/GTNewHorizons/GT5-Unofficial/blob/master/src/main/java/gregtech/api/items/MetaBaseItem.java#L272-L273

I wouldn't know where to start setting a debugger to check my theory but a misbehaving item implementation might be causing this crash.

**Comment by Lyfts** [comment] 2024-09-25 20:33
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17401

**Closed by Lyfts** 2024-09-25 20:33 UTC
Labels: Type: Crash, Status: Triage
