### ISSUE TITLE
Iron Cap Recipe missing 2.3.3

### ISSUE THREAD

**Issue by desagas** [GTNewHorizons/GT-New-Horizons-Modpack#13410] opened 2023-05-02 07:07 UTC
### Your Pack Version

2.3.3

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

Tried making initial wand for thaumcraft. There is no recipe for iron caps in thaumcraft in version 2.3.3, yet, in 2.3.0 there was a recipe.

### The Reality

There is currently no recipe for any wand cap that can get you into thaumcraft, yet alone to complete the initial quest.

### Your Proposal

Re add the recipe that was removed from the scripts Thaumcraft-Thaumaturge file, as it was.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by kuba6000** [comment] 2023-05-02 09:02
Fixed in
https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/575
https://github.com/GTNewHorizons/NewHorizonsCoreMod/releases/tag/2.1.1

**Closed by kuba6000** 2023-05-02 09:02 UTC
Labels: Type: bugMinor, Mod: GTNH Core

**Comment by desagas** [comment] 2023-05-02 16:44
Now that this is fixed, is it safe to update this mod to 2.1.1, and the subsequent GT5 Unofficial 5.09.43.08? Or, should I wait until there is an official beta or release?

**Comment by chochem** [comment] 2023-05-02 16:48
no you cant just update gt to 43.x, wont work. coremod I dont know

**Comment by desagas** [comment] 2023-05-03 20:41
This is a problem ... as I am going through, I now notice that whomever was porting the scripts to the core mod has actually delete several of the 'recipes additions,' while leaving in the 'remove recipes' lines from a lot of the script files, and then failed to include the new core mod in the release that includes the recipe changes. This means that many recipes are missing or incorrect. Currently, this means that the entire Thaumcraft line is inaccessible without op or cheats enabled. While the pack is still playable, it is not playable as intended. I am seeing a few more issues open up now with similar issues. Perhaps this version should not be listed as beta?

**Comment by chochem** [comment] 2023-05-03 20:42
you mean kuba I guess. But you gotta be way more specific, 'a lot' doesnt help. might also just moved to somewhere else.

**Comment by desagas** [comment] 2023-05-03 20:49
Or, sorry, I meant the thaumcraft scrips are missing almost every recipe addition, while leaving in almost every remove recipe. The files are almost half the size, or less in some cases.

Specifically so far I have compared 2.3 and 2.33 for thaumcraft-thaumatirge, alchemist and basics.

Sorry for the confusion.

**Comment by OperativeLoop** [comment] 2023-06-14 02:58
Looks like this is still not working in 2.3.4 BETA.

**Comment by OperativeLoop** [comment] 2023-06-14 13:48
I'm not sure what I'm doing wrong to not see it, I created a fresh instance in MMC with the GT_New_Horizons_2.3.4_Java_8.zip then loaded up a fresh world, searched for iron wand cap, and tried to hit the recipe hotkey on it, and nothing happens.

**Comment by chochem** [comment] 2023-06-14 13:49
from some other people on discord with the same problem I learned it comes from a mistake while updating. you left the old script folder in. see https://gtnh.miraheze.org/wiki/Installing_and_Migrating

**Comment by OperativeLoop** [comment] 2023-06-14 14:07
I created a brand new instance, so no old script folder. Is there supposed to be something in the scripts folder? The 2.3.4 downloads don't have a scripts folder.

**Comment by OperativeLoop** [comment] 2023-06-20 22:47
Is it just me with this issue? I can still reproduce this issue with a brand new instance and brand new world.

**Comment by desagas** [comment] 2023-06-21 00:10
The newness of the world is irrelevant, what people are asking you is whether or not there is something in your scripts folder? Anything at all, not in the world folder, in the pack folder? Can you post screen shots, screen shots of the folder? Are you positive you used the 2.3.4 download, perhaps you accidently re did a 2.3.3 instance, not knowing it. Did you maybe download a 2.3.4-nightly version listed on the releases instead of a ... it is really hard to trouble shoot with you without knowing or seeing from your experience.

All I know is this, in a fresh instance, brand new, copying saves FROM my old instance to the new instance, the pack and recipes for this work perfectly fine?

Are you sure you are playing in the new instance? And not on the old one? I know it can be confusing and it is very easy to mix up which one you are loading, especially when copy and pasting, it happens to me all the time.

**Comment by desagas** [comment] 2023-06-21 00:13
AHHH, wait ... there is an IRON WAND CAP from GT++, and an IRON CAP from Thaumcraft. Iron Cap is what you use, not Iron Wand Caps!!

**Comment by OperativeLoop** [comment] 2023-06-21 00:24
wow, that's it, I can see the regular iron cap recipe. maybe the other item with no recipe can be removed.

**Comment by desagas** [comment] 2023-06-21 00:27
@chochem we found the issue, well, an issue.
