### ISSUE TITLE
Eating Causes Crash (Only Apples So Far)

### ISSUE THREAD

**Issue by BEEF-Gaming** [GTNewHorizons/GT-New-Horizons-Modpack#14059] opened 2023-07-25 05:19 UTC
### Your GTNH Discord Username

ShrooMoo

### Your Pack Version

2.3.5

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Actions

Eat apple. Reloading the save, apple is gone, so it appears the crash occurs when finishing said apple. 

### Crash Report

[crash-2023-07-25_01.15.27-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12157353/crash-2023-07-25_01.15.27-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by serenibyss** [comment] 2023-07-25 05:21
Duplicate of #14033, and was fixed in https://github.com/GTNewHorizons/Nutrition/releases/tag/0.0.3

**Closed by serenibyss** 2023-07-25 05:21 UTC
Labels: Type: Crash, Status: Triage
