### ISSUE TITLE
Massive TPS Drop on generating new Chunks (Possible GC Planets only?)

### ISSUE THREAD

**Issue by Blade8895** [GTNewHorizons/GT-New-Horizons-Modpack#7212] opened 2021-01-01 18:04 UTC
#### Which modpack version are you using?
2.1.0.0

#
#### If in multiplayer; On which server does this happen? 
Dedicated Server - Vanilla GTNH Setup
I7 4790k
32GB Ram
SSD
Debian 10
JDK8 

Start Params: 
-Xmx12288M -XX:ReservedCodeCacheSize=256M -Dsun.io.useCanonCaches=false -XX:CompileThreshold=1500 -XX:MaxTenuringThreshold=15 -XX:+UseBiasedLocking -Xverify:none -XX:UseSSE=4 -XX:UseAVX=2 -XX:+OptimizeStringConcat -XX:+UseFastAccessorMethods -Xrs -XX:+UseCompressedOops -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:+AggressiveOpts

tried " -Dforge.forceNoStencil=true " too
#
#### What did you try to do, and what did you expect to happen?
The Server runs smooth af before the update to 2.1.0.0. (Prior 2.0.9.0) 
but now when we generate new Chunks on GC Planets (not tested on overworld... had already generate huge tiles ^^) the TPS goes from stable 20 to 0 and comes after 2-8 seconds back to 80+ to keep up and come back to 20. and thats not after generating many chunks for a short time... it happens after 2 or 3 chunks....

#
#### What happened instead? (Attach screenshots if needed)
no screenshot needed ;P

#
#### What do you suggest instead/what changes do you propose?
-/-

i will help as far as i can.

~ Blade8895

**Comment by KiloJoel** [comment] 2021-01-01 18:06
Try disabling natura retrogen (config/Natura.cfg) and see if the issue persists

**Comment by Blade8895** [comment] 2021-01-01 18:44
no change at all.... sorry

**Comment by AtomicGrog** [comment] 2021-01-03 03:44
Have seen similar on Ross128b after server has been running an hour or so, gets to the point where players timeout. This was pre-2.1.0.0 update though, not been back since because it's an unmanageable scenario.

Symptoms were pretty obvious, server fails to generate new chunks as you move around into new areas, visually you see the edge of a cliff as it fails to render. TPS basically goes infinite and you are disconnected some 30 seconds later. Trying to move slowly doesn't resolve the issue, once server is in this state it stays that way until restart.

**Comment by Blade8895** [comment] 2021-01-03 13:54
exactly this happened! on the same planet!

but we had 12hours auto restart and had this problem since the day we updated to 2.1.0.0

**Comment by braeven** [comment] 2021-01-04 11:34
This also happens on the official Epsilon Server:
As soon as someone visits the planet, the Server starts losing TPS, even in allready generated Chunks.

Generating new Chunk even generates Lag-Spikes, something is currently wrong with Ross128ba

**Comment by boubou19** [comment] 2021-01-04 18:32
@bartimaeusnek this is what i caught with a fresh instance of warmroast just before stressing delta with ross128b:
https://cdn.discordapp.com/attachments/752497188399087656/795720829769089054/WarmRoast.html. Looks like your code is iddling a lot, so i don't know what actually happens.

**Comment by bartimaeusnek** [comment] 2021-01-04 18:37
@braeven @boubou19 its added to prevent null ores from spawning. a secreity measue due to the way mc is handleing TileEntitys and def. nedded.

**Comment by GTNH-Colen** [comment] 2021-01-04 18:52
> @braeven @boubou19 its added to prevent null ores from spawning. a secreity measue due to the way mc is handleing TileEntitys and def. nedded.

I still don't really understand why GT has ores as tile entities, seems rather silly when no other mod I know does it. The only reason I've seen is to stop xraying but imo that is beyond the purview of GT anyways.

**Comment by leagris** [comment] 2021-01-04 19:41
> I still don't really understand why GT has ores as tile entities, seems rather silly when no other mod I know does it. The only reason I've seen is to stop xraying but imo that is beyond the purview of GT anyways.

Later GT like gt-ce opted to not use tiles for ore blocks. Incidently they had to reduce the number of ore types and possible background stone types significantly. Block meta is only 4-bit and sor offers only 16 combinations. Now take thousands of materials with 6 different background stones, storing all this with only ID and meta would use up an insane amount of BlockID just for Ores.

Tiles ores are not the direct lagg issue here.

Most likely some of the latest changes are.

**Comment by KorGgenT** [comment] 2021-02-02 07:39
i can confirm the lag on chunk loading persists on ross on 2.1

**Comment by boubou19** [comment] 2021-02-22 14:21
duplicate of #7386

**Closed by boubou19** 2021-02-22 14:21 UTC
Labels: Mod: BartWorks, Type: Lag, Type: duplicate
