### ISSUE TITLE
threaded supper buffer wrong output

### ISSUE THREAD

**Issue by zgggz** [GTNewHorizons/GT-New-Horizons-Modpack#6473] opened 2020-08-02 06:27 UTC
#### Which modpack version are you using?
2.0.9
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
just setup buffer to input bus with 9 stack size.
#
#### What happened instead? (Attach screenshots if needed)
i see in bus 9 stacks and 1
![Screenshot_9](https://user-images.githubusercontent.com/64369015/89116954-5095b380-d4a2-11ea-8f4b-63e504b50d43.png)

#
#### What do you suggest instead/what changes do you propose?
At simple one buffer we can use modes that fix it. May be this one also need it?

**Comment by chochem** [comment] 2020-08-02 07:41
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6428

can be closed.

**Closed** 2020-08-02 07:52 UTC
