### ISSUE TITLE
Pressing escape puts backtick into NEI field

### ISSUE THREAD

**Issue by jurrejelle** [GTNewHorizons/GT-New-Horizons-Modpack#12828] opened 2023-03-07 20:18 UTC
### Your GTNH Discord Username

jurrejelle#4936

### Your Pack Version

2.3.0 RC3

### Your Server

Kiyalabs.io

### Java Version

Java 19

### Type of Server

Don't know

### Your Expectation

When I press escape when in NEI or inside an ME terminal, it should close me out of the interface.

### The Reality

Instead, it puts a backtick in the field instead of actually processing the escape keystroke.

### Your Proposal

Make escape keystrokes actually escape out of NEI / ME terminals again

Further info: 

I didnt have this issue when on 2.2.11-nightly, however, I used the java 8 version there (I didnt see this download link needed java 9+ until after downloading, so I installed java 19 for it).

I'm on Windows 10 Home, version 21H2, build 19044.2604, using an English (United States International) keyboard layout

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by jurrejelle** [comment] 2023-03-07 20:24
Video of me reproducing the bug: https://youtu.be/m2rPXcbPJ10

**Comment by jurrejelle** [comment] 2023-03-07 20:28
(Fixed) video of me reproducing the bug: https://youtu.be/LHNIu882m98
When I click outside of the textbox / unfocus the search bar, it does process the keystroke correctly, so I assume it's some problem with (NEI) searchbars processing the escape keystroke

**Comment by jurrejelle** [comment] 2023-03-07 21:28
Update: I just downloaded the java 8 file pack and installed it on my old java 8 client, and now it doesn't have the bug anymore, so it seems like it's strictly java 9+ that causes it

**Comment by Ethryan** [comment] 2023-03-07 23:47
It has to do with [link](https://github.com/GTNewHorizons/lwjgl3ify/issues/28)

**Comment by chochem** [comment] 2023-03-08 00:05
I dont see how that is related ethyran. this is just one specific key being wrongly mapped and in windows. not about fast multikey presses in linux.

I can confirm this ticket btw, I have same when I press esc (UK layout, windows).

**Comment by Ethryan** [comment] 2023-03-08 00:39
I had the same problem, but only when i connected to a linux based server, it dissapeared when i changed it.

**Comment by chochem** [comment] 2023-03-08 10:11
this is almost certainly clientside. your server doesnt even matter. Any I am on windows singleplayer. This is just completly different than the unrelated (and solved!) other issue.

**Comment by chochem** [comment] 2023-03-08 10:38
All I can add is that it is inconsistent for me. I just started a game to get logs and everything is fine. But a few days ago I had the problem a lot. I have not yet found the deciding factor for that. That is also the reason why I hadnt made a ticket yet and was waiting for other people to have the same issue.

**Comment by chochem** [comment] 2023-03-08 21:59
alright the error is back, so now I have some logs. This is just me pressing Esc a few times while the NEI search field is highlighted.

```[21:56:48] [Client thread/INFO] [lwjgl3ify/]: [DEBUG-KEY] key window:1485231589872 key:256 scancode:1 action:1 mods:0 char:?
[21:56:48] [Client thread/DEBUG] [NotEnoughItems/]: Searching for `
[21:56:48] [Client thread/INFO] [lwjgl3ify/]: [DEBUG-KEY] key window:1485231589872 key:256 scancode:1 action:0 mods:0 char:?
[21:56:49] [Client thread/INFO] [lwjgl3ify/]: [DEBUG-KEY] key window:1485231589872 key:256 scancode:1 action:1 mods:0 char:?
[21:56:49] [Client thread/DEBUG] [NotEnoughItems/]: Searching for ``
[21:56:49] [Client thread/INFO] [lwjgl3ify/]: [DEBUG-KEY] key window:1485231589872 key:256 scancode:1 action:0 mods:0 char:?
[21:56:49] [Client thread/INFO] [lwjgl3ify/]: [DEBUG-KEY] key window:1485231589872 key:256 scancode:1 action:1 mods:0 char:?
[21:56:49] [Client thread/DEBUG] [NotEnoughItems/]: Searching for ```
[21:56:49] [Client thread/INFO] [lwjgl3ify/]: [DEBUG-KEY] key window:1485231589872 key:256 scancode:1 action:0 mods:0 char:?
[21:56:49] [Client thread/INFO] [lwjgl3ify/]: [DEBUG-KEY] key window:1485231589872 key:256 scancode:1 action:1 mods:0 char:?
[21:56:49] [Client thread/DEBUG] [NotEnoughItems/]: Searching for ````
[21:56:49] [Client thread/INFO] [lwjgl3ify/]: [DEBUG-KEY] key window:1485231589872 key:256 scancode:1 action:0 mods:0 char:?```

**Comment by chochem** [comment] 2023-03-08 22:10
[fml-client-3.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10925639/fml-client-3.log)

full log for that

**Comment by chochem** [comment] 2023-03-08 22:25
oh, and when it is working the debug looks like this:
```[22:23:36] [Client thread/INFO] [lwjgl3ify/]: [DEBUG-KEY] key window:2334111561216 key:256 scancode:1 action:1 mods:0 char:?
[22:23:36] [Client thread/INFO] [lwjgl3ify/]: [DEBUG-KEY] key window:2334111561216 key:256 scancode:1 action:0 mods:0 char:?
[22:23:37] [Client thread/INFO] [lwjgl3ify/]: [DEBUG-KEY] key window:2334111561216 key:256 scancode:1 action:1 mods:0 char:?
[22:23:37] [Client thread/INFO] [lwjgl3ify/]: [DEBUG-KEY] key window:2334111561216 key:256 scancode:1 action:0 mods:0 char:?
[22:23:38] [Client thread/INFO] [lwjgl3ify/]: [DEBUG-KEY] key window:2334111561216 key:256 scancode:1 action:1 mods:0 char:?
[22:23:38] [Server thread/DEBUG] [FML/]: Gathering id map for writing to world save Terra Nova 2.1.2 v1
[22:23:38] [Client thread/INFO] [lwjgl3ify/]: [DEBUG-KEY] key window:2334111561216 key:256 scancode:1 action:0 mods:0 char:?```
(just on focussing and closing the nei gui)

**Comment by Blade8895** [comment] 2023-03-10 19:55
The Error exist on Signs with pressing Backpace too.
If you backspace then 1 letter will removed and a ` will be added each time you press backspace.

And can confirm the NEI bug. 
But each launch its different. sometimes it worked as expected esc = gui close
but then out of a sudden it will lock you to the Textbox and add the ^ in my case. iirc (cant check it right now)

Biggest problem in Fluid Terminal when there is no way to deselect a ghost box or something linke this. You cant escape anymore. Then you must press the Crafting task button on the top right and then esc out.

No Logs that can confirm this....

**Comment by eigenraven** [comment] 2023-03-10 20:10
It's not a proper fix for the underlying issue, but <https://github.com/GTNewHorizons/lwjgl3ify/releases/tag/1.1.38> should be enough to stop esc&backspace randomly breaking

**Comment by eigenraven** [comment] 2023-11-29 22:02
The big keyboard refactor should have solved this permanently.

**Closed by eigenraven** 2023-11-29 22:02 UTC
Labels: Type: bugMinor, java17+
