### ISSUE TITLE
Travel anchors always visible without using staff of travelling

### ISSUE THREAD

**Issue by skinke17** [GTNewHorizons/GT-New-Horizons-Modpack#15406] opened 2024-01-24 14:22 UTC
### Your GTNH Discord Username

sJ (canyoushootme)

### Your Pack Version

2.6.0-nightly-2024-01-23

### Your Server

private server

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Not showing the travel anchors from EnderIO all the time, without using/holding the staff of traveling.

![billede](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/144228003/5784cb90-c466-4a16-8b1a-965adac04c14)

I do have optifine and neodynium installed but i've tried without them as well and it's the same issue.

### The Reality

It's permanently showing the travel anchors whenever i'm in distance of one.

### Your Proposal

idk hopefully it's an easy fix or i've missed something somewhere

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Caedis** [comment] 2024-01-24 14:33
Do they go away at any point?

**Comment by Caedis** [comment] 2024-01-24 14:41
Confirmed

**Comment by skinke17** [comment] 2024-01-24 14:42
They only go away if they're out of view distance

**Comment by Caedis** [comment] 2024-01-24 15:07
@TheUnderTaker11 if you want to take a look at it since its due to your PR

**Comment by TheUnderTaker11** [comment] 2024-01-24 15:57
Ah I see, yes I did not realize the travel anchor rendering logic was hooked into the same method(s) I had changed for the keybind functionality. It was obviously not intended to have the inventory scanning run every tick, I was only trying to add that logic to happen when travel staff is actually used (keybind or shift right click).
I'll get a fix for this in soon.

**Comment by Caedis** [comment] 2024-01-24 16:09
Thanks!

**Closed** 2024-01-24 16:58 UTC
Labels: Type: bugMajor
