### ISSUE TITLE
Alt Gr characters not working (e.g. @£$€)

### ISSUE THREAD

**Issue by Novie53** [GTNewHorizons/GT-New-Horizons-Modpack#15175] opened 2023-12-20 20:02 UTC
### Your GTNH Discord Username

Quintus#6363

### Your Pack Version

2.5.0

### Your Server

Private server & Single player

### Java Version

Java 17

### Type of Server

None

### Your Expectation

Nothing happends when I try to type any Alt Gr special characters. Have tried in NEI searchbar and ingame chat. Have tried to restart the client and creating a new fresh Prism instance. 

Swedish keyboard
Windows 10

### The Reality

.

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by glowredman** [comment] 2023-12-20 20:08
Duplicate of https://github.com/GTNewHorizons/lwjgl3ify/issues/91.

**Closed by glowredman** 2023-12-20 20:08 UTC
Labels: Type: bugMinor, Status: Triage
