### ISSUE TITLE
Inventory disappear

### ISSUE THREAD

**Issue by Oueio** [GTNewHorizons/GT-New-Horizons-Modpack#17790] opened 2024-10-28 23:50 UTC
### Your GTNH Discord Username

oueio

### Your Pack Version

2.7.0beta3 (2.6.0)

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Watching recipes in NEI

### The Reality

Don't know how to recreate bug, but it appears second time (last was in 2.6.0). And in this state i can't close inventory and play, so need to close game and restart
![image](https://github.com/user-attachments/assets/4fa3cfab-f93f-40ab-83f1-b035b0518727)

### Your Proposal

Close inventory in this state without closing the game

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Alexdoru** [comment] 2024-10-28 23:53
do you have any other mod or a certain texture pack ?

**Comment by Oueio** [comment] 2024-10-28 23:55
No resource packs, additional mod - FPS Reducer. I play with it always since 2.1 and didnt see problems

**Comment by FireWarrior2** [comment] 2024-10-29 06:07
F6 or changing game mode will help.
Also, it's a duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15878

**Comment by Oueio** [comment] 2024-10-29 07:37
What F6 is binded for?

**Comment by wlhlm** [comment] 2024-10-29 15:29
> What F6 is binded for?

https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15878#issuecomment-2195622294

**Comment by Oueio** [comment] 2024-10-29 15:34
I asked, because i tried Toggling nei and it didnt work

**Closed** 2024-11-02 21:54 UTC
Labels: Type: bugMinor, Status: Triage
