### ISSUE TITLE
BioLab quest (#2566) broken?

### ISSUE THREAD

**Issue by Rokkitz** [GTNewHorizons/GT-New-Horizons-Modpack#6827] opened 2020-10-18 17:37 UTC
#### Which modpack version are you using?
not sure. StoneLegion Server
#
#### If in multiplayer; On which server does this happen? 
StoneLegion
#
#### What did you try to do, and what did you expect to happen?
Built bioLab, did not register so quest did not complete. Other items for the quest were completed. Quest #2566 in HV tab. Did not open the vat quest in multiblock tab.
#
#### What happened instead? (Attach screenshots if needed)
Nothing. 
#
#### What do you suggest instead/what changes do you propose?
I believe that the version of the bioLab built depends on what circuits are used. Perhaps it was the "wrong" circuits?

**Comment by Prometheus0000** [comment] 2020-10-18 17:52
Duplicate of #6290, #6444.

**Closed by Prometheus0000** 2020-10-18 17:52 UTC
Labels: Type: duplicate
