### ISSUE TITLE
Redundant Aluminium Recipe from Raw Aluminum

### ISSUE THREAD

**Issue by henrydukepickle** [GTNewHorizons/GT-New-Horizons-Modpack#10470] opened 2022-06-10 19:28 UTC
### Your GTNH Discord Username

henryduke#0140

### Your Pack Version

2.1.2.4-5

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I expected a consistent smelt time for raw aluminium.

### The Reality

The compressed aluminium -> aluminium ingot recipe (without added gas) has 2 recipes with different lengths/power requirements. The EBF seems to just pick one at random, which leads to inconsistency. Additionally, if aluminium dust -> aluminium ingot is supposed to be gated behind kanthal coils, it should be noted that the recipe runs at MV power and <1800K.
![image](https://user-images.githubusercontent.com/90169501/173136359-d735b87d-6a27-44f2-a0de-dbcbc5966396.png)
![image](https://user-images.githubusercontent.com/90169501/173136384-66ace280-71a8-4d70-b18c-2e1917ffa806.png)

### Your Proposal

Remove the 80s recipe. From what I can gather, the 65s recipe is more in line with the other (gas) recipes.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2022-06-10 19:33
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10041

redundant ticket basically :P

**Comment by henrydukepickle** [comment] 2022-06-10 19:35
I mean it's less about it being available in MV and more about the redundant recipe causing inconsistency.

**Comment by Dream-Master** [comment] 2022-06-10 20:58
this was a recipe suggested by @leagris

**Comment by chochem** [comment] 2022-06-10 21:03
there is just 2 recipes doing exactly the same on different times, that is the main point of the ticket.

**Closed** 2022-07-19 00:16 UTC
Labels: Type: Recipe Change, Type: bugMinor, Mod: GT
