### ISSUE TITLE
deprecated super buffers still exist and say to drop in disassembler. which no longer exists

### ISSUE THREAD

**Issue by Hiagg** [GTNewHorizons/GT-New-Horizons-Modpack#13560] opened 2023-05-24 19:46 UTC
### Your Pack Version

2.3.3+ (whatever TEG has)

### Your Server

self hosted

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Expectation

these should be gone

### The Reality

they are here

### Your Proposal

gone them

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by minecraft7771** [comment] 2023-05-24 19:51
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12211

**Closed** 2023-05-26 05:41 UTC
Labels: Type: bugMinor, Status: Triage
