### ISSUE TITLE
? Button in NEI is missing

### ISSUE THREAD

**Issue by litten8** [GTNewHorizons/GT-New-Horizons-Modpack#15084] opened 2023-12-14 23:57 UTC
### Your GTNH Discord Username

agwic

### Your Pack Version

2.5.0-$C-1

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

I wanted to use the ? button in NEI to automatically input recipes into JEC, but it was no there.

### The Reality

The ? button only seems to appear for crafting table recipes.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/20496976/58babec5-a9a5-4b89-bb04-dfe4cef9da6a)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/20496976/1e7a4ba2-e840-4d58-b8a7-6f90164f0ac2)

### Your Proposal

There should be a ? button in NEI for every recipe.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2023-12-15 00:02
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15077

**Closed by chochem** 2023-12-15 00:02 UTC
Labels: Type: Duplicate, Type: bugMinor, Not supported Mod
