### ISSUE TITLE
[Thaumic Exploration] Everfull Urn

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6382] opened 2020-07-12 15:33 UTC
#### Which modpack version are you using?
2.0.9.4QF4
#
#### If in multiplayer; On which server does this happen? 
Eta
### Using RCM on Everfull Urn turn tools and another meta-items to null meta-items
![изображение](https://user-images.githubusercontent.com/47714084/87250452-7ca6b180-c46d-11ea-983c-69f3bf8deeef.png)
![изображение](https://user-images.githubusercontent.com/47714084/87250462-8d572780-c46d-11ea-8c42-f03208cf8172.png)
### I have a little the null metaitem collection :)
![изображение](https://user-images.githubusercontent.com/47714084/87250487-cb544b80-c46d-11ea-9214-d333aeaa34c5.png)

**Comment by boubou19** [comment] 2020-07-12 15:34
duplicate of #6249, #5453, #1442. Please look for existing issues before posting one.

**Closed** 2020-07-12 16:34 UTC
Labels: duplicate
