### ISSUE TITLE
"North-Facing Nagastone" Crashes Server

### ISSUE THREAD

**Issue by Enderithe** [GTNewHorizons/GT-New-Horizons-Modpack#17753] opened 2024-10-24 22:48 UTC
### Your GTNH Discord Username

enderithe & surgeapex52 & epicboss32

### Your Pack Version

2.6.1

### Your Server

private server

### Java Version

Java 17

### Type of Server

None

### Your Actions

If a North-facing Etched Nagastone is blown up by an entity in a way that drops its item, and then that item is picked up by a player, the server will crash. The world hangs until it is reverted to a backup.

The specific line from the crash report is: 
java.lang.NullPointerException: Cannot invoke "net.minecraftforge.common.util.ForgeDirection.ordinal()" because "this.EtchedNagastoneNorth" is null

### Crash Report

[message.txt](https://github.com/user-attachments/files/17513666/message.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Lyfts** [comment] 2024-10-24 22:52
![s](https://github.com/user-attachments/assets/d9286e8a-10d1-493c-b13b-6c59d3cc2440)
Searching "Twilight Forest", "Nagastone" or something similar on the issue tracker results in about 50 issues identical to this one. 

Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16353 and many others.

**Closed by Lyfts** 2024-10-24 22:52 UTC
Labels: Type: Crash, Status: Triage

**Comment by SRG-Apex** [comment] 2024-10-24 22:59
I don't believe its the same crash, as described by the OP of the linked post, their world crashes on render NOT pickup, and we have tried the fix described and same result, while I guess the fix may fix the rendering issue, our issue is different

**Comment by Enderithe** [comment] 2024-10-24 23:03
All the others are rendering issues. We have only encountered issues when we pick up a specific block. We have repeatedly experimented, and this _never_ occurs when rendering. The crash happens instantly when we pick up that block. At the very least, this report has more information than the other reports.

**Comment by Lyfts** [comment] 2024-10-24 23:04
It is the same crash and it has been fixed for over 6 months now, stop beating a dead horse.

**Comment by SRG-Apex** [comment] 2024-10-24 23:06
_if you say so_

**Comment by Lyfts** [comment] 2024-10-24 23:07
I don't say so, your crash log does.
