### ISSUE TITLE
New crafting units not working

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#6030] opened 2020-05-03 15:53 UTC
#### Which modpack version are you using?
2.0.9.0 and 2.0.8.8
#
256k, 1024k, 4096k, 16384k crafting units do not work at all currently. They attached to the AE system and show up but cannot be used for crafting tasks, it is as if they hold 0 bytes.

**Comment by Prometheus0000** [comment] 2020-05-03 15:58
Similar/same as #5264? Also see #4382, https://github.com/alkcorp/GTplusplus/issues/681

**Comment by Dream-Master** [comment] 2020-05-03 16:02
@DeForce Maybe you can check it. Thanks

**Comment by Retster** [comment] 2020-05-03 17:33
Got same issue at 8.8 when connect 2*256 Crafting units, but when connect to them another unit with 16K then all storage is used properly.

**Comment by GTNH-Colen** [comment] 2020-05-03 18:23
> Got same issue at 8.8 when connect 2*256 Crafting units, but when connect to them another unit with 16K then all storage is used properly.

Yea can confirm this, just got informed by someone and tested it. Still a bug but less important I suppose.

**Comment by Prometheus0000** [comment] 2020-10-09 19:24
Duplicate of #5264

**Closed by Prometheus0000** 2020-10-09 19:24 UTC
Labels: Mod: EC2, Type: duplicate
