### ISSUE TITLE
Deleting blizz rod from existence using cutting machine

### ISSUE THREAD

**Issue by POPlol333** [GTNewHorizons/GT-New-Horizons-Modpack#8580] opened 2021-09-21 21:08 UTC
### Your GTNH Discord Username

AdamR#0072

### Your Pack Version

2.1.1.0

### Your Server

Delta

### Type of Server

Don't know

### Your Expectation

Well I don't know, tbh I was just being curious with blaze rods (I came from the blitz rod  NEI to the blizz rod with vacuum freezer recipe) and ended up infront of that ?

### The Reality

Seems that cutting blizz rods give literally nothing ?
![image](https://user-images.githubusercontent.com/76914762/134247918-ef10a57b-d42e-4258-a6ba-7596b10895f9.png)

### Your Proposal

I don't really nor delete the craft nor just add a product to this?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by leagris** [comment] 2021-09-21 21:23
Recipe is auto-generated for each material with a rod and the cutting of a rod is expected to produce two bolts of same material. Unfortunately there is no such thing as blizz/ice bolts, so the recipe output is non-existant

**Comment by boubou19** [comment] 2021-09-21 21:52
I thought we had a thing against null items in recipe output?

**Comment by Prometheus0000** [comment] 2021-09-21 21:58
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6102

**Closed by Prometheus0000** 2021-09-21 21:58 UTC
Labels: Type: duplicate, Type: bugMinor, Status: Triage
