### ISSUE TITLE
Long Distance Item Pipeline doesn't work with GT item pipe as output target

### ISSUE THREAD

**Issue by TimeConqueror** [GTNewHorizons/GT-New-Horizons-Modpack#8534] opened 2021-09-14 01:14 UTC
### Your GTNH Discord Username

TimeConqueror#0001

### Your Pack Version

2.1.1.2

### Your Server

private one

### Type of Server

Thermos

### Your Expectation

I set up the long distance item pipe and connected its output to the item tin pipe. All items should be passed to these pipes.

### The Reality

But LDIP doesn't see it as a valid target, even if the pipe leads somewhere. And this is not a wrong LDIP setup. If I place any chest, it will suddenly work as expected, but with pipes it doesn't want to do so

### Your Proposal

Make the item pipes be a valid source?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Prometheus0000** [comment] 2021-09-14 01:21
Duplicate of #7259

Feel free to fix it yourself, since mitch seems busy.

**Closed by Prometheus0000** 2021-09-14 01:21 UTC
Labels: Type: duplicate, Type: bugMinor, Mod: GT, Status: Triage
