### ISSUE TITLE
Iridium alloy ingot ucraftable

### ISSUE THREAD

**Issue by Florexiz** [GTNewHorizons/GT-New-Horizons-Modpack#9027] opened 2021-12-08 10:39 UTC
### Your GTNH Discord Username

FalseColor#8524

### Your Pack Version

2.1.2.0-pre4

### Your Server

Zeta

### Type of Server

Thermos

### Your Expectation

Craft iridium alloy ingot 
![image](https://user-images.githubusercontent.com/29033773/145194103-22aa0093-d7b2-47bf-89c1-4c59f2ed4306.png)

### The Reality

It doesn't have recipe

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment] 2021-12-08 10:42
Duplicate of #9020

**Closed by Glease** 2021-12-08 10:42 UTC
Labels: Type: Duplicate, Type: bugMinor
