### ISSUE TITLE
Water Purification Plant shuts down immediately after loading the world

### ISSUE THREAD

**Issue by Kogepan229** [GTNewHorizons/GT-New-Horizons-Modpack#18093] opened 2024-11-24 08:02 UTC
### Your GTNH Discord Username

kogepan229

### Your Pack Version

2.7.0-beta4

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Won't shut down

### The Reality

The following error appears in the logs and the machine shuts down.
When I turn the machine on it starts to run but at the end of the cycle the machine shuts off with the same error.
Replacing the machine makes it work temporarily, but when I reopen the world the same problem occurs.

I added a null check before [this line](https://github.com/GTNewHorizons/GT5-Unofficial/blob/41243097f3e95b1d0e98f4c816bd64e398ba30d4/src/main/java/gregtech/common/tileentities/machines/multi/purification/MTEPurificationUnitBase.java#L420) and it showed that `mOutputItems` was null.

[fml-client-latest.log](https://github.com/user-attachments/files/17892444/fml-client-latest.log)
```
[16:33:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.NullPointerException: Cannot read the array length because "<local2>" is null
[16:33:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//gregtech.api.metatileentity.implementations.MTEMultiBlockBase.addItemOutputs(MTEMultiBlockBase.java:1395)
[16:33:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//gregtech.common.tileentities.machines.multi.purification.MTEPurificationUnitBase.addRecipeOutputs(MTEPurificationUnitBase.java:423)
[16:33:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//gregtech.common.tileentities.machines.multi.purification.MTEPurificationUnitPlasmaHeater.addRecipeOutputs(MTEPurificationUnitPlasmaHeater.java:429)
[16:33:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//gregtech.common.tileentities.machines.multi.purification.MTEPurificationUnitBase.endCycle(MTEPurificationUnitBase.java:435)
[16:33:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//gregtech.common.tileentities.machines.multi.purification.MTEPurificationPlant.endCycle(MTEPurificationPlant.java:463)
[16:33:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//gregtech.common.tileentities.machines.multi.purification.MTEPurificationPlant.updateCycleProgress(MTEPurificationPlant.java:408)
[16:33:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//gregtech.common.tileentities.machines.multi.purification.MTEPurificationPlant.runMachine(MTEPurificationPlant.java:379)
[16:33:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//gregtech.api.metatileentity.implementations.MTEMultiBlockBase.onPostTick(MTEMultiBlockBase.java:472)
[16:33:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//gregtech.common.tileentities.machines.multi.purification.MTEPurificationPlant.onPostTick(MTEPurificationPlant.java:356)
[16:33:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:565)
[16:33:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//net.minecraft.world.World.func_72939_s(World.java:1939)
[16:33:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[16:33:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[16:33:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[16:33:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
[16:33:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[16:33:07] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

### Your Proposal

Fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by wlhlm** [comment] 2024-11-24 08:17
Duplicate of #17994

**Closed by wlhlm** 2024-11-24 08:17 UTC
Labels: Bug: Minor, Status: Triage
