### ISSUE TITLE
Twilight forest crashing prevents me from joining the world 

### ISSUE THREAD

**Issue by Comedic85** [GTNewHorizons/GT-New-Horizons-Modpack#17059] opened 2024-08-20 14:57 UTC
### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Actions

I was running around in the twilight forest and then randomly crashed. Ever since then every time I've tried to enter the world it crashes.

### Crash Report

[crash-2024-08-20_13.49.52-server.txt](https://github.com/user-attachments/files/16677576/crash-2024-08-20_13.49.52-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2024-08-20 14:59
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16353 and a so so many others...

**Closed by chochem** 2024-08-20 14:59 UTC
Labels: Type: Crash, Status: Triage

**Comment by mitchej123** [comment] 2024-08-20 15:03
![image](https://github.com/user-attachments/assets/609090f5-fb9a-43c2-af6f-d09857190c91)

**Comment by SONOFTTB** [comment] 2024-08-23 14:33
I have this issue also
[wompwomp.txt](https://github.com/user-attachments/files/16730098/wompwomp.txt)
