### ISSUE TITLE
The game crashed when I carry a bucket of lava

### ISSUE THREAD

**Issue by agoodgamer** [GTNewHorizons/GT-New-Horizons-Modpack#15975] opened 2024-04-14 15:47 UTC
### Your GTNH Discord Username

TONGFANG13

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Actions

The game crashed when I carry a bucket of lava
I found there is a similar problem in Issues, but It seems that the problem hasn't been solved.

### Crash Report

[crash-2024-04-14_23.33.06-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14971263/crash-2024-04-14_23.33.06-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2024-04-14 16:04
any steps to reproduce?

**Comment by chochem** [comment] 2024-04-14 17:52
also yea, duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15928. Best post more over there

**Closed by chochem** 2024-04-14 17:52 UTC
Labels: Type: Crash, Status: Triage
