### ISSUE TITLE
Pahoehoe centrifuge recipe gives unconditional bauxite

### ISSUE THREAD

**Issue by riking** [GTNewHorizons/GT-New-Horizons-Modpack#9200] opened 2021-12-20 06:06 UTC
### Your GTNH Discord Username

Riking#6902 (not on GTNH Discord)

### Your Pack Version

2.1.2.0

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Expectation

1. Check recipes on Tin Nugget and go to the Multiblock Centrifuge.
2. Recipe: Configuration 10, Pahoehoe Lava (result of Lava in Heat Exchanger)
3. Every result is a percentage chance, except Bauxite Dust.

Valuable (Titanium) byproducts from an infinite processing chain should have low percentage chances attached.

### The Reality

Bauxite Dust renders in NEI as a guaranteed result.

### Your Proposal

Check the commit history to see what chance was intended or previously assigned to this output.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment] 2021-12-20 06:20
Iirc this is a visual bug now fixed. The actual recipe runs correctly (same as non multi)

**Comment by GTNH-Afx237v7** [comment] 2021-12-20 08:33
See here: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9137

**Comment by Glease** [comment] 2021-12-20 09:03
Visual bug. Duplicate of #9137

**Closed by Glease** 2021-12-20 09:03 UTC
Labels: Type: bugMinor, Status: Triage
