### ISSUE TITLE
Spice Of Life crashing game

### ISSUE THREAD

**Issue by Blaze8834** [GTNewHorizons/GT-New-Horizons-Modpack#15924] opened 2024-04-05 22:15 UTC
### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Actions

Opened inventory and tried to hover over some berries from the spice of life in my inventory. This caused the game to crash. It is weird because I have had these in my inventory before and it never crashed. (The berries were blueberry, raspberry and the yellowish orange one)

### Crash Report

[crash report here](https://mclo.gs/xXqENVq)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2024-04-06 10:58
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14471

**Closed by chochem** 2024-04-06 10:58 UTC
Labels: Type: Crash, Status: Triage
