### ISSUE TITLE
Game crashed a bit after entering world

### ISSUE THREAD

**Issue by FireWarrior2** [GTNewHorizons/GT-New-Horizons-Modpack#16088] opened 2024-04-29 10:20 UTC
### Your GTNH Discord Username

fire.warrior

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Game crashed a bit after I entered my world. Possibly something with angelica.
First time it crashed in about 10 seconds, then I caught black screen and crash.
Second time I was able to play ~5 minutes, but eventually it crashed again.

### Crash Report

[crash-2024-04-29_13.11.14-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15147915/crash-2024-04-29_13.11.14-client.txt)
[crash-2024-04-29_13.16.42-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15147916/crash-2024-04-29_13.16.42-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Ethryan** [comment] 2024-04-29 10:54
duplicate of #16075

**Closed by Ethryan** 2024-04-29 10:54 UTC
Labels: Type: Crash, Status: Triage
