### ISSUE TITLE
Return the aluminium used for indium concentrate

### ISSUE THREAD

**Issue by mollekylen** [GTNewHorizons/GT-New-Horizons-Modpack#18449] opened 2024-12-20 13:51 UTC
### Your GTNH Discord Username

mollekylen

### Your Pack Version

2.7.0

### Your Proposal

Making indium from indium concentrate requires a lot of aluminium dust. Despite aluminium not being the most scarce material, it's still a huge loss if you're making 1000+ indium and you don't have the required bees

### Your Goal

My goal is to recover at least 50% of the aluminium back so it can be reused

### Your Vision

After refining the indium concentrate, you get aluminium sulfate which can the electrolyzed back into alumina or aluminium dust

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by StaffiX** [comment] 2024-12-20 14:08
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16892

And indium concentrate is just one of many ways indium can be acquired, look at uses of indium comb if you want to see all of them

**Closed** 2024-12-20 14:08 UTC
Labels: Suggestion, Status: Triage
