### ISSUE TITLE
filling an empty cell from molten potassium disulfide bedrockium gives a bugged cell

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#6386] opened 2020-07-14 14:22 UTC
#### Which modpack version are you using?
2.0.9.0 QF4
#
#### If in multiplayer; On which server does this happen? 
Delta
#
#### What did you try to do, and what did you expect to happen?
i wanted to fill an empty cell with molten potassium disulfate to complete the quest "platinum group processing - all the other metals" in IV tab. To do that, i right clicked on a bedrockium barrel containing molten potassium disulfate with an empty cell.
#
#### What happened instead? (Attach screenshots if needed)
Instead of getting the molten potassium disulfate cell, i got a gt.bwMetaGeneratedcell.59.name, which is somehow oredicted like the molten potassium disulfate cell.

![image](https://user-images.githubusercontent.com/12850933/87436480-63c50a00-c5ed-11ea-98eb-363b4a16023b.png)

![image](https://user-images.githubusercontent.com/12850933/87436538-78090700-c5ed-11ea-86b5-cb0db961ebbd.png)

filling the cell in a GT tank work normally tho.

Also, the bugged cell takes 1 bucket in the drum while it should have taken 144 mb. I tried the same filling method for molten gallium from GT, but it works as intended and it gives me a molten gallium cell.

**Comment by boubou19** [comment] 2020-07-14 14:26
also, you cannot empty molten potassium disulfide cell in a bedrockium drum, you can only empty it in a gt tank

**Comment by Prometheus0000** [comment] 2020-07-14 14:28
Duplicate of #5393 I think.

**Comment by boubou19** [comment] 2020-07-14 14:31
yeah i saw this one too, did not think they could be related. at least now we know that trying to push 1 bucket in an empty cell triggers the bugged cell.

**Comment by Dream-Master** [comment] 2020-07-20 15:22
@bartimaeusnek any idea?

**Comment by Prometheus0000** [comment] 2020-10-10 13:27
This now fills an empty cell correctly, but not a universal one using the fluid canner or a tank

**Closed** 2021-07-29 08:36 UTC
Labels: Mod: BartWorks
