### ISSUE TITLE
Can not change redstone output strength of Needs Maintenance Cover on GT++ machines

### ISSUE THREAD

**Issue by joegnis** [GTNewHorizons/GT-New-Horizons-Modpack#15259] opened 2024-01-01 21:58 UTC
### Your GTNH Discord Username

joegnis

### Your Pack Version

2.5.1

### Your Server

private server

### Java Version

Java 17

### Type of Server

None

### Your Expectation

After putting a Needs Maintenance Cover on a machine controller block, right clicking it with a soldering iron should be able to set redstone output to strong.

### The Reality

Right clicking results in alternating the machine void mode no matter which area I clicked. I even tried right clicking directly the face where the cover is. On GT machines like EBF and LCR, this works as expected.

### Your Proposal

Be able to right click to change output strength since we have void mode button now on the machine controller, or add a output strength button to the Needs Maintenance Cover

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by LewisSaber** [comment] 2024-01-01 22:12
IM very sorry for this inconvinience

**Comment by LewisSaber** [comment] 2024-01-01 22:12
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15191

**Closed** 2024-01-01 22:13 UTC
Labels: Type: bugMinor, Status: Triage
