### ISSUE TITLE
Dragging NEI items into a disabled bookmark panel crashes the game

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#11908] opened 2022-12-01 23:52 UTC
### Your GTNH Discord Username

Tommeh#9804

### Your Pack Version

2.2.3

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Actions

Dragging an item from NEI into a disabled bookmark panel.

### Crash Report

[crash-2022-12-02_00.47.14-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10137031/crash-2022-12-02_00.47.14-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment] 2022-12-02 00:44
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11531, update NEI

**Closed by miozune** 2022-12-02 00:44 UTC
Labels: Type: Crash, Status: Triage
