### ISSUE TITLE
Cleanroom recipe length

### ISSUE THREAD

**Issue by halloo123** [GTNewHorizons/GT-New-Horizons-Modpack#15561] opened 2024-02-19 16:02 UTC
### Your GTNH Discord Username

halloo

### Your Pack Version

2.6.0-nightly-353

### Your Server

zeta

### Java Version

Java 17

### Type of Server

None

### Your Expectation

Built a cleanroom, powered it with 2 lv generators. Complete structure with no maintenance issues. I expected the standard length recipe.

### The Reality

The recipe is a lot longer than expected.
![2024-02-19_10 13 31](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/14303039/bd1c8d15-dfd8-4d9e-be50-6893d6675057)

### Your Proposal

Revert the recipe length back.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2024-02-19 16:07
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15473

**Closed by chochem** 2024-02-19 16:07 UTC
Labels: Type: bugMinor, Status: Triage
