### ISSUE TITLE
Add larger AE2 crafting storage

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#13537] opened 2023-05-20 23:04 UTC
### Your Pack Version

2.3.2

### Your Proposal

Add 32768k, 65536k and 131072k crafting storage.

### Your Goal

The current 16384k crafting storages are quite tedious to work with when orders easily need a billion bytes worth of storage.

### Your Vision

Limit the need to spam tiny crafting storages in comparison to end game orders.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by greesyB** [comment] 2023-05-20 23:10
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13053

**Closed by greesyB** 2023-05-20 23:10 UTC
Labels: Type: Suggestion, Status: Triage
