### ISSUE TITLE
TF Mod crashes game upon joining world

### ISSUE THREAD

**Issue by TFCrash** [GTNewHorizons/GT-New-Horizons-Modpack#17263] opened 2024-09-08 21:20 UTC
### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

I made the portal and I spawned in, walked a bit and saw a giant castle and the game crashed, I had not been able to join the world ever since, it crashes upon joining the world

### Crash Report

[crash-2024-09-09_00.15.24-server.txt](https://github.com/user-attachments/files/16923712/crash-2024-09-09_00.15.24-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Caedis** [comment] 2024-09-08 21:22
Update TF to https://github.com/GTNewHorizons/twilightforest/releases/download/2.6.33/TwilightForest-2.6.33.jar

Duplicate of many other tickets

**Closed by Caedis** 2024-09-08 21:22 UTC
Labels: Type: Crash, Status: Triage
