### ISSUE TITLE
Stockroom Catalogue does not correctly display material names

### ISSUE THREAD

**Issue by Volumetric-Nanometre** [GTNewHorizons/GT-New-Horizons-Modpack#6522] opened 2020-08-19 12:17 UTC
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Private server survival, but also verified to occur on single player creative
#
#### What did you try to do, and what did you expect to happen?
When using the stockroom catalogue, the names of items should appear as text next to the quantity of items
#
#### What happened instead? (Attach screenshots if needed)
The names of the majority of ingots and dusts appear as "%material Dust"/"%material Ingot"/"Tiny Pile of %material Dust" instead of "Gold Dust" or "Tiny Pile of Copper Dust"
The image attached demonstrated this
![image](https://user-images.githubusercontent.com/19982916/90633514-122c2280-e21e-11ea-8d2e-132d65010262.png)

I have tried this in 4x4 storage drawers and in standard chests and the same result occurs. 
It is worth noting that it DOES disinguish between the dusts and ingots correctly, i.e is does not sum all the dusts into one, you just get n "%material Dust" with different count values.
#
#### What do you suggest instead/what changes do you propose?
My hunch is that the name is being incorrectly read from the material metadata, however I do not know enough about the codebase to comment. It also apears to be intermittent, as some ingots and dusts correctly display.

**Comment by boubou19** [comment] 2020-08-19 12:18
duplicate of #4828 and #5571.

**Comment by repo-alt** [comment] 2020-08-19 13:24
Bibliocraft is closed source and ARR

**Comment by Dream-Master** [comment] 2020-08-19 13:39
@repo-alt can we add a fix from outside ?

**Comment by repo-alt** [comment] 2020-08-19 13:43
That is probably not trivial. Also I don't see that reported in the original repo, so obviously nobody really cares.

**Closed** 2020-08-19 22:09 UTC
Labels: duplicate
