### ISSUE TITLE
Storage disconnection bug in Ae2Fc

### ISSUE THREAD

**Issue by CrJolin0783** [GTNewHorizons/GT-New-Horizons-Modpack#12743] opened 2023-03-01 06:53 UTC
### Your Pack Version

2.2.9.7

### Your Server

SP

### Java Version

Java 8

### Type of Server

Open To LAN

### Your Expectation

/

### The Reality

In version 2.2.9.7 I used T.F.F.T and the newly added Fc fluid storage bus to store the source mass; a very brave solution But! I am playing with the server. It has a fatal bug, every time the server is restarted the TFFT is disconnected from the ae (disconnected in this case means that it is not displayed in the source terminal and cannot be invoked during magic injection) but it is displayed and invoked in the tfft where the source is stored along with the fluids.
This is a very tricky bug and I don't know if it can happen with other containers.
Existing workaround: disconnect the Fc fluid storage bus and reconnect it to the ae and it will continue to work

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2023-03-01 09:51
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12610
please post there.

**Closed by chochem** 2023-03-01 09:51 UTC
Labels: Type: bugMinor, Status: Triage
