### ISSUE TITLE
TGS eating chainsaws sometimes

### ISSUE THREAD

**Issue by Star-Tube** [GTNewHorizons/GT-New-Horizons-Modpack#16989] opened 2024-08-12 05:40 UTC
### Your GTNH Discord Username

star_tube

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Chainsaws that are out of energy but still have durability should either remain in the input bus or be reliably put into the output bus

### The Reality

Sometimes the chainsaw is eaten even though it has durability. My best guess is that it is because the recipe only checks if there is enough output space for the logs and doesn't account for the Chainsaw.

### Your Proposal

Make the Chainsaw stay in the input hatch while still reducing it's energy and durability or make the recipe check for output space accurately or allow us to filter output buses so we can have one that takes the logs and another that only takes the chainsaws.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Star-Tube** [comment] 2024-08-12 05:42
Has happened to me twice so far.

**Comment by Star-Tube** [comment] 2024-08-18 06:00
Just happened again. My current work around is going to be just running it with something cheap like iron saws instead of chainsaws... real sad that chainsaws just aren't viable because of this.

**Comment by Glease** [comment] 2024-08-19 12:14
likely duplicate of #16518

**Closed by Glease** 2024-08-19 12:14 UTC
Labels: Type: bugMinor, Status: Triage
