### ISSUE TITLE
Game crashes when enabling NEI Sync in EIO Inventory Panel

### ISSUE THREAD

**Issue by Maxerz13** [GTNewHorizons/GT-New-Horizons-Modpack#11907] opened 2022-12-01 19:45 UTC
### Your Pack Version

2.2.0.0

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Actions

Basically the title. If I click the enable NEI Sync in the Ender I/O Inventory Panel it crashes my game back to the main menu screen.

### Crash Report

[crash-2022-12-01_14.23.38-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10135704/crash-2022-12-01_14.23.38-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by minecraft7771** [comment] 2022-12-01 19:47
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11867

**Closed by minecraft7771** 2022-12-01 19:47 UTC
Labels: Type: Crash, Status: Triage
