### ISSUE TITLE
Bartworks corrupted packet causing fatal error on connection

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#15089] opened 2023-12-15 20:07 UTC
### Your Pack Version

2.4.1

### Your Server

Private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

/

### The Reality

After being online for 10sec at best my connection gets terminated due to a fatal error from bartworks on the client:

```
[21:01:12] [Client thread/ERROR]: BW Packet was corrupted or modified!
[21:01:12] [Netty Client IO #10/INFO]: Restoring client configs.
[21:01:12] [Netty Client IO #10/INFO]: Reset configs to client values for com.enderio.core.common.config.ConfigHandler
[21:01:12] [Netty Client IO #10/INFO]: Reset configs to client values for tterrag.wailaplugins.config.WPConfigHandler
[21:01:12] [Netty Client IO #10/INFO]: Scheduling client settings reset.
[21:01:12] [Client thread/ERROR]: There was a critical exception handling a packet on channel BartWorks
io.netty.handler.codec.DecoderException: java.lang.NullPointerException: element
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(Unknown Source) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:6606) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException: element
	at io.netty.util.internal.RecyclableArrayList.add(RecyclableArrayList.java:104) ~[RecyclableArrayList.class:?]
	at com.github.bartimaeusnek.bartworks.common.net.BW_Network.decode(BW_Network.java:74) ~[BW_Network.class:?]
	at com.github.bartimaeusnek.bartworks.common.net.BW_Network.decode(BW_Network.java:48) ~[BW_Network.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$2.decode(MessageToMessageCodec.java:81) ~[MessageToMessageCodec$2.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:89) ~[MessageToMessageDecoder.class:?]
	... 18 more
```

### Your Proposal

/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Tommeh1** [comment] 2023-12-15 20:16
It turns out that deleting hodgepodge solves this

**Comment by boubou19** [comment] 2023-12-16 00:02
apparently fixed in dev

**Closed by boubou19** 2023-12-16 00:02 UTC
Labels: Type: bugMinor, Status: Triage

**Comment by bombcar** [comment] 2023-12-16 00:17
A similar error has been caused by a corrupted install, especially a corrupted /config/ directory
