### ISSUE TITLE
Villages Spawn with Too Much Gravel

### ISSUE THREAD

**Issue by djj2148-1** [GTNewHorizons/GT-New-Horizons-Modpack#10813] opened 2022-07-24 07:15 UTC
### Your GTNH Discord Username

kertus27

### Your Pack Version

2.1.2.4-18-pre

### Your Server

private server/SP

### Type of Server

Don't know

### Your Expectation

I've recently updated both client and server to dev18-pre but the download package seems to have a bug with village spawning. Using the dropbox download on announcements to update (updating from 2.1.2.3qf on MultiMC), all villages regardless of biome and size spawn with way too much gravel almost seeming like gravel is replacing much of the ground and even some of the buildings themselves. 

### The Reality

![2022-07-24_01 54 30](https://user-images.githubusercontent.com/92820670/180635494-806d610b-9f4e-468b-a9d5-6ad0e4f894d8.png)
![2022-07-24_01 52 32](https://user-images.githubusercontent.com/92820670/180635496-a8f452db-7be3-4f3c-827f-277112a880e3.png)
As you can see, most (if not all) of the ground is gravel.

### Your Proposal

I'm not sure, maybe if there was a setting that controls village spawns that was changed between 2.1.2.3qf and 2.1.2.4-18pre reverting it to a previous iteration may work?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment] 2022-07-24 07:51
Duplicate of #10689

**Closed by miozune** 2022-07-24 07:51 UTC
Labels: Type: bugMinor, Status: Triage
