### ISSUE TITLE
Game Crash after interacting with Lava Fluid with Bucket

### ISSUE THREAD

**Issue by thelooter** [GTNewHorizons/GT-New-Horizons-Modpack#16604] opened 2024-06-26 13:28 UTC
### Your GTNH Discord Username

thelooter

### Your Pack Version

2.6.0

### Your Server

private server

### Java Version

Java 17

### Type of Server

Vanilla Forge

### Your Actions

Right click with standard iron Bucket on Lava

### Crash Report

https://mclo.gs/pTXG35p

The game says its related to Railcraft

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Caedis** [comment] 2024-06-26 13:30
Please update to 2.6.1 and see if it can be replicated

**Comment by chochem** [comment] 2024-06-26 14:21
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15928. please post more there and yes please test 2.6.1.

**Closed by chochem** 2024-06-26 14:21 UTC
Labels: Type: Crash, Status: Triage

**Comment by SirLordCandice** [comment] 2024-09-21 18:16
I Have the same problem on version 2.61
