### ISSUE TITLE
Applied Energistics not updating network after breaking cables.

### ISSUE THREAD

**Issue by Omnipact** [GTNewHorizons/GT-New-Horizons-Modpack#13531] opened 2023-05-20 04:02 UTC
### Your GTNH Discord Username

Omnipact

### Your Pack Version

2.3.2

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

 I wanted to temporarily disconnect a storage bus from an AE2 network by breaking the cable connecting it. 

### The Reality

The storage bus still exists on the network. I can add and remove items though it. I'll note that the smart cable connecting to it did change to reflect that the storage bus had been removed.
![2023-05-20_04 29 08](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/457252/a8677ed3-2eb3-4c7a-a1c5-21a7ea7cb886)
Screenshot shows that the bus is still online.

Quitting and reloading unsurprisingly will fix it.
Can be reproduced.

### Your Proposal

The bus should be removed from the network when disconnected.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by firenoo** [comment] 2023-05-20 04:06
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13065

**Closed by firenoo** 2023-05-20 04:06 UTC
Labels: Type: Duplicate, Type: bugMinor, Status: Triage
