### ISSUE TITLE
Remove magic from Dyson craft or give alternative recipe

### ISSUE THREAD

**Issue by FireWarrior2** [GTNewHorizons/GT-New-Horizons-Modpack#17387] opened 2024-09-20 08:38 UTC
### Your GTNH Discord Username

fire.warrior

### Your Pack Version

2.6.1

### Your Proposal

Remove Magic memory from Dyson swarm controller recipe or change Extremely primordial pearl in memory recipe for something else.
Or add alternative recipe for memory with something expensive, but not reffered to magic (idk, UIV fieldgen?)
![2024-09-20_11 23 28](https://github.com/user-attachments/assets/03c48d68-66bc-4994-abf1-d3f561100a65)

### Your Goal

Remove magic from main tech progression or make alternative recipe where it is not used (dragonblood production is a good example).

### Your Vision

Before UIV magic gives almost only QoL features, so you don't really need to do it to progress in greg.
But Dyson needs magic progression which is rather strange and annoying because you need this machine to generate energy (I know that there is a Naquadah reactor and Antimatter incoming).

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment] 2024-09-20 08:42
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13538

**Closed by chochem** 2024-09-20 08:42 UTC
Labels: Type: Suggestion, Status: Triage

**Comment by FireWarrior2** [comment] 2024-09-20 08:49
Then maybe open https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13538 ?

**Comment by HoleFish** [comment] 2024-09-20 09:08
it probably means "we discussed this before and the answer is _no_"

**Comment by boubou19** [comment] 2024-09-20 09:31
NH is a pack providing both magic and tech. You must accept the tiny amount of magic required in the tech progression even if you hate magic.

**Comment by duckedddd** [comment] 2024-09-20 09:44
You literally just need one pearl and can grow it to get enough for the large one which is a very small amount of magic and it isn’t even consumed, next tier you will need deep dark which is a bit more of an investment and is actually required. 
Requiring magic perfectly follows the route of the other strong solar line in the pack which is magic based. Dyson is even less required next update with the new antimatter gen in 2.7 and naqfuel buffs.
