### ISSUE TITLE
Alumina dust from Lazurite doesn't work anymore

### ISSUE THREAD

**Issue by sethdark** [GTNewHorizons/GT-New-Horizons-Modpack#12106] opened 2022-12-26 18:34 UTC
### Your GTNH Discord Username

sethdark#8143

### Your Pack Version

2.2.8

### Your Server

sp

### Type of Server

None

### Your Expectation

mv electrolyzer: 14 lazurite + circuit 1  = 3 alumina + byproducts

### The Reality

the circuit doesn't take and you get the aluminium dust recipe (the one without circuit)

### Your Proposal

I'm sorry I don't really have a proposal, maybe add a circuit to the other recipe so it doesn't default to it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by querns** [comment] 2022-12-26 18:41
This is probably a dupe of #11164 .

**Closed** 2022-12-26 18:46 UTC
Labels: Type: bugMinor, Status: Triage

**Comment by sethdark** [comment] 2022-12-26 19:01
ah yeah sorry my bad, I searched for the wrong keywords it seems
