### ISSUE TITLE
Items located in center of recipe in dire autocrafting table are not put in fluid pattern terminal

### ISSUE THREAD

**Issue by FireWarrior2** [GTNewHorizons/GT-New-Horizons-Modpack#16928] opened 2024-08-06 20:23 UTC
### Your GTNH Discord Username

fire.warrior

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

All items will be put in fluid pattern terminal when clicking [?].

### The Reality

Items located in center of recipe in dire autocrafting table are not put in fluid pattern terminal when clicking [?].
Item terminal works good.
Some of such recipes: Neutronium Compressor (UV Compressor), Neutronium Energy Cell (Cosmic Nt Block) etc.
![2024-08-06_23 21 44](https://github.com/user-attachments/assets/9bbaa805-dd7b-4a98-aa8d-a8e4df01b6d2)
![2024-08-06_23 21 48](https://github.com/user-attachments/assets/6b763463-e2a3-4a4e-9430-f0f929511e66)

### Your Proposal

Fix bug.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Caedis** [comment] 2024-08-06 20:26
![image](https://github.com/user-attachments/assets/c52e0b8d-9399-483d-8d6f-0bf1428a818d)

**Comment by miaowwwwww** [comment] 2024-08-06 23:47
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13341

**Comment by chochem** [comment] 2024-08-07 00:11
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13341

**Closed by chochem** 2024-08-07 00:11 UTC
Labels: Type: bugMinor, Status: Triage
