### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by FiZiK-gh** [GTNewHorizons/GT-New-Horizons-Modpack#16278] opened 2024-05-15 08:32 UTC
### Your GTNH Discord Username

FiZiK_dc

### Your Pack Version

2.6.0

### Your Server

private server

### Java Version

Java 8

### Type of Server

Ultramine

### Your Actions

moving

### Crash Report

https://mclo.gs/hbeMMU3

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment] 2024-05-15 08:37
Duplicate of #16075. Update ae2 or remove angelica to fix.

Also why outdated helpfixer

**Closed by Glease** 2024-05-15 08:37 UTC
Labels: Type: Crash, Status: Triage
