### ISSUE TITLE
Crash when Attack Mobs with Tinker Tools

### ISSUE THREAD

**Issue by Blade8895** [GTNewHorizons/GT-New-Horizons-Modpack#12585] opened 2023-02-13 16:56 UTC
### Your GTNH Discord Username

Blade8895#6067

### Your Pack Version

2.2.9 Dev

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Actions

While attacking with Left Click a Mob with any Tinker Tool result in Server Only Crash.
Crossbow ranged Attack, Right Click working normal.

### Crash Report

[crash-2023-02-13_17.40.26-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10724417/crash-2023-02-13_17.40.26-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Blade8895** [comment] 2023-02-13 17:40
Crashing aswell while mining small ores.
[crash-2023-02-13_18.38.09-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10724775/crash-2023-02-13_18.38.09-server.txt)

**Comment by chochem** [comment] 2023-02-13 18:10
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12567

**Closed by chochem** 2023-02-13 18:10 UTC
Labels: Type: Crash, Status: Triage
