### ISSUE TITLE
Crash in Twilight Forest 

### ISSUE THREAD

**Issue by buddy8704** [GTNewHorizons/GT-New-Horizons-Modpack#16708] opened 2024-07-08 16:36 UTC
### Your GTNH Discord Username

buddyy9651

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

exploring in Twilight Forest, crash every time on this coords

### Crash Report

[crash-2024-07-08_18.13.24-server.txt](https://github.com/user-attachments/files/16131991/crash-2024-07-08_18.13.24-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Lyfts** [comment] 2024-07-08 16:40
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16353 and a gazillion others.

You can update twilight forest to https://github.com/GTNewHorizons/twilightforest/releases/tag/2.6.12

**Closed by Lyfts** 2024-07-08 16:40 UTC
Labels: Type: Crash, Status: Triage
