### ISSUE TITLE
"Cotton and string" quest is not restarts

### ISSUE THREAD

**Issue by NoX-programer** [GTNewHorizons/GT-New-Horizons-Modpack#6701] opened 2020-09-26 12:51 UTC
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
multiplayer; private
#
#### What did you try to do, and what did you expect to happen?
I bought some stings in "Cotton and string" at coinscoins tab, and expect countdown to quest be available
#
#### What happened instead? (Attach screenshots if needed)
There was no countdown, just completed quest
#
#### What do you suggest instead/what changes do you propose?
The quest is in the coinscoins tab, so it's expexted to be restartable, but it's not. If it's not intended, than it's a minor issue.

**Comment by Prometheus0000** [comment] 2020-09-26 14:05
Duplicate of #5540.

**Comment by NoX-programer** [comment] 2020-09-26 14:14
Edit mode is not active, my issue is about only one named quest. Have anyone else "Cotton and string" quest not restarting or it's only me?

**Comment by Prometheus0000** [comment] 2020-09-29 15:33
Are you all on the same server? It's not just about edit mode. Does it also not reset in sp, even after restarting the client?

**Comment by NoX-programer** [comment] 2020-09-30 01:45
I tested in SP, my private server, also another player from GTNH discord (Liquid) confirmed it (looks like he plays on eta - that role he is scecified): https://discordapp.com/channels/181078474394566657/289850721988509696/759423428461068300

**Closed** 2020-11-03 17:15 UTC
Labels: Status: FixedInDev, Type: Quest change
