### ISSUE TITLE
All minecraft:dye items fit into the Miner's Backpack

### ISSUE THREAD

**Issue by p3rsonUnknown** [GTNewHorizons/GT-New-Horizons-Modpack#16568] opened 2024-06-21 06:01 UTC
### Your GTNH Discord Username

p3rsonUnknown

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

a "minecraft:dye" category item shouldn't be picked up into a Miner's backpack, or simply shouldn't be allowed in it.

### The Reality

all "minecraft:dye" items get sorted into the Miner's Backpack. I realised this when my cocoa beans got auto-sorted into the backpack while I was collecting them.

### Your Proposal

Perhaps someone included the "minecraft:dye" category as allowed by accident since lapis is also an item you mine to get and is also under "minecraft:dye" category (I see the category from advanced tooltips "F3 + H"). I also tried GregTech's dyes but they don't fit since they're under their own seperate category "gregtech:gt.metaitem.02" so I assume It's only the vanilla dyes.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by p3rsonUnknown** [comment] 2024-06-21 06:01
![Desktop Screenshot 2024 06 21 - 08 49 22 66](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/159222684/06a4b70a-3a00-439e-beed-3d97cf832d1c)

**Comment by Dream-Master** [comment] 2024-06-21 06:48
@p3rsonUnknown you can just change this here and make a pull request.
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/blob/master/config/forestry/backpacks.cfg

**Comment by p3rsonUnknown** [comment] 2024-06-21 13:53
In the config file "minecraft:dye" category is only included under hunter's backpack but for some reason I can't find most of the ore dictionary names of dyes under the miner's backpack either (only found "dustBone" and "gemLapis"). I have no idea what exactly is causing this at this point.

**Comment by chochem** [comment] 2024-06-21 14:16
the report seems to be incorrect. Cocoa does not enter, nor do other dyes.

_cocoa dust_ however enters because its in that config for whatever reason.

**Comment by p3rsonUnknown** [comment] 2024-06-22 02:16
https://www.youtube.com/watch?v=edeSScRKVLg I have reproduced the problem and recorded it. Also the GregTech dyes also fits now??? I'm geniunely confused because they did not fit before (lootbag drop got auto sorted into the backpack)

**Comment by p3rsonUnknown** [comment] 2024-06-22 02:16
![Desktop Screenshot 2024 06 22 - 05 13 33 14](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/159222684/c4194109-2f03-414c-9593-02c3a19e16ce)

**Comment by p3rsonUnknown** [comment] 2024-06-22 02:57
I don't know how to reproduce with the gregtech paint, but If you pick up bone meal or lapis lazuli then It allows other vanilla dye into the backpack as far as I've tested. This problem persists until you restart the game.

**Comment by p3rsonUnknown** [comment] 2024-06-22 03:01
https://youtu.be/mSuufoQeky4 This is the lapis example | https://youtu.be/70nWHJWTBC0 This is the bone meal example

**Comment by Ethryan** [comment] 2024-06-22 08:16
> I don't know how to reproduce with the gregtech paint, but If you pick up bone meal or lapis lazuli first then It allows other vanilla dye into the backpack as far as I've tested. This problem persists until you restart the game.

This might be why the Backpacks sometimes accept unrelated GT5 items when they shouldn’t. 
Might mean that the whitelisting logic don’t properly limit it to the metavalue correctly.

**Comment by p3rsonUnknown** [comment] 2024-06-22 11:30
What I think is once you put an item in the backpack that's oreDictionary tag is in allowed list ("gemLapis" or "dustBone" in this instance, and idk why bone meal is even allowed in a miner's backpack), It also starts to allow other oreDictionary tags that is included (all dyes share "dye" oreDictionary tag).

**Comment by chochem** [comment] 2024-06-22 12:19
@Ethryan you can reproduce it?

**Comment by p3rsonUnknown** [comment] 2024-06-22 12:45
Check the last 2 youtube links I've sent. It shows how to reproduce the problem.

**Comment by chochem** [comment] 2024-06-22 12:46
sorry but no. light gray dye dust not enter for me.

**Comment by p3rsonUnknown** [comment] 2024-06-22 12:47
I've shown in the video that they actually don't fit into the backpack originally. But after I pick up lapis or bone meal, then they're allowed to fit for some reason.

**Comment by chochem** [comment] 2024-06-22 12:50
ah ok so ignore first video but then the others.

hmm, so you what are saying is that items that enter corrupt the config or alter it somehow - probably not restricted to dyes. Will try and see what I can find.

**Comment by chochem** [comment] 2024-06-22 12:53
alright can reproduce finally.
test 1:
1. pick up light dye: wont work

test 2:
1. pick up lapis (works)
2. pick up light dye (now works!)

seems to work until game restart.

**Comment by Ethryan** [comment] 2024-06-22 13:11
> @Ethryan you can reproduce it?

Yes, I get GT motors and parts in my miners backpack, if it contains any crushed, dirty dust or dusts.

It also happens with machines if the backpack contains any ore blocks.

**Comment by chochem** [comment] 2024-06-22 13:21
ok no idea about motors and without clear steps not something I can test. but https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16568#issuecomment-2184022839 is fixed with this PR.

**Comment by chochem** [comment] 2024-06-22 13:27
well even without any details from you, I am gonna guess its the same thing. they share an itemid with an ore and it then works after you had that ore in.

**Closed** 2024-06-22 16:30 UTC
Labels: Type: bugMinor, Mod: Forestry
