### ISSUE TITLE
Output Hatch and Bus (ME) do not connect to ME System anymore

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#18198] opened 2024-12-02 10:48 UTC
### Your GTNH Discord Username

Ngar

### Your Pack Version

2.7 RC2

### Your Server

Zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

unchanged setup with Output xxx (ME) block should work like in past

### The Reality

unchanged setup with Output xxx (ME) block do not connect anymore to ME coloured cable, without any note/failure info

### Your Proposal

I have tested with uncolored cables - it works. But there's no reason for it, because only the cables I want to connect are placed on the connection side. Without a connection, the buses make no sense. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ngar1** [comment] 2024-12-02 10:51
This (ME) Output blocks were the old ones (unlimited fill). I have setups with the new, they connect.

**Comment by Ngar1** [comment] 2024-12-02 11:59
Wired behavior:
machine (eg LCR) with a rceipte and Output Hatch (ME) say not enought output space for fluid.
Also after change of that output hatch.
Only if a put a normal output hatch was placed - it gets some fluids - and disassemble them again - Output Hatch (ME) works well.

**Comment by serenibyss** [comment] 2024-12-02 14:19
The second issue with "not enough output space" is resolved by #3594. Are you able to provide any more info on how to reproduce the connection issue? I'm not able to reproduce it locally

**Comment by serenibyss** [comment] 2024-12-02 15:44
Logged on to zeta to investigate, only two of many ME output parts disconnected, where others functioned normally. Reconnecting the parts was done successfully by break and replacing the cables, the hatches were able to be left and reconnected. I think this is a force loaded chunk hiccup and not an explicit problem with these parts, since it is known that chunk loading issues can cause ae2 parts to disconnect

**Closed by serenibyss** 2024-12-02 15:44 UTC
Labels: Bug: Minor, Status: Triage
