### ISSUE TITLE
Clicking hopper with right crowbar

### ISSUE THREAD

**Issue by Runakai1** [GTNewHorizons/GT-New-Horizons-Modpack#9634] opened 2022-01-30 08:19 UTC
### Your GTNH Discord Username

Runakai ~ Docsyᵇᵒᵗ

### Your Pack Version

2.1.1.0

### Your Server

gtnh-2.myftb.de

### Type of Server

Don't know

### Your Actions

Title says all. Right clicking with a red crowbaw on a hopper makes the game crash. You can also not join back since if you look at the hopper, it will crash your game again and needs removal with worldedit or similar. 

### Crash Report

https://paste.myftb.de/urufiludis

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Glease** [comment] 2022-01-30 08:26
Duplicate of #8894

**Closed by Glease** 2022-01-30 08:26 UTC
Labels: Type: Crash
