### ISSUE TITLE
Kick when I'm just at the base

### ISSUE THREAD

**Issue by Proficus** [GTNewHorizons/GT-New-Horizons-Modpack#16089] opened 2024-04-29 10:35 UTC
### Your GTNH Discord Username

mihailgrand

### Your Pack Version

2.6.0

### Your Server

Eta

### Java Version

Java 21

### Type of Server

None

### Your Actions

It's the second time I've thrown it out with such an error, when I'm just at the base

### Crash Report

https://mclo.gs/0Ci2uqW

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Ethryan** [comment] 2024-04-29 10:54
Duplicate of #16075

**Closed by Ethryan** 2024-04-29 10:54 UTC
Labels: Type: Crash, Status: Triage
