### ISSUE TITLE
Make Applied Energistics crafting status screen stop switching to another cpu

### ISSUE THREAD

**Issue by Divran** [GTNewHorizons/GT-New-Horizons-Modpack#10232] opened 2022-04-28 21:49 UTC
### Your GTNH Discord Username

Divran

### Your Pack Version

2.1.2.3qf (with some of the mods updated beyond that)

### Your Proposal

This has been a thing in AE2 for as long as it has existed and it's always been a gigantic pain. Please make it so that when you are viewing the crafting status screen, it never ever jumps to a different crafting cpu for any reason other than you manually pressing the button to do so. 

Optionally (your choice) you *could* make it switch if the current craft is finished, but that's it. Otherwise it could simply display a blank screen with a "finished" message on it or something.

### Your Goal

Because viewing AE2 crafting status when you have two dozen export buses with crafting cards is basically impossible.

### Your Vision

Would make the crafting status screen usable.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by miozune** [comment] 2022-04-29 00:35
Maybe https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/97 ?

**Comment by boubou19** [comment] 2022-04-29 07:21
yup duplicate of #9510.

**Comment by GTNHAfx237v7** [comment] 2022-04-29 07:44
They need to be named, yes.

**Comment by boubou19** [comment] 2022-04-29 08:13
according to @repo-alt 
> Well, I can try to stick to the name, but CPU clusters have to be renamed for this to be consistent, because those "CPU: #0" names are autogenerated and will shift with the active CPU changes

**Comment by repo-alt** [comment] 2022-04-29 09:56
w/o names it's kind of hard to distinguish them to keep order

**Comment by Divran** [comment] 2022-04-29 11:23
honestly that menu has needed a complete rewrite since ae2 was first released, it's shit. I could probably try myself but I have no clue how to set up a minecraft dev environment and am way too lazy to figure it out.

**Comment by kubasz** [comment] 2022-04-29 11:25
Could maybe use this for reference <https://github.com/AppliedEnergistics/Applied-Energistics-2/releases/tag/forge%2Fv10.1.0-beta.1> but I have no idea how much code for 1.18 guis is backportable to 1.7.10

**Comment by Divran** [comment] 2022-04-29 18:15
I have tried naming cpus and I can confirm that it does not work. We are using this version: `appliedenergistics2-1.7.10-rv3-beta-82-GTNH-6-g214a762.jar` I have no idea if this is too old to have the feature yet

**Comment by Divran** [comment] 2022-05-01 17:10
After having paid attention to it some more, it doesn't seem to work at all. It'll still jump to random other pages. Either the fix does absolutely nothing, or the version of AE we have installed doesn't have the fix in it.

**Comment by kubasz** [comment] 2022-05-01 17:28
I'm currently working on backporting the cpu selection table from the link in my comment above, which should also fix this issue. I'm mostly done, just need to add a couple more rendered elements and figure out why my new client packet handler does not get invoked to be updated with new data from the server

**Comment by Divran** [comment] 2022-05-01 18:44
Sounds great, but I hope that code doesn't rely on storing the index of a constantly changing array as its only means of keeping track of which tab to display...

**Comment by kubasz** [comment] 2022-05-01 18:46
> Sounds great, but I hope that code doesn't rely on storing the index of a constantly changing array as its only means of keeping track of which tab to display...

It doesn't, it keeps a persistent map of objects to indices

**Comment by kubasz** [comment] 2022-05-01 20:42
@Divran would you be able to download the build from <http://jenkins.usrv.eu:8080/job/Applied-Energistics/240/> and confirm that it does actually fix the issue?

**Closed** 2022-05-01 21:18 UTC
Labels: Type: Suggestion, Mod: AE2

**Comment by Divran** [comment] 2022-05-01 21:42
amazing, please let me know when it's ready for download so we can give it a try (from <http://jenkins.usrv.eu:8080/job/Applied-Energistics/> I assume? yep looks correct)

**Comment by kubasz** [comment] 2022-05-05 16:12
@Divran while the WCT doesn't work right now, standard ae2 wireless terminals should work

**Comment by boubou19** [comment] 2022-05-05 16:46
> Ah, I guess it implements its own copy of the UI so it will just have to be copied over, it's a separate mod

Don't copy it, make WCT use the already existing GUI. That way maintainability becomes more and more easier.

**Comment by repo-alt** [comment] 2022-05-06 07:17
WCT historically copies all UI, because UI widgets are not part of AE2 API. We _may_ refactor that but it takes time and some accuracy

**Comment by Divran** [comment] 2022-05-06 07:59
Oh and while this is being changed already, another hopefully very easy fix that would be very useful would be to make the crafting status UI 100% tall just like the main UI. I believe I use the "normal" UI scale and for me the status UI is a tiny box in the center of the screen. Lots of scrolling is always needed to see anything.

**Comment by kubasz** [comment] 2022-05-06 08:06
> Oh and while this is being changed already, another hopefully very easy fix that would be very useful would be to make the crafting status UI 100% tall just like the main UI. I believe I use the "normal" UI scale and for me the status UI is a tiny box in the center of the screen. Lots of scrolling is always needed to see anything.

That's not really an easy fix, you can open a separate ticket for that

**Comment by Divran** [comment] 2022-05-06 08:27
> > Oh and while this is being changed already, another hopefully very easy fix that would be very useful would be to make the crafting status UI 100% tall just like the main UI. I believe I use the "normal" UI scale and for me the status UI is a tiny box in the center of the screen. Lots of scrolling is always needed to see anything.
> 
> That's not really an easy fix, you can open a separate ticket for that

that's a bit weird. In most UIs it'd just be a matter of changing a single variable. I thought worst case in minecraft's case with several different UI scales it'd be a few variables, but alright
