### ISSUE TITLE
Wireless Crafting Terminal unusable on a Server if it has an Infinity Booster Card installed

### ISSUE THREAD

**Issue by glowredman** [GTNewHorizons/GT-New-Horizons-Modpack#10843] opened 2022-07-27 19:23 UTC
### Your GTNH Discord Username

glowredman#1337

### Your Pack Version

Private modpack but this bug has been confirmed on Zeta too (2.1.2.4-18-pre)

### Your Server

Private server

### Type of Server

Vanilla Forge

### Your Expectation

After putting an Infinity Booster Card in my (linked) Wireless Crafting Terminal, I expect it to work like before, just with unlimited range.

WCT version: 1.8.8.6
AE2 version: rv3-beta-91-GTNH-2-gf8a536d

### The Reality

The client is disconnected from the server.
![grafik](https://user-images.githubusercontent.com/35727266/181354377-1151b2ca-b725-49db-bdbe-69effc63b9cf.png)
The server only shows messages regarding the disconnect (like any other disconnect) but the client throws an exception:
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9202949/latest.3.log)

### Your Proposal

Fix it.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by repo-alt** [comment] 2022-07-28 10:19
Looks like the bug is not in WCT, or at least not only in WCT

**Comment by miozune** [comment] 2022-08-02 07:10
Can we close this?

**Comment by repo-alt** [comment] 2022-08-02 07:59
idk, I could not reproduce the bug outside the modpack

**Comment by glowredman** [comment] 2022-08-02 16:13
I haven't had this or any other problem since https://github.com/GTNewHorizons/WirelessCraftingTerminal/pull/19, acoording to @repo-alt it's only a bandaid fix though.

**Comment by repo-alt** [comment] 2022-08-02 20:02
I guess we may close it for now and if testing will reveal any other symptomes we may always reopen it

**Closed by repo-alt** 2022-08-02 20:02 UTC
Labels: Type: bugMajor, Mod: WCT
