### ISSUE TITLE
Ross128b disconnecting players/chunk lag

### ISSUE THREAD

**Issue by anoldshoe** [GTNewHorizons/GT-New-Horizons-Modpack#7352] opened 2021-01-19 17:42 UTC
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
MMCC Ironman
#
#### What did you try to do, and what did you expect to happen?
Tried wiping dimension
#
#### What happened instead? (Attach screenshots if needed)
lag and dc's persist
#
#### What do you suggest instead/what changes do you propose?
UNK
[logs.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5837599/logs.txt)

**Comment by Prometheus0000** [comment] 2021-01-19 17:46
I heard bart already fixed this

**Comment by Prometheus0000** [comment] 2021-01-19 17:47
Duplicate of #7235, probably? If it isn't, say so.

**Closed by Prometheus0000** 2021-01-19 17:47 UTC
Labels: Type: duplicate
