### ISSUE TITLE
Some of the packager recipes consume schematics

### ISSUE THREAD

**Issue by Pxx500** [GTNewHorizons/GT-New-Horizons-Modpack#8277] opened 2021-07-22 09:21 UTC
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Automatic mining system was doing it's job.
#
#### What happened instead? (Attach screenshots if needed)
Mining system mined gypsum and blocked packager by destroying schematic
#
#### What do you suggest instead/what changes do you propose?
Fix recipes in packager because some of them consume Schematic (Dusts).
#
#### What is your GTNH Discord username?
Pxx500
#

List of dusts I found:
Cooked ZrCl4
Gypsum
Electrical Steel
Redstone Alloy
Calcium Carbonate
Manure Byproduct
ZrCl4
Lithium Hydroxide
Soularium
Phtalic Anhydride
Organic Fertilizer
Energetic Alloy
Hydrated Lime
Conductive Iron
Pulsating Iron
Vibrant Alloy

Of course some of these may not be useful in any way. I've listed some of those I found and I've omitted those I think are useless

**Comment by Glease** [comment] 2021-07-22 09:25
Duplicate of #8100.

**Comment by boubou19** [comment] 2021-07-22 09:25
Please grab a newer gt++ version on jenkins to fix this issue

**Closed by Glease** 2021-07-22 09:25 UTC
