### ISSUE TITLE
Ender fluid conduit and fluid storage bus interaction

### ISSUE THREAD

**Issue by Shyrff** [GTNewHorizons/GT-New-Horizons-Modpack#6954] opened 2020-11-18 08:32 UTC
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
private, tested in SP anyway
#
#### What did you try to do, and what did you expect to happen?
I've connected several supertanks with ender fluid conduits and configured to always extract. I've put fluid storage bus on this conduit system and hooked it to network. I see fluids detected in fluid monitor but I can not "interact" with them: neither take it with cell from monitor nor export it to another tank with fluid bus.
#
#### What happened instead? (Attach screenshots if needed)
Ender fluid conduit and fluid storage bus interaction is incosistent: fluids are detected but not acceptable.
My first hypothesis was that fluid conduit IO capabilities (200/800 mb/t) are too low, but increasing it to be more than 1000 mb/t 
did not help.
#
#### What do you suggest instead/what changes do you propose?
At least I want to know how the setup is intended to work.
Secondly I want the behaviour to be consistent: either storage bus do not see fluids from conduit or it should be able to interact with it.
Proposed setup can be little bit overpowered, but current state is too frustrating.

**Comment by GTNH-Afx237v7** [comment] 2020-11-18 08:41
The fluid storage bus is meant to interact with actual tanks or machine internal Tanks. The conduits are not tanks, hence it surprises me that the storage bus can actually see the fluids. When connected to a conduit/conduit network, the fluid storage bus should not display anything.

**Comment by repo-alt** [comment] 2020-11-18 09:09
... _Carthaginem esse delendam_, that is, EC2 should be disabled for good

**Comment by GTNH-Afx237v7** [comment] 2020-11-18 09:17
Some things are good, haven’t had any issues with fluid export or import busses for example. It’s just storage busses and tank interaction that is sometimes buggy...

**Comment by Skiftcha** [comment] 2020-11-18 10:43
same with gt pipes. fluid monitor shows fluid but cannot access it

**Comment by Prometheus0000** [comment] 2020-11-18 17:29
So, not a bug? Can we just close this then? Fixing EC2 is a whole other thing, and this is just how conduits work.

**Closed** 2020-12-07 22:13 UTC
Labels: Mod: EC2, Mod: Ender IO, Type: Not a Bug
