### ISSUE TITLE
IsaMill only being able to use base stone ore variants for its milling process

### ISSUE THREAD

**Issue by scaropio** [GTNewHorizons/GT-New-Horizons-Modpack#17277] opened 2024-09-10 01:19 UTC
### Your GTNH Discord Username

scorpionletal

### Your Pack Version

2.6

### Your Server

Pirvate Server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

We made an IsaMill to try to get less painful indium,

### The Reality

But when we built it we noticed how our "Black Granite" variant of the Sphalerite Ore wasnt being process, we thought it was because the multi didnt accept 2 hatches, but after cheating 16 Stone variants of the Sphalerite Ore we found out it didnt work with their other Stones variants, but it works with its crushed variant.

### Your Proposal

I think this is only a wrong oredict issue on this part because its a quite odd multiblock and mechanic to use.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2024-09-11 08:42
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17139

**Closed by chochem** 2024-09-11 08:42 UTC
Labels: Type: bugMinor, Status: Triage
