### ISSUE TITLE
Some Pyrolyze recipes display incorrectly

### ISSUE THREAD

**Issue by ah-OOG-ah** [GTNewHorizons/GT-New-Horizons-Modpack#12258] opened 2023-01-12 22:44 UTC
### Your GTNH Discord Username

OmniSlaves#6732

### Your Pack Version

2.2.8 w/ updated GT5u, GT++, MUI

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Wood Log + Steam > Charcoal and Coal Gas in the Pyrolyse Oven should need 20 logs.

### The Reality

Using GT++ 1.7.176, GT5u 5.09.41.196, and MUI 1.0.37, some recipes display as only needing 1 log while outputting the same amount of charcoal.
![image](https://user-images.githubusercontent.com/75745146/212196713-ef942862-1216-4237-8589-d2bf1cfe7332.png)

### Your Proposal

Remove the 1 log recipes

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by YTXilo** [comment] 2023-01-12 22:49
duplicate of #12091 , already fixed

**Comment by chochem** [comment] 2023-01-12 22:49
its just a NEI bug. see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12075.

**Comment by YTXilo** [comment] 2023-01-12 22:50
lol wtf, I screwed that up

**Closed** 2023-01-12 22:51 UTC
Labels: Type: Duplicate, Type: bugMinor
