### ISSUE TITLE
Issue with LV sticky resin recipe

### ISSUE THREAD

**Issue by kawika98** [GTNewHorizons/GT-New-Horizons-Modpack#8239] opened 2021-07-14 14:25 UTC
#### Which modpack version are you using?
2.1.0.0QF1-1.7.10
#
#### If in multiplayer; On which server does this happen? 
Single player world
#
#### What did you try to do, and what did you expect to happen?
In the LV age, there is a recipe with the centrifuge that allows you to sometimes get sticky resin (and other things) from rubber wood. 
![image](https://user-images.githubusercontent.com/57806930/125638730-5bf81ac6-de2b-4bbb-89cf-c02495dd6bc2.png)
#
#### What happened instead? (Attach screenshots if needed)
Though this recipe does not give any other products, it only gives 60L of methane.
![image](https://user-images.githubusercontent.com/57806930/125638803-035763da-2363-4c95-9b4e-d4a241509c44.png)
![image](https://user-images.githubusercontent.com/57806930/125638839-52666865-8a7e-4479-b347-0449c6c483b8.png)
#
#### What do you suggest instead/what changes do you propose?
I suggest that the centrifuge recipe be fixed so that it gives the by-products as it shows in JEI
#
#### What is your GTNH Discord username?
potatokiller234#3624

**Comment by GTNH-Afx237v7** [comment] 2021-07-14 15:08
Duplicate of #5243. please update to latest version (2.1.1.0).

**Closed** 2021-07-14 18:00 UTC
Labels: Type: duplicate
