### ISSUE TITLE
Multi-smelter lag

### ISSUE THREAD

**Issue by GTNH-Colen** [GTNewHorizons/GT-New-Horizons-Modpack#6416] opened 2020-07-21 01:09 UTC
#### Which modpack version are you using?
2.0.9.0 QF4
#

As part of the recent lag-busting series I've noticed this multiblock causing an abnormally high amount of lag.

![unknown](https://user-images.githubusercontent.com/54497873/88001001-f20e2400-caf6-11ea-892c-35a015957c7a.png)

Any input on why this might be happening or how to fix it would be greatly appreciated.

**Comment by Glease** [comment] 2020-08-17 20:57
Similiar to #6515, this go through the whole smelting list as well. The only reason of this using less time is because smelting recipe table is smaller... I guess we could use a small thread local buffer of 16 to get rid of 80% of queries.

**Comment by repo-alt** [comment] 2020-09-02 15:56
Indeed simple MRU recipe cache would do much good to many machines

**Comment by repo-alt** [comment] 2020-09-07 21:33
@GTNH-Colen How many input buses does that smelter have? Somehow I was not able to reproduce such a big lag locally. I added  a furnace recipe cache anyway, because iterating the whole list every time is just wrong.

**Comment by GTNH-Colen** [comment] 2020-09-07 22:57
> @GTNH-Colen How many input buses does that smelter have? Somehow I was not able to reproduce such a big lag locally. I added a furnace recipe cache anyway, because iterating the whole list every time is just wrong.

I think 3? Nothing insane.

**Comment by boubou19** [comment] 2020-09-22 18:40
![2020-09-22_20 38 13](https://user-images.githubusercontent.com/12850933/93923493-be789180-fd13-11ea-88d8-188724751fc8.png)
it's fixed in the 2.0.9.1 dev pack

**Closed** 2020-11-03 17:15 UTC
Labels: Status: FixedInDev, Type: Lag
