### ISSUE TITLE
Twilight Forest crashed my world near the Lich Tower and don't let me load in

### ISSUE THREAD

**Issue by P1agy** [GTNewHorizons/GT-New-Horizons-Modpack#17904] opened 2024-11-08 09:51 UTC
### Your GTNH Discord Username

Tomkov

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Just wandered around TF dimension in search of the Labyrinth. As soon as I approach one of the Lich Towers, my world crashes out  and after trying to boot back in, the loading stops at 0%.

Rolling back to the last backup allows me to continue playing in my world, but as soon as I approach the same tower again, the crash happens again.

### Crash Report

1st appearance: https://mclo.gs/DtAaqmg

Last crash report: https://mclo.gs/Vfc9BZo

Video below from trying to recreate crash. The latest crash report is related to him.

Crash recreate: https://imgur.com/a/QdwHyAD

![crash](https://github.com/user-attachments/assets/1e7dae80-851e-4452-bdef-a67900247731)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Lyfts** [comment] 2024-11-08 10:02
![s](https://github.com/user-attachments/assets/d9286e8a-10d1-493c-b13b-6c59d3cc2440)
Searching "Twilight Forest", "Nagastone" or something similar on the issue tracker results in about 50 issues identical to this one. 

Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16353 and many others.

**Closed by Lyfts** 2024-11-08 10:02 UTC
Labels: Type: Crash, Status: Triage
