### ISSUE TITLE
super buffer cause lags. (threaded and normal one)

### ISSUE THREAD

**Issue by zgggz** [GTNewHorizons/GT-New-Horizons-Modpack#6472] opened 2020-08-02 06:23 UTC
#### Which modpack version are you using?
2.0.9

#### If in multiplayer; On which server does this happen? 
prospercraft

#### What did you try to do, and what did you expect to happen?
setup bezos packager+super buffer seted to 9 stack ouput. ZPM voltage

first screen - normal one. 
![super simple one](https://user-images.githubusercontent.com/64369015/89116887-a9188100-d4a1-11ea-874e-94352f69e5b6.png)

Secound - threaded one.
![super threaded](https://user-images.githubusercontent.com/64369015/89116886-a3bb3680-d4a1-11ea-9117-84174a71d1e2.png)

**Comment by chochem** [comment] 2020-08-02 07:42
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6414

can be closed

**Closed** 2020-08-02 07:53 UTC
