### ISSUE TITLE
Crash with unidentified cause shortly after creating new world

### ISSUE THREAD

**Issue by hallucinogender** [GTNewHorizons/GT-New-Horizons-Modpack#11179] opened 2022-08-30 22:03 UTC
### Your GTNH Discord Username

hallucinogender#1408

### Your Pack Version

2.1.2.4-29-pre

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Started a new world. Moved around a bit. Game crashed immediately after. The world cannot be reloaded after the crash, and any attempt to load up the world again crashes the game instantly.

Potentially relevant is the fact that I had previously started a new world with the same name, and deleted it (as well as deleting the Journeymap file for that world so that the identical name would not cause the map to be copied over), in an attempt to get a starting biome I liked better. I did not close and reopen the game between the first world and the replacement world, though I did close and reopen the game after the crash and before doing anything else.

This has also occurred when I tested doing the same thing without deleting the Journeymap file.

### Crash Report

First crash:
[crash-2022-08-30_22.46.08-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9456913/crash-2022-08-30_22.46.08-server.txt)

Crash after attempting to rejoin the broken world immediately after it crashed:
[crash-2022-08-30_22.46.38-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9456916/crash-2022-08-30_22.46.38-server.txt)

Second crash when testing the conditions:
[crash-2022-08-30_22.53.42-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9456920/crash-2022-08-30_22.53.42-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2022-08-30 22:04
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10377. can you post your logs there please?

**Closed by chochem** 2022-08-30 22:04 UTC
Labels: Type: Duplicate, Type: Crash
