### ISSUE TITLE
Extra ticket!

### ISSUE THREAD

**Issue by NoNameISNoMan** [GTNewHorizons/GT-New-Horizons-Modpack#12660] opened 2023-02-20 08:47 UTC
### Your GTNH Discord Username

nooneinparticular#8014

### Your Pack Version

2.2.8

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

I tried to open a Tinkers workbench. That's it!

### Crash Report

https://paste.ubuntu.com/p/8KGY9FGhpq/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2023-02-20 10:05
this happens consistently?

**Comment by miozune** [comment] 2023-02-20 10:08
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12658

**Closed by miozune** 2023-02-20 10:08 UTC
Labels: Type: Crash, Mod: Tinkers' Construct, Mod: Minecraft, Status: Triage
