### ISSUE TITLE
Optionally allow solid casings directly adjacent to a Mega Blast Furnace's controller

### ISSUE THREAD

**Issue by querns** [GTNewHorizons/GT-New-Horizons-Modpack#8870] opened 2021-11-18 15:32 UTC
### Your GTNH Discord Username

querns#3785

### Your Pack Version

2.1.1.4QF2

### Your Proposal

I would like for the four blocks adjacent to the MEBF's controller to be allowed to be a solid block of some sort. These could be heat proof casings, or coils, or something else entirely.

![Suggested areas for solid blocks](https://i.imgur.com/XLquseS.png)

### Your Goal

Tiered glass cannot conduct or propagate redstone signals. This means that there are no faces on the MEBF controller available for things like Machine Controller or Activity Detector covers.

![Showing redstone propagation with tiered glass vs a solid block](https://i.imgur.com/KtV73tn.png)

### Your Vision

Allowing covers to be used on the MEBF allows for more interesting automation possibilities. I believe that reducing the glass requirement from 1008 to a potential 1004 is not a particularly high reduction in difficulty for constructing an MEBF.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by bombcar** [comment] 2021-11-18 17:32
This would look a bit weird - would it not be easier to just allow the controller to move down two? Perhaps that would require changes in existing setups if MBs can't handle two possible locations for controller.

If we do allow casings around it - I would propose allowing them ALL around it so it would be a square.

**Comment by GTNH-Afx237v7** [comment] 2021-11-18 18:16
Wireless redstone cover

**Comment by querns** [comment] 2021-11-18 18:18
How are you supposed to send a signal to the wireless redstone covers?

**Comment by boubou19** [comment] 2021-11-18 18:22
duplicate of #8245

**Closed by boubou19** 2021-11-18 18:22 UTC
Labels: Type: suggestion, Status: Triage

**Comment by bombcar** [comment] 2021-11-18 18:24
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/5526#issuecomment-863044912
