### ISSUE TITLE
Twilight Forest crashes server

### ISSUE THREAD

**Issue by crueltekk** [GTNewHorizons/GT-New-Horizons-Modpack#16394] opened 2024-05-27 17:06 UTC
### Your GTNH Discord Username

x3d4r

### Your Pack Version

2.6.1

### Your Server

Private Dedi Server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Actions

My mate was traveling through TF when the server crashed. Happened again when he joined after restart. I took a look around that area he was (got his position from crashlog). Everything was fine first but it crashed on me too.
We cant rejoin now, server crashes instantly.

### Crash Report

[crash-2024-05-27_18.40.42-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15458421/crash-2024-05-27_18.40.42-server.txt)
[crash-2024-05-27_18.47.06-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15458422/crash-2024-05-27_18.47.06-server.txt)
[crash-2024-05-27_18.55.22-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15458423/crash-2024-05-27_18.55.22-server.txt)

That are all crashlogs for that situation.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by BlueHero233** [comment] 2024-10-23 20:43
Have you updated Twilight Forest to 2.6.12? if not this is a duplicate of a already fixed issue

**Comment by BlueHero233** [comment] 2024-10-26 23:12
Closed, known issue already fixed

**Closed by BlueHero233** 2024-10-26 23:12 UTC
Labels: Type: Crash, Status: Triage
