### ISSUE TITLE
The lv auto workbench doesn't work

### ISSUE THREAD

**Issue by Longusernamern** [GTNewHorizons/GT-New-Horizons-Modpack#14329] opened 2023-08-26 00:41 UTC
### Your GTNH Discord Username

hh_h_h

### Your Pack Version

2.3.0

### Your Server

Modded Minecraft Club

### Java Version

Java 17

### Type of Server

Don't know

### Your Expectation

The workbench to craft when items are put in it
![wefwgwrrg](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/43304100/d5c8ef92-3f31-4ca9-8bce-ee8eb12b74ef)

### The Reality

Nothing is crafted. I was told it was because the energy buffer isn't high enough for it to do anything. 

### Your Proposal

Do whatever to fix the lv auto workbench or remove it. I can't even put it in the arc furnace or macerator so it's currently sitting on a pillar for shame. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by desagas** [comment] 2023-08-26 01:21
Do the quests for these machines not state that power is required for it to perform work, but is not required for it to move items, including the chests from this mod addon? Does it work when you properly power it with LV power?

**Comment by Lyfts** [comment] 2023-08-26 15:27
Already fixed here: https://github.com/GTNewHorizons/GTplusplus/pull/630

**Comment by miozune** [comment] 2023-08-27 07:45
As mentioned, duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11190

**Closed by miozune** 2023-08-27 07:45 UTC
Labels: Type: bugMinor, Status: Triage
