### ISSUE TITLE
Crop replicator takes a little longer than expected

### ISSUE THREAD

**Issue by DannyParker0001** [GTNewHorizons/GT-New-Horizons-Modpack#15196] opened 2023-12-22 12:53 UTC
### Your Pack Version

gtnh-nightly-2023-12-06+250-server.zip

### Your Server

private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

I put 1uum and 1 stickreed seed and it takes a playable amount of time

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/24753108/a8885681-765c-4ba3-b0a6-7641bb7c1e91)
it takes a second to craft and 3 uum instead of 1

### Your Proposal

takes less than a day to duplicate the crop 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by StaffiX** [comment] 2023-12-22 13:15
duplicate of #15132

**Closed** 2023-12-22 13:19 UTC
Labels: Type: bugMinor, Status: Triage
