### ISSUE TITLE
Inventory check causes crash.

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#6038] opened 2020-05-04 12:53 UTC
#### Which modpack version are you using?
2.0.8.3～2.0.8.9
#
#### If in multiplayer; On which server does this happen? 
Single
#
#### What did you try to do, and what did you expect to happen?
I tried to login to the world.
#
#### What happened instead? (Attach screenshots if needed)
Game Crash.
I tried delete the player's inventory data and login again but game crashes....

Crash Report:
[crash-2020-05-04_21.35.20-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4574702/crash-2020-05-04_21.35.20-server.txt)
#
#### What do you suggest instead/what changes do you propose?
Fix it.

**Comment by Prometheus0000** [comment] 2020-05-04 14:21
Try listing the EXACT version next time. Duplicate of #6005

**Closed** 2020-05-04 14:33 UTC
