### ISSUE TITLE
Cannot see ore generation locations in NEI 

### ISSUE THREAD

**Issue by KeveKeve4** [GTNewHorizons/GT-New-Horizons-Modpack#11806] opened 2022-11-09 20:48 UTC
### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Open To LAN

### Your Expectation

opens a menu in which i can see where a particular ore is generated

### The Reality

A text apears saying ''There was error durring loading recipe.Please check log for details.
btw here is the log
![Screenshot 2022-11-09 224134](https://user-images.githubusercontent.com/117863532/200938296-5177b6c4-fdeb-41eb-8a96-6e41f57f53e6.png)
[GregTech.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9974975/GregTech.log)

### Your Proposal

im not smart with the programmy side of mods so i wouldnt know. sorry

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment] 2022-11-10 03:45
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11461

**Closed by miozune** 2022-11-10 03:45 UTC
Labels: Type: bugMinor, Status: Triage
