### ISSUE TITLE
Essentia Condenser Needs to be nerfed.

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#7889] opened 2021-05-01 06:06 UTC
#### Which modpack version are you using?
2.1.0.6b but this affects all versions
#
#### What did you try to do, and what did you expect to happen? and What happened instead?
Essentia condenser is bugged right now, and instead of storing only 3k of each aspect. Currently you can use golems to push that past it's max to an infinite storage size. 
#
#### What do you suggest instead/what changes do you propose?
I suggest that either 

A. you remove the golem ability to interact with the thing (could be an issue since it needs a golem to put the first essentia in) to which I suggest giving it the ability to just suck essentia from any source no matter what (like it does after a golem put essentia into it) so that it can just store the 3000 and be done with it, all said, all done.

or

 B. Don't do anything, remove the cap, make it official, I realize that this is suppose to be an endgame Thaumcraft essentia storage item, it works with ae2+thaumcraft addon, it works well with infusion altars, in general it is great because it removes a lot of the lag that could be associated with thaumcraft since it gets rid of the need to use so many jars and doesn't really have that much in terms of visual affects
          - Therefore my suggestion here is ALMOST DON'T DO ANYTHING TO IT, and by the gods do *not* up the recipe to include to ichorium ingots! it would be like the worst solution to the issue since it'd just drive more people away from TC and like, why? It already is nerfed to hell in a lot of areas it doesn't need another ichorium ingot recipe in the book.
          - Honestly, in this case you could remove the cap from the multi entirely! It would benefit the main server's so much considering how thaumcraft has seemed to be a major issue for y'all graphically wise! So this glitch could be a blessing hidden in disguise because if you could actually give the recipe a huge buff that would encourage people to start using it earlier on it would prevent people from using jars, I don't personally know if jars cause plenty of lag but i have the strong feeling they probably do. And the condenser could be the solution if y'all'd own it and remove the cap!

Y'all know me, I post a lot about TC and buffs for it. I have *literally never* posted a nerf for it, *never*, you know that I think Thaumcraft needs a lot of buffs so that it progressively becomes more and more viable. I think that it speaks to matter at hand that, I, of all people think this issue needs to be solved since it is technically a gamebreaking glitch the level of the soul brazier. But, since it could solve a graphical bit of issue (if it exists), especially since a lot of the longterm TC players have large ass jar facilities sometimes(sometimes its AE but eh not always), I believe that if it was treated right, that this could actually be a massive boon!
#
#### What is your GTNH Discord username?
Alastors_Game

**Comment by Glease** [comment] 2021-11-29 19:44
Duplicate of #2990

**Closed by Glease** 2021-11-29 19:44 UTC
Labels: Mod: Thaumcraft
