### ISSUE TITLE
Mystical Bee not recognized by GeneBank

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#5997] opened 2020-04-27 17:11 UTC
#### Which modpack version are you using?
2083
#
#### If in multiplayer; On which server does this happen? 
MyFTB
#
#### What did you try to do, and what did you expect to happen?
sequenced Mystical Bee
also the white diamond bee don´t bee stored in Gene Bank (only the blue one)
#
#### What happened instead? (Attach screenshots if needed)
not recogniced or listed in GeneBank
![Mystical01](https://user-images.githubusercontent.com/7759876/80400135-a7e02280-88ba-11ea-9640-9c984ca83635.PNG)
![Mystical02](https://user-images.githubusercontent.com/7759876/80400146-aca4d680-88ba-11ea-906d-4925a9f3b323.PNG)
![Mystical03](https://user-images.githubusercontent.com/7759876/80400154-b0385d80-88ba-11ea-8bc1-c7ef69ea8170.PNG)
![Mystical04](https://user-images.githubusercontent.com/7759876/80400163-b4647b00-88ba-11ea-9908-ad5c2591955a.PNG)

**Comment by yukieiji** [comment] 2020-04-28 07:31
Duplicate of #4930

**Comment by Ngar1** [comment] 2020-05-12 22:39
mystical could be recognized by genebank
testet with GTNH-1.7.10-2.0.9.0-pre7-dev.zip same world, SP -> solved
![Mystical_bee_03](https://user-images.githubusercontent.com/7759876/81752660-34413680-94b2-11ea-92d6-cf32827b6191.JPG)

**Closed** 2020-06-07 18:51 UTC
Labels: Bees, FixedInDev, bugMinor, duplicate
