### ISSUE TITLE
Crash when eating food restoring zero hunger

### ISSUE THREAD

**Issue by rjm0999** [GTNewHorizons/GT-New-Horizons-Modpack#14147] opened 2023-08-04 14:13 UTC
### Your GTNH Discord Username

rmarks1999

### Your Pack Version

2.3.5

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Actions

When the diminishing returns on food get to the point a food restores zero hunger, eating that food causes a crash.

### Crash Report

[crash-2023-08-04_10.06.05-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12261569/crash-2023-08-04_10.06.05-client.txt)
[crash-2023-08-04_01.01.50-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12261570/crash-2023-08-04_01.01.50-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2023-08-04 14:16
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14033, https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14059, https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14065, https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14106

**Closed by chochem** 2023-08-04 14:16 UTC
Labels: Type: Crash, Status: Triage
