### ISSUE TITLE
Tinkers Construct/Sodium Crash

### ISSUE THREAD

**Issue by dariusgemini** [GTNewHorizons/GT-New-Horizons-Modpack#17930] opened 2024-11-10 16:38 UTC
### Your GTNH Discord Username

DarDarBinks

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

I existed. Seriously.

### Crash Report

https://mclo.gs/dlXejZ2

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Lyfts** [comment] 2024-11-10 16:44
Dupe of https://github.com/GTNewHorizons/Angelica/issues/543

You can update tinkers to https://github.com/GTNewHorizons/TinkersConstruct/releases/tag/1.12.5-GTNH (or just update to 2.7 beta)

**Closed by Lyfts** 2024-11-10 16:44 UTC
Labels: Crash, Status: Triage
