### ISSUE TITLE
Thaumcraft infusion allowing simmiliar but wrong items

### ISSUE THREAD

**Issue by DovydasDomkus** [GTNewHorizons/GT-New-Horizons-Modpack#14336] opened 2023-08-26 14:57 UTC
### Your GTNH Discord Username

Bonkus#3268

### Your Pack Version

2.3.0

### Your Server

private server

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

When crafting decanting core NEI suggested using ztones tank block instead of a buildcraft tank.

### The Reality

The infusion was succesful consuming ztones tank block.

### Your Proposal

fix both NEI and infusion recipe.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment] 2023-08-27 09:37
Technically duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12938

**Closed by miozune** 2023-08-27 09:37 UTC
Labels: Type: bugMinor, Mod: Thaumcraft
