### ISSUE TITLE
Keep Crashing when loading world

### ISSUE THREAD

**Issue by Qwerkus11** [GTNewHorizons/GT-New-Horizons-Modpack#12305] opened 2023-01-17 22:50 UTC
### Your GTNH Discord Username

Qwerkus1027#7588

### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Single Player

### Your Actions

[crash-2023-01-17_23.24.12-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10439920/crash-2023-01-17_23.24.12-client.txt)
[crash-2023-01-17_23.30.07-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10439922/crash-2023-01-17_23.30.07-client.txt)
[crash-2023-01-17_23.34.59-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10439923/crash-2023-01-17_23.34.59-client.txt)
[crash-2023-01-17_23.04.22-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10439925/crash-2023-01-17_23.04.22-client.txt)

[crash-2023-01-17_23.09.02-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10439926/crash-2023-01-17_23.09.02-client.txt)

### Crash Report

Game keeps crashing, i can start the world and play once at the first startup, from the second cant load the world keep crashing, i can only play when delete whole tekkit stuff and %appdata% folder, each crash report says at the end, there is a line for example (The RF API that is being used (1.7.10R1.3.1 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.13B1 from extrautilities-1.2.13a.jar).) and i delete the mentioned mod, start the game and another crash report mention another mod delete and again and again mention a mod.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2023-01-17 23:27
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11433

**Closed by chochem** 2023-01-17 23:27 UTC
Labels: Type: Crash, Status: Triage

**Comment by Qwerkus11** [comment] 2023-01-21 08:43
#11433 did not resolve my problem

**Comment by Qwerkus11** [comment] 2023-01-21 13:05
Downgraded back to 2.1.0.0, only this option worked for me.
Started a new world at 2.2.0.0, when leaving planet crashed, even when i deleted gravi suit,
