### ISSUE TITLE
The server crashes when a player explores the twilight forest

### ISSUE THREAD

**Issue by LinGatra** [GTNewHorizons/GT-New-Horizons-Modpack#17048] opened 2024-08-19 17:27 UTC
### Your GTNH Discord Username

lingatra

### Your Pack Version

2.6.1

### Your Server

private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Actions

I was exploring the twilight forest, and at some point our server went down. The reasons says 'Cannot invoke “net.minecraftforge.common.util.ForgeDirection.ordinal()” because “this.EtchedNagastoneNorth” is null', But I can't figure out the exact cause - any attempt to walk around leads to another crash. This has happened in various locations around the world several times.

### Crash Report

[latest.log](https://github.com/user-attachments/files/16663427/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Lyfts** [comment] 2024-08-19 17:32
![s](https://github.com/user-attachments/assets/d9286e8a-10d1-493c-b13b-6c59d3cc2440)
You sure? Anyways duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16353 and about a thousand others

**Closed by Lyfts** 2024-08-19 17:32 UTC
Labels: Type: Crash, Status: Triage
