### ISSUE TITLE
Crash on Inventory?

### ISSUE THREAD

**Issue by Alastors** [GTNewHorizons/GT-New-Horizons-Modpack#7450] opened 2021-02-09 18:34 UTC
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
My server
#
#### What did you try to do, and what did you expect to happen?
open inventory
#
#### What happened instead? (Attach screenshots if needed)
the whole client crashes
#### What do you suggest instead/what changes do you propose?
idk[](url)

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2/9/21 12:08 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at codechicken.nei.LayoutManager.renderSlotOverlay(LayoutManager.java:721)
	at codechicken.nei.guihook.GuiContainerManager.renderSlotOverlay(GuiContainerManager.java:435)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at mods.railcraft.client.gui.GuiContainerRailcraft.func_73863_a(GuiContainerRailcraft.java:45)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1400)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at codechicken.nei.LayoutManager.renderSlotOverlay(LayoutManager.java:721)
	at codechicken.nei.guihook.GuiContainerManager.renderSlotOverlay(GuiContainerManager.java:435)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146977_a(GuiContainer.java:270)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:99)
	at mods.railcraft.client.gui.GuiContainerRailcraft.func_73863_a(GuiContainerRailcraft.java:45)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1400)

-- Screen render details --
Details:
	Screen name: mods.railcraft.client.gui.GuiSteamOven
	Mouse location: Scaled: (219, 79). Absolute: (438, 321)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

**Comment by Prometheus0000** [comment] 2021-02-09 18:51
We prefer you upload the log file, instead of copy pasting the text

**Comment by redmage17** [comment] 2021-02-09 18:53
_Screen name: mods.railcraft.client.gui.GuiSteamOven_

Are you opening your player inventory or a steam oven? Have you tried restarting the server?

**Comment by repo-alt** [comment] 2021-02-12 07:00
Log is good but steps to reproduce also wouldn't harm.

**Comment by mitchej123** [comment] 2021-02-12 19:06
This was caused by a prospecting book being bookmarked.  The 1.7.10 version of NBT <> json ser/des doesn't properly quote the result, and the books use characters that must be quoted.

Need to either asm hax the ser/des to quote, or blacklist prospecting books.

**Comment by mitchej123** [comment] 2021-02-12 19:07
Dupe of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7010

**Closed** 2021-02-12 19:07 UTC
Labels: Type: duplicate
