### ISSUE TITLE
Twilight Forest Naga courtyard generation on a lan world crash to menu 

### ISSUE THREAD

**Issue by Gamercave** [GTNewHorizons/GT-New-Horizons-Modpack#16656] opened 2024-07-01 14:50 UTC
### Your GTNH Discord Username

Gamercave

### Your Pack Version

2.6.1

### Your Server

SP, Lan world

### Java Version

Other versions in between

### Type of Server

Open To LAN

### Your Actions

Exploring the twilight forest with other player in overworld breaking flowers

### Crash Report

[crash-2024-07-01_15.43.02-server.txt](https://github.com/user-attachments/files/16054702/crash-2024-07-01_15.43.02-server.txt)
[crash-2024-07-01_15.35.32-server.txt](https://github.com/user-attachments/files/16054703/crash-2024-07-01_15.35.32-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Lyfts** [comment] 2024-07-01 14:54
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16353 and like 30 others.

You can update twilight forest to https://github.com/GTNewHorizons/twilightforest/releases/tag/2.6.12

**Closed by Lyfts** 2024-07-01 14:54 UTC
Labels: Type: Crash, Status: Triage
