### ISSUE TITLE
Unable to create server using Thermos

### ISSUE THREAD

**Issue by Apochy** [GTNewHorizons/GT-New-Horizons-Modpack#16105] opened 2024-04-30 08:02 UTC
### Your GTNH Discord Username

Apochy

### Your Pack Version

2.6.0

### Your Server

private sever

### Java Version

Java 8

### Type of Server

Thermos

### Your Actions

Building a GTNH server using dedicated Thermos.
<img width="734" alt="867c298fe58c01ffddd0b7b5208aa63d" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/160820615/2db12add-b9c1-410a-b7db-801519705e58">

Thermos:
<img width="740" alt="{B463EE63-FD5E-49e7-B2D2-9C757C415B64}" src="https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/160820615/43c24178-fa31-4d2e-aff0-feb0bc714663">

java version "1.8.0_411".

### Crash Report

[fml-server-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15160159/fml-server-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by RealSilverMoon** [comment] 2024-04-30 08:50
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16087

**Comment by Dream-Master** [comment] 2024-04-30 09:01
only Archaicfix  wont work but Core tweaks not affected

**Comment by chochem** [comment] 2024-12-11 17:43
looks resolved

**Closed by chochem** 2024-12-11 17:43 UTC
Labels: Crash, Mod: Thermos Strikes Again, Status: Triage
