### ISSUE TITLE
Light levels affect better questing party tab

### ISSUE THREAD

**Issue by zEcho0** [GTNewHorizons/GT-New-Horizons-Modpack#16735] opened 2024-07-12 19:06 UTC
### Your GTNH Discord Username

x_echo

### Your Pack Version

2.61

### Your Server

Private server

### Java Version

Java 21

### Type of Server

Don't know

### Your Expectation

Hitting the party button in better questing should show who invited you, your party members, etc.

### The Reality

Hitting the party button in better questing doesn't show anything in total darkness. 

### Your Proposal

Light levels shouldn't affect the party tab.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lyfts** [comment] 2024-07-15 18:42
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16496

**Closed by Lyfts** 2024-07-15 18:42 UTC
Labels: Type: bugMinor, Mod: Betterquesting, Status: Triage
