### ISSUE TITLE
Multiblock preview Crash

### ISSUE THREAD

**Issue by sean11235** [GTNewHorizons/GT-New-Horizons-Modpack#15409] opened 2024-01-24 20:22 UTC
### Your GTNH Discord Username

n0t_a_weeb

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Actions

Looking at the windmill multiblock preview the change tier arrows crashs the game when clicked 

### Crash Report

[crash-2024-01-24_11.56.22-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14043281/crash-2024-01-24_11.56.22-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Lyfts** [comment] 2024-01-24 20:26
Duplicate of: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15185

You can update to latest BlockRenderer version for now
https://github.com/GTNewHorizons/BlockRenderer6343/releases

**Closed** 2024-01-24 20:27 UTC
Labels: Type: Crash, Status: Triage

**Comment by sean11235** [comment] 2024-01-24 20:31
ah im blind i looked and didnt see that thx
