### ISSUE TITLE
Thaumcraft: Entity Deconstructor not craftable

### ISSUE THREAD

**Issue by KyriaThor** [GTNewHorizons/GT-New-Horizons-Modpack#14675] opened 2023-10-08 21:17 UTC
### Your GTNH Discord Username

kyriathor

### Your Pack Version

2.4.0

### Your Server

private server

### Java Version

Java 17

### Type of Server

Don't know

### Your Expectation

I tried to craft the Entity Deconstructor (Mod Thaumcraft: Thaumic Bases). It is crafted in an Infusion Recepie. Other Infusion Recepies worked fine.
The Recepie is 2 Weighted Pressure Plates, 6 Lenses (yellow, red, blue, green, black and white) on the outer Ring and a Deconstruction Table in the Middle.
The expectation is when you place everything and click the runic matrix, the infution should start and slowly use up the essences and items and change the deconstruction table to an entity deconstructor.
![Screenshot 2023-10-08 231104](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/144559948/0b81091d-7c3e-465c-86fb-2794e4cb29ae)

### The Reality

Even when everything is placed on the pedestals and the essences are near in warded jars, the infusion won't start, when the runic matrix is clicked with a wand. There is no reaction. The placement and type  of the lenses and everything else was checked multiple times. Everything is according to the recepie.
![Screenshot 2023-10-08 231305](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/144559948/71eb26b0-a146-44f2-ac42-9edc0474d8cb)
I tried it with multiple lenses as shown in NEI. In the Screenshot it is Yellow Garnet, Red Garnet, Sapphire, Emerald, Perditio and Glass. 

### Your Proposal

The Infusion should start, when all correct items are placed and the matrix is clicked with a wand.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by DarkAmbientNoise** [comment] 2023-10-11 20:41
Last time I had tried this recipe, I ended up having to use all Thaumcraft only lenses made from the shards themselves. But that was some time ago, I should have reported it as an issue.

**Comment by Ethryan** [comment] 2023-10-11 20:52
Yes, there is a issue where it displays all oredictionary entries for the item in the Infusion Altar. Even though they can’t be used to craft the item.

**Comment by KyriaThor** [comment] 2023-10-12 07:37
yeah, you guys are right. With only the lenses from the magical shards, it worked. So the NEI needs to be fixed.

**Comment by chochem** [comment] 2023-10-15 10:17
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12938

**Closed by chochem** 2023-10-15 10:17 UTC
Labels: Type: bugMinor, Status: Triage
