### ISSUE TITLE
Instant crash near precise assemblers

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#12574] opened 2023-02-13 00:35 UTC
### Your Pack Version

2.2.8

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Actions

I came within rendering distance of a precise assembler.
Although i'm using fastcraft i've had other people i play with also crash there multiple times in a row without any added mods.

### Crash Report

[crash-2023-02-13_01.31.48-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10717724/crash-2023-02-13_01.31.48-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2023-02-13 00:37
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12077

**Closed by chochem** 2023-02-13 00:37 UTC
Labels: Type: Crash, Status: Triage
