### ISSUE TITLE
Specialized GT help/info pages in NEI have massively incorrect item hitboxes

### ISSUE THREAD

**Issue by truenachtara** [GTNewHorizons/GT-New-Horizons-Modpack#17754] opened 2024-10-24 22:48 UTC
### Your Pack Version

2.7.0-beta3

### Your Server

Private server

### Java Version

Java 21

### Type of Server

None

### Your Expectation

Hovering over an item should show you its tooltip

### The Reality

Hovering over a spot well above the item is what shows you its tooltip instead. My mouse is in the red box for all these screenshots:
![image](https://github.com/user-attachments/assets/f38a9891-af71-4ccd-8cd8-50e9d953cb8b)
![image](https://github.com/user-attachments/assets/420b5a69-40f3-423c-a5b7-c85b55c15b63)

In addition, the aspect display is misaligned as well. The red box shows the aspects for the item in the lower half.
![image](https://github.com/user-attachments/assets/a5caca0e-7b0f-4123-8ba9-dfa0e1e8d920)
![image](https://github.com/user-attachments/assets/421b7f9f-e251-4521-a0bb-9ebe9b450a56)

### Your Proposal

Correct the item hitboxes

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FourIsTheNumber** [comment] 2024-10-24 22:55
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17715

Fixed with update to nei-custom-diagram

**Closed by FourIsTheNumber** 2024-10-24 22:55 UTC
Labels: Type: bugMinor, Status: Triage
