### ISSUE TITLE
Quest 'Simple RF power: Solid' says that GT wires can convert from EU to RF while this seems to no longer be true

### ISSUE THREAD

**Issue by blattgoldowo** [GTNewHorizons/GT-New-Horizons-Modpack#9220] opened 2021-12-21 18:03 UTC
### Your GTNH Discord Username

Эшли#1917

### Your Pack Version

2.1.2.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

I expect that the quest book doesn't lie to me

### The Reality

It lies, GT wires won't convert to RF with EIO machines. It does work if you pass the EU through a machine hull.

### Your Proposal

Make the quest book say that you need a machine hull for it to accept EU because it won't otherwise.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment] 2021-12-21 18:18
This is due to the enet changes. Let me see if we can clarify this. 

A gt wire will convert power if at least one gt power drain is somewhere on the same wire network (can be a hull that does nothing).

**Comment by Glease** [comment] 2021-12-21 22:06
Duplicate of #8171

**Closed by Glease** 2021-12-21 22:06 UTC
Labels: Type: bugMinor, Status: Triage
