### ISSUE TITLE
Crash in forestry workbench GUI

### ISSUE THREAD

**Issue by AtHisF1nest** [GTNewHorizons/GT-New-Horizons-Modpack#17422] opened 2024-09-22 16:05 UTC
### Your GTNH Discord Username

athisfinest

### Your Pack Version

2.7.0 beta 1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

When hovering over items while holding shift often crash the game. I don't know which items (I click shift to move the items fast). In forestry workbanches

### Crash Report

https://mclo.gs/ae7WAJd

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2024-09-22 16:07
duplicate of two others and already fixed

**Closed by chochem** 2024-09-22 16:07 UTC
Labels: Type: Crash, Status: Triage
