### ISSUE TITLE
Charm of Keeping 1 crashing server

### ISSUE THREAD

**Issue by ETx13** [GTNewHorizons/GT-New-Horizons-Modpack#5018] opened 2019-09-19 04:06 UTC
Whenever I die with a Charm of Keeping 1 the server crashed and the grave doesn't spawn and I lose all my stuff. Someone else had a Charm of Keeping 2 and it worked fine. So there's a big problem with 1.

**Comment by draknyte1** [comment] 2019-09-19 10:45
Got a log file or something?
We literally can’t do anything with this report otherwise..

**Comment by Dream-Master** [comment] 2019-10-15 12:53
@ETx13 we need more infos and log files.
If i get no infos i close this issue.

**Comment by richardhendricks** [comment] 2020-01-24 22:45
@ETx13 Update?

**Comment by dvdmandt** [comment] 2020-11-28 04:21
So this was almost certainly the same issue as #5619 which was fixed by this commit to the TF repo: https://github.com/GTNewHorizons/twilightforest/commit/34d2a106d7108c1f89bb157800dfe835d18524ba

**Comment by Dream-Master** [comment] 2020-11-28 07:42
@jss2a98aj can you check this too?

**Comment by jss2a98aj** [comment] 2020-11-28 07:57
This is a duplicate of issue #5619 which I fixed.

**Closed** 2020-11-28 08:29 UTC
Labels: Mod: Twilight Forest, Status: FixedInDev, Type: Crash, Type: Need more Info, Type: duplicate
