### ISSUE TITLE
Ticking entity Crash

### ISSUE THREAD

**Issue by joshaup1999** [GTNewHorizons/GT-New-Horizons-Modpack#7942] opened 2021-05-19 07:13 UTC
#### Which modpack version are you using?
2.1.0.7
#
#### If in multiplayer; On which server does this happen? 
Private
#
#### What did you try to do, and what did you expect to happen?
Unsure what caused it, crash log attached. I did update gregtech to the latest successful build as advised last night. 

https://pastebin.com/GgtfNJcz

#
#### What is your GTNH Discord username?

Lord_Peverell

**Comment by Quadrocake** [comment] 2021-05-19 08:27
I'm getting the same crash. Before getting it I've played without issues for a few hours, and now it crashes the second I join my server.

**Comment by boubou19** [comment] 2021-05-19 08:34
try changing your GT version with this one: http://jenkins.usrv.eu:8080/job/Gregtech-5-Unofficial/1238/artifact/build/libs/gregtech-5.09.34.17.jar

**Comment by Glease** [comment] 2021-05-19 13:15
Duplicate of #7936.

**Closed by Glease** 2021-05-19 13:15 UTC
Labels: Mod: GT, Type: duplicate
