### ISSUE TITLE
Game Crash Hydroenergy 2.1.1.1a

### ISSUE THREAD

**Issue by Zodiack256b** [GTNewHorizons/GT-New-Horizons-Modpack#8370] opened 2021-08-07 23:46 UTC
#### Which modpack version are you using?
2.1.1.1a
#
#### If in multiplayer; On which server does this happen? 
private
#
#### What did you try to do, and what did you expect to happen?
Entering world game crashed with attached crash.
Also received crash at startup with optifine in the mods folder and hydroenergy at the same time.
#
#### What happened instead? (Attach screenshots if needed)
Entering world game crashed with attached crash.
#
#### What do you suggest instead/what changes do you propose?

#
#### What is your GTNH Discord username?
ZodiacK256B

**Comment by Zodiack256b** [comment] 2021-08-07 23:46
[
[Crash hydroenergy alone entering world.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6950027/Crash.hydroenergy.alone.entering.world.txt)
[Crash hydroenergy and optifine.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6950028/Crash.hydroenergy.and.optifine.txt)
](url)

**Comment by Glease** [comment] 2021-08-08 05:07
Duplicate of #8353

**Closed by Glease** 2021-08-08 05:07 UTC
