### ISSUE TITLE
Greatwood Plank making oak slabs

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#7743] opened 2021-04-03 04:08 UTC
#### Which modpack version are you using?
2.1.0.5
#
#### If in multiplayer; On which server does this happen? 
zeta
#
#### What did you try to do, and what did you expect to happen?
I was trying to make some arcane bellows but i can't seem to make greatwood slabs, as the planks will turn into oak slabs
#
#### What happened instead? (Attach screenshots if needed)
![2021-04-03_01 04 52](https://user-images.githubusercontent.com/57275066/113467363-ebbba000-9418-11eb-837d-70c065711eda.png)

**Comment by Prometheus0000** [comment] 2021-04-03 04:25
Duplicate of #7496

**Closed by Prometheus0000** 2021-04-03 04:25 UTC
