### ISSUE TITLE
logisticspipes-1.7.10-0.9.4.5.4-GTNH causes "severe threat"

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#10196] opened 2022-04-23 16:02 UTC
### Your GTNH Discord Username

Szajkop

### Your Pack Version

2123qf

### Your Server

priv srv

### Your Expectation

Trying to launch 2123qf version of the pack but got error message from windows. The client loads but the mod is not loaded, I cannot connect to a server.

### The Reality

Windows defender marked the following file as Trojan malware:
logisticspipes-1.7.10-0.9.4.5.4-GTNH.jar
![image](https://user-images.githubusercontent.com/7230430/164913632-516bd46e-18ca-4e04-9e74-90ba63cc53a1.png)

https://go.microsoft.com/fwlink/?linkid=142185&name=Trojan:AndroidOS/Multiverze&threatid=2147785333

### Your Proposal

Fix the issue

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by glowredman** [comment] 2022-04-23 16:05
- Duplicate of #10085
- Fixed by https://github.com/GTNewHorizons/LogisticsPipes/pull/7

**Closed by glowredman** 2022-04-23 16:05 UTC
Labels: Type: bugMinor, Status: Triage
