### ISSUE TITLE
LuV Processing Array with IV Circuit Assemblers Running LuV Recipes

### ISSUE THREAD

**Issue by Simmons572** [GTNewHorizons/GT-New-Horizons-Modpack#15844] opened 2024-03-27 03:33 UTC
### Your GTNH Discord Username

Simmons572

### Your Pack Version

2.5.1

### Your Server

Private Server, Bombulum MC

### Java Version

Java 21

### Type of Server

Open To LAN

### Your Expectation

We ran a recipe for the Crystal Processer Mainframe in an LuV powered Processing Array with 4 IV Circuit Assemblers installed.  Based on our previous experience, this should not work.

### The Reality

The recipe ran without issues.

### Your Proposal

Block this recipe and similar recipes from running.  Our guess is that LuV recipes are running as we are supplying LuV power.
![image_2024-03-26_233315789](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/15789121/c998d858-9cbf-4e00-a5f4-97d0bf72d62b)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by HoleFish** [comment] 2024-03-27 06:21
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15383

**Closed by HoleFish** 2024-03-27 06:21 UTC
Labels: Type: bugMinor, Status: Triage
