### ISSUE TITLE
Serious Bug with Precision Assembler in Good Generator

### ISSUE THREAD

**Issue by KamenriderZO** [GTNewHorizons/GT-New-Horizons-Modpack#10566] opened 2022-06-28 02:35 UTC
### Your GTNH Discord Username

GregTechDriver

### Your Pack Version

2.1.2.4-14dev

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Make normal assembling machine recipes in precision assembler
(T2 Duty plate,Compressed Ice Plate...)

### The Reality

This machine just swallow some part of the input materials.
For 2*meteoric Iron plate + 1 T1 Duty plate.
it consumes 1 T1 Duty plate. only and ouput nothing.
(Its not about power consumption! becasue not enough power it should eat every material)
(And there is no machine control cover on it,so if not enough power it should turn off)

This is serious because if this machine has problem
There is no way to make Naquadah line machines later!

### Your Proposal

Fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by xSkewer** [comment] 2022-06-28 02:37
Already fixed, you need to update Bartworks to this version if you want to play with the fix:
http://jenkins.usrv.eu:8080/job/Bartworks/498/artifact/build/libs/bartworks-1.7.10-0.5.53-pre-1-g81a6017.jar

**Comment by miozune** [comment] 2022-06-28 04:11
Duplicate of #10552

**Closed by miozune** 2022-06-28 04:11 UTC
Labels: Type: bugMinor, Status: Triage
