### ISSUE TITLE
TC nodes do not change biome in personal dimension

### ISSUE THREAD

**Issue by Smith0rC** [GTNewHorizons/GT-New-Horizons-Modpack#13139] opened 2023-04-05 07:49 UTC
### Your GTNH Discord Username

Smith#2892

### Your Pack Version

2.3.0

### Your Server

Delta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Trying to change the biome of a small area in personal dimension using TC nodes. I placed both sinister and pure (containing victus) and expected the biome to change in the usual 7 block radius.

### The Reality

Even after hours the biome didn't change, not even for a single block below the nodes. Couldn't test other methods to change biomes yet. Not sure if this is a bug or a feature...

### Your Proposal

Allow biome changing at least for such small area methods. These biome adjustments are crucial for doing bees/crops in just one area/personal dim, instead of splitting it to multiple chunkloaded areas.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2023-04-05 07:52
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12759

**Closed by chochem** 2023-04-05 07:52 UTC
Labels: Type: bugMinor, Status: Triage
