### ISSUE TITLE
New Machine sounds aren't Stereo

### ISSUE THREAD

**Issue by 48a3efa65c881ef567345b17f3910e06** [GTNewHorizons/GT-New-Horizons-Modpack#17453] opened 2024-09-25 01:14 UTC
### Your GTNH Discord Username

33yy

### Your Pack Version

Nightly 666

### Your Server

address: 100.ong (my server)

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

When i go around new multiblocks, their sounds in each ear would differ based on which side faces the MB, like regular sounds

### The Reality

Sounds are directly based on direct proximity in both ears and feel kind of off

### Your Proposal

The new sounds should work properly

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by leumasme** [comment] 2024-09-25 06:34
It seems like the audio files themselves are encoded as stereo (do they actually have different sounds on the two channels?). I believe this makes the Minecraft sound engine use the stereo channels from the file instead of computing stereo channels based on player rotation.

**Comment by 48a3efa65c881ef567345b17f3910e06** [comment] 2024-09-27 01:08
Yeah it should definitely compute stereo based off rotation like all other sounds are? even the previous multiblock sounds like the grinder do that

**Comment by leumasme** [comment] 2024-09-30 12:17
Caused by https://github.com/GTNewHorizons/GT5-Unofficial/pull/3139

**Comment by wantayanamirei** [comment] 2024-10-01 20:17
Fixed in https://github.com/GTNewHorizons/GT5-Unofficial/pull/3308 (you need to wait until someone will merge mono sounds into master branch)

**Comment by BlueHero233** [comment] 2024-10-08 09:27
Mono sounds were merged, does this close your issue?

**Comment by Dream-Master** [comment] 2024-10-08 09:31
sure

**Closed by Dream-Master** 2024-10-08 09:31 UTC
Labels: Type: bugMinor, Status: Triage
