### ISSUE TITLE
Dimension provider crash when leaving world to menu and entering one without restarting the client

### ISSUE THREAD

**Issue by konvaa** [GTNewHorizons/GT-New-Horizons-Modpack#10377] opened 2022-05-23 11:57 UTC
### Your GTNH Discord Username

konva#9953

### Your Pack Version

2.1.2.3gf

### Your Server

SP

### Type of Server

Single Player

### Your Actions

When looking for a decent seed to play on, each attempt on current version causes crash. I have to start again, then the first world I create is created without issues, if I am unhappy with seed, new one requires restarting the game, else game crashes during loading into game.

### Crash Report

https://paste.ee/p/5nD2W

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by konvaa** [comment] 2022-05-23 12:00
Also I found that if I use technic, where version is 2.1.2.0, the issue wont happen. Currently im using Multi MC

**Comment by chochem** [comment] 2022-05-23 14:03
the problem seems to be:

> java.lang.IllegalArgumentException: Could not get provider type for dimension 32, does not exist
	at net.minecraftforge.common.DimensionManager.getProviderType(DimensionManager.java:148) ~[DimensionManager.class:?]
	at net.minecraftforge.common.DimensionManager.shouldLoadSpawn(DimensionManager.java:268) ~[DimensionManager.class:?]

a short search on discord says that dim 32 is barnarda C and that people including [dreammasterXXL himself](https://discord.com/channels/181078474394566657/603348502637969419/937327237898858496) had this crash before but from what I can see nobody made a ticket or fixed it.

**Comment by Erizid** [comment] 2022-05-23 23:14
I just had this crash.  Started a world, played for 10 minutes, didnt like it.  Saved and Quit, then deleted that world.  Started a new world and had that crash about 20 second in.

**Comment by xSkewer** [comment] 2022-06-09 03:05
Had this crash happen twice today.
Once while teleporting to Ceres without a rocket, and again when trying to launch a T4 rocket for the first time. 
First crash was for dimension id 42, which is Ceres, but the second was for id 30, which I think is asteroids.
After the first crash, I deleted my Ceres dimension folder and loaded the world just fine (don't know if I needed to do this). 
After the second crash, I reopened without any issues and was still in the rocket as it was launching and it launched fine. 

On .4-dev 5 with version 5.09.40.48-dev for GT5.

**Comment by Oldmemory1** [comment] 2022-06-09 03:38
I found it as well.A few days ago,I created a creative save to test a thing.But when the save was loaded,it freezed,the the game crashed.Here is the crash report: https://paste.ubuntu.com/p/fjdbnXQ7nQ/   I am sorry that my mother language is not English.

**Comment by Oldmemory1** [comment] 2022-06-09 03:40
I used the latest version:2.1.2.3qf ,but It still happened.

**Comment by lyuben-todorov** [comment] 2022-08-17 20:28
```
[23:13:04] [Server thread/ERROR] [FML]: The following problems were captured during this phase
[23:13:04] [Server thread/ERROR] [FML]: Caught exception from GalacticraftCore
java.lang.IllegalArgumentException: Failed to unregister dimension for id 30; No provider registered
    at net.minecraftforge.common.DimensionManager.unregisterDimension(DimensionManager.java:134)
```
I suggest renaming this. Seems to happen upon exiting a SP world and trying to enter it again.

**Comment by hallucinogender** [comment] 2022-08-30 22:06
Additional relevant crash reports:

[crash-2022-08-30_22.46.08-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9456932/crash-2022-08-30_22.46.08-server.txt)
[crash-2022-08-30_22.46.38-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9456933/crash-2022-08-30_22.46.38-server.txt)
[crash-2022-08-30_22.53.42-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9456934/crash-2022-08-30_22.53.42-server.txt)

**Comment by TheBlizWiz** [comment] 2022-10-07 00:40
Looks like the issue is back in 2.2.0.0. Just had a crash on a creative testing world. Game crashed the moment I entered the rocket and started the launch sequence.
[crash-2022-10-06_17.19.22-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9729533/crash-2022-10-06_17.19.22-server.txt)
[dimension.csv](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9729536/dimension.csv)

**Comment by thibaut-fagart** [comment] 2022-12-15 19:54
just had this happened too, (java.lang.IllegalArgumentException: Could not get provider type for dimension 42, does not exist) as I was launching T3 rocket for the first time.
I'm running 2.2.3
[crash-2022-12-15_20.48.09-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10240201/crash-2022-12-15_20.48.09-server.txt)

**Comment by chochem** [comment] 2022-12-15 20:32
you are on 2.2.3. the fix (attempt) is not in there. 2.2.7 should be better.

**Comment by BritishCynic** [comment] 2023-03-27 13:05
Closing as this is an old crash report; if this crash is still occurring with 2.3.0+, please comment to reopen.

**Closed by BritishCynic** 2023-03-27 13:05 UTC
Labels: Type: Crash

**Comment by vertexofvortex** [comment] 2023-07-28 18:45
Just encountered the same issue. After connecting to (our private) server or joining a singleplayer world, then leaving and trying to connect to the singleplayer, the world crashes and game quits to the main menu. This issue appeared when I first started experiments with a teleporter via AE2 spatial cells, if memory serves me. [Crash report here](https://pastebin.com/MRjunx93).

I'm currently using Prism Launcher and GTNH v. 2.3.0 patched for Java 17-19.

**Comment by barsikus007** [comment] 2025-01-01 21:57
Same as above
After I logged out from Delta, I can't join singleplayer world due to this error
