### ISSUE TITLE
Destroy a Galacticraft block with GT Wrench crashes the server

### ISSUE THREAD

**Issue by reobf** [GTNewHorizons/GT-New-Horizons-Modpack#16107] opened 2024-04-30 09:55 UTC
### Your Pack Version

2.5.1

### Your Server

private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Actions

Destroy a Galacticraft block with GT Wrench crashes the server.

Block.getPickBlock will call Block.getItem(a.k.a. func_149694_d)
which is  annotated with @SideOnly(Side.CLIENT)
this works fine on SP but crashes the MP server

### Crash Report

java.lang.NoSuchMethodError: net.minecraft.block.Block.func_149694_d(Lnet/minecraft/world/World;III)Lnet/minecraft/item/Item;
    at net.minecraft.block.Block.getPickBlock(Block.java:1801)
    at net.minecraft.block.Block.getPickBlock(Block.java:1796)
    at micdoodle8.mods.galacticraft.core.energy.tile.TileBaseElectricBlock.getWrenchDrop(TileBaseElectricBlock.java:186)
    at gregtech.common.tools.GT_Tool_Wrench.onBreakBlock(GT_Tool_Wrench.java:186)
    at gregtech.common.GT_Proxy.onBlockBreakingEvent(GT_Proxy.java:1613)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_17_GT_Proxy_onBlockBreakingEvent_BreakEvent.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:467)
    at net.minecraft.server.management.ItemInWorldManager.func_73084_b(ItemInWorldManager.java:259)
    at net.minecraft.server.management.ItemInWorldManager.func_73082_a(ItemInWorldManager.java:217)
    at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:498)
    at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
    at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2024-04-30 09:56
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15195

**Closed by chochem** 2024-04-30 09:56 UTC
Labels: Type: Crash, Status: Triage
