### ISSUE TITLE
Sudden crash when opening a specific quest in Steam and when I picked up a strawberry

### ISSUE THREAD

**Issue by icm98** [GTNewHorizons/GT-New-Horizons-Modpack#17811] opened 2024-10-30 18:59 UTC
### Your GTNH Discord Username

icm98

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Actions

Tried opening a quest multiple times, game keeps crashing when opening it, off the top of my head it's one in Steam Age. Now I avoided doing this the last 30 minutes, everything went well, untill I picked up a strawberry. No idea why this randomly happened in my offline world. Have never messed around with coding, and if the solutions requires coding I guess I'mm screwed :) I have 0 additional information, yesterday everything was allright. 

### Crash Report

[crash-2024-10-30_19.49.37-client.txt](https://github.com/user-attachments/files/17577678/crash-2024-10-30_19.49.37-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2024-11-01 01:25
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14471
probably some corrupted game files, try redownloading

**Closed by chochem** 2024-11-01 01:25 UTC
Labels: Type: Crash, Status: Triage

**Comment by icm98** [comment] 2024-11-04 17:52
Yeah still keeps happening. I can play for like two hours after restoring a previous backup (last backup made, so 30 minutes earlier), then it crashes again. If I redownload, will all progress be lost?

**Comment by icm98** [comment] 2024-11-04 18:03
This is the newest crash report
[crash-2024-11-04_19.01.26-server.txt](https://github.com/user-attachments/files/17622162/crash-2024-11-04_19.01.26-server.txt)

**Comment by chochem** [comment] 2024-11-04 18:06
thats a completely different crash. see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16353

**Comment by icm98** [comment] 2024-11-04 18:41
Yes that's the point. When the game crashes, I go back to the last back-up, restore it, and play for a bit. How long I can play is variable, but at some point the game crashes. I've restored to back-ups for like 6 times now, and it crashed 6 times, but since I could continue for a bit when restoring to a back-up, each crash is new as it happens at different moments. But this was the most recent report.

**Comment by icm98** [comment] 2024-11-04 18:45
But since this keeps happening, playing a corrupted file is a possibility? And if that's the case, does redownloading remove all progress? Like, right now I can play the game, but since it keeps crashing and I have to restore backup to continue a bit further, right now it's like a "two steps forward, one step back" situation, and it's really annoying me :) I don't want to keep doing this, plus I have the feeling that if the problem is in corruption of the files, it won't solve itself, and the problem will keep presenting itself.

**Comment by FourIsTheNumber** [comment] 2024-11-04 18:51
> But since this keeps happening, playing a corrupted file is a possibility? And if that's the case, does redownloading remove all progress? Like, right now I can play the game, but since it keeps crashing and I have to restore backup to continue a bit further, right now it's like a "two steps forward, one step back" situation, and it's really annoying me :) I don't want to keep doing this, plus I have the feeling that if the problem is in corruption of the files, it won't solve itself, and the problem will keep presenting itself.

Just update the twilight forest mod. Nothing is corrupted.

**Comment by chochem** [comment] 2024-11-04 18:53
> Yes that's the point. When the game crashes, I go back to the last back-up, restore it, and play for a bit. How long I can play is variable, but at some point the game crashes. I've restored to back-ups for like 6 times now, and it crashed 6 times, but since I could continue for a bit when restoring to a back-up, each crash is new as it happens at different moments. But this was the most recent report.

you were told to redownload and you didnt it seems, so you keep crashing. all sounds pretty consistent. except that one crash was independent of all that lol.

**Comment by icm98** [comment] 2024-11-05 17:07
Okay, thank you guys. I'll look into it, no idea how to, but I'll search for a bit how to update. Thanks!

**Comment by icm98** [comment] 2024-11-05 18:01
Thanks guys, so far it works!
