### ISSUE TITLE
not able to see vine stats

### ISSUE THREAD

**Issue by Eason134HK** [GTNewHorizons/GT-New-Horizons-Modpack#11530] opened 2022-10-03 10:38 UTC
### Your GTNH Discord Username

Eason1134HK#5098

### Your Pack Version

2.1.2.0

### Your Server

delta

### Type of Server

Don't know

### Your Expectation

i try to see vine stats by R click some ores 
![image](https://user-images.githubusercontent.com/59776356/193557551-99a656fa-553d-4086-9acf-f15baf02ef25.png)
it supposed to show me the vine stats

### The Reality

but I am not able to see vine stats
and the game show my this 
![image](https://user-images.githubusercontent.com/59776356/193557512-78bb3918-4dc5-47e2-b053-2b18c0ab0b7c.png)

I clipped a part of the log

[20:36:08] [Client thread/INFO]: [CHAT] There was error during loading recipe. Please check log for details.
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.util.concurrent.ExecutionException: java.lang.NullPointerException
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.nei.recipe.RecipeHandlerQuery.getHandlersWithRecipes(RecipeHandlerQuery.java:63)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.nei.recipe.RecipeHandlerQuery.getRecipeHandlersParallel(RecipeHandlerQuery.java:45)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.nei.recipe.RecipeHandlerQuery.runWithProfiling(RecipeHandlerQuery.java:32)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:38)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:22)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.github.dcysteine.neicustomdiagram.api.diagram.component.ItemComponent.interact(ItemComponent.java:120)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.github.dcysteine.neicustomdiagram.api.diagram.component.DisplayComponent.interact(DisplayComponent.java:89)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.github.dcysteine.neicustomdiagram.api.diagram.interactable.InteractiveComponentGroup.interact(InteractiveComponentGroup.java:115)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.github.dcysteine.neicustomdiagram.api.diagram.DiagramGroup.interact(DiagramGroup.java:228)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at com.github.dcysteine.neicustomdiagram.api.diagram.DiagramGroup.mouseClicked(DiagramGroup.java:267)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.nei.recipe.GuiRecipe.func_73864_a(GuiRecipe.java:339)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3104)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NullPointerException
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.GeneratedConstructorAccessor289.newInstance(Unknown Source)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 24 more
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NullPointerException
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.GeneratedConstructorAccessor289.newInstance(Unknown Source)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.nei.recipe.RecipeHandlerQuery.lambda$getHandlersWithRecipes$2(RecipeHandlerQuery.java:62)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.nei.recipe.RecipeHandlerQuery$$Lambda$2180/1409544736.call(Unknown Source)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NullPointerException
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at WayofTime.alchemicalWizardry.client.nei.NEIMeteorRecipeHandler.matchItem(NEIMeteorRecipeHandler.java:137)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at WayofTime.alchemicalWizardry.client.nei.NEIMeteorRecipeHandler.lambda$loadCraftingRecipes$0(NEIMeteorRecipeHandler.java:116)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at WayofTime.alchemicalWizardry.client.nei.NEIMeteorRecipeHandler$$Lambda$2205/108452845.test(Unknown Source)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at WayofTime.alchemicalWizardry.client.nei.NEIMeteorRecipeHandler.loadCraftingRecipes(NEIMeteorRecipeHandler.java:116)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.nei.recipe.TemplateRecipeHandler.loadCraftingRecipes(TemplateRecipeHandler.java:405)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at WayofTime.alchemicalWizardry.client.nei.NEIMeteorRecipeHandler.loadCraftingRecipes(NEIMeteorRecipeHandler.java:109)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.nei.recipe.TemplateRecipeHandler.getRecipeHandler(TemplateRecipeHandler.java:544)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.nei.recipe.GuiCraftingRecipe.lambda$openRecipeGui$0(GuiCraftingRecipe.java:36)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at codechicken.nei.recipe.GuiCraftingRecipe$$Lambda$2173/981193797.apply(Unknown Source)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:747)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.stream.ReduceOps$ReduceTask.doLeaf(ReduceOps.java:721)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.stream.AbstractTask.compute(AbstractTask.java:316)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1040)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
[20:36:08] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: 	... 2 more

### Your Proposal

FIx it 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2022-10-03 10:41
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11461

**Closed by chochem** 2022-10-03 10:41 UTC
Labels: Type: bugMinor, Status: Triage
