### ISSUE TITLE
Crash when launch world

### ISSUE THREAD

**Issue by Qwerkus11** [GTNewHorizons/GT-New-Horizons-Modpack#12296] opened 2023-01-16 15:04 UTC
### Your GTNH Discord Username

Qwerkus1027#7588

### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Crash when launching world.
I played yesterday night, everything was fine.

### Crash Report

[crash-2023-01-16_16.03.28-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10426927/crash-2023-01-16_16.03.28-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2023-01-16 16:55
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11433
post about it there

**Closed by chochem** 2023-01-16 16:55 UTC
Labels: Type: Crash, Status: Triage
