### ISSUE TITLE
When I point at food, the game crashes

### ISSUE THREAD

**Issue by kamenskyi** [GTNewHorizons/GT-New-Horizons-Modpack#15468] opened 2024-02-03 23:05 UTC
### Your GTNH Discord Username

proventus569

### Your Pack Version

2.5.1

### Your Server

sp

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Навожу на еду любую, просиходиит сбой. При перезапуске клиента сбоя не происходит. При удалении SpiceOfLife сбоя не происходит вообще.

### Crash Report

[crash-2024-02-02_22.48.44-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14154489/crash-2024-02-02_22.48.44-client.txt)
[latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/14154493/latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2024-02-04 00:55
tickets in english please

**Comment by chochem** [comment] 2024-02-04 11:17
also based on the log its just a duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14709 and https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14471 and multiple others.

**Closed by chochem** 2024-02-04 11:17 UTC
Labels: Type: Duplicate, Type: Crash, Status: Triage
