### ISSUE TITLE
[Temagamite Ore] NEI Error rendering

### ISSUE THREAD

**Issue by MotDT** [GTNewHorizons/GT-New-Horizons-Modpack#6075] opened 2020-05-07 21:44 UTC
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
eta.gtnewhorizons.com
#
After trying to see Temagamite Ore recipe(Ore NEI) > Error rendering > Crash client
#
[crash-log](https://pastebin.com/viaij1av)

**Comment by Prometheus0000** [comment] 2020-05-07 21:52
Update your game

**Comment by chochem** [comment] 2020-05-07 21:52
Duplicate of #5392 
its fixed in newer versions.

**Comment by MotDT** [comment] 2020-05-07 21:53
> 
> 
> Duplicate of #5392
> its fixed in newer versions.

see, thanks.

**Closed** 2020-05-07 21:53 UTC
