### ISSUE TITLE
ME IO Port doesn't always work after a restart 

### ISSUE THREAD

**Issue by combusterf** [GTNewHorizons/GT-New-Horizons-Modpack#15260] opened 2024-01-01 23:18 UTC
### Your GTNH Discord Username

Combuster

### Your Pack Version

2.5.1

### Your Server

Delta

### Java Version

Java 17

### Type of Server

Thermos

### Your Expectation

An IO Port was moving bulk items stored among 64K drives into super chests when the server restarted, and I expected the process to resume after reconnecting.

### The Reality

The IO port was inactive and wasn't moving items anymore, despite there being items to move. Opening the inventory didn't change anything, but replacing one of the drives restarted the process.

### Your Proposal

ME IO Ports should be reliable across restarts. It probably needs an initial trigger after the tile entity is loaded/powered.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by StaffiX** [comment] 2024-01-01 23:24
Duplicate of #13482 i think

**Comment by AbdielKavash** [comment] 2024-01-02 04:12
Can confirm, duplicate, and fixed in https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/448.

**Closed** 2024-01-04 08:07 UTC
Labels: Type: bugMinor, Status: Triage
