### ISSUE TITLE
Adding vehicle mods in a New Horizons modpack

### ISSUE THREAD

**Issue by NikitaGamer64** [GTNewHorizons/GT-New-Horizons-Modpack#8798] opened 2021-11-08 23:24 UTC
### Your GTNH Discord Username

Никита#8621

### Your Pack Version

2.0.9, but I’m writing for the newest pack version

### Mod Name

Immersive Vehicles & Immersive Railroading

### The Mod to Add

Immersive Vehicles: Vehicles assembled with previously crafted parts. They are damageable and repairable. You can drive, fly and, maybe, even sail across the world. This mod has numerous addons which feature more vehicles of all kinds and ages (maybe even magic vehicles), and even traffic signs (of course, only the best addons are considered).
Immersive Railroads: This mod features broad gauge railway tracks and bigger cars and engines (maybe even trams). They may not be automatable like a Railcraft narrow gauge minecart system, but they add a little realism.
P.S. Maybe there is a way to add a trolley-bus? It is driven as a automotive bus but has trolley poles that slide through the wires like railcar wheelsets.

### Your Reason

With these two mods, you can transport yourself without any horses, jetpacks and teleports, but by classic cars, trains, planes and boats. Of course, they should be integrated with New Horizons modpack before launching, but then everyone will be able to enjoy riding their own car through Minecraft world!
I can’t imagine how many cities could be build with such an infrastructure! It may not be needed, but creativity is always an advantage!

### Preliminary Investigation

Unfortunately, I haven’t played these mods yet, but I saw some reviews at some YouTube channels. If necessary, vehicle interior planning (doors, entering/exiting ways, seats, salons, tambours, decks, hulls, wall boxes) and drive/impact mechanics should be improved. Maybe more vehicles via extra addon (and bigger ships) will be needed. Recipes integrated with GregTech, of course.
Wait, it is the later Minecraft version! Maybe it’s possible to port it into 1.7.10?

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by bombcar** [comment] 2021-11-08 23:28
Unfortunately Immersive Vehicles at least is ARR.

We do have a moon buggy, maybe it works on Earth

**Comment by yukieiji** [comment] 2021-11-08 23:38
Duplicate of #6789

**Comment by NikitaGamer64** [comment] 2021-11-08 23:44
> Unfortunately Immersive Vehicles at least is ARR.
> 
> We do have a moon buggy, maybe it works on Earth

What is ARR? And moon buggy is just not the right thing… not something suitable.

**Comment by NikitaGamer64** [comment] 2021-11-08 23:45
> Duplicate of #6789

I haven’t seen that in a search by “Immersive Vehicles”.

**Comment by NikitaGamer64** [comment] 2021-11-08 23:48
> Duplicate of #6789

This is a way of easier applying found by me. These mods are considered as a solution method. And some people may be really tired of jetpacks, especially if the distance is too big.

**Comment by Glease** [comment] 2021-11-09 10:24
1. In final checklist item 1, you claim "This mod is released under an open source license." However, it declare itself as All Right Reserved on curseforge, which is not an open source license. Don't worry, it's an honest mistake. Most people won't ever be involved in this copyright mess.
2. It's a mod for later minecraft version and it contains a whole bunch of rendering code, thus making it near impossible to backport. (Rendering was redone multiple times after minecraft 1.7.10, so it's not a backport, but a reimplementation) Of course, with enough manpower we can do this, except we don't.

Closing for now for above two reasons.

**Closed by Glease** 2021-11-09 10:24 UTC
Labels: Type: Mod Addition, Status: Triage
