### ISSUE TITLE
ME Interface recipe different for panel vs block

### ISSUE THREAD

**Issue by aelam01** [GTNewHorizons/GT-New-Horizons-Modpack#16747] opened 2024-07-14 03:26 UTC
### Your GTNH Discord Username

aelam

### Your Pack Version

2.6.1

### Your Server

private server

### Java Version

Java 21

### Type of Server

Don't know

### Your Expectation

Recipe for panel and block versions of the ME interface should be the same in the assembler, seeing as you can directly convert them in the crafting table/molecular assembler.

### The Reality

The panel version of the recipe in the assembler requires an extra annihilation core, while you can instead just craft the cheaper block version and then freely convert it into a panel.
![Screenshot 2024-07-13 232327](https://github.com/user-attachments/assets/ec274aca-ba8b-4f90-b0aa-0671e355d7dd)
![Screenshot 2024-07-13 232344](https://github.com/user-attachments/assets/98863de6-9b17-42bf-8fb2-ee95b00e27f7)

### Your Proposal

The panel recipe should be edited to be identical to the block recipe

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by NotAPenguin0** [comment] 2024-07-15 18:37
Duplicate of #16479

**Closed by NotAPenguin0** 2024-07-15 18:37 UTC
Labels: Type: bugMinor, Status: Triage
