### ISSUE TITLE
[EnderIO] Fluid Tanks eat air cells

### ISSUE THREAD

**Issue by xiPakuL** [GTNewHorizons/GT-New-Horizons-Modpack#14295] opened 2023-08-22 02:05 UTC
### Your GTNH Discord Username

lukapix

### Your Pack Version

2.3.6

### Your Server

Private Vanilla Forge Server

### Java Version

Java 20

### Type of Server

Vanilla Forge

### Your Expectation

Putting an Ic2 Air cell into an EnderIO Fluid tank, would output an Empty Cell just like in a GT Tank

### The Reality

It gets the fluid and consumes the cell in the process.

### Your Proposal

Make it output an empty cell to it's output slot

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by desagas** [comment] 2023-08-22 22:43
Duplicate ... many times this has been reported.

**Comment by xiPakuL** [comment] 2023-08-24 11:30
I couldn't find an open issue on this

**Comment by Ethryan** [comment] 2023-08-24 14:25
duplicate of #1003

**Closed by Ethryan** 2023-08-24 14:25 UTC
Labels: Type: bugMinor, Status: Triage
