### ISSUE TITLE
Agon block conflict with Resistor in Assembler recipe

### ISSUE THREAD

**Issue by winterturtle1** [GTNewHorizons/GT-New-Horizons-Modpack#9501] opened 2022-01-18 14:25 UTC
### Your GTNH Discord Username

WinterTurtle#7656

### Your Pack Version

2.1.2.0-RC1

### Your Server

SP

### Your Expectation

Crafting resistors in the assembler with 576 mb TC glue

### The Reality

It conflicts with a recipe for ztones agon which uses 250 mb glue and they both use the 5 circuit

https://cdn.discordapp.com/attachments/181078474394566657/933000831681318952/unknown.png

### Your Proposal

remove the extraneous agon block recipe, along with the other recipes that use the 4,5,6 and 7 circuits.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by riking** [comment] 2022-01-18 19:10
This does deserve a fix.

**Comment by PolkageistHS** [comment] 2022-01-20 17:01
Duplicate of #9417 ?

**Comment by Nenluen** [comment] 2022-01-21 05:54
Agon (8) is also blocking circuit boards once the glue exceeds 250mb on 2.1.2.1:

![image](https://user-images.githubusercontent.com/10765948/150473449-bcc3ba66-e498-487a-b8a9-60aa7a0587f3.png)

![image](https://user-images.githubusercontent.com/10765948/150473672-4a0fd0aa-a350-4e3d-88a2-9f68d257d363.png)

**Comment by miozune** [comment] 2022-01-21 16:53
duplicate of #9417

**Closed by miozune** 2022-01-21 16:53 UTC
Labels: Type: bugMinor, Status: Triage
