### ISSUE TITLE
Opis Leading to Crashing

### ISSUE THREAD

**Issue by PFleur** [GTNewHorizons/GT-New-Horizons-Modpack#18272] opened 2024-12-08 18:57 UTC
### Your GTNH Discord Username

patchoulifleur

### Your Pack Version

2.6.1_Java_17-21, 2.7.0_Java_17-21

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

Continuation of [this](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16632) due to the same issue occurring in multiple versions. Upon launching the game it begins to load and eventually freezes. On both version it loads properly after Opis is removed.

### Crash Report

[2.6.1-fml-client-latest.log](https://github.com/user-attachments/files/18053583/2.6.1-fml-client-latest.log)
[2.7.0](https://pastebin.com/6PEMfviN)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2024-12-11 20:58
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16632

**Closed by chochem** 2024-12-11 20:58 UTC
Labels: Crash, Status: Triage
