### ISSUE TITLE
AE refuses to start on some patterns

### ISSUE THREAD

**Issue by jonanlsh** [GTNewHorizons/GT-New-Horizons-Modpack#10630] opened 2022-07-05 03:45 UTC
### Your GTNH Discord Username

jonanlsh#2693

### Your Pack Version

GTNH-1.7.10-2.1.2.4-14-pre

### Your Server

SP

### Your Expectation

Opened AE and tried to order up a 64A ZPM Dynamo Hatch. Recipe was coded previously and had worked before. Checked the pattern and it was valid. Clicked Start when at the item manifest after inputting in the quantity.

### The Reality

AE does not register when I click on Start. It allows me to select the crafting CPU and to cancel the order, but it will not allow me to Start the autocrafting recipe. This only happens for some patterns, others still work.

### Your Proposal

Have AE be able to autocraft that pattern again.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment] 2022-07-05 03:55
Duplicate of #10590

**Closed by miozune** 2022-07-05 03:55 UTC
Labels: Type: bugMinor, Status: Triage
