### ISSUE TITLE
Railcraft Firestone Ore won't macerate

### ISSUE THREAD

**Issue by Mad-Gnome** [GTNewHorizons/GT-New-Horizons-Modpack#17618] opened 2024-10-11 13:56 UTC
### Your GTNH Discord Username

MadGnome

### Your Pack Version

2.7.0 Beta 2

### Your Server

Private Server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

When mining (manually or with ore miner) only Railcraft Firestone blocks are mined.  The Macerator will not process them.
![FirestoneMacerator](https://github.com/user-attachments/assets/b59c5fe8-a413-4190-bb8f-a96e701fb93c)

### The Reality

Nothing happens, they won't process in the Macerator.

### Your Proposal

Make them process in the Macerator, or make the Gregtech Firestone Ore drop instead when manually mined/mined with Miner.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2024-10-11 15:13
duplicate of a few others and fixed

**Closed by chochem** 2024-10-11 15:13 UTC
Labels: Type: bugMinor, Status: Triage
