### ISSUE TITLE
rubber wood in centrifuge issue

### ISSUE THREAD

**Issue by AoNoAsgard** [GTNewHorizons/GT-New-Horizons-Modpack#6049] opened 2020-05-05 11:01 UTC
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
in a private server 
#
#### What did you try to do, and what did you expect to happen?
i put rubber wood and a programmed circuit in a centrifuge to get sticky resin and stuff
#
#### What happened instead? (Attach screenshots if needed)
it looks like it doesn't see the programmed circuit and does the recipe only for the methane
#
#### What do you suggest instead/what changes do you propose?
if it's possible remove the basic wood recipe(only for rubber wood) for methane and leave the one for sticky resin and stuff without the circuit

**Comment by AoNoAsgard** [comment] 2020-05-05 11:02
yesterday the recipe worked but now it doesn't for no reason

**Comment by chochem** [comment] 2020-05-05 11:04
Duplicate of #5243

**Comment by AoNoAsgard** [comment] 2020-05-05 11:07
didn't noticed, sorry for that

**Closed** 2020-05-05 11:07 UTC
