### ISSUE TITLE
Adding Batch Mode and MAX+OC for Draconic Evolution Fusion Crafter

### ISSUE THREAD

**Issue by 255344610** [GTNewHorizons/GT-New-Horizons-Modpack#14032] opened 2023-07-23 19:11 UTC
### Your GTNH Discord Username

Roy

### Your Pack Version

2.3.4

### Your Proposal

Adding Batch Mode and MAX+OC for Draconic Evolution Fusion Crafter

### Your Goal

The Draconic Evolution Fusion Crafter is mainly used in the later stages of the game to produce dragonblood and some Draconic Evolution materials. However, there are too many Draconic Evolution basic materials required to produce some advanced materials, and DEFC can only complete the work once within 1 tick, which will bring huge delays. The inability to MAX+overclock also limits the production speed of dragon blood in the later stages of the game (relative to the very terrifying usage)

### Your Vision

Reduce the delay caused by DEFC in the final stage of the game

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment] 2023-07-23 19:13
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14024

**Closed by chochem** 2023-07-23 19:13 UTC
Labels: Type: Suggestion, Status: Triage
