### ISSUE TITLE
Industrial Apiary Lifespan upgrades

### ISSUE THREAD

**Issue by BlueWeabo** [GTNewHorizons/GT-New-Horizons-Modpack#11119] opened 2022-08-23 19:26 UTC
### Your GTNH Discord Username

BlueWeabo#7517

### Your Pack Version

2.1.2.4-28-pre

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Expectation

Lifespan upgrades decrease the time needed for the bee and keep the same drops

### The Reality

Lifespan upgrades decrease the drops for bees with Normal+ lifespan and increase the drops of bees with shorter and lower lifespan.

### Your Proposal

Lifespan upgrades should not change drop amount and only change the time needed. OR keep the same time, but increase the drops.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2022-08-23 19:51
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10952

**Closed by chochem** 2022-08-23 19:51 UTC
Labels: Type: bugMinor, Status: Triage
