### ISSUE TITLE
Hitting a mob with a Tinker's Construct weapon causes a crash

### ISSUE THREAD

**Issue by Velrous** [GTNewHorizons/GT-New-Horizons-Modpack#12622] opened 2023-02-17 13:34 UTC
### Your Pack Version

2.2.9

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

I decided to upgrade from version 2.2.8 to 2.2.9. Transferred the save, some mods (FTBLib-1.7.10-1.0.18.3, FTBUtilities-1.7.10-1.0.18.3, OptiFine_1.7.10_HD_U_E7) and JourneyMap data. When I started my save, I got an error and threw it into the list of servers. 

![Screenshot 2023-02-17 161150](https://user-images.githubusercontent.com/49007725/219662138-d38bab34-4a3d-4aa3-b122-426c418e4283.jpg)
![Screenshot 2023-02-17 161201](https://user-images.githubusercontent.com/49007725/219662171-30a9d935-f149-471a-9cce-5a3a9cb75ea9.jpg)

This happens every time after restarting Minecraft. After trying a second time, I was able to enter my world, but I ran into an interesting situation. As soon as I try to hit a mob (it was both a standard small zombie and a large black skeleton) with my sword from Tinkers' Construct, the game freezes and a crash message appears.

![Screenshot 2023-02-17 160505](https://user-images.githubusercontent.com/49007725/219662320-afe2ac64-76a2-4c17-9993-17dbf3176a84.jpg)

Since I can repeat this crash an infinite number of times, I reloaded my save and filmed the process on video.
https://youtu.be/zuINpbCKHN0

### Crash Report

https://paste.ubuntu.com/p/MCn3PQq5Gy/
[crash-2023-02-17_15.57.19-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10767077/crash-2023-02-17_15.57.19-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2023-02-17 13:50
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12567

**Closed by chochem** 2023-02-17 13:50 UTC
Labels: Type: Duplicate, Type: Crash, Status: Triage
