### ISSUE TITLE
Fluid cells can be macerated for Tin and can be made from PTFE

### ISSUE THREAD

**Issue by 48a3efa65c881ef567345b17f3910e06** [GTNewHorizons/GT-New-Horizons-Modpack#17582] opened 2024-10-06 17:42 UTC
### Your GTNH Discord Username

33yy

### Your Pack Version

nightly 686

### Your Server

my own server

### Java Version

Java 21

### Type of Server

None

### Your Expectation

Fluid cells can be made from 1 ptfe sheet -> 4 fluid cells in the bender, they shouldn't be able to be macerated for tin

### The Reality

One fluid cell -> 2 tin, this means 1 PTFE = 8 tin  (very cursed way to make a tin singularity)

### Your Proposal

Remove the macerating recipe

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2024-10-06 17:54
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17127

**Closed by chochem** 2024-10-06 17:54 UTC
Labels: Type: bugMinor, Status: Triage
