### ISSUE TITLE
Crash when I am in Twilight forest (Says Natura and Twilight forest are the crash cause)

### ISSUE THREAD

**Issue by Jfardeen** [GTNewHorizons/GT-New-Horizons-Modpack#17642] opened 2024-10-16 04:00 UTC
### Your GTNH Discord Username

thajetplane

### Your Pack Version

GT: New Horizons 2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

I drank a Laudanum (Weakness 3, Slowness 3, Mining Fatigue 3, Nausea) and jumped off a lich tower with a hang glider - it happened again when I was just on a tree. This required a full relaunch to get back in and simply reloading the world afterwards using BetterCrashes would cause MC to not respond. The second crash wasn't immediate, in fact, I played for about 15 seconds before it did it again (and moved a decent bit away from the location of the first crash as well)

It says the suspected mods are TF and Natura and from a base glance at the log it seems like it had to do with bluebells generating somewhere?

I have been able to play again after the crash so I don't think this corrupted the save, but I crashed effectively twice in a row here

This could potentially be the same as the naga generation crash, but Nature was mentioned here, so I wasn't sure.

### Crash Report

1st crash: https://mclo.gs/yy1jCud

2nd crash: https://mclo.gs/DYX4V6h

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by FourIsTheNumber** [comment] 2024-10-16 04:07
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16353 and approximately five billion others. Update twilight forest mod here https://github.com/GTNewHorizons/twilightforest/releases/download/2.6.12/TwilightForest-2.6.12.jar

**Closed by FourIsTheNumber** 2024-10-16 04:07 UTC
Labels: Type: Crash, Status: Triage

**Comment by Jfardeen** [comment] 2024-10-16 04:23
Sorry for posting a dupe. and thank you for linking the fix (it worked :) ). I hope you have a great rest of your day.
