### ISSUE TITLE
Stardust bee cannot be mutating on 2.0.9.0 - 2.1.0.0

### ISSUE THREAD

**Issue by Vernam** [GTNewHorizons/GT-New-Horizons-Modpack#7297] opened 2021-01-11 19:20 UTC
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
local
#
#### What did you try to do, and what did you expect to happen?
Tried to breed Stardust bee ( HEE material bee )
#
#### What happened instead? (Attach screenshots if needed)
this mutation doesn't work
#
#### What do you suggest instead/what changes do you propose?
tested on new 2.1.0.0 version, same problem. All requirements  for mutation is done. Tried Stardust ore block as foundation, its analog too. Tried on Alveary too. Change biome for requirement "arid" is done. I hope it will be fixed because  tried on new and old versions... 
Maybe mutation doesn't see block as a foundation like the same problem when Alveary doesn't see thaum clusters for thaum bees.

**Comment by combusterf** [comment] 2021-02-09 21:47
I can confirm the same problem exists on the public servers, using an apiary and satisfying the biome (changed it to "glacier"),  Dimension and foundation requirements as per the NEI tooltip.

**Comment by KiloJoel** [comment] 2021-02-16 08:49
The issue seems to be from the humidity requirement. All GT mutations with a humidity req. don't work. Not sure if other mods have any with humidity reqs.

I'm going to look into this more shortly.

**Comment by Dream-Master** [comment] 2021-02-16 09:32
guess we need to rework gt bee code. Some stuff not working well

**Comment by KiloJoel** [comment] 2021-02-16 18:46
> guess we need to rework gt bee code. Some stuff not working well

Oh are there other problems? I'm only aware of this one

**Comment by boubou19** [comment] 2021-08-11 16:11
according to code, the bees need to be in the end dimension: https://github.com/GTNewHorizons/GT5-Unofficial/blob/5451998388b35d89d3496ae3e16694983a31f6cb/src/main/java/gregtech/loaders/misc/GT_BeeDefinition.java#L1591
Has someone tried to breed them in the end?

**Comment by Dream-Master** [comment] 2021-08-11 16:15
Maybe the end have no arid biome so we need to change that. Not sure if we can change the codition with forestry addons or witchery

**Comment by Zeruel13** [comment] 2021-08-11 16:15
> according to code, the bees need to be in the end dimension: https://github.com/GTNewHorizons/GT5-Unofficial/blob/5451998388b35d89d3496ae3e16694983a31f6cb/src/main/java/gregtech/loaders/misc/GT_BeeDefinition.java#L1591
> Has someone tried to breed them in the end?

Yes, I have and has @KiloJoel. There is no biome in the end that has a natural arid humidity so you have to use an alveary with heaters in the end. The problem is that with GT bees, changing the climate via alveary blocks doesn't work. Removing the arid requirement is a band-aid fix to this larger problem.

**Comment by Dream-Master** [comment] 2021-08-11 16:21
Better to find out the problem why biome cant canged with forestry alveary. Maybe the gt code is wrong. Remove Biome req. is duct taping.

**Comment by Prometheus0000** [comment] 2021-08-11 16:28
Duct taping is fine if no one fixes the real problem though isn't it? How long has this problem existed without anyone doing anything about it? I'd rather not have a situation where they can't be bred because no one feels like fixing it. Of course I'll be happy if someone does so.

Also, setting a breeding condition that can't naturally occur is kinda weird to begin with. All the ones that require the end dim should also want the same humidity/temp as found _in_ the end.

**Comment by Dream-Master** [comment] 2021-08-11 16:29
And if this not worked all bees that have a unobtainable Biome in this dim will not work. So a major bug which need a fix

**Comment by boubou19** [comment] 2021-08-11 16:30
Pack has been duct taped too much (how many time a code issue has been fixed with a quest description?). Understanding why the code is borked will let us do better integration than just removing what doesn't work.

**Comment by Dream-Master** [comment] 2021-08-11 16:32
Bee conditions was randomly choosen before so i guess we need to rework it a bit. But again if the biomes humidity cant be changed with forestry a lot of Bees dont work.

**Closed** 2021-08-14 13:50 UTC
Labels: Type: bugMajor, Type: Bees
