### ISSUE TITLE
Holding an item zooms the screen and becomes unplayable

### ISSUE THREAD

**Issue by Nasuu1** [GTNewHorizons/GT-New-Horizons-Modpack#11098] opened 2022-08-22 10:41 UTC
### Your GTNH Discord Username

nasu#7968

### Your Pack Version

2.1.2.0

### Your Server

SP

### Your Expectation

Holding any item or opening inventory causes the screen to zoom in very close.

### The Reality

Holding any item or opening inventory causes the screen to zoom in very close. Also some rendering issues.
![image](https://user-images.githubusercontent.com/111744859/185902312-c3a7ce95-9408-4884-b9aa-cef224957209.png)

While holding an item:
![image](https://user-images.githubusercontent.com/111744859/185902390-af7c4ec6-8d59-49c7-9b1b-c211be4256e2.png)

While inventory is open:
![image](https://user-images.githubusercontent.com/111744859/185902495-8030ddaa-0446-412d-9bfd-726d93b7dafd.png)

### Your Proposal

Hope to find a known fix for this

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GTNHAfx237v7** [comment] 2022-08-22 10:52
Possible duplicate of #10490

**Comment by boubou19** [comment] 2022-08-22 10:54
Yeah looks like an intel driver issue. See #10490 for more details.

**Closed by boubou19** 2022-08-22 10:54 UTC
Labels: Type: bugMinor, Status: Triage
