### ISSUE TITLE
Mod Suggestion: Just Enough Calculations

### ISSUE THREAD

**Issue by legacywarfare** [GTNewHorizons/GT-New-Horizons-Modpack#8731] opened 2021-10-24 22:23 UTC
### Your GTNH Discord Username

LW#1100

### Your Pack Version

2.1.1.0

### Mod Name

Just Enough Calculations

### The Mod to Add

It provides recipe cost calculation and the steps you would take to craft an item, helping visualize the cost of items(also provides an in game simple calculator).  User sets up both the recipe they want and how each item in the branching recipe would be obtained (ex. redstone alloy cables can be configured and changed to use both the alloy smelter and 2 rubber OR a rubber sheet and a wire in a crafting table).  Mod also has inventory detection to see what you are missing currently to complete a craft.

Example of my current cost of an LV electronic Circuit:

![image](https://user-images.githubusercontent.com/92343415/138615205-1a5948c3-a09f-431e-8d57-d95e1d29bd1c.png)

Example of Recipe integreation (Red Alloy Cable)
![image](https://user-images.githubusercontent.com/92343415/138615233-015e9d2e-9fbb-4414-8b69-c77c66a06a2d.png)

Example of MY current steps for crafting an electronic circuit:

![image](https://user-images.githubusercontent.com/92343415/138615252-2b1f982a-b6ca-479a-b8a8-61c380fbe393.png)

In game Calculator GUI:

![image](https://user-images.githubusercontent.com/92343415/138615287-3ded00fb-e43c-475f-8ade-d19b29eead8f.png)

### Your Reason

When batch crafting and figuring out the true cost of components (ex, conveyor belts, motorts etc.) having the mod show exactly how much of each resource is needed per craft when configured to your liking.  I can see this being helpful even outside of lower tiers as it can provide a clearer route for automated crafting setups on what is required in each given recipe as shown in the "steps" example.

### Preliminary Investigation

It has absolutely made the early game a lot more digestible helping see the true cost of items and how much you need of resources when batch crafting a bunch of components.  Although the mod itself has very little documentation online, it only took me a few minutes to figure out how it exactly worked for my personal needs. The mod exists in another gregtech modpack, Omnifactory in which the GUI exists as an early game item you can craft, in the 1.7.10 backport of the mod it is is a simple key bind to open it up. 

### Final Checklist

- [X] This mod is released under an open source license. Yes, this is required now.
- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this mod, please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.
- [ ] I'm the official maintainer or original author of this mod for minecraft 1.7.10.

**Comment by yukieiji** [comment] 2021-10-25 00:21
Duplicate of #7990, #7899, #6145, #3186, #1185

**Closed as completed** 2021-10-25 00:34 UTC
Labels: Type: Mod Addition, Status: Triage
