### ISSUE TITLE
Slice@spice auto-item-placement broken

### ISSUE THREAD

**Issue by Cinobi** [GTNewHorizons/GT-New-Horizons-Modpack#8113] opened 2021-06-25 16:49 UTC
#### Which modpack version are you using?
Zeta live
#
#### If in multiplayer; On which server does this happen? 
Zeta
#
#### What did you try to do, and what did you expect to happen?
Shfit+click to silicone plates and expect them go to correct places at recipe
#
#### What happened instead? (Attach screenshots if needed)
the machine accepts plates at wrong positions
#

As all of you probably know, eio slice@spice need items be placed in it in a strict order and it places items itself - so u can just shift+click to all recipe components to them to go to right places. With new EIO recipes(this two i guess) 
![изображение](https://user-images.githubusercontent.com/25028786/123458591-e0c67500-d5ed-11eb-83d8-2922cb3b6907.png)
silicone plates can go not at 1-3 bottom row slots but to center slot too, and this breaks this two recipes 
![изображение](https://user-images.githubusercontent.com/25028786/123458706-0489bb00-d5ee-11eb-86f6-ae29025b7d8e.png)
because we get this situation
![изображение](https://user-images.githubusercontent.com/25028786/123458821-27b46a80-d5ee-11eb-843b-6af86ff1b281.png)
when trying to automate this two broken recipes.
#### What do you suggest instead/what changes do you propose?
Replace silicon at this recipes with smt else
![изображение](https://user-images.githubusercontent.com/25028786/123458957-50d4fb00-d5ee-11eb-91e6-290a4fe93008.png)
with electric steel, for example
#
#### What is your GTNH Discord username?
Cinobi

**Comment by Prometheus0000** [comment] 2021-06-25 17:41
Duplicate of #7242

**Closed by Prometheus0000** 2021-06-25 17:41 UTC
