### ISSUE TITLE
Crashing whenever I join server, not sure whats causing it.

### ISSUE THREAD

**Issue by TMPJoker** [GTNewHorizons/GT-New-Horizons-Modpack#12536] opened 2023-02-09 16:30 UTC
### Your GTNH Discord Username

Spiff#3353

### Your Pack Version

2.28

### Your Server

Private Server

### Type of Server

Don't know

### Your Actions

Tried to reset everything, reinstalled pack multiple times, cleaned install etc etc  nothing seems to work. it works in SIngle player but whenever I join server I crash, nothing else seems to work.

### Crash Report

[fml-client-3.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10699338/fml-client-3.log)
[MultiMC-3.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10699343/MultiMC-3.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2023-02-09 18:24
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12077

**Closed by chochem** 2023-02-09 18:24 UTC
Labels: Type: Crash, Status: Triage
