### ISSUE TITLE
ME Dual Interface leaves extra resources

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/GT-New-Horizons-Modpack#15680] opened 2024-03-09 09:19 UTC
### Your GTNH Discord Username

kebal#2759

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Blue Steel Recipe in a single block mixer with circuit 16.

Copper + Gold + Zinc + Steel Dust + 80 Black Steel = 160 Blue Steel.

ME Dual Interface is in a blocking mode. Should use 80 Black Steel to craft.

### The Reality

It consumes 80 black steel. Starts a recipe and outputs correct 160 blue steel. But after the recipe has started it will put extra 16 black steel inside a singleblock.

So in the end the overall recipe consumed only 64 black steel. There is a 16 black steel extra left. This can be repeated for any similar recipe.

### Your Proposal

Fix the bug. It can be  used to dupe resources at any tier for a recipe that has over 64 resources inside a singleblock.

How did I dupe - craft blue steel, centrifuge blue steel. Received 16 black steel for free. Even though black steel is cheap, just find a recipe with expensive resource and repeat in the same way.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lyfts** [comment] 2024-03-09 09:43
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15606

**Closed by Lyfts** 2024-03-09 09:43 UTC
Labels: Type: bugMinor, Status: Triage
