### ISSUE TITLE
Plasma Forge energy hatch issues

### ISSUE THREAD

**Issue by GDCloudstrike** [GTNewHorizons/GT-New-Horizons-Modpack#10557] opened 2022-06-26 23:54 UTC
### Your GTNH Discord Username

GDCloud#2907

### Your Pack Version

2.1.2.4-dev-pre14

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Trying to use multi-amp hatches, lasers or just more than 2 regular energy hatches on a Plasma Forge. Expected it to form.

### The Reality

The Plasma Forge doesn't form with lasers, multi-amp hatches or more than 2 regular energy hatches. It only forms with a max of 2 regular energy hatches.

![2022-06-27_01 39 31](https://user-images.githubusercontent.com/93287602/175838737-d7d5af23-5495-40bf-8b7d-600ae5cc72b4.png)
![2022-06-27_01 39 41](https://user-images.githubusercontent.com/93287602/175838741-2b3c628f-515d-4c1f-ba76-259a6d839483.png)
![2022-06-27_01 40 30](https://user-images.githubusercontent.com/93287602/175838747-6d0c8f2f-d80f-4371-808f-ab74957ddbcf.png)
![2022-06-27_01 41 05](https://user-images.githubusercontent.com/93287602/175838751-9d0c8944-0575-4406-9ada-f15a16858d5b.png)
.

### Your Proposal

Make the Plasma Forge accept lasers and multi-amp hatches so that the more energy-intensive recipes are craftable.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Connor-Colenso** [comment] 2022-06-27 00:14
The max of two energy hatches is by design, TT energy hatch support is on my todo list when I can figure out how the Processing Array implemented it in base GT.

**Comment by miozune** [comment] 2022-08-02 07:08
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/1100

**Closed by miozune** 2022-08-02 07:08 UTC
Labels: Type: bugMinor, Status: Triage
