### ISSUE TITLE
AE2 Busses and Interfaces Stop working

### ISSUE THREAD

**Issue by kilianloftis** [GTNewHorizons/GT-New-Horizons-Modpack#12612] opened 2023-02-16 06:52 UTC
### Your GTNH Discord Username

martok111

### Your Pack Version

2.2.8

### Your Server

SP

### Java Version

Java 11

### Type of Server

Single Player

### Your Expectation

AE2, EC, and AE2FC busses and interfaces work consistently

### The Reality

Intermittently, individual peripherals will stop working. They are not offline, channels are available, the system has power, and storage space. Items or fluids are in the output bus waiting to be imported into the system, or there is space available in the input bus, but no items are transferred.

- All of these are on the other side of a P2P interface. That said, I don't have any busses connected directly to the ME Core
- Breaking and replacing a cable nearby causes the peripheral to start working again
- Break and replacing nearly all the p2p connection (a cable between the two interfaces), and leaving for several hours, will allows all peripherals to work for a few days, before the begin stopping again.
- The interfaces that stopped working were acting as import busses. I don't think I've seen any missing recipes yet

### Your Proposal

Ask me for more information, guide me through some troubleshooting. The issues is intermittent, but I usually find a broken peripheral every few minutes, now.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2023-02-20 10:27
double/triple check that everything(!) is chunkloaded and that there are enough channels

**Comment by kilianloftis** [comment] 2023-02-21 00:57
Confirmed. Definitely enough channels. Checked chunk loading a few times now. I've definitely had areas not loaded, but that creates a different problem: the system will go offline periodically. In this case the system and peripherals never go offline, they just stop doing what they ought to be.

Btw, this has been going on for a long time for me. Don't remember exactly when it started, but before the GTNH changes to the AE2 UI.

**Comment by Kyrorichekku** [comment] 2023-02-22 13:57
> Confirmed. Definitely enough channels. Checked chunk loading a few times now. I've definitely had areas not loaded, but that creates a different problem: the system will go offline periodically. In this case the system and peripherals never go offline, they just stop doing what they ought to be.
> 
> Btw, this has been going on for a long time for me. Don't remember exactly when it started, but before the GTNH changes to the AE2 UI.

are you using backbone cables as it could be the source of the issue like I'd reported with https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12382

**Comment by kilianloftis** [comment] 2023-02-22 15:28
No backbone cables in the network at all.

**Comment by kilianloftis** [comment] 2023-03-09 06:52
Just had an interface connected directly to the controller stop responding. No P2P involved.

**Comment by kilianloftis** [comment] 2023-03-17 04:57
Is there some logging I can enable to help? Other things I can try to help troubleshoot?

I was about to remove AE2, and re-add it - start AE2 from scratch - but apparently Gregtech is dependent on it.

**Comment by Kataiser9** [comment] 2023-03-17 07:08
Same issue. Just abruptly started happening after a few hundred hours of using AE2 with no issues; it now happens near-constantly. I have no idea where to start with diagnosing the problem, so here are some random observations:


- As with OP, everything is chunkloaded and channels are fine (in fact, the devices that stop working display "Device Online" in WAILA). Network and all subnets are completely fine on power.
- Export buses and occasionally interfaces (that are currently exporting stuff to craft) stop working. Fluid export buses do not, AFAICT.
- Strange behavior with breaking and replacing cables. I've been testing this with two specific export buses. For one of them, if I wrench and replace the cable, _every_ stuck peripheral on the network (even those on completely different cable lines) starts working again for a brief period (20 seconds to several minutes depending on the peripheral). Wrenching and replacing a controller block has a similar effect. If I wrench and replace the cable on the other one, nothing happens.

Considering that this makes large portions of my automation essentially unusable without resetting them every minute or two, it's somewhat gamebreaking. Any leads or advice would be appreciated.

**Comment by Kataiser9** [comment] 2023-03-19 04:05
After a few hours of trial and error, I've narrowed down the peripheral causing the problem. It's a fluid export bus with a redstone card (set to "export with signal"), receiving a signal, attempting to export to a machine that is usually full. I still need to do some more testing to figure out which of those elements matter. However, the export bus causes no problems unless the redstone card is present.

@kilianloftis Maybe check if something similar to the above exists in your own network?

**Comment by kilianloftis** [comment] 2023-03-19 06:59
Omg, finally someone else having this problem!! Not that I'm wishing this on anyone.

How on earth did you figure out that export bus? Did everything start working again when you removed it?

I tried re-enabling chunks of my network at a time, but it took a couple days for something to go offline after everything was enabled again. I'll try removing the redstone cards.

Hit me up on discord if you want to chat: martok111

**Comment by El-Basurero** [comment] 2023-03-28 01:47
> t's a fluid export bus with a redstone card (set to "export with signal"), receiving a signal, attempting to export to a machine that is usually full. 
> 

I had run into a similar issue where my p2p tunnels disconnected after I removed a cable. I was able to resolve by removing the signals from my export buses with redstone cards set to "export signal". They weren't exporting into full machines so I think it's just related to an export bus with a redstone card receiving a redstone signal.

**Comment by kilianloftis** [comment] 2023-03-28 05:10
Yeah, can confirm: I removed my redstone cards, and I haven't seen the issue in a week.

**Comment by Kataiser9** [comment] 2023-03-30 18:57
I've had it start happening again, albeit less frequently (twice in the last week). Both times, it's been shortly after adding an export or fluid export bus near a redstone signal source. More testing is needed, but so far it seems like the issue isn't actually the redstone cards - it's buses receiving redstone at all.

**Comment by firenoo** [comment] 2023-07-16 16:52
This may be fixed by https://github.com/GTNewHorizons/Applied-Energistics-2-Unofficial/pull/353

comment to reopen

**Closed by firenoo** 2023-07-16 16:52 UTC
Labels: Type: bugMinor, Mod: AE2, Status: Triage
