### ISSUE TITLE
The crafting table recipe for some items does not match the quantity produced by the assembler recipe.

### ISSUE THREAD

**Issue by Onean1** [GTNewHorizons/GT-New-Horizons-Modpack#14668] opened 2023-10-07 07:24 UTC
### Your Pack Version

gtnh-nightly-2023-10-06+159

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Make something

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/147234411/e3267455-92b4-412a-97b8-990814513146)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/147234411/61148c0c-2897-4de5-9057-d1b7b769ff10)

### Your Proposal

Align the quantity produced by the assembly machine recipe with the quantity produced by the crafting table recipe

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2023-10-07 10:27
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14668

**Closed by chochem** 2023-10-07 10:27 UTC
Labels: Type: bugMinor, Status: Triage
