### ISSUE TITLE
Void Putty 'repair's items by changing metadata (like the old life imbuer)

### ISSUE THREAD

**Issue by feliser** [GTNewHorizons/GT-New-Horizons-Modpack#6193] opened 2020-06-02 02:10 UTC
#### Which modpack version are you using?
2.0.8.8
#
#### If in multiplayer; On which server does this happen? 
Private Multiplayer Server
#
#### What did you try to do, and what did you expect to happen?
Tried using void putty to repair empty fuel canister to see what would happen.
Also, if you are using void putty on a partially filled fuel canister (ex. Diesel, LOX) it refills the canister to full
#
#### What happened instead? (Attach screenshots if needed)
![cde9d37e546350c695080f88a8468176](https://user-images.githubusercontent.com/37637640/83472185-a9ba7a00-a454-11ea-8df0-e631a5ff27d7.png)
#
#### What do you suggest instead/what changes do you propose?
Fix

**Comment by Prometheus0000** [comment] 2020-06-02 04:29
Confirmed, it also creates a duplicate of the canister too. There aren't that many types of canister, so you can't abuse it too much.

**Comment by repo-alt** [comment] 2020-06-02 10:04
Refilling the fuel with a void putty is not even abuse. I would argue that even duplicating the canister is not really serious, you can't even recycle it iirc

**Comment by Dream-Master** [comment] 2020-06-02 17:08
Void Putty is from which mod ?
Guess we have the source to fixed it in code.
@Prometheus0000 
@repo-alt 
@feliser

**Comment by feliser** [comment] 2020-06-02 17:09
I think it is from thaumic horizons

**Comment by repo-alt** [comment] 2020-06-02 17:10
May regard it as somewhat extravagant (and expensive) way to get fuel.

**Comment by Dream-Master** [comment] 2020-06-02 17:10
or if it use up some materials its ok for me some magical way get items.

**Comment by feliser** [comment] 2020-06-02 17:11
To get void putty you throw void metal into the planar vortex so this is a very expensive way to get oil

**Comment by feliser** [comment] 2020-06-02 17:14
Yes this is not a big deal, but the void putty also has some other questionable interactions for example when used to repair the wool gin from project red it duplicates it (not sure if i should make a seperate issue). Also void putty can be used to repair the gt++ bee frames (which cant be reapired with thaumic restorer) although I think this is kind of cool as it gives a reason to actually make the planar vortex

**Comment by Dream-Master** [comment] 2020-06-02 17:18
@feliser feel free to add it here with some screenshots and rename the titel or make a new issue if you like.

**Comment by feliser** [comment] 2020-06-02 17:19
Alright I will open new issues later today

**Comment by Dream-Master** [comment] 2020-06-02 17:20
@feliser ok good
if thi issue is solved or answered just close it.If not just comment and let it open.
Thanks

**Comment by draknyte1** [comment] 2020-06-12 14:45
Void putty should actually check if things are repairable.

**Comment by Prometheus0000** [comment] 2020-06-12 16:52
@feliser Where's those issues?

**Comment by Anarack** [comment] 2020-07-15 00:42
doesn't seem to work on gt dust at least.
it will work on stuff like ic2 coolant cells as well
so it has some detection for things it should very not work on
it can repair fuel rods... ya this thing has some problems
@draknyte1

**Comment by Prometheus0000** [comment] 2020-09-13 23:04
Related: #2824, #3017.

**Comment by Rakdarian** [comment] 2020-10-13 18:17
Didn't dream already give this interaction the green light?

**Comment by Prometheus0000** [comment] 2020-10-13 18:19
No? And this only checks to see if an item is repairable. If it can be repaired, it still will be.

**Comment by Rakdarian** [comment] 2020-10-13 18:25
"ok so it is ok for me let the recipe in"

**Comment by Prometheus0000** [comment] 2020-10-13 18:26
? Dream's quotes are not always understandable without context.

**Closed** 2020-11-03 17:15 UTC
Labels: Status: FixedInDev, Type: bugMinor
