### ISSUE TITLE
The game crashes almost immediately upon loading the world on Nightly 238

### ISSUE THREAD

**Issue by TorvikW** [GTNewHorizons/GT-New-Horizons-Modpack#14956] opened 2023-11-28 19:27 UTC
### Your GTNH Discord Username

Torvik

### Your Pack Version

Nightly 238

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

The world loads in fine and I can look around, but as soon as I move the game crashes.

### Crash Report

[crash-2023-11-28_14.15.58-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/13492338/crash-2023-11-28_14.15.58-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Cleptomania** [comment] 2023-11-28 19:52
This is almost certainly caused by NotEnoughIDs update. I will try and re-produce and hunt down the cause today/tomorrow.

**Comment by Cleptomania** [comment] 2023-11-28 20:51
Yeah that tracks, Nightly 238 upgrades from NEID 1.4.6 to 1.5.1 which is more or less a complete re-write of the mod. Should be able to track it down easy though.

**Comment by Cleptomania** [comment] 2023-11-29 06:11
https://github.com/GTNewHorizons/NotEnoughIds/pull/6

I've put in a PR for a fix for this in NEID, should be fixed in nightlies whenever that gets merged, released, and picked up in the nightly builds.

**Closed** 2023-11-30 05:29 UTC
Labels: Type: Crash
