### ISSUE TITLE
Page 2 of the Narslimmus entry in the Lexica Botania crashes the game

### ISSUE THREAD

**Issue by OrderedSet86** [GTNewHorizons/GT-New-Horizons-Modpack#9771] opened 2022-02-18 18:07 UTC
### Your GTNH Discord Username

Order#0001

### Your Pack Version

2.1.2.2qf2

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Actions

1. Open Lexica Botania
2. Go to "Generating Flora"
3. Open "Narslimmus"
4. Go to page 2
5. Game crash with divide by 0 error

### Crash Report

[2022-02-18-2.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/8099410/2022-02-18-2.log)
Relevant section:
![image](https://user-images.githubusercontent.com/88752681/154738204-1b705335-513d-4498-b042-3a05d4062a50.png)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment] 2022-02-19 03:25
It seems you are using outdated version of Botanic Horizons btw.

**Comment by OrderedSet86** [comment] 2022-02-20 00:17
This is the Feb 04 version of 2.1.2.2qf2, downloaded from DevPacks.

**Comment by combusterf** [comment] 2022-02-20 12:06
This is actually a duplicate of #9614

**Closed** 2022-02-20 13:09 UTC
Labels: Type: Duplicate, Status: FixedInDev, Type: Crash, Mod: Botania
