### ISSUE TITLE
Client crash (thaumcrft -> golemancy)

### ISSUE THREAD

**Issue by Zereff06** [GTNewHorizons/GT-New-Horizons-Modpack#8129] opened 2021-06-26 20:52 UTC
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
own server
#
#### What did you try to do, and what did you expect to happen?
Water core from golemancy
Right click on the cluster with the wand
![image](https://user-images.githubusercontent.com/17906427/123525513-e26d6700-d6d9-11eb-9ed5-f39e716914de.png)
[crash-2021-06-26_23.43.05-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6720826/crash-2021-06-26_23.43.05-client.txt)

#
#### What happened instead? (Attach screenshots if needed)
client crash
#
#### What do you suggest instead/what changes do you propose?
Fix it
#
#### What is your GTNH Discord username?
Кетцаль#0802

**Comment by Glease** [comment] 2021-06-27 07:39
Duplicate of #8075.

**Closed by Glease** 2021-06-27 07:39 UTC
