### ISSUE TITLE
Rechargeable Scribing Tools Quest Description Mistake

### ISSUE THREAD

**Issue by DSLM** [GTNewHorizons/GT-New-Horizons-Modpack#7518] opened 2021-02-23 12:45 UTC
#### Which modpack version are you using?
2.1.0.3a.
#
#### If in multiplayer; On which server does this happen? 
Not multiplayer.
#
#### What did you try to do, and what did you expect to happen?
The Quest.1354 said Rechargeable Scribing Tools is a LV tool, so I put it into LV battery buffer.
#
#### What happened instead? (Attach screenshots if needed)
It won't be charged in LV battery buffer, and it just works at HV battery buffer.
#
#### What do you suggest instead/what changes do you propose?
Fix the quest description, change the "LV" to "HV".

**Comment by Prometheus0000** [comment] 2021-02-23 12:47
Duplicate of #6281. No one add the quest label, so I didn't see it. I thought the item was just bugged.

**Closed by Prometheus0000** 2021-02-23 12:47 UTC
Labels: Type: duplicate
