### ISSUE TITLE
收藏馆mod 精致工作台可以复制物品

### ISSUE THREAD

**Issue by mingkong233** [GTNewHorizons/GT-New-Horizons-Modpack#12475] opened 2023-02-03 05:13 UTC
### Your Pack Version

2.2.0.0

### Your Proposal

收藏馆(BiblioCraft)mod中，精致工作台该物品可以复制物品，例如两个压缩箱子，有物品的为a，无物品的为b，把a放在精致工作台里保存配方，点击使用物品栏中的物品合成，可以把b变为a。

### Your Goal

可以复制物品，复制附魔，修改nbt。

### Your Vision

该物品应ban掉

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Dream-Master** [comment] 2023-02-03 07:42
google traslation:

### Your Proposal:

In the Bibliocraft MOD, the items of the exquisite workbench can be replicated, such as two compressed boxes, which are A, no items are B, put A in the exquisite workbench to save the formula, click the item bar to use the item bar The items in it can turn B to A.

### Your Goal

You can copy items, copy the enchantment, and modify the NBT.

### Your Vision

This item should be banned

**Comment by BritishCynic** [comment] 2023-02-03 09:26
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12424

**Closed by BritishCynic** 2023-02-03 09:26 UTC
Labels: Type: Suggestion, Status: Triage
