### ISSUE TITLE
Turn weblinks back on

### ISSUE THREAD

**Issue by Pallinaama** [GTNewHorizons/GT-New-Horizons-Modpack#5454] opened 2020-01-28 15:09 UTC
#### Which modpack version are you using?
2.0.8.1
#
#### If in multiplayer; On which server does this happen? 
official Epsilon, i guess every server that has defalut config.
#
#### What did you try to do, and what did you expect to happen?
tried to paste url in ingame chat
#
#### What happened instead? (Attach screenshots if needed)
url has dots removed and is essentially useless
#
#### What do you suggest instead/what changes do you propose?
turn config option web links to ON

**Comment by Viktor-KN** [comment] 2020-01-28 15:13
Links can pasted thru Discord chat without any limitations...

**Comment by GTNH-Colen** [comment] 2020-01-28 17:37
Honestly this is actually really annoying, it's frustrating for a lot of people especially if they don't have discord open. I'd definitely advocate for this config to be changed, it seems to be the default on virtually every server now. For large ones with problems of mass advertising and spam bots I can see the use but on private whitelisted modded servers it really doesn't need to be on at all.

**Comment by Pallinaama** [comment] 2020-01-28 19:46
> 
> 
> Links can be pasted thru Discord chat without any limitations...

I am well aware, IMO it strenghtens my point to make this change.

**Comment by Dream-Master** [comment] 2020-01-28 20:43
@GTNH-Colen @Pallinaama who knows if somone post some shit here. I vote for let it like it is. Switch to Discord isnt a big deal. Run game in windows mode np.

**Comment by Pallinaama** [comment] 2020-01-28 20:54
> 
> 
> @GTNH-Colen @Pallinaama who knows if somone post some shit here. I vote for let it like it is. Switch to Discord isnt a big deal. Run game in windows mode np.

well my point is, isn't spamming already againts the rules -> just ban the offender. And if you're allowed to post links from discord why not from ingame .. as it stand the restriction is completely arbitrary and asinine.

**Comment by GTNH-Colen** [comment] 2020-01-28 21:29
Yea the restriction makes very little sense given discord just allows you to bypass it anyways, this would be a really nice QoL change.

**Comment by Prometheus0000** [comment] 2021-03-21 17:44
@GTNH-Colen @boubou19 Either enable it or close the issue is _my_ vote.

**Comment by boubou19** [comment] 2021-03-21 17:45
Dream said no, so no it is.

**Closed by boubou19** 2021-03-21 17:45 UTC
Labels: Server: EU Live Server, Status: RFC (request for comment), Type: suggestion
