### ISSUE TITLE
Dynamise Tablet give fluorite ore from limestone

### ISSUE THREAD

**Issue by noobnoobnub** [GTNewHorizons/GT-New-Horizons-Modpack#5744] opened 2020-03-13 10:04 UTC
#### Which modpack version are you using?
2.0.8.6
#
#### If in multiplayer; On which server does this happen? 

#
#### What did you try to do, and what did you expect to happen?

#
#### What happened instead? (Attach screenshots if needed)

#

**Comment by Houstonruss** [comment] 2020-03-18 04:34
yes

**Comment by boubou19** [comment] 2020-03-18 07:35
@noobnoobnub can you be a bit more specific about the steps to reproduce this please?

**Comment by Prometheus0000** [comment] 2020-03-18 14:58
1) Have a block placer place down the limestone (chisel variant), use a redstone clock to get it to activate.
2) Have a Dynamism Tablet facing the limestone with a pickaxe in it, it'll mine the block (mine took ~2 sec each). This uses durability, but gains xp.
3) Most of the time it'll be limestone, but will sometimes be Fluorite Ore, both are picked up by the vacuum hopper and deposited in the chest.
4) A filter on the item conduit will send back only limestone to the block placer.

The process will repeat until you run out of limestone (if you aren't autocrafting it) or durability (unless it's indestructible). You could probably use a hammer to do nine at once too.

![2020-03-18_10 46 24](https://user-images.githubusercontent.com/8517039/76973186-fedef900-6905-11ea-9eca-7ef99c3bdb5e.png)

**Comment by draknyte1** [comment] 2020-03-18 16:29
Not intended behaviour at all. 
Please report to https://github.com/alkcorp/GTplusplus/issues

**Comment by 0lafe** [comment] 2020-03-18 21:08
Sadly I think hammers in tablets only mine one block for some reason :(

**Comment by Houstonruss** [comment] 2020-03-18 21:11
IIRC Flourite was supposed to have a drop chance from sandstone and higher chance from limestone.

**Comment by draknyte1** [comment] 2020-03-18 21:15
They’re intended explicitly to only drop from real players mining them, so thins like this wouldn’t work. (Looping inputs until it all becomes Fluorite via automation)

**Comment by Dream-Master** [comment] 2020-03-19 20:18
@draknyte1 is this fixable or should it be fixed in Thaumic Tinkerer?

**Comment by draknyte1** [comment] 2020-03-19 21:03
It’s just a minor oversight on my end I guess. No clue how TT is doing it, but I seem to recall I check explicitly for a real player. Will take a look tomorrow.

**Comment by Dream-Master** [comment] 2020-03-19 21:04
ok cool

**Comment by Prometheus0000** [comment] 2020-05-03 02:38
From Alk's changelog on 03/29/2020:
$ Fixed Thaumcraft based FakePlayer's triggering Fluorite drops.

So I guess it's fixed. Also tested on dev2, and it seems fixed.

**Closed** 2020-06-07 18:52 UTC
Labels: FixedInDev, GT++ Issue, bugMinor
