### ISSUE TITLE
There is a problem with the recipe for making navigation upgrades in Opencomputer

### ISSUE THREAD

**Issue by BarryBooder** [GTNewHorizons/GT-New-Horizons-Modpack#9270] opened 2021-12-24 16:47 UTC
### Your Pack Version

2114QF

### Your Server
Inconvenient to disclose

### Type of Server

Vanilla Forge

### Your Expectation

There is a problem with the recipe for making navigation upgrades in Opencomputer. The problems are as follows:
The navigation upgrade recipe requires the use of: "Map", NBT: "#0 358", and it must be this NBT, other NBTs will not work.

## Comparison chart of formula and actual situation:
![Snipaste_2021-12-25_00-43-23](https://user-images.githubusercontent.com/49380228/147365199-1d623fc0-b798-49e1-9924-8d9626aa5eef.png)

## formula:
![Snipaste_2021-12-25_00-43-34](https://user-images.githubusercontent.com/49380228/147365205-4a8df7ca-3b69-4509-88dd-11fbe800cbad.png)

##  actual situation（Can't work！！！）:
![Snipaste_2021-12-25_00-43-41](https://user-images.githubusercontent.com/49380228/147365209-4cf72aaa-a631-455f-b5bb-12ee2cd2355d.png)

### Your Proposal

I found the map with the map ID "#0 358" and it worked. I hope to modify the formula so that all map IDs can work.

### Final Checklist

- [x] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment] 2021-12-31 16:35
This recipe probably should just use empty map instead.

**Comment by Glease** [comment] 2021-12-31 16:37
This has been changed to use empty map already in 2.1.2.1.

**Comment by Glease** [comment] 2021-12-31 16:38
Duplicate of #8403

**Closed by Glease** 2021-12-31 16:37 UTC
Labels: Type: Recipe Change, Type: bugMinor
