### ISSUE TITLE
Gravitation suit quantum shield crashes server when hit by chaotic crystal explosion

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#13067] opened 2023-03-28 15:16 UTC
### Your Pack Version

2.3.0

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Actions

Broke a chaotic crystal while having the quantum shield from a gravitation suit enabled.

### Crash Report

[crash-2023-03-28_14.22.51-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11091043/crash-2023-03-28_14.22.51-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by ramseyspace** [comment] 2023-03-28 15:55
Confirmed, the issue. it does crash. I went to gaia boss with shield mode enabled. by cheating to give myself gravi suit because i was never able to enable shield. I never had this issue until gravi suit got reworked. which was like 2.2.10 iirc? I can enable this on SP world but not on MP for some reason. that might be triggering with servers mainly

**Comment by glowredman** [comment] 2023-05-03 19:22
Update before I forget it completely:
I managed to fix two out of three issues. The server no longer crashes and the shield FX now properly works. However the shield key doesn't work yet and I can't figure out why nor have I found a way to debug it properly. I'm going to do a PR with those two fixes now but unless I magically get a breaking idea this issue needs someone smarter to fix :(

**Comment by chochem** [comment] 2023-07-14 11:31
so this is all fixed now or is something missing?

**Comment by glowredman** [comment] 2023-07-14 11:46
Should be

**Closed** 2023-07-14 11:46 UTC
Labels: Status: FixedInDev, Type: Crash, Mod: Gravitation Suite Neo
