### ISSUE TITLE
Cutting machine recipe for AE2 cable anchors

### ISSUE THREAD

**Issue by NotAPenguin0** [GTNewHorizons/GT-New-Horizons-Modpack#11527] opened 2022-10-03 09:01 UTC
### Your GTNH Discord Username

NotAPenguin#5179

### Your Pack Version

2.1.2.0.pre-18

### Your Proposal

Add a cutting machine recipe for AE2 facades instead of just the iron ingot + knife recipe.

### Your Goal

It's annoying to use tools in crafts, especially later in the game when machines could easily do this for you.

### Your Vision

It makes sense in the context of the entire pack.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment] 2022-10-03 10:45
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9394.
you probably need to update to get the change.

**Closed** 2022-10-03 10:46 UTC
Labels: Type: Duplicate, Type: Suggestion, Status: Triage
