### ISSUE TITLE
Unable to sync quest between party mates

### ISSUE THREAD

**Issue by 905Sunny** [GTNewHorizons/GT-New-Horizons-Modpack#6639] opened 2020-09-17 02:03 UTC
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Eta
#
#### What did you try to do, and what did you expect to happen?
My friend joined the game, I invited him to my party. I expected his questbook to update and follow up to my progress
#
#### What happened instead? (Attach screenshots if needed)
nothing happened. His quest book didn't update and sync quest with me
#

**Comment by Prometheus0000** [comment] 2020-09-17 02:08
Did you ask on the discord first? This kind of thing comes up all the time.

**Comment by 905Sunny** [comment] 2020-09-17 02:46
I asked. But they don't seem to help...

**Comment by Prometheus0000** [comment] 2020-09-17 02:53
Try the search function on discord too. Or the BQ3 discord server, even though it's kinda dead there.

**Comment by shawnbyday** [comment] 2020-09-17 03:00
I don’t believe the quest book will sync to your current spot. They will have to catch up and then it should be good. I had same issue on a private server I run. Sort of intended behavior so you don’t get to tier 5 and invite new players so they can sync to tier 5. Pretty sure on officials the shared rewards are disabled too, however, on a private server you can configure that part.

**Comment by 905Sunny** [comment] 2020-09-17 03:01
catch up? there are a lot of crafting tasks

**Comment by DuskNite** [comment] 2020-09-17 03:27
There are certain types of tasks that dont auto sync. Checkbox tasks dont autosync afaik, and sometimes quests are gated behind them. Consume quests also dont auto sync. I'm not sure about crafting quests.

Just start doing quests a little and see what happens.

**Comment by yukieiji** [comment] 2020-09-17 04:10
duplicate of #3974

**Comment by Prometheus0000** [comment] 2020-09-17 04:16
That's about quest rewards, not about being able to sync progress.

**Comment by yukieiji** [comment] 2020-09-17 04:43
I'm sorry, my mistake.
According to this issue(#5399), BQ3 doesn't have a party feature.

**Comment by Dream-Master** [comment] 2020-09-17 05:00
it have but I never sit down and set if it will be a party reward or a reward per player. Or was this a different problem?

**Comment by Prometheus0000** [comment] 2020-09-17 05:11
They want their friend to 'catch up' in terms of quest progress to them just by being added to a party. But this can lead to abuse in the form of UHV players forming a party with others and then they get all the rewards (I assume).

If rewards were per party then it wouldn't matter, but I have no idea if it is or not, I only play SP.

@905Sunny Did you take a look at boubou's comments in #5399? Does that help you?

**Comment by Prometheus0000** [comment] 2020-09-18 03:10
![image](https://user-images.githubusercontent.com/8517039/93550779-30c72b80-f93a-11ea-9850-861fa5bc5ac6.png)

Expected behavior as expected then. But adding a note to a quest about party syncing if there isn't one already would be a good idea.

**Comment by Prometheus0000** [comment] 2020-09-18 03:17
Also apparently there's a command to copy quest progress?
![image](https://user-images.githubusercontent.com/8517039/93551448-e3e45480-f93b-11ea-8b96-bfa4a14f2b63.png)
Try that.

**Comment by Prometheus0000** [comment] 2020-09-20 23:13
Added note to quest. If we want to change the functionality or something, that can be brought up in another ticket.

**Closed** 2020-09-21 21:06 UTC
Labels: Betterquesting, FixedInDev, Quest change
