### ISSUE TITLE
Tectech Research Station power bug

### ISSUE THREAD

**Issue by Prometheus0000** [GTNewHorizons/GT-New-Horizons-Modpack#6236] opened 2020-06-10 21:44 UTC
#### Which modpack version are you using?
2.0.9.0 RC2
#
After sending computation from the QC and turning on the RS to research something, you can turn it (RS) off, and it won't consume power, but will still keep running and complete the research.
#
#### What do you suggest instead/what changes do you propose?
Make it cancel the research.

**Comment by Technus** [comment] 2020-06-11 10:49
i need the exact setup and recipe u run

**Comment by Dream-Master** [comment] 2020-06-11 10:53
@Prometheus0000

**Comment by Prometheus0000** [comment] 2020-06-11 12:39
![2020-06-11_08 27 18](https://user-images.githubusercontent.com/8517039/84385418-86fb3480-abbd-11ea-90f3-31b34e6c34b2.png)
![2020-06-11_08 27 23](https://user-images.githubusercontent.com/8517039/84385426-89f62500-abbd-11ea-88d6-8a57b4b26eb0.png)
![image](https://user-images.githubusercontent.com/8517039/84386052-a6df2800-abbe-11ea-933f-235dc6b78490.png)
![image](https://user-images.githubusercontent.com/8517039/84386078-b8283480-abbe-11ea-8405-90aa8e28ddf1.png)
![image](https://user-images.githubusercontent.com/8517039/84385993-8a42f000-abbe-11ea-97e0-9f0c18ec2b8d.png)
![image](https://user-images.githubusercontent.com/8517039/84386227-f3c2fe80-abbe-11ea-9622-f20675334637.png)

The QC has the same in all 4 CR. It has a 1 value for overclocking and overvoltage. It is using a UV 16A hatch, with the creative buffer sending UV at 16A.

The RS was researching UHV energy hatches with a UV energy hatch, with a data stick in the controller. It receives power from a creative source and a UV 4A hatch.

I have the appropriate maintenance issues fixed, and connected master to slave with optical hatches and cable (colored of course). Heat vents are not blocked on either.

After turning off the RS (I think I used a hammer), you can destroy the creative power source, and also see that the energy hatch power does not go down. 

Was that sufficient?

**Comment by chochem** [comment] 2020-06-13 10:43
I have similar issues. I am currently researching this recipe:
![2020-06-13_11 36 53](https://user-images.githubusercontent.com/40274384/84566632-b7340600-ad6a-11ea-956d-26c3caf8833c.png)
however, my RS only has a single 4A UV energy hatch, so it should not have enough power. It works though.

I think I might have found the cause though. The scanner says it **makes** energy instead of **using** it, so there probably is a sign wrong somewhere:
![2020-06-13_11 37 43 - Copy](https://user-images.githubusercontent.com/40274384/84566681-1560e900-ad6b-11ea-8b63-1d696d134549.png)

**Comment by Dream-Master** [comment] 2020-06-13 10:52
@Technus any idea ?

**Comment by Technus** [comment] 2020-06-14 05:36
Resolved in https://github.com/Technus/TecTech/commit/55d58b9812096f09a41a5298e74791d82509595b

**Comment by Dream-Master** [comment] 2020-06-14 06:28
will close after a nee release

**Closed** 2020-09-21 21:07 UTC
Labels: FixedInDev, TecTech
