### ISSUE TITLE
siftable oreDict Tag (like 1.12.2 CE)

### ISSUE THREAD

**Issue by MasterOfDevilLP** [GTNewHorizons/GT-New-Horizons-Modpack#18426] opened 2024-12-18 13:47 UTC
### Your GTNH Discord Username

masterofdevillp

### Your Pack Version

2.7.0

### Your Proposal

since you want to sift nearly all siftables it would be way easier to give siftable crushedPurified ores a siftable Tag like in 1.12.2 CE so you can write `siftable*` in the sifter and `!siftable*` in the macerator or thermal centrifuge

### Your Goal

better ore processing setup

### Your Vision

it just makes it better

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment] 2024-12-18 14:19
There is Recipe Filter blocks for this exact purpose

**Comment by GTNH-Afx237v7** [comment] 2024-12-19 07:05
Duplicate of #18266 (and various others)

**Closed** 2024-12-19 09:37 UTC
Labels: Suggestion, Status: Triage

**Comment by chochem** [comment] 2024-12-19 09:39
and the result was this addition https://github.com/GTNewHorizons/GT5-Unofficial/pull/870
