### ISSUE TITLE
Void Miner (moving to other dimension) bug

### ISSUE THREAD

**Issue by JustBenji** [GTNewHorizons/GT-New-Horizons-Modpack#12625] opened 2023-02-17 15:34 UTC
### Your GTNH Discord Username

Benji#0586

### Your Pack Version

2.2.2.0

### Your Server

ETA

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

Had void miners on different planets, picked them up, placed the on other planets and expect them to run without issue.

### The Reality

 They ran but gave no output in the output bus.

### Your Proposal

The bug is; Whenever you pickup a Void Miner, with a cover attached to it, it doesnt seem to reset all the other data in the background.
For this, if you move a void miner with a cover on it like (Machine cover), and place it in another dimension, it doesnt give any output. It will run, but no output.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment] 2023-02-17 15:37
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10205

**Closed by miozune** 2023-02-17 15:37 UTC
Labels: Type: bugMinor, Status: Triage
