### ISSUE TITLE
Irreversible crash damage occurred in the server archive when the Transformer Interface was connected to Chemical Inert Machine Casting

### ISSUE THREAD

**Issue by zeroCNM** [GTNewHorizons/GT-New-Horizons-Modpack#14049] opened 2023-07-24 17:11 UTC
### Your GTNH Discord Username

zero_CM

### Your Pack Version

2.3.3

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Actions

Hello, this is a player from China. I have discovered a bug in the server that can cause the server's archive to crash. If the Transformer Interface block of Thaumic Tinkerer is connected to Chemically Inert Machine Casting, it will cause the server's archive to crash instantly and be damaged to the point where it cannot be accessed, and it can only be processed through rollback. “ https://mclo.gs/GpZNERC ”And“ https://mclo.gs/cFCPKoA ”There are two crash reports for my server, which are generated by crashes that occur when two types of blocks are connected and dismantled. Please handle them.
PS:When we tried to reproduce the bug, we found that it only appeared on the server side.

### Crash Report

[crash-2023-07-24_14.30.01-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12148190/crash-2023-07-24_14.30.01-server.txt)
[crash-2023-07-24_14.59.37-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12148191/crash-2023-07-24_14.59.37-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment] 2023-07-28 05:14
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13291

**Closed by miozune** 2023-07-28 05:14 UTC
Labels: Type: Crash, Status: Triage
