### ISSUE TITLE
Make Stocking Input Bus (ME) configurable with NEI ghost items

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#11458] opened 2022-09-28 19:25 UTC
### Your GTNH Discord Username

Pandoro#4811

### Your Pack Version

delta

### Your Proposal

Like the title says
It would be really cool to be able to configure the input bus (ME) from NEI ghost items, wihout the need to search for single items in the ME, pick 1 etc...

### Your Goal

+

### Your Vision

+

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by PolkageistHS** [comment] 2022-09-28 20:59
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11137

**Closed** 2022-09-28 21:19 UTC
Labels: Type: Suggestion, Status: Triage
