### ISSUE TITLE
Brownstone blocks don't increase speed

### ISSUE THREAD

**Issue by oogabooga66** [GTNewHorizons/GT-New-Horizons-Modpack#7668] opened 2021-03-20 11:04 UTC
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
My own self hosted server.
#
#### What did you try to do, and what did you expect to happen?
I ran on paths made of brownstone cobblestone, brownstone and brownstone slabs and expected my speed to be increased.
#
#### What happened instead? (Attach screenshots if needed)
I did not go any faster. Another player on the server running beside me still moved at increased speed.
#
#### What do you suggest instead/what changes do you propose?
That speed is applied equally.
#
#### What is your GTNH Discord username?
ooga#0812

**Comment by Prometheus0000** [comment] 2021-03-20 12:16
Duplicate of #6427.

**Closed by Prometheus0000** 2021-03-20 12:16 UTC
Labels: Type: duplicate
