### ISSUE TITLE
CA mode in CALS can only do one recipe at a time 

### ISSUE THREAD

**Issue by AbdulazizA364** [GTNewHorizons/GT-New-Horizons-Modpack#15072] opened 2023-12-12 07:26 UTC
### Your GTNH Discord Username

_hwx

### Your Pack Version

2.5.0-beta-1

### Your Server

private server

### Java Version

Java 20

### Type of Server

Don't know

### Your Expectation

all the Recipes of the Circuit Assembler will work in CALS in circuit assembler mode

### The Reality

the CA mode can only do one recipe (Like imprints)
(like start using it to make IV circuit and it will only work to make IV circuits and if you want to make an LuV circuit you have to break and place the controller) 

### Your Proposal

make all the Recipes work

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by AbdulazizA364** [comment] 2023-12-12 10:31
I'm testing it in a creative world and it seems to work, but in my server it doesn't . need more testing

**Comment by AbdulazizA364** [comment] 2023-12-12 10:41
it seems to work fine in SP but in servers it's broken .
like the glass (managlass) that I use for the CALs, in SP it's tier is HV but in the server it's EV

**Comment by AbdulazizA364** [comment] 2023-12-12 10:55
I found the problem. the CA mode act like the CAL mode in terms of imprints. once you start a recipe in the CA mode it will only do that recipe until you break the controller and place it

**Comment by LewisSaber** [comment] 2023-12-12 11:19
Thanks narrowing issue, I will check it today

**Comment by LewisSaber** [comment] 2023-12-12 14:20
After Sitting with issue author in voice, we didnt manage to find the cause of issue and replicate it, issue also somehow fixed itself, im closing this for now, if someone has more info or steps how to replicate I will dig into it

**Closed** 2023-12-20 17:14 UTC
Labels: Type: bugMinor, Mod: BartWorks
