### ISSUE TITLE
Menu bug AGAIN

### ISSUE THREAD

**Issue by Kobeto** [GTNewHorizons/GT-New-Horizons-Modpack#16184] opened 2024-05-05 21:02 UTC
### Your GTNH Discord Username

Demonicat

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Expectation

I launched a brand new instance fully new on ATLauncher as well as MultiMC. I did not expect anything to go wrong

NOTE: When i used MultiMC I did:
1) a new instance completely new with 21.0.3 java
2) a new instance completely new with 21.0.2 java

For ATLauncher i just searched "GT" downloaded the modpack and tried running it, it worked but the menu bug persists.

### The Reality

Some menus are bugged and some items are not rendered, i have this problem using both MultiMC AND ATLauncher.

![2024-05-05_21 01 16](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/95346324/2f482e0e-9a6c-4712-8106-8c7fb7c6135a)
![2024-05-05_21 01 39](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/95346324/46bcd55b-c479-4c24-9af0-8b017b099b6c)
![2024-05-05_21 02 58](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/95346324/d3babbf6-21da-430c-b150-4efe1893dec5)
![2024-05-05_21 03 20](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/95346324/dc74f418-fa65-4ffb-95a7-c3d91461aca6)
![2024-05-05_21 04 08](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/95346324/0587f45f-fb9c-4b1a-ae08-20acb4428a04)
![2024-05-05_21 04 15](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/95346324/8b92d680-e939-4f96-9b31-41932037aa33)
![java and stuff](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/95346324/35af2684-5543-4ef4-b01b-aab8fc5c9897)

### Your Proposal

I tried using 2 launchers, both instances with java 21.0.2 and then 21.0.3, meaning i legit played like a new player with 0 new additions to the game or settings so i dont know whats wrong.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Kobeto** [comment] 2024-05-05 21:03
NOTE: The reason the title says "AGAIN" is because i thought i had made a previous bug report but it did not get sent, mb

**Comment by chochem** [comment] 2024-05-05 21:44
duplicate of https://github.com/GTNewHorizons/Angelica/issues/185 nad the others

**Closed by chochem** 2024-05-05 21:44 UTC
Labels: Type: bugMinor, Status: Triage
