### ISSUE TITLE
Infused Seeds praecantatio provokes a crash

### ISSUE THREAD

**Issue by Kriion** [GTNewHorizons/GT-New-Horizons-Modpack#14301] opened 2023-08-22 08:42 UTC
### Your GTNH Discord Username

Kriione[Kirill]#4672

### Your Pack Version

2.3.7

### Your Server

Zeta

### Java Version

Java 19

### Type of Server

Thermos

### Your Actions

Used Infused Seeds with the praecantatio aspect (6 vanilla thauma shards and a few others from related mods fall out) . At a certain point a strange shard dropped and crashed, after that I can't log in to the server. In all likelihood it went into my inventory.
In single player all repeated.
![image-5](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/142689341/f31f6bec-e676-49fb-bce0-e3940bcae375)

### Crash Report

[crash-2023-08-22_11.35.44-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12406752/crash-2023-08-22_11.35.44-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Kriion** [comment] 2023-08-23 18:33
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/142689341/136099ff-b0a4-4905-bbb2-acfc14988073)

This item, when placed in the world, causes a crash if moved or placed in inventory.

**Comment by Alastors** [comment] 2023-08-23 19:03
Extremely known issue, use the infused seeds at your own risk

**Comment by Alastors** [comment] 2023-08-23 19:03
We know what you were using them for though, :yobaFace:

**Comment by Alastors** [comment] 2023-08-23 19:09
Duplicate of: https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7893

**Closed by Alastors** 2023-08-23 19:09 UTC
Labels: Type: Crash, Status: Triage
