### ISSUE TITLE
The Enhanced Building Guide causes blocks such as chests to glow at a certain angle

### ISSUE THREAD

**Issue by Mobius0526** [GTNewHorizons/GT-New-Horizons-Modpack#14896] opened 2023-11-17 13:01 UTC
### Your Pack Version

2.4.1

### Your Server

SP

### Java Version

Java 17

### Type of Server

None

### Your Expectation

![2023-11-17_20 46 48](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/62875887/f6edc981-660d-45ed-9d20-a8930f9014dd)
![2023-11-17_20 46 50](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/62875887/169a3988-b32d-43f4-88ce-4e984e666a5d)

Remove extra added mods like Optifine and things won't get any better
The angle at which this change occurs changes every time you re-enter the game or refresh the screen (for example, adjusting a smooth lighting level).
It definitely has nothing to do with the settings, I've tried reinstalling gtnh
This may have something to do with a certain block I put down, which doesn't happen elsewhere, but at my base

### The Reality

Chest rendering error

### Your Proposal

Blocks such as chests glow at certain angles

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by bombcar** [comment] 2023-11-17 14:19
Blocks in the world can futz with rendering of other items. If you can figure out what block is causing it, it would help tremendously tracking it down. Maybe set chunk rendering distance super low and move the chest around to try to find which chunk it is in

**Comment by vovaksenov** [comment] 2023-11-17 14:35
Yes, try to focus "unusual" blocks. Like tanks with rendered fluids inside, items directly placed in-world or generally blocks that dont take up the full 16x16x16 block space.

**Comment by AdolMors** [comment] 2023-11-18 02:39
I do not believe the Enhanced Build Guide to be the only cause.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/47838758/fd0daeae-a103-4dea-a894-0608ac33b30f)
I noticed this effect appeared _as soon as_ our private server upgraded from 2.3.6 to 2.4.0. In regards to the building guide, it was never made in our world until a few days ago. Placing and then breaking does not resolve the problem here. It is likely that there are other causes.

**Comment by vovaksenov** [comment] 2023-11-18 02:45
In this case, too, please try to locate the culprit. It is in addition to my suggestion above, try also looking into if you have other openblocks blocks, since there is a chance of a similar glitch. Until you can locate what causes your issue, the name of this issue should stay as is i think.

**Comment by Mobius0526** [comment] 2023-11-18 11:25
> I do not believe the Enhanced Build Guide is the only cause. Rendering issues on gold and diamond chests can be seen in the following screenshot. ![image](https://user-images.githubusercontent.com/47838758/283967904-fd0daeae-a103-4dea-a894-0608ac33b30f.png) I noticed this effect appeared _as soon as_ our private server upgraded from 2.3.6 to 2.4.0. In regards to the building guide, it was never made in our world until a few days ago. Placing and then breaking the guide does not resolve the problem here. It is likely that there are other causes.

Yes, it appears after the version update
The mana pool has also been affected

**Comment by AdolMors** [comment] 2023-11-19 05:51
If you look at the chest next to the minimap, a player head is also affected, so not just chests.
I used dolly to pick up and put back the chests with rendering issues. That temporarily made the issues go away, but the symptoms returned after I went in and out of nether.

**Comment by Cardinalstars** [comment] 2023-11-20 01:48
Doing some more testing it shows that this only reproduces in main pack thus far. Just pulling OpenBlocks doesn't seem to cause it. This could be something to do with an optimization mod we have on.

**Comment by Cardinalstars** [comment] 2023-11-20 04:07
> I do not believe the Enhanced Build Guide is the only cause. Rendering issues on gold and diamond chests can be seen in the following screenshot. ![image](https://user-images.githubusercontent.com/47838758/283967904-fd0daeae-a103-4dea-a894-0608ac33b30f.png) I noticed this effect appeared _as soon as_ our private server upgraded from 2.3.6 to 2.4.0. In regards to the building guide, it was never made in our world until a few days ago. Placing and then breaking the guide does not resolve the problem here. It is likely that there are other causes.

Please try and find the block that is causing this one I'm quoting.

It seems to be different than a bug that is fixed in this PR (which is the original post): https://github.com/GTNewHorizons/OpenBlocks/pull/17

If anyone has more information on the transparency issues or if @AdolMors can provide a world download of some sort along with exact version and locations I could look to solve the other one.

**Closed** 2023-11-20 20:43 UTC
Labels: Type: bugMinor, Mod: OpenBlocks
