### ISSUE TITLE
departure from the server due to capsules

### ISSUE THREAD

**Issue by x-zenny** [GTNewHorizons/GT-New-Horizons-Modpack#14300] opened 2023-08-22 07:34 UTC
### Your GTNH Discord Username

zhenya288

### Your Pack Version

2.3.0.0

### Your Server

eta

### Java Version

Java 8

### Type of Server

Don't know

### Your Actions

I tried to take a capsule from greg tech xenon from the input hatch

### Crash Report

[crash-2023-08-22_02.48.18-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12406108/crash-2023-08-22_02.48.18-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment] 2023-08-22 13:52
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12170

**Closed by miozune** 2023-08-22 13:52 UTC
Labels: Type: Crash, Status: Triage
