### ISSUE TITLE
SmelteryRender -> ConcurrentModification

### ISSUE THREAD

**Issue by HenryLoenwind** [GTNewHorizons/GT-New-Horizons-Modpack#16678] opened 2024-07-05 02:33 UTC
### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

Doing other things while pouring stuff out of a Tinkers Smeltery with a redstone pulser.

```
Caused by: java.util.ConcurrentModificationException
    at tconstruct.smeltery.model.SmelteryRender.renderSmeltery(SmelteryRender.java:62)
```

Looking at the code it's quite obvious. The renderer iterates over a live list of the TE.

```java
for (FluidStack liquid : logic.moltenMetal) {
```

That list needs to be copied or otherwise wrapped.

### Crash Report

[crash-2024-07-05_04.15.17-client.txt](https://github.com/user-attachments/files/16104224/crash-2024-07-05_04.15.17-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Caedis** [comment] 2024-07-05 04:58
duplicate of https://github.com/GTNewHorizons/Angelica/issues/543

**Closed by Caedis** 2024-07-05 04:58 UTC
Labels: Type: Crash, Mod: Tinkers' Construct, Status: Triage
