### ISSUE TITLE
Updating world from older version to 2.6.1 causes issues with world corruption

### ISSUE THREAD

**Issue by Zalert** [GTNewHorizons/GT-New-Horizons-Modpack#16465] opened 2024-06-05 21:45 UTC
### Your GTNH Discord Username

zalert.

### Your Pack Version

2.5.x -> 2.6.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

after updating my game from 2.5.1 to 2.6.1, now my world always crashes after loading in for a split second.
https://pastebin.com/TTdKKdBR
here is the crash report^

Once crash occurs game can't load any worlds without restarting it.

I used mcedit to delete the chunk containing the coords mentioned at the top of the log:(1435, 35, 611)
deleting angelica didn't change anything.

using a backup of the world from 2.5.0, made 4 months ago results in the same crash https://mclo.gs/NK7YPOY

Of additional note. This world once had a chunk corruption issue in the coord noted above, a long time ago.
Deleting that chunk fixed the issue several versions back. And the world still works on 2.5.0 and 2.5.1, this issue only occurs again once I attempt to join these worlds in my 2.6.1 version.

### Crash Report

2.5.1 -> 2.6.1
https://pastebin.com/TTdKKdBR 

2.5.0 -> 2.6.1
https://mclo.gs/NK7YPOY

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2024-06-24 13:45
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16531

**Closed by chochem** 2024-06-24 13:45 UTC
Labels: Type: Crash, Status: Triage
