### ISSUE TITLE
Windows Defender Virus Detected in logisticspipes-1.7.10-0.9.4.5.4-GTNH.jar

### ISSUE THREAD

**Issue by RichardCritten** [GTNewHorizons/GT-New-Horizons-Modpack#10673] opened 2022-07-09 14:42 UTC
### Your Pack Version

2.1.2

### Your Server

SP

### Your Actions

Downloaded the MultiMC version of 2.1.2, imported into MultiMC  and launch.

Windows defender detected and quarantined the following

Detected: Trojan:AndroidOS/Multiverze
Status: Quarantined
Date: 09/07/2022 15:35

Affected items:
ile: C:\Data\Games\Minecraft\MultiMC\instances\GTNewHorizonsClient-1.7.10-2.1.2.3qf-MMC\.minecraft\mods\logisticspipes-1.7.10-0.9.4.5.4-GTNH.jar

### Crash Report

Game never got as far as a crash due to the Virus Scanner

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment] 2022-07-09 14:44
Duplicate of #10085

**Closed by miozune** 2022-07-09 14:44 UTC
Labels: Type: Crash, Status: Triage

**Comment by chochem** [comment] 2022-07-09 14:49
check out https://discord.com/channels/181078474394566657/252440750174765057/967842334484086794 for a fix

**Comment by boubou19** [comment] 2022-07-09 14:52
sadly, the fix we did no longer works, as the new LP version still gets flagged as a malware, see https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10602
