### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by Axiflare** [GTNewHorizons/GT-New-Horizons-Modpack#8432] opened 2021-08-21 05:12 UTC
#### Which modpack version are you using?
2.1.1.1

#
#### If in multiplayer; On which server does this happen? 
Private

#
#### What did you try to do, and what did you expect to happen?
This crash randomly happens. Can be while moving, while standing still, while tabbed out, while game is focused. This time I was walking around the base.

#
#### What happened instead? (Attach screenshots if needed)
Crashed

#
#### What is your GTNH Discord username?
Axiflare

If it helps, I had Fastcraft 1.25 and no Optifine at time of crash.

[crash.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/7024898/crash.txt)

**Comment by Glease** [comment] 2021-08-21 07:20
Duplicate of #7959. Though yeah, we sadly haven't work out a fix for this quite yet.

**Closed by Glease** 2021-08-21 07:20 UTC

**Comment by Glease** [comment] 2021-08-21 07:23
Duplicate of #7959. Though yeah, we sadly haven't work out a fix for this quite yet.
