### ISSUE TITLE
Waterline bugs when relogging

### ISSUE THREAD

**Issue by sudgy** [GTNewHorizons/GT-New-Horizons-Modpack#17730] opened 2024-10-23 00:35 UTC
### Your GTNH Discord Username

sudgy

### Your Pack Version

2.7.0 nightly 703/beta 3

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

When I set up the waterline (currently up to flocculation), it should not be affected by relogging, with the machines running like normal and nothing getting voided.

### The Reality

After logging in, the current waterline cycle finishes, but then the water purification plant turns off, and the ozonation purification unit and flocculation purification unit go into this weird state where they say they're running, the time taken in the controller gui is stuck at 120 seconds, and they don't output anything.  Starting the purification plant again voids everything the machines were making and starts everything over.  This is not just the machines failing to purify the water, since the flocculation waste liquid is completely voided, which is what made me realize something is going wrong.

One interesting thing that I noticed is that when starting the world, for a brief moment the water purification plant says it has an incomplete structure, but it stops saying that soon afterwards.  No idea if that's related.  It's in a single chunk.  However, the other machines are not in a single chunk, but all of their chunks are chunkloaded, which I've been told should stop any issues.  And given that all the waterline multis need to be close to the purification plant it seems very difficult to fit all the multis into chunk boundaries anyway.

Since I have nowhere better to say it, a note on my GTNH version: I found this bug on nightly 703, and before reporting it, I decided to try it on beta 3.  My world crashes the moment after logging in on beta 3, and I'm still trying to figure out exactly what is causing that crash.  However, I once was able to put off the crash long enough to verify that this issue still exists.  However, if there's any further testing that is needed, I would rather do it on the nightly since it doesn't crash every two seconds of playing.

### Your Proposal

The waterline should keep running like normal after logging in, or at the very least it shouldn't void everything and make me waste millions of chlorine.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FourIsTheNumber** [comment] 2024-10-23 01:23
Seems to be replicated by several others

**Comment by FourIsTheNumber** [comment] 2024-10-23 01:42
Oh, this is actually also duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17655
Will bump that up on the tracker

**Closed by FourIsTheNumber** 2024-10-23 01:42 UTC
Labels: Type: bugMinor, Status: Triage

**Comment by sudgy** [comment] 2024-10-23 02:03
Dang it I searched "waterline" and "water line" but not "water purification"
