### ISSUE TITLE
Rocket Launch Crash

### ISSUE THREAD

**Issue by RudyNahra** [GTNewHorizons/GT-New-Horizons-Modpack#11231] opened 2022-09-07 04:11 UTC
### Your GTNH Discord Username

pkpr#3546

### Your Pack Version

2.1.2.4-29dev

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Launch T3 Rocket. This occurred in (legacy) garden dim, and Europa. Got in rocket, press space bar, sound comes on, the counter counts down from 20 to 19, then the game freezes with 19 on the screen. Reopening the game resumes at 19, allowing me to launch rocket with no further issues. This happened two out of three times I tried to launch my rocket today.

### Crash Report

https://paste.ubuntu.com/p/xbNKkjdr52/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment] 2022-09-07 04:31
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10377

**Closed by miozune** 2022-09-07 04:31 UTC
Labels: Type: Crash, Status: Triage
