### ISSUE TITLE
Primitive Magneto Resonatic Circuit recipe missing

### ISSUE THREAD

**Issue by yukieiji** [GTNewHorizons/GT-New-Horizons-Modpack#7958] opened 2021-05-22 13:35 UTC
#### Which modpack version are you using?
v2.1.0.0 and v2.1.0.7a
#
#### If in multiplayer; On which server does this happen? 
single and multi
#
#### What did you try to do, and what did you expect to happen?
I was trying to craft an Primitive Magneto Resonatic Circuit.
#
#### What happened instead? (Attach screenshots if needed)
I need two Imprint supporting Board's, to craft it but I was able to craft it with just one. This is why I can't craft the Mgneto Resonatic Circuit after LV....
![2021-05-22_21 46 05](https://user-images.githubusercontent.com/40425798/119228427-ee4f9180-bb4d-11eb-9d2b-bb64f348301e.png)
![2021-05-22_21 46 12](https://user-images.githubusercontent.com/40425798/119228430-f0195500-bb4d-11eb-8b10-618175a23aa8.png)

#
#### What do you suggest instead/what changes do you propose?
Fix it.
#
#### What is your GTNH Discord username?
yukieiji

**Comment by Prometheus0000** [comment] 2021-05-22 14:04
Duplicate of #7770

**Closed by Prometheus0000** 2021-05-22 14:04 UTC
