### ISSUE TITLE
Duplication Glitch with Disassembler

### ISSUE THREAD

**Issue by jakepaschke** [GTNewHorizons/GT-New-Horizons-Modpack#10488] opened 2022-06-14 20:09 UTC
### Your GTNH Discord Username

Jakobus#6952

### Your Pack Version

2.1.2.3

### Your Server

Private Server with friends

### Type of Server

Don't know

### Your Expectation

I tried to disassemble HS Tracks from a villager. 

### The Reality

The disassemble worked, however, it gave back the same tracks along with the components to craft the tracks. Thus allowing an infinite amount of track materials to be farmed. The list of materials possible include: Stainless Steel, Osmium, Titanium, Tungsten Steel, Iridium, and Neutronium. All are available at HV tier, or lower (I tested with HV). 

### Your Proposal

Make it so disassembled tracks yield the materials used to craft them, and not return more tracks

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment] 2022-06-15 01:44
Duplicate of #10369

**Closed by miozune** 2022-06-15 01:44 UTC
Labels: Type: bugMinor, Status: Triage
