### ISSUE TITLE
Crashed with work table forestry

### ISSUE THREAD

**Issue by lobiita24** [GTNewHorizons/GT-New-Horizons-Modpack#7848] opened 2021-04-22 18:42 UTC
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
multiplayer
#
#### What did you try to do, and what did you expect to happen?
try to make a long iron rod on a frorestry work table and crash
#
#### What happened instead? (Attach screenshots if needed)
java.nullexpection
#
#### What do you suggest instead/what changes do you propose?
crash
#
#### What is your GTNH Discord username?
lobiita

**Comment by Prometheus0000** [comment] 2021-04-22 18:57
Where's the crashlog?

**Comment by lobiita24** [comment] 2021-04-22 19:24
![Uploading IMG_20210422_212122.jpg…]()

**Comment by lobiita24** [comment] 2021-04-22 19:25
![IMG_20210422_212137](https://user-images.githubusercontent.com/78134472/115773880-24fc8580-a3b1-11eb-8493-a741cd34788e.jpg)
![Uploading IMG_20210422_212200.jpg…]()

**Comment by lobiita24** [comment] 2021-04-22 19:25
i used telephon

**Comment by Prometheus0000** [comment] 2021-04-22 19:29
Looks like a duplicate of #7209.

**Closed by Prometheus0000** 2021-04-22 19:29 UTC
Labels: Type: Crash, Type: duplicate

**Comment by Prometheus0000** [comment] 2021-04-22 19:30
Also, please upload the crashlog file next time instead of a picture.

**Comment by lobiita24** [comment] 2021-04-22 20:23
sorry

**Comment by lobiita24** [comment] 2021-04-22 20:23
me ha pasado con dos items mas dispensador y carcaj

**Comment by Prometheus0000** [comment] 2021-04-22 20:24
Naw, it's cool. It can be hard to tell sometimes.

**Comment by lobiita24** [comment] 2021-04-22 20:28
tal vez deberias fixear la mesa o quitarla
