### ISSUE TITLE
Multi Smelter should accept Crafting Input Bus

### ISSUE THREAD

**Issue by Rexicon226** [GTNewHorizons/GT-New-Horizons-Modpack#14859] opened 2023-11-09 07:58 UTC
### Your GTNH Discord Username

telaxion

### Your Pack Version

2.4.0

### Your Proposal

There is no reason why the multi smelter shouldn't be able to accept input from the crafting input bus. It doesn't require any liquids, so the issue isn't partitioning. 

### Your Goal

Make it accept input from it.

### Your Vision

No need for ME chest subnet nonsense.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by vovaksenov** [comment] 2023-11-09 08:01
#14587 is very similar in essence

**Comment by miozune** [comment] 2023-11-09 08:13
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14587

**Closed by miozune** 2023-11-09 08:13 UTC
Labels: Type: Suggestion, Status: Triage
