### ISSUE TITLE
Add Auto-Slover for Quantum Computer

### ISSUE THREAD

**Issue by ramseyspace** [GTNewHorizons/GT-New-Horizons-Modpack#13282] opened 2023-04-22 23:14 UTC
### Your GTNH Discord Username

Ramsey#7916

### Your Pack Version

2.3.2

### Your Proposal

Have an automatic way to reslove quantum computer. I have Uncertainty Resolver X and still fails very frequently.

### Your Goal

Quantum computer stops computation when resolver goes uncertain. Thus messes up my research data and halt.

### Your Vision

This would be a huge benefit for people who have the extra resources and willing to pay extra resources for QOL. This would save a lot of time users having to check their computers are solved or not. Especially bigger ones fail a lot more.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment] 2023-04-22 23:16
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12213

**Closed by chochem** 2023-04-22 23:16 UTC
Labels: Type: Suggestion, Status: Triage
