### ISSUE TITLE
Certain Foils Lack a Bending Machine Recipe

### ISSUE THREAD

**Issue by SpaceMinere** [GTNewHorizons/GT-New-Horizons-Modpack#13499] opened 2023-05-14 03:39 UTC
### Your Pack Version

2.3.3

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Trying to craft certain foils (e.g. PTFE, PPS, aluminium) should have a bending machine recipe.

### The Reality

Certain foils (e.g. PTFE, PPS, aluminium) do not have bending machine recipes anymore. There was no mention of this change in the change-log so I'm assuming it is a bug. As it stands, these foils can only be produced in a crafting table with a hammer and are difficult to automate as a result.

### Your Proposal

Add these foil recipes back to the bending machine or add an alternative way to create them.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by TheEpicGamer274** [comment] 2023-05-14 03:40
I believe this has been fixed in later dev versions that are still in testing, 2.3.3 is more of a don't play version atm

**Comment by miozune** [comment] 2023-05-14 05:24
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13293

**Closed by miozune** 2023-05-14 05:24 UTC
Labels: Type: bugMinor, Status: Triage

**Comment by chochem** [comment] 2023-05-14 10:39
if you play on 2.3.3 you should at least update gt
https://github.com/GTNewHorizons/GT5-Unofficial/releases/tag/5.09.42.87
