### ISSUE TITLE
Nature's Compass not crafting

### ISSUE THREAD

**Issue by Radactivi** [GTNewHorizons/GT-New-Horizons-Modpack#12690] opened 2023-02-23 15:43 UTC
### Your GTNH Discord Username

Radactive#2660

### Your Pack Version

2.2.8

### Your Server

private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

I tried to craft the nature's compass in the basic assembly machine but it didnt work, i made sure that everything is correct which is, i got the sapling, log, compass and refined glue, it just wont do anything

### The Reality

nothing happened

### Your Proposal

it wont use any of the items and craft the natures compass

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2023-02-23 15:48
you need more items then NEI is showing. duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12193

**Closed by chochem** 2023-02-23 15:48 UTC
Labels: Type: bugMinor, Status: Triage
