### ISSUE TITLE
Menu Screen Tearing

### ISSUE THREAD

**Issue by jonbrownyeah** [GTNewHorizons/GT-New-Horizons-Modpack#16190] opened 2024-05-06 10:55 UTC
### Your Pack Version

2.6

### Your Server

SP

### Java Version

Java 20

### Type of Server

None

### Your Expectation

I've been playing 2.5.1 for a while now with no issues on MultiMC. I'm using my Intel GPU, Java 20, the required java arguments, and the neodymium-1.7.10 mod to resolve any screen issues in-game. I wanted to upgrade to 2.6, so I downloaded the latest 2.6 SP java 17-21 .jar file and installed a new instance in MultiMC. I used the same configs as my 2.5.1 instance (including adding the neodymium mod) while also adding the following java argument (-Djava.system.class.loader=com.gtnewhorizons.retrofuturabootstrap.RfbSystemClassLoader). 

### The Reality

There are no issues while playing the 2.6 game. I was able to create a new world and progress through a few quests without any screen issues. However, some menus have really bad screen tearing. It makes it so that I can't use these menus. Here are screenshots from my 2.5.1 instance and my 2.6 instance to show the difference in what I'm seeing. 

***2.5 Main Menu***
![2 5 Main Menu](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/137091573/989bcb69-f80f-4699-a935-bfde55dd8f63)

***2.5 Controls Menu***
![2 5 Controls](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/137091573/4063dd4b-a48b-4de8-ac09-98ff2c22f36d)

***2.5 Resource Packs***
![2 5 Resource Packs](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/137091573/26037ec8-9d9b-4667-bde9-795ffd264143)

***2.5 Video Settings***
![2 5 Video Settings](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/137091573/a61d9dc8-18b5-48fb-8410-b10c78cea3d2)

***2.6 Main Menu***
![2 6 Main Menu](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/137091573/3c0ecd98-fe8c-4de2-931b-98186e47cac5)

***2.6 Controls***
![2 6 Controls](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/137091573/dc97c0d5-8be9-46b2-a4a8-6a26d33a1be3)

***2.6 Resource Packs***
![2 6 Resource Packs](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/137091573/d22fd2fd-ca88-4bbd-809c-db54a795621d)

***2.6 Video Settings***
![2 6 Video Settings](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/137091573/875a04a4-5e6d-4c3f-b05e-4f9ec648f0b2)

### Your Proposal

It doesn't look like there is anything wrong with my PC setup, since I am able to use the 2.5.1 instance just fine. There must be something that was added in the 2.6 update that changed the way the menus are rendered (especially seeing that the video settings are displayed differently between 2.5.1 and 2.6). Any idea what to do here? 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lyfts** [comment] 2024-05-06 10:59
Duplicate of https://github.com/GTNewHorizons/Angelica/issues/185.

Update Angelica https://github.com/GTNewHorizons/Angelica/releases/tag/1.0.0-alpha44 or disable fontrenderer in Angelica config.

**Closed by Lyfts** 2024-05-06 10:59 UTC
Labels: Type: bugMinor, Status: Triage

**Comment by jonbrownyeah** [comment] 2024-05-06 11:06
Wow thank you so much for the quick response! I'm sorry I didn't realize this was a duplicate issue. Updating Angelica worked!
