### ISSUE TITLE
Oak drawer + hopper voids stuff

### ISSUE THREAD

**Issue by Szajkop** [GTNewHorizons/GT-New-Horizons-Modpack#10237] opened 2022-04-29 21:01 UTC
### Your GTNH Discord Username

szajkop

### Your Pack Version

2123qf

### Your Server

priv srv

### Your Expectation

I filled up an 1x2 oak drawer with sulphur and raw rubber dust to keep the chem reactor stacked for rubber producing.
The drawer connected with a hopper with 1 stack of raw dust, 1 stack of sulphur and 3x 1 piece of cobble

### The Reality

all the mats got voided with lightspeed (much higher than normal hopper speed) until the number of items came down to 1 stack each
![image](https://user-images.githubusercontent.com/7230430/166068483-fd4c7a48-67f3-4b9d-b64e-5aeb035c18b8.png)
![image](https://user-images.githubusercontent.com/7230430/166068780-3ee08dcb-16d4-4da1-9d5a-51ad6a1620bb.png)

After further testing i found ot that this bug only happens when i have the 3 single cobble items in the hopper. when i used 3 full stack the voiding is not happened.

### Your Proposal

fix pls

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment] 2022-04-30 19:48
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7778.

**Closed by Glease** 2022-04-30 19:48 UTC
Labels: Type: bugMinor, Status: Triage
