### ISSUE TITLE
The Spice of Life, AppleCore and open chest bug

### ISSUE THREAD

**Issue by Naiwed** [GTNewHorizons/GT-New-Horizons-Modpack#12396] opened 2023-01-26 21:21 UTC
### Your GTNH Discord Username

Naiwed#2324

### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Wanted to open the chest to put things

### The Reality

Some bug in The Spice of Life and Apple Core crashes my world to the home screen.(but when I open the backpack everything is fine, nothing crashes)

### Your Proposal

(?)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Naiwed** [comment] 2023-01-26 21:22
[crash-2023-01-26_22.12.25-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10513473/crash-2023-01-26_22.12.25-client.txt)

**Comment by Alexdoru** [comment] 2023-01-26 22:09
do you have another error in the log prior to the crash ?

**Comment by Naiwed** [comment] 2023-01-26 22:17
> do you have another error in the log prior to the crash ?

![image](https://user-images.githubusercontent.com/51828015/214963034-277f9104-fbc6-4255-8a17-94b332a6a8dd.png)
I only have the first text document with a different error, and all the rest are the same

**Comment by Naiwed** [comment] 2023-01-26 22:17
[crash-2023-01-25_14.04.11-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10513829/crash-2023-01-25_14.04.11-client.txt)

**Comment by miozune** [comment] 2023-02-05 05:34
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11645

**Closed by miozune** 2023-02-05 05:34 UTC
Labels: Type: bugMinor, Status: Triage
