### ISSUE TITLE
Slice of Life - Carrot Edition crashing game. Help!

### ISSUE THREAD

**Issue by LumiTH-Hedge** [GTNewHorizons/GT-New-Horizons-Modpack#12028] opened 2022-12-18 22:24 UTC
### Your GTNH Discord Username

Lumi#2140

### Your Pack Version

2.2.0.0

### Your Server

Private Server

### Type of Server

Don't know

### Your Actions

Just logging on a server, trying to move! So far, I've crashed 5 times consistently.

The game just says "Slice of Life - Carrot Edition, AppleCore" when checking what mods are causing the conflict.

### Crash Report

Pastebin: https://paste.ubuntu.com/p/jfQtJ9g6ws/

And the crash logs: 
[crash-2022-12-17_11.26.24-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10254757/crash-2022-12-17_11.26.24-client.txt)
[crash-2022-12-18_17.50.04-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10254758/crash-2022-12-18_17.50.04-client.txt)
[crash-2022-12-18_17.55.56-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10254759/crash-2022-12-18_17.55.56-client.txt)
[crash-2022-12-18_17.59.26-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10254760/crash-2022-12-18_17.59.26-client.txt)
[crash-2022-12-18_18.01.08-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10254761/crash-2022-12-18_18.01.08-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment] 2022-12-19 03:05
Closing as duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11645

**Closed by miozune** 2022-12-19 03:05 UTC
Labels: Type: Crash, Status: Triage
