### ISSUE TITLE
Lumber axe head can cut whole trees. is this intended?!

### ISSUE THREAD

**Issue by That1GitHubUser** [GTNewHorizons/GT-New-Horizons-Modpack#15870] opened 2024-03-29 19:58 UTC
### Your GTNH Discord Username

Aspect800

### Your Pack Version

2.5.1

### Your Server

Apoc Gaming

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

basically when you shift + right click with the lumber axe head, and select the chopping mode it cuts the whole tree, with just the HEAD of the lumber axe. 

### The Reality

I dont think this is intended so I'm reporting it here

### Your Proposal

Please fix this

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by That1GitHubUser** [comment] 2024-03-29 20:02
sorry, i didnt know how to add a label

**Comment by danRP408** [comment] 2024-08-06 02:27
yes

**Comment by Miklebe** [comment] 2024-10-23 09:21
> basically when you shift + right click with the lumber axe head, and select the chopping mode

is this even GTNH? No matter how much i right/left click with or without shift, i can't open anything, where i select the chopping mode. 
Also can't reproduce even in 2.5.1
![javaw_PQE8TaJ7Gb](https://github.com/user-attachments/assets/910d5fef-2e44-4a52-89f2-20dc92610a4a)

**Comment by BlueHero233** [comment] 2024-11-17 19:29
Closing this one because cant reproduce at all

**Closed by BlueHero233** 2024-11-17 19:29 UTC
Labels: Bug: Minor, Mod: Tinkers' Construct
