### ISSUE TITLE
no texture at Precise Auto Assembler

### ISSUE THREAD

**Issue by Ngar1** [GTNewHorizons/GT-New-Horizons-Modpack#16528] opened 2024-06-13 14:22 UTC
### Your GTNH Discord Username

Ngar

### Your Pack Version

2.7. Nightly - 455

### Your Server

Zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

after building PAA, block texture of controller and operational blocks apear in PAA colour

### The Reality

transparent blocks

![grafik](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/7759876/68894478-a5fa-4923-9865-2ec727e4ddee)

### Your Proposal

fix texture

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment] 2024-06-13 15:40
![Uploading image.png…]()
fixed in dev

**Comment by Quarri6343** [comment] 2024-06-14 22:34
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16413

**Closed by Quarri6343** 2024-06-14 22:34 UTC
Labels: Type: bugMinor, Status: FixedInDev, Status: Triage

**Comment by Quarri6343** [comment] 2024-06-14 22:35
@Dream-Master 
It is probably not fixed in dev. it just works fine in dev for some reason. See https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16413
