### ISSUE TITLE
Free items from computer cube

### ISSUE THREAD

**Issue by CallyKoh** [GTNewHorizons/GT-New-Horizons-Modpack#13601] opened 2023-06-02 22:25 UTC
### Your GTNH Discord Username

Calico#0637

### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

Placed a computer cube mark 2 to try and test the reactor simulator function, broke it to attempt to move it to a better place. 

### The Reality

When I broke it, the item that was being used to simulate (in this case, a neutron reflector) was dropped alongside the computer cube, despite not actually being given one. This makes it a way to practically select which free nuclear item you want.

### Your Proposal

It should definitely not do that?

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment] 2023-06-03 03:42
Duplicate of #12849

**Closed by miozune** 2023-06-03 03:42 UTC
Labels: Type: bugMinor, Type: Exploit
