### ISSUE TITLE
Increase qft catalyst limit

### ISSUE THREAD

**Issue by meepmopper** [GTNewHorizons/GT-New-Horizons-Modpack#14097] opened 2023-07-29 07:26 UTC
### Your Pack Version

2.3.4

### Your Proposal

Increase or uncap the qft parallel limit.

### Your Goal

Reduce the amount of qfts needed. Poor worgy borgy had to place multiple for mutated solder.

### Your Vision

More parallels = happier players

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by minecraft7771** [comment] 2023-07-29 07:28
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14055

**Closed by minecraft7771** 2023-07-29 07:28 UTC
Labels: Type: Suggestion, Status: Triage
