### ISSUE TITLE
H2SO4 duping

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#13671] opened 2023-06-12 05:22 UTC
### Your GTNH Discord Username

LEO_PREMIUM#3437

### Your Pack Version

2.3.4

### Your Server

zeta

### Java Version

Java 8

### Type of Server

None

### Your Expectation

no dupes

### The Reality

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/9d4ca15e-1438-4014-a50e-47e48a79fbed)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/49871378/b23861b6-e443-4d6c-973c-3a68f02d5120)

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment] 2023-06-12 05:51
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13667

**Closed by miozune** 2023-06-12 05:51 UTC
Labels: Type: bugMinor, Status: Triage
