### ISSUE TITLE
Wrong journey map ore notation

### ISSUE THREAD

**Issue by Catalyst2100** [GTNewHorizons/GT-New-Horizons-Modpack#18523] opened 2024-12-26 14:23 UTC
### Your Pack Version

2.7.1

### Your Server

SP single player

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Working good

### The Reality

After I move my saves visualprospecting, and journeymap, TCNodeTracker file from 2.7.0 java8 to 2.7.1 java8, the visualprospecting working wrong. That I am in The Twilight Forest, I see the other word ore, and then I attempt to move into 2.7.1 mmc java17 without visualprospecting folder. It worked good when I first play and when I play it the second time it went wrong again.

![image](https://github.com/user-attachments/assets/6c2e3d6b-0516-4587-abe9-0831821faa41)
![image](https://github.com/user-attachments/assets/d3039403-bf40-4c0d-ace3-e7fec2b8290d)

### Your Proposal

Working good

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Dream-Master** [comment] 2024-12-26 14:37
wasent this fixed ?

**Comment by Catalyst2100** [comment] 2024-12-26 14:47
> wasent this fixed ?

I have changed my game version and delete my visualprospecting folder, rescan the map by MV prospector，and it looks all right but after I restart the game it changed

**Comment by Catalyst2100** [comment] 2024-12-26 14:50
Additonally, my game path does not contains non-ASCII character.
![image](https://github.com/user-attachments/assets/73954894-c81a-4c79-9f9f-f5f3c990ff49)

**Comment by Dream-Master** [comment] 2024-12-26 14:51
> > wasent this fixed ?
> 
> I have changed my game version and delete my visualprospecting folder, rescan the map by MV prospector，and it looks all right but after I restart the game it changed

change back to wrong ores ?

**Comment by Catalyst2100** [comment] 2024-12-26 14:52
> > > wasent this fixed ?
> > 
> > 
> > I have changed my game version and delete my visualprospecting folder, rescan the map by MV prospector，and it looks all right but after I restart the game it changed
> 
> change back to wrong ores ?

Yes, and the (this version 2.7.1 Java17 MMC) wrong ores seems to be different to (version 2.7.1 java8 other game luncher)

**Comment by Catalyst2100** [comment] 2024-12-26 15:04
And in DIM0 main world it looks like Phobos?
![image](https://github.com/user-attachments/assets/f56cf2f6-f3a8-4046-a4df-aa330349ed87)
![image](https://github.com/user-attachments/assets/941f23d9-9a2b-476d-a3da-09d4fd9e5222)

**Comment by Lyfts** [comment] 2024-12-26 15:14
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18058, same solution applies here.

Also fixed for future versions by https://github.com/GTNewHorizons/VisualProspecting/pull/62

**Closed by Lyfts** 2024-12-26 15:14 UTC
Labels: Bug: Minor, Status: Triage
