### ISSUE TITLE
Bug when trying to open the TC node tracker on Journeymap

### ISSUE THREAD

**Issue by Brunnosh** [GTNewHorizons/GT-New-Horizons-Modpack#17462] opened 2024-09-25 21:56 UTC
### Your GTNH Discord Username

Brunosh

### Your Pack Version

2.7.0-beta1

### Your Server

Private MP

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Wanted to see my discovered TC nodes to refill my wand

### The Reality

When i click the TC node tracker button, Journeymap completely panics and stops working completely with an error message on chat
https://prnt.sc/RCm0bQ8e7Loh
It happens both with the fairplay and unlimited versions of journeymap

### Your Proposal

want refill wand, want know where node at, journeymap kaput, me sad :(

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ethryan** [comment] 2024-09-25 22:16
duplicate of #17420

**Closed by Ethryan** 2024-09-25 22:16 UTC
Labels: Type: bugMinor, Status: Triage
