### ISSUE TITLE
Fluid Regulator Covers reset to Export upon reloading the world

### ISSUE THREAD

**Issue by jonanlsh** [GTNewHorizons/GT-New-Horizons-Modpack#9770] opened 2022-02-18 17:09 UTC
### Your GTNH Discord Username

jonanlsh#2693

### Your Pack Version

2.1.2.2QF2

### Your Server

SP

### Your Expectation

I set my fluid regulators to import, to control plasma flow rates for my turbines.

### The Reality

Upon reloading the world, the fluid regulators covers reset to export status, preventing my plasma turbines from operating.

### Your Proposal

Have the fluid regulator covers remember their previous state upon shutdown.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment] 2022-02-19 06:54
Duplicate of #9593

**Closed by Glease** 2022-02-19 06:54 UTC
Labels: Type: Duplicate, Type: bugMinor
