### ISSUE TITLE
Left/Right Click broken on some NEI pages

### ISSUE THREAD

**Issue by chochem** [GTNewHorizons/GT-New-Horizons-Modpack#13994] opened 2023-07-19 19:02 UTC
### Your GTNH Discord Username

chochem

### Your Pack Version

nightly from 19 July

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

left click works like R, right click like U. (works in 2.3.4 and anything prior)

### The Reality

they dont do that anymore on nei custom diagram pages. e.g. the materials overview or the ore proc overview.

left/right click still works correctly on other pages like any of the specific gt machine processing pages.

### Your Proposal

fix it. :)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by wlhlm** [comment] 2023-07-19 19:55
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13954

**Closed by wlhlm** 2023-07-19 19:55 UTC
Labels: Type: bugMinor, Mod: NEI
