### ISSUE TITLE
getting "Any IV Circuit" by disassembling IV machines

### ISSUE THREAD

**Issue by NoX-programer** [GTNewHorizons/GT-New-Horizons-Modpack#10734] opened 2022-07-17 06:15 UTC
### Your GTNH Discord Username

NoXъ # 0667

### Your Pack Version

2.1.2.4-18-pre

### Your Server

private, also SP

### Type of Server

Vanilla Forge

### Your Expectation

Maybe, it must be some usual circuits, but...

### The Reality

In v.2.1.2.3qf, and also 2.1.2.4-18-pre, I get "Any IV Circuit" (from GT: New Horizons mod) after throwing IV machines to disassembler. That "Any IV Circuit" isn't craftable by normal way, but it can be used in recipes well. Checked pre-IV machines - I got usual circuits in the disassembler.

### Your Proposal

If this behavior is not intended, fix please.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment] 2022-07-17 06:17
Duplicate of #10173

**Closed by miozune** 2022-07-17 06:17 UTC
Labels: Type: bugMinor, Status: Triage
