### ISSUE TITLE
After upgrading from beta2 to beta3, the UI does not display properly

### ISSUE THREAD

**Issue by CC-3301** [GTNewHorizons/GT-New-Horizons-Modpack#17778] opened 2024-10-27 12:27 UTC
### Your Pack Version

2.7.0-beta-3

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

UI displays normally

### The Reality

2.7.0-beta-2
![image](https://github.com/user-attachments/assets/25d3f347-76d5-4a62-bda0-d72858b9937d)
![image](https://github.com/user-attachments/assets/2bd937a6-5917-4d36-8ce9-b125a849fb1f)

2.7.0-beta-3
![image](https://github.com/user-attachments/assets/8af015b6-6d59-4afe-8abf-f8ee12a91864)
![image](https://github.com/user-attachments/assets/109d9c9c-8d64-4848-983b-7c5a15936ec7)

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lyfts** [comment] 2024-10-27 12:32
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17772

**Closed by Lyfts** 2024-10-27 12:32 UTC
Labels: Type: bugMinor, Status: Triage

**Comment by CC-3301** [comment] 2024-10-27 13:04
![image](https://github.com/user-attachments/assets/827a1935-1cb9-4bd9-b70d-af4eb452f2af)
