### ISSUE TITLE
Hot Titanium Ingot can't be searched in NEI but exists

### ISSUE THREAD

**Issue by TimeConqueror** [GTNewHorizons/GT-New-Horizons-Modpack#8464] opened 2021-08-28 08:28 UTC
### Your GTNH Discord Username

TimeConqueror#0001

### Your Pack Version

2.1.1.2-DEV

### Your Server

private one

### Type of Server

Thermos

### Your Expectation

Expected to see Hot Titanium Ingot in NEI

### The Reality

It can't be searched in NEI

### Your Proposal

Make this item be visible

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by TimeConqueror** [comment] 2021-08-28 12:40
The same for Hot Tungstensteel Ingot

**Comment by Dream-Master** [comment] 2021-08-28 12:51
If all displayed in nei the loading time will be increasing i guess.

**Comment by Prometheus0000** [comment] 2021-08-28 15:45
We don't need these items visible do we? Same for all the partial ore processed stuff. There might be a config setting though, and if not, feel free to add one.

It might be useful for the ones with weird processing though I guess? Is that what you mean?

**Comment by Glease** [comment] 2021-08-28 19:22
Hot ingots are not showed by design, to decrease clutter in NEI. I second Prometheus on this one:
> There might be a config setting though, and if not, feel free to add one.

**Comment by socolio** [comment] 2021-08-28 19:40
It looks like very strange design decision. Game has very few hot ingots. It is very impractical to remove them from the NEI when there are a huge number of other things that are not even used.

If you need an example when ingots are needed in NEI then here it is. If I want to see the characteristics of EBF required for titanium smelting, the first thing I would do is click on the Hot Titanium to see recipes in NEI. But there is no Hot Titanium in NEI, but some other very useful cool staff like 6 types of Volumetric Flask with Inconel792 i can find in NEI.

How about to return all hot ingots to the NEI?

**Comment by Prometheus0000** [comment] 2021-08-28 22:41
Honestly it'd be better to hide stuff like double and so on ingots and plates, so long as a quest explains they exist. They're so rarely used outside of rocket stuff. Well, sometimes double plates are used, but the triple, quad and quint (I think it goes that high?) aren't really.

> Game has very few hot ingots.
How about to return all hot ingots to the NEI?

? All the ingots past a certain temp are hot. So most of them are hot. And they're _already_ removed? Also, just look at titanium ingot, then hot titanium ingot, it's just one more step.

**Comment by bombcar** [comment] 2021-08-28 22:58
Yeah usually I search the ingot click it click the hot click the dust to figure out what I am looking for. 

Removing the billions of pages of tinkers tools and cells would be fine by me but I kind of like hots

**Comment by Prometheus0000** [comment] 2021-09-26 14:15
I think this can be closed with the new material page that makes this unnecessary?

**Comment by bombcar** [comment] 2021-10-01 02:34
The mentioned issue points out another side effect - finding something to put into a filter which you can do from NEI but not if the hot ingot is hidden.

**Comment by Prometheus0000** [comment] 2021-10-01 07:31
I'm not sure what you mean but this _particular issue_ is done.

**Closed by Prometheus0000** 2021-10-01 07:31 UTC
Labels: Type: bugMinor, Mod: NEI
