### ISSUE TITLE
HHE EnderGoo does not return buckets when used in super tank 

### ISSUE THREAD

**Issue by basdxz** [GTNewHorizons/GT-New-Horizons-Modpack#7490] opened 2021-02-17 06:38 UTC
As title.
Make it return bucket when dumped into Super tank and make it work with cells

cheers fam

**Comment by GTNH-Afx237v7** [comment] 2021-02-17 06:46
Some more info would be helpful.
What pack version are you using?
Did you notice that buckets disappear when using other tanks as well?
What is meant by "making it work with cells" - being able to fill a cell with HEE Ender Goo from an already filled tank, I assume?

**Comment by Prometheus0000** [comment] 2021-02-17 06:48
Duplicate of #5234

**Closed by Prometheus0000** 2021-02-17 06:48 UTC
Labels: Type: duplicate
