### ISSUE TITLE
[SFM] sfm can't use a seaweedbroth liquid filter

### ISSUE THREAD

**Issue by MotiasF33** [GTNewHorizons/GT-New-Horizons-Modpack#6604] opened 2020-09-12 15:49 UTC
#### Which modpack version are you using?
2.0.9.0qf4

### Seaweedbroth need for bioware proccesing and for maximum efficiency the Output hatch Batcterial wat always half empted
![изображение](https://user-images.githubusercontent.com/47714084/92999195-ccfec600-f527-11ea-935d-2c83feaee03e.png)
### Liquid filter seaweedbroth changes when you out sfm 
![изображение](https://user-images.githubusercontent.com/47714084/92999251-151de880-f528-11ea-85a3-921ce134b20d.png)

**Comment by Prometheus0000** [comment] 2020-09-12 20:07
Bart's fluids don't work with SFM, complain to bart.

**Comment by MotiasF33** [comment] 2020-09-12 20:34
> 
> 
> Bart's fluids don't work with SFM, complain to bart.

strange..bacteria and row growth medium can be using as filter
![изображение](https://user-images.githubusercontent.com/47714084/93004528-75c11b80-f550-11ea-8233-1edc9d6e1e05.png)

**Comment by Prometheus0000** [comment] 2020-09-12 20:36
I'm just saying what I heard. And I know that since fluids (most of them) will change if you bookmark them in NEI and close MC and open it again, that might happen too.

**Comment by MotiasF33** [comment] 2020-09-12 20:39
> 
> 
> I'm just saying what I heard. And I know that since fluids (most of them) will change if you bookmark them in NEI and close MC and open it again, that might happen too.

Got it. Thank :*

**Comment by Dream-Master** [comment] 2020-09-12 22:18
@bartimaeusnek can this be fixed ?

**Comment by Prometheus0000** [comment] 2020-11-11 17:58
Duplicate of #5646.

**Closed by Prometheus0000** 2020-11-11 17:58 UTC
Labels: Mod: BartWorks, Type: duplicate
