### ISSUE TITLE
use_machine_metal_tint=false no longer works

### ISSUE THREAD

**Issue by Jimbno** [GTNewHorizons/GT-New-Horizons-Modpack#9970] opened 2022-03-16 09:31 UTC
### Your GTNH Discord Username

Jimbno

### Your Pack Version

2.1.2.3QF

### Your Server

2.1.2.3QF

### Type of Server

Single Player

### Your Expectation

I changed I changed use_machine_metal_tint=false expecting it to remove the tint

### The Reality

This config no longer works

### Your Proposal

Remedy the config

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment] 2022-06-25 06:38
Duplicate of 9599

**Closed by Glease** 2022-06-25 06:38 UTC
Labels: Type: bugMinor, Status: Triage
