### ISSUE TITLE
Water purification MB's are not functioning properly after game restart.

### ISSUE THREAD

**Issue by RS-23-T** [GTNewHorizons/GT-New-Horizons-Modpack#17655] opened 2024-10-17 00:55 UTC
### Your GTNH Discord Username

rizakrko

### Your Pack Version

nightly 700

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

After game restart the water purification MB's should continue the cycle as if no restart happened.

### The Reality

Water purification units processing is stopped at 120s mark without shutting down the units, controller unit is shutting down after 120s. Trying to start the controller unit voids the output of the previous cycle.
I've tried to break and relink all the units, but it did not help.
Something that might be related was fixed in this PR https://github.com/GTNewHorizons/GT5-Unofficial/pull/3369 , but it did not help (nightly 700 contains this change).
Video: https://imgur.com/a/s7LR01d

### Your Proposal

At least the output of the previous cycle should not be voided since it becomes a hassle to supply new materials for the closed loop at T3 after each restart.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by VinDevGH** [comment] 2024-10-25 05:13
So, I have made some observations that may lead to the root cause.

From my testing with just the clarifier and the plant, the issue didn't seem 100% consistent, sometimes when I restarted it would keep running fine. Another thing I noticed was that it didn't seem to happen at all when in debug mode. And a final thing that I think narrows it down quite a bit it when the issue occurs, the below error get's logged.

`[23:47:52] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: java.lang.NullPointerException: Cannot read field "mChances" because "this.currentRecipe" is null
[23:47:52] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//gregtech.common.tileentities.machines.multi.purification.MTEPurificationUnitBase.addRecipeOutputs(MTEPurificationUnitBase.java:401)
[23:47:52] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//gregtech.common.tileentities.machines.multi.purification.MTEPurificationUnitBase.endCycle(MTEPurificationUnitBase.java:427)
[23:47:52] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//gregtech.common.tileentities.machines.multi.purification.MTEPurificationPlant.endCycle(MTEPurificationPlant.java:461)
[23:47:52] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//gregtech.common.tileentities.machines.multi.purification.MTEPurificationPlant.updateCycleProgress(MTEPurificationPlant.java:406)
[23:47:52] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//gregtech.common.tileentities.machines.multi.purification.MTEPurificationPlant.runMachine(MTEPurificationPlant.java:377)
[23:47:52] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//gregtech.api.metatileentity.implementations.MTEMultiBlockBase.onPostTick(MTEMultiBlockBase.java:472)
[23:47:52] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//gregtech.common.tileentities.machines.multi.purification.MTEPurificationPlant.onPostTick(MTEPurificationPlant.java:354)
[23:47:52] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:568)
[23:47:52] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//net.minecraft.world.World.func_72939_s(World.java:1939)
[23:47:52] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[23:47:52] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[23:47:52] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[23:47:52] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
[23:47:52] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[23:47:52] [Server thread/INFO] [STDERR/]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)`


This leads me to believe that on reloading the game currentRecipe is being lost and that the issue only occurs after a reload AND a successful craft because addRecipeOutputs is only called when not in debug mode and the craft roll was successful. I think currentRecipe being null causes the endCycle function to fail causing the purification unit gets stuck and breaking the cycle loop.

Hopefully this helps. I'm not sure what a proper solution would be.

**Comment by NotAPenguin0** [comment] 2024-10-27 06:50
@RS-23-T This should have been fixed in the linked PR by @VinDevGH. Please reopen this if you still have this problem in newer releases.

**Closed** 2024-10-27 06:50 UTC
Labels: Type: bugMinor, Mod: GT

**Comment by RS-23-T** [comment] 2024-10-27 10:55
@NotAPenguin0 Nightly 710 + https://github.com/GTNewHorizons/GT5-Unofficial/pull/3420 fixed this issue. Thank you @VinDevGH !
