### ISSUE TITLE
UEV transformer not working

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#5125] opened 2019-11-30 20:54 UTC
#### Which modpack version are you using?
2.0.8.0a
#
#### If in multiplayer; On which server does this happen? 
SSP
#
#### What did you try to do, and what did you expect to happen?
tried to upvolt UHV to UEV
#
#### What happened instead? (Attach screenshots if needed)
it does not output the uev 
#
#### What do you suggest instead/what changes do you propose?
fix so it can output UEV

**Comment by Dream-Master** [comment] 2019-12-01 00:49
The GT one ? @botn365 can you add a picture here ?

**Comment by boubou19** [comment] 2019-12-01 21:43
possible duplicate of #4135

**Closed** 2020-10-10 12:27 UTC
Labels: Type: bugMinor, Type: duplicate
