### ISSUE TITLE
Missing recepie or conversion for TiCo Mannylin nuggets

### ISSUE THREAD

**Issue by monroth** [GTNewHorizons/GT-New-Horizons-Modpack#13200] opened 2023-04-12 15:17 UTC
### Your GTNH Discord Username

monroth#4236

### Your Pack Version

2.3.0

### Your Server

private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Tried to put TiCo manyullyn nuggets that I get from bees or from transmutation into alloy smelter to get mannylin ingot. Wanted to get ingot.

### The Reality

Nothing happened. No recepie that use TiCo manyullyn nuggets, and they don't autoconvert (like thaumcraft nuggets) into GT manyullyn nuggets.

### Your Proposal

Make them autoconvert or add alloy smelter recepies.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Runakai1** [comment] 2023-04-12 15:34
Tcon nuggets are going to be replaced by GT counterpart in bee related resource gathering

**Comment by monroth** [comment] 2023-04-18 14:06
they need to be replaced in transmutation too

**Comment by chochem** [comment] 2023-04-20 14:30
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10842

**Closed by chochem** 2023-04-20 14:30 UTC
Labels: Type: bugMinor, Status: Triage
