### ISSUE TITLE
Witchery's oven crash (trying to smelt wrong items)

### ISSUE THREAD

**Issue by inklesspen1scripter** [GTNewHorizons/GT-New-Horizons-Modpack#7764] opened 2021-04-05 20:40 UTC
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
My own. I'm using UltraMine core but I don't think it's has meaning
#
#### What did you try to do, and what did you expect to happen?
Tried to place non-smelting items in witchery's oven
Excepted denied placing  item in the slot to smelt items
#
#### What happened instead? (Attach screenshots if needed)
Server crash
#
#### What do you suggest instead/what changes do you propose?
Open sourcecode of witchery and fix that.
If u think it's not your fault u can ignore this problem. I'll send crash-report to witchery's devs also
#
#### What is your GTNH Discord username?
inklesspen#1345
I don't know have I joined the server

Crash report:
[crash-2021-04-05_20.33.06-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/6260561/crash-2021-04-05_20.33.06-server.txt)

**Comment by inklesspen1scripter** [comment] 2021-04-05 20:42
Oke I can't find witchery's github 
Also the witchery's author is inactive on curseforge so I can't contact him
I'm posting the crash report here only

**Comment by Skiftcha** [comment] 2021-04-05 20:43
try WitcheryExtras-1.1.2.jar
http://jenkins.usrv.eu:8080/job/Witchery-Extras/
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7154

**Comment by boubou19** [comment] 2021-04-05 22:16
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/7183.

**Closed by boubou19** 2021-04-05 22:16 UTC
