### ISSUE TITLE
Singleplayer Game Crashes Upon Loading

### ISSUE THREAD

**Issue by TekkitAshley** [GTNewHorizons/GT-New-Horizons-Modpack#18481] opened 2024-12-22 18:37 UTC
### Your GTNH Discord Username

TekkitAsh

### Your Pack Version

Gregtech NH 2.7.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

Trying to load up my single player world, which i only started less than an hour ago and i get kicked out before i even get in-game and i get greeted with this message - https://gyazo.com/ed477bf3a508bb44d4471beff8fb7e88

Ive attached my crash log below in Crash Report

### Crash Report

[2024-12-22-2.log](https://github.com/user-attachments/files/18222910/2024-12-22-2.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2024-12-23 09:46
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18239

**Closed by chochem** 2024-12-23 09:46 UTC
Labels: Crash, Status: Triage
