### ISSUE TITLE
Game crash - The spice of life

### ISSUE THREAD

**Issue by IGNxlol** [GTNewHorizons/GT-New-Horizons-Modpack#16237] opened 2024-05-11 15:54 UTC
### Your GTNH Discord Username

jojoeeee

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

I was farming a hay statue and i was going to drop some zombie meat and as soon as i go to click (just hovering with mouse), my game crashes and it says the problem im having is with the mod pack spice of life

### Crash Report

[crash-2024-05-11_11.36.19-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15283337/crash-2024-05-11_11.36.19-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by IGNxlol** [comment] 2024-05-11 16:59
not having this issue anymore. I reset my pc and everything is working

**Comment by Quarri6343** [comment] 2024-05-11 23:53
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14471

**Closed by Quarri6343** 2024-05-11 23:53 UTC
Labels: Type: Crash, Status: Triage
