### ISSUE TITLE
Tiny/Small Pile of Gypsum dust will consume Schematic in a Packager

### ISSUE THREAD

**Issue by Judisch** [GTNewHorizons/GT-New-Horizons-Modpack#8294] opened 2021-07-26 21:54 UTC
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
Private server
#
#### What did you try to do, and what did you expect to happen?
I put 9 `Tiny Pile of Gypsum Dust` into a Packager, along with the Dust schematic. 
I expected the machine to make 1 `Gypsum Dust` item, and not consume the schematic. 
#
#### What happened instead? (Attach screenshots if needed)
The dust schematic is consumed

**Comment by boubou19** [comment] 2021-07-26 22:00
duplicate of #8277, #8130 and #8100. Thanks for the report, but please next time use the search bar to look for similar issues.

**Closed by boubou19** 2021-07-26 22:00 UTC
Labels: Type: duplicate

**Comment by Judisch** [comment] 2021-07-27 17:16
My bad, I was only looking at Open issues and not Closed ones
