### ISSUE TITLE
GTNEIOrePlugin recipes not working issue

### ISSUE THREAD

**Issue by D4shwood** [GTNewHorizons/GT-New-Horizons-Modpack#11932] opened 2022-12-06 13:36 UTC
### Your GTNH Discord Username

Marwood#0383

### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Being able to use GTNEIOrePlugin recipes.

### The Reality

When I try to use the ore vein recipe I get this error on the chat.
![205795474-1d812c35-a5a7-4d60-939b-d5cbbdeb5df9](https://user-images.githubusercontent.com/31806544/205926291-f6b96766-bd18-44e6-9837-2ee36d62a260.png)

### Your Proposal

I get these lines in the console when the error happens

.
[B#768] [14:53:11] [Server thread/INFO]: Saving chunks for level 'Journey'/SpectreWorld
[B#768] [14:53:13] [AromaBackup/INFO]: [§1AromaBackup§r] World Backup done!
[B#768] [14:53:13] [AromaBackup/INFO]: [§1AromaBackup§r] Next scheduled Backup in 30 minutes.
[B#768] [15:01:26] [Client thread/INFO]: [CHAT] [§1AromaBackup§r] World Backup done!
[B#768] [15:01:26] [Client thread/INFO]: [CHAT] [§1AromaBackup§r] Next scheduled Backup in 30 minutes.
[B#768] [15:01:27] [Server thread/WARN]: WARNING: Possible Lag Source at [-170, 69, 179] in Dimension 0 with 378930300ns caused by an instance of class gregtech.common.tileentities.boilers.GT_MetaTileEntity_Boiler_Solar
[B#768] [15:01:38] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.util.concurrent.ExecutionException: java.lang.NullPointerException
[B#768] [15:01:38] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
[B#768] [15:01:38] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at codechicken.nei.recipe.RecipeHandlerQuery.getHandlersWithRecipes(RecipeHandlerQuery.java:63)
[B#768] [15:01:38] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at codechicken.nei.recipe.RecipeHandlerQuery.getRecipeHandlersParallel(RecipeHandlerQuery.java:45)
[B#768] [15:01:38] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at codechicken.nei.recipe.RecipeHandlerQuery.runWithProfiling(RecipeHandlerQuery.java:32)
[B#768] [15:01:38] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:38)
[B#768] [15:01:38] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at codechicken.nei.recipe.GuiCraftingRecipe.openRecipeGui(GuiCraftingRecipe.java:22)
[B#768] [15:01:38] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at codechicken.nei.api.ShortcutInputHandler.handleMouseClick(ShortcutInputHandler.java:72)
[B#768] [15:01:38] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at bq_standard.client.gui.panels.content.PanelInteractiveItemSlot.onMouseClick(PanelInteractiveItemSlot.java:43)
[B#768] [15:01:38] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at betterquesting.api2.client.gui.panels.CanvasMinimum.onMouseClick(CanvasMinimum.java:105)
[B#768] [15:01:38] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at betterquesting.api2.client.gui.panels.CanvasEmpty.onMouseClick(CanvasEmpty.java:76)
[B#768] [15:01:38] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at betterquesting.api2.client.gui.panels.lists.CanvasScrolling.onMouseClick(CanvasScrolling.java:317)
[B#768] [15:01:38] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at betterquesting.api2.client.gui.panels.CanvasEmpty.onMouseClick(CanvasEmpty.java:76)
[B#768] [15:01:38] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at betterquesting.api2.client.gui.panels.CanvasEmpty.onMouseClick(CanvasEmpty.java:76)
[B#768] [15:01:38] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at betterquesting.api2.client.gui.panels.CanvasEmpty.onMouseClick(CanvasEmpty.java:76)
[B#768] [15:01:38] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at betterquesting.api2.client.gui.GuiScreenCanvas.onMouseClick(GuiScreenCanvas.java:281)
[B#768] [15:01:38] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at betterquesting.client.gui2.GuiQuest.onMouseClick(GuiQuest.java:205)
[B#768] [15:01:38] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at betterquesting.api2.client.gui.GuiScreenCanvas.func_146274_d(GuiScreenCanvas.java:206)
[B#768] [15:01:38] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
[B#768] [15:01:38] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
[B#768] [15:01:38] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
[B#768] [15:01:38] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3104)
[B#768] [15:01:38] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.client.main.Main.main(SourceFile:148)
[B#768] [15:01:38] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[B#768] [15:01:38] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[B#768] [15:01:38] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[B#768] [15:01:38] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at java.lang.reflect.Method.invoke(Method.java:497)
[B#768] [15:01:38] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[B#768] [15:01:38] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[B#768] [15:01:42] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NullPointerException
[B#768] [15:01:42] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[B#768] [15:01:42] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[B#768] [15:01:42] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[B#768] [15:01:42] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[B#768] [15:01:42] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
[B#768] [15:01:42] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
[B#768] [15:01:42] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: ... 27 more
[B#768] [15:01:42] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NullPointerException
[B#768] [15:01:42] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[B#768] [15:01:42] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[B#768] [15:01:42] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[B#768] [15:01:42] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[B#768] [15:01:42] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
[B#768] [15:01:42] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
[B#768] [15:01:42] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:735)
[B#768] [15:01:42] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at java.util.stream.ReduceOps$ReduceOp.evaluateParallel(ReduceOps.java:714)
[B#768] [15:01:42] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
[B#768] [15:01:42] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
[B#768] [15:01:42] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at codechicken.nei.recipe.RecipeHandlerQuery.lambda$getHandlersWithRecipes$2(RecipeHandlerQuery.java:62)
[B#768] [15:01:42] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at codechicken.nei.recipe.RecipeHandlerQuery$$Lambda$2299/1434111396.call(Unknown Source)
[B#768] [15:01:42] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
[B#768] [15:01:42] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[B#768] [15:01:42] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[B#768] [15:01:42] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
[B#768] [15:01:42] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[B#768] [15:01:42] [Client thread/INFO]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NullPointerException
[B#768] [15:01:42] [Client thread/INFO]: [CHAT] There was error during loading recipe. Please check log for details.
[B#768] [15:01:43] [Server thread/WARN]: WARNING: Possible Lag Source at [-175, 65, 171] in Dimension 0 with 158625800ns caused by an instance of class gregtech.api.metatileentity.implementations.GT_MetaTileEntity_BasicMachine_GT_Recipe
[B#768] [15:01:47] [Server thread/INFO]: Saving and pausing game...
.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2022-12-06 13:41
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11461

**Closed by chochem** 2022-12-06 13:41 UTC
Labels: Type: bugMinor, Status: Triage

**Comment by D4shwood** [comment] 2022-12-06 13:43
Thank youu
