### ISSUE TITLE
Placing the capacitor bank caused the server to crash

### ISSUE THREAD

**Issue by Apochy** [GTNewHorizons/GT-New-Horizons-Modpack#16231] opened 2024-05-10 15:33 UTC
### Your Pack Version

2.6.0

### Your Server

private sever

### Java Version

Java 8

### Type of Server

Thermos

### Your Actions

place a Lapotronic Supercapacition

### Crash Report

[crash-2024-05-10_23.14.27-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15276857/crash-2024-05-10_23.14.27-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Lyfts** [comment] 2024-05-10 15:40
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16167

Update Kekztech to latest https://github.com/GTNewHorizons/KekzTech/releases/tag/0.11.3

**Closed by Lyfts** 2024-05-10 15:40 UTC
Labels: Type: Crash, Status: Triage
