### ISSUE TITLE
Hybrid Solar Panel Crach

### ISSUE THREAD

**Issue by sora301** [GTNewHorizons/GT-New-Horizons-Modpack#5936] opened 2020-04-16 21:47 UTC
Which modpack version are you using?
2.0.8.8

If in multiplayer; On which server does this happen? 
Private

What did you try to do, and what did you expect to happen?
Place The Hybrid Solar Panel 

What happened instead? (Attach screenshots if needed)
All the players what Kick and is impossible to restart the ServeR

[crash-2020-04-16_21.53.18-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/4489881/crash-2020-04-16_21.53.18-server.txt)

**Comment by Prometheus0000** [comment] 2020-04-16 21:52
Duplicate of #4858

**Closed** 2020-06-07 18:52 UTC
Labels: FixedInDev, duplicate
