### ISSUE TITLE
pipes disconect when shutter is of

### ISSUE THREAD

**Issue by botn365** [GTNewHorizons/GT-New-Horizons-Modpack#5648] opened 2020-02-25 17:00 UTC
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
mp
#
#### What do you suggest instead/what changes do you propose?
when you trie to control fluid from going in/out of tanks with shutters/pump
the pipe will break the conection with the tank when the shutter is off but not re connect after it is enebled again 
this makes fluid controll very hard

**Comment by Dream-Master** [comment] 2020-02-25 18:44
@botn365 feel free to do a pr if you like

**Comment by mitchej123** [comment] 2020-02-25 18:56
Can you provide a screenshot of the setup with details on how to reproduce?  I went to great lengths to ensure the shutters/etc just disabled flow and didn't actually disconnect, exactly because of the issue that you're talking about.

**Comment by repo-alt** [comment] 2020-02-25 18:57
I think I saw that but thought it is just visual

**Comment by botn365** [comment] 2020-02-25 19:00
![afbeelding](https://user-images.githubusercontent.com/42187820/75278027-7212b500-5809-11ea-85e5-f04d2f9b51e3.png)

**Comment by Prometheus0000** [comment] 2021-03-21 18:17
Should be fixed given #5733

**Closed by Prometheus0000** 2021-03-21 18:17 UTC
Labels: Mod: GT, Type: Need Code changes

**Comment by dgealow** [comment] 2024-09-26 00:57
This is actually totally still an issue. Ditto for pumps. Ticket should be reopened.

**Comment by dgealow** [comment] 2024-09-26 01:01
Workaround: Put the controller cover and shutter/pump on the pipe instead of the machine
