### ISSUE TITLE
Oil Cracking Unit stopped forming when "stacked" horizontally

### ISSUE THREAD

**Issue by Sphyix** [GTNewHorizons/GT-New-Horizons-Modpack#8099] opened 2021-06-23 13:15 UTC
#### Which modpack version are you using?
2.1.1.0
#
#### If in multiplayer; On which server does this happen? 
delta

#
#### What did you try to do, and what did you expect to happen?
Built 2 Oil Cracking Units 1 near the other sharing the middle on the long side
![javaw_lw8Nt8Kbgo](https://user-images.githubusercontent.com/17811922/123101972-dad96400-d434-11eb-9c76-6092bf7ef7d5.png)
![javaw_yZOUhNFcmL](https://user-images.githubusercontent.com/17811922/123101980-dca32780-d434-11eb-8f07-6aa328ac041b.png)
Expected them to form and work, but 1 refuses to work.

Noticed that I can stack them vertically and get them to work properly.
![javaw_RSVqfQISKr](https://user-images.githubusercontent.com/17811922/123102036-ed539d80-d434-11eb-9c4a-ecac8b80567e.png)

What's the difference between them stacked vertically or horizontally?
I guess I could get them to work by inverting input and output on the one that is not forming horizontally, but that shouldn't be an issue.

So I suggest to change the structure check to accept input and output buses on both sides of the multiblock, to be able to wallshare them horizontally aswell

#
#### What is your GTNH Discord username?
Pandoro#4811

**Comment by Glease** [comment] 2021-06-23 13:25
Input has to be on the logical left side of controller and output on right. Rotate the controller front face 180 degree with TecTech front rotation tool in case you want the input to on the right side. Duplicate of #7616.

**Closed by Glease** 2021-06-23 13:25 UTC
