### ISSUE TITLE
Zeron-100 Reactor Shielding is not made of Zeron-100

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11280] opened 2022-09-11 07:02 UTC
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.2.0.0-RC-1

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

It should not be called zeron-100 reactor shielding when not made of zeron-100.

### The Reality

![Zeron-100](https://user-images.githubusercontent.com/85604068/189516142-8f4db217-a7f2-49bb-853c-15385eb8019f.png)

### Your Proposal

Change the name and texture of this block.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment] 2022-09-11 07:36
Duplicate of #10961

**Closed by miozune** 2022-09-11 07:36 UTC
Labels: Type: bugMinor, Status: Triage
