### ISSUE TITLE
Modpack loading up but always crashes seconds before making it to the main menu

### ISSUE THREAD

**Issue by Swissboy9435** [GTNewHorizons/GT-New-Horizons-Modpack#16251] opened 2024-05-12 19:01 UTC
### Your GTNH Discord Username

stoodpaladin556

### Your Pack Version

2.6.0

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

I started it up and was waitng for it to load, it was at 100% and the memory was just doing something for a bit and it crashed.
![Screenshot 2024-05-12 203209](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/169609701/13447dac-58c9-4c70-bf54-0cbac794efd8)

### Crash Report

[crash-2024-05-12_18.02.15-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15287373/crash-2024-05-12_18.02.15-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2024-05-12 19:56
duplicate of https://github.com/GTNewHorizons/Angelica/issues/411 and https://github.com/GTNewHorizons/Angelica/issues/322

**Closed by chochem** 2024-05-12 19:56 UTC
Labels: Type: Crash, Status: Triage
