### ISSUE TITLE
Dark Deep Portal infusion recipe currently broken, likely from its recipe's instability value being over the limit. 

### ISSUE THREAD

**Issue by ChromicRedBrick** [GTNewHorizons/GT-New-Horizons-Modpack#11290] opened 2022-09-12 06:47 UTC
### Your GTNH Discord Username

ChromicRedBrick#6260

### Your Pack Version

2.2.0.0-RC-2

### Your Server

SP

### Type of Server

Single Player

### Your Actions

I was testing the new infusion interceptor, everything went smoothly at first. But when I start the infusion of Portal to Deep Dark, the game crashes. I tried several times including performing a clean install of 2.2.0.0-RC-2, it still crashed when the infusion started, giving the same error. 

I also tried many other infusion recipes, but only DD made the game crash.

### Edit: Note from Alastor:
Not an issue with the intercepter, an issue with the portal's recipe, not related to the intercepter whatsoever, we gotta stop putting infusion instability values over 25 my guys.

### Crash Report

First crash report (RC1): https://pastebin.ubuntu.com/p/QjT2r5VKyx/
After updated to RC2: https://pastebin.ubuntu.com/p/nZ9cVxhTYX/
After a clean install of RC2:  https://pastebin.ubuntu.com/p/bvZnBz54Sz/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [x] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Alastors** [comment] 2022-09-13 01:28
@ChromicRedBrick 

A few questions:

1. Were you WAing the intercepter?
2. How were you supplying essentia?
3. Could you provide a recipe for the DD portal? (I could get it myself in game, but in general it would help to have it here to know if it's anything specific with the recipe itself?

**Comment by Alastors** [comment] 2022-09-13 01:30
Oh one other thing, were you WAing the infusion matrix?

**Comment by Alastors** [comment] 2022-09-13 01:31
I'm wondering if it's a bug with the matrix itself, the intercepter, the WA, or if it's a bug with recipe tweaker as a whole (I doubt it's this one, but one never knows)

**Comment by ChromicRedBrick** [comment] 2022-09-13 02:36
I reproduced this crash in the video: https://youtu.be/9u3fcMvMm8I

Crash report is almost the same: https://pastebin.ubuntu.com/p/Zd4fTTJmWh/

1. I'm using the infusion interceptor only. 
2. I supply essentia with thaumic energistics.
3. I show the recipe in the video.

The modpack version is 2.2.0.0-RC-2 with several manual updates and some additional mods, but I can reproduce the crash use original 2.2.0.0-RC-2 pack following the exact steps in the video too.

**Comment by Alastors** [comment] 2022-09-13 05:45
@ChromicRedBrick through testing and extensive searching through the code, Glee and myself have come to the conclusion/found the actual issue:

It's not the intercepter, it's an issue with the recipe itself, I tested the recipe, without the intercepter, without anything really, instant crash, Glee believes it might be due to the instability being 64 or such, (the highest recipe instability is 25) 

Likewise, in my replication of the error (the first test without the intercepter) I instantly crashed, confirming the thought.
[crash-2022-09-13_00.41.50-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9553863/crash-2022-09-13_00.41.50-server.txt)

Now the real question, as Glee put it, "how has no one noticed this bug in two years? The change was 2 years ago."

**Comment by ChromicRedBrick** [comment] 2022-09-13 08:02
I asked other people who used DD recipe before (all of them do not use infusion interceptor because it is a new thing), some said they experienced the crash but others did not. The crash always happens instantly at the start of infusion. As far as I can know, the crash happens in single player only, no one in server experienced the crash.

The crash does not happens every time, I test 3 times without anything, 3 times with WA only and 7 times with the infusion interceptor. Infusion interceptor always leads to an instant crash, and I only experience 1 crash with WA, and 1 crash without anything. Other people I asked also said that not every time the crash happens. The crash reports all points to the same error.

Few people would report the bug since game not crashes every time, and they only need 1 successful infusion to finally obtain the Deep Dark Portal--it is unlikely to get 3 or more crashes in a row, maybe it's the reason.

In addition, I changed the instability of the recipe from 64 to 20 in CoreMod.zs, and tested with interceptor, with WA, with nothing; all situations tested and not a single crash happened. I think glee is right, the instability causes the crash.

**Comment by Hikari1nVoid** [comment] 2022-09-13 08:31
This bug will trigger once the EssentiaHandler.drainEssentia() returned false and your crafting recipe instability is higher than 33.3.

**Comment by Hikari1nVoid** [comment] 2022-09-13 08:39
Or you guys really want to make it a penalty that "If someone gets into trouble while doing infusion on DD then DESTORY his world saves(in MP then kill the server,lol)"...

**Comment by ChromicRedBrick** [comment] 2022-09-13 08:51
> This bug will trigger once the EssentiaHandler.drainEssentia() returned false and your crafting recipe instability is higher than 33.3. Since TC4 is close sourced so maybe we have to buff all recipes to less than 33 instability. For reference only:[https://github.com/LostModders/Thaumcraft4-1.7.10/blob/master/thaumcraft/common/tiles/TileInfusionMatrix.java]

So maybe this is why the infusion interceptor + DD recipe always lead to a crash. It does not drain essentia at the exact start of infusion process, thus triggers both of the conditions.

People who start to make deep dark portal in lategame mostly have sufficient essentia supply, and the matrix can drain essentia immediately, so the first condition of the crash is not triggered (when they use traditional essentia supply instead of infusion interceptor).

**Comment by Connor-Colenso** [comment] 2022-09-13 13:16
I'm not convinced this isn't related to some weird stuff you're doing since the DD recipe hasn't changed in a long time (other than just swapping out some field generators) and lots of people, including myself, have crafted it previously without issue.

**Comment by EnderProyects** [comment] 2022-09-13 13:31
Edit some other recipe to a high instability and test if there is a crash, so you can tell if is the instability or the recipe itself

**Comment by ChromicRedBrick** [comment] 2022-09-13 14:16
I edited the instability of dragon egg recipe to 33, and silky jewel to 34, both in CoreMod.zs, like this: https://pastebin.ubuntu.com/p/Xk7mzVpYkD/

Started infusion without any essentia supply, the dragon egg recipe did not crash, and the silky jewel recipe caused crashing instantly when the infusion started. And crash report was almost the same as DD infusion: https://pastebin.ubuntu.com/p/dR7kstg83B/

This is easy to reproduce, just start an infusion with an instability > 33 **without any essentia supply**, then--crash.

**Comment by Alastors** [comment] 2022-09-13 21:51
> I asked other people who used DD recipe before (all of them do not use infusion interceptor because it is a new thing), some said they experienced the crash but others did not. The crash always happens instantly at the start of infusion. As far as I can know, the crash happens in single player only, no one in server experienced the crash.
> 
> The crash does not happens every time, I test 3 times without anything, 3 times with WA only and 7 times with the infusion interceptor. Infusion interceptor always leads to an instant crash, and I only experience 1 crash with WA, and 1 crash without anything. Other people I asked also said that not every time the crash happens. The crash reports all points to the same error.
> 
> Few people would report the bug since game not crashes every time, and they only need 1 successful infusion to finally obtain the Deep Dark Portal--it is unlikely to get 3 or more crashes in a row, maybe it's the reason.
> 
> In addition, I changed the instability of the recipe from 64 to 20 in CoreMod.zs, and tested with interceptor, with WA, with nothing; all situations tested and not a single crash happened. I think glee is right, the instability causes the crash.

my guy, I'm telling you, this isn't the intercepter's issue.

**Comment by Alastors** [comment] 2022-09-13 21:53
> > This bug will trigger once the EssentiaHandler.drainEssentia() returned false and your crafting recipe instability is higher than 33.3. Since TC4 is close sourced so maybe we have to buff all recipes to less than 33 instability. For reference only:[https://github.com/LostModders/Thaumcraft4-1.7.10/blob/master/thaumcraft/common/tiles/TileInfusionMatrix.java]
> 
> So maybe this is why the infusion interceptor + DD recipe always lead to a crash. It does not drain essentia at the exact start of infusion process, thus triggers both of the conditions.
> 
> People who start to make deep dark portal in lategame mostly have sufficient essentia supply, and the matrix can drain essentia immediately, so the first condition of the crash is not triggered (when they use traditional essentia supply instead of infusion interceptor).

The intercepter code doesn't actually touch the drain essentia code or any of the normal essentia transport methods, I attach directly to the matrix, and pull the matrix's aspectlist directly into the intercepter

**Comment by Alastors** [comment] 2022-09-13 21:54
Also it does dran at near the exact start, it starts the removal the second the matrix puts up the aspectList

**Comment by Alastors** [comment] 2022-09-13 22:00
> I edited the instability of dragon egg recipe to 33, and silky jewel to 34, both in CoreMod.zs, like this: https://pastebin.ubuntu.com/p/Xk7mzVpYkD/
> 
> 
> 
> Started infusion without any essentia supply, the dragon egg recipe did not crash, and the silky jewel recipe caused crashing instantly when the infusion started. And crash report was almost the same as DD infusion: https://pastebin.ubuntu.com/p/dR7kstg83B/
> 
> 
> 
> This is easy to reproduce, just start an infusion with a recipeInstability > 33 (only recipe itself matters)**without any essentia supply**, then--crash.

Which indicates that it's clearly an issue with instability and not the intercepter specifically

**Comment by Alastors** [comment] 2022-09-13 22:01
> I'm not convinced this isn't related to some weird stuff you're doing since the DD recipe hasn't changed in a long time (other than just swapping out some field generators) and lots of people, including myself, have crafted it previously without issue.

Yeah, that's kind of been my thought from the start, but I was able to instantly reproduce it on a base-non-intercepted infusion altar first try on my thaum test world and it corrupted that shit the second it went off

**Comment by Alastors** [comment] 2022-09-13 22:07
I merged Ethryan's commit to reduce the instability to 32, honestly I dunno why we don't just reduce it to the cap at 25, but either way, if someone could test and see if it can be replicated with the more stable recipe, that would be lovely

**Comment by Hikari1nVoid** [comment] 2022-09-13 23:33
> I merged Ethryan's commit to reduce the instability to 32, honestly I dunno why we don't just reduce it to the cap at 25, but either way, if someone could test and see if it can be replicated with the more stable recipe, that would be lovely

33 is based on decompiled TC4 code in order not to trigger a crash.Feel free to change it to 25 if you think that's reasonable.

**Comment by Alastors** [comment] 2022-09-14 00:31
> > I merged Ethryan's commit to reduce the instability to 32, honestly I dunno why we don't just reduce it to the cap at 25, but either way, if someone could test and see if it can be replicated with the more stable recipe, that would be lovely
> 
> 33 is based on decompiled TC4 code in order not to trigger a crash.Feel free to change it to 25 if you think that's reasonable.

I don't just keep pointing out 25 as some magic number btw, the thaum code reduces instability above 25 to 25 in many places throughout the infusion matrix code

<img width="249" alt="Screen Shot 2022-09-13 at 7 31 09 PM" src="https://user-images.githubusercontent.com/78517796/190032643-d65f9cf5-4855-4c70-96c5-499500e998c5.png">

**Comment by Alastors** [comment] 2022-09-14 00:32
<img width="509" alt="Screen Shot 2022-09-13 at 7 31 54 PM" src="https://user-images.githubusercontent.com/78517796/190032740-7d86d114-aeb2-4fb5-9042-adaf61c83551.png">
<img width="533" alt="Screen Shot 2022-09-13 at 7 32 01 PM" src="https://user-images.githubusercontent.com/78517796/190032750-79fe5491-6841-4ddd-ae24-ec84a0d76622.png">
<img width="513" alt="Screen Shot 2022-09-13 at 7 32 08 PM" src="https://user-images.githubusercontent.com/78517796/190032760-5fbe665e-86fc-41cf-a8e3-b715b164545d.png">

(I thought there were more, but 3 places is more than enough to see that it's trying to set 25 as the max cap for instability for a reason)

**Comment by Alastors** [comment] 2022-09-14 00:33
<img width="491" alt="Screen Shot 2022-09-13 at 7 33 08 PM" src="https://user-images.githubusercontent.com/78517796/190032851-8325023c-89ed-4c21-8b07-1bebce705672.png">
one more just to show what class this is in

**Comment by Hikari1nVoid** [comment] 2022-09-14 05:11
32 Crashed again.Same exception but in different lines of code.
It turns out the TC4 author are using 100-3*instability>0 and 50-2*instability IN THE SAME FILE.
He really don't wants someone to create some dangerous item lol.

**Comment by ChromicRedBrick** [comment] 2022-09-14 05:54
Recipe instability 32 can cause crash too.

As I mentioned before, recipeInstability > 33 cause crashing at the start of infusion when not provide any essentia. RecipeInstability > 25 can also cause  crashing but this only triggers when the altar is highly instable after draining all essentia needed. 

Steps are as follows:

1. Start the recipe with a high altar instability(or do not provide essentia at first to raise the altar instability);

2. Provide essentia;

(I used infusion interceptor to provide essentia, only because it can do that very quickly without triggering the infusion stalling because of high instability. The interceptor itself do not cause any problems.)

3. Make sure when altar start to absorb ingredients on arcane pedestals, the altar instability is 25(max instability). 

(I used omniocular to see the instability value of the altar)

4. The game crashes when ingredients get knocked off because of the instability.

(Maybe this triggers "50-2\*recipeInstability" code)

Unfortunately, nearly same crash report:

https://pastebin.ubuntu.com/p/b7vpP983Cm/
https://pastebin.ubuntu.com/p/JcK4Rgy3Q5/

**Comment by ChromicRedBrick** [comment] 2022-09-14 11:27
I noticed another recipe with > 25 instability in 2.2.0.0-RC-2, the angel ring.
![20220914185430](https://user-images.githubusercontent.com/85604068/190135812-f898a0de-5042-4d3a-b379-a9719ac0763a.png)

I tried this recipe, followed the steps above, got another crash, yet another similarly dull crash report:  https://pastebin.ubuntu.com/p/phh89h4g9H/

Also, I found the steps to reproduce the crash (when recipe instability = 26-33) is rather easy, so I edited previous comment.

**Comment by mitchej123** [comment] 2022-09-14 13:11
Seems like we should patch the crash and hard cap the instability via asm/mixins as it seems clear he tried to do that elsewhere but neglected this location

**Closed** 2022-09-23 07:22 UTC
Labels: Status: Waiting for Fix, Type: bugMinor, Status: Work in Progress, Type: Crash, Priority: MEDIUM, Mod: Thaumcraft, Mod: Extra Utilities, Closed Source, Recipe: Minetweaker, Thaumcraft: Instability Over Limit

**Comment by ChromicRedBrick** [comment] 2022-09-28 05:07
https://github.com/GTNewHorizons/TC4Tweaks/pull/11 Why is this fix not included in 2.2.0.0 stable? The pack in download page still uses Thaumcraft4Tweaks-1.7.10-1.4.16.jar.

**Comment by Connor-Colenso** [comment] 2022-09-28 05:11
Presumably because a new version was not tagged after merger. This would be resolved by auto tagging upon PRs but apparently that is bad practice so this stuff can happen from time to time.
