### ISSUE TITLE
Falling obsidian causes FPS lag in the end

### ISSUE THREAD

**Issue by Lainiel** [GTNewHorizons/GT-New-Horizons-Modpack#18120] opened 2024-11-26 18:28 UTC
### Your GTNH Discord Username

lainiel

### Your Pack Version

2.6.1

### Your Server

private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Falling obsidian doesn't cause lag in the end.

### The Reality

Falling obsidian in the end causes FPS lag. It turned the chunk that is from X:0-15 and Z:0-15 into a swiss cheese and there's a lot of bugged fallen obsidian. When you break the block under the falling obsidian it it spawns several stacks of obsidian blocks. When these bugged falling obsidian blocks are removed the lag stops. Given by the amount of obsidian blocks I got there were probably more than a thousand bugged falling obsidian entities in my case.

Here's a video of what happens:

https://github.com/user-attachments/assets/32be81a3-9fbd-469c-85ce-4b40dba38366

Here's how the chunk looks like:

![image](https://github.com/user-attachments/assets/9035b375-8a4d-493d-be06-27cff1f4d20d)

### Your Proposal

Fix the falling obsidian code.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2024-12-03 10:16
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17914

**Closed by chochem** 2024-12-03 10:16 UTC
Labels: Bug: Minor, Status: Triage
