### ISSUE TITLE
Server crash when exploring the Twilight Forest

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [GTNewHorizons/GT-New-Horizons-Modpack#16884] opened 2024-07-31 21:37 UTC
### Your GTNH Discord Username

eldrinn_elantey

### Your Pack Version

2.6.1

### Your Server

privat server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Actions

With a friend exploring the dusky forest. Headed in the direction of the unkilled Naga

### Crash Report

[crash-2024-08-01_01.30.34-server.txt](https://github.com/user-attachments/files/16447397/crash-2024-08-01_01.30.34-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Ruling-0** [comment] 2024-07-31 21:39
This is a known, common crash that has had several issues. Updating Twilight Forest as below should fix it

To fix nagastone-related crashes, update the Twilight Forest mod:
https://github.com/GTNewHorizons/twilightforest/releases/download/2.6.12/TwilightForest-2.6.12.jar
Download the .jar, and replace the old version of the mod in your ./minecraft/mods/ folder.

**Comment by Lyfts** [comment] 2024-07-31 21:42
![s](https://github.com/user-attachments/assets/d9286e8a-10d1-493c-b13b-6c59d3cc2440)
You sure? Anyways duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16353 and a so so many others...

**Closed by Lyfts** 2024-07-31 21:42 UTC
Labels: Type: Crash, Status: Triage
