### ISSUE TITLE
The Spice of Life - Carrot Edition, Natura Crash

### ISSUE THREAD

**Issue by JustABlitz** [GTNewHorizons/GT-New-Horizons-Modpack#13587] opened 2023-05-30 18:19 UTC
### Your GTNH Discord Username

JustABlitz#6993

### Your Pack Version

2.3.2

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

eating because dimishing returns. *probably* because the item (some berry from those bushes) restored 1 hunger already and it couldnt take away more. also i cant re-enter the world

### Crash Report

https://paste.ubuntu.com/p/TPYtQVvQh5/
https://pastebin.com/cE5cZxcj (no login)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment] 2023-06-07 14:27
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12519

**Closed by miozune** 2023-06-07 14:27 UTC
Labels: Type: Crash, Status: Triage, Mod: Spice of Life
