### ISSUE TITLE
Higher tier's Energy Hatch need for new way to make 

### ISSUE THREAD

**Issue by Sakura-sama** [GTNewHorizons/GT-New-Horizons-Modpack#6807] opened 2020-10-11 11:55 UTC
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
multiplayer

#### What do you suggest instead/what changes do you propose?
  Now energy hatchs higher than UHV are still using their old,easy and opportunistic recipe,one blockmachine and one wire.
  They are so easy to be made, even IV.So I suggest they can get their own new high tier recipe like the other energy hatchs, one blockmachine,some pumps,coils ,wires,chips and other liquid.They shall be more expensive,and need for suitable technic level.

  One more needs for change,now t8 rocket needs for UEV,means for your Assembly Line needs two UHV energy hatch,which need UHV superconducter. But making UHV superconductor needs for awakendargon powder,only generate at T8 planets.
  So we should give UHV energy hatch a new recipe,like the other high tier energy hatch.

**Comment by Prometheus0000** [comment] 2020-10-11 12:10
Duplicate of #4977. Suggest a recipe if you want it to change. Also, the rocket thing is fixed already, maybe not on 2.0.9.0 QF4 though. #6208

**Closed by Prometheus0000** 2020-10-11 12:10 UTC
Labels: Type: duplicate
