### ISSUE TITLE
Hide ThaumicEnergistics Aspect gases in ae2fc fluid terminal 

### ISSUE THREAD

**Issue by EIioH** [GTNewHorizons/GT-New-Horizons-Modpack#13430] opened 2023-05-05 18:28 UTC
### Your GTNH Discord Username

ElioH#1043

### Your Pack Version

2.3.3

### Your Proposal

Please, hide TE aspects gases from fluid terminal.

### Your Goal

They are annoying.

### Your Vision

They are not displayed in the Extracells terminal.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by firenoo** [comment] 2023-05-05 23:29
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12971

**Closed by firenoo** 2023-05-05 23:29 UTC
Labels: Type: Duplicate, Type: Suggestion, Status: Triage
