### ISSUE TITLE
Textures not loading (2.2.9 9-pre-dev, java19)

### ISSUE THREAD

**Issue by cinch** [GTNewHorizons/GT-New-Horizons-Modpack#12549] opened 2023-02-10 16:15 UTC
### Your GTNH Discord Username

Fiyorin

### Your Pack Version

2.2.9 9-pre-dev (latest zip from dream GTNH-2.2.9-9-pre-dev-Java-19-PrismL.zip)

### Your Server

SP

### Type of Server

None

### Your Expectation

I made a new instance in MultiMC and a new world. Textures don't load in game.

### The Reality

![2023-02-10_17 02 02](https://user-images.githubusercontent.com/61357/218139091-0b05821c-b466-4812-8ce2-61411e98026b.png)

error log:
missing texture errors are from line 27708

[fml-client-latest.log](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10709268/fml-client-latest.log)

interestingly it runs just fine if optifine is enabled (OptiFine_1.7.10_HD_U_E7.jar)

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [x] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2023-02-10 16:40
removed optifine (I always use it normally), can confirm:

![image](https://user-images.githubusercontent.com/40274384/218146664-18a1607f-b819-4d45-9da8-4dafce181224.png)

**Comment by chochem** [comment] 2023-02-11 18:10
more testing says its caused by fastcraft. (optifine mostly disables it)

**Comment by eigenraven** [comment] 2023-02-18 11:04
Should already be fixed in 2.2.10

**Closed by eigenraven** 2023-02-18 11:04 UTC
Labels: Type: bugMinor, java9+
