### ISSUE TITLE
Minor - Tutorial Quest Book defaults conflicting bindings.

### ISSUE THREAD

**Issue by BaneWilliams** [GTNewHorizons/GT-New-Horizons-Modpack#14821] opened 2023-11-04 10:23 UTC
### Your GTNH Discord Username

banewilliams

### Your Pack Version

2.4.0

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Expectation

The tutorial told me I didn't need the questbook and that tilde would open it as long as I hadn't changed keybindings.

### The Reality

Pressing tilde opened up an options menu instead of the quest book. 

### Your Proposal

remove the conflicting keybind from CraftPresence - Controls

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2023-11-04 11:08
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14006
uff I thought we fixed that before stable. clearly we didnt.

**Closed by chochem** 2023-11-04 11:08 UTC
Labels: Type: bugMinor, Status: Triage
