### ISSUE TITLE
Fusion/Compact Fusion improvement

### ISSUE THREAD

**Issue by MaGeBZz** [GTNewHorizons/GT-New-Horizons-Modpack#15303] opened 2024-01-09 13:47 UTC
### Your GTNH Discord Username

marvinhhmagebzz

### Your Pack Version

2.5.1

### Your Proposal

The fusions didn't accept crafting input buffer and/or stocking hatches, I would suggest to accept at least one of them maybe even both

### Your Goal

Automation of fusion can be done with fluid p2p's etc but imo it's not the best way and maybe it didn't have to be crafting input buffers but stocking hatches would be good to be accepted to use them instead of multiple subnets or p2p's

### Your Vision

Let the fusions or at least the compacts get access to crafting input buffer and/or stocking hatches to replace normal input hatches

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by lordIcocain** [comment] 2024-01-09 17:14
but compact already support stocking hatch

**Comment by HoleFish** [comment] 2024-01-09 17:17
buffer part is duplicate of [#14991 ](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14991)

**Comment by MaGeBZz** [comment] 2024-01-12 14:46
@lordIcocain they do? Just tested it with a normal mk4 and it didn't work so I assumed compacts don't have the ability to use stocking too

**Comment by foxwhite25** [comment] 2024-01-26 15:56
Yes that change only changes the compact fusion, and normal fusion reactor still does not work with crafting input buffer

**Closed** 2024-02-06 13:20 UTC
Labels: Type: Suggestion, Status: Triage
