### ISSUE TITLE
Cooking for Blockheads Cooking Table causes Armor to "disconnect"

### ISSUE THREAD

**Issue by TwoTailedFox** [GTNewHorizons/GT-New-Horizons-Modpack#11215] opened 2022-09-04 13:34 UTC
### Your GTNH Discord Username

BritishCynic#9193

### Your Pack Version

2.1.2.4-dev29

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

When you right-click on the Cooking Table, the table GUI should open without negative effects.

### The Reality

When you right-click on the Cooking Table, the GUI for the table opens as normal, but the game thinks that all of the player's armor has been removed (when you open the inventory GUI, all armor slots will show a vacant slot), but when you left-click one of the empty slots, all of the previously-equipped armor pieces reappear, and the armor piece you clicked is in your mouse cursor as if it was showing when you clicked to pick it up.

This means that all enchantments that were active at the time, like night vision, cease to function until you make the armor show again in the inventory GUI and you re-enable it manually.

### Your Proposal

Prevent the Cooking Table from hiding the armor from the player and the game inventory.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment] 2022-09-05 09:23
Duplicate of #10396

**Closed by miozune** 2022-09-05 09:23 UTC
Labels: Type: bugMinor, Status: Triage
