### ISSUE TITLE
Wrong Recipe UEV Polarizer

### ISSUE THREAD

**Issue by Alexdoru** [GTNewHorizons/GT-New-Horizons-Modpack#8489] opened 2021-09-01 18:33 UTC
### Your Pack Version

2.1.1.0

### Your Server

solo

### Your Expectation

e

### The Reality

The recipe for the UEV Polarizer (Epic Magnetism inducer II) requires a UHV machine hull instead of the UEV one

### Your Proposal

e

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Prometheus0000** [comment] 2021-09-01 19:05
Didn't I already fix this?

**Comment by Prometheus0000** [comment] 2021-09-01 19:11
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/8243

**Closed by Prometheus0000** 2021-09-01 19:11 UTC
Labels: Type: bugMinor, Status: Triage
