### ISSUE TITLE
AE2 thin interface is more expensive than block version

### ISSUE THREAD

**Issue by Demiu** [GTNewHorizons/GT-New-Horizons-Modpack#16538] opened 2024-06-15 17:25 UTC
### Your GTNH Discord Username

Demiu

### Your Pack Version

2.6.1

### Your Server

private

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Both versions of the AE2 interface have the same cost since they can be freely converted between each other

### The Reality

Thin interface takes two annihilation cores
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/7906172/470286c1-1e04-4683-b6d2-27664f273696)
While the block version takes one
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/7906172/53648ac7-27e7-4832-b8ed-74a60cd4fa6e)

### Your Proposal

Reduce the amount of annihilation cores needed for the thin interface to 1

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by NotAPenguin0** [comment] 2024-06-15 17:35
Duplicate of #16479, already fixed in https://github.com/GTNewHorizons/NewHorizonsCoreMod/pull/862

**Closed by NotAPenguin0** 2024-06-15 17:35 UTC
Labels: Type: bugMinor, Status: Triage
