### ISSUE TITLE
Project Red is being weird

### ISSUE THREAD

**Issue by Impos913** [GTNewHorizons/GT-New-Horizons-Modpack#7326] opened 2021-01-16 17:44 UTC
#### Which modpack version are you using?
2.1.0.2c
#
#### If in multiplayer; On which server does this happen? 
sp

Updated the pack from 2.1.0.0 and realized my project red stock keeper chips aren't working properly.

https://user-images.githubusercontent.com/36479271/104818920-843f7c80-583b-11eb-9596-b1bd2a79c69b.mp4

**Comment by Prometheus0000** [comment] 2021-01-16 17:46
BTW, not everyone is familiar with PR, so you might want to explain what the expected behavior is, because I have no idea what's even supposed to happen here.

**Comment by Impos913** [comment] 2021-01-16 17:49
The chip is set to keep stock of 60 items in the connected inventory. When you break and replace the routed interface pipe and put the chip in it, it sends the item but it doesn't send again when I take them out of the chest.

**Comment by Dream-Master** [comment] 2021-01-16 17:50
@makamys can you have a lock please. I add your two prs before. Maybe some of your code cause this? or is it a old bug ?

**Comment by Dream-Master** [comment] 2021-01-16 17:51
https://github.com/GTNewHorizons/ProjectRed/commit/438bec4e143199b950350b7ca87d532cad78f78d
https://github.com/GTNewHorizons/ProjectRed/commit/e3e0c4cb84eda5a90dcb0f776ec2fd62dda8de7d
https://github.com/GTNewHorizons/ProjectRed/commit/989f49d249cc1936922be1fb910ebabea1f4d991

**Comment by Impos913** [comment] 2021-01-16 17:52
They were working in 2.1.0.0. I have many stock keeper chips in the system. They all stopped now.

**Comment by oliverkane** [comment] 2021-01-24 18:07
@Dream-Master, I'm too having some strange behavior in PR's Stockkeeper chips.  I'll report back when I have some more detail for you, but what I can say so far is that my system seemed to be working up until I hit a certain level of complexity in my PR pipes (which is just a hold over till AE anyways).

Whatever happened is "infectious" in the sense that after the glitch happened, I realized that I was actually breaking each stockkeeper I pulled out to look at.  I suspect my character's data is somehow corrupt and that's causing the issue.  I notice this same behavior in a creative world I played, but haven't been able to re-create this yet.

I have a snapshot of a known good state, and will try to get back when things are broken again.

**Comment by oliverkane** [comment] 2021-01-24 20:25
Ignore me.  I was being an idiot and had not placed a Broadcaster .

**Comment by TheElan** [comment] 2021-01-25 19:12
I had the same issue couple days ago while doing oil products desulfuring automation quest line.

It looks like it is working again, I am not sure what fixed it, maybe it was a server restart or reducing system complexity (from 12 to 10 interface pipes, from 17 to 14 chips overall).

I am running private server with modpack version 2.1.0.0 + projectred from [jenkins build](http://jenkins.usrv.eu:8080/job/ProjectRed/) which is after crafting chip fix and some modes to improve monitor and TPS like opis, AI fix, etc, they shouldn't be the issue here.

**Comment by TheElan** [comment] 2021-01-25 19:31
After playing with the system a bit it stopped working again. Maybe it may have something with stock keepers abusing crafting chip, as there were not hydrogen in tank and many empty cells, which resulted in them bouncing back and forth between tank and interface pipe core.

**Comment by EmrahKhan** [comment] 2021-03-13 17:15
Project Red seperate mods in 2.1.0.0 just works fine. Merged Project Red file in 2.1.0.4 breaks all stock keepers. i changed project red mod file to older ones and theyr working fine now with dev pack.

**Comment by TheElan** [comment] 2021-03-13 18:12
@EmrahKhan did you check red chips? They are not working in 2.1.0.0.

**Comment by Impos913** [comment] 2021-04-05 13:33
Can somebody look at fixing this?  Using Project Red isn't an option right now because of this bug.

**Comment by Glease** [comment] 2021-04-07 20:27
You will need someone who actually understand scala. If that fails you could probably just go use logisitic pipes. they are very similiar. in fact some would even consider LP a superset of PR pipes

**Comment by Impos913** [comment] 2021-04-07 21:36
LP isn't fully implemented yet, no modules show up nei

**Comment by Glease** [comment] 2021-04-07 23:33
That's not supposed to happen. Try again on latest and file a ticket if that is still the case. I haven't tried the latest but the last time I review the LP script I did see most if not all 1.7.10 LP modules showing up.

**Comment by Prometheus0000** [comment] 2021-04-08 02:10
> You will need someone who actually understand scala.

Isn't what's needed is to *revert whatever was changed*? And then check it's fixed? Why don't you people who want it fixed try builds until you find one that works from the jenkins http://jenkins.usrv.eu:8080/job/ProjectRed/. Try 7-13, and report back on which one works.

**Comment by Glease** [comment] 2021-04-08 02:13
If only reloading the pack doesn't take 10 minutes and sucks all processing power/RAM away

Anyhow, there is one more problem here. One of the commit mentioned talks about "Revert XXX", so even if we just revert everything back to pre 2.0.9 it's highly likely something else went broken.

**Comment by Prometheus0000** [comment] 2021-04-08 02:30
Then I'm gonna go with: Bother the people who did the commits after finding out which one broke something.

Also, if they really want it fixed, 10m alt-tabbed several times isn't _that_ long. You can still read news or w/e, just not play a game.

**Comment by Impos913** [comment] 2021-04-08 07:56
It works fine in 2.1.0.0, and it doesn't work in 2.1.0.2c and past. Probably those commits dream mentioned broke it.

**Comment by Prometheus0000** [comment] 2021-04-08 08:55
Yes, so please test it?

**Comment by Impos913** [comment] 2021-04-08 08:58
Test wha? Idk what needs testing

**Comment by Prometheus0000** [comment] 2021-04-08 09:05
Go read what I wrote again.

**Comment by Impos913** [comment] 2021-04-08 11:20
ProjectRed-4.7.0pre13.10.jar works
http://jenkins.usrv.eu:8080/job/ProjectRed/8/
Started testing from newest, this one is the working newest.

**Comment by Dream-Master** [comment] 2021-04-11 11:41
I wrote the author of the pr a mail

**Closed** 2021-06-22 17:29 UTC
Labels: Mod:Project Red, Status: FixedInDev, Status: need to be tested, Type: bugMinor

**Comment by makamys** [comment] 2021-07-23 03:16
Hey, sorry I didn't respond. Repo's fix looks good. What happened is I made a mistake when reimplementing https://github.com/GTNewHorizons/ProjectRed/commit/db5a3863d01bd801ef2c94190f0f586297892d64 in https://github.com/GTNewHorizons/ProjectRed/commit/e3e0c4cb84eda5a90dcb0f776ec2fd62dda8de7d, but repo fixed it.
(Also I don't see a mail, maybe my spam filter ate it.)
