### ISSUE TITLE
Client Crashes on Remove EEC (kubatech)

### ISSUE THREAD

**Issue by ordpus** [GTNewHorizons/GT-New-Horizons-Modpack#11229] opened 2022-09-06 18:56 UTC
### Your Pack Version

2.1.2.4-29-pre

### Your Server

private server

### Type of Server

Thermos

### Your Actions

Remove Extreme Extermination Chamber right after placing it, the client crashed

### Crash Report

[crash-2022-09-06_14.41.06-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9499961/crash-2022-09-06_14.41.06-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by kuba6000** [comment] 2022-09-06 18:59
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11099

**Closed by kuba6000** 2022-09-06 18:59 UTC
Labels: Type: Crash, Mod: KubaTech
