### ISSUE TITLE
NEI client CME loading into server

### ISSUE THREAD

**Issue by Tommeh1** [GTNewHorizons/GT-New-Horizons-Modpack#13359] opened 2023-04-29 22:27 UTC
### Your Pack Version

2.3.2

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Actions

Started loading into the server, the client quickly froze and exited the moment terrain and presumably NEI as well started to load.

### Crash Report

[crash-2023-04-30_00.25.15-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11360167/crash-2023-04-30_00.25.15-client.txt)

Stacktrace only:
```java
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
	at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
	at codechicken.nei.KeyManager.tickKeyStates(KeyManager.java:28)
	at codechicken.nei.ClientHandler.tickEvent(ClientHandler.java:279)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_1016_ClientHandler_tickEvent_ClientTickEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at cpw.mods.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:325)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1587)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by wlhlm** [comment] 2023-05-02 10:20
Duplicate of #13292.

**Closed by wlhlm** 2023-05-02 10:20 UTC
Labels: Type: Crash, Status: Triage
