### ISSUE TITLE
Add advanced glue usage to special ceramics dust in good generator 

### ISSUE THREAD

**Issue by tommy307507** [GTNewHorizons/GT-New-Horizons-Modpack#10893] opened 2022-08-01 13:39 UTC
### Your GTNH Discord Username

Hebi#2752

### Your Pack Version

2.1.2.4 20 pre

### Your Proposal

![image](https://user-images.githubusercontent.com/49487505/182160205-3c6bcbd8-6bde-4f00-a8ad-d0489579ae5e.png)

Right now you can only use refined glue to make this ceramics, however with the push of advanced glue , I think most player would have already automated the 'better' glue way before needing to make a neutron something , would be nice to have better glue recipes that have some benefits, e.g. less time or less eu or sth 

### Your Goal

QOL and make advanced glue more common as a refined glue alternative

### Your Vision

more usage to advanced glue and higher tier glue

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by chochem** [comment] 2022-08-01 13:53
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10391

**Closed by chochem** 2022-08-01 13:53 UTC
Labels: Type: Duplicate, Type: Suggestion
