### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by bengenie** [GTNewHorizons/GT-New-Horizons-Modpack#7181] opened 2020-12-28 00:32 UTC
#### Which modpack version are you using?

#2.1.0.0QF1
#### If in multiplayer; On which server does this happen? 

#offine
#### What did you try to do, and what did you expect to happen?

#try to lord an save
#### What happened instead? (Attach screenshots if needed)

#
[crash-2020-12-27_18.59.05-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/5745495/crash-2020-12-27_18.59.05-client.txt)

**Comment by GTNH-Afx237v7** [comment] 2021-01-03 20:44
Did this happen again? Can you reproduce it, or tell us what you were doing as it crashed?

**Comment by bengenie** [comment] 2021-01-08 01:12
no it never happen again (it just started when just load an save in singleplayer

**Comment by TimeConqueror** [comment] 2021-01-08 14:16
The error is with TCNEIAdditions. Since NEI made registering recipe handlers multi-threaded, it will produce race conditions like in TCNEIAdditions#StuffRemovingThread, so it's better to fix the race condition int NEI itself (issue came from https://github.com/GTNewHorizons/NotEnoughItems/pull/27). 
ll INEIConfigure plugins register their handlers to the non-concurrent list from another thread, and on openGui it may crash from the main thread while iterating over other handlers (registrar thread is still alive at this moment).

**Comment by mitchej123** [comment] 2021-02-13 21:08
I _believe_ this should be fixed with NEI 2.0.9; if the issue remains please comment here.

**Closed** 2021-06-22 17:29 UTC
Labels: Mod: NEI, Status: FixedInDev, Type: Crash
