### ISSUE TITLE
ArrayIndex error in NEI while looking at titanium screw

### ISSUE THREAD

**Issue by POPlol333** [GTNewHorizons/GT-New-Horizons-Modpack#10804] opened 2022-07-23 11:01 UTC
### Your GTNH Discord Username

AdamR#0072

### Your Pack Version

2.1.2.0 (latest)

### Your Server

Delta

### Type of Server

Thermos

### Your Actions

everything works fine until you try to look to the titanium screw utility in the thaumcraft crafting table page 3

### Crash Report

https://pastebin.com/x45URGQL

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment] 2022-07-23 11:28
Duplicate of #7930

**Closed by miozune** 2022-07-23 11:28 UTC
Labels: Type: Crash, Status: Triage
