### ISSUE TITLE
CHEM Plant wrong processing time

### ISSUE THREAD

**Issue by miaowwwwww** [GTNewHorizons/GT-New-Horizons-Modpack#12734] opened 2023-02-28 04:33 UTC
### Your GTNH Discord Username

LEO_PREMIUM#3437

### Your Pack Version

2.2.9 + some ae changes

### Your Server

private server

### Java Version

Java 8

### Type of Server

Crucible

### Your Expectation

the coil gives the correct processing time.

### The Reality

https://cdn.discordapp.com/attachments/522098956491030558/1079973143176806450/GX5_BYR_2B4J4CD99Q3P7.png
https://cdn.discordapp.com/attachments/522098956491030558/1079973143545913354/37YEVOUJ9FMDNCY.png
CuNi coil 1tick anything 
FeAlCr coil have a lifetime process time. 
this is the screenshot of making living solder.

### Your Proposal

my guess is that the Chem plant processing time calculation is wrong.

for example, 
CuNi coil has 50% speed, the nei process time is n, final time should be n/ 0.5 = 2n. 
but the calculation might be: n/(0.5-1) which is negative, so it shows 1tick. 
FeAlCr coil has 100% speed, n/(1-1) which is infi.

Ni4Cr 1600s  tpv 800s which fits my guess. n/(1.5-1) is twice to n/(2-1)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment] 2023-02-28 05:59
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12683

**Closed by Glease** 2023-02-28 05:59 UTC
Labels: Type: bugMinor, Status: Triage
