### ISSUE TITLE
quests 933 and 934 needs solar with removed assembly nbt

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#6466] opened 2020-08-01 12:58 UTC
#### Which modpack version are you using?
2.0.9.0 QF4
#
#### If in multiplayer; On which server does this happen? 
delta
#
#### 
quest 933 "power of the sun" and quest 934 "power of the sun 8v" requires solar panels with no nbt. (solar panel 8v does not store assembly nbt when crafted so this one is fine)

**Comment by chochem** [comment] 2020-08-02 07:44
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/6283

can be closed

**Closed** 2020-08-02 11:04 UTC
Labels: NBT, Quest change, duplicate
