### ISSUE TITLE
[2.2.3] Crash on startup

### ISSUE THREAD

**Issue by albertopirillo** [GTNewHorizons/GT-New-Horizons-Modpack#11627] opened 2022-10-12 17:10 UTC
### Your GTNH Discord Username

AlbyNexus#4160

### Your Pack Version

2.2.3

### Your Server

Private Server

### Type of Server

Vanilla Forge

### Your Actions

Start the server

### Crash Report

Server loads correctly, but as soon as the overworld is loaded everything crashes.
The crash seems related to the LCS and the Nuclear Control mod. 
It might be related with https://github.com/GTNewHorizons/KekzTech/pull/43

Full crash report:
[crash-2022-10-12_17.04.22-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9767213/crash-2022-10-12_17.04.22-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by GTNHAfx237v7** [comment] 2022-10-12 17:19
Duplicate of #11558

**Closed** 2022-10-12 17:20 UTC
Labels: Type: Crash, Status: Triage
