### ISSUE TITLE
Hunter's backpack support for pam's meats

### ISSUE THREAD

**Issue by tyrannus00** [GTNewHorizons/GT-New-Horizons-Modpack#5865] opened 2020-04-03 23:17 UTC
#
2.0.88
#
local server, likely irrelevat

#
I opened the hunters backpack from Forestry and put all my (vanilla) meats in it, and tried to also put the pams harvestcraft meats like mutton, rabbit, ... in there.

#
It didnt let me place the modded meats in the backpack.

#
I suggest that compatibility is added, in a similar way as the greg tech ores and dusts fit into the miner's backpack. Not sure if its possible via crafttweaker but that could be a way to do it.

**Comment by Dream-Master** [comment] 2020-04-07 14:40
yes forestry bags need heavily configured. The problem is you havent had you bag realy long bfore you can build normal backpacks.

**Comment by Dream-Master** [comment] 2020-04-07 15:57
@tyrannus00 
feel fre to add it manually
https://github.com/GTNewHorizons/NewHorizons/blob/master/config/forestry/backpacks.cfg#L11374
Use ingame /mt hand on all items you want to add and copy paste it in the file.
Send me the file or make a pull request. Thanks

**Comment by Dream-Master** [comment] 2020-04-18 21:48
@tyrannus00 any news here?

**Comment by Krispion** [comment] 2020-07-19 18:57
@Dream-Master 
Added:

**Comment by Krispion** [comment] 2020-07-19 19:42
@Dream-Master 

Adding listAllmeatcooked and listAllmeatraw oredicts should cover all animal meats. Not sure why it isn't there by default.

**Comment by Dream-Master** [comment] 2020-07-19 19:43
idk

**Comment by Dream-Master** [comment] 2020-07-20 06:51
will add those items. Not sure if oredict is allowed

**Comment by shawnbyday** [comment] 2020-09-15 16:39
It looks like config has oredict sections. Can assign to me and I will implement and test.

**Comment by Prometheus0000** [comment] 2020-09-15 18:33
I don't think you need to wait to be 'assigned' to things if nothing's happened in a while, just go for it.

**Closed** 2020-09-21 21:07 UTC
Labels: FixedInDev, addition, config
