### ISSUE TITLE
Ross128b generation lag

### ISSUE THREAD

**Issue by Shyrff** [GTNewHorizons/GT-New-Horizons-Modpack#7235] opened 2021-01-03 20:04 UTC
#### Which modpack version are you using?
2.1.0.0
#
#### If in multiplayer; On which server does this happen? 
private, ultramine
#
#### What did you try to do, and what did you expect to happen?
on 2.0.9.0 new chunk generation caused ~0 lag.
on 2.1.0.0 new chunk generation causes huge tps drop (other planet generation has good performance). clicking prospector on ross128b causes extreme lags. Normally we have stable 20 tps, during chunk gen it drop to ~12 with often spikes of 0.5-1tps.
Server logs smth like
[20:55:20] [Server thread/WARN] [net.minecraft.network.NetworkManager/]: Possible lag source on processiong packet C08PacketPlayerBlockPlacement from EntityPlayerMP['Shyrff'/8657, l='world_unnamed64',
 x=-239.85, y=72.00, z=-2689.08] 1230ms
 during spikes
#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Maybe smth messy was done inbetween 2.0.9.0 and 2.1.0.0 with Ross128b gen? It's pretty unplayble and ross is the best pre-fusion source of indium.

**Comment by boubou19** [comment] 2021-01-03 20:34
Indium ore is not supposed to spawn anymore, unless NEI is lying. Also, this is a possible duplicate of #7212

**Comment by Shyrff** [comment] 2021-01-03 20:38
I use roquesite ore for indium. we wiped ross128b before update (for size of backup purposes), and I've found ore on newly generated planet

**Comment by Shyrff** [comment] 2021-01-03 20:47
maybe it is dup but I added info about behaviour on other planets

**Comment by boubou19** [comment] 2021-01-03 20:56
my bad for the indium part then. And thanks for the additional infos.

**Comment by Prometheus0000** [comment] 2021-01-19 17:49
@bartimaeusnek I heard you fixed this? Where's the commit/PR? Or is it not fixed? and is #7212 the same?

**Comment by boubou19** [comment] 2021-02-22 14:22
duplicate of #7386

**Closed by boubou19** 2021-02-22 14:22 UTC
Labels: Mod: BartWorks, Type: Lag, Type: duplicate
