### ISSUE TITLE
Slot in ME Interface stuck

### ISSUE THREAD

**Issue by nikitinalexx** [GTNewHorizons/GT-New-Horizons-Modpack#6404] opened 2020-07-18 10:10 UTC
The 4th slot in my ME interface got stuck. It doesn't remove the item that doesn't match.
And even if I remove the unmatched item, it will not automatically request what should be crafted.
So in example you can see it should request 3 Hydrogen, but it doesn't. And later when the wrong item is put into that slot it doesn't get freed. This happens relatively usual.
The hydrogen is craftable. Whenever I put those 3 hydrogen into a different slot, it immediately gets crafted. And no matter which item I put into the 4th slot, it doesn't get crafted and later gets stuck when something puts a different item into a bottom slot.

![image](https://user-images.githubusercontent.com/4941736/87850311-dbe64500-c8f7-11ea-8e56-ee0ff5384c41.png)

Reboot helps. But I go afk, return and see after 5 hours that it got stuck and didn't work these 5 hours...

**Comment by Dream-Master** [comment] 2020-07-20 15:09
@repo-alt any idea on this ?

**Comment by repo-alt** [comment] 2020-07-20 15:18
Maintainers of AE2 usually say about these bugs: try to reproduce with pure AE2 or maybe a few mods at most. Seriously, what can I do to reproduce that? These 2 rows of slots are implemented as an inventory (2 inventories), so there is nothing special about 4-th slot, it is never treated separately.

**Comment by Dream-Master** [comment] 2020-07-20 15:19
@nikitinalexx

**Comment by GTNH-Afx237v7** [comment] 2020-07-20 16:50
Both this issue and 6235 sound like they appear after certain time. I have a similar issue where After setting up the platinum line, an ME interface on the opposite side of the base wouldn’t accept items coming in from an advanced electrical furnace (they would just pile up in the interface). According to Opis, said chunk is the worst performance wise...
To summarize, maybe simply an issue due to high load in the chunk, maybe memory leak after certain time the game has been running? Or something else caused by too high CPU/RAM demand because of how stuff is built...

**Comment by repo-alt** [comment] 2020-07-20 16:59
Like - conduit pushes a stack into the interface, but the interface does not get the chance to process the stack? I'm not sure if there is any check in the conduit but there should be, interface is probably just an inventory from the conduit point of view, so if it gets full, conduit should not push.

**Comment by GTNH-Afx237v7** [comment] 2020-07-20 17:10
May have expressed myself bad, the platinum line and the Interface in question are not connected. Said Interface is directly attached to the furnace. The furnace outputs the processed item which then remains inside the interface‘s inventory. There is sufficient space in the AE system (both storage disks and attached chests/drawers).

**Comment by nikitinalexx** [comment] 2020-07-23 22:05
Yes, there is nothing special about the 4th slot, it might happen to any other. It's just that AE somehow thinks that it should not pull from that slot, whereas it should.

**Comment by nikitinalexx** [comment] 2020-07-30 12:04
Okay, I can easily reproduce this even from reboot to reboot.
What you need to do.
1)Put an autocraft card.
2)Put in the 2, 3 slot an item, that will be request by AE to be crafted. Make this item to be crafted for quite long, so that the slot always stays empty. And also pull that item by conduit out of the ME interface.
3)Make an SFM constantly input the items into that ME Interface.
Now you will have something like this.
![image](https://user-images.githubusercontent.com/4941736/88920665-e5679980-d275-11ea-8f53-5149260cc396.png)
@repo-alt

**Comment by nikitinalexx** [comment] 2020-07-30 12:08
So I would say the issue is that if AE expects an item to be crafted and put into the slot, and if a different item enters that slot - it won't be removed.
But it should be removed, because an autocraft of a different item was expected, and not the one that was actually put in there.

**Comment by nikitinalexx** [comment] 2020-07-30 12:12
More than that when some random items are put in such an ME Interface, ME interface would not put those items in the first slots available, it would even put them specifically into the slots that are expecting specific items to be crafted.
So for example you can see in slot 2 and 3 random tiny dusts, and in slot 8 random volumetric flask.
These 3 different items should have taken slot 1, 2, 3, and then be removed.
But what it did, it put them into slot 2,3 and 8, which makes no sense at all.

**Comment by repo-alt** [comment] 2020-07-30 15:27
This would explain both voiding and "stuck" items

**Comment by Prometheus0000** [comment] 2020-10-12 23:59
@repo-alt Is this and #6235 fixed now? And is it in 2.0.9.0 QF4 that has had people test it? Unlike 2.0.9.1a dev

**Comment by repo-alt** [comment] 2020-10-13 00:18
No idea, I was unable to reproduce the original issue, but I fixed the second issue that was easier to reproduce. I sent the jar to the user to test but never heard back. (And no, I have no idea if 2.0.9.0 QF4 was forked before the fix or after (Aug 27))

**Comment by nikitinalexx** [comment] 2020-11-23 18:28
Hi, @repo-alt I have been looking at my server for a couple of days, and it was pretty stably reproducing Before your fix.
But now after your fix I haven't met a single case of this bug being reproduced(and I have at least 2 different places to check).
So looks like your fix Does work.

**Comment by repo-alt** [comment] 2020-11-23 18:35
good

**Closed** 2020-12-03 21:32 UTC
Labels: Mod: AE2, Status: FixedInDev
