### ISSUE TITLE
Industrial information panel bug

### ISSUE THREAD

**Issue by LewisSaber** [GTNewHorizons/GT-New-Horizons-Modpack#8779] opened 2021-11-05 19:02 UTC
### Your GTNH Discord Username

Lewissaber#7231

### Your Pack Version

 2.1.1.4QF-2

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Expect to panel to show properly

### The Reality

panel bugs from time to time, today it bugged twice
text stays even if u break extenders,or disable panel
![image](https://user-images.githubusercontent.com/39595617/140564392-04d703cb-42d4-466c-b509-b905647b9500.png)
![image](https://user-images.githubusercontent.com/39595617/140564556-4fa59e31-1a25-4ad3-aa8f-b85fbbd9e377.png)

### Your Proposal

fix

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Savallator** [comment] 2021-11-08 20:22
Dupe of #8567

**Closed** 2021-11-08 20:25 UTC
Labels: Type: duplicate, Type: bugMinor, Type: visual
