### ISSUE TITLE
NEI says one thing machine outputs another - Stone Plates

### ISSUE THREAD

**Issue by BeardBois** [GTNewHorizons/GT-New-Horizons-Modpack#14489] opened 2023-09-10 16:59 UTC
### Your GTNH Discord Username

beardbois

### Your Pack Version

2.4.0

### Your Server

Private Server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

Stone plates recipe giving correct stone plates(GTNH core mod ones). Not the GT stone plates.

### The Reality

![2023-09-10_11 47 14](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/134227567/6a107c32-919b-4aff-8e37-92fcd366f047)
![2023-09-10_11 47 09](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/134227567/d9af8f06-03a3-4baf-86a6-94bd8bf73e03)

The photos above are what is happening and what its giving me.

### Your Proposal

Should be a simple recipe change. But it should be giving the GTNH core mod stone plate, as the other seems to have been removed. 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2023-09-10 17:08
make sure the script folders on both client and server are empty (outside of custom stuff you are adding)

**Comment by chochem** [comment] 2023-09-10 17:08
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14433

**Closed by chochem** 2023-09-10 17:08 UTC
Labels: Type: bugMinor, Status: Triage
