### ISSUE TITLE
Gas Satellite dimensions completely stops loading their chunks after server restart.

### ISSUE THREAD

**Issue by maniifestantes** [GTNewHorizons/GT-New-Horizons-Modpack#10657] opened 2022-07-07 19:11 UTC
### Your GTNH Discord Username

maniifestantes

### Your Pack Version

2.1.2.4-14-pre

### Your Server

zeta

### Your Expectation

Usually, you can use a teleposer to travel from one dimension to another, planets included.

### The Reality

But that seems to not happen with Sattelites (like jupiter's in this example). I can't teleport there unless i use the rocket (which makes the whole purpose of that teleposer almost null). The teleposer does work after travelling once, but once the server restarts, i have to travel there again by rocket to make it work. The reason for this is because the pumps also stop working until i visit there.

### Your Proposal

Before going to jupiter.
https://user-images.githubusercontent.com/57275066/177853289-1df88e3a-94e4-4b0c-8c0b-6fc18a993105.mp4

After going to Jupiter.
https://user-images.githubusercontent.com/57275066/177853310-b52c5dfe-b79a-44b8-b986-1ef4ec604e25.mp4
I haven't changed anything about the teleposer.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2022-07-07 19:13
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10512

**Closed** 2022-07-07 21:26 UTC
Labels: Type: Duplicate, Type: bugMinor, Status: Triage
