### ISSUE TITLE
Crash Upon Using a TC Tool/Weapon

### ISSUE THREAD

**Issue by garaiza-93** [GTNewHorizons/GT-New-Horizons-Modpack#12575] opened 2023-02-13 02:18 UTC
### Your GTNH Discord Username

nowaaaay#8573

### Your Pack Version

2.2.9 (modern java)

### Your Server

SP

### Type of Server

Single Player

### Your Actions

I had a TC Hammer in my hotbar. Crashed when switching to it or when I use it.
The crash mentioned that "Optifine is not supported. I am using [OptiFine_1.7.10_HD_U_E7](https://optifine.net/adloadx?f=OptiFine_1.7.10_HD_U_E7.jar&x=52ee)
![image](https://user-images.githubusercontent.com/57430880/218355951-d13e5685-3981-492b-be7b-c5c16cbd4786.png)

### Crash Report

https://paste.ubuntu.com/p/dxKym59Q3M/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Alexdoru** [comment] 2023-02-13 02:19
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12567

**Closed by Alexdoru** 2023-02-13 02:19 UTC
Labels: Type: Crash, Status: Triage
