### ISSUE TITLE
Thaumcraft greatwood leaves consumes a lot of server tick time

### ISSUE THREAD

**Issue by SKProCH** [GTNewHorizons/GT-New-Horizons-Modpack#16314] opened 2024-05-19 15:08 UTC
### Your GTNH Discord Username

skproch

### Your Pack Version

2.6.0

### Your Server

Private

### Java Version

Java 21

### Type of Server

Ultramine

### Your Expectation

Thaumcraft greatwood leaves shouldn't consume a lot of server resources

### The Reality

Thaumcraft greatwood leaves consumes a lot of server tick time. I've has a couple of greatwoods (5-6 trees) around the base and when i load chucks with greatwoods ty server tick time wents from 20 mspt to 50+ mspt.

Here is spark profiling:

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/29896317/7c9c9687-b522-4e7e-8fe3-8384ab54a377)

Seems like BlockMagicalLeaves.UpdateTick heavely check adjustment block of every leave block:

```java
   public void updateTick(World par1World, int par2, int par3, int par4, Random par5Random) {
      if(!par1World.isRemote) {
         int var6 = par1World.getBlockMetadata(par2, par3, par4);
         if((var6 & 8) != 0 && (var6 & 4) == 0) {
            byte var7 = 4;
            int var8 = var7 + 1;
            byte var9 = 32;
            int var10 = var9 * var9;
            int var11 = var9 / 2;
            if(this.adjacentTreeBlocks == null) {
               this.adjacentTreeBlocks = new int[var9 * var9 * var9];
            }

            if(par1World.checkChunksExist(par2 - var8, par3 - var8, par4 - var8, par2 + var8, par3 + var8, par4 + var8)) {
               for(int var12 = -var7; var12 <= var7; ++var12) {
                  for(int var13 = -var7; var13 <= var7; ++var13) {
                     for(int var14 = -var7; var14 <= var7; ++var14) {
                        Block block = par1World.getBlock(par2 + var12, par3 + var13, par4 + var14);
                        if(block != null && block.canSustainLeaves(par1World, par2 + var12, par3 + var13, par4 + var14)) {
                           this.adjacentTreeBlocks[(var12 + var11) * var10 + (var13 + var11) * var9 + var14 + var11] = 0;
                        } else if(block != null && block.isLeaves(par1World, par2 + var12, par3 + var13, par4 + var14)) {
                           this.adjacentTreeBlocks[(var12 + var11) * var10 + (var13 + var11) * var9 + var14 + var11] = -2;
                        } else {
                           this.adjacentTreeBlocks[(var12 + var11) * var10 + (var13 + var11) * var9 + var14 + var11] = -1;
                        }
                     }
                  }
               }

               int var15 = 0;

               for(int var12 = 1; var12 <= 4; ++var12) {
                  for(int var13 = -var7; var13 <= var7; ++var13) {
                     for(int var14 = -var7; var14 <= var7; ++var14) {
                        for(var15 = -var7; var15 <= var7; ++var15) {
                           if(this.adjacentTreeBlocks[(var13 + var11) * var10 + (var14 + var11) * var9 + var15 + var11] == var12 - 1) {
                              if(this.adjacentTreeBlocks[(var13 + var11 - 1) * var10 + (var14 + var11) * var9 + var15 + var11] == -2) {
                                 this.adjacentTreeBlocks[(var13 + var11 - 1) * var10 + (var14 + var11) * var9 + var15 + var11] = var12;
                              }

                              if(this.adjacentTreeBlocks[(var13 + var11 + 1) * var10 + (var14 + var11) * var9 + var15 + var11] == -2) {
                                 this.adjacentTreeBlocks[(var13 + var11 + 1) * var10 + (var14 + var11) * var9 + var15 + var11] = var12;
                              }

                              if(this.adjacentTreeBlocks[(var13 + var11) * var10 + (var14 + var11 - 1) * var9 + var15 + var11] == -2) {
                                 this.adjacentTreeBlocks[(var13 + var11) * var10 + (var14 + var11 - 1) * var9 + var15 + var11] = var12;
                              }

                              if(this.adjacentTreeBlocks[(var13 + var11) * var10 + (var14 + var11 + 1) * var9 + var15 + var11] == -2) {
                                 this.adjacentTreeBlocks[(var13 + var11) * var10 + (var14 + var11 + 1) * var9 + var15 + var11] = var12;
                              }

                              if(this.adjacentTreeBlocks[(var13 + var11) * var10 + (var14 + var11) * var9 + (var15 + var11 - 1)] == -2) {
                                 this.adjacentTreeBlocks[(var13 + var11) * var10 + (var14 + var11) * var9 + (var15 + var11 - 1)] = var12;
                              }

                              if(this.adjacentTreeBlocks[(var13 + var11) * var10 + (var14 + var11) * var9 + var15 + var11 + 1] == -2) {
                                 this.adjacentTreeBlocks[(var13 + var11) * var10 + (var14 + var11) * var9 + var15 + var11 + 1] = var12;
                              }
                           }
                        }
                     }
                  }
               }
            }

            int var12 = this.adjacentTreeBlocks[var11 * var10 + var11 * var9 + var11];
            if(var12 >= 0) {
               par1World.setBlock(par2, par3, par4, this, var6 & -9, 3);
            } else {
               this.removeLeaves(par1World, par2, par3, par4);
            }
         }
      }

   }
```

Here is code reconstruction:

```java
public void updateTick(World world, int x, int y, int z, Random random) {
    // Ensure this is not a client-side operation
    if (!world.isRemote) {
        int metadata = world.getBlockMetadata(x, y, z);

        // Check if the block needs updating and hasn't been updated already
        if ((metadata & 8) != 0 && (metadata & 4) == 0) {
            byte range = 4;
            int extendedRange = range + 1;
            byte areaSize = 32;
            int volume = areaSize * areaSize;
            int halfAreaSize = areaSize / 2;

            // Initialize the array for adjacent blocks if it hasn't been initialized yet
            if (this.adjacentTreeBlocks == null) {
                this.adjacentTreeBlocks = new int[areaSize * areaSize * areaSize];
            }

            // Check if all necessary chunks are loaded within the range
            if (world.checkChunksExist(x - extendedRange, y - extendedRange, z - extendedRange, x + extendedRange, y + extendedRange, z + extendedRange)) {
                
                // Populate the array with values based on the type of surrounding blocks
                for (int dx = -range; dx <= range; ++dx) {
                    for (int dy = -range; dy <= range; ++dy) {
                        for (int dz = -range; dz <= range; {
                            Block block = world.getBlock(x + dx, y + dy, z + dz);
                            if (block != null && block.canSustainLeaves(world, x + dx, y + dy, z + dz)) {
                                this.adjacentTreeBlocks[(dx + halfAreaSize) * volume + (dy + halfAreaSize) * areaSize + dz + halfAreaSize] = 0;
                            } else if (block != null && block.isLeaves(world, x + dx, y + dy, z + dz)) {
                                this.adjacentTreeBlocks[(dx + halfAreaSize) * volume + (dy + halfAreaSize) * areaSize + dz + halfAreaSize] = -2;
                            } else {
                                this.adjacentTreeBlocks[(dx + halfAreaSize) * volume + (dy + halfAreaSize) * areaSize + dz + halfAreaSize] = -1;
                            }
                        }
                    }
                }

                // Propagate values through the array to determine supported leaves
                for (int step = 1; step <= 4; ++step) {
                    for (int dx = -range; dx <= range; ++dx) {
                        for (int dy = -range; dy <= range; ++dy) {
                            for (int dz = -range; dz <= range; ++dz) {
                                if (this.adjacentTreeBlocks[(dx + halfAreaSize) * volume + (dy + halfAreaSize) * areaSize + dz + halfAreaSize] == step - 1) {
                                    if (this.adjacentTreeBlocks[(dx + halfAreaSize - 1) * volume + (dy + halfAreaSize) * areaSize + dz + halfAreaSize] == -2) {
                                        this.adjacentTreeBlocks[(dx + halfAreaSize - 1) * volume + (dy + halfAreaSize) * areaSize + dz + halfAreaSize] = step;
                                    }
                                    if (this.adjacentTreeBlocks[(dx + halfAreaSize + 1) * volume + (dy + halfAreaSize) * areaSize + dz + halfAreaSize] == -2) {
                                        this.adjacentTreeBlocks[(dx + halfAreaSize + 1) * volume + (dy + halfAreaSize) * areaSize + dz + halfAreaSize] = step;
                                    }
                                    if (this.adjacentTreeBlocks[(dx + halfAreaSize) * volume + (dy + halfAreaSize - 1) * areaSize + dz + halfAreaSize] == -2) {
                                        this.adjacentTreeBlocks[(dx + halfAreaSize) * volume + (dy + halfAreaSize - 1) * areaSize + dz + halfAreaSize] = step;
                                    }
                                    if (this.adjacentTreeBlocks[(dx + halfAreaSize) * volume + (dy + halfAreaSize + 1) * areaSize + dz + halfAreaSize] == -2) {
                                        this.adjacentTreeBlocks[(dx + halfAreaSize) * volume + (dy + halfAreaSize + 1) * areaSize + dz + halfAreaSize] = step;
                                    }
                                    if (this.adjacentTreeBlocks[(dx + halfAreaSize) * volume + (dy + halfAreaSize) * areaSize + (dz + halfAreaSize - 1)] == -2) {
                                        this.adjacentTreeBlocks[(dx + halfAreaSize) * volume + (dy + halfAreaSize) * areaSize + (dz + halfAreaSize - 1)] = step;
                                    }
                                    if (this.adjacentTreeBlocks[(dx + halfAreaSize) * volume + (dy + halfAreaSize) * areaSize + dz + halfAreaSize + 1] == -2) {
                                        this.adjacentTreeBlocks[(dx + halfAreaSize) * volume + (dy + halfAreaSize) * areaSize + dz + halfAreaSize + 1] = step;
                                    }
                                }
                            }
                        }
                    }
                }
            }

            // Check the central block in the array to determine if it is supported
            int centerValue = this.adjacentTreeBlocks[halfAreaSize * volume + halfAreaSize * areaSize + halfAreaSize];
            if (centerValue >= 0) {
                world.setBlock(x, y, z, this, metadata & -9, 3); // Update the block
            } else {
                this.removeLeaves(world, x, y, z); // Remove the block
            }
        }
    }
}
```

### Your Proposal

Probably mixin to remove (or optimize this logic). We also have a fast leaves decay as a mod and probably we don't need this logic inside a thaum. Also, probably other TC leaves affected too.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by HoleFish** [comment] 2024-05-19 15:11
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16092

**Closed by HoleFish** 2024-05-19 15:11 UTC
Labels: Type: bugMinor, Status: Triage
