### ISSUE TITLE
Memory leak causes crash on Linux

### ISSUE THREAD

**Issue by Morris-pi** [GTNewHorizons/GT-New-Horizons-Modpack#12056] opened 2022-12-21 12:07 UTC
### Your GTNH Discord Username

Mozzarella#4449

### Your Pack Version

2.2.3 and 2.2.0.0

### Your Server

SP

### Type of Server

Single Player

### Your Actions

Every time I play, after a while, it crashes with exit code 9. This is drastically sped up by loading chunks into memory.

I did some poking about that I detailed in a Reddit post [here](https://www.reddit.com/r/feedthebeast/comments/z7dusr/weird_ram_issues_with_gtnh_2200_on_linux_with/) 

As well as that, I have tried switching JVMs to OpenJ9 which didn't help

### Crash Report

[Uploading fml-client-latest.log…]()

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by boubou19** [comment] 2022-12-21 12:48
what's your ram allocated to the pack and how much ram do you have in total? Could just be linux terminating the program because you are close from saturating your system.

**Comment by Morris-pi** [comment] 2022-12-21 13:51
8192 MiB allocated, 16 GB in total, the other programmes plus OS takes up ~3GB. I have watched my memory usage slowly climb to 15 GB then closed GTNH and it instantly drops back down to 3/4 GB

**Comment by vovaksenov** [comment] 2022-12-24 10:45
Same on 2.2.7. I thought i just did something wrong. Also exceeds allocated memory over time. Both server and client. Have to restart every 1-2 hours basically, otherwise the client (and for some reason the launcher, multimc, too) instantly crashes with no crash report.

**Comment by Morris-pi** [comment] 2022-12-24 10:52
The launcher rarely crashes for me, which is weird because I use Prism Launcher, I have managed to get it to run for 6 hours without crashing; however I was just moving between storage and machines, doing crafting. With exploration, it will severely reduce how long I can run to, and if I move to a different dimension, it will rarely last 30 minutes before a crash. Not looking forward to properly exploring the Twilight Forest/Other planets.

**Comment by vovaksenov** [comment] 2022-12-24 11:04
The reason might be in that i am running both a client and a server on the same machine, and they have to share the 14GB of free ram. Consider that the memory is also leaking from two sources now, and it isnt really surprizing I cant play for 6 hours straight. The most important thing for me, is that despite also leaking memory, the server does not crash, because the client always crashes first, freeing up the memory. This way, i can just restart with all world data safe.

**Comment by Jan-Loettgen** [comment] 2022-12-24 12:24
I am also having this issue, same exit code, same issue with it happening more freuqently when I load alot of chunks. I am on Ubuntu, playing GTNH 2.2.3 I play on a hosted server, so I dont think this issue is due to running a sever and client on the same machine. 

Info:
16 GB of ram,
8 allocated to minecraft
Ubuntu

**Comment by Glease** [comment] 2022-12-24 12:45
We have recently identified a memory leak in craftpresence. try remove it and see if it helps.

**Comment by Morris-pi** [comment] 2022-12-24 14:07
Tried it, seemed to make no difference with or without CraftPresence

**Comment by vovaksenov** [comment] 2022-12-25 17:48
Might need further confirmation, but it seems I have found the cause. The pre-installed openjdk seems to be the culprit. Have been running on newly downloaded 8.351 for a few hours and it seems fine for me now.

**Comment by ColeTackett** [comment] 2023-01-01 07:43
> Exact same results on steam deck 16gb of ram with 1gb dedicated to the IGPU, usage will just climb until the entire OS crashes or if I'm lucky exit code 9. Windows machine seems to be garbage collecting correctly on same java versions.

**Comment by Neskuik34** [comment] 2023-01-04 23:10
I had the same problem and i think it is related to mesa and not the pack. I'm running arch on a Ryzen 3200g (using the integrated vega 8) with 16gb of ram, 6gb allocated to the pack. After some time the game would use more ram than allocated and the whole os ends up freezing. Tried multiple JVMs and nothing changed.
Then using mangohud i noticed that the game starts leaking when the video memory fills up. I had 1gb allocated, so i increased it to 3gb and it lasted a bit longer.
Then i found this in the mesa repo https://gitlab.freedesktop.org/mesa/mesa/-/issues/6140#note_1343133, so i compiled mesa changing the buffer size here https://gitlab.freedesktop.org/mesa/mesa/-/blob/main/src/mesa/vbo/vbo_save.h#L115. After this the vram usage seems to stabilize at around 2gb after some hours and i don't have any more leaks.

**Comment by LukasEins** [comment] 2023-01-04 23:50
I have the same problem running Arch 6.1.2 and openjdk 8.352 / 16gb ram (6 allocated) / Ryzen 5800x3d, after 1-2 hours my game just straight up freezes my entire computer. If I manage to close the game before this happens my ram usage stays at whatever I am actually using + what the game was using before. Tried removing mods / adding mods like FoamFix but nothing changed

**Comment by boubou19** [comment] 2023-01-04 23:58
Looks like it is way beyond the scope of the pack. I'm closing this.

**Closed by boubou19** 2023-01-04 23:58 UTC
Labels: Type: Not our Fault, Type: Crash, Type: Memory Leak

**Comment by kumquat-ir** [comment] 2023-01-05 21:27
Did a bit of testing on this:
Occurs on both openjdk 352 from the arch repos with default gc and adoptium 322 with g1gc

Leaked memory does *not* belong to the java process so it is not freed on quitting, but can be cleared *when the game is closed* with `sudo sh -c 'sync && echo 2 > /proc/sys/vm/drop_caches` (which synchronizes writes and then tells the kernel to clear some of its caches)

Since the pack loads in only a couple minutes for me, this isn't too much of an inconvenience, just quit the game and run that command when memory usage gets a bit too high (total system memory/swap usage can be monitored in-game with mangohud)

just an absolutely bizarre issue honestly

**Comment by kumquat-ir** [comment] 2023-02-01 04:56
This issue seems to have been fixed by mesa 22.3.4:
https://gitlab.freedesktop.org/mesa/mesa/-/commit/0f5c8c3dc35561f23a5383cb05075898942ce0c5
From minor testing (riding around on a horse for a while), vram usage caps out at about 7.5gb for me and is freed over time down to around 6.5gb, so this does solve the issue! (now just wait for your distro to package mesa 22.3.4)

**Comment by HidetaroTanaka** [comment] 2023-05-19 00:52
I had similar problem and I tried messing around java arguments, and it seems that java uses about 1.5~2 times bigger memory than allocated in Ubuntu. (In my case with 16GB RAM, allocating 6GB seems good)

btw, this memory leak happened not only in GTNH, so probably the fault of Ubuntu or Java?

**Comment by creepebucket** [comment] 2026-01-18 03:14
> This issue seems to have been fixed by mesa 22.3.4: https://gitlab.freedesktop.org/mesa/mesa/-/commit/0f5c8c3dc35561f23a5383cb05075898942ce0c5 From minor testing (riding around on a horse for a while), vram usage caps out at about 7.5gb for me and is freed over time down to around 6.5gb, so this does solve the issue! (now just wait for your distro to package mesa 22.3.4)

I'm using NVIDIA drivers and had same issue again. I tried switch to mesa drivers and it dident seems changing sonething, weird
