### ISSUE TITLE
Recipe for changing Asgard's dandelion

### ISSUE THREAD

**Issue by SafariXiu** [GTNewHorizons/GT-New-Horizons-Modpack#12926] opened 2023-03-17 06:01 UTC
### Your GTNH Discord Username

鄂木斯克间谍#9569

### Your Pack Version

2.3.0

### Your Proposal

Change the recipe for Asgard's dandelion so that it is linked to plant magic instead of being independent on the outside

改变阿斯加德的蒲公英的配方，让它与植物魔法联动而不是独立在外面

### Your Goal

It doesn't make sense that Asgard's dandelions can be crafted with just some Ingots of Infinity, so why do we need to create magic pools? It doesn't make sense that people only need to make a few dandelions to play through plant magic quickly

阿斯加德的蒲公英只需要一些无尽之锭就可以进行制作了，这并不合理，那我们为什么还需要创造魔力池?大家只需要制作几颗蒲公英就可以迅速玩完植物魔法了，这并不合理

### Your Vision

Change its recipe so that players can play Plant Magic normally from start to finish

把它的配方进行更改，让玩家可以从头到尾正常的游玩植物魔法

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this change please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members think it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by EnderProyects** [comment] 2023-03-21 13:12
Duplicate of this https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12454

**Closed** 2023-06-15 00:42 UTC
Labels: Type: Duplicate, Type: Suggestion, Status: Triage
