### ISSUE TITLE
Localisation for tips BetterLoadingScreen

### ISSUE THREAD

**Issue by boozzeeboom** [GTNewHorizons/GT-New-Horizons-Modpack#6385] opened 2020-07-14 05:22 UTC
#### Which modpack version are you using?
2.0.9.0qf4
#
#### If in multiplayer; On which server does this happen? 
private server
#
#### What did you try to do, and what did you expect to happen?
trying to ad RU localisation for tips at betterloadingscreen
#
#### What happened instead? (Attach screenshots if needed)
Get this
![2020-07-07_17-42-15](https://user-images.githubusercontent.com/21971234/87387285-d1f0d900-c5bb-11ea-9d6b-d99570febb39.png)

**Comment by Dream-Master** [comment] 2020-07-14 08:11
@jackowski626 any idea here ?

**Comment by MotiasF33** [comment] 2020-07-15 05:57
> 
> #### Which modpack version are you using?
> 
> 2.0.9.0qf4
> #### If in multiplayer; On which server does this happen?
> 
> private server
> #### What did you try to do, and what did you expect to happen?
> 
> trying to ad RU localisation for tips at betterloadingscreen
> #### What happened instead? (Attach screenshots if needed)
> 
> Get this
> ![2020-07-07_17-42-15](https://user-images.githubusercontent.com/21971234/87387285-d1f0d900-c5bb-11ea-9d6b-d99570febb39.png)

  ```
# What font texture to use? Special Cases:
    #  - If you use the Russian mod "Client Fixer" then change this to "textures/font/ascii_fat.png"
    # Note: if a resourcepack adds a font, it will be used by CLS. [default: textures/font/ascii.png]
    S:font=textures/font/ascii.png
```

**Comment by jackowski626** [comment] 2020-07-15 10:03
> ### $\.minecraft\config\Betterloadingscreen\betterloadingscreen.cfg
> 
> ```
> # What font texture to use? Special Cases:
>   #  - If you use the Russian mod "Client Fixer" then change this to "textures/font/ascii_fat.png"
>   # Note: if a resourcepack adds a font, it will be used by CLS. [default: textures/font/ascii.png]
>   S:font=textures/font/ascii.png
> ```

The problem is actually reading file w/o specifying file encoding. Dm me (jackowski626#0522) if you want the fixed jar. For instance, I can not say when the source code is going to be pushed.

**Comment by boozzeeboom** [comment] 2020-07-22 05:46
fix from @jackowski626 works correctly. thx much.

**Comment by Dream-Master** [comment] 2020-07-22 07:07
so long I see no code we let this open.

**Comment by jackowski626** [comment] 2020-09-11 18:06
Btw @Dream-Master you can close this, will make an issue less :)

**Comment by Dream-Master** [comment] 2020-09-11 18:10
Labled it and close it after release. @jackowski626 thanks

**Closed** 2020-09-21 21:06 UTC
Labels: FixedInDev, waiting for fix
