### ISSUE TITLE
Creeper: Evolved #919

### ISSUE THREAD

**Issue by Devtron3D** [GTNewHorizons/GT-New-Horizons-Modpack#5796] opened 2020-03-22 12:47 UTC
#### Which modpack version are you using?
2.0.8.3
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
I killed him ( found 3 of them so far to kill) and the quest will not detect
Creeper: Evolved #919

#
#### What happened instead? (Attach screenshots if needed)
![image](https://user-images.githubusercontent.com/3405825/77249730-92386700-6c43-11ea-83d9-32e2e57da84e.png)
![image](https://user-images.githubusercontent.com/3405825/77249741-a54b3700-6c43-11ea-8fb8-769d694beb3f.png)

#
#### What do you suggest instead/what changes do you propose?
Make the quest detect :)

**Comment by Impos913** [comment] 2020-03-22 12:50
It may be fixed in later versions

**Comment by chochem** [comment] 2020-03-22 12:54
Duplicate of #5346 

funwayguy (dev of bq) acknowledged that there is an issue with bq3. Possibly already be fixed in newer versions?

**Comment by Dream-Master** [comment] 2020-03-22 19:27
@Devtron3D can you test with 2.0.8.8 or 2.0.8.7?

**Closed** 2020-09-18 03:13 UTC
Labels: Betterquesting, bugMinor, duplicate, need to be tested
