### ISSUE TITLE
rainforest oak from GT++ doesn't work in cutting machine

### ISSUE THREAD

**Issue by KaneHart** [GTNewHorizons/GT-New-Horizons-Modpack#6753] opened 2020-10-03 18:21 UTC
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
MP/SP / Stone Legion
#
#### What did you try to do, and what did you expect to happen?
N/A
#
#### What happened instead? (Attach screenshots if needed)
N/A
#
#### What do you suggest instead/what changes do you propose?

So the Rainforest Oak is pretty much a Oak Tree that is nice and more lag friendly large lag. When you hand craft it into planks it works fine and converts into Oak Planks. But when you put them into the cutting machine they do not give you anything. They should give Oak Planks.

**Comment by Dream-Master** [comment] 2020-10-03 18:37
please report this on gt++ repo @KaneHart

**Comment by GTNH-Afx237v7** [comment] 2020-10-03 20:00
Duplicate of #4943

**Comment by Prometheus0000** [comment] 2020-10-03 20:02
Why do people constantly try to use rainforest oak? I've never even seen it, and redwoods are more than enough for me.

**Closed** 2020-10-03 20:01 UTC
Labels: Mod: GT++

**Comment by KaneHart** [comment] 2020-10-03 20:14
I have no clue why people use something that is available to them.....
