### ISSUE TITLE
Icongraphs in item frames are buggy

### ISSUE THREAD

**Issue by SteamDoge9000** [GTNewHorizons/GT-New-Horizons-Modpack#10596] opened 2022-07-01 01:42 UTC
### Your GTNH Discord Username

Shibva_

### Your Pack Version

2.1.2.3

### Your Server

NA

### Type of Server

Single Player

### Your Expectation

I was going about a village and found that some of them were brighter than normal, I remember this happening with even regular villagers outside of this pack and remember it being caused by the polaroid/iconographs being rendered in the time frames as you can see here
![image](https://user-images.githubusercontent.com/38770780/176805000-b535b564-51cb-45bf-b4c9-12f26ad81ee9.png)
(even the frame is being affected by it; the one that's darker is behaving as it should)

### The Reality

its glowing when it shoudnt and in turn causing entities nearby to glow as well if your looking in its direction

### Your Proposal

modify the structure geneating by doing 1 of 2 things 

1. remove the structure entirely
2. remove the item frames period and have a chest upstairs instead containing 3 randomly generated icongraphs; eliminating the rendering issue

3. the hard way would be to fix the rendering issue caused by them period, but that is more work than what its worth if we are being realistic here

Note: this issue can easily be recreated without a village structure, just have an iconograph image taken with anything and put it in an item frame

[note: this was originally thought to be a world-bricking bug but turned out I was being trolled, so this report is to report the visual bug like I was going todo before the troll to spite them]

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by SteamDoge9000** [comment] 2022-07-01 01:43
it should also be noted that this bug existed before any possible modification where made by the GTNH group, this was a thing in the normal Witching Gadgets as well

**Comment by SteamDoge9000** [comment] 2022-07-02 00:31
Corrected name, [force of habbit doing this sort of thing]

**Comment by YannickMG** [comment] 2022-07-02 00:40
The third fix is probably the only fix worth doing, given that this has literally no negative gameplay impact.

**Comment by SteamDoge9000** [comment] 2022-07-02 12:21
one person said it might be some GLstate forgetting to be delt with since its a custom model

**Comment by SteamDoge9000** [comment] 2022-07-02 12:26
its in github discussion, youll be fortunate if you find the convo

**Comment by eigenraven** [comment] 2022-07-10 17:34
Duplicate of #8376

**Closed by eigenraven** 2022-07-10 17:34 UTC
Labels: Type: bugMinor, Type: Visual
