### ISSUE TITLE
Wireless crafting terminal, has major server lag issues when batch crafting

### ISSUE THREAD

**Issue by Devtron3D** [GTNewHorizons/GT-New-Horizons-Modpack#6407] opened 2020-07-19 09:14 UTC
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
Prospercraft
#
#### What did you try to do, and what did you expect to happen?
I was using the wireless crafting terminal (7283), the one that can be upgraded infinity booster card
Crafting 9 tiny dust into 1 normal dust with shift click

#
#### What happened instead? (Attach screenshots if needed)
I got the dust converted already, but not before kicking everyone off the server doing it
redid tests, 10+ stacks with shift click to make them and it will kick everyone off the server
5 stacks made and it will lag for around 20 seconds
#
#### What do you suggest instead/what changes do you propose?
Was talking in zeta chat about this issue and its an old known one that had issues before.
I was told that it was fixed with other crafting grids and missed on this one
Would suggest a fix or ban the item, as it causes major lag and or kick of players (I got everyone kicked with a test)

**Comment by ivelieu** [comment] 2020-07-19 09:48
#5163
Issue is Wireless Crafting Terminal code was not updated.  Fixed in WCT versions 1.12.2 and 1.10.2. Something like https://github.com/p455w0rd/WirelessCraftingTerminal/commit/12bb59f3943d8d9799c368a945523c1f0fd13417

Maybe we will get wildcard support too? I know it's not an easy fix though.

**Comment by repo-alt** [comment] 2020-07-20 12:26
What wildcard support?

**Comment by ivelieu** [comment] 2020-07-20 13:45
![image](https://user-images.githubusercontent.com/28797826/87943679-ba48b180-cae1-11ea-8c82-d603e1294d56.png)

As in #5163 by richardhendricks:
> another option is to figure out how to tell if the recipe has wildcards, and never move/cache those.

Here it is:
			```final boolean checkFuzzy = ae_req.isOre() || providedTemplate.getItemDamage() == OreDictionary.WILDCARD_VALUE || providedTemplate.hasTagCompound() || providedTemplate.isItemStackDamageable();```
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/f558e64ef99d8ce49ad350c36614e82934355141/src/main/java/appeng/util/Platform.java#L1836

**Comment by repo-alt** [comment] 2020-07-20 14:07
That was about global cache. WCT optimization is done in GUI container essentially.

**Comment by Cleista** [comment] 2020-07-20 19:06
The problem isn't exclusive to the WCT. Try shift-clicking tiny dust crafts in a regular crafting terminal. If you click too fast it freezes the server.

**Comment by repo-alt** [comment] 2020-07-20 19:27
wut, it was fixed quite a while ago

**Closed** 2020-09-21 21:06 UTC
Labels: FixedInDev, Lag
