### ISSUE TITLE
ME Fluid Terminal Unlimited Brush Material

### ISSUE THREAD

**Issue by RiderisPr** [GTNewHorizons/GT-New-Horizons-Modpack#13305] opened 2023-04-24 04:09 UTC
### Your Pack Version

2.3.2

### Your Server

private server

### Java Version

Java 8

### Type of Server

None

### Your Expectation

hope to fix this bug. using this bug in EV or IV stage can easily get titanium and Tungsten steel ingot by making large units.

### The Reality

Fill the empty cell with a fluid,  but not consumed instead of one more cell to be filled.this can easily get titanium and Tungsten steel ingot by making large units in EV or IV stage.
![InkedQQ截图20230424120353](https://user-images.githubusercontent.com/114299480/233897759-9d8f4caf-23e2-4843-967a-3992d0162bf9.jpg)
![InkedQQ截图20230424120630](https://user-images.githubusercontent.com/114299480/233897875-31777b9b-0611-4d7e-88c8-afee9e1acda0.jpg)

### Your Proposal

hope repair

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by firenoo** [comment] 2023-04-24 04:17
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13177

**Closed by firenoo** 2023-04-24 04:17 UTC
Labels: Type: bugMinor, Status: Triage
