### ISSUE TITLE
Duke Mix'Em only works with vanilla (and biomes o plenty) music discs

### ISSUE THREAD

**Issue by KiwiLT** [GTNewHorizons/GT-New-Horizons-Modpack#18456] opened 2024-12-20 17:49 UTC
### Your GTNH Discord Username

KiwiLT#1907

### Your Pack Version

2.7.0

### Your Server

SP

### Java Version

Java 21

### Type of Server

Don't know

### Your Expectation

I expect any music disc that works in the vanilla minecraft juke box to also work in the Duke Mix'Em 3D and the other electric jukeboxes

### The Reality

The most awesome music disc of all time (botania boss music) is completely silent in Duke Mix'Em 3D. I tested the EV Jukebox too, it has the same problem. The Hardcore Ender Expansion music discs all have the same problem too. The Biomes O Plenty music discs do work tho.

### Your Proposal

Would be cool if all musics discs that work in the vanilla jukebox also work in the electric jukeboxes, instead of only vanilla and Biomes O plenty music.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by FourIsTheNumber** [comment] 2024-12-20 17:55
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/18055
Fixed by https://github.com/GTNewHorizons/GT5-Unofficial/pull/3628

**Closed by FourIsTheNumber** 2024-12-20 17:55 UTC
Labels: Bug: Minor, Status: Triage
