### ISSUE TITLE
stocking bus only exposes a stack to the Integrated Processing Factory

### ISSUE THREAD

**Issue by boubou19** [GTNewHorizons/GT-New-Horizons-Modpack#11490] opened 2022-09-30 17:14 UTC
### Your GTNH Discord Username

boubou_19

### Your Pack Version

2.2.0.0

### Your Server

delta

### Type of Server

Thermos

### Your Expectation

I expected to have a x1024 parallelism on my ore processing factory, so i could use the stocking bus to treat my items without any actual item movement.

### The Reality

the reality is that despite having a of 31M of tungsten ore, it only treats the ore as if it had only 64 items. I tried to add multiple times the ore in the slots, but looks like it only accepts a different item per stocking slot.

### Your Proposal

add an explicit compat for the stocking bus, otherwise it clearly defeats the point to have the stocking bus.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by boubou19** [comment] 2022-09-30 17:20
might be a good idea to override this https://github.com/GTNewHorizons/GT5-Unofficial/blob/3c7a1788d733ddf39061c6ceb6254dfc5b1ef3b8/src/main/java/gregtech/api/metatileentity/implementations/GT_MetaTileEntity_MultiBlockBase.java#L946-L960
to add the compat for the stocking bus inputs. Or even better, update it in the base class.

**Comment by shekurika** [comment] 2022-10-02 12:31
In addition to this, the IOP seems to pull 16 stacks of ore correctly out of the ME via the Stocking Bus, then processes one stack and voids the other 15

**Comment by joshaup1999** [comment] 2022-10-15 20:43
Any fix for this as of yet?

**Comment by Sphyix** [comment] 2022-10-20 23:55
this is broken only on the ore processing factory as of now, stocking input bus works fine on multi smelter and mega lcr

**Comment by repo-alt** [comment] 2022-12-01 15:11
hmm, I could not reproduce that in dev env. Stepped through recipe processing and it does handle stacks of arbitrary sizes just fine

**Closed** 2022-12-15 14:46 UTC
Labels: Type: bugMinor, Status: Can't Reproduce, Mod: GT
