### ISSUE TITLE
Twilight Forest NagaStone getOrdinal Crash Server 2.6.1

### ISSUE THREAD

**Issue by DrZed** [GTNewHorizons/GT-New-Horizons-Modpack#16418] opened 2024-05-29 23:13 UTC
### Your GTNH Discord Username

@KeldonSlayer

### Your Pack Version

2.6.1

### Your Server

private server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Actions

First entered Twilight Forest, Walked about 50 blocks, Crashed Server, repeated 3 times.

### Crash Report

java.lang.NullPointerException: Cannot invoke "twilightforest.block.BlockTFNagastone2$Yaw.ordinal()" because "facing" is null
	at RFB-Launch//twilightforest.block.BlockTFNagastone2.GetMetadata(BlockTFNagastone2.java:639)

java.lang.NullPointerException: Cannot invoke "net.minecraftforge.common.util.ForgeDirection.ordinal()" because "this.EtchedNagastoneNorth" is null
	at RFB-Launch//twilightforest.structures.courtyard.ComponentTFNagaCourtyardWall.func_74875_a(ComponentTFNagaCourtyardWall.java:576)
[crash-2024-05-30_01.06.24-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15491664/crash-2024-05-30_01.06.24-server.txt)
[crash-2024-05-30_00.57.56-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15491665/crash-2024-05-30_00.57.56-server.txt)
[crash-2024-05-30_01.00.53-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15491666/crash-2024-05-30_01.00.53-server.txt)
[crash-2024-05-30_01.04.08-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15491667/crash-2024-05-30_01.04.08-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2024-05-29 23:17
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16353.
see there for fix.

**Closed by chochem** 2024-05-29 23:17 UTC
Labels: Type: Crash, Status: Triage
