### ISSUE TITLE
All repeatable quests are stuck up to rejoin to server

### ISSUE THREAD

**Issue by Askara** [GTNewHorizons/GT-New-Horizons-Modpack#11712] opened 2022-10-22 17:10 UTC
### Your GTNH Discord Username

Marginalines/Zefiroid#4621

### Your Pack Version

2.2.3.0

### Your Server

Zvezdolet

### Type of Server

Ultramine

### Your Expectation

I'm completing any repeatable quest and waiting to complete it once more time. 

### The Reality

All repeatable quests are stuck in COMPLETE condition up to rejoin to server. 

Example for buying sticky resin

![photo_2022-10-22_20-04-08](https://user-images.githubusercontent.com/2502760/197353291-9fcf8d14-f4c9-4f96-8f3e-b5ba29449f5b.jpg)

![photo_2022-10-22_20-05-41](https://user-images.githubusercontent.com/2502760/197353288-ae7a4371-bdd7-47f5-962c-af53e25ed076.jpg)
 
 ![photo_2022-10-22_20-06-09](https://user-images.githubusercontent.com/2502760/197353300-b2dcd6e7-de94-4a8f-abaa-5fa5662260b6.jpg)
 
 ![photo_2022-10-22_20-06-22](https://user-images.githubusercontent.com/2502760/197353296-a9356d98-5ad9-4aed-9e64-801ad3626ba9.jpg)
 
![photo_2022-10-22_20-06-36](https://user-images.githubusercontent.com/2502760/197353280-ae90843e-9e0c-40fb-a960-6b410e36cbeb.jpg)

### Your Proposal

It's not a good condition =(

The same thing is on Official servers too

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment] 2022-10-22 18:33
Duplicate of #10294

**Closed by Glease** 2022-10-22 18:33 UTC
Labels: Type: bugMinor, Status: Triage
