### ISSUE TITLE
crash when shift clicking into recently opened machine

### ISSUE THREAD

**Issue by toaster-god** [GTNewHorizons/GT-New-Horizons-Modpack#17427] opened 2024-09-23 02:53 UTC
### Your GTNH Discord Username

Rat/toastergod.

### Your Pack Version

2.7 beta 1

### Your Server

SP

### Java Version

Java 21

### Type of Server

Single Player

### Your Actions

opening a GT machine and shift clicking something into the menu sometimes, and fairly commonly, causes an immediate crash.
I can't say much more as I haven't been able to recreate it purposefully, but its happened to me 3 or 4 times within an hour.

### Crash Report

[crash-2024-09-22_22.44.33-client.txt](https://github.com/user-attachments/files/17092293/crash-2024-09-22_22.44.33-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment] 2024-09-23 03:17
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17401

**Closed by miozune** 2024-09-23 03:17 UTC
Labels: Type: Crash, Status: Triage
