### ISSUE TITLE
less efficiency, more power 

### ISSUE THREAD

**Issue by RaitGamerGR** [GTNewHorizons/GT-New-Horizons-Modpack#12166] opened 2023-01-01 10:44 UTC
### Your GTNH Discord Username

Rait_GamerGR(Александр)#5721

### Your Pack Version

2.2.8

### Your Server

Private Server

### Type of Server

Ultramine

### Your Expectation

Trying to use new waila feature. 100% efficient = full generated power, less efficient = less power.

### The Reality

100% efficient = 100% power;
Less efficient = more then 100% power showed.
![2022-12-30_23 06 33](https://user-images.githubusercontent.com/70205464/210167917-4224e604-5026-4812-a638-11b8da5019e4.png)
![2022-12-30_23 06 31](https://user-images.githubusercontent.com/70205464/210167921-2010c962-867d-4857-93fb-887181042da8.png)
![2023-01-01_11 29 25](https://user-images.githubusercontent.com/70205464/210167928-c0f88602-0d1c-47e4-a988-63944f5edafb.png)
![2023-01-01_11 29 28](https://user-images.githubusercontent.com/70205464/210167943-49b6948b-0e8d-4113-813c-921baf227dec.png)
![2023-01-01_11 29 33](https://user-images.githubusercontent.com/70205464/210167934-670c03fc-dcde-4c8a-af4a-6520f6b03ff9.png)

### Your Proposal

100% efficient = 100% power;
Less efficient = real generetad power.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2023-01-01 12:01
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12145

**Closed by chochem** 2023-01-01 12:01 UTC
Labels: Type: bugMinor, Status: Triage
