### ISSUE TITLE
NPE in gtPlusPlus recipe handler

### ISSUE THREAD

**Issue by bombcar** [GTNewHorizons/GT-New-Horizons-Modpack#9089] opened 2021-12-13 22:31 UTC
### Your GTNH Discord Username

bombcar#1042

### Your Pack Version

2.1.2.0rc

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Don't NPE

### The Reality

```
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.NullPointerException
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gtPlusPlus.core.util.minecraft.RecipeUtils$InternalRecipeObject.run(RecipeUtils.java:577)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gtPlusPlus.core.handler.COMPAT_HANDLER.runQueuedRecipes(COMPAT_HANDLER.java:282)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gtPlusPlus.core.common.CommonProxy.postInit(CommonProxy.java:170)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gtPlusPlus.core.proxy.ClientProxy.postInit(ClientProxy.java:108)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at gtPlusPlus.GTplusplus.postInit(GTplusplus.java:206)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.main.Main.main(SourceFile:148)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
[16:28:08] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at org.multimc.EntryPoint.main(EntryPoint.java:34)
```

### Your Proposal

Everything still appears to load, so I suspect something is being done twice or an expected item is missing.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Glease** [comment] 2021-12-13 22:33
As alk said, this can be literally everything. Also, duplicate of #8956

**Comment by draknyte1** [comment] 2021-12-13 22:33
Could literally be any auto generated material recipe. Turn all logging on and see if that helps.

**Closed** 2021-12-13 22:33 UTC
Labels: Type: bugMinor, Mod: GT++, Status: Triage
