### ISSUE TITLE
Server gets stuck in infinite loop after 1 second with exception

### ISSUE THREAD

**Issue by ParagonX42** [GTNewHorizons/GT-New-Horizons-Modpack#11797] opened 2022-11-05 12:37 UTC
### Your GTNH Discord Username

᲼᲼᲼᲼᲼᲼#3520

### Your Pack Version

2.2.3

### Your Server

Private

### Your Actions

1. launch the server
2. wait for it to start the world and load the chunks
3. join the server (or not, doesn't matter)
4. server throws an exception
5. timed out permanently

### Crash Report

Don't have valid logs any more as I tried to manually update mods to solve the issue but the exception is
> [13:09:58] [Server thread/INFO] [STDOUT]: [com.glodblock.github.coremod.FCClassTransformer:transform:38]: [AE2FC] Transforming class: appeng.crafting.CraftingTreeNode
> [13:09:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.util.NoSuchElementException
> [13:09:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at com.google.common.collect.Iterators$5.next(Iterators.java:550)
> [13:09:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at gtPlusPlus.xmod.gregtech.common.tileentities.machines.basic.GT_MetaTileEntity_CropHarvestor.onPostTick(GT_MetaTileEntity_CropHarvestor.java:268)
> [13:09:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at gregtech.api.metatileentity.BaseMetaTileEntity.func_145845_h(BaseMetaTileEntity.java:536)
> [13:09:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at net.minecraft.world.World.func_72939_s(World.java:1939)
> [13:09:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:1145)
> [13:09:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
> [13:09:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
> [13:09:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
> [13:09:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
> [13:09:59] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:749]:         at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

After this there's an infinite timeout

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by kuba6000** [comment] 2022-11-05 16:12
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11613

**Closed by kuba6000** 2022-11-05 16:12 UTC
Labels: Type: Crash, Status: Triage

**Comment by ParagonX42** [comment] 2022-11-09 07:40
[crash-2022-11-09_08.35.44-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9968540/crash-2022-11-09_08.35.44-server.txt)

**Comment by ParagonX42** [comment] 2022-11-09 07:40
Server gets stuck in infinite loop after this message
![image](https://user-images.githubusercontent.com/55181234/200768248-a509745e-ffe5-4270-b08f-753ba0dcefa5.png)

**Comment by ParagonX42** [comment] 2022-11-09 09:16
Updating ae2fc to 1.0.29 did not fix the problem

**Comment by GlodBlock** [comment] 2022-11-09 09:27
what is your current using ae's version?

**Comment by GlodBlock** [comment] 2022-11-09 09:31
btw the crash report you provided shows it's a lp issue instead of ae2. it seems that there is a dead loop in it

**Comment by ParagonX42** [comment] 2022-11-09 09:36
Currently using ae2fc-1.7.10-1.0.22-gtnh

The crash report may not be related to the issue. We don't have any logisticspipes but we do have thaumcraft. Either way every morning there's the issue that server is stuck and we have to restart it like 20 times for it to finally work

**Comment by GlodBlock** [comment] 2022-11-09 09:44
what's ae2fc devices are you using now? like a fluid export bus with a crafting card

**Comment by ParagonX42** [comment] 2022-11-09 09:45
Nope, no fluid export buses. 
We're using dual interfaces, fluid storage buses, fluid processing terminal, fluid terminal, packet decoder, fluid discretizer.

The source of this issue seems to be this translucer
![image](https://user-images.githubusercontent.com/55181234/200796810-7defb9c3-db92-4749-aeec-94f3aaa91a97.png)

**Comment by ParagonX42** [comment] 2022-11-14 21:42
[crash-2022-11-14_22.38.19-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/10007341/crash-2022-11-14_22.38.19-server.txt)

**Comment by Divran** [comment] 2022-11-18 20:55
the crash happens very often when we change ae shit, for example it's crashed twice in a row now when I tried to add more ME Drives. so it most likely has something to do with ae

**Comment by GodlyIdea** [comment] 2022-11-20 17:45
In local machine ran the world as server and when server froze hooked into the server VM with WarmRoast tool and it showed that the VM was stuck in method:
>appeng.hooks.TickHandler.onTick()
>appeng.me.Grid.update()
>appeng.me.GridCacheWrapper.onUpdateTick()
>appeng.me.cache.PathGridCache.onUpdateTick()
>appeng.me.pathfinding.PathSegment.step()
>appeng.me.pathfinding.PathSegment.useChannel()
Our suspicion is that backbone cables caused the issue as sometimes it failed to connect all things through backbone cables.
We didn't try to remove all backbones to see if server got stuck again as we achieved infinitive AE power source so we switched directly to wireless and server don't get stuck anymore.
