### ISSUE TITLE
Sticky card on fluid storage bus causes ongoing crafts to ignore that fluid type pushed in

### ISSUE THREAD

**Issue by Spartends** [GTNewHorizons/GT-New-Horizons-Modpack#17180] opened 2024-09-02 07:29 UTC
### Your GTNH Discord Username

Spartends

### Your Pack Version

2.6.1

### Your Server

private

### Java Version

Java 17

### Type of Server

None

### Your Expectation

Thought sticky card would just prevent fluid from entering the system if the attached super tank is full.

### The Reality

This functionality works, but the bug is that the ongoing crafts will not grab that fluid as it is being pushed into the system. Even though the tank is not even full. 

### Your Proposal

n/a

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by hiroscho** [comment] 2024-09-02 16:41
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16152

![image](https://github.com/user-attachments/assets/d46acb87-e19e-4ff9-a071-a6a271ee6def)

**Closed** 2024-09-03 04:07 UTC
Labels: Type: bugMinor, Status: Triage
