### ISSUE TITLE
Multiblock Combustion Engine causes lag

### ISSUE THREAD

**Issue by Flexy07** [GTNewHorizons/GT-New-Horizons-Modpack#6017] opened 2020-05-01 14:19 UTC
#### Which modpack version are you using?
2.0.8.8

#
#### If in multiplayer; On which server does this happen? 
I play with my friend using Hamachi
#
#### What did you try to do, and what did you expect to happen?
When we set the multiblock combustion engine up,I started having insane lag on the server,for example when I open the Applied Energistics system to request an item,I never get the item and the lag is so insane that the clock starts to rewing by itself so I have to disconnect every single time.I stopped the multiblock combustion engine and the lag is decreased,we have over %50 FPS increase and now I can use the AE2 system without any problems.

#
#### What happened instead? (Attach screenshots if needed)

#
#### What do you suggest instead/what changes do you propose?
Maybe add another choice to power EV machines,like adding EV combustion engine? Idk but the lag is really frustrating.

**Comment by draknyte1** [comment] 2020-05-01 14:32
Could you try use VisualVM and profile your server? It’s *realllllly* doubtful it’s the multiblock.

**Comment by Flexy07** [comment] 2020-05-04 15:57
I don't have any idea how to use VisualVM,just downloaded it.But I tested it a few times with my friend.The problem really is the combustion engine.

**Comment by draknyte1** [comment] 2020-05-04 16:03
Use google, there’s many guides to cpu sampling.. 🤦🏻‍♀️

**Comment by mitchej123** [comment] 2020-05-04 16:34
> I won't prove it, but my theory is definitely right

Please provide evidence and we'll definitely get it fixed.  Otherwise you're asking devs to go on a wild goose chase.  If we can't reproduce it, or see it, we can't fix it.  Run visualvm like asked, provide the logs, and then it'll be less of a needle in a haystack.

**Comment by Flexy07** [comment] 2020-05-05 14:05
Okay so,the combustion engine wasnt the problem,the problem was that we give lubricant/oxygen to the combustion with AE2 cables,and for some reason when we gave those fluids with gregtech pipes the problem resolved.So the problem belongs to AE2.You asked me to run visualVM but me and my friend really have no idea,don't forget that I'm not some kind of a pro programmer or something,so I couldnt do what you asked.I managed to do the cpu sampling part but I have no idea where the logs are saved so I cannot provide it if you will not be helpful.Thank you.

**Comment by Glease** [comment] 2020-05-05 14:12
ExtraCells 2's fluid export bus is known to be lag intensive. Sadly we haven't come up with a fix so far.

**Comment by mitchej123** [comment] 2020-05-05 16:20
Thanks for tracking down the root cause.  As for visualvm, you should learn - it's very helpful: https://engineering.talkdesk.com/ninjas-guide-to-getting-started-with-visualvm-f8bff061f7e7. Here's one such tutorial on interpreting it.

**Comment by eigenraven** [comment] 2022-07-07 14:13
The export bus now ticks much more rarely, should be fixed in dev.

**Closed by eigenraven** 2022-07-07 14:13 UTC
Labels: Type: Lag, Mod: EC2
