### ISSUE TITLE
journeymap map is blank upon joining server until dimension change

### ISSUE THREAD

**Issue by Hiagg** [GTNewHorizons/GT-New-Horizons-Modpack#13955] opened 2023-07-15 02:07 UTC
### Your Pack Version

2.3.4 nightly (idk which)

### Your Server

bee run

### Java Version

Java 17

### Type of Server

None

### Your Expectation

map works when you join

### The Reality

you have to change dimensions every time you log in to see the minimap in any form, including fullscreen map

every bee runner has this problem at least

### Your Proposal

fix ty

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Hekkmac** [comment] 2023-07-16 14:24
Thank you for reporting this. We have the same problem. Even with Java 8.

**Comment by wlhlm** [comment] 2023-07-16 14:27
@Hekkmac Which GTNH/JM version are you on?

**Comment by iskorp** [comment] 2023-08-18 04:26
Confirmed still affecting worlds on 2.3.6B / 1.8 JVM
Thank you

**Comment by Hekkmac** [comment] 2023-12-29 12:10
Still happening on 2.5.1

**Comment by boubou19** [comment] 2023-12-29 12:20
what's your server brand? do you have custom mods/plugins? does it happen when you remove those if you have any?

**Comment by Hekkmac** [comment] 2023-12-29 12:32
Intel® Xeon® E-2234 Coffee Lake | 4 x 3,6 GHz (4C/8T)                                  
2 x 512 GB NVMe SSD Software Raid 1 | 32 GB DDR4 ECC RAM
Ubuntu 22.04.2 LTS
JDK 21 (Official Oracle), but all others too.

Simple server package from GTNH, only ServerUtils added, but it also happend without ServerUtils.
I can provide World Backup over discord pm.

**Comment by Ableytner** [comment] 2024-02-25 18:26
This seems to be a journeymap / personalspace issue.

I have the same issue on 2.5.1, but only if I join a server where i am in the personal dimension. Joining in the overworld/twilight forest, it works as expected. 

After a bit more testing, the bug also occurs with only
* journeymap-1.7.10-5.1.4p6-fairplay (GTNH 2.5.1)   /   journeymap-1.7.10-5.1.4p7-fairplay (latest)
* personalspace-1.0.30 (latest)

being loaded. 

In singleplayer, everything works fine.

**Comment by Caedis** [comment] 2024-02-29 09:20
Issue has been found and its in minecraft itself.

The player is sent a S01PacketJoinGame packet only when they first connect that contains the dimension id that Journeymap then uses to determine what map to use.

The default dimension id is 180 and the packet stores the dimension id in a signed byte, -128 to 127. This overflows the byte so dimension 180 becomes -76.

A fix is in progress.

**Closed** 2024-02-29 20:47 UTC
Labels: Type: bugMinor, Status: Triage, Mod: JourneyMap
