### ISSUE TITLE
Fluid Drilling Rig stops working with two energy hatches.

### ISSUE THREAD

**Issue by AbdielKavash** [GTNewHorizons/GT-New-Horizons-Modpack#14200] opened 2023-08-10 22:57 UTC
### Your GTNH Discord Username

abdiel_kavash

### Your Pack Version

2.3.6

### Your Server

SP

### Java Version

Java 19

### Type of Server

Single Player

### Your Expectation

Built an Oil/Gas/Fluid Drilling Rig II, placed it in the overworld on an oil field of some size. Used two HV energy hatches to overclock it to EV. Connected both hatches to a debug power generator set to 8A HV connected with superconductor wires. Expected fluid to come out.

### The Reality

Machine shuts down after a few seconds, presumably due to power failure.

Using a singular HV hatch works normally, using a single EV hatch properly overclocks and runs normally too.

I haven't tested different tiers of drilling rigs or different hatches.

### Your Proposal

Allow the drilling rig to use two energy hatches of tier N and 4A of power to overclock to tier N+1 as usual for other multiblocks.

Alternatively, if this is not allowed by design, mention it in the controller's tooltip and make the multiblock not form with more than one energy hatch.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Pxx500** [comment] 2023-08-13 19:26
The multiblock doesn't need EV power only, it also needs an EV hatch, works as intended.
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/81298696/58db470a-ddde-40d4-95bb-19a836586ef6)

**Comment by AbdielKavash** [comment] 2023-08-13 21:27
No, this is the T2 rig, which needs HV power. It runs with one HV hatch fine, as I wrote in the post.

I can try other tiers with other hatches if needed.

**Comment by BritishCynic** [comment] 2023-08-13 21:30
The multiblock only accepts one hatch for power.

I'm reopening this issue as I don't agree that this restriction should apply to a multiblock that is structurally the same as another multiblock that does accept two hatches for power.

**Comment by chochem** [comment] 2023-08-13 21:55
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13566

**Closed** 2023-08-13 21:55 UTC
Labels: Type: Duplicate, Type: bugMinor, Type: Balancing, Mod: GT
