### ISSUE TITLE
some GUI's are stretched down to the bottom left

### ISSUE THREAD

**Issue by NovashieId** [GTNewHorizons/GT-New-Horizons-Modpack#16168] opened 2024-05-05 01:08 UTC
### Your GTNH Discord Username

Novashields

### Your Pack Version

2.6.0

### Your Server

private server

### Java Version

Java 8

### Type of Server

Don't know

### Your Expectation

The gui works normaly and does not look weird

### The Reality

when I open certain GUI's like control's the texture gets dragged down to the bottom left corner and covers alot of elements
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/168942771/98676487-4ef9-4164-9f41-6dcf2f983c45)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/168942771/979058af-d0a1-4c34-b323-d94fcc62adad)

### Your Proposal

I would like help finding out how to fix the problem

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2024-05-05 10:49
duplicate of https://github.com/GTNewHorizons/Angelica/issues/185

**Comment by chochem** [comment] 2024-05-05 10:50
you could update angelica to https://github.com/GTNewHorizons/Angelica/releases/tag/1.0.0-alpha42 if you want to.

**Closed by chochem** 2024-05-05 10:49 UTC
Labels: Type: bugMinor, Status: Triage
