### ISSUE TITLE
NPE resulting in server crash from pattern/crafting recipe in 2.7.0 beta3

### ISSUE THREAD

**Issue by xkuyax** [GTNewHorizons/GT-New-Horizons-Modpack#17805] opened 2024-10-29 19:17 UTC
### Your GTNH Discord Username

xkuyax

### Your Pack Version

2.7.0 beta-3

### Your Server

private server

### Java Version

Java 21

### Type of Server

Don't know

### Your Actions

Auto happens as soon as the server starts, was previously working on the 2.6
I added a pattern for Leach Residue and crafted 2k of them, and now the server crashes on boot as soon as the ME finishes loading

### Crash Report

The server is running the beta pack, its self hosted on pterodactyl 

```
[19:05:31] [Server thread/INFO]: Starting minecraft server version 1.7.10
[19:05:49] [Server thread/INFO]: Loading properties
[19:05:49] [Server thread/INFO]: Default game type: SURVIVAL
[19:05:49] [Server thread/INFO]: Generating keypair
[19:05:49] [Server thread/INFO]: Starting Minecraft server on 0.0.0.0:26667
[19:06:17] [Server thread/INFO]: Preparing level "World"
[19:06:18] [Server thread/INFO]: Preparing start region for level 0
[19:06:19] [Server thread/INFO]: Done (1.940s)! For help, type "help" or "?"
[19:06:20] [Server thread/INFO]: Reloaded default quest database
[19:06:28] [User Authenticator #1/INFO]: UUID of player xkuyax is 8748d319-c3ea-476c-8dd8-4898e1ea323e
[19:06:29] [Server thread/INFO]: xkuyax[/91.141.62.171:16097] logged in with entity id 1065 at (501.8783762541305, 117.0, 1049.0485402719867)
[19:06:29] [Server thread/INFO]: xkuyax joined the game
[19:06:32] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2237ms behind, skipping 44 tick(s)
[19:06:45] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking GridNode
	at RFB-Launch//appeng.me.cache.TickManagerCache.onUpdateTick(TickManagerCache.java:122) ~[TickManagerCache.class:?]
	at RFB-Launch//appeng.me.GridCacheWrapper.onUpdateTick(GridCacheWrapper.java:30) ~[GridCacheWrapper.class:?]
	at RFB-Launch//appeng.me.Grid.update(Grid.java:257) ~[Grid.class:?]
	at RFB-Launch//appeng.hooks.TickHandler.onTick(TickHandler.java:192) ~[TickHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_834_TickHandler_onTick_TickEvent.invoke(.dynamic) ~[?:?]
	at RFB-Launch//cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at RFB-Launch//cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
	at RFB-Launch//cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247) ~[FMLCommonHandler.class:?]
	at RFB-Launch//net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590) ~[MinecraftServer.class:?]
	at RFB-Launch//net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at RFB-Launch//net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NullPointerException: Cannot read the array length because the return value of "net.minecraftforge.fluids.IFluidHandler.getTankInfo(net.minecraftforge.common.util.ForgeDirection)" is null
	at RFB-Launch//com.glodblock.github.inventory.FluidConvertingInventoryAdaptor.wrap(FluidConvertingInventoryAdaptor.java:106) ~[FluidConvertingInventoryAdaptor.class:?]
	at RFB-Launch//com.glodblock.github.coremod.hooker.CoreModHooks.wrapInventory(CoreModHooks.java:69) ~[ae2fc-1.3.41-gtnh.jar:?]
	at RFB-Launch//appeng.helpers.DualityInterface.pushItemsOut(DualityInterface.java:617) ~[DualityInterface.class:?]
	at RFB-Launch//appeng.helpers.DualityInterface.tickingRequest(DualityInterface.java:573) ~[DualityInterface.class:?]
	at RFB-Launch//appeng.tile.misc.TileInterface.tickingRequest(TileInterface.java:195) ~[TileInterface.class:?]
	at RFB-Launch//com.glodblock.github.common.tile.TileFluidInterface.tickingRequest(TileFluidInterface.java:109) ~[TileFluidInterface.class:?]
	at RFB-Launch//appeng.me.cache.TickManagerCache.onUpdateTick(TickManagerCache.java:77) ~[TickManagerCache.class:?]
	... 10 more
[19:06:45] [Server thread/ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2024-10-29_19.06.45-server.txt
[19:06:45] [Server thread/INFO]: Stopping server
[19:06:45] [Server thread/INFO]: Saving players
[19:06:45] [Server thread/INFO]: Saving worlds
[fml-server-latest.log](https://github.com/user-attachments/files/17561986/fml-server-latest.log)

```

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by xkuyax** [comment] 2024-10-29 19:19
[crash-2024-10-29_19.06.45-server.txt](https://github.com/user-attachments/files/17562024/crash-2024-10-29_19.06.45-server.txt)

**Comment by xkuyax** [comment] 2024-10-29 19:19
[fml-server-latest.log](https://github.com/user-attachments/files/17562026/fml-server-latest.log)

**Comment by Lyfts** [comment] 2024-10-29 19:21
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17718

**Closed by Lyfts** 2024-10-29 19:21 UTC
Labels: Type: Crash, Status: Triage
