### ISSUE TITLE
bartimaeusnek crops have tremendous harvest size

### ISSUE THREAD

**Issue by Filiz1** [GTNewHorizons/GT-New-Horizons-Modpack#7517] opened 2021-02-23 11:38 UTC
#### Which modpack version are you using?
2.0.9.0
#
#### If in multiplayer; On which server does this happen? 
unofficial server with Ultramine core
#
#### What did you try to do, and what did you expect to happen?
Im searching for suitable crop for biomass production with adequate harvest size
#
#### What happened instead? (Attach screenshots if needed)
I am trying to harvest from bartimaeusnek crops by IC2 harvester and get 40+ stacks from 1 Shimmerleaf at once and ~500 stacks from Huckleberry for 1-2 times. I also noticed this with Ardite berry, Cobalt Berry, Magic Metal Berry, Cinderpearl, but on a much smaller scale - near 6 stacks at once from one crop.
Some crops like stonelilies, Gold Berry, Glowflowers, Glowing Earth Coral have more adequate harvest size but too large, so some days of gathering provides sufficiency of this resources for a long time. 
#
#### What do you suggest instead/what changes do you propose?
Maybe it is worth correcting yield of stonelilies, Gold Berry, Glowflowers, Glowing Earth Coral and fix other mentioned crops, and also check other crops.

**Comment by Prometheus0000** [comment] 2021-02-23 11:46
1) define 'bartimaeusnek crops'
2) Try again on latest, maybe it's fixed
3) Try in SP

**Comment by Filiz1** [comment] 2021-02-23 11:55
1. Those indicated 'bartimaeusnek' as author in GTNH spreadsheet but in particular I listed concrete crops with this problem.
2. I have not found any similar issue like this, so this is very doubtful.

**Comment by boubou19** [comment] 2021-02-23 11:57
I have heard several reports from players on the officials saying some crops where giving too much stuff, but it never reached more than a few stacks per harvest.

**Comment by GTNH-Afx237v7** [comment] 2021-02-23 12:00
What stats are your crops?

**Comment by bedrill64** [comment] 2021-02-23 12:01
This is not an issue using forestry multifarm, max I get is stack+ worth of items from max stat stonelilies, asked KiloJoel about it as he is using Crop Harvesters, it is more or less the same.

**Comment by Prometheus0000** [comment] 2021-02-23 12:02
You need to define which mod it is, GT, crops++, or both (or just all crops). Look at the wiki to see which mod they belong to if the SS doesn't say. You need to check crops from the same mod that don't have bart in the name, because a simple name change is not going to do anything. It sounds like it's crops++ though.

**Comment by bedrill64** [comment] 2021-02-23 12:04
> This is not an issue using forestry multifarm, max I get is stack+ worth of items from max stat stonelilies, asked KiloJoel about it as he is using Crop Harvesters, it is more or less the same.

Following, I'm also farming shimmerleafs and haven't noticed mass drops from these. Regular few per harvest.

**Comment by KiloJoel** [comment] 2021-02-23 12:06
I have noticed an excessive drop rate from the witchery crops. Not sure about any others

**Comment by Filiz1** [comment] 2021-02-23 12:13
> You need to define which mod it is, GT, crops++, or both (or just all crops). Look at the wiki to see which mod they belong to if the SS doesn't say. You need to check crops from the same mod that don't have bart in the name, because a simple name change is not going to do anything. It sounds like it's crops++ though.

Yes, this is oll from Crops++.
I'm not a programmer, but think that looking into the code, you can identify a pattern. At least I hope so)

**Comment by KiloJoel** [comment] 2021-02-23 12:15
Just tested garlic at 1-1-1 stats and it drops only 1 garlic
Whereas at 31-31-0 it sometimes drops over 15 stacks
So it seems like something wrong with the multiplier from gain might be the cause

**Comment by Prometheus0000** [comment] 2021-02-23 12:21
There haven't been any changes to crops++ since June of last year though. Has this been occurring for a long time?

**Comment by Zereff06** [comment] 2022-02-05 13:41
2.1.2.1 still has this bug
The more you harvest from crops, the more it yields (or the more it's on the bed)

**Comment by DianeXD** [comment] 2022-07-04 02:48
This even happened with the new multi EIG

**Comment by mistaqur** [comment] 2022-10-28 23:56
Probably caused by [CropLoadCore](https://github.com/GTNewHorizons/CropLoadCore/blob/master/src/main/java/com/github/bartimaeusnek/croploadcore/OreDict.java#L21). It should always return new ItemStack with stackSize=1 because IC2 sometimes increase stackSize of CropCard.getGain(...).

**Comment by Pxx500** [comment] 2022-12-30 17:52
fixed by https://github.com/GTNewHorizons/Crops-plus-plus/pull/45

**Closed** 2023-11-03 14:47 UTC
Labels: Mod: Crops++
