### ISSUE TITLE
world crashes when greg sensor kit linked to LCS is put inside industrial panel

### ISSUE THREAD

**Issue by DarthSuperior** [GTNewHorizons/GT-New-Horizons-Modpack#17573] opened 2024-10-05 13:18 UTC
### Your GTNH Discord Username

darth_gregtechmaniac

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 21

### Type of Server

None

### Your Expectation

I was trying put greg sensor kit WHICH was linked to NOT formed LCS into industrial information panel

### The Reality

The game crashed and world became corrupted

### Your Proposal

maybe stop people to be able to link sensor kit to not formed structures

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by querns** [comment] 2024-10-05 13:19
They forgot to add the crashlog, but I can help out.

[crash-2024-10-05_14.47.48-server.txt](https://github.com/user-attachments/files/17266321/crash-2024-10-05_14.47.48-server.txt)

**Comment by Lyfts** [comment] 2024-10-05 13:23
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16167

You can update KekzTech to https://github.com/GTNewHorizons/KekzTech/releases/tag/0.11.4 for now.

**Closed by Lyfts** 2024-10-05 13:23 UTC
Labels: Type: bugMinor, Status: Triage
