### ISSUE TITLE
Game crashes after opening any inventory with pam's harvest cinnamon in it

### ISSUE THREAD

**Issue by argentkek** [GTNewHorizons/GT-New-Horizons-Modpack#16048] opened 2024-04-24 12:31 UTC
### Your GTNH Discord Username

argentum2137

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Actions

I tried opening a diamond chest which caused the game to crashed.
Next I tried breaking the chest and slowly going through every single item inside of it which caused my game to crash again after picking up pam's harvest cinnamon.

### Crash Report

[crash-2024-04-24_14.10.42-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15094157/crash-2024-04-24_14.10.42-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment] 2024-04-28 03:15
Possibly jar corruption, try reinstalling the pack if you're on CurseForge

**Comment by chochem** [comment] 2024-04-30 10:01
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14471 and all the others. and yea try reinstalling.

**Closed by chochem** 2024-04-30 10:01 UTC
Labels: Type: Crash, Status: Triage
