### ISSUE TITLE
Recipe loophole: Not losing stone when crafting stone slabs

### ISSUE THREAD

**Issue by Mr-Jeany** [GTNewHorizons/GT-New-Horizons-Modpack#13468] opened 2023-05-10 18:33 UTC
### Your GTNH Discord Username

OuO#0803

### Your Pack Version

2.3.3

### Your Server

SP (Private Server tbh)

### Java Version

Java 8

### Type of Server

Crucible

### Your Expectation

I was trying to craft Stone Slabs in Cutting Machine and get 2 Stone Slabs from 1 Stone.

### The Reality

I have gotten 2 Slabs and 1 Stone. (That's mean I haven't lost my stone!)
![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/72220793/ddd35ae6-d585-4798-b2a3-b844ca28d611)

### Your Proposal

Change the recipe from "1 Stone -> 1 Stone and 2 Stone Slabs" to "1 Stone -> 2 Stone Slabs"

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miaowwwwww** [comment] 2023-05-10 19:27
it's fixed in dev

**Comment by miozune** [comment] 2023-05-11 01:20
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13308

**Closed by miozune** 2023-05-11 01:20 UTC
Labels: Type: bugMinor, Status: Triage
