### ISSUE TITLE
Crash in Twilight Forest, due to Nagastone

### ISSUE THREAD

**Issue by SylianXx** [GTNewHorizons/GT-New-Horizons-Modpack#16424] opened 2024-05-30 14:50 UTC
### Your GTNH Discord Username

sylian2407

### Your Pack Version

2.6.1

### Your Server

SP

### Java Version

Java 20

### Type of Server

Single Player

### Your Actions

Walking in TF towards the Naga Courtyard causes a crash.
Trying to load that world again crashes too.
The Crash is reproducable.

### Crash Report

Crash report:

[crash-2024-05-30_16.42.06-server.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/15501565/crash-2024-05-30_16.42.06-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2024-05-30 14:53
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16353 with fix there as well.

**Closed by chochem** 2024-05-30 14:53 UTC
Labels: Type: Crash, Status: Triage
