### ISSUE TITLE
industrial apiculture acclimatiser and drone domestication station used wrong liquid honey

### ISSUE THREAD

**Issue by truecyt** [GTNewHorizons/GT-New-Horizons-Modpack#12212] opened 2023-01-06 06:20 UTC
### Your GTNH Discord Username

truecyt#2723

### Your Pack Version

227

### Your Server

private server

### Type of Server

None

### Your Expectation

industrial apiculture acclimatiser and drone domestication station used wrong liquid honey
it used bop's liquid honey not forestry's honey
we cannot acquire the bop's honey

### The Reality

![image](https://user-images.githubusercontent.com/58604873/210941943-4e1dd7d9-fb2a-46be-b02e-7fcb9bad7b0d.png)
the mega apiary's recipe used honey registry is “honey”
but the FR's liquid honey registry is "for.honey"
![image](https://user-images.githubusercontent.com/58604873/210942176-0b70beef-fe97-4e9e-aa15-d18265143c39.png)

### Your Proposal

fix in next edition

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment] 2023-01-06 06:41
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12005

**Closed by miozune** 2023-01-06 06:41 UTC
Labels: Type: bugMinor, Status: Triage
