### ISSUE TITLE
 World Not Created in Single Player

### ISSUE THREAD

**Issue by FoKuCNiK** [GTNewHorizons/GT-New-Horizons-Modpack#11521] opened 2022-10-02 19:42 UTC
### Your GTNH Discord Username

FoKuCNiK

### Your Pack Version

2.2.0.0-RC-3

### Your Server

SP, MP

### Your Actions

When I launch a single player game, it crashes like this. Someone knows how to solve this? My players play on a server and sometimes you need to test something in a single game and it's difficult when it doesn't start! 
I'm attaching the logs below.

[LOGS.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/9693353/LOGS.txt)

### Crash Report

HELP!!!!!!!!!!

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2022-10-02 20:06
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10447
maybe add what info you have there. And maybe try with the new stable version.

**Closed by chochem** 2022-10-02 20:06 UTC
Labels: Type: Crash, Status: Triage
