### ISSUE TITLE
Game crashed - Lunch box && Bowls

### ISSUE THREAD

**Issue by valeriouslis** [GTNewHorizons/GT-New-Horizons-Modpack#3317] opened 2018-07-16 15:35 UTC
#### Which modpack version are you using?
last for now
#
#### If in multiplayer; On which server does this happen? 
single player
#
#### What did you try to do, and what did you expect to happen?
i have lunch box (id 7739) with berry medley (id 4680), each give 1 bowl (id 281) in inventory.
#
#### What happend instead? (Attach screenshots if needed)
Sometimes this bowl turns out to be in lunch box and it is painted as if there is food, when i try eat from lunch box game crashed. 
#

**Comment by Dream-Master** [comment] 2018-07-16 18:16
So far i can say it happend only in MP.

**Comment by valeriouslis** [comment] 2018-07-16 18:42
MP?

**Comment by Dream-Master** [comment] 2018-07-16 18:57
multi player @valeriouslis

**Comment by Bryfer** [comment] 2018-07-16 22:04
Dupe of #3263 ?

**Comment by shawnbyday** [comment] 2020-09-16 19:06
This is old issue. If still having issues please feel free to reopen this issue. Thanks!

**Closed by shawnbyday** 2020-09-16 19:06 UTC
Labels: Need more Info, question
