### ISSUE TITLE
Spice of Life crash

### ISSUE THREAD

**Issue by skero258** [GTNewHorizons/GT-New-Horizons-Modpack#16556] opened 2024-06-19 20:30 UTC
### Your GTNH Discord Username

skero258

### Your Pack Version

2,6,1

### Your Server

private server

### Java Version

Java 8

### Type of Server

Open To LAN

### Your Actions

It happen when diary went to 0%, propably

### Crash Report

[crash-2024-06-19_22.21.26-client.txt](https://github.com/user-attachments/files/15905678/crash-2024-06-19_22.21.26-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by DupiGus** [comment] 2024-06-19 21:27
found any solutions im having the  same issue

**Comment by Eiree** [comment] 2024-06-19 21:56
Seems this issue has arisen in the past, may be due to a corrupt download of the file. Reinstalling the modpack or disabling the mod may help.

**Comment by chochem** [comment] 2024-06-19 22:17
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/14471 and at least 10 others

**Closed by chochem** 2024-06-19 22:17 UTC
Labels: Type: Crash, Status: Triage
