### ISSUE TITLE
Strong redstone signals from covers behave as weak signals

### ISSUE THREAD

**Issue by TheStoneWolf** [GTNewHorizons/GT-New-Horizons-Modpack#13400] opened 2023-05-01 12:50 UTC
### Your GTNH Discord Username

StoneWolf#7888

### Your Pack Version

2,3.3

### Your Server

SP

### Java Version

Java 8

### Type of Server

Single Player

### Your Expectation

If you put a cover on a machine and then use a soldering iron to set that side to have a strong output, the redstone signal should be able to go through one block. This is what it did in the update  from which I recently updated which I think was 2.2, but I am not sure. I am also pretty sure it worked in version 2.3.0-RC that I played a bit before.

This may be an uncorrelated bug, but the soldering iron should cycle through between 'weak' and 'strong' if you use it on the same side multiple times.

Why is this worth fixing? Well, an EBF only has one free side you can place a cover on (the bottom), meaning that if you want to have two covers on it, for example a machine controller and an activity detector cover, the activity detector cover output has to go through a coil block since the bottom side of the EBF controller has the machine controller cover. Since the strong redstone signals behave as weak now however, this do not work anymore.

I have tested this on fresh installs to not be working in both Java 8 and Java 19. Optifine was not used.

### The Reality

Even though the cover outputs a signal, it is weak despite the soldering iron claiming the side to have a strong redstone output.

The soldering iron does not cycle between setting the side to 'weak' and 'strong', but instead only sets the side to 'strong'. However, there is a short pulse the moment the soldering iron is used, meaning that the redstone signal is strong for the duration of that pulse (1 tick long I believe).

![RedstoneStrengthExample](https://user-images.githubusercontent.com/15616024/235453399-358c0d26-be51-4282-8662-fc3bed960b42.png)

In the example above, the item detector cover has the same settings, but the output shown in the wire is different. Note the lack of cycling with the soldering iron.

### Your Proposal

Fix it to how it was before. The soldering iron should be cycling between 'weak' and 'strong' and when a side has been set to 'strong' by the soldering iron, the redstone signal should be strong, meaning that the signal can go through a block.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by greesyB** [comment] 2023-05-01 14:11
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13270. The breaking changes were reverted so should be working in dev.

**Closed by greesyB** 2023-05-01 14:11 UTC
Labels: Type: bugMinor, Status: Triage
