### ISSUE TITLE
Nanosuit wings defence too low

### ISSUE THREAD

**Issue by KiloJoel** [GTNewHorizons/GT-New-Horizons-Modpack#6812] opened 2020-10-12 16:09 UTC
#### Which modpack version are you using?
2.0.9.0
#
#### What happened instead? (Attach screenshots if needed)
Nanosuit wings (Electro-Magic Tools) only give 5 armour points when equipped. This is lower than the 6 points thaumium wings give, which are the tier below, and also lower than the nanosuit bodyarmour, which gives 7.
#
#### What do you suggest instead/what changes do you propose?
Change nanosuit wings so that they give 7 armour instead of 5.

**Comment by KiloJoel** [comment] 2020-10-12 16:10
Just tried quantum wings and they also only give 5

**Comment by Dream-Master** [comment] 2020-10-12 16:27
we can change emt code.

**Comment by Prometheus0000** [comment] 2020-10-12 21:45
Duplicate of #3663

**Closed by Prometheus0000** 2020-10-12 21:45 UTC
Labels: Type: duplicate
