### ISSUE TITLE
Random crash relating to tool tips and or items when hovering over them?

### ISSUE THREAD

**Issue by NerdySpider** [GTNewHorizons/GT-New-Horizons-Modpack#13326] opened 2023-04-26 09:32 UTC
### Your GTNH Discord Username

🍁NerdySpider🍁#5501

### Your Pack Version

2.3.0

### Your Server

SP

### Java Version

Java 9

### Type of Server

Single Player

### Your Actions

Opening random quests, inspecting random items in chests. This tends to be random, but I have found its happened on the "finding apatite" quest and the one relating to the forestry leave shear things next to the grafter quest? Most recently I just opened a chest and tried to hover over some of the items and it crashed.

### Crash Report

https://pastebin.com/R0FNHZ11

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment] 2023-04-26 09:42
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12696

**Closed by miozune** 2023-04-26 09:42 UTC
Labels: Type: Crash, Status: Triage
