### ISSUE TITLE
Data Bank Recipe only using LuV Mainframes

### ISSUE THREAD

**Issue by johnch18** [GTNewHorizons/GT-New-Horizons-Modpack#7647] opened 2021-03-17 18:04 UTC
#### Which modpack version are you using?
2.1.0.0
#
#### What did you try to do, and what did you expect to happen?
Tried crafting a data bank with a crystalprocessor assembly. According to the wiki it works with any LuV circuit.

#
#### What happened instead? (Attach screenshots if needed)
Craft wouldn't start, on a hunch I tried nanoprocessor mainframes and it worked.

#
#### What do you suggest instead/what changes do you propose?
Oredictionary the recipe.

**Comment by Prometheus0000** [comment] 2021-03-17 18:25
Duplicate of #6178

**Closed by Prometheus0000** 2021-03-17 18:25 UTC
Labels: Type: duplicate, Type: oredict
