### ISSUE TITLE
Texture bugging in the "Select World" and "Conntrols" menu

### ISSUE THREAD

**Issue by Oton35** [GTNewHorizons/GT-New-Horizons-Modpack#16191] opened 2024-05-06 11:30 UTC
### Your GTNH Discord Username

Otonek#2530

### Your Pack Version

2.6.0

### Your Server

Solo world

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Clear menu

### The Reality

![CTRLS](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/169046940/db30b86f-8e41-49bd-a27e-843522c76dca)
![Selecting world](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/169046940/043616d8-1ebb-4fea-8a45-cec7f25afa79)

### Your Proposal

.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lyfts** [comment] 2024-05-06 11:57
Duplicate of https://github.com/GTNewHorizons/Angelica/issues/185.

Update Angelica https://github.com/GTNewHorizons/Angelica/releases/tag/1.0.0-alpha44 or disable fontrenderer in Angelica config.

**Closed by Lyfts** 2024-05-06 11:57 UTC
Labels: Type: bugMinor, Status: Triage
