### ISSUE TITLE
Loading different minecraft world after logging off one world causes Thaumcraft crash

### ISSUE THREAD

**Issue by PolkageistHS** [GTNewHorizons/GT-New-Horizons-Modpack#14010] opened 2023-07-20 19:59 UTC
### Your GTNH Discord Username

Pao

### Your Pack Version

2.3.4 balls run build

### Your Server

Balls

### Java Version

Java 20

### Type of Server

Vanilla Forge

### Your Actions

After logging out of the Balls Run server, when I try to open a different GTNH (singleplayer or multiplayer), I get this crash.  It's happened twice, with different worlds.  Closing Minecraft and running it again fixes the issue.  Chi/Sandrusher got the same error the other day, same blocks (Nitor/Hungry Chest). 

Two crash logs are attached, along with a screenshot of the exact coordinates in the latest crash.  There's no Nitor, no Hungry Chest, and no Wisps that could be making particles.  

![2023-07-18_19 31 32](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/9247381/c67c9d4a-8a2b-4f4d-ac4b-b93bdec6e776)

### Crash Report

[crash-2023-06-19_21.04.06-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12113619/crash-2023-06-19_21.04.06-client.txt)
[crash-2023-07-18_19.20.37-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/12113620/crash-2023-07-18_19.20.37-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [X] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2023-07-20 20:06
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13824

**Closed by chochem** 2023-07-20 20:06 UTC
Labels: Type: Crash, Status: Triage

**Comment by PolkageistHS** [comment] 2023-07-20 20:59
Boo, search was no help because the other ticket didn't have any applicable keywords and I wasn't going to manually check every crash report

**Comment by chochem** [comment] 2023-07-20 21:02
not a big deal, dont worry about it.
though you could comment on that ticket, in particular if you have any more specific idea what '2.3.4 balls run build' means.

**Comment by PolkageistHS** [comment] 2023-07-20 21:04
Yeah, problem with that is it changes daily. The upside/downside to having multiple devs in a run who find and patch bugs as they're found
