### ISSUE TITLE
Nuclear control panel attached to Lapotronic Super Capacitor causing crash

### ISSUE THREAD

**Issue by fdsatrew3** [GTNewHorizons/GT-New-Horizons-Modpack#16953] opened 2024-08-09 13:51 UTC
### Your Pack Version

2.6.1

### Your Server

private server

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Actions

I broke controller of this multiblock while it attached to nuclear control panel and placed again at same place to cause server crash. After server restart it crashed again in ~5s after chunk loaded

### Crash Report

[crash-2024-08-08_19.33.22-server.txt](https://github.com/user-attachments/files/16561990/crash-2024-08-08_19.33.22-server.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by Lyfts** [comment] 2024-08-09 13:54
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/16167

You can update Kekztech to https://github.com/GTNewHorizons/KekzTech/releases/tag/0.11.4

**Closed by Lyfts** 2024-08-09 13:54 UTC
Labels: Type: Crash, Status: Triage
