### ISSUE TITLE
Graphical Issue

### ISSUE THREAD

**Issue by SD678** [GTNewHorizons/GT-New-Horizons-Modpack#11995] opened 2022-12-16 04:26 UTC
### Your Pack Version

2.2.0.0

### Your Server

SP

### Type of Server

Single Player

### Your Expectation

Attempted to play the pack with the new update. I had the issue fixed already and completely forgot that this issue existed.

### The Reality

![2022-12-15_23 17 01](https://user-images.githubusercontent.com/78656707/208021648-644f6acb-202d-4e1f-b958-d61368d14688.png)
![2022-12-15_23 17 04](https://user-images.githubusercontent.com/78656707/208021649-6b89a012-8e22-41db-96ff-6902df77dbc4.png)
![2022-12-15_23 16 59](https://user-images.githubusercontent.com/78656707/208021650-afe02528-02bb-44d6-9ba8-ed72198ba4b7.png)

### Your Proposal

I know I fixed it before but I forget how I did

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by miozune** [comment] 2022-12-16 04:34
Graphic card issue, duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10106

**Closed by miozune** 2022-12-16 04:34 UTC
Labels: Type: bugMinor, Status: Triage
