### ISSUE TITLE
Convert input to output and vice versa hatch|bus

### ISSUE THREAD

**Issue by AderMeepo** [GTNewHorizons/GT-New-Horizons-Modpack#9754] opened 2022-02-16 12:29 UTC
### Your GTNH Discord Username

Ader#8113

### Your Pack Version

2.1.2.1

### Your Proposal

INPUT and OUTPUT bus/hatch recipes have identical crafting, why not add the ability to convert them between each other? This is a completely logical possibility for such mechanisms, especially since, as I said, they have the same crafts.

### Your Goal

I offer 2 options, make a conversion through the crafting window or make a conversion through the assembler and a chip with the corresponding number

### Your Vision

Often I make a mistake with the chip number and craft the wrong block that I need, so this is mostly a remedy for inattention. Therefore, I thought that it would not be bad if such an opportunity were introduced, especially since it does not particularly affect anything
p.s. sorry for my english :d 

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying *I like this feature please reconsider adding it* will prompt us to investigate and reopen it once we confirm your report.
- [X] I believe there is nothing similar in the pack already, or the existing solution isn't good enough.
- [X] I understand this change request may not attract enough attention and thus not be implemented.
- [X] I understand this change request may be rejected due to other community members thinking it's inappropriate.
- [X] I believe this feature would make the pack better.

**Comment by Glease** [comment] 2022-02-16 12:30
I think this was discussed before but I cannot find the old issue.

**Comment by AderMeepo** [comment] 2022-02-16 12:34
Yeah i too cant found this disscusion

**Comment by GTNHAfx237v7** [comment] 2022-02-16 12:38
Duplicate of #8273

**Comment by Relvl** [comment] 2022-02-16 12:42
Im sure this is a good option, this recipes are same, just different circuit option.
Maybe converting in the assembling machine?

**Comment by AderMeepo** [comment] 2022-02-16 12:44
I think through the assembler this is the most logical solution

**Comment by Glease** [comment] 2022-02-16 12:52
Duplicate of #8273. Thanks @GTNHAfx237v7 .

**Closed by Glease** 2022-02-16 12:52 UTC
Labels: Type: Suggestion, Type: New Recipe
