### ISSUE TITLE
NEI Preview is buggy

### ISSUE THREAD

**Issue by MaGeBZz** [GTNewHorizons/GT-New-Horizons-Modpack#15988] opened 2024-04-16 12:02 UTC
### Your GTNH Discord Username

marvinhhmagebzz

### Your Pack Version

2.6.0 Beta 3

### Your Server

SP

### Java Version

Java 17

### Type of Server

Single Player

### Your Expectation

The NEI preview shouldn't have this weird black frame around it + you should be able to hover over the blocks to see what you need to use there

![image](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/133218866/bee17b7e-fc8a-4752-8877-bff96fac5945)

### The Reality

You an't do the things I mentioned

### Your Proposal

Remove the black frame + be able to hover over the blocks again and click on them to see what these blocks are exactly

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lyfts** [comment] 2024-04-16 12:29
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/15802

**Closed by Lyfts** 2024-04-16 12:29 UTC
Labels: Type: bugMinor, Status: Triage
