### ISSUE TITLE
Crash caused by The Spice of Life - Carrot Edition, AppleCore

### ISSUE THREAD

**Issue by leonmcfly** [GTNewHorizons/GT-New-Horizons-Modpack#13654] opened 2023-06-10 09:50 UTC
### Your GTNH Discord Username

leonmcfly#8698

### Your Pack Version

2.32

### Your Server

private Server

### Java Version

Java 17

### Type of Server

Don't know

### Your Actions

Opened one of my food chest and it crashes 
its a specific item cause if i open any other food chest then it wont crash
then i broke the chest  and have all my items in the my inventory 
now its crashing if i open my inventory 
cant  upload  fml client log cause its to  big

### Crash Report

[crash-2023-06-10_11.46.15-client.txt](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11712127/crash-2023-06-10_11.46.15-client.txt)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by leonmcfly** [comment] 2023-06-10 09:51
[fml-client-latest.zip](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/files/11712134/fml-client-latest.zip)
needed to compress the fml log

**Comment by chochem** [comment] 2023-06-10 09:54
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12696

**Closed by chochem** 2023-06-10 09:54 UTC
Labels: Type: Crash, Status: Triage

**Comment by wlhlm** [comment] 2023-06-10 09:56
You can manually replace your SoL with the fixed version: https://github.com/GTNewHorizons/SpiceOfLife/releases/tag/2.1.0-carrot
