### ISSUE TITLE
Glitched Screen on Controls menu and others

### ISSUE THREAD

**Issue by Noameil** [GTNewHorizons/GT-New-Horizons-Modpack#16312] opened 2024-05-19 11:39 UTC
### Your GTNH Discord Username

noameil

### Your Pack Version

2.6

### Your Server

SP

### Java Version

Java 8

### Type of Server

None

### Your Expectation

Trying to change key bindings and can't see what to click on

### The Reality

![Capture](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/110397935/738106c0-cb73-4811-9a5c-f452f6d2bb3c)

### Your Proposal

I would like to know how can I fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [x] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [ ] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Lyfts** [comment] 2024-05-19 12:29
Duplicate of GTNewHorizons/Angelica#185.

Update Angelica https://github.com/GTNewHorizons/Angelica/releases/tag/1.0.0-alpha50 or set enableFontRenderer to false in Angelica config.

**Closed by Lyfts** 2024-05-19 12:29 UTC
Labels: Type: bugMinor, Status: Triage
