### ISSUE TITLE
Warded glass nuke protection

### ISSUE THREAD

**Issue by POPlol333** [GTNewHorizons/GT-New-Horizons-Modpack#8860] opened 2021-11-17 16:55 UTC
### Your GTNH Discord Username

AdamR#0072

### Your Pack Version

2.1.1.0

### Your Server

Delta

### Your Expectation

Well, it's closed so it should be protected 
![image](https://user-images.githubusercontent.com/76914762/142245500-1b41cf28-3ef9-449f-bcef-153cf3a90401.png)

### The Reality

so why the fuck it exploded by a closed corner 
![2021-11-17_17 30 08](https://user-images.githubusercontent.com/76914762/142245607-24e91424-e513-4d0c-ba5b-3775be38b52a.png)

### Your Proposal

Fix it

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by POPlol333** [comment] 2021-11-17 16:56
Probably duplicated issue, but too salty to not write something about it

**Comment by Impos913** [comment] 2021-11-17 17:02
This is how explosions work in minecraft
You need blocks on the corners too

**Comment by POPlol333** [comment] 2021-11-17 17:03
> This is how explosions work in minecraft You need blocks on the corners too

dick coded game

**Comment by boubou19** [comment] 2021-11-17 17:12
Please stay polite :) Also i'm closing this as it's clearly not a bug

**Closed by boubou19** 2021-11-17 17:12 UTC
Labels: Type: bugMinor, Status: Triage
