### ISSUE TITLE
Attempting to access the crafting status on an non existing ME system via a Wireless Terminal causes a crash

### ISSUE THREAD

**Issue by pokeball99** [GTNewHorizons/GT-New-Horizons-Modpack#13769] opened 2023-06-21 23:12 UTC
### Your GTNH Discord Username

Kekel7#9661

### Your Pack Version

2.3.0

### Your Server

Private

### Java Version

Java 8

### Type of Server

Don't know

### Your Actions

1. link a wireless terminal to a ME system with crafting setup
2. cut power to crafting but keep power to the wireless access point
3. attempt to look at crafting status via a Wireless terminal

### Crash Report

https://cdn.discordapp.com/attachments/401118216228831252/1121215092487377026/message.txt

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2023-06-30 17:00
looks like a duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/12888

**Closed** 2023-06-30 17:00 UTC
Labels: Type: Crash, Mod: AE2, Status: Triage
