### ISSUE TITLE
Hydrogen Peroxide production doesn't start.

### ISSUE THREAD

**Issue by koiNoCirculation** [GTNewHorizons/GT-New-Horizons-Modpack#11495] opened 2022-10-01 01:07 UTC
### Your Pack Version

2200RC2

### Your Server

private server

### Type of Server

Vanilla Forge

### Your Expectation

![image](https://user-images.githubusercontent.com/57739338/193376969-ee81c74a-6369-438c-a63f-e99d36c32fc2.png)
I am trying to make some rocket fuel, with hydrogen peroxide, and here's my chemical plant.
The plant is powered with HV power, it should start making hydrogen peroxide with ingredients provided.

### The Reality

The machine doesn't start.
![image](https://user-images.githubusercontent.com/57739338/193377031-31e91c22-2594-4aef-8038-f9b6775d8367.png)
Ingredients are put in input buses, and programmed circuits is present in control block.
![image](https://user-images.githubusercontent.com/57739338/193377087-24baecd0-ad83-4bd6-a3db-4b032a36f1fa.png)
![image](https://user-images.githubusercontent.com/57739338/193377161-77fa2a83-fb2b-43c6-9531-e6e0f5caa700.png)
![image](https://user-images.githubusercontent.com/57739338/193377178-cbb3403e-cb1c-4728-b3d1-594d971ac43d.png)
![image](https://user-images.githubusercontent.com/57739338/193377197-7ecf8c8f-f522-4ce4-b1bb-5f204f235f01.png)

### Your Proposal

Check if there's a problem in recipes and fix.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by GlodBlock** [comment] 2022-10-01 02:29
chemical plant doesn't count item in controller block, tryt to put the circuit in input bus

**Comment by koiNoCirculation** [comment] 2022-10-02 10:10
@GlodBlock  well, still doesn't work bro, I tried putting that circuit into input bus.

**Comment by koiNoCirculation** [comment] 2022-10-02 10:16
@GlodBlock 
Actually I tried a different recipe with circuit in controller, it works.
![image](https://user-images.githubusercontent.com/57739338/193449094-36191d50-1512-4d80-8e55-7c956ab2fa7f.png)

![image](https://user-images.githubusercontent.com/57739338/193449094-36191d50-1512-4d80-8e55-7c956ab2fa7f.png)

**Comment by koiNoCirculation** [comment] 2022-10-02 10:16
![image](https://user-images.githubusercontent.com/57739338/193449126-c849aa32-c72f-4a6e-8739-8cdb05f5b1c5.png)

**Comment by chochem** [comment] 2022-10-02 22:47
probably a duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11448
can you try a bigger output hatch? (though you will also need better machine casings then obviously). I guess you can also reduce the parallels by reducing the pipe casings.

**Comment by koiNoCirculation** [comment] 2022-10-03 11:13
@chochem Actually I tried placing 2 HV output hatches, but obviously it didn't work :(.

**Comment by koiNoCirculation** [comment] 2022-10-04 06:11
@chochem worked when using IV Hatches

**Closed** 2022-10-04 09:50 UTC
Labels: Type: bugMinor, Status: Triage
