### ISSUE TITLE
Crash when setting up a template by dragging things from NEI

### ISSUE THREAD

**Issue by Eldrinn-Elantey** [GTNewHorizons/GT-New-Horizons-Modpack#11906] opened 2022-12-01 19:42 UTC
### Your GTNH Discord Username

Eldrinn Elantey#0399

### Your Pack Version

2.2.0.0

### Your Server

Private

### Type of Server

Vanilla Forge

### Your Actions

I put the recipe in the template via NEI and decided to change one item. He is glued to the cursor and throws it off the server when trying to remove it

### Crash Report

https://paste.ubuntu.com/p/SJ72PRmHVw/

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [ ] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by miozune** [comment] 2022-12-02 00:44
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/11531, update NEI

**Closed by miozune** 2022-12-02 00:44 UTC
Labels: Type: Crash, Status: Triage
