### ISSUE TITLE
The server crashes after ordering printed circuit boards

### ISSUE THREAD

**Issue by RobotPavuk** [GTNewHorizons/GT-New-Horizons-Modpack#17840] opened 2024-11-02 16:01 UTC
### Your GTNH Discord Username

robotpavuk

### Your Pack Version

2.7.0 beta 3

### Your Server

Private 

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Actions

When ordering printed circuit boards in a chemical reactor using liquids in the template, the server crashes. The interface stand closer to the quadruple fluid bus, through enderIo conduit which item are fed. After the crash, the server is instantly closed when loading.

### Crash Report

[fml-server-latest.log](https://github.com/user-attachments/files/17607460/fml-server-latest.log)

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the crash still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this crash consistently by following the exact steps I described above.
- [ ] I have asked other people and they confirm they also crash by following the exact steps I described above.

**Comment by chochem** [comment] 2024-11-02 21:58
no crash in that log. maybe its the wrong one?

**Comment by RobotPavuk** [comment] 2024-11-03 12:43
maybe you need this one
[crash-2024-11-02_19.27.44-server.txt](https://github.com/user-attachments/files/17610440/crash-2024-11-02_19.27.44-server.txt)

**Comment by Lyfts** [comment] 2024-11-03 13:02
Duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/17718

You can update AE2FC to https://github.com/GTNewHorizons/AE2FluidCraft-Rework/releases/tag/1.3.45-gtnh

**Closed by Lyfts** 2024-11-03 13:02 UTC
Labels: Type: Crash, Mod: AE2FC
