### ISSUE TITLE
Traveller's Gear Ability Switching UI Broken

### ISSUE THREAD

**Issue by Ruling-0** [GTNewHorizons/GT-New-Horizons-Modpack#17347] opened 2024-09-15 01:58 UTC
### Your GTNH Discord Username

ruling_

### Your Pack Version

Nightly 646

### Your Server

Private Server

### Java Version

Java 21

### Type of Server

Vanilla Forge

### Your Expectation

As on previous versions, I could hold the Traveller's Gear Active Ability key to pull up a circular UI which allowed clicking on certain gears to change their methods. For example, this allows changing the alignment of Primordial Armor pieces.

![2024-09-14_20 55 11](https://github.com/user-attachments/assets/ae580792-0b68-47f1-896f-16a2951200d3)

### The Reality

When attempting to move the cursor to the armor and select them, the game now seems to re-catch the cursor and keep it in the middle. Even though the armor pieces highlight, clicking just does a normal left click (such as mine a block). This means something like Primordial Armor cannot have its mode changed anymore.

![2024-09-14_20 58 27](https://github.com/user-attachments/assets/1a1429f3-0a3e-4015-a770-c83a12b541f9)

### Your Proposal

Restore the ability to click the equipment in the UI

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by Ruling-0** [comment] 2024-11-08 06:51
Confirmed still an issue on Nightly 727. This makes anything using the UI (mainly primordial armor) entirely unusable, when it was previously functional.

**Comment by wlhlm** [comment] 2024-11-13 09:26
This is fixed by downgrading to TravellersGearNeo to 1.2.1. This means this was caused by https://github.com/GTNewHorizons/TravellersGearNeo/pull/1

**Comment by Dream-Master** [comment] 2024-11-13 10:16
if this not work we should reverse the pr? or can we have a fix ?

**Comment by wlhlm** [comment] 2024-11-13 10:20
I can fix this. I'm currently trying to coordinate with the original author.

**Comment by wlhlm** [comment] 2024-11-17 12:59
OK, this might not be as straight forward as I'd hoped. Everything works fine in TravellersGearNeo devenv, but not in full GTNH, so there must be another mod/config options that causes this.

**Comment by wlhlm** [comment] 2024-11-23 21:38
Turns out, this has nothing to do with GTNH at large and *can* be reprocuded in devenv. I just got confused, because I tested it with keyboard keybinds in one environment and mouse button keybinds in the other and keyboard keybinds don't work correctly. It's just a logic error I have to entangle.

**Closed** 2024-12-01 19:25 UTC
Labels: Bug: Minor, Mod: Witching Gadgets, Mod: Traveller's Gear, Type: GUI, Status: Ready for Developer
