### ISSUE TITLE
Overflow valve does not properly read contents

### ISSUE THREAD

**Issue by Krydax** [GTNewHorizons/GT-New-Horizons-Modpack#16519] opened 2024-06-12 01:21 UTC
### Your GTNH Discord Username

Krydax

### Your Pack Version

2.6.0

### Your Server

none

### Java Version

Java 21

### Type of Server

Single Player

### Your Expectation

Set LV overflow valve to 2,000 units (doubled checked)
Obviously the fluid should void when >2000

### The Reality

The fluid is not voided, you can see clearly in the pic there is 12k of the output. 

### Your Proposal

According to @Four on Discord, the reason is that it is using the LEFT fluid slot to read how much it has, and if I were to put fluid (at least 2k) into the "input" slot, then it would ALWAYS void. 

Obviously it should utilize the output amount to read how much fluid it has in order to void.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by chochem** [comment] 2024-06-14 12:56
duplicate of https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/9561

**Closed by chochem** 2024-06-14 12:56 UTC
Labels: Type: bugMinor, Status: Triage
