### ISSUE TITLE
The Mass Fabricator recipe is malfunctioning and causing serious errors

### ISSUE THREAD

**Issue by lao-pan** [GTNewHorizons/GT-New-Horizons-Modpack#15209] opened 2023-12-24 02:16 UTC
### Your GTNH Discord Username

pzqpzqpzq

### Your Pack Version

2.5.1

### Your Server

SP

### Java Version

Java 8

### Type of Server

Vanilla Forge

### Your Expectation

After updating to version 2.5.1 in the EV phase, when I was inspecting the previous 2.4.0 production line, I noticed that the LV Mass Fabricator, casually constructed before, was generating UU matter. During the process of utilizing the HV UU-Amplification Liquid Generator to produce amplification liquid, the time and power consumption reached an astonishing level
![1](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/124324563/46287626-ee7b-4efc-b219-8b9699a40e01)

### The Reality

Then I checked NEI and found that the recipe wasn't as outlandish as I thought. As a result, I also replicated this recipe's behavior. Please take a look at my actions
![2](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/124324563/95da6f56-de3e-404a-a94f-e6cfdcca0ccf)
![3](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/124324563/6fd62931-49e7-4ded-9b86-c94b0b08cc23)
![4](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/124324563/7cfe434f-59b5-4451-ae2a-a4baf0d6b919)
As shown by me, it seems the new recipe hasn't been fully implemented

### Your Proposal

Although the LV-tier Mass Fabricator isn't powerful, it can still produce a small amount. After all, this is GTNH.   XD

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by vovaksenov** [comment] 2023-12-24 02:28
This is probably a duplicate of #15132, right?

**Comment by StaffiX** [comment] 2024-01-02 22:13
well, no

I cant replicate the nei page where it displays max int recipe time

but normally it should be
160s
80s
40s
20s
10s
and eu usage should double


but now it's
max int
160s
160s
80s
40s
and uses -1 for lv, 256 for mv and hv, then doubles

**Comment by lao-pan** [comment] 2024-01-02 22:28
"Yes, I clicked on the middle of the machine to see the synthesis recipe, and when I used the 'U' shortcut key with NEI while facing the machine, there was a significant discrepancy in the ingredients for synthesis. Using the NEI shortcut key shows the normal recipe, and it's not reaching the maximum values. However, when I clicked on the middle of the machine, two different recipes appeared. That's what I wanted to convey."

**Comment by StaffiX** [comment] 2024-01-02 22:36
okay yeah, when you use the arrow, those values appear what i wrote, but it shows proper time and eu when you just right click the machine list

**Comment by Ngar1** [comment] 2024-01-08 10:58
LV Basic Mass Fab takes 40.000s instead 40s (GTNH 2.5.1)
![grafik](https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/assets/7759876/1418c3ed-1d2a-4c30-9bb3-85cba6c60b54)

**Comment by desagas** [comment] 2024-01-19 07:08
Still not fixed in 2.5.1+313

**Comment by Rami114** [comment] 2024-01-19 18:57
Not sure where this is being introduced. Extracted all the logic for the Mass Fabricator including it's custom OverclockDescriber and checkRecipe implementation. All my tests with various tiers show the recipe code working just fine including OCs. It's using addFakeRecipe so is this being handled somewhere in IC2?

**Closed** 2024-01-19 20:49 UTC
Labels: Type: bugMajor, Mod: GT
