### ISSUE TITLE
galaxy space jetpack

### ISSUE THREAD

**Issue by kokochicken** [GTNewHorizons/GT-New-Horizons-Modpack#1221] opened 2017-03-17 20:52 UTC
flying with the galaxy space jetpack then landing causes super high damage for no reason, i flew one block off the ground landed and got 1shot from 10hearts.

**Comment by Dream-Master** [comment] 2017-03-17 20:57
Not using it. The Mod is not open source so nothing i can do.
And do me a favor and report it on his side. Thanks.

**Comment by Dream-Master** [comment] 2017-03-17 20:58
https://github.com/BlesseNtumble/GalaxySpace/issues

**Comment by kokochicken** [comment] 2017-03-17 21:02
ok thank you

**Comment by Dream-Master** [comment] 2017-03-17 21:11
Will see if @BessNtumbe ever answering. Another issue on his mod he not answering yet.

**Comment by nanmumc** [comment] 2017-03-18 15:18
It calculate the damage from the highest you reached, so that use a hangglider to resetting the height may help you a lot.

**Comment by Dream-Master** [comment] 2017-12-23 15:27
Maybe i will update galaxy space in the future idk.

**Comment by Prometheus0000** [comment] 2020-09-14 21:10
This can be fixed now if it's still an issue.

**Comment by glowredman** [comment] 2020-09-18 22:57
I tested it and were not able to reproduce this bug.

**Closed** 2020-09-27 09:25 UTC
Labels: Mod: Galaxy-Space, Status: can't reproduce
