### ISSUE TITLE
Healing Axe recipe requires obsidian sticks from random things, but it automatically gets converted back into tcon obsidian tool rods whenever converted

### ISSUE THREAD

**Issue by srdr2k3** [GTNewHorizons/GT-New-Horizons-Modpack#10078] opened 2022-04-01 00:05 UTC
### Your GTNH Discord Username

Serdar#7777

### Your Pack Version

2.1.2.0

### Your Server

Eta

### Type of Server

Don't know

### Your Expectation

Tried to craft healing axes for my buddies that are going to join me.
Normally the recipe requires any unstable ingots and specifically random things obsidian sticks which can be converted from tcon obsidian tool rods.

### The Reality

Converting the obsidian tool rod from tconstruct in to the aforementioned random things obsidian sticks will automatically convert it back into tcon rods.
Therefore it wont allow for the Healing Axe to be crafted.

I've found a workaround for this conversion:
Forestry worktables deny the conversion from random things obsidian sticks to tcon obsidian tool rods
I was able to craft the healing axes that way

### Your Proposal

Allow to Healing Axe recipe to use any type of obsidian sticks.

### Final Checklist

- [X] I have searched this issue tracker and there is nothing similar already. Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I can reproduce this problem consistently by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.
- [X] I have asked other people and they confirm they also have this problem by follow the exact steps I described above, or this does not need reproducing, e.g. recipe loophole.

**Comment by srdr2k3** [comment] 2022-04-01 00:11
Whoops it seems i havent searched hard enough, and i've found a similar issue to mine:
https://github.com/GTNewHorizons/GT-New-Horizons-Modpack/issues/10011
Should i just be closing this one?

**Comment by miozune** [comment] 2022-04-01 05:44
Duplicate of #10011

**Closed by miozune** 2022-04-01 05:44 UTC
Labels: Type: bugMinor, Status: Triage
