### ISSUE TITLE
Centrifuging Rubber Wood only outputs Methane Gas

### ISSUE THREAD

**Issue by Kohuda** [GTNewHorizons/GT-New-Horizons-Modpack#5243] opened 2019-12-28 00:50 UTC
#### Which modpack version are you using?

2.0.8.0

#
#### If in multiplayer; On which server does this happen? 

Singleplayer

#
#### What did you try to do, and what did you expect to happen?

Centrifuging Rubber wood for the item outputs.

#
#### What happened instead? (Attach screenshots if needed)

Got just Methane gas, there are two recipes in the Centrifuge.

#
#### What do you suggest instead/what changes do you propose?

Remove the recipe without any item outputs.

**Comment by Dream-Master** [comment] 2020-01-03 20:09
Since rubber wood is oredicted that happend. I add circuit to rubber wood recipe and let the other recuipes without a circuit.

**Comment by TataTawa** [comment] 2020-03-02 18:16
https://github.com/GTNewHorizons/GT5-Unofficial/commit/2e392e49d87732c9e9e64b737722375f725114a7

The recipe is wrong, I can centrifuge rubber wood without circuit, and can get a circuit each time.

**Comment by Dream-Master** [comment] 2020-03-02 18:29
ok will fix

**Comment by Dream-Master** [comment] 2020-03-02 19:22
fixed

**Comment by 0lafe** [comment] 2020-03-17 14:36
Trying this in 2.0.8.7 I can't get the items to output. Ran it with and without a circuit and each time it just runs the methane only recipe

**Comment by ponenerve** [comment] 2020-04-23 18:51
same here on 2.0.8.8 the issue is still there

**Comment by Methes** [comment] 2020-05-31 12:14
Could the recipe without circuit (Methane product only) be removed so that the regular recipe works again? Ideally without a circuit? There's absolutely no point to keep the methane only recipe and having the regular one with a circuit.

**Comment by 0lafe** [comment] 2020-05-31 20:46
We could try disabling it in the core mod right?

**Comment by Dream-Master** [comment] 2020-05-31 20:48
i thought this was fixed long time ago

**Comment by chochem** [comment] 2020-05-31 20:53
test on beta3: NEI shows two recipes. one with circuit on 1 for methane+items, one without circuit for methane only.

which recipe I get when using the circuit seems to depend on the order in which I put circuit and rubber wood inside.

**Comment by chochem** [comment] 2020-06-11 00:56
can we reopen this? still not fixed in 9.0 QF2, only the circuit is a 2 now.

![image](https://user-images.githubusercontent.com/40274384/84333093-a034be80-ab86-11ea-8a2e-057122367040.png)
![image](https://user-images.githubusercontent.com/40274384/84333100-a7f46300-ab86-11ea-86d5-c019ad2269c1.png)

**Comment by ScriptedPiky** [comment] 2020-06-11 01:02
I don't get why we have the rubberwood into Methane as a recipe in the first place unless it was added within GT++, then I will consult with Alk about it and see if they have anything about that recipe.

**Comment by chochem** [comment] 2020-06-11 01:03
the methane only recipe exists for all wood types

**Comment by Dream-Master** [comment] 2020-06-11 01:24
i try it to fix but I guess it is another mod. it can't be gt because I add circuit 1 to the wood to methane recipes

**Comment by j2ghz** [comment] 2020-06-27 21:09
The bug is still present on 2.0.9.0QF4

**Comment by Prometheus0000** [comment] 2020-10-19 19:57
This isn't fixed on 2.0.9.1a dev, why did you close it? Maybe add a circuit to the non-rubber wood one too.

**Comment by Dream-Master** [comment] 2020-10-20 06:28
I add circuits allready but it won't work. Idk why

**Comment by ekzoi** [comment] 2020-10-21 11:44
To all who still can't get this recipe to work, what worked for me was breaking the centrifuge, placing it down again and putting inside first the circuit inside the left input slot, then the rubber wood in the right one. This should make the machine detect the correct recipe first. If the non-circuit recipe has already been active inside the centrifuge it will not work (needs to be placed down again).

**Comment by Dream-Master** [comment] 2020-10-21 14:10
i dont get it which mod add the circuit less recipe

**Comment by Dream-Master** [comment] 2020-10-21 14:10
it's not gt

**Comment by GeicowithaBango** [comment] 2020-10-21 14:10
perhaps gt++?

**Comment by ScriptedPiky** [comment] 2020-10-21 20:54
If I recall, this is a result of GT++ either trying to make Rubber Wood output Methane gas when there was a bug at the time or trying to make *all* wood types output Methane.

**Closed** 2021-06-25 16:23 UTC
Labels: Mod: GT++, Status: FixedInDev, Type: bugMinor, Type: recipe change
